### ISSUE TITLE
最新版本每次打开游戏都要重新勾选吗？

### ISSUE THREAD

**Issue by vexling201515** [HIllya51/LunaTranslator#100]
老版本一个游戏只要hook过一次，下一次打开后回自动翻译。
1.34.5版本为什么每次打开游戏都要重新勾选？
![image](https://user-images.githubusercontent.com/94334363/207223002-b8fb0510-4f97-48d5-aef7-8ed891a2500f.png)
移除非选定hook已经取消

**Comment by HIllya51** [comment]
测试未发现你说的问题。可能是游戏每次重开地址发生变化了。
