### ISSUE TITLE
我想要自动“显示”特殊码以HB-1C开头的hook

### ISSUE THREAD

**Issue by Stillily** [HIllya51/LunaTranslator#1001]
### Question 问题

游戏中我发现场景切换时的hook的特殊码会变
比如图中两个以HB-1C@C8004:RealLiveEn.exe为开头的hook，下面那个是场景切换后新出现的，这样我就时不时需要点击“显示”按钮，我想让这种hook自动显示，我能自己改代码，能告诉我在哪个部分吗？在探测到新hook时判定一下字符串应该就够了
![图片_20240816123053](https://github.com/user-attachments/assets/fb95064d-4fd2-4739-af94-040ff5bb37bd)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/LunaTranslator/textsource/texthook.py#L422
https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/LunaTranslator/textsource/texthook.py#L544
这两个地方都可以

**Comment by Stillily** [comment]
好快的回，我改成功了，感谢
