### ISSUE TITLE
历史翻译问题

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaTranslator#1002]
### Question 问题

![QQ20240816-132718](https://github.com/user-attachments/assets/a5322ea6-b664-4c3e-8e38-c28c999ee228)
只能显示百度的，其他两种翻译源不显示，而且“重新翻译”功能疑似失效

**Comment by HIllya51** [comment]
![屏幕截图 2024-08-16 133251](https://github.com/user-attachments/assets/b34e9c05-f129-4274-acfc-1eee1d2d6245)
没失效啊。config发我看看？

**Comment by qscasdasd** [comment]
> ![屏幕截图 2024-08-16 133251](https://private-user-images.githubusercontent.com/101191390/358479433-b34e9c05-f129-4274-acfc-1eee1d2d6245.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODc5MzEsIm5iZiI6MTcyMzc4NzYzMSwicGF0aCI6Ii8xMDExOTEzOTAvMzU4NDc5NDMzLWIzNGU5YzA1LWYxMjktNDI3NC1hY2ZjLTFlZWUxZDJkNjI0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNTUzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTkwZWFhMDc3MDQxNmFiYTdhNTE4M2U1MTA2ZTFlMzgwMmMwNzgwNDJkYTBlNWUxNjhmYjQ5MGZlMDdlMTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EI4kl6PohA6tNzTRbrXOUKyACtypwfiCznTrx6FFdeo) 没失效啊。config发我看看？

userconfig吗？https://mega.nz/file/BW0EWAwB#vxKV2x2g6qQqCK9VyC_FaPYX2wbRbVT3OTSoSIndBXI

**Comment by HIllya51** [comment]
修复了
