### ISSUE TITLE
关于游戏设置中“自动切换到模式”的一些问题和功能请求

### ISSUE THREAD

**Issue by chlbc** [HIllya51/LunaTranslator#1003]
### Question 问题

您好，想询问大佬一些问题，
以及一些希望您能考虑添加的功能：
1. 在设置为 Hook 模式，
并在游戏设置中设置“自动切换到模式”到“OCR”或“剪贴板”时，
在游戏管理中启动游戏后，
会发生同时开启两个模式（Hook 与 OCR / 剪贴板）的情况，
不太确定这种情况是否正常
![image](https://github.com/user-attachments/assets/49d5d159-dac7-4064-8119-20a4b5eb9096)

2. 希望游戏设置的“自动切换到模式”除了在游戏管理中启动游戏时可以应用之外，
在检测到游戏启动时也可以自动切换；
如果可以的话也希望能在游戏关闭、或是关闭并重新启动 LunaTranslator 后，切换回原本的模式
3. 希望“自动切换到模式”中可以添加一个“无（仅绑定窗口）”的模式，
在该模式中，不会读入游戏的文本，
而是只用绑定窗口实现窗口缩放等功能。
（有点像是 Hook 模式，但是不会主动弹出选择文本的窗口）
因为在游玩一些有官中或已汉化的游戏时，
会想要只使用 Luna 的游戏管理、或是一些像是窗口缩放之类的功能，
而不想要对其文本翻译

**Comment by HIllya51** [comment]
1. 其实我有点想把这个东西删掉，因为这个基本没有人使用，没有太大的的意义，且意义令人迷惑。
2. 进行这样的切换是非常复杂的，要考虑非常非常多的情况（比如游戏未关闭时手动切换），因此太难弄了。
3. emmm 没什么必要吧，就手动绑定一下窗口并不是什么复杂的操作。

**Comment by chlbc** [comment]
了解。那能否考虑改成在个别游戏设置里加一个选项「不自动显示选择文本窗口」呢
就是在 Hook 模式检测到某个游戏启动后，
如果该游戏的这个选项已激活，
就算没有任何 Hook 的文本，也不会出现选择文本的窗口，
这样在那些不需要翻译的汉化游戏使用时也比较方便些

**Comment by HIllya51** [comment]
这个设置太令人迷惑，不想在UI里面专门为此添加。
你可以手动在savegamedata_5.3.1.json里面，为当前项目添加一个无效的项来使其不显示。
就像这样："embedablehook": [[0, 0, 0, 0]]

**Comment by chlbc** [comment]
> 这个设置太令人迷惑，不想在UI里面专门为此添加。

好的，
原本是想说会不会也有其他用户有相同的需求，
因为目前的 Hook 模式就会自动检测并绑定窗口了，
对于不用翻译的游戏而言只要再不会自动弹出选择文本窗口就很方便了。

总之我会这样试试的！感谢大佬的回复~~
