### ISSUE TITLE
Text Not Automatically Sent to ChatGPT in Latest LunaTranslator Version - Regression Bug

### ISSUE THREAD

**Issue by Figurecollection** [HIllya51/LunaTranslator#1004]
### Version 程序版本

5.28.1 64bit

### OS version and bits 系统版本和位数

windows 11 23h2 64 bit

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/798f89b7-f0df-47ff-911a-6cb78aec0c5d)

### Reproduction steps 复现步骤

I've encountered a bug when using the ChatGPT large model in browser debug mode that wasn't present in an earlier version of LunaTranslator. With the latest version, the text is automatically written into the ChatGPT input field but isn't sent. However, if I manually send the text using the mouse, the translated text appears in LunaTranslator.

In a previous version of the program, the text was also sent automatically. It seems that a bug has been introduced with the new version of the software.

### Log files 日志文件

[2024-08-16-15-09-15.txt](https://github.com/user-attachments/files/16637432/2024-08-16-15-09-15.txt)

**Comment by HIllya51** [comment]
fixed.
it is because chatgpt's button's css-selector has changed
