### ISSUE TITLE
关于文本编辑的弹窗

### ISSUE THREAD

**Issue by k2250761** [HIllya51/LunaTranslator#1005]
### Expected behavior 预期的功能

![image](https://github.com/user-attachments/assets/02331df9-a012-4daa-8078-5873015f95db)
这个点击后弹出的游戏文本编辑框能否增加窗口坐标的记忆功能，现在是跟随软件设置框，因为设置框要时常挂在另一个屏幕，方便一些操作，但是每次需要编辑文本时点击按钮弹出的编辑框都在另一个屏幕，要拉回主屏幕操作很繁琐，如果不麻烦希望所有编辑框能增加窗口记忆功能

**Comment by HIllya51** [comment]
这个非常麻烦，涉及到最基本的一些东西。。。
而且即使能做到也不会这样做，因为这并不是一个常见的需求，而且这样改反而会让没有这种需要的人（我）感觉不方便
既然设置框要常挂在其他地方，那把这个编辑框也挂在指定地方不关闭不就好了，这又不是一个模态窗口。。

**Comment by k2250761** [comment]
了解

**Comment by HIllya51** [comment]
不过可以把按钮弹窗显示到翻译框的位置

**Comment by HIllya51** [comment]
显示到设置窗口的位置确实有点不太合适

**Comment by HIllya51** [comment]
我想了个点子，可以实现了

**Comment by HIllya51** [comment]
所有通过主界面按钮打开的窗口，都会在本次运行期间记录位置了，下次启动后恢复默认

**Comment by HIllya51** [comment]
所有通过主界面按钮打开的窗口，都会在本次运行期间记录位置了，下次启动后恢复默认

**Comment by k2250761** [comment]
> 所有通过主界面按钮打开的窗口，都会在本次运行期间记录位置了，下次启动后恢复默认

非常感谢
