### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Yuriuori** [HIllya51/LunaTranslator#1006]
### Version 程序版本

v5.28.3

### OS version and bits 系统版本和位数

Windows 11

### bug's screenshot 错误截图

Geeting this Error when Luna hook is active for some reason 
![image](https://github.com/user-attachments/assets/046595e3-8492-4ab4-bfd0-b6675c97ab06)

### Reproduction steps 复现步骤

It always happen when different scene happen or when the background change

### Log files 日志文件

.

**Comment by HIllya51** [comment]
I have been fairly confident from experience that this error is caused by not using the correct locale.
https://github.com/xupefei/Locale-Emulator
