### ISSUE TITLE
Can you please bring back this feature?

### ISSUE THREAD

**Issue by gqwg2003** [HIllya51/LunaTranslator#1007]
### Expected behavior 预期的功能

Can you please bring back this feature?  

![Снимок экрана 2024-08-18 065309](https://github.com/user-attachments/assets/9c170d47-347d-42fd-b20c-9147f3d63b19)
![Снимок экрана 2024-08-18 065511](https://github.com/user-attachments/assets/db686224-430b-4028-b005-3bf5d9b5c19a)
![Снимок экрана 2024-08-18 065540](https://github.com/user-attachments/assets/a82f718a-2baa-4d94-a1a1-14b4e5274450)

### Alternative behavior (optional) 近似的功能（可选）

If you are reading this, thank you very much for reading.

**Comment by HIllya51** [comment]
After careful testing, these preprocessing methods will only make the recognition effect worse rather than better.
Therefore, it is impossible to bring them back.
