### ISSUE TITLE
Translation error using Gemini

### ISSUE THREAD

**Issue by NONAMEHP** [HIllya51/LunaTranslator#1008]
### Version 程序版本

v5.28.3

### OS version and bits 系统版本和位数

Windows 11

### bug's screenshot 错误截图

![Screenshot 2024-08-18 114035](https://github.com/user-attachments/assets/0d2b78e1-23a2-42db-b6e9-b390a7d58acd)

### Reproduction steps 复现步骤

Since I updated Luna to the new version, I've been using gemini to translate and every few texts I get this error. Can you guide me to fix it? I'm sorry for my bad English.  Tsuki no Kanata de Aimashou
https://vndb.org/v24803

### Log files 日志文件

[2024-08-18-11-52-19.txt](https://github.com/user-attachments/files/16647233/2024-08-18-11-52-19.txt)

**Comment by HIllya51** [comment]
cancel streaming output
![屏幕截图 2024-08-18 161433](https://github.com/user-attachments/assets/de4374f2-cc3d-4600-bcf9-bcff0833533a)
