### ISSUE TITLE
Ability to Set Specific OCR Region without automated execution, Shortcuts for manual OCR Execution and Use Controller Buttons as Shortcuts

### ISSUE THREAD

**Issue by Figurecollection** [HIllya51/LunaTranslator#1009]
### Expected behavior 预期的功能

I would like to ask if it's possible to add the option to set a specific OCR Region in LunaTranslator without using automated execution. For example, I use the "Perform OCR" shortcut key to translate different OCR Regions on my game screen, as I play JRPGs. However, sometimes it would be useful to set a specific OCR Region and activate it only via a shortcut, without relying on automated execution.

Additionally, I would like to know if it's possible to add controller buttons as shortcuts. I know other programs that allow you to select an OCR Region and then perform OCR only in the chosen area when you press the right analog stick (or other buttons) on the controller.
Thanks in advance for your answer!

**Comment by HIllya51** [comment]
https://docs.lunatranslator.org/#/zh/alltoolbuttons?id=-%e8%bf%9b%e8%a1%8c%e4%b8%80%e6%ac%a1ocr

**Comment by Figurecollection** [comment]
> https://docs.lunatranslator.org/#/zh/alltoolbuttons?id=-%e8%bf%9b%e8%a1%8c%e4%b8%80%e6%ac%a1ocr

我的意图是另有所指。因此，我不希望每次文本更改时都自动激活OCR，而只是设置OCR间隔。然后，通过程序的快捷方式执行OCR。

**Comment by Figurecollection** [comment]
在视觉小说中，自动执行OCR模式是可行的，因为视觉小说是静态的视频游戏。然而，在如JRPG这样的游戏中，游戏场景非常活跃，所以存在即使没有文本需要翻译也不断执行OCR的风险。虽然程序中有“进行一次OCR”的功能，但保存OCR间隔然后仅在保存的间隔内通过快捷方式执行OCR也不失为一个好方法。

**Comment by HIllya51** [comment]
这是玩galgame的软件，rpg不是首要考虑的目标

**Comment by Figurecollection** [comment]
> 这是玩galgame的软件，rpg不是首要考虑的目标

例如，我在使用LunaTranslator玩JRPG时，会使用Hook模式来找到文本，我本不介意增加一个方便玩JRPG的OCR模式功能。此外，我甚至能够玩像《如龙》这样的游戏，因为通过hook我能获取到文本。还有其他程序只能通过快捷方式启动OCR，但我觉得LunaTranslator比这些程序更好，所以我很希望能增加这样的功能。最后，感谢您抽时间回答我的问题，希望将来您有时间和意愿时，能在未来的程序更新中加入我之前提出的这项功能。祝您有美好的一天！

**Comment by Figurecollection** [comment]
存在一个名为VNTranslator的程序，它主要是为galgame设计的，但它仍然具有只设置OCR区域然后通过快捷方式执行OCR的功能。

**Comment by HIllya51** [comment]
新增了一个按钮以实现这件事

**Comment by Figurecollection** [comment]
> 新增了一个按钮以实现这件事

非常感谢您为软件增加了这项功能。我已经通过“再次进行OCR”按钮进行了测试，一切运行得很完美。但是，我注意到“再次进行OCR”的功能并未出现在程序的快捷键列表中，如果能将“再次进行OCR”按钮的功能也添加到快捷键中将会更加方便。
