### ISSUE TITLE
v1.34.6 问题

### ISSUE THREAD

**Issue by ssincxv** [HIllya51/LunaTranslator#101]
似乎只有百度api能够使用，其它api无法正常使用

**Comment by ssincxv** [comment]
老版本没有问题

**Comment by ssincxv** [comment]
解决了

**Comment by ssincxv** [comment]
全删了重下了好了

**Comment by HIllya51** [comment]
大部分翻译器不兼容自动检测。

**Comment by ssincxv** [comment]
还有一个能不能同时使用多个ocr窗口和textractor，比如很多gal有选项，让多个窗口的ocr来跑选项，因为选项的位置大多固定，普通的对话用textractor来跑

**Comment by ssincxv** [comment]
我尝试了VNR的共享辞书，发现目前如果用火山的api，并不太适合辞书了，火山翻译已经很准了，只差些专有名词，在专有名字翻译哪里能增加一个导出专有名词么，方便整理出来

**Comment by HIllya51** [comment]
> 还有一个能不能同时使用多个ocr窗口和textractor，比如很多gal有选项，让多个窗口的ocr来跑选项，因为选项的位置大多固定，普通的对话用textractor来跑

可以多开

**Comment by HIllya51** [comment]
> 我尝试了VNR的共享辞书，发现目前如果用火山的api，并不太适合辞书了，火山翻译已经很准了，只差些专有名词，在专有名字翻译哪里能增加一个导出导入专有名词么

什么意思，没明白。

**Comment by ssincxv** [comment]
增加专有名字的导出和导入，目前只能软件里修改，如果词条多了不好管理

**Comment by HIllya51** [comment]
直接改userconfig/noundictconfig.json就行了。
