### ISSUE TITLE
Translation of automatically print-screened game window

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#1010]
### Question 问题

Good day. I know there is a function in Luna which allows to see image of captured game screen in Luna window with translated text instead of original text. Unfortunately still I have not figured out how to use it. Perhaps it's Clipboard regime. I tried to switch on Clipboard and  didn't manage this thing to work.
I have emulator window and somehow second Luna window must open with image of emulator screen and translated text. Something like that on picture below. Its example from another program, but I believe Luna can perform the same function. 
How to achieve it?

![transabove](https://github.com/user-attachments/assets/c203e12f-a45e-483b-ba34-3683075c30ab)
![transabove2](https://github.com/user-attachments/assets/da28cafc-1a26-4273-9504-4a97fa9b5285)

**Comment by HIllya51** [comment]
You know wrong, there's no such thing

**Comment by Farooq87** [comment]
> You know wrong, there's no such thing

@HIllya51 
Is it possible to add such functionality in future?

**Comment by HIllya51** [comment]
never.

**Comment by Farooq87** [comment]
> never.

Well, thanks for clarification
