### ISSUE TITLE
can you make a similar function for photo processing? what is described below

### ISSUE THREAD

**Issue by gqwg2003** [HIllya51/LunaTranslator#1011]
### Expected behavior 预期的功能

I need a photo processing function so that normal text can be read on some background on a bad background a too bright a too dark a color  but on a too bright background we start to read the text poorly, and on a colored background it starts to be like 50 to 50 some words I can read, but some I can't count using OCR   Can you please add this feature?

### Alternative behavior (optional) 近似的功能（可选）

Thank you very much for answering all the messages that I write to you, I am very grateful to you

**Comment by HIllya51** [comment]
cant understand

**Comment by gqwg2003** [comment]
can you add a photo processing app

**Comment by gqwg2003** [comment]
like post-processing only slightly improved

**Comment by gqwg2003** [comment]
so that all the gamma functions are displayed and you can adjust the brightness of the tone and everything else

**Comment by HIllya51** [comment]
Do these things have anything to do with this software? 😅

**Comment by gqwg2003** [comment]
yes, it has very strong some photos need to be processed so that the text can be scanned
