### ISSUE TITLE
DeepLX connection failed

### ISSUE THREAD

**Issue by linakima** [HIllya51/LunaTranslator#1012]
### Version 程序版本

v5.28.4 64bit

### OS version and bits 系统版本和位数

Windows 10 x64

### bug's screenshot 错误截图

![1](https://github.com/user-attachments/assets/c268a60f-ad5e-41d3-98fc-bf1e1f04c500)
![2](https://github.com/user-attachments/assets/69a9e7ae-f072-4ab3-8921-999f435d9f75)

### Reproduction steps 复现步骤

https://github.com/OwO-Network/DeepLX/releases/tag/v0.9.5
Downloaded the deeplx_windows_386.exe, v0.9.5 application.
Started deeplx_windows_386.exe
Enabled Deeplx in LunaTranslator settings changed the address to 0.0.0.0.0:1188, got an error.
If return 127.0.0.0.0:1188, no error and no translation.
If start deeplx_windows_amd64.exe, nothing changes.

### Log files 日志文件

[logs.zip](https://github.com/user-attachments/files/16649172/logs.zip)

**Comment by HIllya51** [comment]
http://127.0.0.1:1188/translate

**Comment by HIllya51** [comment]
Do not arbitrarily modify the default values. If it doesn't work, it's your own problem.
