### ISSUE TITLE
RPG maker, text wrapping

### ISSUE THREAD

**Issue by linakima** [HIllya51/LunaTranslator#1013]
### Question 问题

Hi there! Thank you for the amazing tool. I'm interested in using your tool for RPG Maker games. Is it possible to somehow implement automatic line breaks after N characters for embedded translation?

**Comment by HIllya51** [comment]
see document https://docs.lunatranslator.org/#/zh/embedtranslate

**Comment by linakima** [comment]
I found the function 'Limit Number of Words per Line'. It inserts a line break between characters. 
Is it possible to insert this line break between words, so that the word is not divided into parts?
