### ISSUE TITLE
you can add a text translation function if there are English and Chinese characters in one line so that they are automatically identified and translated

### ISSUE THREAD

**Issue by gqwg2003** [HIllya51/LunaTranslator#1014]
### Expected behavior 预期的功能

you can add a text translation function if there are English and Chinese characters in one line so that they are automatically identified and translated  and I have another request, is it possible to add a language detection function, I have situations when I don’t know what language the text is written in

### Alternative behavior (optional) 近似的功能（可选）

Thank you very much in advance for reading and Yes I support you with both hands for you to continue this project I am very-very-very grateful to you the application is a bomb

**Comment by HIllya51** [comment]
Detecting the language will only waste extra time, the language of the game should be determined by you.
