### ISSUE TITLE
Translation Request

### ISSUE THREAD

**Issue by Yuriuori** [HIllya51/LunaTranslator#1015]
### Expected behavior 预期的功能

Hello, Can you please add X AI GROK (Twitter)  to the Browser Debug
Soon they will release API Too so i was hoping to add it to LunaTranslator

**Comment by HIllya51** [comment]
no. i don't have account.

**Comment by Yuriuori** [comment]
@HIllya51 I can give you my account to test it out can i send it to you in discord ?

**Comment by HIllya51** [comment]
Maybe there is something wrong with my IP address, many accounts have been banned by X.
