### ISSUE TITLE
Bro Chizh, add the functions of submitting a transfer request to. Offline translator in the emulator. 

### ISSUE THREAD

**Issue by gqwg2003** [HIllya51/LunaTranslator#1017]
### Expected behavior 预期的功能
from any language to another language translation completely offline
 LunaTranslator  From that app. To the emulator of the offline translation application.
Add a request function. To the emulator. For translation.
I'm begging you, I finally found how to translate offline.   I beg you very much.  
![Снимок экрана 2024-08-22 035323](https://github.com/user-attachments/assets/472ec6fa-116d-4f5f-b525-116ea16567c3)
![Снимок экрана 2024-08-22 035351](https://github.com/user-attachments/assets/c6d80f27-12fd-482c-8df4-21d2359aa9e6)
![Снимок экрана 2024-08-22 035534](https://github.com/user-attachments/assets/c4fb8677-018b-4a04-a15e-c7792d5ae923)

### Alternative behavior (optional) 近似的功能（可选）

And yes, thank you so much for reading it.

**Comment by HIllya51** [comment]
😅
