### ISSUE TITLE
目标语言为中文时，自动加载中文人名进专有名词翻译的可能提案

### ISSUE THREAD

**Issue by chlbc** [HIllya51/LunaTranslator#1018]
### Expected behavior 预期的功能

当前版本会自动从 VNDB 加载日、英文人名，
然而对于中文用户而言可能没那么方便，
因此尝试提出以下方案，
或许大佬可以考虑看看。

### 一、直接从 Bangumi 取得日文、简体人名
繁体再額外做简繁转换
（优点：较准确）
（缺点：只能拿到角色全名，较不实用）

### 二、直接从 VNDB 日文人名转中文之可能的处理方式提议
1. 以空格、中点（· / ‧ / ．）、片假名中点（・ / ･）、假名连字号（゠ / ＝ / = / ⹀）作分隔符，
将日文全名分成数个 Token 分别处理，
并记录每个分隔符
2. 若 Token 全部都是汉字，则直接做简繁转换
（如果有日本汉字转假名的词典会更好）
3. 若 Token 中只有汉字、の、ノ、ヶ、々，
则将 の、ノ 替换为“之”，
将 ヶ 直接删掉，
将 々 替换为其前面的汉字
4. 若 Token 中含有其他假名或英文，
则将其丢给谷歌_v2、百度等支持自动检测来源语言的翻译
（或直接使用来源语言设置，而不自动检测）
（可创建一个翻译器顺序列表，或由用户指定）
5. 按照当时纪录的分隔符，组合回全名，
并将 Token 和全名去重后放入专有名词：
   1. 如果是空格，则加空格
   2. 如果是中点、片假名中点或假名连字号，则
   简体中文加 ·（U+00B7）；
   繁体中文加 ‧（U+2027）

### 其他附加提议
1. 建议中文词条的添加位置由直接替换改为占位符
（因为除了 Sakura 等少数例外之外，
中文词条若使用直接替换，
多数还是会被二度转换，导致结果与词条不符）
2. 建议词条可一并加入 sakura gpt 词典内
3. 建议可根据 VNDB 或 Bangumi 中的人物性别，
在 sakura gpt 词典的注释中加入“男性”、“女性”

### Alternative behavior (optional) 近似的功能（可选）

专有名词翻译、加载元数据、简繁转换

**Comment by HIllya51** [comment]
太麻烦，没兴趣弄。改成仅英语才加载这个玩意儿了

**Comment by chlbc** [comment]
了解，不过加载日文原文人名的话，感觉对于会自建词条的用户而言也会比较方便
或许可以考虑在游戏设置的元数据页面弄个“从 VNDB 加载原文人名”的按钮或选项？
就不加载英文，只加载日文原文这样

**Comment by HIllya51** [comment]
就是改成这样了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月22日(周四) 下午4:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HIllya51/LunaTranslator] 目标语言为中文时，自动加载中文人名进专有名词翻译的可能提案 (Issue #1018)




 
了解，不过加载日文原文人名的话，感觉对于会自建词条的用户而言也会比较方便
 或许可以考虑在游戏设置的元数据页面弄个“从 VNDB 加载原文人名”的按钮或选项？
 就不加载英文，只加载日文原文这样

**Comment by chlbc** [comment]
了解，虽然若能自动添加中文词条应该会更方便，
不过这样改也确实比以前好些。

不过对于欧美用户（俄、法等）而言，
感觉还是可以使用英文词条？
不用英文词条的大概只有简体中文和繁体中文而已（韩文不确定）

**Comment by HIllya51** [comment]
就是这样的。。。

**Comment by chlbc** [comment]
> 就是这样的。。。

不好意思，
我这边没有很确定大佬指的是“已经改成欧美语言（俄、西、法等）都会加载英文人名”
还是“已经决定改成只有英文会加载英文人名”。

因为根据我这边的印象，
日文轻小说就算翻成西班牙语，
人名好像也还是会保持英文名居多。

而当前 Luna 是改成[只有目标语言是英文时才会加载英文人名](https://github.com/HIllya51/LunaTranslator/blob/b73c62f1aae1ecd2ca7e65565ece3347e966b1c5/LunaTranslator/LunaTranslator/metadata/abstract.py#L184)，
因此才会提出改成“只有日文、简体、繁体加载日文原名，其他语言加载英文人名”的建议。

![image](https://github.com/user-attachments/assets/d624049b-59ec-4971-9796-66372f943a43)

P.S. 话说从上面那张截图中，意外发现 UI 在某些语言上，似乎有跑版的情况，要额外把窗口拉大才正常

**Comment by HIllya51** [comment]
> > 就是这样的。。。
> 
> 不好意思， 我这边没有很确定大佬指的是“已经改成欧美语言（俄、西、法等）都会加载英文人名” 还是“已经决定改成只有英文会加载英文人名”。
> 
> 因为根据我这边的印象， 日文轻小说就算翻成西班牙语， 人名好像也还是会保持英文名居多。
> 
> 而当前 Luna 是改成[只有目标语言是英文时才会加载英文人名](https://github.com/HIllya51/LunaTranslator/blob/b73c62f1aae1ecd2ca7e65565ece3347e966b1c5/LunaTranslator/LunaTranslator/metadata/abstract.py#L184)， 因此才会提出改成“只有日文、简体、繁体加载日文原名，其他语言加载英文人名”的建议。

无所谓，管他呢。

> 
> ![image](https://private-user-images.githubusercontent.com/42777336/360799750-d624049b-59ec-4971-9796-66372f943a43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTI0MjksIm5iZiI6MTcyNDM5MjEyOSwicGF0aCI6Ii80Mjc3NzMzNi8zNjA3OTk3NTAtZDYyNDA0OWItNTllYy00OTcxLTk3OTYtNjYzNzJmOTQzYTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA1NDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNWExNjU2MjU3MDJlYTY2ODhiOThmOTYyZDczOWUwYmMzMjkwODE3N2FlM2E4ZDM4MzY4NWU4M2NkNmE0ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hbjPA941aMyCWCzhm8mGrRCZGed8jehBu9zWCT0jXfo)
> 
> P.S. 话说从上面那张截图中，意外发现 UI 在某些语言上，似乎有跑版的情况，要额外把窗口拉大才正常

不这样的话，窗口得多大啊。。。我可没兴趣为这些小语种专门改UI。

**Comment by chlbc** [comment]
了解www
