### ISSUE TITLE
与 https://fish.audio/zh-CN/   tts 集成

### ISSUE THREAD

**Issue by fastfading** [HIllya51/LunaTranslator#1019]
### Expected behavior 预期的功能

与 https://fish.audio/zh-CN/   tts 集成
这个包含了大量ai语音模型，
简单实用， 唯一缺点， 花点小钱

api https://notion.fish.audio/APIs-2afdd0529d72479e96834df114c16274

**Comment by fastfading** [comment]
最好能加上    语音reference_id  与角色名映射设置

**Comment by HIllya51** [comment]
怎么用啊

**Comment by fastfading** [comment]
demo  
https://fish.audio/zh-CN/text-to-speech/?modelId=5196af35f6ff4a0dbf541793fc9f2157

api
https://notion.fish.audio/APIs-2afdd0529d72479e96834df114c16274

在游戏中自动生成角色列表，  然后手动设置一个 referenceid  
比如  trump   =   5196af35f6ff4a0dbf541793fc9f2157

**Comment by HIllya51** [comment]
给我一个有用的文档。

**Comment by fastfading** [comment]
https://notion.fish.audio/APIs-2afdd0529d72479e96834df114c16274  
这个就是啊 
里面代码都有

**Comment by HIllya51** [comment]
这玩意儿跑不起来。

**Comment by HIllya51** [comment]
![屏幕截图 2024-08-23 133708](https://github.com/user-attachments/assets/899f0cdd-5959-4cc3-a640-72f966653db8)

**Comment by HIllya51** [comment]
我不知道你说得是什么意思，我没用过这玩意儿，也完全不懂你说的什么referenceid是干什么的。

**Comment by fastfading** [comment]
referenceid  是表示 使用哪个角色语音。  
api 这里需要设置 参考音频

   references=[
        ServeReferenceAudio(
            audio=open("lengyue.wav", "rb").read(),
            text="Text in reference AUDIO",
        )
    ],
这个有点麻烦， 还需要音频数据集。  一时半会还搞不定， 看来。

**Comment by fastfading** [comment]
https://github.com/fishaudio/fish-speech/issues/495

depend on fish-speech  improvement

**Comment by HIllya51** [comment]
用[tetos](https://github.com/frostming/tetos)跑起来了。试了以下，随便给了一个短句跑了快二十秒才出，速度也太慢了吧。

**Comment by fastfading** [comment]
的确是慢，  还是用我的gpt-sovits v2 吧
