### ISSUE TITLE
Can you create a setting for each translator that only translates when I press the retranslate menu? 

### ISSUE THREAD

**Issue by onedayakub** [HIllya51/LunaTranslator#1020]
### Expected behavior 预期的功能

Some online translators are blocked when there are a lot of requests. Can you create a setting for each translator that only translates when I press the retranslate menu? 

It would be efficient to auto translate to a low-latency offline translator in normal cases and then retranslate only when there are strange translations to compare.

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/issues/257

add a key "manual" in config.json by yourself.
