### ISSUE TITLE
you can add yandex.ocr

### ISSUE THREAD

**Issue by gqwg2003** [HIllya51/LunaTranslator#1021]
### Expected behavior 预期的功能

you can add yandex.ocr  Yandex's advantages OCR recognizes Russian letters well I'm happy it works quickly 

### Alternative behavior (optional) 近似的功能（可选）

Thank you very much for reading

**Comment by HIllya51** [comment]
give me doc and key

**Comment by gqwg2003** [comment]
What kind of document is this? And what kind of key is this?

**Comment by HIllya51** [comment]
You should tell me how to use this thing.

**Comment by gqwg2003** [comment]
you need an access key and an explanation of how it works. got it right. i'll tell you right away - i have neither.   

by the way I apologize in advance for wasting your time I realized that it was a stupid idea

**Comment by HIllya51** [comment]
。。。
