### ISSUE TITLE
Theb.ai makes Luna performance slow when streaming output is on

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#1022]
### Version 程序版本

5.30.6

### OS version and bits 系统版本和位数

Windows 10 64-bit

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/938eaa73-007b-4e78-9e9b-7802f7122755)

Luna begins work very slow and freezes when theb.ai is opened in browser window and streams its translation to Luna window.
As soon as I switch off streaming output performance improves. Could you please fix it?
I hardly can move OCR region area and select new one. Other opened applications such as browser and game perform well

### Reproduction steps 复现步骤

Perform OCR - Output is streaming from theb window to Luna - Luna performance slows down: I can't move Luna window flawlessly and selection of new OCR area is sluggish

### Log files 日志文件

[2024-08-25-03-10-49.txt](https://github.com/user-attachments/files/16738438/2024-08-25-03-10-49.txt)

**Comment by HIllya51** [comment]
I can't reproduce this problem. It may be a problem with your computer.
And then, it is not recommended to use OCR+debug browser translation, because there are a lot of cheap APIs available.

**Comment by HIllya51** [comment]
Even https://groq.com/ is free. So using the debug browser translation is completely pointless. I also don't want to maintain debug browser translation anymore.

**Comment by Farooq87** [comment]
@HIllya51 
Reason to use Browser debug is huge. For example for me it is possibility to gain access in Luna to such AI as ChatGPT and Claude 3 for free. Both of very good quality in translation and both demand paid subscription if online API with a key. They also demand using VPN for such country as Russia. So debug browser is perfect solution and helps a lot. It is salvation. Don't abandon it, HIllya.
It is really of great assistance to poor folks or those ones who can't afford good quality VPNs

**Comment by Farooq87** [comment]
@HIllya51 ,
Thank you, my friend
Theb works just fine with good performance/speed of Luna window now.  
And thanks for Duck Duck Go interface. Very useful too.
