### ISSUE TITLE
can you add a function so that OCR copies text to the clipboard 

### ISSUE THREAD

**Issue by gqwg2003** [HIllya51/LunaTranslator#1023]
### Expected behavior 预期的功能

I explain the scheme of OCR operation scanned the text and sent it to the clipboard 

### Alternative behavior (optional) 近似的功能（可选）

I guess I've already annoyed you with my questions and requests, so I apologize to you. I have a ton of ideas but no way to turn them into reality.

**Comment by HIllya51** [comment]
This is an existing feature.

**Comment by gqwg2003** [comment]
can't you tell me Yes, this function is located
