### ISSUE TITLE
I have a translator that works offline on a PC, I want you to combine it with your application, at least make it possible

### ISSUE THREAD

**Issue by gqwg2003** [HIllya51/LunaTranslator#1027]
### Expected behavior 预期的功能

I have a translator that works offline on a PC, I want you to combine it with your application, at least make it possible    the name of the application Lingvanex Translator for offline translation can translate Not perfect but offline and with support for Russian and other languages  sorry for the mistakes in the text, not to merge, but the ability to connect to the application

### Alternative behavior (optional) 近似的功能（可选）
sorry for the mistakes in the text, not to merge, but the ability to connect to the application
_No response_

**Comment by HIllya51** [comment]
`Vosk is a speech recognition toolkit`
