### ISSUE TITLE
can you add the ability to translate offline using this app description below

### ISSUE THREAD

**Issue by gqwg2003** [HIllya51/LunaTranslator#1028]
### Expected behavior 预期的功能

Please read everything carefully, if you don't read carefully, you won't be able to understand the meaning.

I apologize for the inaccuracies in some words

warning although all links and files were checked for viruses but I advise you to double check just in case for your own safety

I ask for the opportunity to interact with him for translation   add the ability to output text to this application lingvanex translator and further translation in it and then back LunaTranslator text below description

it has the ability to translate offline   Language support up to offline translation   Translation is performed without an Internet connection. It is possible to translate text on web pages, as well as translate files and documents.
Key features of the Lingvanex Translator application:     Lingvanex Translator is a modern translation application for 127 languages, with which you can translate text, voice, audio, images, web pages and documents. The translator supports the following languages: English, Arabic, Armenian, Azerbaijani, Belarusian, Chinese (Simplified), Chinese (Traditional), Croatian, Czech, Danish, French, Georgian, German, Romanian, Russian, Serbian, Spanish, Ukrainian and many others.   

link to the official website  https://lingvanex.com/

 if the link doesn't work write to me I'll send you the file  it was checked immediately and there were no viruses    link where you can download a free hacked version  https://diakov.net/14308-lingvanex-translator-pro-111390-portable.html 

 further screenshots 

![Снимок экрана 2024-08-25 225220](https://github.com/user-attachments/assets/28ba3010-1973-427d-82c0-300beb3bb4b4)
![Снимок экрана 2024-08-25 225301](https://github.com/user-attachments/assets/1e9ebe6a-29e4-4bc1-a1ae-3f8ca4da9144)
![Снимок экрана 2024-08-25 225328](https://github.com/user-attachments/assets/97904d74-d50f-436c-ac74-a16661372efa)

### Alternative behavior (optional) 近似的功能（可选）

I apologize for the inaccuracies in some words

I've probably pissed you off already, I apologize for this and thank you very much for reading and answering, I thank you very much

**Comment by HIllya51** [comment]
no.

**Comment by HIllya51** [comment]
Stop bothering me with this unrealistic stuff
