### ISSUE TITLE
optimization settings

### ISSUE THREAD

**Issue by KirpichKrasniy** [HIllya51/LunaTranslator#103]
Can you separate the filter checkboxes of English characters and numbers? so that you can turn off either English characters or numbers separately

**Comment by HIllya51** [comment]
你想多了，和这个根本没关系，纯脆是重新识别图片变了。

**Comment by HIllya51** [comment]
只过滤英语在正则表达式里面加一条[a-zA-Z]+，过滤数字加一条[0-9]+。

**Comment by KirpichKrasniy** [comment]
Got it, I passed it on. thanks

**Comment by KirpichKrasniy** [comment]
I will try to quickly make instructions for the application, because I have already been asked a lot of simple questions that are resolved quickly)))

**Comment by KirpichKrasniy** [comment]
> 只过滤英语在正则表达式里面加一条[a-zA-Z]+，过滤数字加一条[0-9]+。

due to the fact that I myself translated some of the program's functions incorrectly, I got confused in their settings xDD

I will try to describe the instructions as extensively as possible so that people have as few questions as possible

**Comment by HIllya51** [comment]
算了 我还是干脆把他俩拆开吧。

**Comment by KirpichKrasniy** [comment]
> 算了 我还是干脆把他俩拆开吧。

with the help of regular expressions, you can do anything, this is quite an extensive functionality

**Comment by KirpichKrasniy** [comment]
![image](https://user-images.githubusercontent.com/109726461/207826357-430a37a8-d49b-45a0-8e6e-7f181b2f190b.png)
sorry for the dumb question, but what does this function do?

**Comment by HIllya51** [comment]
点击这个按钮，然后点击一个窗口，那么接下来OCR只会在这个窗口内截图。

**Comment by KirpichKrasniy** [comment]
it turns out that this function allows you to capture text only from the game, without capturing the entire screen. I'm understood, thank you.

Google translator translated so badly that I didn't understand what it was all about)

![image](https://user-images.githubusercontent.com/109726461/207830374-61284c55-3c82-4c25-880a-2ead0e9a10b9.png)

**Comment by KirpichKrasniy** [comment]
is it possible to add correction using regular expressions for the translated text too?
currently available only for recognized text. I would like also for the translated

**Comment by KirpichKrasniy** [comment]
correction of English language recognition using regular expressions
purity 99%
[postprocessconfig.zip](https://github.com/HIllya51/LunaTranslator/files/10243769/postprocessconfig.zip)

**Comment by KirpichKrasniy** [comment]
https://user-images.githubusercontent.com/109726461/208053744-8c290f22-4691-471c-b2c1-63a3b12d18aa.mp4

**Comment by KirpichKrasniy** [comment]
I made a lot of dumb mistakes before, but now everything should work perfectly
