### ISSUE TITLE
增设非语音内容的朗读适配

### ISSUE THREAD

**Issue by X012C** [HIllya51/LunaTranslator#1030]
### Expected behavior 预期的功能

galgame里面有语音的角色往往不多，如果可以通过排除发音文本来避免朗读有cv的文本就好了。如果实现起来困难，还望增设快捷键来打断当前自动朗读的发音。

**Comment by HIllya51** [comment]
https://docs.lunatranslator.org/#/zh/ttsofname

**Comment by HIllya51** [comment]
右键点击按钮会中断播放
