### ISSUE TITLE
查词窗口频发性白屏闪退

### ISSUE THREAD

**Issue by X012C** [HIllya51/LunaTranslator#1031]
### Version 程序版本

最新

### OS version and bits 系统版本和位数

win11 64

### bug's screenshot 错误截图

通过原文分词点进查词界面，查词窗口白屏，触发闪退。查词不到五六次就遇到一次白屏。

### Reproduction steps 复现步骤

查词卡在白屏一会后，就闪退。

### Log files 日志文件

[2024-08-26-21-31-56.txt](https://github.com/user-attachments/files/16749238/2024-08-26-21-31-56.txt)

**Comment by HIllya51** [comment]
![8e99b9d53f8ddda03ea255051fde07e9](https://github.com/user-attachments/assets/50a56ca8-37f3-4f79-8dd6-f6cebd25ebde)

**Comment by HIllya51** [comment]
图呢。

**Comment by HIllya51** [comment]
请告诉我触发闪退时的单词，以及查词相关设置

**Comment by X012C** [comment]
> 请告诉我触发闪退时的单词，以及查词相关设置

![屏幕截图 2024-08-26 223753](https://github.com/user-attachments/assets/31e64110-0f7c-44c4-a49d-4b76a6722bec)
![image](https://github.com/user-attachments/assets/8762759e-b8ab-474c-a159-1a18b51f520e)

图太难截了，感觉没什么规律。显示引擎从其他两个设到webview2后，感觉webview2的出词速度快了，闪退从之前五六次变成了十次以上？当感觉真的没毛病的时候就果断给闪退了。

他卡住的特征就是加载稍微久一点不出来，就知道要寄了。看了很容易识别出来，他和其他应用那种没反应了的效果是差不多。

**Comment by HIllya51** [comment]
单词是什么，我看看是不是和单词有关？

**Comment by X012C** [comment]
> 请告诉我触发闪退时的单词，以及查词相关设置

还有那个用户设置保存的问题，是不是在软件退出之后才会开始保存，我感觉每次闪退都要重新设置。

**Comment by X012C** [comment]
> 单词是什么，我看看是不是和单词有关？

上面那个猎物就是卡闪退了。

**Comment by HIllya51** [comment]
你能不能用命令行打开软件，然后尝试让他闪退，然后给我看一下命令行有没有什么输出？我完全无法复现你这个问题，可能和操作系统有关。

**Comment by X012C** [comment]
> 你能不能用命令行打开软件，然后尝试让他闪退，然后给我看一下命令行有没有什么输出？我完全无法复现你这个问题，可能和操作系统有关。

debug模式闪退太快了，我没看出来他卡住之后有啥内容出来，好像都是之前常规查词内容。

**Comment by HIllya51** [comment]
我的意思是你用cmd打开，这样闪退了也能看见输出。。。

！很有可能，可能没有写入权限导致的

**Comment by X012C** [comment]
> 我的意思是你用cmd打开，这样闪退了也能看见输出。。。
> 
> ！很有可能，可能没有写入权限导致的
[cmd2024-08-26_23-30-39.txt](https://github.com/user-attachments/files/16750603/cmd2024-08-26_23-30-39.txt)

我换了位置，和重新下一份，感觉比之前闪退更快了。这是CMD里面的内容。

**Comment by HIllya51** [comment]
[usefulwidget.zip](https://github.com/user-attachments/files/16750728/usefulwidget.zip)

你替换一下这个文件：LunaTranslator\gui\usefulwidget.py， 我改了几个可能有问题的地方

**Comment by X012C** [comment]
> [usefulwidget.zip](https://github.com/user-attachments/files/16750728/usefulwidget.zip)
> 
> 你替换一下这个文件：LunaTranslator\gui\usefulwidget.py， 我改了几个可能有问题的地方

还是秒退。

**Comment by X012C** [comment]
我这边还有看到一个特别的现象就是采用游戏截图会使得原本文本乱码。
![image](https://github.com/user-attachments/assets/ea2c776c-fa5e-426e-9058-531c100c2480)
以及我的查词设置 。
![image](https://github.com/user-attachments/assets/6cc43317-53bf-4ae9-9235-29c43ee27d8c)
不知道和它们有无关联。

**Comment by HIllya51** [comment]
很迷，似乎是更底层的依赖有bug，吐了。

**Comment by HIllya51** [comment]
稳定复现。麻了。

**Comment by X012C** [comment]
> 稳定复现。麻了。

哈哈，能复现了，是不是有解决的希望？

**Comment by HIllya51** [comment]
嗯，应该吧，下个版本

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/actions/runs/10572322543/artifacts/1857982731

你下一下试试，应该可以了。

**Comment by HIllya51** [comment]
好像和自动tts有关，关了这个东西好像就没问题了

**Comment by X012C** [comment]
> 好像和自动tts有关，关了这个东西好像就没问题了

好像是，我把查词界面的设置自动TTS和例句TSS关了之后，狂点都没有卡顿闪退。不知道后面是否会出现问题，应该和这个设置有关联吧。

**Comment by X012C** [comment]
> 好像和自动tts有关，关了这个东西好像就没问题了

而且上面截图乱码的问题好像解决了，把那两个设置关了之后，截图乱码没有出现了。

**Comment by X012C** [comment]
> 截图乱码是另一个问题，我已经解决了。崩溃这个问题还是群里有个老哥帮我复现出来的，太难崩了，我现在还不知道到底咋回事。

这个还真看个人使用习惯，可能是我的习惯太小众了。我去年也遭遇了一样的事情（扶额），只是没想着反馈，最近又开始玩galgame才又遇上这个问题。
