### ISSUE TITLE
译典通翻译英文标点符号会乱码

### ISSUE THREAD

**Issue by shinslashisuka** [HIllya51/LunaTranslator#1036]
### Question 问题

![捕获](https://github.com/user-attachments/assets/696d3982-dd76-48b4-8a67-41c1931a363e)
基本上除了逗号句号，翻译英文时候大多数其他的标点符号都这样。
试了VNR也有同样问题。

**Comment by HIllya51** [comment]
都2024年了，没必要用这个辣鸡翻译了吧。。。

**Comment by shinslashisuka** [comment]
确实无所谓，不过更新以后又发现其他问题，一会儿发出来看看

**Comment by HIllya51** [comment]
![屏幕截图 2024-08-28 023058](https://github.com/user-attachments/assets/d97b6e93-9edf-4e16-979c-66e0d2386c4f)

不存在问题。你的快译通程序有问题。

**Comment by shinslashisuka** [comment]
破案了，是这个游戏的问题，这是个英化版本，输出的标点不规范。换个正经英文游戏就没问题
