### ISSUE TITLE
英文“专有名词翻译 占位符”存在问题，未找出原因

### ISSUE THREAD

**Issue by shinslashisuka** [HIllya51/LunaTranslator#1038]
### Question 问题

我是从3.x版本升级上来的，之前的“专有名词翻译”变成了“专有名词翻译 占位符”，旧版本“专有名词翻译”里标签0的是全局，标签md5则是对应具体游戏。新版改成了“专有名词翻译 占位符”设置里的都是全局，单个游戏在“游戏管理”界面设置。旧版本靠md5难以判断是哪个游戏，新版本可以解决这种问题，但是使用中却发现了不小的问题。
我只录入了几个英文单词的“专有名词翻译”，刚升级版本时候发现之前我自己设置的“专有名词翻译”在翻译时候会出现乱码或者对应不上的问题。当时我认为是版本升级造成的，就在“专有名词翻译 占位符”里删除旧的行，重新录入一行，确实解决了一些问题。但是随后发现，比如我录入了A单词，当时翻译正确显示了，但是等我录入B单词，下次再遇到A单词的时候，又出现问题（乱码或者对应“专有名词翻译 占位符”中其他行的翻译）。
目前未找出原因，而且因为出现错误的形式不固定，也无法实现确定的重现，所以就先发到这里了，没有发在bug报告里面。

举个例子，下面这句原文是：This is it. Cum in her ass.
我在“专有名词翻译 占位符”里录入了”Cum“=”射精“、"her ass"="她的屁股"，但是翻译显示出来是这个样子
![捕获2](https://github.com/user-attachments/assets/e5c9613f-d057-4a17-a14d-f078556d1394)

猜测可能是因为我录入了带”[]“符号的专有名词造成的？如下图这样的词：
![捕获1](https://github.com/user-attachments/assets/d480df37-9107-4610-b9b1-078067951fa2)
因为截图这个游戏里面有大量带”[]“符号的词，所以基本上没有一句翻译是对的，我也试过删行重新录入，都是录了A单词当时翻译正确，录完B单词回去A单词又错了，这样。

后来我在全局“专有名词翻译 占位符”中去掉了全部带”[]“符号的词，对仅使用全局“专有名词翻译 占位符”的游戏，效果好了很多，但是依然存在少量类似问题。

**Comment by HIllya51** [comment]
![屏幕截图 2024-08-28 024202](https://github.com/user-attachments/assets/d9b55f6d-ed05-4551-b578-a175a2ddb4ce)
不存在问题

**Comment by HIllya51** [comment]
已修
