### ISSUE TITLE
OCR接口增加：白描OCR

### ISSUE THREAD

**Issue by X012C** [HIllya51/LunaTranslator#1040]
### Expected behavior 预期的功能

之前为了用啥功能买个永久会员，本着白用白不用的心态用它的客户端才发现它的识别功能比QQ和win自带的效果要好，在多语言情况下没有见到把日文和中文混淆、英文和数字混淆的这类低级情况（前两个之前经常遇到）。就数年间体验的准确率上来说，我觉得白描还是有可取之处的,一次性付费也算是勉强能够接受的方案吧。

白描OCR的API：https://github.com/baimiaoapp/baimiao-desktop/blob/main/API.md
隔壁没有客户端的实现方式：https://github.com/TechDecryptor/pot-app-recognize-plugin-baimiao

我搜了一下发现 #717 已经提了，冒昧再提，实在不好意思。如果实现有问题或者实在不考虑，希望能够得到OCR推荐，我使用OCR类型的经验也并不丰富，我的目的还是推galgame。

**Comment by HIllya51** [comment]
既然你都看见这个了，那干嘛又来问我。

**Comment by X012C** [comment]
> 既然你都看见这个了，那干嘛又来问我。

臣斗胆有一事启奏，陛下三思啊，这工具真有可取之处。

**Comment by HIllya51** [comment]
用这玩意还不如用有道词典接口，永久免费

**Comment by X012C** [comment]
> 用这玩意还不如用有道词典接口，永久免费

好吧，我去试试，能白嫖就是好事。~~主要是前期被那批连个O都识别成0的OCR给整到心理阴影了，简直要笑死的。~~
