### ISSUE TITLE
Hook won't get text if it had special character

### ISSUE THREAD

**Issue by noideaforeal** [HIllya51/LunaTranslator#1043]
### Version 程序版本

newest

### OS version and bits 系统版本和位数

win 11 23h2

### bug's screenshot 错误截图

Whenever this text ~ appear in the text, hook won't get the text at all. Try to change translate engine but to no avail, because it doesn't get the text to begin with.
![image](https://github.com/user-attachments/assets/2048d973-0402-4dff-8482-a31c090b6763)

### Reproduction steps 复现步骤

Using as normal, but ~ character appear then suddenly the hook doesn't get text.

### Log files 日志文件

[2024-08-30-03-46-21.txt](https://github.com/user-attachments/files/16806219/2024-08-30-03-46-21.txt)
[2024-08-29-20-14-48.txt](https://github.com/user-attachments/files/16806165/2024-08-29-20-14-48.txt)
[2024-08-29-05-13-10.txt](https://github.com/user-attachments/files/16806175/2024-08-29-05-13-10.txt)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/issues/new?assignees=&labels=enhancement&projects=&template=01_game_request.yaml

**Comment by HIllya51** [comment]
Recreate the issue following requirements. Your current issue does not include any meaningful information.

**Comment by miepo** [comment]
Last year I had a similar issue. Every time there was a "~" or "～" Luna would not translate the text after the tildes. After hours of troubleshooting I fixed it by unchecking "Filter Other Garbled Characters" under Text Processing. Maybe you also accidentally enabled that? I had enabled it thinking it would remove code or actually "garbled characters" not common characters like tildes.
