### ISSUE TITLE
Pre-translation bug

### ISSUE THREAD

**Issue by linakima** [HIllya51/LunaTranslator#1044]
I have a .sqlite database that already contains edited translated strings.
When I run LunaTranslator v5.28.4 and connect this file, I get the strings from this database.
When I run LunaTranslator v5.32.0 with identical settings, I get the strings from this database + an additional machine translation. 
The original string captured by the hook has not changed. Why is the translator sending a new translation request?

**Comment by HIllya51** [comment]
After testing, there are no errors.

**Comment by HIllya51** [comment]
why do you open deepl.

**Comment by HIllya51** [comment]
Your logic is confusing.
