### ISSUE TITLE
Pre-translation bug v2

### ISSUE THREAD

**Issue by linakima** [HIllya51/LunaTranslator#1045]
https://github.com/HIllya51/LunaTranslator/issues/1044
If the string has already been translated and it in the database, you don't need to send a new translation request.
If the string has not been translated, a translation request will be sent. 
Version v5.28.4 worked just like this. This is the normal working logic.
Version v5.32.0 sends a translation request even if the string has already been translated in the database. This is not the normal working logic lol.

**Comment by HIllya51** [comment]
This is your misunderstanding, it works exactly as designed.
And please also stop asking the same question over and over again, it's annoying.
