### ISSUE TITLE
特定游戏的自定义python处理被清空

### ISSUE THREAD

**Issue by mrl998** [HIllya51/LunaTranslator#1048]
### Version 程序版本

v5.29.0 64bit

### OS version and bits 系统版本和位数

win11 22h2 64bit

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/0cf65391-a485-4bb9-8905-23403948b9f2)

![9b7ab536ce5ad2a0bab0ef87039fa0fb](https://github.com/user-attachments/assets/2b275625-1fdd-424d-8584-a1bbd45d8dad)

### Reproduction steps 复现步骤

针对个别游戏设置自定义python处理后，如果再调整字符串替换或GPT词典，自定义python处理函数会被清空

### Log files 日志文件

[2024-09-02-14-27-32.txt](https://github.com/user-attachments/files/16834536/2024-09-02-14-27-32.txt)

**Comment by HIllya51** [comment]
1x
