### ISSUE TITLE
按Enter鍵不能讀取新的文本

### ISSUE THREAD

**Issue by AyaRu97** [HIllya51/LunaTranslator#1049]
### Version 程序版本

5.33.3 64bit

### OS version and bits 系统版本和位数

win11 23h2 

### bug's screenshot 错误截图

https://streamable.com/gqwr49

### Reproduction steps 复现步骤

不知道是我電腦問題還是什麼
按Enter鍵不能讀取新的文本
只有在場景刷新或該galgame可以用enter鍵以外來更新文本，LunaTranslator才可以讀取到新的。
p.s.沒有開啟快捷鍵

### Log files 日志文件

[2024-09-03-01-16-10.txt](https://github.com/user-attachments/files/16840115/2024-09-03-01-16-10.txt)

**Comment by HIllya51** [comment]
已修
