### ISSUE TITLE
翻译后的字颜色怎么调，只能是蓝色吗，

### ISSUE THREAD

**Issue by luckunicorn17** [HIllya51/LunaTranslator#105]
![image](https://user-images.githubusercontent.com/120942183/208304183-7ff6493c-e421-4178-bb67-8e80f333a71c.png)
没看到在哪调，另外，辞书那些的目录能设成相对路径吗，这样方便集成到移动硬盘。

**Comment by HIllya51** [comment]
在翻译设置里面调颜色，每个翻译源都可以设不同的颜色。
可以用相对路径。

**Comment by luckunicorn17** [comment]
![image](https://user-images.githubusercontent.com/120942183/208413572-9e14186c-db74-4004-a7e3-6582b31a426a.png)
谢谢大佬，相对路径也找到怎么用了，字典在dictionary文件夹下，要写成"../dictionary/JBeijing7"才能找到
