### ISSUE TITLE
Game path

### ISSUE THREAD

**Issue by alan-zxs** [HIllya51/LunaTranslator#1050]
### Question 问题

Hello.
I want to put the LunaTranslator folder in the game folder and run the game on any PC, writing the path to the game.exe file only once.
In the savegamedata.json file I changed the game path to ..\\\\game.exe
But this doesn't work, how do I specify the correct path to game.exe if it is 1 folder above the LunaTranslator folder?
--gamefolder\\
----game.exe
----Luna folder\\
------luna.exe

**Comment by HIllya51** [comment]
![屏幕截图 2024-09-03 185008](https://github.com/user-attachments/assets/a69a252d-e6aa-4ec0-b064-735bdd61cf05)

**Comment by alan-zxs** [comment]
thanks!

**Comment by HIllya51** [comment]
Emmm... In fact, I tested it again, and the picture I just sent you was actually incorrect, so I deleted it.
https://github.com/HIllya51/LunaTranslator/commit/729bcde932cca15c9efc814349807ec4381d4be8  I just made some changes to make it support relative paths. Please re-download it after rebuilding.
