### ISSUE TITLE
Tags for manual translation

### ISSUE THREAD

**Issue by alan-zxs** [HIllya51/LunaTranslator#1051]
Thank you for the tool. I use it for manual translation.
It would be cool if it was possible to use different tags to change the colour of a string/word, use bold/cursive font, display custom icons/pictograms in the text box.

**Comment by HIllya51** [comment]
I don't understand what you mean. If you want to request a new feature, you should follow the [template](https://github.com/HIllya51/LunaTranslator/issues/new?assignees=&labels=enhancement&projects=&template=02_request.yaml). Don't just create a blank issue. It's offensive.

**Comment by alan-zxs** [comment]
But it has the enhancement label... Ok, a new version https://github.com/HIllya51/LunaTranslator/issues/1056
