### ISSUE TITLE
使用saruka模型会在结尾显示额外的Exception b'data

### ISSUE THREAD

**Issue by haruka411** [HIllya51/LunaTranslator#1052]
### Question 问题

![eb456993-aefb-40c7-acd7-3ca3fa9c7ceb](https://github.com/user-attachments/assets/eee9370c-d656-45ab-ab40-194ce5bef89e)
使用saruka模型会在结尾显示额外的Exception b'data，似乎无需显示此信息

**Comment by HIllya51** [comment]
关闭显示错误信息

**Comment by HIllya51** [comment]
或者我修了一下，重新下载即可。
