### ISSUE TITLE
当前台词在线翻译失败后无法翻译接下来的文字

### ISSUE THREAD

**Issue by siriuxy** [HIllya51/LunaTranslator#1055]
### Version 程序版本

5.33.8

### OS version and bits 系统版本和位数

Win11 64 bit

### bug's screenshot 错误截图

Lunatranslator在遇到claude/anthropic过载的HTTP 529错误后：
1. 不会重试
2. 会跳过接下来所有翻译，不论是⏩自动翻译还是↻手动重新翻译。
3. 查询claude api的使用log，发现确实没有向服务器发出request
4. 重启lunatranslator之后可以重新使用claude

这是服务器返回的529错误代码
···
{
  "client_error": false,
  "code": 529,
  "detail": "Overloaded"
}
···

另外，修改system prompt之后需要重启lunatranslator才能生效。这是bug还是feature？

### Reproduction steps 复现步骤

1. 设置为使用Claude Api 并填入key
2. 使用lunatranslator自动翻译字幕
3. 在遇到529错误之后，自动翻译不再出现接下来台词的翻译结果，翻译历史无当前或者之后翻译结果，手动翻译快捷键/按钮也不会触发翻译。其他的翻译途径能正常使用。

### Log files 日志文件

稍后提供日志和我的claude prompt
使用的是claude-3.5-sonnet模型，streaming mode流模式

**Comment by siriuxy** [comment]
要不这个我自己来修吧？加一下529 handling和default retry = 2
https://github.com/HIllya51/LunaTranslator/blob/c5a94b46747870093d8b1baeee20669e2b6f2575/LunaTranslator/LunaTranslator/translator/claude.py#L120

**Comment by HIllya51** [comment]
不要这样。我不希望做错误重试。等我来改。



---原始邮件---
发件人: "Likai ***@***.***&gt;
发送时间: 2024年9月4日(周三) 下午4:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [HIllya51/LunaTranslator] 当前台词在线翻译失败后无法翻译接下来的文字 (Issue #1055)




 
要不这个我自己来修吧？加一下529 handling和default retry = 2
 https://github.com/HIllya51/LunaTranslator/blob/c5a94b46747870093d8b1baeee20669e2b6f2575/LunaTranslator/LunaTranslator/translator/claude.py#L120

**Comment by HIllya51** [comment]
测试修改system prompt可以理解生效，可能你哪里搞错了吧。。。

**Comment by HIllya51** [comment]
错误后不再继续这个问题比较奇怪。我得仔细看一下。

**Comment by HIllya51** [comment]
我复现不出来这个问题。

**Comment by HIllya51** [comment]
对于错误后不再继续这个问题，我复现不出来。或许你可以录制一个视频向我展示一下是什么情况。

**Comment by siriuxy** [comment]
好的，我晚些时候提供视频。

**Comment by HIllya51** [comment]
.10可能修复了，我遇到了一个有点相似的问题，你试试吧。

**Comment by siriuxy** [comment]
* ~修改system prompt之后需要重启lunatranslator才能生效~ **确认问题不存在**
* 会跳过接下来所有翻译，不论是⏩自动翻译还是↻手动重新翻译。 **暂时无法复现**
