### ISSUE TITLE
Tags system

### ISSUE THREAD

**Issue by alan-zxs** [HIllya51/LunaTranslator#1056]
### Current behavior 预期的功能

Strings without tags: 
Coloured word
Coloured line
Cursive text
Bold text
New font
Text with custom icon

Result:
![1](https://github.com/user-attachments/assets/7ea2e29d-aae5-474d-afbb-db925675205a)

### Alternative behavior (optional) 近似的功能（可选）

Strings with tags:
Coloured <color=#ff1f1f>word<\/color>
<color=#4d36fb>Coloured line<\/color>
Cursive \<i>text<\/i>
Bold \<b>text<\/b>
New <font=Monotype Corsiva>font<\/font>
Text with custom icon <icon=sword.png>

Result:
![2](https://github.com/user-attachments/assets/f1c4457e-6c30-4aac-ba2d-52fcef7c4810)

**Comment by HIllya51** [comment]
Does this make any sense?

**Comment by alan-zxs** [comment]
These tags are essential for manual game localisation. They allow features such as colour-coding character dialogue, highlighting keywords and inserting in-game icons, which is particularly useful for translating in-game tutorials.

**Comment by HIllya51** [comment]
You seem to have some misunderstandings about this software. This is just like a external subtitle translation software, not a localization software.

**Comment by HIllya51** [comment]
You should modify the game script if you want to do these things

**Comment by alan-zxs** [comment]
I can change the hooked texts for these things.
If I had access to the in-game resources, I'd translate as normal, not through Luna.

**Comment by HIllya51** [comment]
Even if it can be displayed, how do you specify what content to display?

**Comment by HIllya51** [comment]
![屏幕截图 2024-09-04 195338](https://github.com/user-attachments/assets/3b97e345-1ea0-428b-b384-97d7583e495a)

**Comment by HIllya51** [comment]
I'm not interested in writing a tag rule. But I can remove the restrictions of writing HTML. You can write your own HTML to display any content.

**Comment by alan-zxs** [comment]
> But I can remove the restrictions of writing HTML. You can write your own HTML to display any content.
Ok, I think that's enough for my purposes.

**Comment by HIllya51** [comment]
Now, if you add the "LUNASHOWHTML" flag before the translation, the following text will be added to innerHTML instead of innerText.

**Comment by HIllya51** [comment]
use webview2 display engine instead of Qt.
