### ISSUE TITLE
Embedded translation

### ISSUE THREAD

**Issue by Shisha22s** [HIllya51/LunaTranslator#1057]
### Question 问题

Hi there. 
I tried to use the Embedded Translation feature for [Everlasting Flowers](https://vndb.org/v46543) game (Unity 2022.3.7f1 / il2cpp compiler) but a translation is not embedded (pic 1).
Then I tried using the [BepInEx](https://github.com/BepInEx/BepInEx) UnityIL2CPP 6.0.0.0 builds 692 and the [XUnity.AutoTranslator](XUnity.AutoTranslator) 5.3.1 plugin.
Now I can see the embedded translation (pic 2).
Could you add the BepInEx to your Luna engine?
https://builds.bepinex.dev/projects/bepinex_be
https://pixeldrain.com/u/15n9B8iM

![luna](https://github.com/user-attachments/assets/b6086f51-20ee-4a56-b225-752560c2e028)
![BepInEx](https://github.com/user-attachments/assets/a988e505-7a7e-4eba-bb6a-804b7004ea41)

**Comment by HIllya51** [comment]
no such plan.

**Comment by HIllya51** [comment]
If the translation cannot be embedded, then display it externally.
