### ISSUE TITLE
Sakura 设置 prompt 格式为 v0.9 时，未应用占用符的专有名词翻译词条

### ISSUE THREAD

**Issue by chlbc** [HIllya51/LunaTranslator#1058]
### Version 程序版本

5.33.11

### OS version and bits 系统版本和位数

Windows 10 22H2 64 bit

### bug's screenshot 错误截图

使用之前的文本和词条测试，在 Hook + 个别游戏词条和剪贴板 + 全局词条皆会发生。

![image](https://github.com/user-attachments/assets/ba52581b-5e7c-45d7-9e84-981ee2983e55)

### Reproduction steps 复现步骤

1. 于全局或游戏个别设置的专有名词翻译中添加词条
2. Sakura 设置 prompt 格式为 v0.9
3. 使用 Hook 模式或剪贴板模式翻译
4. Sakura 翻译结果未应用“占位符”方式的专有名词翻译

（经测试谷歌翻译有正常应用占位符；Sakura v0.10pre1 也有正常应用 GPT 词典）

### Log files 日志文件

[2024-09-05-16-34-14.txt](https://github.com/user-attachments/files/16886464/2024-09-05-16-34-14.txt)

**Comment by HIllya51** [comment]
1x
