### ISSUE TITLE
希望能够更好地完善HOOK功能

### ISSUE THREAD

**Issue by xjn6666** [HIllya51/LunaTranslator#106]
首先感谢作者的辛勤劳动！已发电！！希望能够更好地完善HOOK功能及其使用说明，比如说特殊码的作用等。现在HOOK功能有时无法获取到游戏内显示的文本，不稳定。HOOK功能相较于团子等使用的“以OCR为基础获取原文”的功能有很大的优势，这是让我弃用团子而选择Luna的原因。希望作者能加强HOOK功能使其更稳定。测试游戏《Please Be Happy》。等我有无法搜索到文本的情况发生的时候就发截图上来。现在但凡HOOK功能失效，我都是关闭Luna和游戏，重启一次电脑来让软件功能恢复正常（还不是一定可以恢复）。

**Comment by HIllya51** [comment]
好的，我晚上看一下

**Comment by HIllya51** [comment]
![屏幕截图 2022-12-20 215524](https://user-images.githubusercontent.com/101191390/208683419-ceab3982-78c2-4f5a-99a7-09863d31c455.jpg)


可以了。。

**Comment by HIllya51** [comment]
可能是有僵死的进程，开任务管理器找一下杀掉就行了，没必要重启吧

**Comment by HIllya51** [comment]
特殊码这个东西一般要用的时候百度一下就可以了
而且不知道特殊码的人也不可能会去自己写特殊码，说了感觉也没啥用😂
