### ISSUE TITLE
Export file encoding

### ISSUE THREAD

**Issue by alan-zxs** [HIllya51/LunaTranslator#1060]
### Question 问题

Will the exported file always be utf-8 encoded? Can I change the encoding manually?
I am afraid that my characters will be corrupted because they're not in utf-8.

![ex](https://github.com/user-attachments/assets/d0b4338c-09d4-45f8-a531-92e42a618d30)

**Comment by HIllya51** [comment]
Can't.

**Comment by HIllya51** [comment]
Your worries are unnecessary. There are no characters that cannot be encoded using utf8.
