### ISSUE TITLE
能不能增加一个清除翻译数据的功能（快捷键）

### ISSUE THREAD

**Issue by san346596324** [HIllya51/LunaTranslator#1061]
### Expected behavior 预期的功能

获取到翻译数据的时候，不需要再继续进行翻译了。希望清空信息，方便其他操作。

**Comment by HIllya51** [comment]
什么意思？

**Comment by san346596324** [comment]
![图片](https://github.com/user-attachments/assets/7c8096a4-6475-4f09-be9d-1354fe0299da)
当我翻译结束的时候，点击快捷键，圈圈里面的翻译数据清空掉。

**Comment by HIllya51** [comment]
有什么意义吗？

**Comment by HIllya51** [comment]
直接关了重新打开不就行了。。
