### ISSUE TITLE
Line breaks in the RPG Maker Ace

### ISSUE THREAD

**Issue by Shisha22s** [HIllya51/LunaTranslator#1063]
### Question 问题

There is no line break in standard hooks. All text is merged into a single line with no space between strings. Can this be fixed or do I need to look for other hooks?

![1](https://github.com/user-attachments/assets/254a2ec5-0fdc-40eb-852a-6daae4706aeb)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/issues/new?assignees=&labels=enhancement&projects=&template=01_game_request.yaml

**Comment by HIllya51** [comment]
use this hookcode: HVN4:10*0@100415B0
