### ISSUE TITLE
Perform OCR Again Shortcut Not Functioning

### ISSUE THREAD

**Issue by Figurecollection** [HIllya51/LunaTranslator#1064]
### Version 程序版本

5.34.6 64bit

### OS version and bits 系统版本和位数

windows 11 64 bit

### bug's screenshot 错误截图

When using the "Perform OCR" button, followed by "Perform OCR Again" (via the button), everything works perfectly, and the text is translated as expected. However, using the keyboard shortcut for "Perform OCR Again" does not trigger any translation, and nothing happens. This issue was not present in a previous version of the program, where the shortcut for "Perform OCR Again" worked as intended.

### Reproduction steps 复现步骤

Steps to Reproduce:

Use the "Perform OCR" button to perform OCR on some text.
Click the "Perform OCR Again" button — it works fine, and the text is translated.
Try using the shortcut key for "Perform OCR Again" — nothing happens, and no translation occurs.
Expected Behavior:

The shortcut for "Perform OCR Again" should function the same way as clicking the button, triggering the OCR and translation process.

Actual Behavior:

The shortcut for "Perform OCR Again" does not trigger any OCR or translation.

### Log files 日志文件

[2024-09-10-03-15-13.txt](https://github.com/user-attachments/files/16938055/2024-09-10-03-15-13.txt)

**Comment by HIllya51** [comment]
fixed
