### ISSUE TITLE
adding a new language

### ISSUE THREAD

**Issue by gqwg2003** [HIllya51/LunaTranslator#1065]
### Expected behavior 预期的功能

hello maybe you can add a translation from latin and hand-made - latin hand-made is designated as hand-written

### Alternative behavior (optional) 近似的功能（可选）

Thank you very much for reading and sorry for such a question, can I find out what gender you are, female or male? If you do not consider yourself to be either of these, then please do not answer me

-------Thank you very much for reading and watching everything-------

-------By the way, I apologize in advance for the personal question------

------And a big gratitude that you work so much above the application------

--------I could not understand what gender you are for this reason  From below the screenshot --------

**Comment by gqwg2003** [comment]
------------------Here you are designated as a female representative ---------------------

-----------So I just don't understand how to contact you like a man or as a woman----------

![Снимок экрана 2024-09-12 035522](https://github.com/user-attachments/assets/9b08b692-67d0-4bdc-8e85-5eb475127027)

**Comment by HIllya51** [comment]
Latin is a dead language, and I don't know what you want to do with it.

**Comment by gqwg2003** [comment]
A lot of documents In Latin medical And I need to translate medical documents

**Comment by HIllya51** [comment]
...
this is a visual novel translator...

**Comment by HIllya51** [comment]
Didn't expect you to use her for such a thing... Okay, I'll add it

**Comment by gqwg2003** [comment]
I don't understand  but he translates much better than everyone else  

--------------Thank you very much------------

**Comment by gqwg2003** [comment]
I apologize for the mistake in the text

**Comment by gqwg2003** [comment]
You need a multi -sulfur all languages dictionary

First link application   The second link dictionary

what dictionaries are already possible to download All

Links without viruses
https://alpinefile.ru/multitran.html 

https://www.multitran.com/
