### ISSUE TITLE
bro don't put no trojan bull pls

### ISSUE THREAD

**Issue by ssaayyaa12** [HIllya51/LunaTranslator#1066]
### Expected behavior 预期的功能

no viruses

### Alternative behavior (optional) 近似的功能（可选）

pretty please

**Comment by gqwg2003** [comment]
I have a question about what

**Comment by HIllya51** [comment]
Do you think you are very smart? Among so many people using it, you are the only one who discovered that this software contains a Trojan?

**Comment by HIllya51** [comment]
If you it contains a trojan, then don't use it. No one is forcing you to use it.

**Comment by gqwg2003** [comment]
ssaayyaa12   Ha ha ha How funny you are  I finally understood what the question is here

---------🤣🤣🤣🤣👀👀👀👀👌👌👌👌🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🙄🙄😜💥💢💢--------

**Comment by gqwg2003** [comment]
I will tell you so if you trust some author to believe to the last if the author is good, then you need to trust until the last

**Comment by ssaayyaa12** [comment]
> If you think it contains a trojan, then don't use it. No one is forcing you to use it.

ok bro

**Comment by AozoraDev** [comment]
skill issue
