### ISSUE TITLE
Add support for LEC Translator, Atlas & SYSTRAN

### ISSUE THREAD

**Issue by mspykerez** [HIllya51/LunaTranslator#1067]
### Expected behavior 预期的功能

Nice suite you got here!

I was wondering if you could add support for offline LEC Power Translator?
It was the best offline translator for jap>eng back in the day and it's still good.
There are other popular ones such as Fujitsu Atlas translator and SYSTRAN which is also missing here.

Also any plans for a 1-click Manga translator ?

**Comment by HIllya51** [comment]
no.
