### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by gqwg2003** [HIllya51/LunaTranslator#1068]
### Expected behavior 预期的功能

 ----------------------Bratan I don't know what to do---------------------------
------------And yes this is only an example---I show you this document because the rest are impossible ---And yes you correctly understood this recipe
-------I have all the documents with this text spelling  It cannot scan Will I really have to translate everything to manually 😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭------------
![256280024_10fe5211744243bedd01ee1b3a31782b_800](https://github.com/user-attachments/assets/7e88fe3d-daec-41a3-89e7-8c18a4090696)

### Alternative behavior (optional) 近似的功能（可选）

✔✔✔✔✔--------------❤Great for you❤-----------✔✔✔✔✔

-----------Thank you very much for looking and checked -----------------

✔✔✔✔✔-----------I understood one thing  What do I have to translate myself -----------✔✔✔✔✔

**Comment by gqwg2003** [comment]
-----------------I translated it myself------------the system was translating some crap----

1. Разо 20 мг
дай таких доз в таблетках №30
принимать по 1 табл. 2 раза в день.
2. Урсосан 250 мг
д. т. д. в капсулах №50
принимать по 1 капс. перед сном.
3. Тримедат 200 мг
д. т. д. в таблетках №30
по 1 табл. 3 раза в день.

**Comment by HIllya51** [comment]
You should look for professional handwriting recognition OCR software instead of asking me.

**Comment by gqwg2003** [comment]
thanks a lot for the reply

**Comment by gqwg2003** [comment]
Okay, I'll translate everything manually.  Thank God I know Latin
