### ISSUE TITLE
新增华为云机器翻译

### ISSUE THREAD

**Issue by Isayama-Kagura** [HIllya51/LunaTranslator#1069]
### Expected behavior 预期的功能

https://www.huaweicloud.com/product/nlpmt.html
每个月有100w字符额度可白嫖，大佬如果有余力希望也可以实现一下，非常感谢

**Comment by HIllya51** [comment]
你把密钥给我，我不想注册。

**Comment by HIllya51** [comment]
这玩意儿要实名认证，我不想注册。你注册好了把密钥给我。

**Comment by HIllya51** [comment]
你直接写在这，然后删除掉，我能收到邮件。

**Comment by Isayama-Kagura** [comment]
AK/SK认证
User Name,Access Key Id,Secret Access Key
hid_mrvyro7v2ryya91,U1KQY06OJEMSHRPOZDTE,5a0zgvs3EUgAKznlC12QQxuPDdQQcsZCIjNMbDqV



Token认证

参数说明 | 配置参数 | 参数值
-- | -- | --
username | 用户名 | hid_mrvyro7v2ryya91
domainname | 账户名 | hid_mrvyro7v2ryya91
projectname | 需与NLP服务终端节点中的区域保持一致 | cn-north-4






构造请求参数

参数说明 | 配置参数 | 参数值
-- | -- | --
Endpoint | 承载REST服务端点的服务器域名或IP，不同服务在不同区域，Endpoint不同 | nlp-ext.cn-north-4.myhuaweicloud.com
project_id | 您的项目ID | 6d9a2e1bd1ee4029b1ba7ae18fea83b7
Content-Type | 消息体的类型（格式） | application/json
X-Auth-Token | 用户Token，使用Token方式认证时，须填充该字段 | [TOKEN具体获取方式](https://support.huaweicloud.com/api-nlp/nlp_03_0050.html)

**Comment by Isayama-Kagura** [comment]
有好多人订阅了这个项目的状态，安全起见我先把ak/sk停用了，大佬还没调试完再找我私发...

**Comment by HIllya51** [comment]
我靠 试着试着突然失效了。
那你发我邮箱吧，1716147344@qq.com

**Comment by HIllya51** [comment]
人呢？

**Comment by Isayama-Kagura** [comment]
辛苦大佬深夜还在码代码，已发邮件

**Comment by HIllya51** [comment]
怎么又失效了。

**Comment by HIllya51** [comment]
ok
