### ISSUE TITLE
manga vertical text recognition

### ISSUE THREAD

**Issue by KirpichKrasniy** [HIllya51/LunaTranslator#107]
hello, is it possible to implement vertical text recognition for manga translation in your application?
i found a manga translator that also works with PaddleOCR
https://github.com/jtl1207/comic-translation

there are also links to vertical recognition models
https://github.com/kha-white/manga-ocr

**Comment by HIllya51** [comment]
我也可以修改一下让它能够识别竖向的文字，不过效果会比较一般。。。

**Comment by KirpichKrasniy** [comment]
> 我也可以修改一下让它能够识别竖向的文字，不过效果会比较一般。。。

if you can, please do
