### ISSUE TITLE
DeeplX language-list error

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#1070]
### Version 程序版本

5.35.4

### OS version and bits 系统版本和位数

Windows 10 64-bit

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/60a054ed-7d21-4d48-9adf-7e9e4c355ff1)

I have this error in latest versions of Luna. As usual I run deeplx_windows_386.exe
And settings in Deepl are default (http://127.0.0.1:1188/translate)

### Reproduction steps 复现步骤

Run Luna - run deeplx_windows_386.exe -  select OCR range - execute OCR

### Log files 日志文件

[2024-09-14-03-35-58.txt](https://github.com/user-attachments/files/17000391/2024-09-14-03-35-58.txt)

**Comment by HIllya51** [comment]
original deeplx interface is now depracated, please use deepl/deeplx interface.

**Comment by Farooq87** [comment]
> original deeplx interface is now depracated, please use deepl/deeplx interface.

@HIllya51 
![image](https://github.com/user-attachments/assets/04101364-1819-4ff6-baf7-96cb3351155d)

That's what I ve got if I use deepl/deeplx interface. Another error

**Comment by HIllya51** [comment]
show me your settings

**Comment by Farooq87** [comment]
@HIllya51 
![image](https://github.com/user-attachments/assets/c3b35145-3e5e-45e7-9926-4e8df823d944)

**Comment by HIllya51** [comment]
It works well for me. This error is caused by you not running the deeplx service correctly, not Luna' fault.
![屏幕截图 2024-09-14 091340](https://github.com/user-attachments/assets/f08e3c93-5ab8-4f3b-b1c1-a29e461dcc75)

**Comment by Farooq87** [comment]
@HIllya51 
Its strange because I didn't encounter it previously even if I tried this interface

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/4d70fff72bd19b491b8bb39968c2d50b91ccee6d
I tried adding redundant fields to restore support for deprecated interfaces. Try it later.

**Comment by Farooq87** [comment]
Thank you, @HIllya51

**Comment by HIllya51** [comment]
try it now

**Comment by Farooq87** [comment]
> try it now

@HIllya51 Now it works. Oh, big thanks

**Comment by Farooq87** [comment]
> try it now

I meant I used the very latest 5.35.4 which you have uploaded recently

**Comment by HIllya51** [comment]
That's true.
But I can't understand why your DeepL/DeepLX interface doesn't work. You'd better figure out the reason for this, because if anything happens to the Deeplx interface in the future, I won't fix it again.
