### ISSUE TITLE
如何让hook提取的文本可以进行排序

### ISSUE THREAD

**Issue by shiyunqwq** [HIllya51/LunaTranslator#1071]
### Question 问题

如题，我不知道怎么让hook的文本自定的排序，导致名字一直在文本的下方，纯小白求教
![773fca37f02b85d1e3a0dc0c91cb7beb](https://github.com/user-attachments/assets/43d42c70-d01e-4c2a-ace9-cf62ef1ddd45)
![a966e8765fe03548cd159e8b95ecff73](https://github.com/user-attachments/assets/e21fb540-b5df-4af4-ab39-9014d63f0899)

**Comment by HIllya51** [comment]
会按照选择顺序排序。
