### ISSUE TITLE
Gemini 'Unicode Decode error utf-8'

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#1072]
### Version 程序版本

5.35.5

### OS version and bits 系统版本和位数

Windows 10 64-bit

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/497ea236-a1f2-45b2-9404-cc9f79773f72)

I have noticed that this error occures in some relatively new versions of Luna while using gemini.
It didn't happen in older versions. 
It doesn't occur constantly, just from time to time. If you perform OCR again then it might translate as usual. I wonder what is reason?

I tried to copy-paste gemini.py from old version of Luna (5.26.5). It seems that solved an issue, but it would be great to solve it in newer updates

### Reproduction steps 复现步骤

Choose Gemini as translator - Select OCR range - Perform OCR  

### Log files 日志文件

[2024-09-14-13-32-56.txt](https://github.com/user-attachments/files/17001973/2024-09-14-13-32-56.txt)

**Comment by Farooq87** [comment]
Before you ask these are my gemini settings 
![image](https://github.com/user-attachments/assets/2ae66c69-6a87-4d71-b3be-fb386d076a8b)

**Comment by HIllya51** [comment]
give me the old version code

**Comment by Farooq87** [comment]
> give me the old version code

@HIllya51 
https://disk.yandex.ru/d/93GSOKyZ79wcVw  link to download old gemini.py (5.26.5)

**Comment by HIllya51** [comment]
fix

**Comment by Farooq87** [comment]
> fixed

Thank you very much!
