### ISSUE TITLE
关闭自动翻译后,仍更新hook的文本

### ISSUE THREAD

**Issue by Huang-Yujie** [HIllya51/LunaTranslator#1073]
### 期望效果
关闭自动翻译之后,游戏文本刷新时,hook到的新文本照常刷新展示,但是不调用翻译接口

### 场景
使用计费API时,为了节约成本而关闭自动翻译,仅在有需要时手动触发翻译,但是与此同时又想使用**Mecab分词**和**将新文本复制到剪切板**的功能,所以希望关闭自动翻译后也能更新hook到的文本

**Comment by HIllya51** [comment]
使用“显示/隐藏翻译”按钮，隐藏翻译后不会调用翻译。
