### ISSUE TITLE
使用json翻译文件时，提取出来的文本是多行应该如何处理

### ISSUE THREAD

**Issue by fatecyx** [HIllya51/LunaTranslator#1074]
### Question 问题

json文件里有这两行：
    "どうしたんでしょう、あんな一度に……。\nそれに何か、様子がおかしい。": "怎么了，怎么会同时……。\n而且，样子好像有点奇怪。",
    "何かあったんでしょうか。\nまるで何かに襲われているように……。": "发生了什么事吗。\n就好像被什么袭击了一样……。",

但提取出来的文本是
どうしたんでしょう、あんな一度に……。
それに何か、様子がおかしい。何かあったんでしょうか。
まるで何かに襲われているように……。

这时候就找不到了，有什么办法吗

**Comment by HIllya51** [comment]
这个感觉没办法啊。。。如果程序自动分行来匹配的话，感觉时间复杂度太高了

**Comment by HIllya51** [comment]
增加了一个逐行匹配的选择，但速度会有点慢
