### ISSUE TITLE
界面设置-主界面-窗口特效 选择Acrylic或Aero后,工具栏会遮挡内容

### ISSUE THREAD

**Issue by Huang-Yujie** [HIllya51/LunaTranslator#1075]
### Version 程序版本

5.35.6

### OS version and bits 系统版本和位数

Windows 11 23H2 64bits

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/cf7cfc11-b4d9-4151-8448-518f68cfb989)

### Reproduction steps 复现步骤

关闭锁定工具栏
界面设置-主界面-窗口特效 任选Acrylic或Aero
原先在内容文本上方预留的工具栏空间消失,此时工具栏会出现遮挡振假名的情况
窗口特效选择disable时,或者打开锁定工具栏时,不会出现遮挡

### Log files 日志文件

[2024-09-15-00-06-41.txt](https://github.com/user-attachments/files/17003130/2024-09-15-00-06-41.txt)

**Comment by HIllya51** [comment]
因为特效是windows绘制的，即使隐藏了工具栏，如果开启特效，工具栏那块就会有一块儿空白模糊，而无法完全隐藏，所以只能这样。
