### ISSUE TITLE
加载 VNDB 元数据后，部分 VNDB 上的人名未顺利读入专有名词翻译词典

### ISSUE THREAD

**Issue by chlbc** [HIllya51/LunaTranslator#1076]
### Version 程序版本

5.35.9 / 5.36.0

### OS version and bits 系统版本和位数

Windows 10 22H2 64 bit

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/e54bec9d-bc38-4e50-80b9-3d61bbc95041)

### Reproduction steps 复现步骤

1. 初次开启 Luna，语言选择简体中文／繁體中文／英文
2. 进入“游戏管理”，随机添加一个游戏（或於 Hook 模式中直接 Hook 该游戏）
3. 开启该游戏的游戏设置
4. 在 游戏数据 -> 元数据 -> vndb 中，填入“31055”后按加载钮
5. 确认游戏加载完成后，开启专有名词翻译 直接替换
6. 部分 VNDB 上有的人物数据未加载
    - [VNDB](https://vndb.org/v31055/chars#chars) 上有的“太田部 夏海”和“逆茂木 真城”等人物皆未加载进专有名词词典

### Log files 日志文件

v5.35.9
[2024-09-16-13-18-59.txt](https://github.com/user-attachments/files/17008937/2024-09-16-13-18-59.txt)

v5.36.0
[2024-09-16-13-43-38.txt](https://github.com/user-attachments/files/17008951/2024-09-16-13-43-38.txt)

**Comment by HIllya51** [comment]
1x

**Comment by HIllya51** [comment]
vndb的api有点问题，获取不全
