### ISSUE TITLE
翻譯字串取代

### ISSUE THREAD

**Issue by KingkazmaSola** [HIllya51/LunaTranslator#1080]
### Version 程序版本

V5.36.9 64bit

### OS version and bits 系统版本和位数

Windows 11 專業版

### bug's screenshot 错误截图

![螢幕擷取畫面 2024-09-17 154530](https://github.com/user-attachments/assets/ac4d9dd7-af23-4197-a4be-26e9dfa5391d)

### Reproduction steps 复现步骤

圖片中我翻譯Ayase為綾瀨

可是顯示卻變成ZXC

### Log files 日志文件

[2024-09-17-15-33-42.txt](https://github.com/user-attachments/files/17024598/2024-09-17-15-33-42.txt)

**Comment by KingkazmaSola** [comment]
![螢幕擷取畫面 2024-09-17 155503](https://github.com/user-attachments/assets/410f947c-3cb4-492d-ad06-0129fe20f72d)
還有這個字串會直接不見

**Comment by HIllya51** [comment]
就是这样的，没有办法。
https://github.com/HIllya51/LunaTranslator/issues/550

> 還有這個字串會直接不見
测试没有问题。

**Comment by KingkazmaSola** [comment]
了解,我看到了

不過整個字串會不見是開啟專有名詞翻譯的時候才會有

不知道會不會跟 #550 有關

**Comment by HIllya51** [comment]
可能是你用的翻译把ZXBZ那一坨直接给跳过了
