### ISSUE TITLE
Spaces between letters

### ISSUE THREAD

**Issue by allebar** [HIllya51/LunaTranslator#1081]
### Version 程序版本

last

### OS version and bits 系统版本和位数

win 11 64

### bug's screenshot 错误截图

![2024-09-17_18-02-41](https://github.com/user-attachments/assets/69f479dd-431c-4283-b4e1-189b5178da79)

### Reproduction steps 复现步骤

Is there any way to remove the problems between the letters if I use the built-in translation? Spaces between words are disabled in my translation settings. I also tried me fonts, but it didn't help.

### Log files 日志文件

[2024-09-17-12-27-23.txt](https://github.com/user-attachments/files/17030446/2024-09-17-12-27-23.txt)

**Comment by HIllya51** [comment]
Shisha22s is correct.
