### ISSUE TITLE
Support for MistralAI

### ISSUE THREAD

**Issue by caliburn420** [HIllya51/LunaTranslator#1082]
### Expected behavior 预期的功能

Hi, wonder if MistralAI can be supported? It has very good models too. https://mistral.ai/

**Comment by HIllya51** [comment]
it is same to chatgpt.
https://docs.lunatranslator.org/#/zh/guochandamoxing

**Comment by caliburn420** [comment]
Hi, may I ask what do you mean the same? It's from a different Company, Have a different API and easily can be Jailbroken. Maybe you can properly support it.

**Comment by HIllya51** [comment]
As you said, you just need to fill in this link into the chatgpt interface to use it, so what do you want to do?

**Comment by caliburn420** [comment]
> As you said, you just need to fill in this link into the chatgpt interface to use it, so what do you want to do?

Ah... I'll try this later, I'm not sure it will work since maybe it has as separate way to handle system, assistant prompts, etc. My original idea is maybe put a separate category for it, but of course, it's up to you.

**Comment by HIllya51** [comment]
The only difference between chatgpt/mistral/groq/openrouter is just the API url. I have clearly explained in the document how to use it. 
Besides the aforementioned platforms, a similar new platform is generated almost every few days. Do I have to add an interface every time? This is obviously meaningless.

**Comment by caliburn420** [comment]
Alright... Thank you for taking the time to reply Really appreciate it. ^_^

**Comment by caliburn420** [comment]
Looks like it works, didn't know you could also make a separate category also.

**Comment by caliburn420** [comment]
![error](https://github.com/user-attachments/assets/2f102b6e-efe1-4c33-bbb6-6025e96568ed)
I got this error btw. It gets detected but even setting frequency penalty to 0 doesn't solve it.
