### ISSUE TITLE
Way to turn off Settings such as Top-P, Temperature, Penalties, etc. on Openai compatible.

### ISSUE THREAD

**Issue by caliburn420** [HIllya51/LunaTranslator#1084]
### Expected behavior 预期的功能

Hii sorry to make a separate issue. I tried Mistral, which gets detected but even setting frequency penalty to 0 doesn't solve it. Maybe adding a way to turn off (not zero, but not making it sent to the AI) these options such as top-p, temp, penalties will solve it? I think that will also support the new openai o1 model since it requires all the settings to be turned off (Also no system prompts, setting prompts to 'Assistant' (But this is a separate category altogether and using o1 might not be practical). Still, just the user be able to turn off these settings maybe thru tick box would probably support more models. Thanks again!
![error](https://github.com/user-attachments/assets/c3559f4e-6669-484b-9f81-4581a38a740a)

**Comment by HIllya51** [comment]
supported

**Comment by caliburn420** [comment]
Can you please tell how? Thanks

**Comment by caliburn420** [comment]
Thank you! It works now
