### ISSUE TITLE
Is there a setting to display dictionaries on words upon mouseovering on the JP text

### ISSUE THREAD

**Issue by kanbe123** [HIllya51/LunaTranslator#1085]
### Question 问题

 This was a feature on textractor but can't seem to find it here

**Comment by HIllya51** [comment]
show me example



---Original---
From: ***@***.***&gt;
Date: Wed, Sep 18, 2024 12:10 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [HIllya51/LunaTranslator] Is there a setting to display dictionarieson words upon mouseovering on the JP text (Issue #1085)




 
Question 问题
 
This was a feature on textractor but can't seem to find it here

**Comment by HIllya51** [comment]
Firstly, textractor does not have this feature, and I have thoroughly read all of its code. What you're saying may be other programs developed based on it.
Secondly, Luna can search for words by clicking on them. Hovering the mouse to search for words is not within the scope of consideration, as it would be too wasteful of performance.

**Comment by kanbe123** [comment]
"Secondly, Luna can search for words by clicking on them. Hovering the mouse to search for words is not within the scope of consideration, as it would be too wasteful of performance."

How do I get this to work? I have the settings on but click on text doesn't bring up anything

**Comment by HIllya51** [comment]
enable mecab at first https://docs.lunatranslator.org/#/zh/qa1

**Comment by ElaxDev** [comment]
JL (https://github.com/rampaa/JL) have a feature like that and the performance is good, is there no way to implement something like that on LunaTranslator?

**Comment by HIllya51** [comment]
> JL (https://github.com/rampaa/JL) have a feature like that and the performance is good, is there no way to implement something like that on LunaTranslator?

There has much better way to do this in luna.
https://github.com/HIllya51/LunaTranslator/discussions/1331#discussioncomment-12032155
