### ISSUE TITLE
Add option to disable shortcuts/hotkeys when focused window is not LunaTranslator or hooked game

### ISSUE THREAD

**Issue by eao** [HIllya51/LunaTranslator#1086]
### Expected behavior 预期的功能

I have TTS (text-to-speech) bound to the hotkey "T".  When the focused window is LunaTranslator or the game I am hooking, and I press "T", the TTS plays, as expected.  However, if I switch to my browser and try to type the word "test", this does not work, since LunaTranslator intercepts the "t", and I just type "es".  I would like an option to have the hotkeys only be functional when the focused window is LunaTranslator or a game LunaTranslator is hooking.

**Comment by HIllya51** [comment]
It's impossible to do this
And you should use ctrl/alt/shift+key instead of a single key as a shortcut.

**Comment by Ottis125** [comment]
I need help as well. I keep getting an error message saying there's no module called "PYQT6" I can't open Luna at all
