### ISSUE TITLE
是否可以新增gpt-4o和4o mini

### ISSUE THREAD

**Issue by lost-all-name** [HIllya51/LunaTranslator#1087]
### Expected behavior 预期的功能

现在只支持3.5,还是感觉不够用

**Comment by HIllya51** [comment]
谁和你说只能用3.5的。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月19日(周四) 上午10:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HIllya51/LunaTranslator] 是否可以新增gpt-4o和4o mini (Issue #1087)




 
Expected behavior 预期的功能
 
现在只支持3.5,还是感觉不够用
 
Alternative behavior (optional) 近似的功能（可选）
 
No response
