### ISSUE TITLE
"Translation of proprietary terms" works incorrectly

### ISSUE THREAD

**Issue by RkSense** [HIllya51/LunaTranslator#1088]
### Version 程序版本

5.38.x

### OS version and bits 系统版本和位数

windows 10

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/5eceab3e-19e4-4391-8ae5-6f98864e0c92)
![image](https://github.com/user-attachments/assets/cd8e2a98-e227-4514-bfcc-d6332e871447)

### Reproduction steps 复现步骤

in place of the space it puts the \ sign, although in previous versions this was not the case

### Log files 日志文件

[2024-09-19-11-29-54.txt](https://github.com/user-attachments/files/17056221/2024-09-19-11-29-54.txt)

**Comment by HIllya51** [comment]
fixed
