### ISSUE TITLE
Minor Spelling Mistake in Settings (English)

### ISSUE THREAD

**Issue by voidpenguin-28** [HIllya51/LunaTranslator#1089]
### Version 程序版本

5.38.3

### OS version and bits 系统版本和位数

Windows 10 x64

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/482401c3-8ad1-4bc5-aa73-0ff0d5dbf638)

### Reproduction steps 复现步骤

Display Settings > Interface Settings > Main Interface > Follow Game Window

Misspelling in "Mone in Sync with Game Window". "Mone" should be "Move".

Thank you (fantastic app btw).

### Log files 日志文件

Not needed for this issue.

**Comment by HIllya51** [comment]
fixed

**Comment by voidpenguin-28** [comment]
Quick unrelated question. Do you allow contributions to this repo?

Was thinking of integrating ElevenLabs speech synthesis and submitting a pull request.

**Comment by HIllya51** [comment]
Not accept niche commercial APIs.
