### ISSUE TITLE
vertical broken text xD

### ISSUE THREAD

**Issue by KirpichKrasniy** [HIllya51/LunaTranslator#109]
https://user-images.githubusercontent.com/109726461/208686934-d850c3e8-6eea-4152-a3f6-b5ca72217d2b.mp4

I don't know why it is, but the vertical text breaks when you move the mouse over the recognition area

**Comment by HIllya51** [comment]
。。。你鼠标在上面是灰色的，移走后是白色的，OCR识别起来肯定不一样啊。至于为什么鼠标移走后识别错了，识别对错本来就要看运气啊，这没办法的。

**Comment by KirpichKrasniy** [comment]
I didn't quite understand what you meant by mouse...
I wanted to write about the fact that when you hover over the mouse, recognition ceases to be correct. but if it depends on luck, then there's nothing to fix...

**Comment by HIllya51** [comment]
是这样的。OCR的效果取决于模型和数据，要么使用更多数据训练模型，要么去设计一个更先进的识别模型。
