### ISSUE TITLE
Implementation to fix error 429 in google gemini translation

### ISSUE THREAD

**Issue by erickbcr7** [HIllya51/LunaTranslator#1090]
### Expected behavior 预期的功能

![image](https://github.com/user-attachments/assets/d4f07b90-9570-4c20-8a08-b72759bc94e3)
Even if I change the translation request interval, that error still appears even though I am not exceeding the API quota.

**Comment by HIllya51** [comment]
what is your settings

**Comment by erickbcr7** [comment]
![image](https://github.com/user-attachments/assets/80f12c2d-2bc4-4c6f-a8ac-9a8c8122218f)
The only thing that changes is the translation request interval, for example I leave it at 3 seconds after approximately 7 translations the error appears and no matter how much I increase the translation request interval it continues to appear

**Comment by HIllya51** [comment]
gemini free is 15 rpm
