### ISSUE TITLE
3 languages in source-target

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#1092]
### Expected behavior 预期的功能

Could you please add 3 common european languages to target/source?
1. Slovak (Slovenčina) SK
2. Greek (Ελληνικά) EL
3.  Danish (Dansk) DA

**Comment by HIllya51** [comment]
There is no plan to add other languages, which would be pointless.

**Comment by HIllya51** [comment]
I don't want to add so many minor languages anymore, it's meaningless. This is just a visual novel's translator.

**Comment by Farooq87** [comment]
> I don't want to add so many minor languages anymore, it's meaningless. This is just a visual novel's translator.

For the one last time please. And after that no such requests
