### ISSUE TITLE
求教 人名无法去重

### ISSUE THREAD

**Issue by lh-3636** [HIllya51/LunaTranslator#1093]
### Question 问题

例如 ：小小明明[睡睡睡觉觉觉了了了]
去重之后：小小明明[睡觉了]
因为人名无法去重 ，所以提示 "json翻译文件 Exception can't find:小小明明[睡觉了]"

**Comment by HIllya51** [comment]
`(.*?)\[(.*?)\](.*?)`

![屏幕截图 2024-09-24 094939](https://github.com/user-attachments/assets/70d992f5-acc4-497c-b3da-b27600df4227)

**Comment by lh-3636** [comment]
已解决 非常感谢
