### ISSUE TITLE
Got many crashes by using OCR

### ISSUE THREAD

**Issue by Sivarius** [HIllya51/LunaTranslator#1094]
### Version 程序版本

latest

### OS version and bits 系统版本和位数

Windows 10 Pro 22H2 19045.4957

### bug's screenshot 错误截图

can't make screen cause the problem is crash

### Reproduction steps 复现步骤

Well it just happen when i trying to create OCR zone 
Sometimes it's normal, but it crashes in 8\10 cases

### Log files 日志文件

[2024-09-27-23-25-44.txt](https://github.com/user-attachments/files/17166451/2024-09-27-23-25-44.txt)

**Comment by Sivarius** [comment]
https://github.com/user-attachments/assets/f75c6031-00fd-45ae-aca6-3be48ed28485

Here is video with steps to reproduce

**Comment by Sivarius** [comment]
New log with Mecab turned off
[2024-09-27-23-44-20.txt](https://github.com/user-attachments/files/17166574/2024-09-27-23-44-20.txt)

**Comment by Sivarius** [comment]
Think i get it 

when i press hotkey the program start auto-select zone 
so the correct way is to drag mouse and then "click"

i didn't know this so i was like:
press hotkey 
"Click" and drag 
and it cause crash

**Comment by HIllya51** [comment]
fixed.
later for release.
