### ISSUE TITLE
编辑翻译记录功能优化

### ISSUE THREAD

**Issue by yonllll** [HIllya51/LunaTranslator#1096]
### Expected behavior 预期的功能

编辑翻译记录大部分时候是只想修改几个字，但是得复制一整段译文到编辑记录框，再找到要修改那几个字修改或者替换，希望后期可以修改成打开编辑翻译记录默认就是译文，可以省去了复制粘贴这个步骤
![QQ截图20241001012425](https://github.com/user-attachments/assets/9c079c44-6cc4-493f-9408-93926ef9072d)

**Comment by HIllya51** [comment]
ok
