### ISSUE TITLE
Translation Text Missing in DeepL, Visible Only in URL – Browser Debug Issue

### ISSUE THREAD

**Issue by Figurecollection** [HIllya51/LunaTranslator#1097]
### Version 程序版本

v5.40.1

### OS version and bits 系统版本和位数

windows 11 64 bit

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/2094dd72-c19f-4222-865b-882b5fd6931c)

### Reproduction steps 复现步骤

I am trying to translate using DeepL in Browser Debug, but the text to be translated is not being written inside the DeepL site. However, the text to be translated only appears in the URL. So, I recommend checking the screenshot to see that the text to be translated is only in the URL.

### Log files 日志文件

[2024-10-01-04-22-31.txt](https://github.com/user-attachments/files/17198528/2024-10-01-04-22-31.txt)

**Comment by HIllya51** [comment]
fixed
