### ISSUE TITLE
Support for PS2 emulator

### ISSUE THREAD

**Issue by noideaforeal** [HIllya51/LunaTranslator#1098]
### Question 问题

I have this super old game that can only run in PS2/PSP, and I'm using [PCSX2](https://pcsx2.net/) and [PPSSPP ](https://www.ppsspp.org/) to emulate it on windows. I just want to ask is Luna support these emulator?
![image](https://github.com/user-attachments/assets/e517c60b-b6b4-43f8-8d21-fcb0d7e864f1)

**Comment by HIllya51** [comment]
only support ppsspp. 
no plan to support pcsx2
