### ISSUE TITLE
Claude doesn't respond in Luna Window

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#1099]
### Version 程序版本

5.42.0

### OS version and bits 系统版本和位数

Windows 10 64-bit

### bug's screenshot 错误截图

I have strange bug where Claude doesn't give translation, but also it shows no errors. No signs of it being chosen. I switched it on, I have API key set for Haiku model and I use VPN with supported country. And there is just nothing.

![claude](https://github.com/user-attachments/assets/3fc89eb2-6d00-4481-9a3d-e69558a17554)
![claude2](https://github.com/user-attachments/assets/6be27532-c05f-466e-8a60-735fe86bf02e)

2 other translators are DeeplX and Deepseek 

### Reproduction steps 复现步骤

I choose Claude as translator. Perform OCR (Youdao). It shows no translation, nor error. Just empty on Luna window

### Log files 日志文件

[2024-10-04-21-58-29.txt](https://github.com/user-attachments/files/17262990/2024-10-04-21-58-29.txt)

**Comment by HIllya51** [comment]
your network is unstable. it works fine for me

**Comment by Farooq87** [comment]
> your network is unstable. it works fine for me

@HIllya51 
Gemini and Cohere work fine with my network connection.

**Comment by Farooq87** [comment]
@HIllya51 
I compared codes with old version of Luna (5.38.1) and noticed that line 'def checkv1(api_url):' is absent
https://disk.yandex.ru/d/6i7HHpoKHGaAJA  claude.py from 5.38.1
![image](https://github.com/user-attachments/assets/6f91d48d-6d68-4279-b63c-7dbf4c40e7a9)

**Comment by HIllya51** [comment]
There is no doubt that it is your network problem and the quality of your VPN is not good.
![屏幕截图 2024-10-05 220702](https://github.com/user-attachments/assets/bce596a2-ea6e-4dae-b6ff-d850f2e11180)

**Comment by Farooq87** [comment]
> There is no doubt that it is your network problem, the quality of your VPN is not good. ![屏幕截图 2024-10-05 220702](https://private-user-images.githubusercontent.com/101191390/373878343-bce596a2-ea6e-4dae-b6ff-d850f2e11180.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMzgwMjgsIm5iZiI6MTcyODEzNzcyOCwicGF0aCI6Ii8xMDExOTEzOTAvMzczODc4MzQzLWJjZTU5NmEyLWVhNmUtNGRhZS1iNmZmLWQ4NTBmMmUxMTE4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxNDE1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTNmNWUwNmYwZWJiOWE3OTU3YTlhNTRiOTIxNWViMzFhZmM1ZWNmZGQ4MzAwNmNhMjRmNDU2NDY2ZjliOGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WuaftY1ZBKTRwczr1qJ3FyivJYVvc4ypqDhNRZ2L6wk)

Ok, thanks for clarification. I ll try other VPN services
