### ISSUE TITLE
大佬，可以研究下Ｃ：ｄｒｉｖｅ．的超催眠術学園怎么读取文本吗

### ISSUE THREAD

**Issue by wycstc353** [HIllya51/LunaTranslator#11]
大佬，可以研究下Ｃ：ｄｒｉｖｅ．的超催眠術学園怎么读取文本吗，你这个翻译器可以读取到文本，但不全，用了特殊码就闪退，是椎名里绪2.5引擎的游戏

**Comment by HIllya51** [comment]
有没有游戏本体，我没找到可用的下载。

**Comment by wycstc353** [comment]
> 有没有游戏本体，我没找到可用的下载。

链接：https://pan.baidu.com/share/init?surl=kVtKgib
进入码：etce
解压码:say花火
刚找了一下找到的，我也不记得我当时在哪下载的了

**Comment by HIllya51** [comment]
有点恶心，我费半天劲打不开这个游戏。

**Comment by wycstc353** [comment]
[chaocuimian.zip](https://github.com/HIllya51/LunaTranslator/files/9745990/chaocuimian.zip)
试着把注册列表打上去试下，这两个一个是转区注册列表，一个是直接打开的注册列表，记得改下里面的游戏地址

**Comment by wycstc353** [comment]
https://github.com/Artikash/Textractor/issues/910
对了，这个引擎好像Textractor的作者做了兼容，可我试了，没啥用，好像是Textractor读取太卡？我游戏过了好久，它才终于显示几句

**Comment by HIllya51** [comment]
https://i.postimg.cc/7Z9j2R2S/2022-10-11-192149.jpg
emm 话说你是不是搞错啥了  我不用注册表光转区就启动了 然后直接提取成功了。。。（之前我没安装上）

**Comment by wycstc353** [comment]
> https://i.postimg.cc/7Z9j2R2S/2022-10-11-192149.jpg emm 话说你是不是搞错啥了 我不用注册表光转区就启动了 然后直接提取成功了。。。（之前我没安装上）
![image](https://user-images.githubusercontent.com/39401653/195087952-acfa1362-1507-482e-bea4-db1983dd90e4.png)
用你的最新版本的……游戏应该相同的啊，为啥你会有第8项，还有特殊符号的你这边提取没问题吗，我用Textractor提取到特殊符号就可能闪退

**Comment by HIllya51** [comment]
啊这 我这都没问题的😂
我这是没有打那两个补丁的版本的游戏，你打补丁了吗？是不是你打了补丁的原因？

**Comment by wycstc353** [comment]
> 啊这 我这都没问题的😂 我这是没有打那两个补丁的版本的游戏，你打补丁了吗？是不是你打了补丁的原因？

特地去试了一下，的确是补丁原因，打了补丁后椎名里绪版本从2.49变2.50了，但就算原版也还是有问题的，它特殊符号问题解决不了，你可以多玩几句话就会发现问题了

**Comment by HIllya51** [comment]
看新release，把x86里面的这个文件替换进去进行了

**Comment by HIllya51** [comment]
呃呃 别慌 我好像有点调试信息没删 等下qaq

**Comment by HIllya51** [comment]
okok了

**Comment by wycstc353** [comment]
> okok了

怎么说呢，可以用了，但遇到特殊符号就断掉了，或者跳过一部分内容，不过总比以前好，毕竟一般有特殊符号的都是语句词，我测试的是没打补丁的版本，打了补丁的版本也可以用吗？

**Comment by HIllya51** [comment]
比较少见，问题不大就行，游戏我都删掉了，再下也麻烦懒得弄了qaq

**Comment by wycstc353** [comment]
> 比较少见，问题不大就行，游戏我都删掉了，再下也麻烦懒得弄了qaq

那就不要弄了，少见到不是很少见，特殊符号内容挺多的，不过影响不大，主要就是特殊符号都是爱心，基本上带爱心的都是语气词，对于看明白影响不大
