### ISSUE TITLE
同时使用hook与ocr功能

### ISSUE THREAD

**Issue by lizkes** [HIllya51/LunaTranslator#110]
部分游戏（特别是SLG游戏）有大量对话外的提示，需要使用ocr进行翻译。
而hook功能可以更加精准快速的翻译对话文本。
希望可以支持同时使用hook与ocr进行翻译的功能。

**Comment by HIllya51** [comment]
打开两个不就行了。

**Comment by lizkes** [comment]
有道理...没想到居然可以打开两个。
谢谢提醒
