### ISSUE TITLE
Toggle for choosing which text gets copied to clipboard or not

### ISSUE THREAD

**Issue by Kwepoi** [HIllya51/LunaTranslator#1100]
### Expected behavior 预期的功能

![Screenshot 2024-10-05 051016](https://github.com/user-attachments/assets/c3fffb58-3823-40fe-9882-9c664122bc00)

Right here should be a good place for putting the toggle that can be used to choose what text gets auto pushed to clipboard.

Purpose: For games that have both English and Japanese translation already, it would be preferable to push only the Japanese text to clipboard so easy tooling can be used and the Original English translation can be looked at when needed instead of both filling the clipboard.

**Comment by HIllya51** [comment]
meaningless

**Comment by Kwepoi** [comment]
But why?, it's useful for Japanese only study, unless there's a way already to choose what text is copied you can tell me.
