### ISSUE TITLE
新版本使用异常

### ISSUE THREAD

**Issue by frotmo** [HIllya51/LunaTranslator#1101]
### Question 问题

1. hook模式导致游戏进程卡顿 甚至导致电脑系统崩溃(卡住)
2. 软件使用时频繁闪屏，整个屏幕会是不是黑一下
3. 感觉性能占用有点莫名其妙的大 任务管理器看了一下 占了60%的cpu(i7-12700kf)
感觉除了hook模式游戏进程卡顿以外都是最近才有的问题

**Comment by HIllya51** [comment]
什么情况？是怎么解决了么？我没有遇到问题。。
