### ISSUE TITLE
hook模式截图保存异常

### ISSUE THREAD

**Issue by Jastmaskerrr** [HIllya51/LunaTranslator#1103]
### Version 程序版本

v5.42.2

### OS version and bits 系统版本和位数

windows 11 22H2 64 bits

### bug's screenshot 错误截图

![Quicker_20241007_205718](https://github.com/user-attachments/assets/b6d28231-c042-446e-9256-cf165aae778f)
第一张图为游戏画面
![Quicker_20241007_205755](https://github.com/user-attachments/assets/bfaf5a2e-85ef-4881-8819-4d5bdfe3243c)
第二张图为查词，这里截图画面出现了错误

### Reproduction steps 复现步骤

游戏时保持着窗口绑定，查词时的截图一直保持为同一截图（似乎为第一次查词时的截图），以下是我对几款游戏的测试
- 极乐迪斯科：在全屏和窗口下，截图都**异常**
- 逆转裁判：窗口下，截图正常
- sudachi模拟器（火焰纹章 风花雪月）：全屏和窗口都**异常**

### Log files 日志文件

[2024-10-07-21-10-18.txt](https://github.com/user-attachments/files/17279287/2024-10-07-21-10-18.txt)
[2024-10-07-20-54-24.txt](https://github.com/user-attachments/files/17279288/2024-10-07-20-54-24.txt)

**Comment by HIllya51** [comment]
sudachi最新版，测试没有问题
![屏幕截图 2024-10-07 215442](https://github.com/user-attachments/assets/39157f85-66e9-4730-bf97-1a7eab9dfcf5)
![屏幕截图 2024-10-07 215455](https://github.com/user-attachments/assets/ee32d550-68e1-47e8-b38d-400f67ac7e31)

**Comment by Peppa-g** [comment]
有一个方法能解决，alt enter两次对游戏进行窗口化后再全屏，我在星铁 绝区零也遇到同样问题，偶尔进行窗口切换就会刷新，经过尝试得到了这个解决方法，比较麻烦但是至少能暂时解决问题
