### ISSUE TITLE
全屏游戏的ocr识别问题

### ISSUE THREAD

**Issue by Peppa-g** [HIllya51/LunaTranslator#1104]
### Version 程序版本

v5.42.4 64bit

### OS version and bits 系统版本和位数

win11 23H2 64

### bug's screenshot 错误截图

https://github.com/user-attachments/assets/f3759b3b-c2cf-482e-ba64-bd188c319e87

### Reproduction steps 复现步骤

进入全屏游戏，使用luna指定ocr范围，第一次使用正常后，使用热键更新时无法进行更新，重新指定ocr范围，翻译的是第一次设定ocr时的截图时对应位置的文本

### Log files 日志文件

[2024-10-08-15-18-31.txt](https://github.com/user-attachments/files/17293959/2024-10-08-15-18-31.txt)

**Comment by Peppa-g** [comment]
和现在的open issue是同一个问题，全屏游戏会导致更新异常

**Comment by HIllya51** [comment]
取消绑定窗口
