### ISSUE TITLE
内嵌翻译自动分段

### ISSUE THREAD

**Issue by skyalone-ai** [HIllya51/LunaTranslator#1105]
### Question 问题

原文此处是一个句子分为3段，不开启内嵌翻译时可以正常识别为1个句子，只会翻译1次；但开启内嵌翻译后，就会将其作为3个句子翻译，一共翻译4次，从而出现上下文不对应的情况。尝试过滤换行符、提高hook刷新延迟均无效，请问是否有解决方案？
![4](https://github.com/user-attachments/assets/b4e33a3e-df84-477f-b3bf-f712db93f592)

**Comment by HIllya51** [comment]
没有办法

**Comment by HIllya51** [comment]
刷新延迟只对外挂式翻译有效，可以延迟收集多条句子再一起翻译，但内嵌翻译没办法这样。
