### ISSUE TITLE
Integrate EasyOCR by JaidedAI

### ISSUE THREAD

**Issue by Eng-Ahmed-Rifai** [HIllya51/LunaTranslator#1106]
### Expected behavior 预期的功能

LunaTranslator already has some OCR functionality, but I believe integrating EasyOCR by JaidedAI ([EasyOCR](https://github.com/JaidedAI/EasyOCR)) would provide a significant upgrade. I think it's the most advanced open-source OCR solution. It offers high precision of text recognition even with a complex background and uncommon fonts, which could greatly enhance the existing OCR capabilities.

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/issues/989
