### ISSUE TITLE
Browser debug GPT not sent output

### ISSUE THREAD

**Issue by noideaforeal** [HIllya51/LunaTranslator#1107]
### Version 程序版本

Latest

### OS version and bits 系统版本和位数

Windows 11

### bug's screenshot 错误截图

Input being sent to GPT and it's translate, but no output was in the program. I did not hit limit or anything. I tried to delete Luna and download again but it's not letting me because it was 'in use', while no sign of the program run in taskbar or task manager. I have to restart PC and two issue above still remain.

![image](https://github.com/user-attachments/assets/3a3fd543-4130-4d4e-b977-04391e3c6f27)
![image](https://github.com/user-attachments/assets/7bd25472-7ab3-4b7d-8809-6916cffd496b)

### Reproduction steps 复现步骤

1. Browser debug GPT
2.  Translate as usual
3.  No output

### Log file 日志文件

[2024-10-08-23-43-12.txt](https://github.com/user-attachments/files/17325984/2024-10-08-23-43-12.txt)

**Comment by HIllya51** [comment]
only support the latest chromium. if you use the old browser, it will maybe not work.
