### ISSUE TITLE
Sakura No Uta Spanish language 

### ISSUE THREAD

**Issue by Excaliburxxa** [HIllya51/LunaTranslator#1108]
Sakura no uta spanish language https://vndb.org/v562
![Screenshot 2024-10-10 182042](https://github.com/user-attachments/assets/d7f82185-27f8-457e-9b6b-9a00f3cc9ee0)
![Screenshot 2024-10-10 182349](https://github.com/user-attachments/assets/8f817a83-dbe3-4295-a5b0-7e0a1ac0d91e)
Can you add spanish language hook support in the latest update? Link download game
https://drive.google.com/file/d/1zIsgDeiU5qVaYxNJ03Ede32SB-oWm-La/view?usp=sharing

**Comment by HIllya51** [comment]
latin(CP1252)

**Comment by Excaliburxxa** [comment]
![Screenshot 2024-10-10 190610](https://github.com/user-attachments/assets/4beca57f-b695-4d10-bca6-3b053fa65c38)
not works
