### ISSUE TITLE
希望能對接Google翻譯的 API的功能

### ISSUE THREAD

**Issue by SpaceEsc** [HIllya51/LunaTranslator#111]
如題，感謝你!!

**Comment by HIllya51** [comment]
已添加，但是在这边难以测试，不知道管不管用。

**Comment by SpaceEsc** [comment]
感謝!
我再協助測試，有問題的話，我可以幫忙修正此功能。
測試完再跟您回報。

**Comment by SpaceEsc** [comment]
跟您回報一下，API可以成功使用，但是會回傳翻譯後的URL 文本，需要另外做解碼
以下為例

%E9%A1%94%E3%81%A0%E3%81%91%E3%81%AE%E5%A5%B3%E3%81%8C%E5%A4%A2%E3%81%AB%E5 %87%BA%E3%81%A6%E3%81%8D%E3%81%9F%E3%82%89%E6%B7%AB%E5%A4%A2%E3%81%98%E3%82 %83%E3%81%AA%E3%81%84%E3%82%93%E3%81%A0%E3%82%8F%E3%80%82%E6%82%AA%E5%A4%A2 %E3%81%AA%E3%82%93%E3%81%A0%E3%82%8F%E3%82%BD%E3%83%AC

**Comment by HIllya51** [comment]
这是什么？解码出来是日语啊

**Comment by SpaceEsc** [comment]
哇 抱歉QQ，我再測試一下

**Comment by SpaceEsc** [comment]
![image](https://user-images.githubusercontent.com/39794423/208964949-3ce0bcd3-c70d-4751-9f24-d45ace9afaf5.png)
我有測試API的部分應該沒問題
但是App卻會有以下顯示
![image](https://user-images.githubusercontent.com/39794423/208965227-074586c5-1d50-4bec-955e-ec1fce1582f2.png)

我原本想要編譯的您的專案，剛剛搞很久編起來，先提供以上內容除錯，感謝!!

**Comment by HIllya51** [comment]
你设置语言了吗。

**Comment by SpaceEsc** [comment]
![image](https://user-images.githubusercontent.com/39794423/209115021-70b25e30-aab7-44c9-9c48-404c60ab5079.png)
有的 如上圖，需要提供API給您測試嗎

**Comment by HIllya51** [comment]
你打开translators/googleapi.py，把quote去掉试试？

**Comment by SpaceEsc** [comment]
感謝!! 這樣就成功了
