### ISSUE TITLE
Rogue Text Hooking?

### ISSUE THREAD

**Issue by Arspatheia** [HIllya51/LunaTranslator#1111]
### Question 问题

I'm having some problems with an rpg-made game, but the most annoying one is that sometimes the only text copied to the clipboard reads as **LUNAFROMJSrpgmakermv5...** when the LT text window shows the (somewhat) correct sentences. It's the same with Lunar Hook.
I don't know if it's related to the fact that the program can't separate the "headline" from the rest of the text, resulting in a very confusing mix of names and context, for example:

In-game text
![In-game text](https://github.com/user-attachments/assets/ddaf96fc-e645-4ab1-b4d6-228a6eec0128)
LunarTrans hook
![LunarTrans text](https://github.com/user-attachments/assets/f254ec53-5b52-433e-9990-2d669965a657)

I'm not really sure if this is a bug, but I'm posting the problem here in case the solution is to use the regex filter or something simple that I'm missing so you can help me out.

**Comment by HIllya51** [comment]
When hooking RPGMaker/Tyrano engine games, please do not use other software that reads and writes the clipboard.
This is not a bug, and there is no workaround.
https://github.com/HIllya51/LunaHook/blob/main/LunaHook/resource/lunajspatch.js
