### ISSUE TITLE
重复输出前几句译文

### ISSUE THREAD

**Issue by mrl998** [HIllya51/LunaTranslator#1113]
### Version 程序版本

v5.42.12 64bit

### OS version and bits 系统版本和位数

win11 22h2 64bit

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/37f33971-8f21-4f30-9e72-98a52a50c7d2)

### Reproduction steps 复现步骤

翻译器设置里启用了“利用上下文”
正常游玩，随机出现，一小时有个五次八次
并没有点开游戏里的历史记录

### Log file 日志文件

[2024-10-12-07-38-01.txt](https://github.com/user-attachments/files/17367551/2024-10-12-07-38-01.txt)

**Comment by HIllya51** [comment]
prompt格式版本和模型版本是正确对应的吗？sakura模型对这个有点敏感。

**Comment by mrl998** [comment]
没问题的，都用的1.0

**Comment by HIllya51** [comment]
代码有点小问题，晚点改一下

**Comment by HIllya51** [comment]
1x
