### ISSUE TITLE
OCR和hook显示炸了？

### ISSUE THREAD

**Issue by AAxjcy** [HIllya51/LunaTranslator#1118]
### Version 程序版本

5.46.0

### OS version and bits 系统版本和位数

windows 11 23H2 64bit

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/481caa13-b714-4985-a2fc-5bd695f07fe2)
![image](https://github.com/user-attachments/assets/70336b46-baab-46ad-bb39-0588e4bc0586)
![image](https://github.com/user-attachments/assets/f1404937-7925-45e6-b822-ad91dc221d74)
![image](https://github.com/user-attachments/assets/ec2a7054-ca5a-417e-8de2-4b8d2fb8907f)
![image](https://github.com/user-attachments/assets/b146d7a8-c9c3-42bf-a822-5af886d6ca08)

### Reproduction steps 复现步骤

（似乎是自从今天更新到最新版本开始，）ocr随机触发无法识别，比如关掉重开可能就可以正常识别了，但hook始终无法正常显示

### Log file 日志文件

运行了这个debug程序，日志是空的
![image](https://github.com/user-attachments/assets/d34efd7f-7e36-4f13-ae64-0c50c8ea3acc)

**Comment by AAxjcy** [comment]
刚发完这个issue就更新了。。。
更新完后hook依然有问题
![image](https://github.com/user-attachments/assets/562dccc1-3e8d-417e-9291-9b8a25ec9c93)
OCR暂时还未遇到问题

**Comment by HIllya51** [comment]
文件可能损坏，重新手动下载
