### ISSUE TITLE
移动翻译窗口后，使用“显示/隐藏翻译窗口“功能会导致程序卡死

### ISSUE THREAD

**Issue by lizkes** [HIllya51/LunaTranslator#112]
复现步骤：
1.给快捷键设置里的“显示/隐藏翻译窗口“按钮绑定一个快捷键
2.先用几次这个快捷键，一切正常。
3.移动翻译窗口。
4.再使用几次这个快捷键，会发现程序卡死。
![image](https://user-images.githubusercontent.com/20457790/208715795-e3e6361f-341a-4759-a59e-6f4e4f50b9e4.png)

**Comment by HIllya51** [comment]
测试未发现问题。
要不你下载测试版看一下什么问题
https://github.com/HIllya51/LunaTranslator/releases/download/v1.35.1/LunaTranslator_debug.zip

**Comment by lizkes** [comment]
使用最新的1.35.3版本，还是一样的情况。
要快速的按快捷键，同时拖动窗口，就会出。

**Comment by HIllya51** [comment]
呃  这不是没事找事吗

**Comment by lizkes** [comment]
![动画](https://user-images.githubusercontent.com/20457790/208915120-74786522-4177-451d-8150-0c4d0c964c69.gif)
动图，后面软件就卡死了，任何快捷键都没用，点任务栏小图标也不出

**Comment by lizkes** [comment]
> 呃 这不是没事找事吗

在移动窗口后的两秒内隐藏也会卡死，还挺影响的...

**Comment by KirpichKrasniy** [comment]
> ![动画](https://user-images.githubusercontent.com/20457790/208915120-74786522-4177-451d-8150-0c4d0c964c69.gif) [ ![动画](https://user-images.githubusercontent.com/20457790/208915120-74786522-4177-451d-8150-0c4d0c964c69.gif) ](https://user-images.githubusercontent.com/20457790/208915120-74786522-4177-451d-8150-0c4d0c964c69.gif) [ ](https://user-images.githubusercontent.com/20457790/208915120-74786522-4177-451d-8150-0c4d0c964c69.gif) 动图，后面软件就卡死了，任何快捷键都没用，点任务栏小图标也不出

if you use the full screen mode of the game, then the program may break.
use magpie capture by clicking on the third button from the right and then on the game window
it is better to use the game in window mode and with the help of magnie stretch the game to full screen

**Comment by HIllya51** [comment]
已修正
