### ISSUE TITLE
新版本预翻译sqlite翻译记录是失效了吗

### ISSUE THREAD

**Issue by yonllll** [HIllya51/LunaTranslator#1120]
### Question 问题

新版本预翻译sqlite翻译记录是失效了吗？之前用Sakura翻译过的记录现在读取不出来了，导出json倒是能读取，但是实时编辑完点确定，刷新完json也没有实时更新，必须退出软件重启才能读出更新，有办法修复吗？或者有旧版本存档么？感觉前几个版本用得顺手，感谢

**Comment by HIllya51** [comment]
这是个bug，下个版本会修复。
没有旧版本存档。
