### ISSUE TITLE
Outputting OCR text only to websocket

### ISSUE THREAD

**Issue by pinntokuru** [HIllya51/LunaTranslator#1121]
### Question 问题

I use LunaHook mainly, and just found out about LunaTranslator. Is it possible to use LunaTranslator in a similar way to LunaHook? As in, not to translate, but to simply output ocr box to websocket?

I tried setting Text Input->Text Output-> Websocket->Auto Output on, and set the port number, but no text gets output to texthooker-ui. 

It does seem to connect because when I shut off LunaTranslator texthooker-ui says websocket lost connection.

I have also tested the websocket with LunaHooker with Textractor websocket plugin and can confirm it works normally.

**Comment by HIllya51** [comment]
Go to Discord and ask someone, I'm not interested in WebSocket.

**Comment by HIllya51** [comment]
https://discord.com/invite/ErtDwVeAbB

**Comment by HIllya51** [comment]
I have seen screenshots of someone using something similar in Discord, so the program is not incorrect, it is only because you did not configure it correctly. As for how to configure it, I don't know because I have never used it before.
﻿

**Comment by pinntokuru** [comment]
Thanks for the quick reply. The Discord invite says invalid. I also tried the invite in the Readme page and it's also invalid.

**Comment by HIllya51** [comment]
This is your own mistake
