### ISSUE TITLE
不能自动输出到剪贴板

### ISSUE THREAD

**Issue by jijinganhe** [HIllya51/LunaTranslator#1123]
### Version 程序版本

5.51.2

### OS version and bits 系统版本和位数

windows11 23H2

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/ff6cfc9b-d016-4757-9d7e-24623d3ae05d)

### Reproduction steps 复现步骤

无

### Log file 日志文件

无

**Comment by HIllya51** [comment]
😅你开着读取剪贴板，再输出到剪贴板，不就套娃了？

**Comment by HIllya51** [comment]
有道理



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月28日(周一) 下午3:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [HIllya51/LunaTranslator] 不能自动输出到剪贴板 (Issue #1123)




 
感谢回复，我想的是复制之后自动翻译，然后再自动输出到剪贴板马上可以在其它地方粘贴，因为前面有开启“排除复制自翻译器的文本”😉
