### ISSUE TITLE
Include character name for LLM translation

### ISSUE THREAD

**Issue by Igoorx** [HIllya51/LunaTranslator#1125]
### Expected behavior 预期的功能

I noticed that your previous instance about hooking names is that it's meaningless (https://github.com/HIllya51/LunaTranslator/issues/987#issuecomment-2286493662), but that's actually not true for LLMs, because names are important context for a more accurate translation. So I was wondering if it would be possible to hook the character name and include it in the LLM prompt. Thanks in advance!

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/issues/new?assignees=&labels=enhancement&projects=&template=01_game_request.yaml

**Comment by HIllya51** [comment]
If it can't be extracted, you should send me the game.
If it can be extracted, you should enter the name list in the prompt yourself.

**Comment by Igoorx** [comment]
> If it can't be extracted, you should send me the game.

You mean, if it shows up in the hooks? Well, technically it shows up in the second hook but there's a lot of garbage included.
![image](https://github.com/user-attachments/assets/314f2e0a-cdc3-4a50-9537-77e295387683)

> If it can be extracted, you should enter the name list in the prompt yourself.

Do you mean I should edit the prompt for each line in the Visual Novel? That's quite bothersome... It would be really helpful if that happened automatically.

Just to be clear, what I meant with this feature request is NOT a dictionary of character names, but including the character name in every message in the LLM context, e.g.:
```
Character A: 「あははっ、一年分甘えさせてあげないと駄目よ？」
Character B: 「ああ」
```

**Comment by Igoorx** [comment]
@HIllya51 I think you misunderstood me.

> If it can't be extracted, you should send me the game.

You mean, if it shows up in the hooks? Well, technically it shows up in the second hook but there's a lot of garbage included.
![image](https://github.com/user-attachments/assets/314f2e0a-cdc3-4a50-9537-77e295387683)

> If it can be extracted, you should enter the name list in the prompt yourself.

Do you mean I should edit the prompt for each line in the Visual Novel? That's quite bothersome... It would be really helpful if that happened automatically.

Just to be clear, what I meant with this feature request is NOT a dictionary of character names, but including the character name in every message in the LLM context, e.g.:
```
Character A: 「あははっ、一年分甘えさせてあげないと駄目よ？」
Character B: 「ああ」
```

**Comment by Igoorx** [comment]
https://github.com/HIllya51/LunaHook/issues/163

**Comment by HIllya51** [comment]
You haven't accurately described your problem, which can be solved with simple text processing.

https://docs.lunatranslator.org/#/zh/textprocess

**Comment by Igoorx** [comment]
@HIllya51 Text processing isn't enough afaict, the hook that captures the name is very broken:
```
迪希「「ごめん、まだわからないの。家・の・ほ・う・で何かあるかもしれな「ごめん、まだわからないの。家のほうで何かあるかもしれいし…。今、ちょっと葵あおいにメール送るから、合わせて聞ないし……。今、ちょっと葵にメール送るから、合わせていておくね」聞いておくね」
```

Comparison to the third hook:
```
「ごめん、まだわからないの。家のほうで何かあるかもしれないし……。今、ちょっと葵にメール送るから、合わせて聞いておくね」
```

**Comment by HIllya51** [comment]
use regex to filter the first's text and select both of them

**Comment by Igoorx** [comment]
> use regex to filter the first's text and select both of them

@HIllya51 Oh... Sorry, I didn't know that was possible. I wrote this simple filter and it seems to be working:

```
def POSTSOLVE(line):
    if "「「" in line:
        name = line.split("\n")[1].split("「「")[0]
        return name + ": " + line.split("\n")[0]
    else:
        return line.split("\n")[0]
```

Sorry for bothering you, and thanks for the help!

**Comment by HIllya51** [comment]
good



---Original---
From: "Igor ***@***.***&gt;
Date: Thu, Oct 31, 2024 03:21 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HIllya51/LunaTranslator] Include character name for LLMtranslation (Issue #1125)




  
use regex to filter the first's text and select both of them
  
@HIllya51 Oh... Sorry, I didn't know that was possible. I wrote this simple filter and it seems to be working:
 def POSTSOLVE(line):     if "「「" in line:         name = line.split("\n")[1].split("「「")[0]         return name + ": " + line.split("\n")[0]     else:         return line.split("\n")[0]  
Sorry for bothering you, and thanks for the help!
