### ISSUE TITLE
photo ocr

### ISSUE THREAD

**Issue by KirpichKrasniy** [HIllya51/LunaTranslator#113]
is it possible to add the function of translating text from a photo? you added the function of translating text from a txt file, is it possible to make it so that you can upload a photo to the application, and get a text translation at the output.
or translation in the photo itself.
Or is it too hard to implement?

**Comment by HIllya51** [comment]
txt是为了批量进行翻译，图片又不用。
txt是直接读取不需要识别，图片如果不选择范围的话，OCR识别效果不好，感觉没什么意义。

**Comment by KirpichKrasniy** [comment]
> txt是为了批量进行翻译，图片又不用。 txt是直接读取不需要识别，图片如果不选择范围的话，OCR识别效果不好，感觉没什么意义。

I'm understood, thank you.
I am just now translating one unique game into Russian, and with the help of your program it is very convenient and much faster to do this. however, large photographs cannot be quickly recognized and translated... I tried to use a manga translator to translate such photographs, but it is inconvenient and works strangely.
then you will have to continue to read each piece of text through ocr, and then collect them all through the translation history ...
maybe I'll come up with something more efficient to solve my problem.
your program is still very cool and fast and also accurate

**Comment by HIllya51** [comment]
你可以尝试使用百度/docsumo的OCR api而非内置的OCR，他们可能能够较好地直接识别整张图片。。

**Comment by HIllya51** [comment]
或者其他在线ocr api。他们的效果会好一些。

**Comment by KirpichKrasniy** [comment]
> 或者其他在线ocr api。他们的效果会好一些。

thanks, I'll try
