### ISSUE TITLE
OCR translation garbage text breaks everything with no way to fix

### ISSUE THREAD

**Issue by Owyn** [HIllya51/LunaTranslator#1130]
### Version 程序版本

v5.53.9 Latest 

### OS version and bits 系统版本和位数

Win 10

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/b92f9dc9-965c-4c1d-a515-175a79bd250a)

![image](https://github.com/user-attachments/assets/15dfc97d-7663-4fc2-b133-e2956c938450)

### Reproduction steps 复现步骤

Turn on Region OCR, 
set a hotkey for it, 
first enable just few translators: e.g. Google Trans and DeepL
see it works now,
see some occasional cache errors - turn off TL cache now,
now test more translation services to see which give the best result - turn em all on,
now it all breaks - original text is not the original recognized text anymore but some garbled text taken from the result translation,
get scared and go turn every translator except google TL and deepL (like it was), restart the program,
- see it is still broken with no way to fix it :-(

![image](https://github.com/user-attachments/assets/f012885e-a59d-4d0d-8a48-2f54662ce06f)
![image](https://github.com/user-attachments/assets/e5746e79-721a-40fc-82aa-cd5c0018812a)

**Comment by Owyn** [comment]
TL service names are wrong too btw if their display is on, either empty or isn't in the language of the interface (english)

e.g. 
![image](https://github.com/user-attachments/assets/783ebb2c-f532-4266-b134-c1d3ddba5c12)
first one is supposed to be "google v2)

**Comment by HIllya51** [comment]
It should be common knowledge that the translation window should not overlap with the OCR range.

**Comment by Owyn** [comment]
> It should be common knowledge that the translation window should not overlap with the OCR range.

it is not overlapping, as you can see - "window always on top" is turned off so it's not even visible when I select OCR range

**Comment by Owyn** [comment]
Here's a video of the issue: 

https://github.com/user-attachments/assets/2fe2e7d0-f80f-44b6-8670-210bc528aefa
