### ISSUE TITLE
problem turning off "always on top"

### ISSUE THREAD

**Issue by Owyn** [HIllya51/LunaTranslator#1131]
### Version 程序版本

v5.53.9 Latest

### OS version and bits 系统版本和位数

Win 10

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/10cb7fa5-08a6-42d5-a762-ecc1db287a80)

### Reproduction steps 复现步骤

I turned of "window always stays on top" but it's still rather sticky and hard to make background (disappear).

1. select OCR range - translation window pops up
2. click window other than the translation window (it should focus it and hide translation window)
3. it doesn't hide translation window

it only hides translation window if you first click (focus) translation window and then click (focus) other window

I want to make translation window show only when I need it but it tries it best to always be shown 😢 

"auto-hide window" option doesn't help since it hides the window before I can actually read the whole translation there

**Comment by HIllya51** [comment]
I completely don't understand what you mean. Can you write fewer abbreviations? I don't know English.

**Comment by HIllya51** [comment]
This cannot be fixed. Due to the security mechanism of Windows, when there is no user operation focus on the window, setting and canceling the window's top will most likely fail

**Comment by Owyn** [comment]
But normal windows work fine and disappear (go to background) when other window gets clicked

Can't you just make luna window into a normal windows window so it'd work fine?

**Comment by HIllya51** [comment]
unselect this option
![屏幕截图 2024-11-03 224118](https://github.com/user-attachments/assets/ca56bad3-8aa9-4a06-a697-2966a88e5c85)

**Comment by Owyn** [comment]
> unselect this option ![屏幕截图 2024-11-03 224118](https://private-user-images.githubusercontent.com/101191390/382579955-ca56bad3-8aa9-4a06-a697-2966a88e5c85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NDUxOTQsIm5iZiI6MTczMDY0NDg5NCwicGF0aCI6Ii8xMDExOTEzOTAvMzgyNTc5OTU1LWNhNTZiYWQzLThhYTktNGEwNi1hNjk3LTI5NjZhODhlNWM4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QxNDQxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGU5Yjk5NGU4OTI3YTBmNGQyMWVjZThjYTk1ODUxYjJjMjk1NzkwMDdiNzQ0YzA4NjM5OTY0NzNjZDcwZGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.l4jFIVhrdK1fhYc-HA9oS88b7HToE4ZNtiLfNHRqhGY)

It was already not selected for me 
![image](https://github.com/user-attachments/assets/98b109f6-0127-4cd9-b671-673802884ca4)

**Comment by HIllya51** [comment]
unselect and rerun，i tested no any mistake.

**Comment by Owyn** [comment]
> unselect and rerun，i tested no any mistake.

Here is my test after rerun:

https://github.com/user-attachments/assets/867e2a83-8b55-4134-b71c-d208aff50c46

as you can see - the luna window stays up even when I'm clicking and then right-clicking in the browser

**Comment by HIllya51** [comment]
I don't know what you mean. Can you say less colloquial things? Google Translate doesn't understand what you're saying.

**Comment by Owyn** [comment]
I want the window of Luna to disappear when I use mouse to click in my web-browser.

It does not happen currently.

**Comment by HIllya51** [comment]
This is simply impossible

**Comment by HIllya51** [comment]
Your idea can only be achieved through browser plugins

**Comment by Owyn** [comment]
> This is simply impossible

![pain](https://github.com/user-attachments/assets/514e8b64-1b4d-4cda-ad06-43f5fc65fec3)

Why is everything impossible? 😢 

It is possible for normal windows, but you did something for Luna so it stays on top agressively and it can not be turned off...

**Comment by HIllya51** [comment]
Your logic seems a bit confused. If a regular window is set to the top, you alse cannot disappear it when you use mouse to click in your web-browser.

**Comment by Owyn** [comment]
> If a regular window is set to the top

So we just need a way to unset Luna window from the top, that's the goal here.

**Comment by HIllya51** [comment]
There is clearly a button to cancel the window top. I don't know what you really want to do.

**Comment by Owyn** [comment]
> There is clearly a button to cancel the window top. I don't know what you really want to do.

The button does not fully help, I have clicked it.
As you can see in the video above - it is not activated and the window disappears after I click Luna window then something else.
But it does not disappear when I just click something else.

**Comment by HIllya51** [comment]
I cannot understand and cannot reproduce it.
But I modified the implementation of the auto hide window so that you can read it in its entirety.

**Comment by Owyn** [comment]
> I cannot understand and cannot reproduce it. But I modified the implementation of the auto hide window so that you can read it in its entirety.

I understand why you can not reproduce.

I have just tried it in Chrome now and it works fine there.

The problem happens when you use FireFox browser https://www.mozilla.org/firefox/new/

Can you try it?

**Comment by Owyn** [comment]
😢 
It only works fine in google chrome, 
in other programs there is this problem,
I have tried: VSCode studio, cmd.exe, explorer.exe, notepad - little translation window of Luna stays when I click in other windows

**Comment by Owyn** [comment]
I think the problem is somewhere near 
`Qt::WA_ShowWithoutActivating` | 98 | Show the widget without 

because that's how it happens:
 - it shows the Luna window without activating it so it can not get deactivated when some other window is activated...

**Comment by Owyn** [comment]
Yes, I have activated window border for Luna and it clearly shows that is is not active when it pops up, that is the problem:

https://github.com/user-attachments/assets/a4abd4d3-3191-4170-aee1-39b8a3900016
