### ISSUE TITLE
Auto-adjust window position so it doesn't go out of screen border at bottom

### ISSUE THREAD

**Issue by Owyn** [HIllya51/LunaTranslator#1132]
### Expected behavior 预期的功能

This currently happens with "auto-adjust window height" option:
![image](https://github.com/user-attachments/assets/13b3f138-e6c7-4272-a453-b8e4704315cb)

Expected feature behavior:
![image](https://github.com/user-attachments/assets/9d2df7ef-426a-4c32-96db-8bd4860aec94)

and it should move the window back down there to the original position when there is less text again in the next translation (so it doesn't crawl up unintentionally)

**Comment by HIllya51** [comment]
This is also impossible to achieve. Due to the window management mechanism of Windows, manipulating the x and y coordinates of windows can easily cause them to flicker.

**Comment by Owyn** [comment]
> This is also impossible to achieve.

you can move windows with https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowpos

but I have seen windows of other problems have "dock to side of the screen" feature just fine

I don't mind a little flickering when moving - it will still be better than not being able to read the translation because it is out of the screen

**Comment by HIllya51** [comment]
That requires creating a buffering effect for the movement of the window, usually requiring at least quadratic spline interpolation, which is too troublesome and I am not interested in doing this.

**Comment by Owyn** [comment]
Why are effects needed? 
Why not just call `setwindowpos()` function and change the position? 
The position will change after that, that's all.

**Comment by HIllya51** [comment]
> This is also impossible to achieve. Due to the window management mechanism of Windows, manipulating the x and y coordinates of windows can easily cause them to flicker.这也是不可能实现的。由于 Windows 的窗口管理机制，操作窗口的 x 和 y 坐标很容易导致窗口闪烁。

You seem to have no understanding of Windows APIs. What do you think I'm using now?

**Comment by Owyn** [comment]
> What do you think I'm using now?

Nothing? Since the window doesn't move... 😃

**Comment by HIllya51** [comment]
> This is also impossible to achieve. Due to the window management mechanism of Windows, manipulating the x and y coordinates of windows can easily cause them to flicker.这也是不可能实现的。由于 Windows 的窗口管理机制，操作窗口的 x 和 y 坐标很容易导致窗口闪烁。

I have already said that moving the window will cause it to flicker, so I did not do so.

**Comment by HIllya51** [comment]
If I hadn't tested it, would I say this?

**Comment by Owyn** [comment]
> moving the window will cause it to flicker,

But I don't mind the flicker 😢 

If I just move the window up - it will get in the way of scanning original text, even if it's in the backgroud: https://github.com/HIllya51/LunaTranslator/issues/1130
So I can't really do that

**Comment by HIllya51** [comment]
I cannot accept such flickering. And it is very clear that this software is designed specifically for visual novels. If you want to read comics, why not use a more specialized software.

**Comment by Owyn** [comment]
Luna has everything other software for comics have and even more, and Luna has the most stars and users.
There are just some minor inconveniences like this.

**Comment by HIllya51** [comment]
I may need some time to consider how to do this without flickering

**Comment by Owyn** [comment]
Thank you.
And sorry for troubling you. 🫂
