### ISSUE TITLE
查词窗口置顶独立，查词自动发音和文本选取的问题

### ISSUE THREAD

**Issue by Lain1984** [HIllya51/LunaTranslator#1133]
### Expected behavior 预期的功能

使用中感觉可能会带来便利的两个功能，
1，本体的置顶和查词窗口的置顶选项似乎没法独立运作，在本体设置完置顶后查词窗口也会置顶。在查词后由于查词窗口被置顶需要关闭\最小化查词窗口才能看到游戏画面，不能直接点击游戏画面切换过去（简而言之就是节省了点x和最小化的功夫），而关掉本体置顶会导致本体无法在全屏游戏下显示翻译。研究了半天现有选项好像没法实现。

2，希望点击查词后，弹出查词窗口时能自动发音。

3，一个不知道算不算bug，文本选取功能在 _样式_ 中 _显示引擎_ 为 _Webview2_ 时，选取文字会连带选取注音的假名，而 Qt 时不会。

多谢大佬的工具，用起来越来越舒服了

**Comment by HIllya51** [comment]
1. 实现不了。而且查词窗口不置顶全屏下还怎么查词？
2. 可
3. <ruby>就这样，没办法。

**Comment by Lain1984** [comment]
> 1. 实现不了。而且查词窗口不置顶全屏下还怎么查词？
> 2. 可
> 3. <ruby>就这样，没办法。

就是弹出查词窗口的时候激活到前台而不置顶……不过不好分开实现的话就算了。或者可以曲线救国，多一个开关，失去焦点时会自动关闭查词窗口，也能做到不用每次手动点x或者最小化

**Comment by HIllya51** [comment]
。。没什么意义
