### ISSUE TITLE
hook提取逐字显示文本的游戏时，会翻译所有的提取到的内容，这会让最后的翻译结果很慢才显示出来。

### ISSUE THREAD

**Issue by Chillalalal-kira** [HIllya51/LunaTranslator#1136]
### Question 问题

游戏是《天川紗雪と屋敷の九怪奇》，开了去除重复行最后翻译结果倒是能正常显示，但在历史翻译里查看时发现，翻译时是将所有提取的到文本都逐个翻译，这对使用计费API来说不是很友好，而且让翻译结果的出现存在明显迟缓。有什么办法能解决这个问题吗？
实际上我在选择文本时只勾选了**人名**和能**一次显示完整**的文本，但**人名**的hook和**逐字显示文本**的hook是一样，而且这个逐字显示的文本是完整的，但每一个字都附上了颜色代码，可能就是因为这个原因导致重复翻译。
![屏幕截图 2024-11-05 112932](https://github.com/user-attachments/assets/902cac0b-235e-4b2c-8442-9f2681a518fa)
![屏幕截图 2024-11-05 115604](https://github.com/user-attachments/assets/e07527bb-9bde-4af7-ba6b-1eda1e931e42)

![temp](https://github.com/user-attachments/assets/851ce35f-a65d-42f8-9e36-865213e2f418)
翻译了所有提取的文本，大概有10多秒的延迟

**Comment by HIllya51** [comment]
你过滤一下不就行了。。。。。

**Comment by Chillalalal-kira** [comment]
> 你过滤一下不就行了。。。。。

似乎不起作用，我试过正则替换以及过滤<>等，还是会不断地翻译

**Comment by HIllya51** [comment]
过滤历史重复LRU

**Comment by Chillalalal-kira** [comment]
> 过滤历史重复LRU

也不行啊大佬😭

**Comment by HIllya51** [comment]
把游戏给我。

**Comment by HIllya51** [comment]
什么东西都不给，图也不截全，让我占卜吗。。

**Comment by Chillalalal-kira** [comment]
好👍

> 把游戏给我。 https://www.wenshushu.cn/

**Comment by Chillalalal-kira** [comment]
> 把游戏给我。 https://www.wenshushu.cn/
大佬，传好了
https://t.wss.pet/f/fhvv07gkq48 复制链接到浏览器打开

**Comment by HIllya51** [comment]
![屏幕截图 2024-11-05 183713](https://github.com/user-attachments/assets/93942765-6b55-47da-9402-29e43d32f8a5)

**Comment by Chillalalal-kira** [comment]
佬啊，我想问的的不是文本处理，而是自动翻译时软件会逐一地翻译所有获取的文本，相当于给翻译引擎逐个发送了20多条文本，让它逐个地翻译，由于要进行很多次翻译，这让翻译的过程显得比较漫长，等到最后显示翻译结果时已经过去了不少时间了。
佬你翻译的时候打开历史翻译看一下，雄辩不如事实😭。

@HIllya51

**Comment by HIllya51** [comment]
https://docs.lunatranslator.org/#/zh/hooksettings?id=%e5%88%b7%e6%96%b0%e5%bb%b6%e8%bf%9f

**Comment by HIllya51** [comment]
我好像知道了
