### ISSUE TITLE
sougou ocr 不好使么

### ISSUE THREAD

**Issue by lhj5426** [HIllya51/LunaTranslator#114]
RT 没有反应的样子
还有啊 打赏为什么要用爱发电呢 还得注册 麻不麻烦啊 
我用很多软件都是作者直接丢微信支付宝二维码
0 门槛  
举个例子
https://hui-zz.gitee.io/runany/#/ABOUT

![image](https://user-images.githubusercontent.com/30548000/208887798-b79cb904-5ed7-48a9-9bbe-5ecfb53018ae.png)
你这无形中增加了打赏 繁琐度 和积极性

**Comment by HIllya51** [comment]
sougouocr只支持中英文，不支持日文。
存在隐私泄露问题。而且为啥要积极打赏呢，麻烦点也好，不然容易冲动。。。

**Comment by lhj5426** [comment]
> sougouocr只支持中英文，不支持日文。 存在隐私泄露问题。而且为啥要积极打赏呢，麻烦点也好，不然容易冲动。。。

哦  我以为是从 搜狗输入法里截取的OCR呢 那个OCR 对日文很友好

**Comment by HIllya51** [comment]
这是什么软件

**Comment by HIllya51** [comment]
效果不错啊。不过好麻烦，懒得弄了。
