### ISSUE TITLE
Omertà Code:Tycoon Kai

### ISSUE THREAD

**Issue by DarkVN101** [HIllya51/LunaTranslator#1143]
### vndb link/id

https://vndb.org/v10279

### Game resource 游戏资源

https://pixeldrain.com/u/7nJkS7fn

Used emulator version
https://pixeldrain.com/u/RU8Qc4Vr

### screenshot 截图

![2024-11-06_181713](https://github.com/user-attachments/assets/4856d7a4-e374-4b90-b32e-13384ae93482)

Request for an unsupported game

**Comment by HIllya51** [comment]
give me your emulator? unknown why v0.2.0 3681 can't launch it.

**Comment by HIllya51** [comment]
[23:52:50.893] |E| [open_file]: Missing file at "********/Vita3K/Vita3K/ux0/app/PCSG00789/data/screen/title/title_01.dzi" (target path: app0:data/screen/title/title_01.dzi)

many files are missing, this zip seems imperfect
