### ISSUE TITLE
语音合成 在线引擎edge TTS播放没反应；其他在线引擎可以

### ISSUE THREAD

**Issue by xxxloli123** [HIllya51/LunaTranslator#1144]
### Version 程序版本

v5.56.2

### OS version and bits 系统版本和位数

版本	Windows 10 IoT 企业版 LTSC 版本号	21H2 安装日期	‎2024/‎8/‎25 操作系统内部版本	19044.1288 体验	Windows Feature Experience Pack 120.2212.3920.0

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/0d777bf6-61e6-4f3e-8c1e-94f7796fccd6)

### Reproduction steps 复现步骤

edge TTS播放没反应；其他在线引擎可以

**Comment by xxxloli123** [comment]
原来是：语音接口 针对大陆ip 生成的token 进行了封禁； 可以用这个链接https://github.com/rany2/edge-tts/issues/290#issuecomment-2454223245获取国外ip 生成的token; 所以嘴真的是大数据太厉害了 早上在哔哩哔哩搜 结果中午就推送

**Comment by xxxloli123** [comment]
> 原来是：语音接口 针对大陆ip 生成的token 进行了封禁； 可以用下面链接获取国外ip生成的token; 所以嘴真的是大数据太厉害了 早上在哔哩哔哩搜 结果中午就推送

https://github.com/rany2/edge-tts/issues/290#issuecomment-2454223245

**Comment by HIllya51** [comment]
挂梯子。

**Comment by gexgd0419** [comment]
目前edge-tts那边已经有了解决方案，[这个算法](https://github.com/rany2/edge-tts/issues/290#issuecomment-2464956570)可用于本地生成 `Sec-MS-GEC` 以通过验证。

**Comment by HIllya51** [comment]
> 目前edge-tts那边已经有了解决方案，[这个算法](https://github.com/rany2/edge-tts/issues/290#issuecomment-2464956570)可用于本地生成 `Sec-MS-GEC` 以通过验证。

关键是至少是从有这个tts以来，我就没有不挂梯子管用过。。。

**Comment by HIllya51** [comment]
> > > 目前edge-tts那边已经有了解决方案，[这个算法](https://github.com/rany2/edge-tts/issues/290#issuecomment-2464956570)可用于本地生成 `Sec-MS-GEC` 以通过验证。
> > 
> > 
> > 关键是至少是从有这个tts以来，我就没有不挂梯子管用过。。。
> 
> 试了一下，没啥用啊，不挂梯子连它服务器我都连不上。

看了下下面的续评，这个玩意儿不稳定，一会儿管用一会儿不管用，还是算了吧，老老实实挂梯子吧。

**Comment by HIllya51** [comment]
> > > > 目前edge-tts那边已经有了解决方案，[这个算法](https://github.com/rany2/edge-tts/issues/290#issuecomment-2464956570)可用于本地生成 `Sec-MS-GEC` 以通过验证。
> > > 
> > > 
> > > 关键是至少是从有这个tts以来，我就没有不挂梯子管用过。。。
> > 
> > 
> > 试了一下，没啥用啊，不挂梯子连它服务器我都连不上。
> 
> 看了下下面的续评，这个玩意儿不稳定，一会儿管用一会儿不管用，还是算了吧，老老实实挂梯子吧。

算了，先修了，不管用到时候再说。

**Comment by gexgd0419** [comment]
我这里不挂梯子也是可以连接的，而且没有 `Sec-MS-GEC` 至少也能建立 TCP 连接，只不过服务器返回 403 而已。
