### ISSUE TITLE
When I choose Google v2, when translating anything I get the following error: Google v2 AttributesError 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by Viettrieu1989** [HIllya51/LunaTranslator#1145]
### Version 程序版本

v5.56.2 64bit

### OS version and bits 系统版本和位数

Windows 11 pro version: 23H2 64bit

### bug's screenshot 错误截图

The error on the screen appears as the following image:
![image](https://github.com/user-attachments/assets/29867b7e-b44e-4eda-8b5a-f168259185ef)

### Reproduction steps 复现步骤

I just want to report such error. Thanks a lot.

**Comment by HIllya51** [comment]
your QPS is to high
