### ISSUE TITLE
I have set up the windows 11 livecaption.exe hook but Luna translator does not work

### ISSUE THREAD

**Issue by Viettrieu1989** [HIllya51/LunaTranslator#1146]
### Game resource 游戏资源

livecaption.exe of windows 11 pro 64 bit

### screenshot 截图

![image](https://github.com/user-attachments/assets/14df2d87-d866-4cc2-8d41-cf6cd0840350)

**Comment by HIllya51** [comment]
show the extracted text

**Comment by HIllya51** [comment]
use professional sst software instead.
