### ISSUE TITLE
最新版的“进行一次OCR”按钮不起作用

### ISSUE THREAD

**Issue by elfmm** [HIllya51/LunaTranslator#1147]
### Version 程序版本

5.56.5

### OS version and bits 系统版本和位数

win10 64位

### bug's screenshot 错误截图

<img width="497" alt="sshot-3" src="https://github.com/user-attachments/assets/e16ee91a-04a4-421f-a901-82bbe1bc477f">

### Reproduction steps 复现步骤

如题，按了按钮没反应，v5.55.4版本是可以用的

**Comment by HIllya51** [comment]
你ocr引擎失效了吧，这个按钮我整天用，几乎不可能有问题。

**Comment by elfmm** [comment]
我试了一下，新建一个配置，可以用了
沿用老的配置不行
可以关闭这个issue了
