### ISSUE TITLE
Yoshiwara Higanbana (kirikiri engine not the steam but R18 version) with furigana in the kanji doesn't hook properly and has issues in general.

### ISSUE THREAD

**Issue by chisani** [HIllya51/LunaTranslator#1148]
### vndb link/id

https://vndb.org/r30639

### Game resource 游戏资源

https://drive.google.com/file/d/1iKohNgcJhyhwap7jGZQbcqOi5cNY3BAj/view

ryuugames.com (the password)

The source of the pirate site, that i got the link from. The site has more links of the game, but ads 
https://www.ryuugames.com/yoshiwara-higanbana-free-download/

### screenshot 截图

Hello. I have the exact same issue i had with this game here and it's the same kirikiri engine. https://github.com/HIllya51/LunaHook/issues/7
But also other issues, like repeating text, especially with hiragana. Searching for a hook doesn't solve my main problem that's the kanji skipping because of the furigana.

**Comment by HIllya51** [comment]
?
![屏幕截图 2024-11-09 150640](https://github.com/user-attachments/assets/a47e9784-e204-4d64-a9ab-9825fe7506f4)

**Comment by chisani** [comment]
Sorry the images didn't add up. This hook has issues still. 
![cqftKsS0yCWe](https://github.com/user-attachments/assets/0b703e43-2753-48fa-99f7-d69195141da7)
![CoyLq0M3xeNA](https://github.com/user-attachments/assets/518dc7a8-531e-4d2f-9584-225f853f11b6)

**Comment by chisani** [comment]
> Sorry the images didn't add up. This hook has issues still. ![cqftKsS0yCWe](https://private-user-images.githubusercontent.com/145147314/384621208-0b703e43-2753-48fa-99f7-d69195141da7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjY4NDEsIm5iZiI6MTczMTE2NjU0MSwicGF0aCI6Ii8xNDUxNDczMTQvMzg0NjIxMjA4LTBiNzAzZTQzLTI3NTMtNDhmYS05OWY3LWQ2OTE5NTE0MWRhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNTM1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZWMwMGQ5N2QwNjhmMWMzNTg0YTVmZGFlNjc3ODJlYTY3MWNkOTQwY2UwZjUxZjg1Y2QzOTMzNjU4MmFiYzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1-ke1MTaPBCns1SsCI0PZCZwHbWgLuAmLhQTjbdeYJ4) ![CoyLq0M3xeNA](https://private-user-images.githubusercontent.com/145147314/384621221-518dc7a8-531e-4d2f-9584-225f853f11b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjY4NDEsIm5iZiI6MTczMTE2NjU0MSwicGF0aCI6Ii8xNDUxNDczMTQvMzg0NjIxMjIxLTUxOGRjN2E4LTUzMWUtNGQyZi05NTg0LTIyNWY4NTNmMTFiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNTM1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWVlMWYyYjU2MDU4OGU0ODM5NmY2OTQxZmFlMWU2ZGM0Njg2MTJmYTQ4NmQ5N2ViN2FlMzM1NzQ4NjlmZmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T9bb1A1FDpfy1m6r682kv5zZ_bazstaPZ0VApzsFYuk)
