### ISSUE TITLE
Gekka Ryouran Romance

### ISSUE THREAD

**Issue by Yurinomegami** [HIllya51/LunaTranslator#1149]
### vndb link/id

https://vndb.org/v7716

### Game resource 游戏资源

https://drive.google.com/file/d/1TQrS4POgRW2Anam-xtddMIPjYOsRlofP/view?usp=sharing

### screenshot 截图

![Screenshot (1)](https://github.com/user-attachments/assets/ae0d9ace-0569-418f-930a-ca97592bebb5)

**Comment by HIllya51** [comment]
![屏幕截图 2024-11-10 224015](https://github.com/user-attachments/assets/ed981b52-c11d-4162-8161-6a60a5447b62)
![屏幕截图 2024-11-10 223925](https://github.com/user-attachments/assets/31783035-f94f-404b-b585-333bf77f47d0)

**Comment by HIllya51** [comment]
attack before load game.
