### ISSUE TITLE
hook不到 麻呂の患者はガテン系 中的部分文本。

### ISSUE THREAD

**Issue by EXBJAN** [HIllya51/LunaTranslator#115]
游戏链接：https://pan.baidu.com/s/1LXcDPSdsSwYRJ3ejJjlLHw?pwd=aqtu 

读档后hook不到的文本目前遇到的全是超短文本，要么是只有一个符号，要么是单汉字，或者全是汉字，老实讲完全不需要翻译也看得懂。不过这个情况属实罕见，（vnr也提取不到）故分享给大佬研究下。

![QQ截图20221222215905](https://user-images.githubusercontent.com/117036098/209155401-b5965f23-129c-4b10-aa4a-d544b5ca50f8.png)
此外这个游戏的文本提取还有一些奇怪的情况，如上图（条目5为主要文本，条目4为次要文本）所示：
1、游戏加入已保存游戏后，启动时从头开始游戏，条目4能提取到游戏的开场字幕（开场黑景），包括上面提到的hook不到的文本。不过如果读取存档会导致条目4失效，停留在读档前的最后一条文本。
2、即使是条目4也会出现文本提取不全，如上图所示

**Comment by HIllya51** [comment]
5不是很正常？哪有问题啊

**Comment by EXBJAN** [comment]
5是主要文本没问题，但游戏对话框的少部分文本是在4里面的，然而4依然有问题，类似上图这句5中没有，4里也只有“年龄2”，不全。最重要的是，读档后4就失效了，而5依然并不会包含全部文本。

**Comment by HIllya51** [comment]
看了一下，就偶尔漏个很短的句子，影响不大。

**Comment by EXBJAN** [comment]
嗯，是这样的。
