### ISSUE TITLE
I can't find the translation sector for it.

### ISSUE THREAD

**Issue by Kherrz** [HIllya51/LunaTranslator#1152]
### Game resource 游戏资源

![image](https://github.com/user-attachments/assets/97587c02-0ed6-4803-9e9c-424ab3f11512)

### screenshot 截图

![image](https://github.com/user-attachments/assets/46f9737c-f74e-46a6-aa50-df491c365940)

**Comment by HIllya51** [comment]
Please ask questions according to the template requirements, otherwise I will ignore it.

**Comment by HIllya51** [comment]
And obviously you have found the correct text, you only need to configure the filter correctly to get the perfect text
