### ISSUE TITLE
Utawarerumono: Futari no Hakuoro

### ISSUE THREAD

**Issue by IOmar24** [HIllya51/LunaTranslator#1153]
### vndb link/id

https://vndb.org/v18717

### Game resource 游戏资源

https://mega.nz/folder/MAcliAAL#U8H27S0h1caLpuVhOEZIpQ

### screenshot 截图

![Select Text 11_11_2024 18_00_19](https://github.com/user-attachments/assets/454c56fe-6c59-49cb-ba58-a6c38b64628f)
![Utawarerumono_ Mask of Truth 11_11_2024 18_00_30](https://github.com/user-attachments/assets/1a3b490b-8d4c-4e0a-b559-ddee7650e28e)

**Comment by HIllya51** [comment]
any questions？

**Comment by IOmar24** [comment]
Thank you
