### ISSUE TITLE
Chronobox

### ISSUE THREAD

**Issue by superboo07** [HIllya51/LunaTranslator#1155]
### vndb link/id

https://vndb.org/v20144

### Game resource 游戏资源

[ryuugames.com](https://mega.nz/folder/xyMyiaxQ#cfB5Wb-sg3n3oup5F7NaDg)

### screenshot 截图

![The games functioning hook doubles text, while this screenshot is taken from my steam deck its likely this issue occurs on windows too](https://github.com/user-attachments/assets/546a5e70-f234-4461-8e28-6010c1c31b30)

**Comment by HIllya51** [comment]
？

**Comment by superboo07** [comment]
The text doubles when it shouldn't be doubling
