### ISSUE TITLE
Maji de Watashi ni Koi Shinasai!

### ISSUE THREAD

**Issue by IOmar24** [HIllya51/LunaTranslator#1156]
### vndb link/id

https://vndb.org/v1143

### Game resource 游戏资源

https://mega.nz/folder/9PcmDQyb#I1sQ4ZyMK6UapTGfQMIgaQ

### screenshot 截图

![Select Text 12_11_2024 12_27_02](https://github.com/user-attachments/assets/d47ea529-9fef-4b6e-8938-f220c4b39480)
![Majikoi! Love Me Seriously! 12_11_2024 12_27_34](https://github.com/user-attachments/assets/1d16aaba-0ded-4f7d-878a-55aead11c9b7)
![Select Text 12_11_2024 12_41_34](https://github.com/user-attachments/assets/e8430833-d8af-4a46-acb7-582a193a98a2)
![Majikoi! Love Me Seriously! 12_11_2024 12_41_44](https://github.com/user-attachments/assets/61a38222-d269-4721-b721-3108df02bc3e)

**Comment by HIllya51** [comment]
https://docs.lunatranslator.org/#/en/textprocess

**Comment by IOmar24** [comment]
> ?

The previous dialogue mixes with the new dialogue as you can see in the pictures. Is there a solution?

**Comment by HIllya51** [comment]
use japanese version

**Comment by IOmar24** [comment]
> use japanese version

Ok thanks for your work
