### ISSUE TITLE
关于选择多个hook文本的问题。

### ISSUE THREAD

**Issue by EXBJAN** [HIllya51/LunaTranslator#116]
问题一：选择了多个hook，但往往主界面文本框只显示并翻译其中一条hook项的文本。或者均会显示选取到的hook文本，但不会合并为一条文本显示，而是快速跳过只来得及翻译最后停留的文本
关于多项hook文本合并的建议→能否借鉴vnr的文本选择功能，允许用户规定文本类型：
           人名：自动显示在合并文本最前方并添加空格或者冒号
           主要：跟随在人名之后（如果有人名）
           其他：允许选取多个，按 其他1~其他n 的顺序合并（中间以分号或句号隔开）并自动合并在主要文本之后，首尾自动添加括号，如：（其他1；其他2；其他3；...其他n）

问题二：打开文本选择器，貌似选择多项hook并进行游戏的过程中易触发闪退。

**Comment by HIllya51** [comment]
太麻烦了，人名有啥好翻译的。
改了一下，多选不会被刷掉了。

**Comment by EXBJAN** [comment]
好的，辛苦了

**Comment by EXBJAN** [comment]
新问题来了，多选易导致部分翻译优化功能不能发挥作用。主要是重复行的处理。
我猜你的改动是不是先合并文本再进行翻译优化处理？

**Comment by HIllya51** [comment]
那就不要多选了。本来就不是为了人名做的。

**Comment by HIllya51** [comment]
有些游戏不同的人的话在不同的线程里面，所有才允许多选。如果不是为了这个目的的话建议不要多选了。

**Comment by EXBJAN** [comment]
好的。
不过，刚测试最新版的时候发现一个bug，更换已保存中的游戏，hook会失效或者不会自动选取hook文本，手动选取则会造成翻译器闪退，任务管理器中却会残留进程。如果手动删除残余进程，重启翻译器会出现下图多个残留的情况。我之前删除上个版本文件的时候发现有删不掉的，打开管理器一看，残留了好多个。
![QQ截图20221223130753](https://user-images.githubusercontent.com/117036098/209275796-c97bf08b-173f-497d-98cb-4c2f7447b48d.png)

**Comment by HIllya51** [comment]
怎么操作的，我试了没问题啊。。。

**Comment by EXBJAN** [comment]
打开一个已保存的游戏玩一会，这时翻译器正常提取文本翻译。然后关闭该游戏，从已保存游戏中打开别的游戏并开始游戏，大概率会出现翻译器不提取翻译的情况。打开文本选择器>手动选择hook项>点击ok，触发闪退

**Comment by HIllya51** [comment]
呃 试了几个游戏 并没有你说的问题发生。。。
要不你试试debug版，看看哪里的问题？
https://github.com/HIllya51/LunaTranslator/releases/download/v1.35.5/LunaTranslator_debug.zip

**Comment by HIllya51** [comment]
我又改了一下，让后处理单独处理每一个文本了。

**Comment by EXBJAN** [comment]
程序启动时出现第一个错误，这个应该不影响吧？
![image](https://user-images.githubusercontent.com/117036098/209284124-1450e9c7-6604-4674-8fe1-eb664d96d6e7.png)

**Comment by EXBJAN** [comment]
> 我又改了一下，让后处理单独处理每一个文本了。

好的，坐等更新

**Comment by HIllya51** [comment]
只要不卡死就不用管

**Comment by EXBJAN** [comment]
![image](https://user-images.githubusercontent.com/117036098/209290151-e7a02c4c-194d-44f1-9717-6996680f226c.png)
问题大概找到了，关闭游戏时如果未及时detach而启动其他游戏机会造成文本不提取的问题，此时打开文本选择器选择hook项则会闪退。
另外，我只在第一、二次启动debug版本中观察到部分游戏关闭后，最长15秒左右才显示该游戏的detach信息，尤其第二次启动debug版我有意再显示了detach后才启动下一个游戏，这样开关了多个游戏后，现在debug版关闭游戏后detach的速度很快。然而原版如法炮制后以正常速度打开新游戏依然会出现该问题。

**Comment by HIllya51** [comment]
已修正（可能）

**Comment by EXBJAN** [comment]
连续运行了多个游戏，一切正常。大佬牛的
