### ISSUE TITLE
Using LunaTranslator with Sugoi Toolkit

### ISSUE THREAD

**Issue by Vincent-Dawn** [HIllya51/LunaTranslator#1163]
### Question 问题

With LunaHook no longer being updated is there a way to use LunaTranslator with Sugoi Toolkit? The clipboard only seems to work for LT and I have to manually copy any text that appears in the window that displays the hooks and copied text. Also when I move the LunaHook files (with the exception of the updated Host and Hook dlls) into the LunaHook folder in plugins it says I'm not using the latest model as shown in the picture below: 

![Screenshot 2024-11-14 195705](https://github.com/user-attachments/assets/b1f3ef66-24cf-424d-8269-d2ed28de3a1c)

**Comment by HIllya51** [comment]
![屏幕截图 2024-11-15 120730](https://github.com/user-attachments/assets/00093edb-9489-4bbf-a8d3-540b674405c0)

**Comment by Vincent-Dawn** [comment]
What I meant was for Sugoi's own offline or DeepL window. I don't know where to find the api for V10.

**Comment by HIllya51** [comment]
If he did not intentionally modify the interface, then v10 and v8 should be the same interface. 

And Luna also supports DeepL.
