### ISSUE TITLE
OCR problem

### ISSUE THREAD

**Issue by gqwg2003** [HIllya51/LunaTranslator#1165]
### Version 程序版本

6.2.1

### OS version and bits 系统版本和位数

windows 10 Pro  64-bit

### bug's screenshot 错误截图

the error of updating and scanning the text appears immediately or after several minutes or more of the selected area OCR 

scanning and updating frames stopped
used offline OCR

### Reproduction steps 复现步骤

please check I had such errors

**Comment by HIllya51** [comment]
Please fill in the template requirements to ask questions.

**Comment by gqwg2003** [comment]
![Снимок экрана 2024-11-16 104351](https://github.com/user-attachments/assets/178e5ce9-c8d4-42a3-bedd-8b8bf8181a4b)
 
there are also other errors like updates hanging and scanning communication.
and yes online doesn't help

**Comment by HIllya51** [comment]
I don't understand what you're saying. 
And this renpy game can obviously use hook to extract text, why do you want to use OCR?

**Comment by gqwg2003** [comment]
I don't use it because it's inconvenient for me 

I'm used to using OCR 

Please just check for errors OCR .

**Comment by gqwg2003** [comment]
The function is good, I use HOOK in some games, but not in this one.  

so a big request: check for OCR errors, I will be very grateful

**Comment by HIllya51** [comment]
Why don't you provide any information? Do you want me to guess what's wrong with you?

**Comment by HIllya51** [comment]
Why do you only provide a simple screenshot without mentioning any issues? I didn't find any errors.

**Comment by gqwg2003** [comment]
Please don't be angry, forgive me.  I deeply apologize.  

I'll try to reinstall it again.  I apologize very much.   please forgive me I didn't mean to disturb you I'm very sorry

**Comment by HIllya51** [comment]
I am not angry..
I just feel that communicating with you is a bit difficult. And you didn't explain the problem clearly either.

**Comment by gqwg2003** [comment]
Thank you very much for not being angry.
I know I'm a difficult person to talk to so I understand you.  Thank you very much, you communicate with me no matter what. 
You see, it’s hard for me to communicate in other languages.  that's why it's hard for me to explain what I mean.

In a word, thank you very much.

**Comment by HIllya51** [comment]
So can you explain clearly what your problem is? I don't want to hear you talk about these irrelevant contents

**Comment by gqwg2003** [comment]
Error explanation 
error number 1 - after prolonged use the picture stops updating?
error number 2 - sometimes such an error occurs, how How does the text stop being scanned online and offline OCR
error number 3 - sometimes there are 2 such errors at once.
error number 4 - does this error ever occur cannot find selection area.

**Comment by HIllya51** [comment]
switch to Periodic Execution
https://docs.lunatranslator.org/#/ru/ocrparam?id=%d0%9f%d0%b5%d1%80%d0%b8%d0%be%d0%b4%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%be%d0%b5-%d0%b2%d1%8b%d0%bf%d0%be%d0%bb%d0%bd%d0%b5%d0%bd%d0%b8%d0%b5

**Comment by gqwg2003** [comment]
Thank you very much for the tip
