### ISSUE TITLE
transcription function.

### ISSUE THREAD

**Issue by gqwg2003** [HIllya51/LunaTranslator#1166]
### Expected behavior 预期的功能

you can use an audio file and translate the voice into text and then translate the same text into other languages  

and you can also add back formatting of text in an audio file already translated text

### Alternative behavior (optional) 近似的功能（可选）

I kindly ask you to evaluate my proposal  👍 👎

thank you very much for watching as the author many thanks for your work

**Comment by HIllya51** [comment]
You should look for other software specifically designed for speech recognition.

**Comment by gqwg2003** [comment]
Thank you very much for your answer.
