### ISSUE TITLE
”网络设置“界面UI出错

### ISSUE THREAD

**Issue by Ptilopsis01** [HIllya51/LunaTranslator#1167]
### Version 程序版本

6.2.1

### OS version and bits 系统版本和位数

win11 24h2 64

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/b9ad2922-9424-4626-a8d9-dac2b9629bca)

### Reproduction steps 复现步骤

每次点进”网络设置“界面都会把UI复制显示一遍

**Comment by HIllya51** [comment]
你是不是自动更新出岔子了，我测试没问题

**Comment by Ptilopsis01** [comment]
> 你是不是自动更新出岔子了，我测试没问题

我把除了userconfig之外的文件夹都删了重新安装，还是能复现

**Comment by HIllya51** [comment]
啊这。那你把userconfig发我看看？

**Comment by HIllya51** [comment]
dd

**Comment by Ptilopsis01** [comment]
> 啊这。那你把userconfig发我看看？

OK
[userconfig.zip](https://github.com/user-attachments/files/17786996/userconfig.zip)

**Comment by HIllya51** [comment]
你手动把这3行删掉吧，这是不知道什么远古版本的配置升级过来导致有一点点格式不兼容的问题，我这里用代码不太好改。。。

![屏幕截图 2024-11-16 235304](https://github.com/user-attachments/assets/b966dcc0-0420-403f-be35-21e8b9f02fdd)

**Comment by Ptilopsis01** [comment]
OK解决了，谢谢
