### ISSUE TITLE
VOICEVOX、VoiceRoid2无法朗读

### ISSUE THREAD

**Issue by ltyx8** [HIllya51/LunaTranslator#117]
下载debug版提示 using null output device, none available

**Comment by HIllya51** [comment]
麻烦放截图。。。。。。

**Comment by ltyx8** [comment]
![捕获](https://user-images.githubusercontent.com/68658399/209385213-6b64fceb-6f24-44e3-bf20-d0217647e38e.PNG)

**Comment by ltyx8** [comment]
上面是 VOICEVOX
VoiceRoid2只有 using null output device, none available 这一条提示

**Comment by HIllya51** [comment]
已修正
