### ISSUE TITLE
livemaker制作的游戏，识别不了文字

### ISSUE THREAD

**Issue by mmuuyyii** [HIllya51/LunaTranslator#1170]
### Game resource 游戏资源

https://drive.google.com/drive/folders/1WLgpSOWkA7JClR6i88b4e4G5qJP1qH2_?usp=sharing

### screenshot 截图

![文本翻译截图](https://github.com/user-attachments/assets/39ed2160-adc9-4d27-b6d2-c52c43294bc6)
![游戏截图](https://github.com/user-attachments/assets/9efd744e-28a0-469b-9f71-76f5eaecae5c)

**Comment by HIllya51** [comment]
?
![屏幕截图 2024-11-17 130830](https://github.com/user-attachments/assets/f8056cf0-612d-4083-8729-093cc449976c)

**Comment by mmuuyyii** [comment]
明白了，是local emulator的问题。
之前用le转码识别不了hook，不转码还反而能识别（虽然是乱码）
改了下le的设置就成了
