### ISSUE TITLE
希望anki词卡功能能添加更多编辑选项

### ISSUE THREAD

**Issue by wuyou36163** [HIllya51/LunaTranslator#1174]
### Expected behavior 预期的功能

希望能做到类似Yomitan（Yomichan）中anki词卡类似的功能，提高自定义程度：
1. 通过anki connect连接之后能够自动识别anki中已内置的笔记模板，同时读取该笔记模板中的字段信息

2. luna中用户的每次查词信息返回若干子项，如：纯假名、原句中单词、经过mecab之后返回的辞书形（汉字+送り仮名、振り仮名）、音调、截图、语音、词典，用户可将其填入上述模板中的字段（不熟悉的用户或许可以提供默认模板）

如此一来，用户在luna侧无需对词卡模板进行调整，而且可以方便套用anki词卡中已建好的模板，自定义化程度更高。希望能予以考虑~

以下是yomitan中可供用户填入词卡字段的部分内容：
<img width="674" alt="截屏2024-11-20 03 10 06" src="https://github.com/user-attachments/assets/2046352a-9e98-40e4-b55a-a0d536939b94">
<img width="672" alt="截屏2024-11-20 03 10 30" src="https://github.com/user-attachments/assets/84114b8e-e06b-48ec-8ed8-130c2a8af9e1">

**Comment by HIllya51** [comment]
不行，会破坏现有兼容。而且字段功能都不一样，无法对应。
