### ISSUE TITLE
Danganronpa Another ~Tto Hanaui Jeolmang Hagwon~

### ISSUE THREAD

**Issue by Mosencrantz** [HIllya51/LunaTranslator#1177]
### vndb link/id

https://vndb.org/v31661

### Game resource 游戏资源

https://drive.google.com/file/d/0ByKlNYSo1-H7bWFQd2ZOdGpJdnM/view?resourcekey=0-kPhAgSLLVpvC_GJcVonO1A

Might need to run the game with Korean locale emulator or Windows 7 compatibility mode

If you can't run RPG_RT.exe please download the [EasyRPG Player](https://easyrpg.org/player/downloads/) executable, drop it on the game folder and run Player.exe instead, although I believe RPG_RT.exe would be easier to hook if you can run it

### screenshot 截图

![image](https://github.com/user-attachments/assets/36e8af05-5dd6-4509-a9d7-1a0cb175604c)

**Comment by HIllya51** [comment]
?
![屏幕截图 2024-11-21 153656](https://github.com/user-attachments/assets/3243e023-be04-463f-9f6a-183332be7b56)
