### ISSUE TITLE
Super Danganronpa Another 2 ~Huimangui Dalgwa Jeolmangui Taeyang~

### ISSUE THREAD

**Issue by Mosencrantz** [HIllya51/LunaTranslator#1178]
### vndb link/id

https://vndb.org/v31662

### Game resource 游戏资源

https://drive.google.com/file/d/1CDYVaJKE4QgsYXoVzL7a0ZNVvOlW3NEs/view?usp=sharing

### screenshot 截图

![image](https://github.com/user-attachments/assets/c2f65092-5324-44c8-bb55-fd3fbdd21108)

**Comment by HIllya51** [comment]
?
![屏幕截图 2024-11-21 152425](https://github.com/user-attachments/assets/409136fa-cd1c-4250-ae7d-6669c1d1ec39)

**Comment by Mosencrantz** [comment]
> ? ![屏幕截图 2024-11-21 152425](https://private-user-images.githubusercontent.com/101191390/388398793-409136fa-cd1c-4250-ae7d-6669c1d1ec39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzYwODYsIm5iZiI6MTczMjE3NTc4NiwicGF0aCI6Ii8xMDExOTEzOTAvMzg4Mzk4NzkzLTQwOTEzNmZhLWNkMWMtNDI1MC1hZTdkLTY2NjljMWQxZWMzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQwNzU2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2Q4YWU0MTM0NGI0ZjVjM2MzYjMwZGMyY2FkMDEyMWIyN2EwMzI4MmMwZGJlN2NjNzc4MGQyMjg0NDc5MzBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0B_dcK1vIU4GUg1fRIDDht8RvWgnpcZ3iCxs34Nc8ko)

What character encoding were you using in the settings? These didn't show up for me with Korean encoding
