### ISSUE TITLE
RJ01142344\西の森の魔女

### ISSUE THREAD

**Issue by Kyle-Kirsten** [HIllya51/LunaTranslator#1179]
### vndb link/id

dlsite: RJ01142344

### Game resource 游戏资源

https://drive.google.com/file/d/1BFpxQGJQYNbiNydvcNu6cNDiQRq_5K5x/view

### screenshot 截图

![image](https://github.com/user-attachments/assets/b1255c6f-3e38-407a-8d49-d20dde5a1950)
![image](https://github.com/user-attachments/assets/f44820dc-350b-442c-99d5-a4674f214f17)

**Comment by HIllya51** [comment]
？

![屏幕截图 2024-11-22 014145](https://github.com/user-attachments/assets/2d98e7a7-30df-464e-96b9-ac54971cd5cd)
