### ISSUE TITLE
片假名显示问题

### ISSUE THREAD

**Issue by flaccida** [HIllya51/LunaTranslator#118]
![image](https://user-images.githubusercontent.com/54014412/209457414-3c23a9bc-eea4-4889-98de-20570d9ec2bc.png)
如图，第一个词的片假名显示到行下去了…

字体：微软雅黑
大小：15.0

**Comment by HIllya51** [comment]
![屏幕截图 2022-12-25 130416](https://user-images.githubusercontent.com/101191390/209457556-b2facdc9-9b53-485e-8e5b-4b7aab55e036.jpg)
呃 测试没找到问题。。。

**Comment by HIllya51** [comment]
调下窗口宽度试试？（我猜的

**Comment by flaccida** [comment]
![image](https://user-images.githubusercontent.com/54014412/209457656-aed4c12a-a584-4f2c-8b35-ea7fc33eba98.png)
好像没用（悲
系统缩放是200%

**Comment by flaccida** [comment]
还有一个问题，在开启代理并使用weblio辞书时，有时候查词窗口会卡半天才有反应

**Comment by flaccida** [comment]
哦，我发现了，文本输入源选剪贴板才会有这个片假名显示问题，选OCR就没事

**Comment by HIllya51** [comment]
> 哦，我发现了，文本输入源选剪贴板才会有这个片假名显示问题，选OCR就没事 估计是我的文本开头有什么不可见字符？

应该是


> 还有一个问题，在开启代理并使用weblio辞书时，有时候查词窗口会卡半天才有反应

版本问题？这个我修过了

**Comment by flaccida** [comment]
> 版本问题？这个我修过了
是新版本
