### ISSUE TITLE
文本框一直有闪烁光标无法过滤

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaTranslator#1180]
### Question 问题

游戏镜像+模拟器：https://mega.nz/file/MP8VQQZR#JszGGL-h0okPLW4wC6-UmzCb_2yOVgV5ciwgGsOYHts
![1](https://github.com/user-attachments/assets/394a6c6d-3cee-427f-99d5-3201c3a50768)
十几秒的演示视频，具体就是还没来得及翻译就被刷过去了
https://gofile.io/d/0giax9

**Comment by HIllya51** [comment]
试了一下，你把点前面的那个日语空格单独加一行来过滤就可以了

**Comment by HIllya51** [comment]
空格和点，各自一行来过滤

**Comment by qscasdasd** [comment]
> 空格和点，各自一行来过滤

还是不太行，可能是我其他设置的问题？能把你的其他设置给我看看吗

**Comment by HIllya51** [comment]
![屏幕截图 2024-11-22 211934](https://github.com/user-attachments/assets/c66b0e1b-c13d-4bcf-9927-0e3a404b0e91)
![屏幕截图 2024-11-22 212534](https://github.com/user-attachments/assets/8ca7a98d-71eb-42a8-be73-b58fb67665ec)
