### ISSUE TITLE
Taishou Mebiusline Taizen

### ISSUE THREAD

**Issue by DarkVN101** [HIllya51/LunaTranslator#1182]
### vndb link/id

https://vndb.org/v2088

### Game resource 游戏资源

https://drive.google.com/file/d/1gwoJCOde0XKHYbrZCJvEEf5vTZBi3L4p/view?usp=drive_link

### screenshot 截图

![2024-11-22_222119](https://github.com/user-attachments/assets/d0e821b4-7ada-46a4-88da-3941cbbad0a0)

Request for an unsupported game

**Comment by HIllya51** [comment]
invalid download link

**Comment by DarkVN101** [comment]
Sorry now I am uploading the file in pixeldrain I forgot that fichier does not work in some countries.

**Comment by HIllya51** [comment]
Don't give me those cloud drives with download speeds of only a few tens of kb per second. Do you want me to spend several days downloading them?

**Comment by DarkVN101** [comment]
New link
