### ISSUE TITLE
新版本無法打,開被殺毒

### ISSUE THREAD

**Issue by Raiter123** [HIllya51/LunaTranslator#1184]
### Version 程序版本

6.6.1 32ver

### OS version and bits 系统版本和位数

window 11

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/9611cdb2-dc91-48b7-98bb-5002946c3a6a)

### Reproduction steps 复现步骤

下載完后就會出現.
如果重新打開程序又會出現這個
![image](https://github.com/user-attachments/assets/63104a92-12a6-4a08-a831-3c490e6ffe03)
如果關上殺毒也是打不開,重新下載也是一樣,然後64版的直接被殺毒

**Comment by HIllya51** [comment]
请不要问这种让人很无语的问题行吗。
