### ISSUE TITLE
Bringing back Deepseek AI & ThebAI

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#1189]
### Expected behavior 预期的功能

Please bring back Deepseek and theb to browser debug section of translators.
Both these sites **do not require registration**. Everyone can log in just with google account.

- Deepseek provides exceptionally good quality of translation and its old model is completely free 
- Theb gives access to multiple AI translators and it is without limitation in comparison to DuckDuck Go where after 20-25 requests you hit a daily limit.

**Comment by HIllya51** [comment]
if you update inplace, they will not be auto deleted. if you delete the old, they will not back.

**Comment by Farooq87** [comment]
> if you update inplace, they will not be auto deleted. if you delete the old, they will not back.

@HIllya51 
You mean update with copy/paste with replacing old files or update through Luna's settings?

**Comment by Farooq87** [comment]
@HIllya51 
Because when you update manually replacing old files with copy/paste it causes bug of DeeplX. DeeplX ceases to work after it and you haveto delete old and get new Luna.
