### ISSUE TITLE
现在可以支持rpgmaker的作品嘛？

### ISSUE THREAD

**Issue by zzm1918** [HIllya51/LunaTranslator#119]
现在日本的同人rpg大部分都是rpgmaker的作品，但是用luna似乎没法正常找到文本，但是用御坂翻译勾选64位后可以抓到文本。是我用法问题吗？还是现在还不支持了。

**Comment by HIllya51** [comment]
不过好像确实有点问题 等我改一下吧

**Comment by HIllya51** [comment]
已修正

**Comment by EXBJAN** [comment]
居然可以hook rpgmaker了，棒棒！
不过rpg有专门的翻译及作弊整合工具——MTool，它的翻译是内嵌覆盖翻译的，不过翻译质量嘛要自己调教，随着版本更新，也是越来越香了

**Comment by zzm1918** [comment]
好耶
