### ISSUE TITLE
泡沫のユークロニア

### ISSUE THREAD

**Issue by SnuggleNoodle** [HIllya51/LunaTranslator#1190]
### vndb link/id

v40519

### Game resource 游戏资源

在YUZU 1734里运行了这个游戏，但是hook一直不到字，而且也被当做是别的游戏。
本体: [https://drive.google.com/file/d/1xj78idOrX1Qn0HOdjEt-6uc8N6bLb6pr/view?usp=drive_link](url)
补丁升级: [https://drive.google.com/file/d/1nMf4GpT19kOjkWUZNrtmaMiV5I5GUk7L/view?usp=drive_link](url)

### screenshot 截图

![ce72ee30c8a844877d2aa6756a655beb](https://github.com/user-attachments/assets/c109dcad-bb52-4f7f-a529-601ca49504d4)

**Comment by HIllya51** [comment]
你是先hook，再运行游戏的吗？这作是已经适配过的。

**Comment by SnuggleNoodle** [comment]
![QQ20241127-232056](https://github.com/user-attachments/assets/f956714c-279d-4ba3-a2fe-ce94f4cbb837)
我更新到了最新版，并且完全按照b站最新视频一步一步做的。但是也只能Hook到乱码或者什么都hook不到。打开游戏设置它的路径是对准的YUZU.exe，但是不知道为什么好像定位了honey vibes那个游戏(vndb id都是honey vibes)的。

**Comment by HIllya51** [comment]
你不要管主窗口现在的名字，那个只是你第一次hook时记录的游戏名，后面不会变。
你更新一下yuzu的版本，我测试是没问题的。

**Comment by SnuggleNoodle** [comment]
yuzu 1734应该已经是最新版了
我这次直接录了视频，但这次没有出现乱码，而是没有hook到任何字。如果我有步骤做错，请指教！
[https://drive.google.com/file/d/1SZ0Z2ME4PM7ehaAQjvw9g3FO30qPmCrT/view?usp=sharing](url)

**Comment by HIllya51** [comment]
看一下日志信息

**Comment by HIllya51** [comment]
你更新一下再试试
