### ISSUE TITLE
 Neko Project 21/W

### ISSUE THREAD

**Issue by linakima** [HIllya51/LunaTranslator#1192]
### Question 问题

Can you add support the [Neko Project 21/W emulator](https://simk98.github.io/np21w/download.html) for translating novels developed for the PC98 platform?
At the bottom of the page, it says that the emulator has the ability to hook text. This may help you.

Unfortunately the emulator crashes when I try to select a process with LunaTranslator.
Text capture via RetroArch emulator does not work. Tested on [Virgin Angel](https://vndb.org/v8718) game.

![1](https://github.com/user-attachments/assets/ba6e3cbb-7a20-4434-9559-38b2064a06de)

https://pixeldrain.com/u/zCvvcX8t

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/issues/new?assignees=&labels=enhancement&projects=&template=01_game_request.yaml
