### ISSUE TITLE
尚未支持的游戏

### ISSUE THREAD

**Issue by yangxi1116** [HIllya51/LunaTranslator#1196]
### vndb link/id

https://vndb.org/v26640/魔王の娘と外道勇者～紅の瞳と白き淫濁～

### Game resource 游戏资源

https://1drv.ms/u/s!At0vERyWT3tVepNhznKg7OzOJyo?e=aeNwXJ

### screenshot 截图

![屏幕截图 2024-12-01 221430](https://github.com/user-attachments/assets/93f13296-0d43-4a1b-a738-3d9c4a79b532)

**Comment by HIllya51** [comment]
游戏打不开也来问我？ybb

![屏幕截图 2024-12-02 002504](https://github.com/user-attachments/assets/949839f8-70cd-4bc5-aab3-2ea84430cd39)

**Comment by yangxi1116** [comment]
怪事，我再试试吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月2日(周一) 凌晨0:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HIllya51/LunaTranslator] 尚未支持的游戏 (Issue #1196)




 
？
 
2024-12-02.002504.png (view on web)
