### ISSUE TITLE
和風ADV 睡蓮草子: unsupported game, cannot hook text

### ISSUE THREAD

**Issue by lllthhh** [HIllya51/LunaTranslator#1197]
### vndb link/id

it's a game on booth and it doesn't have vndb link

### Game resource 游戏资源

https://317.booth.pm/items/1671263
MEGA: https://mega.nz/file/o7c3iBjD#ueFQCny-9Vv7Nt7AmYQ9cGuq0tqW-MyPn8EdWaGN7zE

### screenshot 截图

![Screenshot (3156)](https://github.com/user-attachments/assets/534fe146-7b29-4d31-bd4e-69885148fbe7)

**Comment by HIllya51** [comment]
Manually select these ****.tmp processes's process id

![屏幕截图 2024-12-02 002035](https://github.com/user-attachments/assets/5d1c1726-dfcf-4d36-b7ef-67b3dfa126a2)
![屏幕截图 2024-12-02 002055](https://github.com/user-attachments/assets/c5b16582-0ead-49d1-b20d-bed9193a078f)

**Comment by lllthhh** [comment]
It works with C:\$Extend\$Deleted\00390000000322AB2341DB4E. Thank you so much!
