### ISSUE TITLE
两行的对话只能识别到后面一行

### ISSUE THREAD

**Issue by zzm88** [HIllya51/LunaTranslator#1199]
### Question 问题

![image](https://github.com/user-attachments/assets/138d1a94-ba04-423e-a0cf-fb0a1357b5e1)

**Comment by HIllya51** [comment]
你用第五行的不就行了吗

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/issues/new?assignees=&labels=enhancement&projects=&template=01_game_request.yaml

而且就算没有第五行的，你连游戏都不发搞毛呢？

**Comment by HIllya51** [comment]
你是不是眼神不太好，哪里只有后面一行了？

**Comment by HIllya51** [comment]
默认的刷新延迟500，不懂不要乱改行吧？
