### ISSUE TITLE
人工字幕来个教程呗

### ISSUE THREAD

**Issue by lhj5426** [HIllya51/LunaTranslator#12]
咋用呀大佬PDF的教程还是1.6 现在已经1.95了 教程貌似该更新了 
![image](https://user-images.githubusercontent.com/30548000/195188507-aa831656-fcb4-4bb7-80d7-aad832bea692.png)
开启录制之后发现log会记录文本 要怎么替换呀？

**Comment by HIllya51** [comment]
这不是bug呀。。。这个log只是简单的记录一下所有的提取和翻译记录，程序不会使用到它的，但是它可以让你自己去打开它看看自己之前翻过什么内容，感觉也挺有用的呀。。。
开启录制后录制的文件放在transkiroku这个文件夹下面了，这个文件夹里的sqlite文件是可以被加载的。
使用的话只要在翻译设置里面打勾然后指定sqlite文件名就行了呀。。。
教程的话只能随缘了，看什么时候有空，写文档什么的最讨厌了qaq

**Comment by hiroi-sora** [comment]
> 写文档什么的最讨厌了qaq

哈哈哈哈 没毛病

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/195253494-b4343a77-a381-4690-a80a-895c124a3eff.png)
随便录了几句 会生成一个无法编辑的Yuuri-to-Marin.log 文档？

**Comment by HIllya51** [comment]
你是玩的「友莉と真凜は癒やしてあげたい」吗？我还专门下下来试了一下，没问题啊。
https://i.postimg.cc/HJhb2H36/2022-10-12-130741.jpg
https://i.postimg.cc/zLBnK3wL/2022-10-12-130810.jpg
不过可能是后缀名不知道为什么错了吧，内容应该还是对的，这是个sqlite文件，你用notepad当然打不开的

**Comment by HIllya51** [comment]
https://i.postimg.cc/bwrZfcrV/2022-10-12-131145.jpg
内容是对的。不知道为什么你那里后缀成.log了。问题不大。

**Comment by lhj5426** [comment]
> 你是玩的「友莉と真凜は癒やしてあげたい」吗？我还专门下下来试了一下，没问题啊。 https://i.postimg.cc/HJhb2H36/2022-10-12-130741.jpg https://i.postimg.cc/zLBnK3wL/2022-10-12-130810.jpg 不过可能是后缀名不知道为什么错了吧，内容应该还是对的，这是个sqlite文件，你用notepad当然打不开的

嗯 随便打开一个想试试 人工字幕这个新功能 嗯 这个是BUG么 没生成后缀为sqlite 的文件哈哈 我就当文档了

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/195255971-6861ab26-398e-4dd7-8290-16900922d8e9.png)
但是好像没录到翻译 ？

**Comment by lhj5426** [comment]
你这个图床我打不开看不到发了什么哈哈 好尴尬

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/195256654-90bcad56-a93a-4f78-875d-8455462e2483.png)
是不是因为抓到的程序是.LOG所以没有生成sqlite 在HOOK游戏的时候程序名就是这个.LOG

**Comment by HIllya51** [comment]
你可以看一下是不是录制的翻译源是不是没有开启。目前设定的是只录制选定的翻译源。后面可以改一下。。

**Comment by HIllya51** [comment]
还真是，我是把.exe替换成.sqlite作为文件名的。。。
话说你这个游戏怎么是.log结尾的啊😂
https://i.postimg.cc/htmft88V/2022-10-12-132315.jpg

**Comment by lhj5426** [comment]
> 还真是，我是把.exe替换成.sqlite作为文件名的。。。 话说你这个游戏怎么是.log结尾的啊😂 https://i.postimg.cc/htmft88V/2022-10-12-132315.jpg

开启了
![image](https://user-images.githubusercontent.com/30548000/195257030-280b47d6-a47e-4ce6-af84-bab108495772.png)
然后我是转区运行的程序 
![image](https://user-images.githubusercontent.com/30548000/195257101-97856469-911a-4b90-ac08-9d9c3025dc6e.png)

**Comment by lhj5426** [comment]
直接转区运行 在任务管理器里就是这个样子
![image](https://user-images.githubusercontent.com/30548000/195257596-48d90444-016e-4e9f-8f0f-eaddf916f3ab.png)

**Comment by HIllya51** [comment]
emmm 我用le专区运行并没有这个问题，可能是runany包了太多层了吧。。
https://i.postimg.cc/gksnXc12/2022-10-12-132950.jpg

我刚才试了一下搜狗2也是没问题的😂
是不是用的软件的问题，你打开aritficatrans那个表看看，我用sqlite-gui打开并没有看到有sqlite-sequence这个表

**Comment by lhj5426** [comment]
> emmm 我用le专区运行并没有这个问题，可能是runany包了太多层了吧。。 https://i.postimg.cc/gksnXc12/2022-10-12-132950.jpg
> 
> 我刚才试了一下搜狗2也是没问题的😂 是不是用的软件的问题，你打开aritficatrans那个表看看，我用sqlite-gui打开并没有看到有sqlite-sequence这个表

![image](https://user-images.githubusercontent.com/30548000/195259647-54424d20-8689-4926-8581-b3d55f12e1af.png)
嗯重新录了一遍 有了 
话说这个就可以自己修改游戏文本然后打到翻译软件里来显示了是嘛
有点类似VNR的那种人工字幕？
![image](https://user-images.githubusercontent.com/30548000/195260139-ebfbd86f-47b2-4774-8a1c-86dd876bee5a.png)
![image](https://user-images.githubusercontent.com/30548000/195260157-59bc43d0-4ffe-4edf-b4d2-ab6b5d6dac85.png)
看样子不错喔~

**Comment by lhj5426** [comment]
之前有一部游戏非常想搞人工翻译可是VNR那个软件太卡了玩人工字幕都玩的不舒服
这次用这个试试 感觉可以试试

**Comment by HIllya51** [comment]
修改的话从usertrans里面改就行，读取的时候优先读usertrans，usertrans没有再读machinetrans，不然可能会被新的机翻给覆盖掉。。。

**Comment by lhj5426** [comment]
> 修改的话从usertrans里面改就行，读取的时候优先读usertrans，usertrans没有再读machinetrans，不然可能会被新的_机翻_给覆盖掉。。。

嗯我刚才直接在录入的机翻位置machinetrans 修改的哈哈  
我知道了 后台挂着游戏自动跑完一个HS先 搞一个试试

**Comment by lhj5426** [comment]
话说快进的时候会记录文本吗

**Comment by HIllya51** [comment]
最好不要快进，因为textractor是有刷新间隔的，快进的话中间会有一大片文字连成一块会直接过滤掉。

**Comment by HIllya51** [comment]
而且翻译器请求频率太高也会被403一段时间

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/195264752-210d3908-c573-449f-8061-6b9fbe77da1a.mp4

话说默认进场景 第一句话不会被读取这个是 textractor 的bug吧

不 我的意思 开着人工录制 但是 不录制任何的机器翻译文本  只提取 游戏文本
然后 打开sqlite 去一句一句编辑 
就像刚才

https://github.com/HIllya51/LunaTranslator/issues/12#issuecomment-1275600727
只抓到了 游戏文本这样

**Comment by lhj5426** [comment]
像这样被忽略的 第一句
手动添加到 sqlite 可以被识别吗？

**Comment by HIllya51** [comment]
这个可能和游戏有关。手动添加就行。

**Comment by lhj5426** [comment]
> 这个可能和游戏有关。手动添加就行。

确实和游戏有关系开原版Textractor 也是第一句不会读取
不会读取原文 添加翻译也没用因为根本不读取第一句的原文 哈哈  只从鼠标点击或者自动播放的第二句开始

**Comment by lhj5426** [comment]
人工字幕 提取游戏文本成数据库的时候 挂Jbeijing 本地跑就行不需要走网络反正后续翻译也要全部重来质量就无所谓了主要得到游戏原文和数据库

**Comment by HIllya51** [comment]
不翻译只存原文都行。

**Comment by lhj5426** [comment]
> 不翻译只存原文都行。

![image](https://user-images.githubusercontent.com/30548000/195299945-d5d1d9f7-c261-4965-84e9-c4937fcd42cc.png)
是么我再 去不开任何翻译提取下原文 
话说一个游戏只生成一个文件哈他是自己会对应文本吗

**Comment by HIllya51** [comment]
直接在sqlite里面查原文对应的翻译啊。什么意思

**Comment by lhj5426** [comment]
> 直接在sqlite里面查原文对应的翻译啊。什么意思

哈哈没事 一个场景分成一个独立的数据库了 这样不乱 也不会因为看着几千条数据而打怵  几百行一个文本还是有点干劲的哈哈
![image](https://user-images.githubusercontent.com/30548000/195312865-94db9674-aff3-4d8f-850b-b83f33116452.png)

**Comment by HIllya51** [comment]
你在翻译设置里面选择sqlite文件了吗？没有的话不会自动加载的。

**Comment by lhj5426** [comment]
> 你在翻译设置里面选择sqlite文件了吗？没有的话不会自动加载的。

当然设置啦 我先翻译了23句 然导入看效果 就发现有不读取的

**Comment by HIllya51** [comment]
emmm 发现了。在输入给人工翻译前文字被预处理了。。。所有找不到了😂一会修一下。。。

**Comment by HIllya51** [comment]
不对 我再看一下

**Comment by HIllya51** [comment]
还真是被处理了，被名词翻译给处理掉了 一会修一下。

**Comment by lhj5426** [comment]
> 还真是被处理了，被名词翻译给处理掉了 一会修一下。

一步一个脚印哈哈

**Comment by HIllya51** [comment]
改了一下 录的时候录成sqlite，录完转成json文件方便修改，读取读取json文件

**Comment by lhj5426** [comment]
> 改了一下 录的时候录成sqlite，录完转成json文件方便修改，读取读取json文件

我把之前的录的文件转换了 然后 现在是这个效果
![image](https://user-images.githubusercontent.com/30548000/195377042-9c1c84b6-4808-415f-a50b-cc7c46fb8de2.png)

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/195379047-a2095516-29e6-48e7-8a0c-3cc07fb7daa1.png)
重新录的文件

**Comment by HIllya51** [comment]
话说 是只有这一句还是所有都不行。
你做了额外的处理了吗，我提取出来文字后面都有一个%K%P

**Comment by HIllya51** [comment]
https://i.postimg.cc/wMnH3gjx/2022-10-13-003303.jpg
啥情况

**Comment by lhj5426** [comment]
> 话说 是只有这一句还是所有都不行。 你做了额外的处理了吗，我提取出来文字后面都有一个%K%P
我去 掉了 后边的 %K%P这种肯定要额外处理吧通过
![image](https://user-images.githubusercontent.com/30548000/195404305-8c19d084-d213-4f48-ae53-3637fb732045.png)

**Comment by lhj5426** [comment]
换了JSON之后我是是整个都都是 无预翻译 原先的和 后来录再转json 读JSON 都不行 我编辑JSON 编码是utf8 跟这个编码有没有关系

**Comment by HIllya51** [comment]
ctrl了半天找到你HS1的位置了，这回应该解决了😂
这个游戏不错，画风有点喜欢

**Comment by lhj5426** [comment]
> ctrl了半天找到你HS1的位置了，这回应该解决了😂 这个游戏不错，画风有点喜欢

P:\GAL\220128\全CG存档.zip
[全CG存档.zip](https://github.com/HIllya51/LunaTranslator/files/9771641/CG.zip)
抱歉才看到  全CG存档 这个是
嗯 这游戏18年初的 然后22年出了动态版 本来就很喜欢
出了动态版更是很爱 哈哈 这就去试试新的

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/195528922-91056b7b-1788-42e7-99a5-a841c46e2aae.png)
这次好像是真的修好了

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/195531552-6feb5966-34d3-481b-8e65-6c54d8624fb4.mp4

这次是真修好了  前边是瞎写的测试人工翻译文字
后边没有写人工文本 直接是读取了 Jbeijing 录制的文本

**Comment by lhj5426** [comment]
非常感谢大佬
这就可以戴上痛苦面具去慢慢搞了 9个HS
