### ISSUE TITLE
最小化到任务栏

### ISSUE THREAD

**Issue by flaccida** [HIllya51/LunaTranslator#120]
（不好意思我又来了

现在只能最小化到托盘，能不能添加一个最小化到任务栏的选项？
并且现在按任务栏中的图标或 Win+D 也不会像其它程序一样切换最小化状态

**Comment by HIllya51** [comment]
可以

**Comment by flaccida** [comment]
任务栏图标可以用了，但点击窗口上的最小化按钮还是只会最小化到托盘

**Comment by HIllya51** [comment]
太多相互依赖的东西了，不想改了。。。

**Comment by flaccida** [comment]
（那不动按钮，新增一个最小化到任务栏的按钮是不是简单点

**Comment by HIllya51** [comment]
改了
