### ISSUE TITLE
最終試験くじ

### ISSUE THREAD

**Issue by sorasoras** [HIllya51/LunaTranslator#1200]
### vndb link/id

https://vndb.org/v78

### Game resource 游戏资源

https://1drv.ms/u/s!Al8eR-kCaR-mhfxSm9T-0KrU1nc5Ww?e=3ri6YY

### screenshot 截图

![1](https://github.com/user-attachments/assets/55f42392-25c0-4e02-8290-cd158d386819)

**Comment by HIllya51** [comment]
不要乱调不懂的参数。把刷新延迟改回500就行了。
