### ISSUE TITLE
Both DeepL and DeepLX are not working for me.

### ISSUE THREAD

**Issue by leraddd** [HIllya51/LunaTranslator#1202]
### Question 问题

I get the error "too many requests" for DeepL. I used to use DEV tools DeepL extension in textractor and I am not sure if I can put that extension into Luna. I just want DeepL to work without giving error messages every few sentences. Is there any way to fix this? Am I using it wrong?

**Comment by HIllya51** [comment]
![屏幕截图 2024-12-04 133148](https://github.com/user-attachments/assets/9dabbefe-dd2e-4f3b-b7a8-85f90a584eff)

**Comment by leraddd** [comment]
Thank you!!
