### ISSUE TITLE
Text is not displayed in the window when using CDP ChatGPT

### ISSUE THREAD

**Issue by allebar** [HIllya51/LunaTranslator#1203]
### Version 程序版本

last

### OS version and bits 系统版本和位数

win 11 64

### bug's screenshot 错误截图

Text is not displayed in the window when using CDP ChatGPT

And yes, I also have a slightly off-topic question. Is there any way to avoid the transfer restriction to DuckDuckGo? I just don't know where else to ask about it.

### Reproduction steps 复现步骤

......

**Comment by HIllya51** [comment]
Do not use CDP ChatGPT, it has been depracated. Please purchase your own API to use ChatGPT.
