### ISSUE TITLE
"ZBZ" and "ZX BZ" instead of output when using "translation of proprietary terms"

### ISSUE THREAD

**Issue by Owyn** [HIllya51/LunaTranslator#1204]
### Version 程序版本

v6.10.2 latest

### OS version and bits 系统版本和位数

Win 10 x64

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/ddea4faa-229d-4be6-ae4d-18278d705942)
![image](https://github.com/user-attachments/assets/1f15d2b6-6c55-432d-a7c0-d65a7fca4ee8)

### Reproduction steps 复现步骤

1. Add something into translation correction, e.g.
"喷！" -> "Tsk!"
2. try to translate it with OCR and google v1 or google v2
3. get ZBZ and ZX BZ instead of "Tsk!"

**Comment by HIllya51** [comment]
https://docs.lunatranslator.org/#/en/transoptimi?id=proper-noun-translation

**Comment by Owyn** [comment]
So, what is the right approach to correct translations? (before the translation because else the result could be random)
I don't have sakura model but this replacer was working mostly fine

**Comment by Owyn** [comment]
"Directly replace" seems to be working better, thx!

**Comment by HIllya51** [comment]
The translation API doesn't provide a way to do this at all. If we don't do it, how else can we do it? Don't nitpick with such short sentences, it's rare to make such mistakes under normal use.
