### ISSUE TITLE
Confidential money psp game can't hook or find hook

### ISSUE THREAD

**Issue by yunagiril** [HIllya51/LunaTranslator#1205]
### vndb link/id

https://vndb.org/v10631 

### Game resource 游戏资源

https://cdromance.org/psp/confidential-money-300-nichi-de-3000-man-doru-kasegu-houhou-jpn/

### screenshot 截图

Nothing appears, if search for hook just dumb text

**Comment by HIllya51** [comment]
This game uses an unknown string encoding, and I cannot find a pattern to map it to shiftjis, so I can only output the hexadecimal of each character.
