### ISSUE TITLE
Alllow re-order of text hooks output

### ISSUE THREAD

**Issue by Bredan80** [HIllya51/LunaTranslator#1206]
### Expected behavior 预期的功能

Hello.

Is there a way to re-order text hooks order in the 'Select text' window ? If no, I would love to see it added.

The idea is : when you use multiple hooks to get full text, outputing several hooks to clipboard can be in wrong order.

Some examples :
- one example would be one hook for normal text, another for furigana in some engines
- another example : a hook with speaker's name, another hook with the line spoken in some engines

The text can be in wrong order (line spoken and then name for example). Reordering could resolve this issue.

PS : thanks for your work.

**Comment by HIllya51** [comment]
It will be sorted in the order of selection
