### ISSUE TITLE
Letters with accents aren´t hooked

### ISSUE THREAD

**Issue by L1bra098** [HIllya51/LunaTranslator#1207]
### Version 程序版本

6.10.2

### OS version and bits 系统版本和位数

Windows 11

### bug's screenshot 错误截图

![imagen_2024-12-05_231940557](https://github.com/user-attachments/assets/af6e719f-d2c5-4d4f-a95b-73d4c09557f1)

### Reproduction steps 复现步骤

I'm trying this VN with Spanish patch. (Sakura no Uta]

I see that it hooks the text well except for the accents that are always replaced with the same letter "ü", so you can't replace each letter with the correct one.

I also tried with several codepages, and instead of ü it results in other types of symbols, but without a solution.

**Comment by HIllya51** [comment]
Non official versions of the game are not supported
