### ISSUE TITLE
提取的文本不正确

### ISSUE THREAD

**Issue by LugaDX** [HIllya51/LunaTranslator#1209]
### vndb link/id

魔法少女沙枝でらっくす

### Game resource 游戏资源

https://drive.google.com/file/d/1WcTrMESUiij7FjOe5rlYiBDuD01K3q3x/view?usp=sharing

### screenshot 截图

![截图](https://github.com/user-attachments/assets/900bf08b-ca75-4908-abc7-e6f2a03d9a56)

**Comment by HIllya51** [comment]
?
![屏幕截图 2024-12-07 145557](https://github.com/user-attachments/assets/33ada873-defc-4ec0-bd70-a48c74c59722)
