### ISSUE TITLE
想请教下

### ISSUE THREAD

**Issue by vcxvcxvxc** [HIllya51/LunaTranslator#121]
Textractor 是不是凡是带有特殊表情符号都会导致整段无法读取的？ 例如 ❤这个。。我发现每一段出现这符号都读取不了文字。。

**Comment by HIllya51** [comment]
看情况。有的游戏能。

**Comment by vcxvcxvxc** [comment]
好吧 感谢回复

**Comment by vcxvcxvxc** [comment]
> 看情况。有的游戏能力。

好吧 感谢回复

**Comment by vcxvcxvxc** [comment]
> 看情况。有的游戏能。
找到了。。编码问题
