### ISSUE TITLE
无法过滤人名

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaTranslator#1210]
### vndb link/id

https://vndb.org/v6409

### Game resource 游戏资源

https://mega.nz/file/1a1WEQYT#hefTMObz9hi-b0cqIxFbAlYpagDBjanG2R9HMZm3c7w
游戏安装好后，把“修正补丁”文件夹里的俩文件复制到游戏目录下，运行UPDATE更新至1.13版本
希望添加一个HOOK，直接过滤掉上面框里的人名

### screenshot 截图

![QQ20241207-023229](https://github.com/user-attachments/assets/ce06e775-d5b9-4074-a468-5d9451283e79)

**Comment by HIllya51** [comment]
更新了。刚才还在改其他需要改的地方。
