### ISSUE TITLE
アイキス3 cute  （Ai Kiss 3 Cute）switch模拟器无法识别

### ISSUE THREAD

**Issue by xyjx001** [HIllya51/LunaTranslator#1211]
### vndb link/id

https://vndb.org/v32132

### Game resource 游戏资源

https://1fichier.com/?bmyi8cy966fflcad5amk&af=2850246

### screenshot 截图

![image](https://github.com/user-attachments/assets/26f315d8-2204-4527-b792-7be64c885fd8)

yuzu以及yuzu分叉torzu使用普通以及admin版本hook都找不到文本，都是乱码。 ocr也不行，对了我是英文win11系统

**Comment by HIllya51** [comment]
我都写了要不限速网盘，你还给我这么个东西，要我怎么下载？
