### ISSUE TITLE
Kuro to Kin no Akanai Kagi/黒と金の開かない鍵

### ISSUE THREAD

**Issue by churroloca** [HIllya51/LunaTranslator#1213]
### vndb link/id

https://vndb.org/v4106

### Game resource 游戏资源

https://drive.google.com/file/d/1J9E2znO7A6EgKjRM9JWYXkO6jBgTVwGI/view?usp=drive_link

It's a direct download and requires no password to download. I got it directly from animate games (trial version). I am so sorry about last time, when I misunderstood what needing the source of game meant. On LunaHook - the game engine shows as Little Cheese - and only has two hooks. One shows twenty of the same characters and cannot write complete sentences. Second one won't even pull sentences.

### screenshot 截图

<img width="960" alt="Screenshot 2024-12-09 130837" src="https://github.com/user-attachments/assets/5a7ada23-5ccf-4e98-8a19-0df7fba715f9">

**Comment by HIllya51** [comment]
?

![屏幕截图 2024-12-09 154314](https://github.com/user-attachments/assets/c24a81d4-d163-449c-af10-c5880699be84)
