### ISSUE TITLE
Spaces in words

### ISSUE THREAD

**Issue by Vincent-Dawn** [HIllya51/LunaTranslator#1215]
### Version 程序版本

Current

### OS version and bits 系统版本和位数

Windows 11

### bug's screenshot 错误截图

![Screenshot 2024-12-09 110511](https://github.com/user-attachments/assets/cacc9980-4296-4b5d-94c1-b1f86440a375)
![Screenshot 2024-12-09 111005](https://github.com/user-attachments/assets/08312332-cd49-4e75-9623-25c737623a13)
![Screenshot 2024-12-09 111017](https://github.com/user-attachments/assets/1af29f8f-816a-4219-bc6d-e8b038191a26)

### Reproduction steps 复现步骤

Games by certain companies (Such as Pin Point) will often contain spaces in the middle of their words mainly when they reach the end of the dialogue box. This also happened when I used Textractor and LunaHook to copy the dialogue and was usually fixed with this Regex Filter "|REGEX|　|BECOMES||MODIFIER|g|END|" and I went through the text processing option to find one that might solve the problem, like filter line break, couldn't find one that worked.

**Comment by HIllya51** [comment]
https://docs.lunatranslator.org/#/zh/textprocess?id=%e5%ad%97%e7%ac%a6%e4%b8%b2%e6%9b%bf%e6%8d%a2

**Comment by Vincent-Dawn** [comment]
@HIllya51 

I don't now what I'm supposed to enter to fix this issue. I read the instructions and entered \n in the original content box and left replace blank and nothing changed with either regex, escaped or both selected.
