### ISSUE TITLE
What do I enter in String Replacement to stop spaces between words?

### ISSUE THREAD

**Issue by Vincent-Dawn** [HIllya51/LunaTranslator#1216]
### Question 问题

I read the section on string replacement you sent me for issue [#1215](https://github.com/HIllya51/LunaTranslator/issues/1215). 

I entered \n in the original content box and left replace with blank and turned on escape, but the problem still persists. Am I supposed to enter something different or is this a bug with the last two versions.

**Comment by HIllya51** [comment]
copy this character directly from the output text

**Comment by Vincent-Dawn** [comment]
I'm a little confused, I don't know which character you're talking about. If it's the \n it never appears in the text. It's basically a space between characters whenever the text is longer than one line in dialouge box.

**Comment by Vincent-Dawn** [comment]
I'm a little confused, I don't know which character you're talking about. If it's the \n it never appears in the text. It's basically a space between characters whenever the text is longer than one line in the dialogue box.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
