### ISSUE TITLE
v1.35.7bug：添加新游戏后点击 已保存游戏 会造成闪退

### ISSUE THREAD

**Issue by EXBJAN** [HIllya51/LunaTranslator#122]
此外使用1.35.7和过往版（如1.35.5）添加新游戏，然后交换两个版本的userconfig文件夹，则1.35.7已保存游戏功能正常。1.35.5也会出现该问题

**Comment by HIllya51** [comment]
呃 很久没改过相关内容了 盲猜添加的游戏的问题。。配置发我看看？

**Comment by HIllya51** [comment]
已修正
