### ISSUE TITLE
もみえろCureTouch─第１話─

### ISSUE THREAD

**Issue by storycoolbro** [HIllya51/LunaTranslator#1222]
### vndb link/id

https://vndb.org/v11673

### Game resource 游戏资源

https://drive.google.com/drive/folders/1PkQq1B2OV5ce2M6RA7eKgc2ERcJFyTbD?usp=drive_link

### screenshot 截图

![image](https://github.com/user-attachments/assets/b3791c6d-7359-4b0c-a59b-6d40b2ff8e57)

**Comment by HIllya51** [comment]
not runable
![屏幕截图 2024-12-12 132258](https://github.com/user-attachments/assets/7a1de821-7418-48ab-84a4-7bf3845eb352)

**Comment by storycoolbro** [comment]
game requieres softdenchi for initial set up was hoping uploading the already verified/installed files would work around it. not sure if this will work but try re-downloading are run the setup, I replaced it with the one from the presetup folder no idea as I noticed the one in the post set up when you try to run it says it can't be run directly or something like that but the other one can be so `¯\_(ツ)_/¯`

**Comment by storycoolbro** [comment]
ignore the above doubt it would work, looked into how to remove soft denchi surprisingly easy. Tested it on my laptop and it appears to work you do have to run set up but it didn't prompt me to enter anything for softd enchi so I believe it work but  here's a small chance I did authenticate it a long time ago on this laptop and just don't remember doing so. [new link](https://drive.google.com/file/d/15W9AfdwcxVAp2s8LiAVWkGzcf4RtSKL6/view?usp=sharing)

**Comment by HIllya51** [comment]
It can't be opened at all.
