### ISSUE TITLE
Sentence Problems with Cyclet and Pin Point games.

### ISSUE THREAD

**Issue by Oyler157** [HIllya51/LunaTranslator#1224]
### Version 程序版本

6.11.3

### OS version and bits 系统版本和位数

Windows 11

### bug's screenshot 错误截图

![Screenshot 2024-12-11 180455](https://github.com/user-attachments/assets/2fba0bde-650f-440f-a044-fa555a8f05e7)
![Screenshot 2024-12-11 181523](https://github.com/user-attachments/assets/3a943f56-bdcf-49eb-baf7-99ee0a60490c)

### Reproduction steps 复现步骤

I noticed in two games I've been playing, [Tsuiraku Jinsei ](https://vndb.org/v16376) and [Konchuu Kansatsu](https://vndb.org/v10294), that when part of the sentence reaches the end of the box there is a space in between the Japanese characters. This issue is present in other Cyclet and Pin Point games as well, mainly when the characters are speaking in the「」. 

I read the instructions about entering \n in string replacement and turning escape on, but when I press the arrow button in the sample box in settings or hit the retranslate button in the box it doesn't change.

I have two links to the games to see if there is a similar issue on your end. You have to have the message speed set on the highest setting or LunaTranslator will skip duplicate characters in Pin Point games (this also happened when I used Textractor). Don't worry about the ISO file for Konchuu Kansatsu, the folder named Konchuu Kansatsu Tokuten is where I got the screenshot from and doesn't require any installation.  

[https://mega.nz/file/91RhnKrS#5jhg6hsBhHNYQeypamdy3epFgyVLsMbpWkEa3yU2apM](https://mega.nz/file/91RhnKrS#5jhg6hsBhHNYQeypamdy3epFgyVLsMbpWkEa3yU2apM)
[https://mega.nz/file/d1gXWIBZ#DnBnr6-wsxJOz9zk7kxfcwMbw7KYHSmeQF398AuKfJ8](https://mega.nz/file/d1gXWIBZ#DnBnr6-wsxJOz9zk7kxfcwMbw7KYHSmeQF398AuKfJ8)

**Comment by HIllya51** [comment]
it is "　", not \n

**Comment by Oyler157** [comment]
These are the two I tried and the sentence didn't change when escape was turned on. I also tried a blank space without the quotes  as well.

![Screenshot 2024-12-11 213053](https://github.com/user-attachments/assets/9fcc69ac-bd21-4a75-b6b0-a1427cbafe72)
