### ISSUE TITLE
请问下内嵌翻译不会触发语音合成吗

### ISSUE THREAD

**Issue by lotanzoe** [HIllya51/LunaTranslator#1233]
### Question 问题

![image](https://github.com/user-attachments/assets/08b70a96-d072-47c4-ad8e-67bee1e0ecd7)
试了几次好像都要开显示才能出语音，同一句话就会被翻译两次，在少数情况下这两次翻译的不一样，导致屏幕上的话（内嵌翻译）和读出来的话不一致。
![image](https://github.com/user-attachments/assets/1f0fc16d-1547-4be3-91c0-1ce7ebe6c16f)

话说，为什么语音要单独翻译一遍啊awa，是我哪里没看到吗……

**Comment by HIllya51** [comment]
你不要用过滤
