### ISSUE TITLE
无法实现自动从剪切板读取内容

### ISSUE THREAD

**Issue by deathwaltz** [HIllya51/LunaTranslator#1234]
### Version 程序版本

v6.11.10 64bit

### OS version and bits 系统版本和位数

Windows 11 23H2

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/6cac9f00-49bd-49ea-a0bc-ddb2fd84970b)

### Reproduction steps 复现步骤

我使用了manga-ocr 输出截图后的文字，期待LunaTranslator读取剪切板的内容，但是没有反应
文本输入已经如下选择为剪切板
![image](https://github.com/user-attachments/assets/a03a530d-7024-4d21-91f9-996940437c37)

但是如果我点击小窗口的【读取剪切板】小按钮的话就有文字。

为了验证自动读取剪切板可行，我下载了ja-learner做测试，没发现问题。
https://github.com/ks233/ja-learner

希望帮忙复现一下，不知道是我的环境问题还是版本问题。

**Comment by HIllya51** [comment]
测试没有问题，建议找找自己设置的问题。

**Comment by deathwaltz** [comment]
谢谢

**Comment by HIllya51** [comment]
而且有整合包，在离线ocr里能直接调用mangaocr，没必要用剪贴板
