### ISSUE TITLE
Request for Browser Debug from all russian users

### ISSUE THREAD

**Issue by x-dogma-x** [HIllya51/LunaTranslator#1235]
### Expected behavior 预期的功能

Greetings, developer of Luna Translator. On behalf of all users of the program from Russia and the countries of the former USSR, we earnestly request that you restore several translators from the Browser Debug section. Here’s the link to our Luna Translator community: https://vk.com/lunatranslator. Our country is experiencing economic hardship, partly due to sanctions. Many users are unable to afford paid subscriptions to translation services such as ChatGPT, Yandex, Deepl to use them without limits. Please bring back support for just 6 translators from Browser Debug: 1) Yandex, 2) ChatGPT, 3) Deepl, 4) Deepseek, 5) DuckDuckGo, 6) Theb. Yours sincerely, Russian users of Luna Translator.

**Comment by HIllya51** [comment]
rename LunaTranslator/translator/__cdp_chatgpt.py as LunaTranslator/translator/cdp_chatgpt.py and restart
