### ISSUE TITLE
希望支援位置在smb共享文件夹的游戏路径

### ISSUE THREAD

**Issue by chaos700** [HIllya51/LunaTranslator#1236]
### Expected behavior 预期的功能

现在最新v6.11.10版的游戏库是可以添加smb共享文件夹上的游戏,
但即使游戏库里显示成功添加,开启游戏按钮是无法启动smb共享文件夹上的游戏,
试过用mklink /d命令在本地文件夹连结smb共享文件夹,成功在游戏库面板上启动游戏,但无法Hook游戏文字,
每次要用LunaTranslator,只能将游戏复制到本地硬盘,但大部分Galgame支持在smb上启动,如果LunaTranslator能支持smb路径就好了。

**Comment by HIllya51** [comment]
配smb太麻烦，我懒得配。你加q群，让我远程控制你电脑把这个bug修了。

**Comment by HIllya51** [comment]
在？

**Comment by chaos700** [comment]
> 在？

对不起，刚刚才看到消息，如果太麻烦就算了，我先关掉这个issue，谢谢你！

**Comment by chaos700** [comment]
> 呃，不算很麻烦啊，你让我远程一下几分钟就搞定了，但我不会配smb。

谢谢你!不过我发现用Rclone将smb挂载本地磁盘,就可以正常使用LunaTranslator。
