### ISSUE TITLE
Deepl Import Failed: ImportError

### ISSUE THREAD

**Issue by rakazzt** [HIllya51/LunaTranslator#1238]
### Version 程序版本

6.12.0 64

### OS version and bits 系统版本和位数

windows 10

### bug's screenshot 错误截图

![luna error](https://github.com/user-attachments/assets/ed811972-91da-40b0-8500-2470e490977f)

updating my Luna and got this error 

### Reproduction steps 复现步骤

,

**Comment by HIllya51** [comment]
Do not use outdated interface, develop DeepL has been merged into DeepL in online translation.
