### ISSUE TITLE
Google Lens Error

### ISSUE THREAD

**Issue by JustOneRandomPlayer** [HIllya51/LunaTranslator#1239]
### Version 程序版本

v6. 12. 0 64bit

### OS version and bits 系统版本和位数

windows 10 64bit

### bug's screenshot 错误截图

![error](https://github.com/user-attachments/assets/ef98523a-1ebf-444c-a85c-21712f5cc077)

### Reproduction steps 复现步骤

I have been using Luna Translator for about two weeks and everything was fine, but today Google Lens stopped working and gives this error. What does this error mean and can it be fixed? I didn't change any settings myself, it just stopped working.

**Comment by HIllya51** [comment]
Google no longer allows people to use the Lens interface for free OCR. Use another interface.

**Comment by HIllya51** [comment]
this api seems no longer valid.

**Comment by bropines** [comment]
> this api seems no longer valid.

Google is carrying out a massive redesign, which is why the upload endpoint stupidly stops working in some regions. We at BT also encountered this

**Comment by phamthaison1207** [comment]
> this api seems no longer valid.

owocr's author is working on a fix for it, maybe you can take a look after he pushed a new version of the fix?

**Comment by HIllya51** [comment]
> @HIllya51 Thank you for fixing Google Lens. You are our hero! We owe you for this@HIllya51 感谢您修复 Google Lens。 您是我们的英雄！我们欠你的
> 
> But I have noticed that new Google Lens API doesn't like working VPN. It doesn't work with VPN. ![image](https://private-user-images.githubusercontent.com/80591773/397487559-61912766-6f87-43ae-8a24-fdee5ef02583.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MzI2MDcsIm5iZiI6MTczNDYzMjMwNywicGF0aCI6Ii84MDU5MTc3My8zOTc0ODc1NTktNjE5MTI3NjYtNmY4Ny00M2FlLThhMjQtZmRlZTVlZjAyNTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE4MTgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjODU4ZDA0N2E1NzY2NzU0YWUwYmI4MmRiNmYzMDZlNjYyYWYxMDYxODYwZTc3MGY4MDM2NWRlMjhmZDlmYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E8wPI-loq1RaL9Idl8wwDkJLirXtIC8oOGvQrb8ofSI)但我注意到新的 Google Lens API 不喜欢有效的 VPN。它不适用于 VPN。

This error only occurs occasionally, just restart the software

**Comment by AuroraWright** [comment]
@HIllya51 Chrome user agents are inconsistent (sometimes it gives the "old version" and sometimes the "new version"), if you use this user agent it works all the time https://github.com/AuroraWright/owocr/commit/f64308223ac0beb45627ae9129c43cde7be08be4

**Comment by HIllya51** [comment]
> @HIllya51 Chrome user agents are inconsistent (sometimes it gives the "old version" and sometimes the "new version"), if you use this user agent it works all the time [AuroraWright/owocr@f643082](https://github.com/AuroraWright/owocr/commit/f64308223ac0beb45627ae9129c43cde7be08be4)@HIllya51 Chrome 用户代理不一致（有时给出“旧版本”，有时给出“新版本”），如果您使用此用户代理，它将一直工作 AuroraWright/owocr@f643082

Unfortunately, he sometimes makes the same mistake for me as well
