### ISSUE TITLE
自定义Python 文本预处理,不能调用别的 库吗

### ISSUE THREAD

**Issue by Pixellevel** [HIllya51/LunaTranslator#1241]
### Question 问题

这个脚本不会工作，只会输出原文
def POSTSOLVE(line):
    import string
    import re
    import time
    import jieba

    # 创建中日文标点符号列表
    cjk_punc = '！？｡。＂＃＄％＆＇（）＊＋，－／：；＜＝＞＠［＼］＾＿｀｛｜｝～｟｠｢｣､、〃》「」『』【】〔〕〖〗〘〙〚〛〜〝〞〟〰〾〿–—''‛""„‟…‧﹏。、，．・：；？！゛゜´｀¨＾￣＿ヽヾゝゞ〃仝々〆〇ー―‐／＼～∥｜…‥''""（）〔〕［］｛｝〈〉《》「」『』【】＋－±×÷＝≠＜＞≦≧∞∴♂♀°′″℃￥＄￠￡％＃＆＊＠§☆★○●◎◇◆□■△▲▽▼※〒→←↑↓〓'
    
    # 检查是否包含中日文字符
    def has_cjk(text):
        return bool(re.search('[\u4e00-\u9fff\u3040-\u309f\u30a0-\u30ff]', text))
    
    # 移除所有标点符号
    for char in string.punctuation + cjk_punc:
        line = line.replace(char, '')
    
    # 存储上一次输出的时间
    POSTSOLVE.last_output_time = getattr(POSTSOLVE, 'last_output_time', 0)
    current_time = time.time()
    
    if current_time - POSTSOLVE.last_output_time < 1.8:
        return ''
    
    POSTSOLVE.last_output_time = current_time

    # 如果包含中日文字符，使用jieba分词
    if has_cjk(line):
        # 使用jieba分词
        words = list(jieba.cut(line))
        
        # 简单的标点恢复规则
        restored_text = ""
        word_count = 0
        for word in words:
            restored_text += word
            word_count += 1
            # 每3-4个词添加一个逗号，每6-8个词添加一个句号
            if word_count % 3 == 0 and len(word) > 1:
                restored_text += "，"
            elif word_count % 7 == 0:
                restored_text += "。"
        
        if not restored_text.endswith("。"):
            restored_text += "。"
        
        # 分割文本为句子
        sentences = restored_text.split("。")
        # 过滤空字符串
        sentences = [s.strip() for s in sentences if s.strip()]
        
        # 如果至少有两个句子，返回最后一个完整的句子
        if len(sentences) >= 2:
            return sentences[-2]
        return sentences[0] if sentences else line
    
    # 如果是英文，使用简单的句子分割
    else:
        words = line.split()
        restored_text = ""
        for i, word in enumerate(words):
            restored_text += word
            if i < len(words) - 1:
                # 每5-7个单词添加一个句号
                if (i + 1) % 6 == 0:
                    restored_text += ". "
                else:
                    restored_text += " "
        
        if not restored_text.endswith("."):
            restored_text += "."
            
        sentences = restored_text.split(".")
        sentences = [s.strip() for s in sentences if s.strip()]
        
        if len(sentences) >= 2:
            return sentences[-2]
        return sentences[0] if sentences else line       

而下面的简单的脚本就可以工作

def POSTSOLVE(line):
    """每16个字符添加一个句号，返回最后一个完整的16字符段"""
    # 如果输入为空，直接返回
    if not line:
        return ''
        
    # 所有标点符号列表（包括中英文标点）
    all_puncs = '''，。！？；：、．.!?,;:'"()[]{}/<>@#$%^&*_+-=\|～·`'''
    
    # 第一步：移除所有标点
    for p in all_puncs:
        line = line.replace(p, '')
    
    # 计算有多少个完整的16字符段
    complete_segments = len(line) // 16
    
    # 如果没有完整的16字符段，返回空字符串
    if complete_segments == 0:
        return ''
    
    # 获取最后一个完整的16字符段
    start = (complete_segments - 1) * 16
    end = complete_segments * 16
    
    return line[start:end] + '。'

**Comment by HIllya51** [comment]
你就不能用debug看报错吗。

**Comment by Pixellevel** [comment]
PS C:\Users\rdzbb> pip show jieba
Name: jieba
Version: 0.42.1
Summary: Chinese Words Segmentation Utilities
Home-page: https://github.com/fxsjy/jieba
Author: Sun, Junyi
Author-email: ccnusjy@gmail.com
License: MIT
Location: C:\Users\rdzbb\AppData\Local\Programs\Python\Python313\Lib\site-packages
Requires:
Required-by:
PS C:\Users\rdzbb>             
系统当中安装了也没有用

**Comment by Pixellevel** [comment]
@HIllya51  
PS C:\Users\rdzbb> pip show jieba
Name: jieba
Version: 0.42.1
Summary: Chinese Words Segmentation Utilities
Home-page: https://github.com/fxsjy/jieba
Author: Sun, Junyi
Author-email: [ccnusjy@gmail.com](mailto:ccnusjy@gmail.com)
License: MIT
Location: C:\Users\rdzbb\AppData\Local\Programs\Python\Python313\Lib\site-packages
Requires:
Required-by:
PS C:\Users\rdzbb>
系统当中安装了也没有用,我之前就已经安装了

**Comment by HIllya51** [comment]
。。。你装系统里有毛用，又不是用的系统的python

**Comment by Pixellevel** [comment]
我在翻译器的文件夹里没找到Python，我不知道怎么在翻译器里安装jieba,脚本也是模型写的，
