### ISSUE TITLE
Volcano OCR

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#1243]
### Question 问题

Since Google Lens is inaccessible temporary due to API issue I started to search for free online alternative option in Luna with similar high-precision recognition (without VPN).
I presume Volcano OCR is somehow connected to Volcano translations. Or maybe I am wrong. Until now I have not managed to find any site with Volcano OCR where I can get API key for use in Luna.
What is web-site of Volcano ocr to obtain key?

![вулкан](https://github.com/user-attachments/assets/7a97f20b-e9ae-4db2-83c3-3f98015d6076)

**Comment by HIllya51** [comment]
https://docs.lunatranslator.org/#/en/useapis/ocrapi
