### ISSUE TITLE
专有名词翻译不起作用

### ISSUE THREAD

**Issue by Ryotosen** [HIllya51/LunaTranslator#1244]
### Version 程序版本

6.13.0

### OS version and bits 系统版本和位数

win10 22H2 64x

### bug's screenshot 错误截图

![屏幕截图 2024-12-19 233444](https://github.com/user-attachments/assets/9fffc6e6-96fd-4979-b9c0-734968798a1b)
![屏幕截图 2024-12-19 233702](https://github.com/user-attachments/assets/1442a0ef-28a5-4c57-ae6b-bc6d3bf03ce5)

### Reproduction steps 复现步骤

添加对应翻译优化的专有名词翻译后，尝试了好几个翻译都能生效，但是只有lingva没用，对应词的翻译还会变来变去的……

**Comment by HIllya51** [comment]
![屏幕截图 2024-12-19 235222](https://github.com/user-attachments/assets/26e14d41-8ccb-4616-8ea7-ea4aa2436c21)
