### ISSUE TITLE
wine运行White Album 2高内存占用

### ISSUE THREAD

**Issue by yuukibarns** [HIllya51/LunaTranslator#1247]
### Version 程序版本

v6.14.2

### OS version and bits 系统版本和位数

Arch Linux x86_64

### bug's screenshot 错误截图

希望作者提供进一步的要求，否则就放一张monitor的截图也没什么用

### Reproduction steps 复现步骤

用wine运行，发现内存占用持续升高到数个G

**Comment by yuukibarns** [comment]
wine v9.22

**Comment by HIllya51** [comment]
你都用linux了，不能自己调试一下吗？难道要我自己去配和你一样的arch环境？这怎么可能做得到。
