### ISSUE TITLE
Text Extraction Problems with Unity Games in LunaTranslator 6.14.2 (Works in 5.38.10 and Textractor with Clean Text Hook)

### ISSUE THREAD

**Issue by Figurecollection** [HIllya51/LunaTranslator#1249]
### Version 程序版本

6.14.2

### OS version and bits 系统版本和位数

windows 11 64 bit

### bug's screenshot 错误截图

6.14.2

![Screenshot 2024-12-20 034622](https://github.com/user-attachments/assets/2a4d7d60-552e-4674-94fb-36d9717b34de)
![Screenshot 2024-12-20 034632](https://github.com/user-attachments/assets/b5a90a77-9548-4d06-8a5a-88f99b3635f6)
![Screenshot 2024-12-20 034634](https://github.com/user-attachments/assets/3b508000-e56f-4d85-8f5e-28967c27204e)

5.38.10

![Screenshot 2024-12-20 034425](https://github.com/user-attachments/assets/ec2a2ae9-4d75-4a09-b3e9-62d5eecbf067)
![Screenshot 2024-12-20 034447](https://github.com/user-attachments/assets/bedff9eb-05b5-4ea9-a65a-97da7d0848d7)
![Screenshot 2024-12-20 034450](https://github.com/user-attachments/assets/38194ce0-94eb-463e-8203-704f5affce82)

Textractor with Clean Text Hook string:IndexOf (string)

![Screenshot 2024-12-20 035459](https://github.com/user-attachments/assets/a58b7149-bd28-4a05-ae23-c341f0b51873)
![Screenshot 2024-12-20 035434](https://github.com/user-attachments/assets/70a5b7c2-a008-4f75-b5df-c35732f7b042)

### Reproduction steps 复现步骤

I've encountered an issue with LunaTranslator version 6.14.2 where it fails to extract text from certain Unity games, such as a game called Mouthwashing.

Previously, I recall being able to hook the text from these games without any problems using an older version of the program. To confirm, I tested LunaTranslator version 5.38.10, and it successfully retrieves the text as expected.

Additionally, I tried using Textractor, which managed to extract the text from the same game using various hooks. One of these hooks found the text completely clean, which is something LunaTranslator is currently unable to achieve. While it's possible to clean the text manually using the Text Processing feature in LunaTranslator, it would be very convenient to include a similar clean text hook like the one available in Textractor.

It seems there might have been a change in recent updates that caused this regression. Could this be investigated?
Thank you very much!

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/issues/new?assignees=&labels=enhancement&projects=&template=01_game_request.yaml

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/issues/new?assignees=&labels=enhancement&projects=&template=01_game_request.yaml

**Comment by Figurecollection** [comment]
> https://github.com/HIllya51/LunaTranslator/issues/new?assignees=&labels=enhancement&projects=&template=01_game_request.yaml

The problem there is with many games with Unity, but OK, I open another ticket there.
