### ISSUE TITLE
为原文和译文设置不同的字体？

### ISSUE THREAD

**Issue by akux** [HIllya51/LunaTranslator#125]
中文和日文中的一些汉字在形态上有细微差异，能否支持为原文和译文设置不同的字体？

**Comment by HIllya51** [comment]
不能，太过麻烦。建议使用微软雅黑/思源黑体。

**Comment by HIllya51** [comment]
字体样式做的太复杂了，改起来太麻烦了。反正这一块儿我是懒得改了。
