### ISSUE TITLE
support offline translation tools

### ISSUE THREAD

**Issue by Prisoner416** [HIllya51/LunaTranslator#1253]
### Expected behavior 预期的功能

Visual Novel Reader supports offline translation via LEC and Atlas. I depend on these over most other choices and have found them to be more accurate when paired with custom dictionaries. Luna detects Hcode and strings that other programs are missing, but I could sorely use the translators.

**Comment by HIllya51** [comment]
give me download link

**Comment by Prisoner416** [comment]
I can provide downloads shortly, I am uncertain how Visual Novel Reader interfaces with the programs. Just noticed the request has been closed though, so...
