### ISSUE TITLE
游戏适配

### ISSUE THREAD

**Issue by vodaaaa787** [HIllya51/LunaTranslator#1257]
### vndb link/id

无

### Game resource 游戏资源

https://drive.google.com/file/d/1jOnDtcTygHh6hOUnuzXyL2wX2tAP6Y7X/view?usp=drive_link

### screenshot 截图

![屏幕截图 2024-12-26 164844](https://github.com/user-attachments/assets/3081a303-5b7b-4e2d-adc8-39099be9d190)

**Comment by HIllya51** [comment]
经典无效链接。

**Comment by vodaaaa787** [comment]
> 经典无效链接。

抱歉,现在已经设置好了.
