### ISSUE TITLE
text without spaces

### ISSUE THREAD

**Issue by 1000blxdesss** [HIllya51/LunaTranslator#1259]
### Version 程序版本

latest

### OS version and bits 系统版本和位数

win10 x64

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/14811126-b944-4955-aa37-b9c6738ea4e9)

### Reproduction steps 复现步骤

I turned on the "Hook" settings and selected my game, and all the output text had no spaces.

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/issues/new?assignees=&labels=enhancement&projects=&template=01_game_request.yaml
