### ISSUE TITLE
請問能調整一下日語查詞的文字大小嗎

### ISSUE THREAD

**Issue by tomeiyin** [HIllya51/LunaTranslator#126]
請問能調整一下日語查詞的文字大小嗎 字體太小了，看不清楚，最好能設定一下字體大小 謝謝~
![Snipaste_2022-12-28_00-16-08](https://user-images.githubusercontent.com/121508195/209692824-1920d8ba-00b6-4ad3-9d38-9638234bf21d.png)

**Comment by HIllya51** [comment]
好

**Comment by tomeiyin** [comment]
看到更新了，謝謝大大幫忙修改，我有一個小小建議，在使用查詞時能自動用tts發音該單詞讀音，對學習日語會有很大幫助
