### ISSUE TITLE
Tokyo 24-ku -inoru-

### ISSUE THREAD

**Issue by DarkVN101** [HIllya51/LunaTranslator#1260]
### vndb link/id

https://vndb.org/v25712

### Game resource 游戏资源

https://drive.google.com/file/d/1ze-kkjnFMLRL0Dx51Pq3N6Wd2QfRsg_U/view?usp=sharing

From now on I will only use Google Drive

### screenshot 截图

Nothing comes out, no text

Request for an unsupported game

**Comment by HIllya51** [comment]
?
![屏幕截图 2024-12-27 124520](https://github.com/user-attachments/assets/497e109e-81d5-417a-a480-25910e4b6a68)
