### ISSUE TITLE
sisters z hypnosis

### ISSUE THREAD

**Issue by ipados2003** [HIllya51/LunaTranslator#1262]
### vndb link/id

https://f95zone.to/threads/sisters-z-hypnosis-final-poison.235683/

### Game resource 游戏资源

https://gofile.io/d/YpQNAl

### screenshot 截图

![Capture d’écran 2024-12-27 113653](https://github.com/user-attachments/assets/af7cfe49-01c1-443d-9428-692325aa3edf)
![Capture d’écran 2024-12-27 113625](https://github.com/user-attachments/assets/6f80b96b-a3ee-4c21-a59f-09fac236849d)

**Comment by HIllya51** [comment]
https://docs.lunatranslator.org/#/zh/textprocess
