### ISSUE TITLE
Make a fork without HOOK module.

### ISSUE THREAD

**Issue by AweDeus** [HIllya51/LunaTranslator#1265]
### Expected behavior 预期的功能

Bro, make a version without HOOK mod for people with paranoia. Aren't you tired of constantly updating your program on GitHub and cleaning old versions because of suspicious behavior of ONE module?

### Alternative behavior (optional) 近似的功能（可选）

I will perceive ignoring or not responding to this post as bad faith behavior, and I will also begin an investigation into your project and start writing reports.

**Comment by HIllya51** [comment]
I think you may have intellectual disabilities.

**Comment by AweDeus** [comment]
> I think you may have intellectual disabilities.

This behavior makes me think that you are not really a conscientious developer.

Either answer normally, or I will start reporting your project and you right now.
