### ISSUE TITLE
Make a fork without HOOK module

### ISSUE THREAD

**Issue by AweDeus** [HIllya51/LunaTranslator#1266]
### Expected behavior 预期的功能

So, why you cant just make a fork without fiture that cause real problems?

Many people do not use the injection function, and they do not want to add certain files to the exceptions of antivirus systems after each update.

**Comment by HIllya51** [comment]
I really doubt if you have any intellectual problems
1. If you don't want to use hooks, why don't you look for specialized OCR software? More than 90% of the code in this software is related to HOOK, don't you think remove HOOK is purely humorous?
2. You haven't made any contribution to this project, you're just getting something for nothing and even wanting to add meaningless workload to me. Don't you feel like you're going too far?
3. This project is completely open source, and even the builds are built on GitHub. Isn't it funny to ask such a meaningless question?
4. You can definitely fork and remove HOOK related content yourself, but you haven't done so. You may be too lazy to do it, or just want to disgust me.

**Comment by HIllya51** [comment]
If you ask me such boring questions again, I will choose to blacklist you. My time is precious.
