### ISSUE TITLE
文本中包含花括号时，内嵌翻译会显示原文

### ISSUE THREAD

**Issue by finale1230** [HIllya51/LunaTranslator#1267]
### Question 问题

renpy游戏，翻译框中可以正常显示，文本处理中的去除花括号不论是否开启都是这样，多个游戏都有这个情况，不知道是缺少参数设置还是因为某些问题内嵌无法翻译带有花括号的文本？

![seeds-of-chaos_s0NI4o02yO](https://github.com/user-attachments/assets/4a85a7e4-285d-45ed-8f6e-389de5c7f10b)

![LunaTranslator_WfoFHlN9rU](https://github.com/user-attachments/assets/c32740e3-6ac8-4ca5-9ea1-28302293c0c8)

**Comment by HIllya51** [comment]
https://docs.lunatranslator.org/#/zh/embedtranslate?id=%e5%86%85%e5%b5%8c%e5%ae%89%e5%85%a8%e6%80%a7%e6%a3%80%e6%9f%a5

**Comment by HIllya51** [comment]
此外，内嵌翻译不会走预处理。但会走翻译优化，你可以在翻译优化里用正则表达式过滤掉花括号

**Comment by finale1230** [comment]
懂了，谢谢
