### ISSUE TITLE
But still.

### ISSUE THREAD

**Issue by AweDeus** [HIllya51/LunaTranslator#1268]
### Question 问题

I litteraly never used HOOK function, but I made a convenient tool for computer vision out of this project, connecting it via API to Google and Yandex services.

Isn't it clear that the OСR function in this sense is much cooler and more useful than a buggy tool for reading shitty visual novels?

Having a chatbot that can, for example, comment on the gameplay and give recommendations for free - in my opinion, is much cooler. Than just using the translation functions.

Your project takes into account that the user is playing a game and the functionality is optimized for work "On the fly", this distinguishes the project from its analogues. In addition, a large number of different interfaces have been added here, which allows you to use the tool much more flexibly than some solutions that are tailored for only one specific LLM.

and, besides, no matter how busy or tired you are from "stupid" questions - it doesn't give you the right to **act like an asshole**.

Yes, you've built a good tool, but it objectively causes problems with antivirus software, even if you claim that everything is open on GitHub - we both know that in fact no one checks every release of yours, and there are no guarantees, even if you give your word of honor, especially considering that you delete old releases and make new versions by re-numbering releases almost every hour.

If you didn't have a crown, you would understand that you should still explain to "ordinary mortals" why your tool causes such problems, EVEN, EVEN if it's obvious especially in light of such shady behavior.

**Comment by HIllya51** [comment]
I have no obligation to pay for your foolishness without compensation.
If you suspect there is a problem with it, please do not use it.
