### ISSUE TITLE
Opus format

### ISSUE THREAD

**Issue by yuukibarns** [HIllya51/LunaTranslator#1269]
### Expected behavior 预期的功能

Opus格式的音频会比mp3小很多，方便anki同步media files

**Comment by HIllya51** [comment]
似乎opus播放不出来。。。

**Comment by yuukibarns** [comment]
[mpvacious](https://github.com/Ajatt-Tools/mpvacious)
在anki卡片里似乎用的是这个格式
[sound:yahari1_00m18s820ms_00m22s380ms.ogg]

**Comment by yuukibarns** [comment]
谢谢大佬
