### ISSUE TITLE
可否支持Deepseek API

### ISSUE THREAD

**Issue by Nyphalem** [HIllya51/LunaTranslator#1270]
### Expected behavior 预期的功能

支持Deepseek API
https://www.deepseek.com/

**Comment by finale1230** [comment]
目前市面上主流的ai模型都支持，我就是用的deepseek，在chatgpt兼容接口里填deepseek的api接口地址https://api.deepseek.com就行，除了少数几个特定平台都用chatgpt兼容接口

https://docs.lunatranslator.org/#/zh/guochandamoxing

LT的功能非常全，多看使用说明真的可以解决绝大多数问题
