### ISSUE TITLE
[功能请求] 添加飞书ocr与翻译支持

### ISSUE THREAD

**Issue by ccdesue** [HIllya51/LunaTranslator#129]
## 特点
1. 免费，注册一个应用获取token即可使用
2. 个人测试支持日文

## 开发参考文档
1. ocr https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/ai/optical_char_recognition-v1/image/basic_recognize
2. 翻译  https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/ai/translation-v1/text/translate
3. 获取tenant_access_toke https://open.feishu.cn/document/ukTMukTMukTM/ukDNz4SO0MjL5QzM/auth-v3/auth/tenant_access_token_internal
4.  调用逻辑 创建app-> 获取 app_id + app_secret -> 获取 tenant_access_toke (2小时内有效, 可能需要考虑cache刷新) -> 以token为凭证访问对应接口

**Comment by ccdesue** [comment]
测试效果
![5adc3712c4d945920a9dda22a60e1356](https://user-images.githubusercontent.com/113218802/210138735-3f4a193c-090b-4f94-8f43-9ecefdbca3a3.png)

![image](https://user-images.githubusercontent.com/113218802/210138732-57010348-9b5c-4c58-b540-2ef74d00943d.png)

**Comment by HIllya51** [comment]
之前试过，要审核权限，刚刚看了一下，一个多月了，还没给我过审呢，搞不了。

**Comment by ccdesue** [comment]
自建应用可以直接用呀，和彩云翻译那种api类似

**Comment by ccdesue** [comment]
> 之前试过，要审核权限，刚刚看了一下，一个多月了，还没给我过审呢，搞不了。

自建应用不需要审核，如果要公有上线确实要审核。。可以类似彩云翻译那种api

**Comment by HIllya51** [comment]
怎么弄的。反正我这里要审核。

**Comment by ccdesue** [comment]
我的意思是可以做成类似彩云翻译在线api的模式
用户申请 app_id 和 app_secret -》 填写到软件-》 软件调用逻辑实现功能

只是调用api的话不需要上线，只要拿到 app_id 和 app_secret就行，个人感觉官网流程算比较简单易懂的

**Comment by ccdesue** [comment]
1. 打开这个网址  https://open.feishu.cn/
2. 点击  
![image](https://user-images.githubusercontent.com/113218802/210139624-0bb7b7a9-710d-45e9-b607-50db69fc5197.png)
3. 点击 
![image](https://user-images.githubusercontent.com/113218802/210139660-a14ef11e-50e2-42a2-aaeb-64736483dd5d.png)
4. 填写必要信息
5. 点击 
![image](https://user-images.githubusercontent.com/113218802/210139679-b5718f6a-2f5d-478f-98a4-593cb509e013.png)
6. 点击
![image](https://user-images.githubusercontent.com/113218802/210139697-fb6b40d8-3e8b-4ee1-b948-bc264dbf1c83.png)

**Comment by ccdesue** [comment]
> 怎么弄的。反正我这里要审核。

我理解错了。。。 可以创建测试企业 权限直接批准

**Comment by HIllya51** [comment]
已更新

**Comment by ccdesue** [comment]
感谢作者！
