### ISSUE TITLE
每次打开设置都不显示在主屏幕

### ISSUE THREAD

**Issue by lhj5426** [HIllya51/LunaTranslator#130]
![剪贴板图片 (3)](https://user-images.githubusercontent.com/30548000/210160312-8e974f0e-9d5c-49d5-bb74-cbba7838251c.png)
![image](https://user-images.githubusercontent.com/30548000/210160351-a9da0fed-d2f4-4654-861d-91ce455916ba.png)

先祝大佬2023元旦新年快乐
反馈的个问题
如同所示我电脑上接了4块屏幕
为了游戏体验我设置的1080作为主屏幕
然后呢 软件每次打开的时候打开设置 设置都会出现在4K这边的屏幕上
能不能让设置 打开的时候出现在主屏幕上？
而不是自动飞到 显示器中分辨率最大的屏幕。。。

**Comment by HIllya51** [comment]
改了。
