### ISSUE TITLE
BUG：krkr引擎有时会无法hook到完整句子

### ISSUE THREAD

**Issue by Ptilopsis01** [HIllya51/LunaTranslator#132]
如题，不是什么大问题，玩苹果妹的时候发现，在文字速度设置为最快的时候是正常的，但一旦文字速度不是最快就会有这个问题，而vnr无此问题

下面视频演示了一下

https://user-images.githubusercontent.com/93318731/210610289-14da2f91-5cc7-4e4a-8362-dba706ef1fe3.mp4

https://user-images.githubusercontent.com/93318731/210610304-3f6129b7-55a2-4b42-aa2e-b55327804455.mp4

**Comment by HIllya51** [comment]
HOOK设置里面把刷新延迟调高一点就行了。

**Comment by Ptilopsis01** [comment]
> HOOK设置里面把刷新延迟调高一点就行了。

确实可以，感谢
