### ISSUE TITLE
线上翻译有字数流量限制吗？

### ISSUE THREAD

**Issue by POLU822** [HIllya51/LunaTranslator#133]
大佬我想问一下
最近用有道3大概持续用了一小时之后就突然没回应了
是因为超过了翻译的流量吗

因为有道3翻译的质量又好又快，实在用不习惯其他家的
如果不是流量问题拜托佬帮帮解决 感恩

**Comment by HIllya51** [comment]
有访问频率限制。

**Comment by POLU822** [comment]
> 有访问频率限制。

那这样有办法解决吗
就算重启软件也没办法翻译了

**Comment by HIllya51** [comment]
开代理换ip地址

**Comment by Laniaidea** [comment]
换个ip就好，不知道具体是个什么限制。
