### ISSUE TITLE
hook無法完整抓取文本

### ISSUE THREAD

**Issue by su074151200** [HIllya51/LunaTranslator#134]
您好，已使用您的軟體，並以贊助。目前體驗感極佳，但有一些小問題，還希望您能解答。
目前使用有道5線上翻譯，hook設定，但有些句子有翻譯出來，有些則沒有，還期望幫助。

**Comment by HIllya51** [comment]
说一下什么游戏&放一下截图啊至少。

**Comment by q983526** [comment]
![批注 2023-01-13 084436](https://user-images.githubusercontent.com/20044260/212211529-3f2c6a89-8f4d-49dc-9cc3-2d8a42fced56.jpg)
类似这种 男主说的话就hook不到  选择文本里面也找不到   别的都能翻译

**Comment by HIllya51** [comment]
你倒是说一下到底是什么游戏啊😅😅😅😅

**Comment by HIllya51** [comment]
不清不楚的，这让我怎么给你解决啊😅

**Comment by q983526** [comment]
我的笔记本好像能识别
