### ISSUE TITLE
任务栏加入专有名词翻译快捷入口；翻译窗口拖动问题

### ISSUE THREAD

**Issue by wyh3130024630** [HIllya51/LunaTranslator#136]
能在工具栏里加入专有名词翻译的快捷入口吗，每次要加入新的专有名词还要跑到设置里找。
另外使用辞典时会点击原文，偶尔不小心会拖动一下窗口，能不能加入只能工具栏乃至工具栏上一个按钮拖动翻译窗口的设置。

**Comment by wyh3130024630** [comment]
还有就是能加入自定义辞典顺序的功能吗，比如每次查词都会默认打开小学馆，但我更希望直接看到有道，可又不希望没有小学馆。

**Comment by wyh3130024630** [comment]
可选取模式倒是能做到翻译栏不拖动，但又和查词冲突。

**Comment by wyh3130024630** [comment]
按钮不是可以自定义的吗，加一下呗。
那查词和可选取的冲突，还有就是窗口隐藏和任务栏中显示冲突呢。

**Comment by wyh3130024630** [comment]
> 按钮已经很多了，不想再加了。
> 
> 不可以，我喜欢整个窗口拖动。
> 
> 太过鸡毛蒜皮了，感觉没什么意义。

**Comment by HIllya51** [comment]
后面有空加一下吧。
这个不是冲突，这两者本来就不可能共存。

**Comment by EXBJAN** [comment]
> 后面有空加一下吧。 这个不是冲突，这两者本来就不可能共存。

关于这个功能是不是可以用鼠标点击行为来判定：比如单击为查词，长按为选取复制文本。
或者还有个更好的解决方案：在历史翻译窗口中右键鼠标加入复制文本选项：有选取则复制选取文本

**Comment by HIllya51** [comment]
> > 后面有空加一下吧。 这个不是冲突，这两者本来就不可能共存。
> 
> 关于这个功能是不是可以用鼠标点击行为来判定：比如单击为查词，长按为选取复制文本。 或者还有个更好的解决方案：在历史翻译窗口中右键鼠标加入复制文本选项：有选取则复制选取文本

这也太麻烦吧，而且也没啥用。我可懒得弄。

**Comment by EXBJAN** [comment]
因为选取模式和点击查词的功能冲突啊，但我很多时候想选取复制某个词，用于添加专有名词翻译，或者用外部工具、网络查词，这时候不得不关闭快捷查词功能。另外，我发现我的查词窗口除了几个本地词典外，没有其他词典
![图片](https://user-images.githubusercontent.com/117036098/211301876-5d1b3f22-5336-41eb-81f2-dded79a27417.png)

**Comment by HIllya51** [comment]
> 因为选取模式和点击查词的功能冲突啊，但我很多时候想选取复制某个词，用于添加专有名词翻译，或者用外部工具、网络查词，这时候不得不去设置里关闭选取模式。另外，我发现我的查词窗口除了几个本地词典外，没有其他词典 ![图片](https://user-images.githubusercontent.com/117036098/211301876-5d1b3f22-5336-41eb-81f2-dded79a27417.png)

从查词窗口输入框里复制不就行了吗？或者打开历史翻译窗口复制也行啊。

你开代理了？开代理了必须其他设置里设置代理，不然连不上网。

**Comment by EXBJAN** [comment]
如你所说确实可以这样，只是除了查询的词，不能自由复制更多，嘛，这个功能就这样吧

代理没有开，不过我后台常年挂着vpn，刚关了，但youdao和goo依然没有，其他几个倒是有了

**Comment by HIllya51** [comment]
> 如你所说确实可以这样，只是除了查询的词，不能自由复制更多，嘛，这个功能就这样吧
> 
> 代理没有开，不过我后台常年挂着vpn，刚关了，但youdao和goo依然没有，其他几个倒是有了

查不到的时候是不显示的。

**Comment by EXBJAN** [comment]
> 
原来如此
