### ISSUE TITLE
韓文OCR無法使用

### ISSUE THREAD

**Issue by cs10108** [HIllya51/LunaTranslator#139]
本地ocr已經下載ko.zip 解壓到LunaTranslator\files\ocr裡面
選擇韓文 翻譯成 中文
翻譯設置成了本地或者私人百度API 都沒有任何反應
只有選成日文 英文的時候能出翻譯結果(當然都是翻譯錯的
不是很懂到底是翻譯機問題還是OCR問題
但我肯定私人百度API沒問題 隔壁團子用好久了
![N1R{ R2IGD8Y7ABE%TBKES0](https://user-images.githubusercontent.com/5214910/212319340-d6e38fe0-dd7a-49a3-b7f8-772a79fb2f21.png)

**Comment by HIllya51** [comment]
ko/det.onnx好像有点问题，把en/det.onnx覆盖到ko中即可。

**Comment by cs10108** [comment]
> ko/det.onnx好像有点问题，把en/det.onnx覆盖到ko中即可。

好的 我再試試

**Comment by cs10108** [comment]
> ko/det.onnx好像有点问题，把en/det.onnx覆盖到ko中即可。
英文的復蓋後OCR有反應了 不過翻譯出問題 全是??
有道圖片翻譯那個倒是比較完美

![12312](https://user-images.githubusercontent.com/5214910/212457837-b74f4eee-e7de-453d-b23d-6b74b6b04358.png)

**Comment by HIllya51** [comment]
![屏幕截图 2023-01-14 135607](https://user-images.githubusercontent.com/101191390/212458179-1fa968d1-1f5c-481d-8267-25e72efd936d.jpg)
你肯定是哪里设置错了。

**Comment by cs10108** [comment]
> ![屏幕截图 2023-01-14 135607](https://user-images.githubusercontent.com/101191390/212458179-1fa968d1-1f5c-481d-8267-25e72efd936d.jpg) 你肯定是哪里设置错了。

我大概懂了 本地那3個翻譯應該不太支持韓文 能用其他API
