### ISSUE TITLE
LunaTranslator閃退

### ISSUE THREAD

**Issue by AyaRu97** [HIllya51/LunaTranslator#14]
v1.9.6或之前的版本能用textractor hook 「嫁探しが捗りすぎてヤバい」(Hulotte社)的文本
但v1.10.0至v.11.0的版本選擇完遊戲進程之後LunaTranslator會直接閃退,是有bug嗎?
系統是win11 22h2 繁中。遊戲是用LE轉區。

另外，想問一下會考慮增加「自訂正则表达式」功能嗎?
有些遊戲文本是人名連著句子,像" 甘夏「あ、おはよう大輝くん」"，想將前面的人名排除掉,,省點翻譯流量..
感謝

**Comment by HIllya51** [comment]
emmm 我在2045月より上没有复现出这个bug 请问能否打开debug/stderr.txt这个文件给我看一下里面的内容，里面有记录错误信息。。
可以添加，下一个版本加一下。

**Comment by wwchy** [comment]
我把游戏下下来，win10 le转区 并没有闪退。。。

**Comment by HIllya51** [comment]
我把游戏下下来试了，win10 le转区 并没有闪退。。。

**Comment by AyaRu97** [comment]
剛剛我也試了其他遊戲。(嫁探し，ハミダシクリエイティブ，恋×シンアイ彼女，にょにんじま ―ヤるだけ管理人)
我發現只要是我在fanza DMM裡買的遊戲都不能用v1.10.0至v.11.0，會直接閃退，只能用v1.9.6或之前
這個bug應該比較難解決吧...可能要花錢買遊戲才解決到...(stderr.txt裡面是空白的)
-------------------------------------
現在應該是這樣
v1.10.0至v.11.0 : 不能用在fanza DMM裡直接下載來的遊戲，實體版和DLsite都能用。(DLsite只試了金色Golden Time)
v1.9.6或之前 : 大概是所有遊戲(?)都能用

**Comment by HIllya51** [comment]
😂我好像最近没改过这个相关的内容。。。我也不知道咋回事。。。
刚刚重新打包了一个带命令行的版本，要不你试试看一下bug在哪？

**Comment by AyaRu97** [comment]
命令行是這樣
![image](https://user-images.githubusercontent.com/115739200/195789127-1acf2153-085c-44c0-9cdb-5b0712442d81.png)

**Comment by HIllya51** [comment]
emmm
我知道了 文件路径乱码导致没办法取游戏程序的md5了 新版加了一个记录功能导致的。。。 我改一下😂
