### ISSUE TITLE
使用搭配RectZoom缩放软件的问题

### ISSUE THREAD

**Issue by POLU822** [HIllya51/LunaTranslator#141]
想问一下佬有没有办法修正冲突问题
缩放软件使用Magpie是没问题的
但是我个人习惯用RectZoom这个软件

不过用RectZoom再用翻译，翻译会一闪一闪的无法固定在最上层
看起来像是RectZoom会连翻译视窗一起尝试放大
我有录制一段这个问题影像
https://imgur.com/uVhAOLh

希望佬后续更新能够解决!感谢!

**Comment by HIllya51** [comment]
你这个软件我搜都搜不到，怎么搞？
看起来是两个窗口在争夺置顶。这我也没有办法。

**Comment by POLU822** [comment]
这有外国人搞的crack，有日英文版的
https://f95zone.to/threads/rectzoom-1-41-crack.113885/

**Comment by HIllya51** [comment]
小众还不开源，懒得搞。
