### ISSUE TITLE
Deepl translate

### ISSUE THREAD

**Issue by KirpichKrasniy** [HIllya51/LunaTranslator#142]
hello, can you add a translator https://lingvanex.com/demo/ ?

and one more question: I don’t quite understand how the transfer request to the depl site works ... it is similar to the request
https://www.deepl.com/translator?share=generic#en/ru/translation%20check
?
and then a response is issued on request?
it's just that the dipl translator works intermittently, but it translates perfectly. I tried to figure out how it works, but got confused)

**Comment by HIllya51** [comment]
> hello, can you add a translator https://lingvanex.com/demo/ ?

这一翻译器早就有了啊？

> and one more question: I don’t quite understand how the transfer request to the depl site works ... it is similar to the request https://www.deepl.com/translator?share=generic#en/ru/translation%20check ? and then a response is issued on request? it's just that the dipl translator works intermittently, but it translates perfectly. I tried to figure out how it works, but got confused)

是通过api访问的。deep对于免费用户有访问频率的限制，因此每隔一段时间就会失效。

**Comment by KirpichKrasniy** [comment]
> > hello, can you add a translator https://lingvanex.com/demo/ ?
> 
> 这一翻译器早就有了啊？

https://docs.lingvanex.com/reference/overview
as I understand it, the translator works with an access key, there are also instructions for python


> > 是通过api访问的。deep对于免费用户有访问频率的限制，因此每隔一段时间就会失效。

i know it has a time limit, but this limit is too small. I'm not the only one with this problem, I'm often told about it. Deepl only allows 2-5 sentences to be translated, after which it simply stops working.
but, if you use the web version of the translator, it turns out to translate long texts 10-20 times, after which you can turn on vpn and use it further. Is there any way to do this in a program?
or can you configure yourself which browser to access (so that it works in the background) and set the VPN itself in the browser (or on a PC)?

**Comment by HIllya51** [comment]
目前并没有很好的办法能持续免费使用deepl翻译。你说的方法很难实现。建议采用deeplapi或deeplapi-free。

**Comment by HIllya51** [comment]
lingvanex可以不使用key直接翻译。不过之前的程序好像有一点问题，刚刚稍微改了一下，不过仍然是v1.37.1，重新下载一下就可以使用了。

**Comment by KirpichKrasniy** [comment]
thanks for the answer!

**Comment by KirpichKrasniy** [comment]
1) https://github.com/Artikash/Textractor/blob/master/extensions/devtoolsdeepltranslate.cpp
I found a code for deepl translator so that it does not have 2-3 sentence limits. tomorrow I will try to rewrite it for python so that it can be ported to the program. 



2) I also found a way to translate in the background with the deepl translator site open (you can use vpn). https://desonovel.vnlx.org/2021/01/tutorial-using-textractor-with-deepl.html



3) Is it possible to use ocr recognition and reading text from the clipboard at the same time in your program? I don't want to open two luna translator apps to use both ocr and clipboard capture at the same time.
I want luna to recognize text from the screen, and then copy it to the clipboard, from there the text would be read by the google chrome extension, pasted into the url search bar, and then copied the result, and after that luna copied from the clipboard would have already text and would display it on the screen

**Comment by KirpichKrasniy** [comment]
https://github.com/eggplants/deepl-cli
another person from the community was able to find this code for python. (I'm not sure if it will suit you, but I'll send it anyway)

**Comment by HIllya51** [comment]
> 1. https://github.com/Artikash/Textractor/blob/master/extensions/devtoolsdeepltranslate.cpp
>    I found a code for deepl translator so that it does not have 2-3 sentence limits. tomorrow I will try to rewrite it for python so that it can be ported to the program.
> 2. I also found a way to translate in the background with the deepl translator site open (you can use vpn). https://desonovel.vnlx.org/2021/01/tutorial-using-textractor-with-deepl.html
> 3. Is it possible to use ocr recognition and reading text from the clipboard at the same time in your program? I don't want to open two luna translator apps to use both ocr and clipboard capture at the same time.
>    I want luna to recognize text from the screen, and then copy it to the clipboard, from there the text would be read by the google chrome extension, pasted into the url search bar, and then copied the result, and after that luna copied from the clipboard would have already text and would display it on the screen

1、在python中一般使用selenium实现类似的方法。但是引入selenium依赖会导致打包后体积过大。
2、这操作也太麻烦了。。
3、你这意思就是读取剪贴板中已翻译的结果显示出来啊，这有什么意义呢。。

**Comment by HIllya51** [comment]
> 

这个就是把selenium换成playwright（另一个类似的浏览器调试工具），没什么区别，甚至更加臃肿。。。

**Comment by HIllya51** [comment]
> https://github.com/eggplants/deepl-cli another person from the community was able to find this code for python. (I'm not sure if it will suit you, but I'll send it anyway)


这个就是把selenium换成playwright（另一种浏览器调试工具实现），没什么区别，甚至更加臃肿。。。

**Comment by HIllya51** [comment]
https://github.com/UlionTse/translators

你可以看一下这个。我不太喜欢用浏览器的方式获取翻译结果。
