### ISSUE TITLE
关于会将游戏的右下角光标识别成对话

### ISSUE THREAD

**Issue by 2658340058** [HIllya51/LunaTranslator#143]
如图，在运行Angel Court的时候，可能因为游戏本身问题，似乎会将游戏界面右下角符号的持续闪烁当成对话，从而导致原来的对话被顶掉，正则式替换试着用了一下好像也不行，问问有没有类似问题的解决方法
![X 8P0I ~XE4N7AH813W2T~C](https://user-images.githubusercontent.com/117324853/212606073-93d89655-c322-4a8c-9f9a-d7d789e5d56d.png)

**Comment by HIllya51** [comment]
已修正

**Comment by 2658340058** [comment]
> 

尝试了一下1.37.2,好像还是不行，是需要调什么设置吗（顺便一提不知道为什么设置里面说它还是1.37.1

**Comment by HIllya51** [comment]
手动重下试试。

**Comment by 2658340058** [comment]
依旧不行,唯一的变化是对话框内显现三角形了（之前是不显示的，要点重新翻译才会显示一下
![Z)G}8XTE6`JUOUBAU4RD6@9](https://user-images.githubusercontent.com/117324853/212616623-e4f2298a-4f76-44e5-83c5-9cbccc5a3171.png)
![YX6_8@NB4D$LH{CIIY2P2$9](https://user-images.githubusercontent.com/117324853/212618306-72e2b857-d8d6-43f5-acf3-d20eae0228c6.png)
话说我这样回复你那边能收到提示吗？我看别人好像可以直接回你（是要艾特吗

**Comment by HIllya51** [comment]
把这个符号过滤掉。

**Comment by 2658340058** [comment]
是这样设置吗？然后变成了图二的样子
![P)9Q%(YN2NQOC7(3R F%1_E](https://user-images.githubusercontent.com/117324853/212622209-a62aef39-b634-40c6-a5f3-c4e3f00e4e68.jpg)


![6Q@Q_23PM`9Q IWEPQ4NZDJ](https://user-images.githubusercontent.com/117324853/212622367-6c79284a-3bf8-4586-ac4a-9130f5634ecb.png)

**Comment by 2658340058** [comment]
好了，解决了，谢谢，把前面那个空格去掉,只过滤那两个三角形就可以
