### ISSUE TITLE
请问像这种用网页版来玩的方式.只能用OCR来翻译对吧?

### ISSUE THREAD

**Issue by a6070160701** [HIllya51/LunaTranslator#144]
如题
最近在用网页版玩闘神都市II
网址在这边
https://kichikuou.github.io/web/
虽然它是抓本地的档案
不过应该没办法用Textractor读取文字对吧?

**Comment by HIllya51** [comment]
是的，只能OCR

**Comment by a6070160701** [comment]
> 是的，只能OCR

好的.感谢你的解答
