### ISSUE TITLE
voicevox选择人物的声音和直接使用软件中对应人物的声音差别过大

### ISSUE THREAD

**Issue by fanyingfx** [HIllya51/LunaTranslator#145]
看了一下voicevox.py中的代码
```python
response = requests.get('http://127.0.0.1:50021/speakers',  headers=headers,proxies={'http':None,'https':None}).json()
self.voicelist=[_['name'] for _ in response]
i=self.voicelist.index(globalconfig['reader']['voicevox']['voice']) 
...
   
            params = {
                'speaker': i,
                'text':content
            }
 
            response = requests.post('http://localhost:50021/audio_query', params=params, headers=headers,  proxies={'http':None,'https':None})
       
            params = {
                'speaker': i,
            }  
            response = requests.post('http://localhost:50021/synthesis', params=params, headers=headers, data=json.dumps(response.json()) )
```
我推测应该是传的speaker不对，我看[官方文档](https://github.com/VOICEVOX/voicevox_engine#api-%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88) 中，speaker对应的是/speakers这个路径返回的json中对应的style的id，理论上来说选项菜单应该和官方的界面一样有些人是二级的，或者可以留一个选项让用户直接填speaker的id?
```json
{"name":"四国めたん","speaker_uuid":"7ffcb7ce-00ec-4bdc-82cd-45a8889e43ff","styles":[{"id":2,"name":"ノーマル"},{"id":0,"name":"あまあま"},{"id":6,"name":"ツンツン"},{"id":4,"name":"セクシー"},{"id":36,"name":"ささやき"},{"id":37,"name":"ヒソヒソ"}],"version":"0.13.3"}
```

**Comment by HIllya51** [comment]
没这个必要。这么多设置一个个都搬过来也太麻烦了吧。况且其他tts又不支持这些东西，做兼容麻烦的很。

**Comment by HIllya51** [comment]
既然你会python，要不你看着改改测好了提个pr吧。我之前已经把voicevox删掉了，懒得弄了。。。

**Comment by fanyingfx** [comment]
好吧，那我有时间的时候改改试试。。。

**Comment by prts64** [comment]
大致对voicevox.py改了一段，姑且试了一下应该没问题
`                response = requests.get('http://127.0.0.1:50021/speakers',  headers=headers,proxies={'http':None,'https':None}).json()
                print(response)
                #self.voicelist=[_['name'] for _ in response]
                voicedict={}
                for speaker in response:
                    styles = speaker['styles']
                    for style in styles:
                        voicedict[style['id']] = "%s(%s)" % (speaker['name'],style['name'])  
                self.voicelist=["%02d %s" % (i,voicedict[i]) for i in range(len(voicedict))]
                return self.voicelist`

**Comment by prts64** [comment]
大致对voicevox.py改了一段，姑且名字对上了正常

                #self.voicelist=[_['name'] for _ in response]
                voicedict={}
                for speaker in response:
                    styles = speaker['styles']
                    for style in styles:
                        voicedict[style['id']] = "%s(%s)" % (speaker['name'],style['name'])  
                self.voicelist=["%02d %s" % (i,voicedict[i]) for i in range(len(voicedict))]
                return self.voicelist

**Comment by HIllya51** [comment]
> 大致对voicevox.py改了一段，姑且名字对上了正常
> 
> ```
>             #self.voicelist=[_['name'] for _ in response]
>             voicedict={}
>             for speaker in response:
>                 styles = speaker['styles']
>                 for style in styles:
>                     voicedict[style['id']] = "%s(%s)" % (speaker['name'],style['name'])  
>             self.voicelist=["%02d %s" % (i,voicedict[i]) for i in range(len(voicedict))]
>             return self.voicelist
> ```

你要pullrequests吗？你要pr的话我就等你提交了

**Comment by prts64** [comment]
> > 大致对voicevox.py改了一段，姑且名字对上了正常
> > ```
> >             #self.voicelist=[_['name'] for _ in response]
> >             voicedict={}
> >             for speaker in response:
> >                 styles = speaker['styles']
> >                 for style in styles:
> >                     voicedict[style['id']] = "%s(%s)" % (speaker['name'],style['name'])  
> >             self.voicelist=["%02d %s" % (i,voicedict[i]) for i in range(len(voicedict))]
> >             return self.voicelist
> > ```
> 
> 你要pullrequests吗？你要pr的话我就等你提交了

你帮加进去吧，菜鸡并不会用github
