### ISSUE TITLE
希望能加入obs視窗擷取支持

### ISSUE THREAD

**Issue by cs10108** [HIllya51/LunaTranslator#147]
在obs視窗擷取中視窗選擇 沒有翻譯器的進程
可能是軟件一直被認成後台軟件 沒法識別出來
有時候想在obs錄屏把翻譯字幕跟遊戲分開調整位置

**Comment by HIllya51** [comment]
你试试这样行不行：显示设置->任务栏中显示

**Comment by kuil12389** [comment]
您好，想問  我已經打開顯示設定/工具列中顯示  但仍然沒辦法從OBS擷取到文字進行翻譯，是我哪邊漏了嗎
