### ISSUE TITLE
几个新问题

### ISSUE THREAD

**Issue by csquya** [HIllya51/LunaTranslator#148]
1. 最近的程序被报毒了，我当然知道这个开源程序肯定不会有毒，但被警告不太爽。
2. 辞书-JMdict 没看到哪里可以应用
3. 语音朗读只要开头是.....(省略号)的就不会朗读，我使用的是火山TTS，也许别的TTS不会？

**Comment by HIllya51** [comment]
1、不知道，我从来不用杀毒软件。报毒的话，加到白名单里就行了。
2、没用，之前俄国老哥说想让我加一个这个，我看了下太麻烦了就没继续弄。
3、是”……“吗？……是中文省略号，shiftjis字符集里没有，如果是日本voice就读不了了（火山tts里是这样，其他tts可以）。

**Comment by csquya** [comment]
关于第一个问题，我觉得能改则改为好，也许是因为程序加壳了？ 白名单我当然知道，问题是现在下载的时候就被拦了，解压到别的地方又拦，用的是windows defender， 很多人也许都不知道怎么弄呢。极大地影响了你这个优秀程序的普及。

第二个问题”……“是日文原文里的，不是中文，中文应该用不到tts吧，但是既然别的tts就可以，应该不是问题。

又想到一个问题， 点查词的时候，会自动跳转到dict2， 而不是排在第一个的小学馆，哪怕我点了下小学馆，下次还是跳到dict2， 难道是因为哪个tab查词快，就跳到哪个tab上的词典？ 建议能默认跳到上次点击的哪个词典，或者可以自行设置，谢谢。

**Comment by HIllya51** [comment]
没加壳。不是很懂杀毒软件，无所谓了。
没法改，肯定是先出来那个就先显示哪个，不然对于一些存在延迟的网络词典，怎么弄？
