### ISSUE TITLE
需要针对日语的去除字母数字的功能

### ISSUE THREAD

**Issue by kannaginomori** [HIllya51/LunaTranslator#15]
大佬可以在文本过滤界面加一个去除字母数字的功能吗？因为有些日语游戏textractor提取到的文本里有多余的垃圾字母和数字，要是能把它们去掉就好了。

**Comment by HIllya51** [comment]
在翻译预处理-简单替换内容里面，把字母和数字逐个添加
或者在翻译预处理-使用正则表达式里面添加两项：([0-9]+)  ([a-zA-Z]+)即可。

**Comment by HIllya51** [comment]
一会更新一下，直接预设这个功能，不然感觉很多人不会用😂

**Comment by kannaginomori** [comment]
> 

感谢大佬！大佬辛苦了！话说大佬方便在ocr设置那里加上百度ocr每天限制次数的高精度识别和竖排文本识别的功能吗？这俩都是百度ocr的功能。
