### ISSUE TITLE
关于OCR的几个小建议

### ISSUE THREAD

**Issue by InugamiKira** [HIllya51/LunaTranslator#150]
（不知道软件内置的“本地OCR”是哪一个源，所以可能重了）对于日文acg作品有一个专门的离线OCR项目Manga OCR（https://github.com/kha-white/manga-ocr） 挺不错，并且支持竖排识别。
关于日文竖排文本和日文振假名的专门处理或许可以参考ImageTrans（非免费开源软件）作者的思路，他的实现方法见https://imagetrans.readthedocs.io/zh_CN/latest/manga_ocr.html ，这一功能的源码在https://github.com/xulihang/ImageTrans-docs/issues/140 的二楼有所讨论。

**Comment by HIllya51** [comment]
没有可比性。
