### ISSUE TITLE
快捷键和自动翻译的两个问题

### ISSUE THREAD

**Issue by a6070160701** [HIllya51/LunaTranslator#151]
1.
关于[快捷键设置]中的[打开设置]这个快捷键
使用时只能[打开设置]但是再按一次快捷键的话没有办法[关闭设置]
大部分快捷键都有打开和关闭的功能
希望给这个快捷键也能添加再按一次即关闭的功能

2.
我发现自动翻译关闭后
在游戏内进行几个文本后
重新打开自动翻译时
自动翻译功能会自动抓取之前[关闭中]的文本直到最新一个文本
这功能挺赞的
即使不打开自动翻译也能记录到历史文本

只是有个问题是
因为会短时间抓取大量文本的关系
想问这些文本是不是也会短时间大量发送到翻译源进行请求翻译
如果不会的话就当我没问这个问题吧
通常重新开启时
需要请求翻译的只有最后显示的文本

如果会的话希望能修改一下(比如说只到最后一个文本才发送请求)
因为某些翻译源的流量(?)是有限制的
短时间大量发送应该很容易就被开启限制了

**Comment by HIllya51** [comment]
1、好的
2、不会的，只会翻译最新的一句

**Comment by a6070160701** [comment]
> 1、好的 2、不会的，只会翻译最新的一句

感谢你对1的功能增加

关于2
![萤幕撷取画面 2023-01-26 163320](https://user-images.githubusercontent.com/122324759/214790789-b2f72280-014c-4577-beb5-801c86979dea.jpg)
我自己在测试的时候
关闭自动翻译后读取大量文本再打开后
查看历史翻译时会有一部分翻译一部分没翻译
这样看起来是有大量发送请求的现象呢
还是说这是我理解错误了?

**Comment by HIllya51** [comment]
hook下关闭后仍会读取文字，但不会进行翻译。
ocr关闭了就什么都不会做了。

**Comment by a6070160701** [comment]
> hook下关闭后仍会读取文字，但不会进行翻译。 ocr关闭了就什么都不会做了。

嗯嗯
我的操作就是hook下关闭自动翻译后
进行游戏内的大量文本
之后重新开启自动翻译
等自动翻译抓取关闭期间的所有文本后
它在抓取这些文本的期间
偶尔某些文本会在翻译视窗上冒出翻译
然后我检查了[历史文本]发现
有的会有翻译
有的没有翻译
才想说可能会有大量请求的问题

以下为我另一个使用以上操作得到的结果
![image](https://user-images.githubusercontent.com/122324759/214794669-786b42c5-c1dc-4c54-a538-e48e891d4bce.png)

**Comment by a6070160701** [comment]
再补充一个
如果关闭自动翻译期间的文本量不大的话
确实是只会有最后一个文本被翻译
![image](https://user-images.githubusercontent.com/122324759/214799704-6aa872a5-4546-464d-8965-a73c1ceca75c.png)


所以我也不确定是不是有大量发送的问题
不过既然你说只会发送最后一个文本
那应该就是没有问题吧(?
