### ISSUE TITLE
1.37.3 和 1.37.4 跳出病毒警告

### ISSUE THREAD

**Issue by AyaRu97** [HIllya51/LunaTranslator#152]
1.37.3 和 1.37.4 跳出病毒警告
是誤判還是什麼 ? 1.37.2版本之前是沒有警告的
![image](https://user-images.githubusercontent.com/115739200/215188949-b38d9b4b-4871-42fd-b0c5-9fafb2bfd4b5.png)

**Comment by HIllya51** [comment]
杀毒软件的问题，我怎么知道。

**Comment by HIllya51** [comment]
稍微改了改，换了台电脑试了一下不会报毒了。要是还报毒那我真是一点办法都无了

**Comment by AyaRu97** [comment]
感謝 ! 1.37.5 沒報毒了 ! 
昨晚用虛擬win11試了將 1.37.3 和 1.37.4 zip 解壓縮
只要不將 "LunaTranslator_no_Admin.exe" 解出來 就不會報毒了
