### ISSUE TITLE
共享辞书似乎不起作用，能请您在修复这一问题后将其改得更明显吗

### ISSUE THREAD

**Issue by kaixuan2457** [HIllya51/LunaTranslator#153]
1.我用的是最新版本，我更改了五个共享辞书版本，六个翻译，做了三十次比较，确认了您的说明里没提到这事，贴吧和哔哩哔哩上也没见到相关的反馈
2.问题是这样的，共享辞书似乎不起作用，至多只在翻译好的句子中添加了逗号，大多数时候似乎没有更改
3.我把设置栏翻了个遍……但确实未见到相关的可以使其起作用的设置
4.我想这一功能是勾选后即刻生效？能请您在确认了这一问题后将其翻译后的效果比对，改得更明显吗？
5.我不确定我是否还需要提交更多的信息，感谢您最近的辛勤更新，如果这确实是个问题，我会在看到您的回复后立刻回复，为您提供需要的信息的。

**Comment by HIllya51** [comment]
测试运行正常无误。

![屏幕截图 2023-01-29 112342](https://user-images.githubusercontent.com/101191390/215302970-037a3ad8-8ba3-4a65-abd7-f912b5b7db4e.jpg)
![屏幕截图 2023-01-29 112400](https://user-images.githubusercontent.com/101191390/215302971-56b898f5-d7d6-49f5-ba6b-049dd430d094.jpg)

**Comment by kaixuan2457** [comment]
明白了！

我附带上了这个例子，请问您那边效果如何呢？
（未开启）
たとえ豊かな人間になったところで、それは立場が変化しただけであり、構造からの脱却にはならない。
阿里  即使成为了富裕的人,那只是立场变化,不能摆脱构造。
有道  即使是丰富的人类的地方,那是只有立场也发生了变化,结构不能摆脱。
papago  即使成为富足的人，也只是立场发生了变化，不能脱离结构。
彩云  即使你成为一个富有的人，那也只是你的地位发生了变化，而不是你脱离了结构。
有道api  即使成为一个富有的人，也只是改变了立场，并不能摆脱结构。
（开启后）
たとえ豊かな人間になったところで、それは立場が変化しただけであり、構造からの脱却にはならない。
阿里  即使成为了富裕的人，那个只是立场变化了，不成为来自构造的脱却。
有道  即使是丰富的人类的地方，那是只有立场也发生了变化，从结构的脱却不应该。
papago  即使成为富足的人，它只是改变了立场，而不是脱离结构
彩云  即使你成为一个富有的人，它也只是改变了你的立场，而不是脱离结构。
有道api  即使成为富有的人，也只是立场发生了变化，而不是脱离结构。

辛苦了！

**Comment by HIllya51** [comment]
你想说什么？这前后不是明显不一样吗？

**Comment by kaixuan2457** [comment]
原来如此，是我经验还不够，麻烦您了。
