### ISSUE TITLE
hook遗漏句子的bug（或许只是我个人有这个问题？）

### ISSUE THREAD

**Issue by EXBJAN** [HIllya51/LunaTranslator#158]
该问题与特殊符号无关，且刷新延迟的调节貌似会一定程度上影响该问题，但始终不能完全避免该问题。
遇到没有hook的句子时可以通过存档再读取的方式解决
如图所示，这个问题是最近几个版本才出现的。在我的游戏库的众多游戏中都不同程度的出现了该问题，这些游戏在之前的版本中没出现这个问题（我忘记是哪个版本了，1月12号前的最后一个版本绝对不存在这个问题，之后比较忙，也没好好玩，不确定从哪个版本开始出现问题）
然后这个问题在不同游戏中的触发频率不一样，像我截图的这个游戏触发频率很高（1月12号前不存在这个问题），有时甚至隔两三句有一句。这里附上下载链接：链接：https://pan.baidu.com/s/1r2tywQkMNGfKYL4RpXiSAA?pwd=oblt 
在有的游戏中又是隔个10多句出现一次。这里我也选取了一个的下载链接：https://www.getchu.com/soft.phtml?id=1202638&gc=gc（下载第一个“体验版DL”）
也有的游戏偶尔才出行一次，通过SL大法不影响游戏体验。
![图片](https://user-images.githubusercontent.com/117036098/216026469-2815e2c7-7903-4002-ba08-e395bd6e6e3a.png)

**Comment by HIllya51** [comment]
emmm 经测试1.12之前的（1.37.0）也是一样的偶尔漏一下
暂时不知道什么原因，可能需要一段时间了。。

**Comment by HIllya51** [comment]
我去 刚说完就找到问题了，多线程访问list没加锁 OKOK

**Comment by HIllya51** [comment]
已修正

**Comment by EXBJAN** [comment]
辛苦大佬了，优秀

**Comment by HIllya51** [comment]
稍等一下 有个小bug 等下

**Comment by EXBJAN** [comment]
慢慢来，早点睡，明天再搞
