### ISSUE TITLE
deepl相关

### ISSUE THREAD

**Issue by rio-kiomi** [HIllya51/LunaTranslator#159]
大佬你好
想问下deepl相关的问题
为什么在最新的版本有deeplapi-free和deeplapi这两个api
这两者有区别吗
我在之前的版本中只填了deeplapi-free可以实现翻译（那时没有deeplapi
但在最新的版本中无法翻译，之后填了上方两处的api也无法得到翻译结果

**Comment by HIllya51** [comment]
你怎么注册的？注册的时候就说了分为free版和pro版，两个是不通用的。
这块完全没改过，我使用完全正常，可能是你的余额没了。

**Comment by rio-kiomi** [comment]
我是知道free和pro的区别的
我后面把软件全部删了一遍再重新下了再配置结果好了
可能是我一直更新就简单的覆盖文件更新有冲突导致的吧，问题解决了
