### ISSUE TITLE
可以在界面上点击对应的行就进行自动复制吗

### ISSUE THREAD

**Issue by lhj5426** [HIllya51/LunaTranslator#16]
那个...
大佬...我拿这个来翻译漫画 但是现在只能通过
![image](https://user-images.githubusercontent.com/30548000/195979414-241cf7b0-ef7a-43fc-a404-af459ddd8672.png)
来进行翻译的复制粘贴 来回切换窗口有点小不方便
可以直接在这个透明界面上
![image](https://user-images.githubusercontent.com/30548000/195979478-0254605b-9788-4b80-9672-4d6a40bb9878.png)

双击对应行或者右键菜单 来 快速复制对应的翻译文本吗?

**Comment by HIllya51** [comment]
刚刚加上了

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/196023142-f7a3c46d-4a02-49d6-8ede-d4fa283268cc.png)
看到了可以直接在界面上选择文字了 感谢
