### ISSUE TITLE
hook的问题

### ISSUE THREAD

**Issue by wyh3130024630** [HIllya51/LunaTranslator#162]
对话中有奇怪的字符，如心形，整段话就hook不出来，hook方法里找也没找到能hook出来的，有救吗。游戏《无法忍耐的童真哥哥和不直率的反抗妹妹》，还有就是这游戏hook出来的都会是一句话重复四遍或者AABBCCDD这样的，虽然能翻译优化解决就是了。

**Comment by owninnn** [comment]
> 

hook设置-字符过滤-将心形添加到例外就可以了，最近几个版本有添加这个功能，或者干脆关掉字符过滤也行

**Comment by HIllya51** [comment]
呃
