### ISSUE TITLE
hook方式获取台词文本不全

### ISSUE THREAD

**Issue by Palvure** [HIllya51/LunaTranslator#163]
版本是最新版1.39.3，测试游戏是麻呂の患者はガテン系3
用hook方式获取文本会遇到获取的内容不全的情况，举个例子：人物对话原文是”されたミんゃなズですか這よ字“，但是程序只能hook到”ミズ這よ字“这一部分的内容
不知道具体原因是什么，不知道会不会是hook页面中代码页选项的相关问题，但是其他选项我都试过了，没有能行的
hook是获取原文最快的方式，体验也最好，希望能修正这个bug，我可以配合把游戏本体发给您

**Comment by Palvure** [comment]
补一点。ORC自动化方法可以添加一个分析图像更新+周期性更新吗？我在测试中遇到一个问题，就是人物有变化时，图像和台次会一起变化，这会导致orc识别翻译失败，软件的翻译栏没有变化，必须要选择“重新翻译”才能在翻译栏更新出新的台次翻译。估计如果添加一个先进行图像分析更新后，还继续按周期性更新的方式，就能相对简单的解决这个问题了。
以上仅供参考

**Comment by HIllya51** [comment]
这作需要特殊码。

**Comment by Palvure** [comment]
感谢！
