### ISSUE TITLE
Hook获取文本重复

### ISSUE THREAD

**Issue by Zhao-Linke** [HIllya51/LunaTranslator#166]
请教大佬，这边Hook到游戏之后，文本选择出来的结果自动每个字符重复三次，请问怎么破呀？
举例来说，就是原文是`你好呀`，hook的文本框出来的就是`你你你好好好呀呀呀`。

**Comment by ssincxv** [comment]
在翻译优化里面有个去除重复字符

**Comment by Zhao-Linke** [comment]
喔，解决了，感谢！

> 在翻译优化里面有个去除重复字符
