### ISSUE TITLE
可以添加排除程序吗？

### ISSUE THREAD

**Issue by lhj5426** [HIllya51/LunaTranslator#167]
这么干净的issues 
很抱歉又污染了这个页面
想问下大佬可以添加一下排除程序的功能么
https://user-images.githubusercontent.com/30548000/217147962-8d8a82ae-3b45-4ef1-ae5d-39379e2161a5.mp4
比如排除自身?
如视频所示那样 我在  LunaTranslator 翻译面板上直接复制任意一段文字  面板会 识别这个复制的文字然后 再次翻译
如果可以添加排除的程序或者排除自身的话 就是在LunaTranslator 的面板上复制文字 不会 在此被识别 然后再次翻译 已经翻译过的文字了

或者反向 只针对某个程序来 运行 比如 
![image](https://user-images.githubusercontent.com/30548000/217148608-fadf2d9f-da79-48aa-8bab-f490618e4be6.png)

**Comment by lhj5426** [comment]
github 好像真的改版了 视频不再是预览形式了 成了链接。。

**Comment by HIllya51** [comment]
可以，已经搞明白了

**Comment by lhj5426** [comment]
> 可以，已经搞明白了

实装了嘛？

**Comment by HIllya51** [comment]
当然

**Comment by lhj5426** [comment]
> 当然

![image](https://user-images.githubusercontent.com/30548000/217286968-18be62b1-3791-40e0-893d-d4cd95a64f80.png)
看到了 得重新下载 新版 而不是直接 在旧版上更新

**Comment by lhj5426** [comment]
> 似乎如果后台有僵死的进程，就会假更新。。。

喔  这算个更新的bug ？

**Comment by HIllya51** [comment]
这个问题其实一直都有。比如用内置的le加载一个游戏，然后不关闭游戏，然后这个时候更新。但是因为游戏还开着所有le的dll没有释放，所有更新就失败了。但这也是没办法的事。

**Comment by lhj5426** [comment]
> 这个问题其实一直都有。比如用内置的le加载一个游戏，然后不关闭游戏，然后这个时候更新。但是因为游戏还开着所有le的dll没有释放，所有更新就失败了。但这也是没办法的事。

无妨  不过 我是用来当翻译器用 而不是读取游戏 所以更新的时候没有hook 任何游戏 软件是独立自己运行的
要说顶多是强奸下系统剪切板

**Comment by luojunyuan** [comment]
> 这个问题其实一直都有。比如用内置的le加载一个游戏，然后不关闭游戏，然后这个时候更新。但是因为游戏还开着所有le的dll没有释放，所有更新就失败了。但这也是没办法的事。

可以尝试内置le启动游戏之后，强制kill le的程序？这似乎对运行后的游戏完全没有任何影响。

**Comment by HIllya51** [comment]
> > 这个问题其实一直都有。比如用内置的le加载一个游戏，然后不关闭游戏，然后这个时候更新。但是因为游戏还开着所有le的dll没有释放，所有更新就失败了。但这也是没办法的事。
> 
> 可以尝试内置le启动游戏之后，强制kill le的程序？这似乎对运行后的游戏完全没有任何副作用影响。还能降低le多的驻内存占用大小部分。

没用。le注入的dll不会因kill le而释放。
