### ISSUE TITLE
一些提取[群青のオルファネージ]文本的问题

### ISSUE THREAD

**Issue by a6070160701** [HIllya51/LunaTranslator#168]
1.常常会预先提取出还没在游戏内显示出的文本.以下图为例.才出现两句话.就已经把后面好几句话都提取出来了
![image](https://user-images.githubusercontent.com/122324759/217192999-1dee5fdb-9a16-44ef-9a15-18e13aaf8217.png)

==========================================================================
2.这游戏的某些文本是有CV的.有台词念出来时会出现一些非对话内容.如: \vo[a_005]
![image](https://user-images.githubusercontent.com/122324759/217174781-59951a2a-6e1e-479c-8548-b09604f8c737.png)

==========================================================================
3.有些带有[颜色]的文字.也会出现非对话内容.如: \[C]1
![image](https://user-images.githubusercontent.com/122324759/217176031-10d648f3-10b7-43a3-95a5-02d2ef9125d4.png)

关于2和3是算还好
不算是非常影响阅读

不过1就比较不太舒畅
当然一次读完也是可以
不过就没有那么符合游戏的气氛

这3个问题也不是说不能自己适应
不过如果能调整的话会更好
谢谢作者一直以来的修BUG和新增功能

顺便一问
这个游戏可以使用新增的那个内嵌翻译功能吗?
(我自己刚刚试了.是无法.不确定是不是自己操作不对)
我通常都是在sandboxie内执行游戏和翻译器
不确定这个是否会影响它的运作

**Comment by HIllya51** [comment]
1、没办法，这是游戏自己的问题
2&3、翻译优化开启过滤英文&过滤数字&简单字符串替换添加“\”

**Comment by HIllya51** [comment]
不可以，这个只支持少部分游戏。

**Comment by a6070160701** [comment]
> 1、没办法，这是游戏自己的问题 2&3、翻译优化开启过滤英文&过滤数字&简单字符串替换添加“\”

了解哩
原来可以这样修正
感谢教学
