### ISSUE TITLE
请问一下最新版本快捷键

### ISSUE THREAD

**Issue by a6070160701** [HIllya51/LunaTranslator#169]
如题
之前我可以透过快捷键
快速切换文本输入源

1.剪贴版翻译
2.OCR翻译
3.HOOK

怎么到了最新版之后
这些功能拔掉了呢?

**Comment by HIllya51** [comment]
改UI的时候忘了改了 回头补一下

**Comment by a6070160701** [comment]
还有我在测试使用内嵌时
选择游戏进程后翻译器卡了数秒后就自动关闭了
之后使用一般的HOOK
则抓取不到文本
翻译视窗好像显示什么[hook进程102xx]  <<==xx忘了是多少
总之觉得哪边怪怪的
我就先换回2.0.0版本来用了
这版hook正常
我是在sandboxie执行的翻译器和游戏
游戏名是[コクハクゲエム]

**Comment by HIllya51** [comment]
内嵌和普通之间有时会有点冲突，如果试了几次都不支持的话还是直接用普通hook的好。

**Comment by a6070160701** [comment]
> 内嵌和普通之间有时会有点冲突，如果试了几次都不支持的话还是直接用普通hook的好。

好的 谢谢
