### ISSUE TITLE
希望增加可以调整的字体边框（空心字体？）

### ISSUE THREAD

**Issue by WuAnShe** [HIllya51/LunaTranslator#17]
![KZ$FR7AW3W9A8VV}A8JK@QM](https://user-images.githubusercontent.com/73771532/196023076-b179b7fb-bd70-4e8d-811b-63c5ff320676.png)
![0~8FBD F6U KLH$DV3E4PQA](https://user-images.githubusercontent.com/73771532/196023077-64b47f8c-d017-4757-801d-97a7f5e3b63a.png)
希望增加可以调整字体边框（空心字体？）颜色和粗细，现在这样的话会出现看不清字体的情况（主要是我有点强迫症，不喜欢用黑色背景）

**Comment by HIllya51** [comment]
改了一下 可以调整了

**Comment by WuAnShe** [comment]
谢谢大佬
![Z2`M OK551LU8$1 %JW1@V2](https://user-images.githubusercontent.com/73771532/196034161-d49430f0-0e41-4325-87cd-aae6bd0e715e.png)
不过那边框好像是框的里边，参数大了后就看不清了，能把它改成外框吗，像游戏原文那样的效果。然后打开空心字体后能调整的就只有边框的颜色了，能否改成边框和字体分别调整颜色呢？

感谢大佬那么快就回复，之前都在用的Misaka，无法调整的颜色和无法隐藏的UI真的有点难受，目前大佬制作的这个是我用过最好用的翻译器，接下来也会分享给朋友使用，谢谢大佬。

**Comment by HIllya51** [comment]
OK
