### ISSUE TITLE
预翻译文件停止记录

### ISSUE THREAD

**Issue by L020304** [HIllya51/LunaTranslator#171]
版本2.2.2  2.2.4 
translation_record下的预翻译文件在记录一段之后停止继续记录，触发条件尚不明。

**Comment by L020304** [comment]
另外，机器预翻译没有显示。

**Comment by HIllya51** [comment]
> 版本2.2.2 2.2.4 translation_record下的预翻译文件在记录一段之后停止继续记录，触发条件尚不明。

原因暂时不明，但是瞎改了一下莫名其妙又不触发了。但是搁置。。



> 另外，机器预翻译没有显示。

已修正

**Comment by L020304** [comment]
2.2.6 会触发停止记录，正在测试2.3.0

**Comment by HIllya51** [comment]
如何？

**Comment by L020304** [comment]
连续有记录2M文本了，目前还没停过

**Comment by L020304** [comment]
停了 /(ㄒoㄒ)/~~

**Comment by HIllya51** [comment]
怎么回事

**Comment by L020304** [comment]
这个问题只在手动控制游戏文本播放的时候出现，貌似自动播放不受影响（2M文件都是自动状态下记录的，切到手动就出问题了）
是不是可以做个临时功能可以监控一下是否实时在记录？这样便于判断触发条件。

**Comment by HIllya51** [comment]
呃 我怎么知道它是自动还是手动

**Comment by L020304** [comment]
在玩的人知道啊

**Comment by L020304** [comment]
可以判断玩家是不是在点鼠标、空格键、回车键。
不过重点不是在判断游戏文本播放方式是自动还是手动。我想表达的意思是我在玩的过程通过中按回车或者点鼠标出现下一个文本，这样玩着玩着就会出现翻译栏卡顿一下然后停止记录的情况。在游戏里选择AUTO，游戏自动出现往后文本，好像就不会出现触发预翻译文件停止记录的情况。

**Comment by HIllya51** [comment]
这是sql的问题，和是不是自动是不可能有任何关系的。
你看一下是不是停止前后几句是不是有句子里面有引号。

**Comment by HIllya51** [comment]
或者把临近的几个句子发我看看

**Comment by L020304** [comment]
「それよりも…ねえあなた…これ♪」
答案を見た母親はテンションが上がっている。一体、今まではどんな点数だったのだろう。
「二桁なんて…初めてじゃないかしら♪」
![haha2](https://user-images.githubusercontent.com/125094357/218316044-0d2fe479-8b31-4c4c-83f8-25da56615e7d.jpg)
（かなりやばかったみたいね…　）
【淘太の父親】「………」
（下面开始没有记录）
相変わらず…何を考えているのか分かりづらい。しかし、何かを伝えようとしている事だけは分かる。
「あら、そうして頂きます？…　うふふ…そうですわね♪…」

**Comment by L020304** [comment]
重启之后，这段又能正常翻译

**Comment by HIllya51** [comment]
还是没有头绪。。我盲猜一下可能是没有commit，先这样试试。

**Comment by HIllya51** [comment]
懂了，有sqlite无法接受的字符

**Comment by L020304** [comment]
2.3.4 测试了两个晚上，目前都能正常记录
\^o^/
