### ISSUE TITLE
[BUG]软件启动后直接崩溃

### ISSUE THREAD

**Issue by Ptilopsis01** [HIllya51/LunaTranslator#172]
![20230212_0111362](https://user-images.githubusercontent.com/93318731/218271710-352fb0dc-1c61-4b5c-9507-4f3f10047b30.gif)

如上图所示，启动后直接崩溃，不清楚是不是什么设置项出了bug

没找到日志文件在哪

**Comment by HIllya51** [comment]
开自动更新了吗？开了的话十有八九是自动更新更炸了。手动下载覆盖上去就行了。

**Comment by Ptilopsis01** [comment]
> 开自动更新了吗？开了的话十有八九是自动更新更炸了。手动下载覆盖上去就行了。

还真是。。这个有点搞啊
![046A16CB](https://user-images.githubusercontent.com/93318731/218274278-0e17ce78-4505-41d0-9dc3-6b099e583b69.png)

**Comment by HIllya51** [comment]
😂没办法，自动更新要考虑的东西挺多的，而且主要是组件要往外部注入dll，有占用删不掉导致失败。。就很麻烦
