### ISSUE TITLE
请问方便增加一个新功能吗？

### ISSUE THREAD

**Issue by kannaginomori** [HIllya51/LunaTranslator#173]
我在玩某游戏的时候，发现游戏本身的文本是把完整的一句话分成好几行，于是hook到的文本也是这样，完整的一句话分成了好几行。打个比方，完整的一句话本来是【小明今天早上吃了两个包子，然后去上学了。】，但hook到的文本是【第一行：小明今天早上吃了   第二行：两个包子，然后去上学了。】
所以方便像ocr设置里的【合并多行识别结果】一样，在hook设置里增加一个【合并多行hook文本】的新功能吗？
很抱歉打扰了。

**Comment by HIllya51** [comment]
文本处理->过滤换行符

**Comment by kannaginomori** [comment]
> 文本处理->过滤换行符

解决了！非常感谢！！！
