### ISSUE TITLE
这个可以考虑添加一下嘛

### ISSUE THREAD

**Issue by lhj5426** [HIllya51/LunaTranslator#174]
沪江小D 的网页翻译
https://dict.hjenglish.com/app/trans
大佬可以考虑添加一下吗？

**Comment by HIllya51** [comment]
![屏幕截图 2023-02-13 153716](https://user-images.githubusercontent.com/101191390/218398119-a552d436-c5d4-4d81-a0ec-83b623cca2ab.jpg)
这个和百度一样的，验证还很麻烦，所以不考虑。

**Comment by lhj5426** [comment]
好的😆和百度一样啊😆
