### ISSUE TITLE
adding language recognition support

### ISSUE THREAD

**Issue by maximros2023** [HIllya51/LunaTranslator#175]
please add Russian letter recognition to the functionality of the program. It will be very convenient to use your program as an announcer from the screen, in addition to the translator. It will be very cool if this feature appears.

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/releases/download/v1.1.2/ru.zip

**Comment by HIllya51** [comment]
download it and Unzip to path ./files/ocr

**Comment by maximros2023** [comment]
thank you very much!!
