### ISSUE TITLE
内嵌指定游戏后.翻译器自动关闭

### ISSUE THREAD

**Issue by a6070160701** [HIllya51/LunaTranslator#176]
如题
不知道为什么
我只要内嵌指定好游戏按OK后
会读取一段时间
然后翻译器就自动关闭
(游戏名是:shrift  版本:8.07  翻译器版本:2.3.7)

有没有人知道是什么问题
该如何解决
![Recording 2023-02-17 at 08 34 26](https://user-images.githubusercontent.com/122324759/219520138-c0225e79-9128-4015-b8e3-8ecff72530d1.gif)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/releases/download/v2.3.7/LunaTranslator_debug.zip
放了一个debug版本，我看看报的什么错

**Comment by a6070160701** [comment]
![image](https://user-images.githubusercontent.com/122324759/219549660-c9d5dc7a-d67b-4aac-90e4-70f37951eade.png)
请问这样子截图OK吗?

**Comment by HIllya51** [comment]
OKOK

**Comment by HIllya51** [comment]
晕 不小心漏打包了一个dll

**Comment by HIllya51** [comment]
重新打包了一下，应该可以了

**Comment by a6070160701** [comment]
> 重新打包了一下，应该可以了

辛苦了
那么就等你上传新版本的

**Comment by HIllya51** [comment]
已经上传了，我把2.3.7换掉了

**Comment by a6070160701** [comment]
喔喔 原来已经换了
我以为会变成2.3.8
哈哈
马上来试试

**Comment by a6070160701** [comment]
![image](https://user-images.githubusercontent.com/122324759/219554735-1e1f2900-7623-4b67-9a50-34a832942680.png)
现在不会自动关闭了
可是一直连接超时然后转回普通hook
我把自动转回关掉
也只是变成一直等待
没有内嵌成功

**Comment by HIllya51** [comment]
开内嵌之前开过普通hook吗？开过的话重开游戏，这两个有冲突。

**Comment by a6070160701** [comment]
![Recording 2023-02-17 at 08 34 26](https://user-images.githubusercontent.com/122324759/219556229-3a818e6b-6f60-4844-80eb-b3ea4a3d37d9.gif)
没有
我的操作就是
开游戏>开LUNA>开内嵌>连接超时

**Comment by HIllya51** [comment]
。。。既然之前已经记录过了就不要再次手动选择游戏了，直接让它自动选取就行了，不然自动选取的和你手动选取的，相当于开了两个hook，发生冲突了。

**Comment by a6070160701** [comment]
一样的说
这次我是
打开游戏>打开LUNA>LUNA自动内嵌>连接超时轉回普通HOOK

**Comment by HIllya51** [comment]
改了一下逻辑，你再试试

**Comment by a6070160701** [comment]
> 改了一下逻辑，你再试试

可以了
感谢你
我发现了问题
大概是因为我开游戏时没有用系统管理员权限打开
然后开LUNA是用系统管理员权限打开
这两个的权限不一样时
LUNA的内嵌就会显示超时

可惜的是
似乎部分文字
(旁白或某些选项描述)
或者战斗中对方的行动描述
内嵌没办法翻译到的样子
一般对话没有问题
谢谢你的修正
辛苦哩

**Comment by a6070160701** [comment]
稍微補充一下自身的使用心得
1.在sandboxie內.也可以正常使用.之前沒那個dll.才是自動關閉的主因.
2.要先開遊戲.之後再開內嵌.(如果開著自動內嵌.然後開遊戲的話.內嵌會失效.需要手動重新內嵌一次)
3.內嵌成功後.如果轉換成其他文本輸入源(例如OCR).那麼再轉回內嵌也會失效.
   一但做成這種操作.就只能重開一遍遊戲才能重新內嵌了.(所以有需求的話.大概只能雙開)

**Comment by HIllya51** [comment]
实测2&3并不会，估计是你做了什么别的的操作。

**Comment by a6070160701** [comment]
![image](https://user-images.githubusercontent.com/122324759/219635585-7875cbf4-c71f-464a-bb77-b21c39d14855.png)
我自己是會這樣就是哩
一樣沒有其他多餘的操作
P.S.我沒有把自動轉回普通hook打開

我手動重新內嵌一次之後
只花了不到2秒就識別到引擎了
![image](https://user-images.githubusercontent.com/122324759/219636502-65179fdc-ee78-49e4-8935-73370121a39a.png)

================================================
至於3
我自己也是會這樣就是哩
上面是我內嵌之後OCR一次
之後轉回內嵌4次
都識別不到引擎
![image](https://user-images.githubusercontent.com/122324759/219637516-4b706d47-76b0-48fd-87de-90dbc06b16c3.png)

==========================================
另外我不用sandboxie開的時候
2是沒有問題
估計用sandboxie開的時候會有一定的機率故障
不過這是我要開sandboxie的問題就是哩

不過3一樣有問題
![Recording 2023-02-17 at 08 34 26](https://user-images.githubusercontent.com/122324759/219645519-3c76aa7e-84f4-450e-b55f-11d0079c00eb.gif)
