### ISSUE TITLE
想请问内嵌显示出来的字.有些会变成[口].这是我哪边设置不对吗?

### ISSUE THREAD

**Issue by a6070160701** [HIllya51/LunaTranslator#179]
![image](https://user-images.githubusercontent.com/122324759/219951747-83b302ee-ab48-4f21-bccd-9a095bac3a53.png)

明明看log都能正常显示出来
但在游戏内显示的却会变成[口]

**Comment by HIllya51** [comment]
游戏的字符集没有这个字。

**Comment by a6070160701** [comment]
> 游戏的字符集没有这个字。

嗯嗯
不过我没有这方面的知识
不知道该怎么完善字符集
看来只能遇到[口]时打开log来看了
谢谢

**Comment by HIllya51** [comment]
你可以在翻译结果修正里把无法显示的字符替换成可以显示的&意思相同的字。

**Comment by a6070160701** [comment]
> 你可以在翻译结果修正里把无法显示的字符替换成可以显示的&意思相同的字。

好的 谢谢
我再试试

**Comment by a6070160701** [comment]
我后来还是决定先用普通hook了
对这游戏(shrift)来说

1.内嵌有很多非对话的内容无法涵盖
2.有些对话中有颜色强调.在内嵌状态下不会有颜色.
3.在某些对话中.会直接当机.
![image](https://user-images.githubusercontent.com/122324759/220236518-07086082-7450-4de0-8095-b3d8e93d5488.png)

4.字符集的问题.即使换了字.也不确定新的字是不是可以正常显示.
5.内嵌成功后.切换成OCR.再切回内嵌时.内嵌会失败.需要整个重开重新内嵌.(版本2.4.1)(目前是会出现[连接超时 内嵌失败])
作者你好像没问题的样子.不过我是会出现这种状况.也许我之后再问问论坛上其他人看有没有解法.

总之诸多问题下
目前还是决定使用普通hook比较顺手
普通hook和OCR之间随时切换也没有问题

**Comment by HIllya51** [comment]
☺️这只是一个可选的功能，泛用性还是普通hook更好一点，因为vnr有而且我觉得比较有意思就搬过来了，相比于外挂有时候内嵌沉浸感更好一点

**Comment by a6070160701** [comment]
> ☺️这只是一个可选的功能，泛用性还是普通hook更好一点，因为vnr有而且我觉得比较有意思就搬过来了，相比于外挂有时候内嵌沉浸感更好一点

嗯嗯 如果不是RPG的话
换成那种纯粹的对话式gal
用内嵌应该会感觉比较好

这类型的RPG因为有各种介面的日文
战斗中还有各种跳出式的状态描述
内嵌的效果比较差强人意一些
