### ISSUE TITLE
谷歌线上翻译出错

### ISSUE THREAD

**Issue by POLU822** [HIllya51/LunaTranslator#18]
大佬你好，我是在台湾使用这软件的人
从1.7版也更到1.11
谷歌1或谷歌2的线上翻译都是出错(其他线上翻译大多正常)
不知道是哪有问题，不知道有没有办法解决呢
谢谢大佬

**Comment by HIllya51** [comment]
啊这 没想到还有台湾同胞在用😂
因为我们这边谷歌翻译停止运营了所以我其实已经移除了谷歌翻译。。不过既然还有需要的话，后面我再修改一下吧。。

**Comment by POLU822** [comment]
谢大佬了阿!
