### ISSUE TITLE
大佬。WIN7虚拟机打不开程序

### ISSUE THREAD

**Issue by yy5552789** [HIllya51/LunaTranslator#180]
win10主机上能打开。在7的虚拟机上打不开

**Comment by HIllya51** [comment]
安装Visual C++ Redistributable运行库。

**Comment by yy5552789** [comment]
大佬，我安装了还是不行，还是说下个360来修复下？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HIllya51/LunaTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 中午11:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HIllya51/LunaTranslator] 大佬。WIN7虚拟机打不开程序 (Issue #180)





 
安装Visual C++ Redistributable运行库。

**Comment by HIllya51** [comment]
没装全。

**Comment by yy5552789** [comment]
试了很多次，也不知道啥原因。我看我win10主机的也没几个运行库呀，头都大了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HIllya51/LunaTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 中午1:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HIllya51/LunaTranslator] 大佬。WIN7虚拟机打不开程序 (Issue #180)





 
没装全。

**Comment by HIllya51** [comment]
你也不把具体表现说清楚，谁知道到底怎么回事？况且兼容性的问题本来就很难解决。

**Comment by yy5552789** [comment]
具体表现就是在WIN7虚拟机上打不开，就是程序都没运行，图标都没有...也用DXDLL修复工具弄过了。我正在下载win10的虚拟机，等下我去那上面试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HIllya51/LunaTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 晚上6:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HIllya51/LunaTranslator] 大佬。WIN7虚拟机打不开程序 (Issue #180)





 
你也不把具体表现说清楚，谁知道到底怎么回事？况且兼容性的问题本来就很难解决。
