### ISSUE TITLE
大佬，请添加新的在线OCR-火山OCR

### ISSUE THREAD

**Issue by Pettety** [HIllya51/LunaTranslator#181]
火山引擎地址：https://console.volcengine.com/
大佬，请添加"火山OCR",因为它目前是完全免费的，且拥有较高的识别精准度。
感谢！！！

**Comment by HIllya51** [comment]
。
跑不起来，使用官方sdk显示'Access Denied: charge perm forbid'，也不知道什么原因。

**Comment by HIllya51** [comment]
可以的 我有个地方写错了。

**Comment by Pettety** [comment]
解决的好快
再次感谢！
