### ISSUE TITLE
源语言自动检测bug

### ISSUE THREAD

**Issue by ssincxv** [HIllya51/LunaTranslator#182]
源语言自动检测没有效果。

**Comment by HIllya51** [comment]
不是所有翻译能有自动。

**Comment by ssincxv** [comment]
还有一个就是搜索特殊码，为什么我一直按搜出来的条目很少，御坂的那个HookFinder就能搜出来很多，应该都是用的Textractor的吧

**Comment by HIllya51** [comment]
御坂那是纯摆烂不作任何处理的。我把乱码都过滤掉了。而且很多同一个特殊码的都合并到一起了。
