### ISSUE TITLE
可以使内嵌翻译不支持翻译文本框上方的名称吗？

### ISSUE THREAD

**Issue by uzuki5245** [HIllya51/LunaTranslator#184]
VNR一直有这个功能。名称经常出现重复翻译并带有多余字符的现象，尝试了更改了很多设定，都无法处理这个问题。

此外，对于内嵌翻译，可以使它保存在游戏的历史回看文本中吗？

**Comment by HIllya51** [comment]
。。。我咋看不懂你说的是啥意思呢
历史可以看得啊，有个按钮可以看所有历史翻译 。
