### ISSUE TITLE
共享辞书不生效

### ISSUE THREAD

**Issue by zlpoi** [HIllya51/LunaTranslator#185]
luna使用的是昨天的2.44版本，vnr使用的是22年5月的版本，共享辞书是vnr自带的。
都使用腾讯api，下面三张图片分别是luna，vnr（开启共享辞书），vnr（删除共享辞书）。
luna的共享辞书不生效，luna的翻译和删除共享辞书的vnr一致。
![8726BCAC-0E4F-4D8E-95F9-792245B142D3](https://user-images.githubusercontent.com/126322052/221352348-070b2983-39e2-4a26-96c8-caf804c203a8.jpeg)
![D6D7A5A5-D00F-488E-9685-CF214D3FF511](https://user-images.githubusercontent.com/126322052/221352351-1ca8f071-a809-4bcb-8435-36a6cc593e66.jpeg)
![1124680C-02E4-4A7F-AF15-9BF9A6B80F0D](https://user-images.githubusercontent.com/126322052/221352353-3fa63bf0-e421-4611-8687-425c838efa5b.jpeg)
![471E4073-80E2-4378-A8D3-C0877F86F1A9](https://user-images.githubusercontent.com/126322052/221352357-44285f9e-0e38-4965-a0b4-ef05e9740d39.jpeg)

**Comment by HIllya51** [comment]
你把你用的辞书发我看看，我手头没有。

**Comment by zlpoi** [comment]
[gamedic.zip](https://github.com/HIllya51/LunaTranslator/files/10831116/gamedic.zip)

**Comment by HIllya51** [comment]
已修正。但这句话中的词条仍不会生效，因为它使用的是vnr自己魔改的正则表达式。

**Comment by zlpoi** [comment]
感谢，我下载了你刚发布的版本，共享辞书大多数时候都能起效了，但仍有不少像你所说不能生效的情况。共享辞书300页中60页，大约有20%的词条都是正则。请问以后会加入对共享辞书的更多支持吗？

**Comment by HIllya51** [comment]
它的格式太过乱七八糟。因此除非有人能研究明白它的格式并pr，否则不会。
