### ISSUE TITLE
繁简转换的代码在哪里？

### ISSUE THREAD

**Issue by jsfqq** [HIllya51/LunaTranslator#186]
我使用hook方式获取的文本，然后经过繁简转换后，原来的“「“和”」“变成了引号，而我想让转换后能够保留文本中的“「“和”」“，但又找不到代码来改

**Comment by jsfqq** [comment]
或者说我应该怎么设置才能达成我想要的效果，我希望转换前和转换后除了文字外都基本不变
例如：
原文本
Google:
    「憂郁的臺灣烏龜」
我希望转换后能够变成
Google:
    「忧郁的台湾乌龟」

但现在它只能变成
Google: "忧郁的台湾乌龟"
其中的括号变成了引号，名字也变得和内容在同一行。

谢谢啦

**Comment by HIllya51** [comment]
文本处理->过滤换行符，关闭掉
翻译优化->使用翻译结果修正，把”->「和“->」添加进去。

**Comment by jsfqq** [comment]
翻译优化确实可以把那两添加进去，但换行这个不行，因为本来就没有开换行，它是自己文本里就没有换行的

**Comment by HIllya51** [comment]
呃  那你这样：正则表达式替换，添加：”^Google:“->”Google:\n“
![屏幕截图 2023-02-26 114011](https://user-images.githubusercontent.com/101191390/221391061-432c5c22-3f31-48e0-9bd0-fecd1e0b8b53.jpg)

**Comment by jsfqq** [comment]
可以了，(*^▽^*)
