### ISSUE TITLE
试问能否增加一个非常不重要的功能

### ISSUE THREAD

**Issue by lnusyaha** [HIllya51/LunaTranslator#187]
暗黑模式。
![5C0E65DA76C75D7FB8DED04E64019682](https://user-images.githubusercontent.com/116066807/221371942-0c2d4a98-12bc-4482-9b95-41437f8a9ac2.png)

**Comment by HIllya51** [comment]
。。。我看看吧

**Comment by HIllya51** [comment]
最新版已支持
