### ISSUE TITLE
v2.5.0 hook模式 进程选择后闪退

### ISSUE THREAD

**Issue by Meowell** [HIllya51/LunaTranslator#188]
管理模式打开时，两种hook模式均是，选择log进程后闪退，选择游戏主进程检测不到文本
非管理模式打开时，检测不到log进程，选择游戏主进程检测不到文本orz
https://user-images.githubusercontent.com/42087251/221373467-bcf277ca-15d6-46bb-be9e-845636db8141.mp4
录屏是2.3.7的，2.5效果一样

**Comment by HIllya51** [comment]
2.5增加了一个错误记录，你把报错时的cache/errlog.txt发我看一下
