### ISSUE TITLE
使用chatgpt作为翻译工具的可行性？

### ISSUE THREAD

**Issue by RyaoChengfeng** [HIllya51/LunaTranslator#189]
想使用chatgpt用于翻译：https://github.com/acheong08/ChatGPT
很多情况下它翻译的文本明显优于其他翻译。
![image](https://user-images.githubusercontent.com/69711608/221394771-6caba536-4045-422d-8798-fae175947114.png)

在translator部分提供一个类用于调用chatgpt的翻译。
如果可行我想在近几天把它加进来。

**Comment by HIllya51** [comment]
其实感觉是可以的。你可以试一试☺

**Comment by CurtisJamesgh** [comment]
HF似乎有兩個模型也支持日翻中，有空的話可以玩玩看。

[M2M-100](https://huggingface.co/facebook/m2m100_418M)
[NLLB](https://huggingface.co/facebook/nllb-200-distilled-600M)

**Comment by HIllya51** [comment]
早就试过了，效果一般般。

**Comment by yunshaochu** [comment]
chatGPT翻译最大的优点是可以根据用户的想法调整翻译结果，想发挥这个优点感觉挺难的

**Comment by RyaoChengfeng** [comment]
本来在解决逆向的chatgpt不稳定的的问题，现在出api了，模型又快又好（
