### ISSUE TITLE
vnr共享辞书的bug？

### ISSUE THREAD

**Issue by lnusyaha** [HIllya51/LunaTranslator#19]
虽然不知道是不是我问题，1.13.0版，打开VNR共享辞书后，翻译似乎会出现问题。似如：「今日はどうやって帰ろうかな…」会变成「&eos;、&eos;今天怎么カエロ呢XCZ」

**Comment by HIllya51** [comment]
用的哪个翻译器，我试试，可能有的翻译器不支持

**Comment by lnusyaha** [comment]
只试过有道3和百度api，我再试试其它的如何

**Comment by lnusyaha** [comment]
![`DI5D 9EAPNP%AV3J{ 422Y](https://user-images.githubusercontent.com/116066807/196401460-b4f21fdd-29c8-4ae5-a1d7-fce5374e2085.png)
这是刚试的结果，我用的VNR辞书是从大佬群下载下来的，不清楚是不是辞书有问题。

然后不知为啥我这百度翻译没反应，但是百度api可以用。（本人是马来西亚人，可能是地区的关系？）

**Comment by HIllya51** [comment]
emmm 
https://i.postimg.cc/3JqnpWqp/2022-10-18-181358.jpg
我开共享辞书结果是正常的。。。
放不方便把你的共享辞书发一下让我研究研究。。。

**Comment by lnusyaha** [comment]
[](https://67.gigafile.nu/0126-dc635af214a94340a04f71e5d5aac3be4)

**Comment by lnusyaha** [comment]
https://26.gigafile.nu/0126-df93c88378e5e8e00c9264334f2b5c7d5
还有这个

**Comment by HIllya51** [comment]
看了一下 辞书里面有好多用了自定义正则表达式却没有声明为正则的 不过统计了一下数量不多 我直接跳过了

**Comment by lnusyaha** [comment]
似乎从1.13.0开始变得容易闪退了？我玩灰姑娘2一段时间后就会无响应然后闪退，之前的版本好像不会这样

**Comment by HIllya51** [comment]
发了个debug版本，你可以试试，闪退的时候截个图就行了，感谢

**Comment by lnusyaha** [comment]
ok😆

**Comment by lnusyaha** [comment]
![Uploading {O[7GG2TH3ZK$L9V`XSQ@Z1.png…]()

**Comment by lnusyaha** [comment]
![{O 7GG2TH3ZK$L9V`XSQ@Z1](https://user-images.githubusercontent.com/116066807/196475572-77ac4418-df59-49a3-b557-9edbba93a9d0.png)

**Comment by HIllya51** [comment]
谢谢！已经修复了这个问题

**Comment by lnusyaha** [comment]
谢谢大佬！😍
