### ISSUE TITLE
Please add Vietnamese language to Translation and OCR language

### ISSUE THREAD

**Issue by nonamebatbai** [HIllya51/LunaTranslator#191]
Please add Vietnamese language to Translation and OCR language

**Comment by HIllya51** [comment]
OCR engine is based on https://github.com/PaddlePaddle/PaddleOCR, and they didn't provide the Vietnamese model, so I can only add Vi to Translation rather than both.

**Comment by nonamebatbai** [comment]
If your way, PaddleOCR software can scan English and translate it into Vietnamese, right?

**Comment by HIllya51** [comment]
yes

**Comment by nonamebatbai** [comment]
please help me.

**Comment by HIllya51** [comment]
In version 2.5.2 , Vietnamese has already been supported.

**Comment by nonamebatbai** [comment]
The software seems to be a bit multi-functional. Can you guide me?

**Comment by HIllya51** [comment]
Where do you have a problem?

**Comment by HIllya51** [comment]
delete directory "userconfig" and reopen the program, then you can select Vietnamese as you language.

**Comment by nonamebatbai** [comment]
![image](https://user-images.githubusercontent.com/55612825/221614530-e1fc2526-f4ff-4943-86d1-2a1270043664.png)
no Vietnamese

**Comment by nonamebatbai** [comment]
![image](https://user-images.githubusercontent.com/55612825/221614913-0fd28d51-f215-494b-9f74-f52651b96bf9.png)
so can't add Vietnamese in language Settings ?

**Comment by nonamebatbai** [comment]
![image](https://user-images.githubusercontent.com/55612825/221615204-6bf5394a-61c8-4a2c-a918-0132c73209ad.png)

**Comment by HIllya51** [comment]
> In version 2.5.2 , Vietnamese has already been supported.

you didn't download the latest version😶
![屏幕截图 2023-02-28 000428](https://user-images.githubusercontent.com/101191390/221615641-10450f01-c6f6-4ec2-a8d5-4af8c8eea8a8.jpg)

**Comment by nonamebatbai** [comment]
> > In version 2.5.2 , Vietnamese has already been supported.
> 
> you didn't download the latest version😶 ![屏幕截图 2023-02-28 000428](https://user-images.githubusercontent.com/101191390/221615641-10450f01-c6f6-4ec2-a8d5-4af8c8eea8a8.jpg)

thank
