### ISSUE TITLE
有时候不翻译

### ISSUE THREAD

**Issue by ssincxv** [HIllya51/LunaTranslator#192]
![QQ截图20230301094301](https://user-images.githubusercontent.com/116273073/222023365-006cfd15-44df-48e2-9e96-e4064208753a.png)
按了刷新键也没有翻译，但是hook里已经显示有文本了，只有有时候会这样，下一条翻译又会正常

**Comment by HIllya51** [comment]
当前句子是vc1530ogg啊

**Comment by ssincxv** [comment]
前面那一句是没有翻译的

**Comment by ssincxv** [comment]
就是上一句

**Comment by ssincxv** [comment]
![image](https://user-images.githubusercontent.com/116273073/222025240-9cc82728-6a64-4170-8f07-79cf7f422e1c.png)
这一句到翻译的时候直接是空白

**Comment by ssincxv** [comment]
是因为没有过滤掉vc1530ogg导致他跳行了是么，所以没翻译是么

**Comment by HIllya51** [comment]
嗯，你在文本处理里面把xxx.ogg过滤掉就行了

**Comment by ssincxv** [comment]
是用过滤英文字母过滤么？

**Comment by ssincxv** [comment]
过滤后还是没有翻译，字母是过滤了但是他提行了

**Comment by HIllya51** [comment]
._

**Comment by ssincxv** [comment]
![Uploading QQ截图20230301095552.png…]()
崩溃了

**Comment by ssincxv** [comment]
![QQ截图20230301095552](https://user-images.githubusercontent.com/116273073/222031132-b625d83c-9125-4d96-8272-a4339c56aa6d.png)
我通过简单字符串替换把标点替换成了字母，然后过滤英文字母过滤了标点，还是没有翻译，是因为什么呢？

**Comment by HIllya51** [comment]
看一下历史翻译

**Comment by ssincxv** [comment]
![image](https://user-images.githubusercontent.com/116273073/222032650-b7247df2-4469-4ff7-89a9-aebf2f595b8a.png)

**Comment by HIllya51** [comment]
看一下历史翻译。不是看提取的文本。

**Comment by ssincxv** [comment]
![image](https://user-images.githubusercontent.com/116273073/222033026-72143573-95b9-4964-8bd9-b3fc4655433d.png)

**Comment by ssincxv** [comment]
还有一个崩溃问题，那个qq的截图截图容易让luna崩溃，崩溃后本来游戏是记录了hook和特殊码的，崩溃后重新开，记录的失效了，只有在进入游戏最开始那一会儿按选择游戏重新选择好游戏然后重新定位特殊码，否则就是一直崩溃

**Comment by HIllya51** [comment]
崩溃的操作顺序是什么

**Comment by ssincxv** [comment]
今天触发了2次，后来就没出现过了，等下次出现我记录下顺序

**Comment by Fakak** [comment]
能顺便问一下是什么游戏吗)

**Comment by ssincxv** [comment]
> 能顺便问一下什么游戏吗）
姫騎士
