### ISSUE TITLE
小功能增加建议

### ISSUE THREAD

**Issue by ssincxv** [HIllya51/LunaTranslator#193]
![QQ截图20230301095552](https://user-images.githubusercontent.com/116273073/222025079-07c85831-7440-4a1f-b316-4e6d19507035.png)
翻译时自动隐藏整个工具栏条，只显示翻译文字，鼠标移动到文字上时显示翻译栏条

**Comment by HIllya51** [comment]
你先看看这几个按钮是什么功能再来问这个问题

**Comment by ssincxv** [comment]
额 找到了 开错了
