### ISSUE TITLE
关于 chatgpt API 作为翻译功能的改进：自定义prompt/前文关联

### ISSUE THREAD

**Issue by StarDuster** [HIllya51/LunaTranslator#197]
目前来看 gpt3.5 API 响应速度已经可以满足即时翻译要求了，而且还比deepl便宜。

**Comment by RyaoChengfeng** [comment]
@StarDuster https://github.com/HIllya51/LunaTranslator/issues/189

**Comment by StarDuster** [comment]
我又来了，实验之后发现不同的prompt对翻译效果还是有一些影响，而且可以通过prompt把前一句喂给chatgpt让他翻的更加贴合上下文，有无考虑开放自定义prompt和做一下前文关联？

**Comment by HIllya51** [comment]
我对chatgpt不是特别熟悉，如果有更复杂的需要，可以参考chatgpt的api文档，自行修改translator/openai.py。如果你有妥善的修改建议，欢迎pullrequests，或者跟我详细说明。

**Comment by HIllya51** [comment]
搞了下没太搞明白怎么用prompt = =

**Comment by lancelotleod** [comment]
搞定了，之前没开代理_(:з」∠)_

**Comment by lancelotleod** [comment]
这个开了代理解决了，还有个问题，就是我在玩樱之刻的时候，如果希望跳过人名的翻译name = {"静流"},这种，有没有办法实现呢

**Comment by HIllya51** [comment]
> 这个开了代理解决了，还有个问题，就是我在玩樱之刻的时候，如果希望跳过人名的翻译name = {"静流"},这种，有没有办法实现呢

实际上没有能保证有效的办法，除非api开放词典设置。

**Comment by LakeishaKowalczyk** [comment]
+1 

合理的提示词可以通过「告知 ChatGPT 语境」和「强制要求」来增加 ChatGPT 翻译的流畅性，准确度，避免翻译腔等等
诸如
「以下是一则法语写的笑话。请用英语重写，就像英语母语者重新撰稿的样子」
「以下是一位中国女性在社交媒体上发布的帖子。请用英语重写，就像它是英语母语者写的社交媒体帖子一样」

参考
https://www.ata-divisions.org/CLD/mts_showdown/

**Comment by HIllya51** [comment]
> 

欢迎pull requests

**Comment by HIllya51** [comment]
> +1
> 
> 合理的提示词可以通过「告知 ChatGPT 语境」和「强制要求」来增加 ChatGPT 翻译的流畅性，准确度，避免翻译腔等等 诸如 「以下是一则法语写的笑话。请用英语重写，就像英语母语者重新撰稿的样子」 「以下是一位中国女性在社交媒体上发布的帖子。请用英语重写，就像它是英语母语者写的社交媒体帖子一样」
> 
> 参考 https://www.ata-divisions.org/CLD/mts_showdown/

欢迎pull requests。
