### ISSUE TITLE
大佬，想问一下为啥我这里只有阿里的可以用，其他的在线翻译点开了也没有动静？

### ISSUE THREAD

**Issue by LHFrank1992** [HIllya51/LunaTranslator#198]

**Comment by HIllya51** [comment]
可能是你开代理了然后没有在软件里面设置代理。

**Comment by LHFrank1992** [comment]
代理我已经设置好了，然后偶尔会蹦出来几句deepl的翻译，大部分情况下只有阿里

**Comment by HIllya51** [comment]
呃 你把userconfig发我看一下吧。

**Comment by LHFrank1992** [comment]
[postprocessconfig.txt](https://github.com/HIllya51/LunaTranslator/files/10887838/postprocessconfig.txt)
[savehook_new_1.39.4.txt](https://github.com/HIllya51/LunaTranslator/files/10887839/savehook_new_1.39.4.txt)
[transerrorfixdictconfig.txt](https://github.com/HIllya51/LunaTranslator/files/10887840/transerrorfixdictconfig.txt)
[translatorsetting.txt](https://github.com/HIllya51/LunaTranslator/files/10887841/translatorsetting.txt)
[config.txt](https://github.com/HIllya51/LunaTranslator/files/10887842/config.txt)
[noundictconfig.txt](https://github.com/HIllya51/LunaTranslator/files/10887843/noundictconfig.txt)
[ocrsetting.txt](https://github.com/HIllya51/LunaTranslator/files/10887844/ocrsetting.txt)
抱歉，麻烦您了。小白一个，不太懂

**Comment by HIllya51** [comment]
试了几个没问题啊。你试了几个啊

**Comment by LHFrank1992** [comment]
百度，阿里，必应，有道，deepl，只有阿里和有道是比较顺利的，百度也是时灵时不灵，deepl几乎没反应

**Comment by LHFrank1992** [comment]
127.0.0.1:7890
话说clash的话代理设置用的是这个数字吗

**Comment by HIllya51** [comment]
你不早说。这几个本来就经常不管用。你用别的就行了。

**Comment by LHFrank1992** [comment]
好的好的，感谢大佬的辛勤付出。
