### ISSUE TITLE
人物名稱翻譯成英文

### ISSUE THREAD

**Issue by bernie84** [HIllya51/LunaTranslator#199]
![image](https://user-images.githubusercontent.com/120006764/222915559-ddc679ce-33e7-4477-81f2-8ad5b3e2a133.png)
![image](https://user-images.githubusercontent.com/120006764/222915587-208d6b53-b0c9-42d0-8d21-a2fc48668b7f.png)
人物名稱會翻譯成英文，但內文卻能正常翻譯。該如何修正呢

**Comment by bernie84** [comment]
我後來測試是只有內嵌模式才會這樣，再麻煩您處理了。

**Comment by HIllya51** [comment]
有道翻译就是这么翻的，你换个不就行了吗😅

**Comment by bernie84** [comment]
好的，只是因為之前人物名稱可以翻譯成日文，所以才會這樣問。
謝謝您的回覆

**Comment by bernie84** [comment]
還想請問有看到hook新增可以選擇人名或文字的類型，內嵌模式是否也可以新增或應用這項功能呢

**Comment by HIllya51** [comment]
这个必须对游戏单独适配，太过于麻烦，没时间搞。

**Comment by bernie84** [comment]
謝謝您的回覆

**Comment by HIllya51** [comment]
😘
