### ISSUE TITLE
功能建議

### ISSUE THREAD

**Issue by sky456757** [HIllya51/LunaTranslator#2]
希望可以添加簡單的文本去重功能

**Comment by HIllya51** [comment]
这个感觉很简单，能大概说一下是什么样子的吗，主要是我玩过的都没有出现过这个情况

**Comment by HIllya51** [comment]
是“AABBCCDD,,EEFF!!”这样的，还是“ABCD,EF!ABCD,EF!”这样的？

**Comment by sky456757** [comment]
上述兩種情況都有可能出現，還有就是希望可以把使用者指定的字符過濾掉，有時候hook出來的文本可能會參雜一些奇怪的字元，像是<br>之類的

**Comment by wwchy** [comment]
好的。我尽快加一下，挺简单的。

**Comment by sky456757** [comment]
ok了，希望之後可以把使用者的配置檔獨立出來，不然每次更新都要重新配置
