### ISSUE TITLE
设置界面有没有考虑用WinUI？

### ISSUE THREAD

**Issue by HazukiKaguya** [HIllya51/LunaTranslator#20]
就是PowerToys在用的WinUI风格。

**Comment by HIllya51** [comment]
我这用python写的，咋用winui啊😂而且设置界面能看懂就行了吧。。。

**Comment by HIllya51** [comment]
搜了一下winui似乎需要C#，我并不是很会C#。。。

**Comment by HIllya51** [comment]
其实我不是很擅长做gui。。。如果这方面你有了解的话可以指点我一下😂

**Comment by luojunyuan** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/3364

winui是微软指导的win11和win10的风格，UWP开发出来的应用就是这套风格。
winui是依赖winrt的不依赖csharp .net，但是没有官方支持想用python搞这并不容易，我没有找到可用的例子。以及界面代码肯定需要重写，不再依赖pyqt。
好看归好看，就是不太现实，实现麻烦，我认为界面本着实用的目的就够了。

**Comment by monkeycc** [comment]
https://github.com/zhiyiYo/PyQt-Fluent-Widgets

**Comment by S-1-5-21-1726115** [comment]
有的，用这个：https://github.com/ynkdir/py-win32more
