### ISSUE TITLE
Free bind

### ISSUE THREAD

**Issue by OttoTell** [HIllya51/LunaTranslator#201]
Why don't you add a free choice of a key to bind. It would be convenient for me to select the mouse keys, for example.
Thanks in advance for your reply.

**Comment by HIllya51** [comment]
I can't understand what you said. Please describe it in more detail.

**Comment by OttoTell** [comment]
I can only select shortcut keys from the provided list. Is it possible to select any key?
![image](https://user-images.githubusercontent.com/88944815/222963089-536771ac-ecac-43e8-a077-cb2c40d27364.png)

**Comment by HIllya51** [comment]
No, only the options provided can be selected.

**Comment by OttoTell** [comment]
Well, if it can't be make, then it's okay. In any case, thanks for your work.

**Comment by lhj5426** [comment]
> 你为什么不添加一个自由选择的键来绑定。 例如，选择鼠标键对我来说很方便。 预先感谢您的回复。

![image](https://user-images.githubusercontent.com/30548000/223021569-049d1a4f-59ce-4d87-a22d-e4608f3d5a11.png)
Using button mapping can solve many unreasonable and uncomfortable button settings

**Comment by luojunyuan** [comment]
Cause it's convenient to developer

**Comment by HIllya51** [comment]
I have added some other choice of key. And I can't add other keys only if I change some basic library ,which is very complex.
