### ISSUE TITLE
专有名词翻译中要填写的MD5值不知如何获取

### ISSUE THREAD

**Issue by YWtheGod** [HIllya51/LunaTranslator#202]
文本预处理/翻译优化/使用专有名词翻译功能中

需要填写“游戏ID MD5”，却不知道如何获取这个MD5值
尝试过在翻译历史的sqlite文件名中截取前半段貌似MD5的字符串填写，无效（填写0时是有效的）
也尝试过在填写游戏列表的序号，也无效

**Comment by HIllya51** [comment]
是自动获取的，不用你填。

**Comment by YWtheGod** [comment]
但是在添加新行时，那个字段出现的默认值是0, 如果我删除那个0，则名词定义会无效
那怎么区分全局和特定游戏的专有名词?

**Comment by HIllya51** [comment]
选择游戏以后会自动算的。没选择就是0.

**Comment by YWtheGod** [comment]
我用的是剪贴板模式，所以没有选择游戏的进程, 从VNTranslator项目里弄了一个自动复制内容到剪切板的rpy文件，配合剪贴板模式进行翻译
hook内置模式不成功, 普通hook模式可以hook上去，但是可能是游戏有个机制自动覆盖了对话框里头的数据，也不成功
只有OCR和剪贴板模式能用，我选择了剪贴板

**Comment by HIllya51** [comment]
剪贴板模式只能用全局的设置，没法判断是什么游戏。

**Comment by YWtheGod** [comment]
我用hook模式看了一下，自动获取的MD5值和历史sqlite文件开头的MD5值是一致的
也就是说，我有查看历史记录文件名和临时打开HOOK模式新建一条记录两种方法可以获得当前游戏的MD5值
我觉得，当切换到剪贴板模式后，只需要提供一个设置的地方让我们将这些获取的MD5值指定为当前游戏ID，就可以在剪贴板模式使用针对游戏的专有名词翻译功能了。

**Comment by HIllya51** [comment]
已加
