### ISSUE TITLE
能否增加一个 翻译结果修正的快捷入口？

### ISSUE THREAD

**Issue by lhj5426** [HIllya51/LunaTranslator#203]
如图 
![image](https://user-images.githubusercontent.com/30548000/223334762-2b2ee887-9da0-44c5-a607-99485a05304e.png)
就像  专有名词这样 在工具栏上可以有一股快捷唤出的 按钮
![image](https://user-images.githubusercontent.com/30548000/223334854-c6b0bc37-619e-46b4-a51d-621a3b1be26c.png)
因为 不是所有的人都是那您开发的工具打游戏
比如在下 在下就是用来翻译漫画所以比起专有名词 用 翻译结果修正更好一些
所以 能不能恳请 开发者 考虑一下增加一个 翻译结果修正的 快捷 工具栏入口

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/223335391-af357a46-3658-4500-9de6-8b8a496ab1cd.png)
界面设置里只有专有名词 而没有 翻译结果修正

**Comment by HIllya51** [comment]
已加

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/223616464-9dcff00b-08f9-4f45-9848-59fd51607d52.png)
感谢
