### ISSUE TITLE
作者大大不考虑盈利么

### ISSUE THREAD

**Issue by innovation9029** [HIllya51/LunaTranslator#205]
都是基于PaddleOCR的项目，隔壁的团子翻译器即使效果很差还不加新在线接口都已经20/月了

**Comment by HIllya51** [comment]
首先ocr只是其中很小一部分的功能，我基本不用，两者没太有可比性。
然后我不觉得这种东西有什么盈利能力，维护麻烦效果还很难和大厂比。
所以顶多挂个赞赏偶尔带来点惊喜能多买个零食就够了。

**Comment by innovation9029** [comment]
赞，开源社区因您而精彩！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月8日(星期三) 晚上7:53
收件人: "HIllya51/LunaTranslator";
抄送: "Author";
主题: Re: [HIllya51/LunaTranslator] 作者大大不考虑盈利么 (Issue #205)





 
首先ocr只是其中很小一部分的功能，我基本不用，两者没太有可比性。
 然后我不觉得这种东西有什么盈利能力，维护麻烦效果还很难和大厂比。
 所以顶多挂个赞赏偶尔带来点惊喜能多买个零食就够了。
 
&mdash;
