### ISSUE TITLE
关于在线翻译的响应速度问题

### ISSUE THREAD

**Issue by OrangeMontBlanc** [HIllya51/LunaTranslator#206]
最近换了chatgpt api在线翻译，感觉虽然准确度比起其他的预翻译和在线翻译都要高，但是响应速度还是有点慢用起来不够流畅。

于是就有个想法，既然在线翻译的文本历史记录都是有序保存着的，那可不可以先通过某些方法先把后面的文本都慢慢翻译完（比如空闲时开个auto挂着让它一直在线翻译），之后再load回去重新玩，如果是之前已经翻过的文本，就直接去历史记录里面找到对应的翻译结果显示出来（检索历史记录的速度再怎么说也不至于比chatgpt还慢吧），只有遇到新文本的时候再调在线翻译api。这样是不是能做到兼顾在线翻译的质量和离线翻译的速度。

以上只是我个人瞎想的东西，如果实现起来不合理的话作者大大请当我没说

**Comment by StarDuster** [comment]
我记得现在是有翻译缓存的

**Comment by HIllya51** [comment]
是有临时缓存的，不过只有1024的buffersize，或者使用预翻译，但不是很方便。
后面会改成持久化缓存的。
