### ISSUE TITLE
文本提取问题

### ISSUE THREAD

**Issue by blucca** [HIllya51/LunaTranslator#207]
现有的 Textractor 对 https://novelgame.jp/ 这里的游戏使用的 JavaScript hook 表现很差，基本没法用，并且也会提示 JavaScript hook is known to be low quality

能不能对这种引擎改进一下文本提取方式呢

**Comment by HIllya51** [comment]
打开网站看了一下，满满的粗制滥造感。
vndb上随便搜了几个都搜不到。
因此实在提不起兴趣去搞。那就用ocr呗。
