### ISSUE TITLE
v2.7.3 Hook闪退

### ISSUE THREAD

**Issue by lnusyaha** [HIllya51/LunaTranslator#210]
不知道什么原因，在hook进程选择樱之诗汉化版会闪退。（因为汉化hs没翻译，日版存档又不同）现在是靠orc来翻译的日文。

**Comment by HIllya51** [comment]
汉化补丁发我。

**Comment by lnusyaha** [comment]
好像找不到补丁了。我发汉化硬盘给你吧

秒传链接：
ee3049f974d13418dace299f9008f16a#01c08763693b6602eb1509de8fb2b246#91073460#[galgame协会@KF@NNK@KDays@SSTM]@200131.part06.rar
d1627d3c37157ddeb8091e144130b301#4dff708a84a07156f31600dcc8003a1f#734003200#[galgame协会@KF@NNK@KDays@SSTM]@200131.part05.rar
3ccb6deddfe4abd4e0fa473e3bfef7d2#399884c1b9a0fa1785fae787c0baff45#734003200#[galgame协会@KF@NNK@KDays@SSTM]@200131.part04.rar
ab326ec58617bf0a4b4e689d3ca87592#0945192c299d5b9c33accf113a068e25#734003200#[galgame协会@KF@NNK@KDays@SSTM]@200131.part03.rar
c398d504ef8171f5caf262b1d117e85a#518c85a700421b197528cec7334181ce#734003200#[galgame协会@KF@NNK@KDays@SSTM]@200131.part02.rar
75895a5af08a0655412a028394aefa44#c71b12e0d815b9f326b9fd17f1b86d7c#734003200#[galgame协会@KF@NNK@KDays@SSTM]@200131.part01.exe

解压密码：galgame协会

**Comment by HIllya51** [comment]
我特么没百度会员。是云忆夕的机翻补丁不？

**Comment by HIllya51** [comment]
唉 已发现 不是游戏的问题 是程序有个傻逼错误 稍等
