### ISSUE TITLE
大佬有考虑过azure支持的翻译api吗

### ISSUE THREAD

**Issue by chunzhimoe** [HIllya51/LunaTranslator#211]
https://azure.microsoft.com/en-us/pricing/details/cognitive-services/translator/
每个月免费200w字符翻译，针对学生账户还是非常友好的！而且访问速度在国内也可以接受

这是有关azure translator的说明
https://learn.microsoft.com/en-us/azure/cognitive-services/translator/

大佬需要azure key测试的话我可以提供！

**Comment by chunzhimoe** [comment]
另外感谢作者大大，hook功能超级好用！

**Comment by HIllya51** [comment]
可以的，但是我无法注册azure（需要visa），因此只能麻烦你提供一个key了。我的邮箱 1871535768@qq.com

**Comment by chunzhimoe** [comment]
这是azure  python-sdk
https://learn.microsoft.com/en-us/samples/microsofttranslator/text-translation-api-v3-python/translator-python-v3/

**Comment by chunzhimoe** [comment]
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/translation/azure-ai-translation-document/samples/async_samples/sample_translation_with_glossaries_async.py

**Comment by HIllya51** [comment]
。。。给我个key呀

**Comment by chunzhimoe** [comment]
已经邮件给大佬发过去了。。

**Comment by chunzhimoe** [comment]
没有的话检查一下收件箱吧。。。

**Comment by HIllya51** [comment]
收到

**Comment by HIllya51** [comment]
可以了 测试已通过 晚一点更新

**Comment by chunzhimoe** [comment]
大佬你是我滴神！！
