### ISSUE TITLE
关于预翻译的格式问题

### ISSUE THREAD

**Issue by lancelotleod** [HIllya51/LunaTranslator#212]
我自己用chatgpt翻译了一整套文本，一一对应的，但是简单集成进游戏里总是黑屏，想直接走内嵌hook，我看有预翻译的功能，那对于json格式有没有什么要求

**Comment by HIllya51** [comment]
{
   "japan":{
      "userTrans":"",
      "machineTrans":""
   },
   ...
   ...
}

**Comment by lancelotleod** [comment]
{
"japan":{
"userTrans":"いらっしゃい",
"machineTrans":"欢迎光临。"
},
"japan":{
"userTrans":"一人の男性客が店に入るなり黙ってその場で立ち止まる。",
"machineTrans":"一个男客人进入店里后默默地停在了原地。"
},
...
}
这样吗？

**Comment by HIllya51** [comment]
{
"いらっしゃい":{
"userTrans":"",
"machineTrans":"欢迎光临。"
},
"一人の男性客が店に入るなり黙ってその場で立ち止まる。":{
"userTrans":"",
"machineTrans":"一个男客人进入店里后默默地停在了原地。"
},
...
}
