### ISSUE TITLE
HOOK提取文本有问题

### ISSUE THREAD

**Issue by POLU822** [HIllya51/LunaTranslator#213]
其实已经发生好几个版本了，还是提一下
不知为何原因，偶而使用HOOK提取文本会直接死当，或者是根本提不到正常的文本
并不限定一款游戏，至少我玩了两三款都会遇到
我之前用1.36、1.37时还没有发生过这问题
后来更新到2.5.5开始发生，现在最新2.7.6也会，HOOK提取文本有时候都怪怪的，至少我回头用1.37版都能正常使用
再麻烦佬看是怎么样吧

**Comment by HIllya51** [comment]
你好歹吧什么游戏说一下啊。。

**Comment by HIllya51** [comment]
![屏幕截图 2023-03-14 231825](https://user-images.githubusercontent.com/101191390/225048471-6f19ce6b-8d15-4d36-b7db-afbaadb33c64.jpg)
随手测试无任何问题。

**Comment by HIllya51** [comment]
你是怎么操作的，是不是操作错了？操作逻辑有小改，现在需要双击条目或点击最前面的选取按钮（之前是单击+确认）

**Comment by HIllya51** [comment]
![屏幕截图 2023-03-14 232235](https://user-images.githubusercontent.com/101191390/225049814-66562d8d-946d-4b95-b35e-eec1cd61c68c.jpg)
这一作甚至可以内嵌翻译。怎么可能有错呢。。

**Comment by HIllya51** [comment]
或者你解压到其他地方来重新运行一下试试，可能有我未知的dll版本加载错误的问题或者其他兼容性问题。

**Comment by POLU822** [comment]
佬我好像抓到问题了
因为我都用繁体中文
我重用简体介面就能正常用
