### ISSUE TITLE
请求加入deeplx作为翻译源

### ISSUE THREAD

**Issue by lisansas** [HIllya51/LunaTranslator#214]
https://github.com/OwO-Network/DeepLX

**Comment by HIllya51** [comment]
这玩意没卵用啊，只会报404 page not found
![屏幕截图 2023-03-14 235410](https://user-images.githubusercontent.com/101191390/225060416-c64f5ef7-a159-4875-a267-1dccb221addf.jpg)
另外非官方api请使用离线翻译->自定义翻译来扩展。

**Comment by HIllya51** [comment]
😅看了一下，这玩意不就是deepl网页api封装了一下吗，有个锤子用。。
