### ISSUE TITLE
游戏全屏后，查单词时，点击文本窗口会弹回桌面

### ISSUE THREAD

**Issue by luojunyuan** [HIllya51/LunaTranslator#216]
游戏体验版在这里找到 http://www.a-kaguya.com/products_HP/tonari/download.html
luna版本2.7.6

**Comment by HIllya51** [comment]
用magpie全屏，游戏自己全屏我管不了。

**Comment by HIllya51** [comment]
> 用magpie全屏，游戏自己全屏我管不了。
