### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by 995890POP** [HIllya51/LunaTranslator#218]
有道图片翻译为什么有时候会翻译不出来 下图是错误代码 电脑重启无效

![Desktop Screenshot 2023 03 19 - 17 26 35 20](https://user-images.githubusercontent.com/128287416/226166078-2bbba9f6-e0e4-4d09-8751-a5b834a02a5b.png)

**Comment by HIllya51** [comment]
有限额。

**Comment by 995890POP** [comment]
该咋办

**Comment by HIllya51** [comment]
用别的
