### ISSUE TITLE
HOOK提取文本閃退

### ISSUE THREAD

**Issue by POLU822** [HIllya51/LunaTranslator#219]
前几天有询问过的...原本以为是语言问题，后来好像不是
简单来说刚载下来用是正常的，但是第二次开启HOOK之后就只会闪退
2.5以后都是这样
有测试过繁简切换、换字型、关闭全部文本处理、非管理員，都无效，还没找到问题点

总之录了一段影片，佬再看看吧
https://youtu.be/l8WOMtYJLcs

**Comment by HIllya51** [comment]
。。。无法复现你说的问题
这个问题是每次都一定会触发，还是偶然触发？

**Comment by POLU822** [comment]
必定啊，一旦停止回应之后全都无法用了
但电脑重开机后有机率能正常使用，不过第二次开启又会必定闪退
2.5.4~现在版本都会这样
1.37.4旧系统倒不会

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/releases/download/v2.7.9/LunaTranslator_x86_debug.zip
你用这个debug版本截一下报的错看一下吧，实在找不到问题。

**Comment by sakura4214** [comment]
可以试试hook设置里的自动插入特殊码给关了,我之前就是因为这个选项有卡死过

**Comment by HIllya51** [comment]
> 可以试试hook设置里的自动插入特殊码给关了,我之前就是因为这个选项有卡死过

这个之前已经改过了，应该和这个无关。

**Comment by sakura4214** [comment]
之前?我不知道您是在哪个版本改的，但是昨天我用2.7.8都还会卡死，把它关了才好的。

**Comment by POLU822** [comment]
停止回应不会报错啊，会直接把程式给关了

会不会是已保存游戏的问题
翻译跟游戏同时运行时，我先把游戏给关了再关翻译
如果我把已保存游戏给删了就能够进入HOOK选取文本，但抓取不到任何东西

**Comment by HIllya51** [comment]
> 截图给我看一下卡死时候的控制台。。

**Comment by POLU822** [comment]
我现在删掉已保存游戏之后变读取不到文本
https://i.imgur.com/BRRB4tV.png
https://i.imgur.com/zNw86UB.png
卡死就是attach都不会出现就闪退了

**Comment by HIllya51** [comment]
你截的这两张图看起来也没卡死啊

**Comment by HIllya51** [comment]
你发的图都是没卡死的  我要看一下卡死的的时候的图啊

**Comment by POLU822** [comment]
https://i.imgur.com/0yGUW2J.png
整理一下我使用(测试)的问题吧
1.电脑重启后翻译能正常使用
2.先关闭游戏再关闭翻译就会出问题(如图)
3.开始出问题就无解决办法
4.出问题之后删除已保存游戏不会卡死，但会读取不到任何东西

**Comment by HIllya51** [comment]
我要看你卡死时候的报错，你不要发正常运行时候的报错给我看啊！😬

**Comment by POLU822** [comment]
圖上那狀況就是已經卡死了...

**Comment by HIllya51** [comment]
![屏幕截图 2023-03-19 220833](https://user-images.githubusercontent.com/101191390/226181554-85be6a07-bdc5-48ff-a88b-306edb8a34fa.jpg)
这才卡死了，你这发的哪卡死了啊我佛

**Comment by POLU822** [comment]
https://i.imgur.com/fKZzOOn.png
没呀...就说卡死不会报任何错

**Comment by HIllya51** [comment]
我去。。。那我也不知道这是问题了🥶

**Comment by HIllya51** [comment]
你可以试一下，再次打开不要再去选择游戏了，它会自动加载选择过的游戏的！可能是中间发生冲突了！

**Comment by POLU822** [comment]
我知道，有时候他能正常自动加载
不过有机率性不会自动加载，这时候大概就是挂点了

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/releases/download/v2.7.9/LunaTranslator_x86.zip
我修改了一个可能存在问题的地方，你试一下？

**Comment by POLU822** [comment]
还是一样，第一次能正常使用
关闭游戏之后关闭翻译
开启游戏再开启翻译，翻译不会自动加载
选择游戏读取文本就会卡死

**Comment by HIllya51** [comment]
。。。

**Comment by POLU822** [comment]
只是不知道为啥重新开机之后必定能正常使用一次

**Comment by HIllya51** [comment]
你看一下，第一次能正常使用
关闭游戏之后关闭翻译，
关闭翻译之后，任务管理器还有没有“TextractorCLI.exe"这个进程

**Comment by POLU822** [comment]
没有
在正常运行中好像也没看见

**Comment by HIllya51** [comment]
你再仔细看一下，正常运行怎么可能没有。。

**Comment by POLU822** [comment]
正常运行的时候有
关闭翻译TextractorCLI.exe也会消失
但如果开始卡死循环TextractorCLI.exe就不会出现了

**Comment by HIllya51** [comment]
你用的32位的还是64位的

**Comment by HIllya51** [comment]
32位的可能bug多一点

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/releases/download/v2.7.9/LunaTranslator.zip
你再试一下？我又改了一下可能存在问题的地方

**Comment by POLU822** [comment]
64位元
可能要明天我再测试吧
辛苦佬了

**Comment by AyaRu97** [comment]
我在3月頭也發生過這問題，試過所有辦法也不能解決
然後選擇放棄..兩三日後又突然能正常用了...
我當時發現如果這裡「WindowsTTS是勾選狀態..但下面的"選擇聲音"卻沒有顯示任何選項的情況下」
Hook遊戲 --> 顯示「選擇文本」視窗 --> 卡死 (沒有回應)
![image](https://user-images.githubusercontent.com/115739200/226206676-f5f903ff-5edb-4493-b2ab-2d130baca607.png)
win11家用22h2 系統管理員帳

**Comment by POLU822** [comment]
好像还真的有点关联!?
语音预设是没勾选的，选择声音栏也没东西
但我勾选WindowsTTS选择声音之后变得比较稳定了
一旦卡死，重新勾选WindowsTTS可以从卡死循环变回正常状态
可能要请佬再检查看看吧

**Comment by POLU822** [comment]
经过一些反覆测试应该就是语音那个问题了
如果选择声音栏是空的一定会卡死
卡死之后就无法下拉选择声音，只能换软体版本
我比较好奇真的有人会用这功能吗?

**Comment by HIllya51** [comment]
。。。感觉和这个没有关系

**Comment by POLU822** [comment]
但我确实那个栏位是空的必定会卡死...
如果声音栏有选取就能正常用

**Comment by HIllya51** [comment]
你有测试2.8吗？我换了个依赖库。

**Comment by POLU822** [comment]
2.8测试一阵子好像是正常的
看了下他的语音合成那边不会设定跑掉
感谢佬啊，不过说真的声音选择那栏位为好像真的是问题点
因为只要那栏空的就会卡死，有选择的时候就不会

**Comment by HIllya51** [comment]
正常就行。和语言没关系的。应该是cpyhook的dll加载有问题。。。

**Comment by POLU822** [comment]
我也会继续用下去，再卡死的话我再反应
感谢佬啊

**Comment by HIllya51** [comment]
我似乎找到问题之所在了，你是不是玩的内存模拟硬盘或者其他特殊的存储上的游戏？

**Comment by POLU822** [comment]
不是的啊，游戏跟翻译直接放在HDD硬盘底下的

**Comment by POLU822** [comment]
不过我用2.8这一两天是没出现问题的
