### ISSUE TITLE
VNR那两个离线TTS不知道能不能整合

### ISSUE THREAD

**Issue by acteds** [HIllya51/LunaTranslator#22]
因为是硬盘版,程序应该是自动检测不到的.  
bdp:https://pan.baidu.com/s/1D9i3srUcs755eUyUioGkJQ?pwd=1234  
VNR吧共享目录:http://vnr-file.ysepan.com/  
[![2022-10-21-11-19-39.png](https://i.postimg.cc/LsH8XftF/2022-10-21-11-19-39.png)](https://postimg.cc/3kcTfkft)

**Comment by HIllya51** [comment]
前面尝试过 没搞定 后面有空再试一下吧。。。

**Comment by acteds** [comment]
不知道vnr怎么调用的,官网是没提供接口:https://www.ah-soft.com/voiceroid/yukari/#faq  
不过vnr也是要打开主程序才能用的,大概率是hook注入.

**Comment by HIllya51** [comment]
voiceroid 1太恶心了没法api调用 放弃了 
voiceroid2可以api调用，但之前一直过不了license验证。
不过刚才研究了一下把license给破掉了，之后可以支持voiceroid2了。

**Comment by HIllya51** [comment]
废了九牛二虎之力，搞定voiceroid2了😂

**Comment by HIllya51** [comment]
看了一下，东北俊子也可以的

**Comment by HIllya51** [comment]
不过还得重新破解，太麻烦了。之后有空再说吧。

**Comment by lhj5426** [comment]
话说这有个开源的 
https://github.com/VOICEVOX/voicevox

**Comment by HIllya51** [comment]
下下来看了一下，这个是另外做的别的tts引擎，不是voiceroid。但这似乎是个假开源，只开源了个gui😂不过这个voicevox调用起来比voiceroid简单的多。

**Comment by HIllya51** [comment]
不对 我搞错了 内核放在另外的repos里了= =

**Comment by lhj5426** [comment]
> 下下来看了一下，这个是另外做的别的tts引擎，不是voiceroid。但这似乎是个假开源，只开源了个gui😂不过这个voicevox调用起来比voiceroid简单的多。

我不懂 我只是翻译漫画的时候有时候几个机翻引起都翻译的不通顺或者不知所以我就把文字复制到这个软件里用我这个塑料听力来 理解对话意思 我看GitHub上 我就以为是开源的 哈哈
