### ISSUE TITLE
是否能增加导入配置功能，导入上一个版本的配置。

### ISSUE THREAD

**Issue by yezhaoyi123** [HIllya51/LunaTranslator#222]

**Comment by yezhaoyi123** [comment]
因为大佬频繁更新版本，导致上一个版本的配置要重新配置，希望能加一个导出导入配置功能，个人觉得有这功能是非常好的。

**Comment by HIllya51** [comment]
<userconfig>别删

**Comment by HIllya51** [comment]
别删《userconfig》

**Comment by HIllya51** [comment]
> > 别删《userconfig》
> 
> 希望把 .\LunaTranslator\postprocess 里的 mypost.py 也移到 .\userconfig 里去，每次更新删 .\LunaTranslator 这个文件夹时还要额外保留一下这个文件…

不是，为什么要删啊，直接覆盖上去就行了。。。。。。

**Comment by HIllya51** [comment]
> > > > 别删《userconfig》
> > > 
> > > 
> > > 希望把 .\LunaTranslator\postprocess 里的 mypost.py 也移到 .\userconfig 里去，每次更新删 .\LunaTranslator 这个文件夹时还要额外保留一下这个文件…
> > 
> > 
> > 不是，为什么要删啊，直接覆盖上去就行了。。。。。。
> 
> 有时候会有旧版本文件残留吧，虽然覆盖上去也能用

好吧。
