### ISSUE TITLE
[BUG]更新2.8.1后无法启动

### ISSUE THREAD

**Issue by Ptilopsis01** [HIllya51/LunaTranslator#223]
如题。自动更新、手动覆盖、有无管理员权限启动都尝试了，只会弹出一下翻译框然后就关闭，无任何其他现象

**Comment by Ptilopsis01** [comment]
备份用户数据后全删了重装就好了，怪（）
顺便问一下为什么chatgpt的api我填了并且勾选了使用但是不显示翻译

**Comment by HIllya51** [comment]
检查两个地方：1、代理设置要打开；2、超时时间要长一点

**Comment by HIllya51** [comment]
还不行的话，打开显示错误信息截给我看一下
