### ISSUE TITLE
使用百度高精度ocr提取文字与原文差异过大，可能有什么bug

### ISSUE THREAD

**Issue by edward21347** [HIllya51/LunaTranslator#225]
使用百度高精度ocr有时出现提取的文字与原文明显牛头不对马嘴的情况，刷新也没有用，必须更换其他的ocr
如图，链接: https://pan.baidu.com/s/1lc04ZPyxjMBIR9hA2B1k2w?pwd=vkf6
链接: https://pan.baidu.com/s/1vJHBoA3fB3DWa6DWGM3phw?pwd=mega 
经测试团子翻译器好像不会这样

**Comment by edward21347** [comment]
> 无任何问题。 ![屏幕截图 2023-03-21 190807](https://user-images.githubusercontent.com/101191390/226588980-b42df363-9f10-42b5-a819-b98fa641ddb4.jpg)
看有的漫画完全不会出现这个问题，看有的漫画就老是发生，可能是要满足什么条件

**Comment by HIllya51** [comment]
这要看百度自己怎么识别的。
