### ISSUE TITLE
识别竖排文字时顺序与看的漫画相反

### ISSUE THREAD

**Issue by edward21347** [HIllya51/LunaTranslator#226]
看的漫画是从右向左，但翻译顺序是从左向右 希望能适配一下顺序

**Comment by HIllya51** [comment]
做不到。百度不给坐标。

**Comment by lhj5426** [comment]
看漫画不是有 专门的漫画软件么
https://github.com/dmMaze/BallonsTranslator
支持 OCR多国语言 就是翻译引擎可选不多 彩云 谷歌 popogo  但是可以复制粘贴用  LunaTranslator 辅助翻译
