### ISSUE TITLE
使用新版本unidic导致的假名标注问题

### ISSUE THREAD

**Issue by blucca** [HIllya51/LunaTranslator#227]
https://github.com/HIllya51/LunaTranslator/releases/download/v1.0/Mecab.zip 这个版本是 2.1.2

https://clrd.ninjal.ac.jp/unidic/ 现在已经更新到 3.1.1 了

但用 3.1.1 假名标注时标点上会有 * 号
![image](https://user-images.githubusercontent.com/127029904/226795277-17e54616-7627-43ae-9e12-f779ae8a84a3.png)

**Comment by HIllya51** [comment]
已修正

**Comment by HIllya51** [comment]
这次肯定好了 刚才改错了
