### ISSUE TITLE
[功能建议]为每个游戏添加一个“游戏攻略”功能以及游戏攻略按钮

### ISSUE THREAD

**Issue by EXBJAN** [HIllya51/LunaTranslator#231]
最近在玩某些选项繁多的多支线游戏时，不免为“保持全屏”与“舒服看攻略”二者不可兼得而烦恼，所以有此新功能的设想。
我觉得可以在已保存游戏里添加一列【攻略】选项（类似一个记事本），玩家可以为每个游戏编辑、保存其攻略，至于是否图文都支持就看大佬的意愿了。
然后在界面设置里增加一个按钮，玩家在玩已保存游戏时，可以点击该按钮查看、编辑并保存对应游戏的攻略。然后随游戏删除而删除。

**Comment by HIllya51** [comment]
已加

**Comment by EXBJAN** [comment]
虽然是共用的，但是也很方便了，感谢！！
