### ISSUE TITLE
Guilty社作品無法提取文字

### ISSUE THREAD

**Issue by y49711** [HIllya51/LunaTranslator#232]
GUILTY社的作品 提取時遊戲都會死當
測試了兩部作品
アイドルのナマ配信
女体でもてなす接待旅館
選取ADVHD.exe提取

**Comment by HIllya51** [comment]
什么版本？

**Comment by y49711** [comment]
> 什么版本？

2.8.1
2.8.3
2.8.5
這三版本這幾天試過不行

**Comment by HIllya51** [comment]
测试发现是texthook的问题，等下修一下
