### ISSUE TITLE
Local OCR is delayed while playing games

### ISSUE THREAD

**Issue by nonamebatbai** [HIllya51/LunaTranslator#233]
when I use Local OCR to translate text during game play, there is a delay. Can you fix it?

**Comment by HIllya51** [comment]
？
I can't understand  what you mean.

**Comment by nonamebatbai** [comment]
![image](https://user-images.githubusercontent.com/55612825/227536729-a9dc0c53-9a95-4dbc-a798-8856fef69cfc.png)
When I play games that use local OCR to translate, it will lag

**Comment by nonamebatbai** [comment]
![image](https://user-images.githubusercontent.com/55612825/227537171-bcf40467-23ad-4934-9df8-7abdb6f3d7f2.png)

**Comment by HIllya51** [comment]
Manabu is an online ocr, so its slow is normal

**Comment by HIllya51** [comment]
I completely cannot understand what your question is about. Could you clarify it a bit??

**Comment by nonamebatbai** [comment]
when I play a normal game that doesn't use "Local OCR" the FPS is 60.
but when I turn on "Local OCR" to translate, the FPS when playing the game is only 20

**Comment by HIllya51** [comment]
I finally got a rough idea of what you mean.
However, this is normal, and it is not a bug. Ocr is a deep learning based method that requires a large amount of cpu resources, so it is normal for you to get stuck when running other programs that require cpu resources.
