### ISSUE TITLE
hook提取文本的时候是否能过滤掉名字？

### ISSUE THREAD

**Issue by yezhaoyi123** [HIllya51/LunaTranslator#234]
<img width="462" alt="Snipaste_2023-03-26_19-38-13" src="https://user-images.githubusercontent.com/63576907/227773219-76ffee5e-6c73-4eb8-a660-38ca49ed1e99.png">
<img width="352" alt="Snipaste_2023-03-26_19-38-24" src="https://user-images.githubusercontent.com/63576907/227773221-4fdf1ae4-f92f-4b14-a568-2b54e1740286.png">

**Comment by HIllya51** [comment]
文本处理里面自己把名字过滤掉。

**Comment by yezhaoyi123** [comment]
哦哦，谢谢
