### ISSUE TITLE
Using the converter

### ISSUE THREAD

**Issue by s3h0cx** [HIllya51/LunaTranslator#238]
First of all, thank you for adding the Turkish language, I wonder if you have information or a video on how to use the program, can you send the link, but also if you have a discord server.

**Comment by s3h0cx** [comment]
I understand, during the usage phase, will I open the application and choose my language, will I do anything else?

**Comment by HIllya51** [comment]
Maybe Yes?
What exactly are you asking? Can you make it clear?

**Comment by s3h0cx** [comment]
In other words, after setting the translator to my own language, will it automatically translate an English game into Turkish? Is there any extra setting I need to do?

**Comment by HIllya51** [comment]
![屏幕截图 2023-03-29 233344](https://user-images.githubusercontent.com/101191390/228591019-510d03ed-a07a-4d30-b769-bb5969dffbb5.jpg)
