### ISSUE TITLE
Please add Korean to DeepL, Papago, Google

### ISSUE THREAD

**Issue by migig3** [HIllya51/LunaTranslator#239]
please

**Comment by HIllya51** [comment]
I am not interested in checking whether each translation supports each language, which is a waste of time.
You can add Korean to translator/deepl.py by yourself.

**Comment by HIllya51** [comment]
I added deep, and didn't see you add Papago and Google again. If you need Papago and Google, please add them yourself

**Comment by migig3** [comment]
I'm sorry. I checked again and the Korean translation works well in several translators. I must have misunderstood something.

However, when using DeepL, it was translated once or twice, and then 429 client error appeared and the translation was not possible.  When I access the DeepL site, it says that I have exceeded my daily usage limit.  Even though I only translated a little bit.  It's the same even if I try changing the IP address with the VPN. Something is strange.
