### ISSUE TITLE
[新功能]灵活的OCR、翻译计数，超额提醒。

### ISSUE THREAD

**Issue by XiaoXiaoYanHe** [HIllya51/LunaTranslator#240]
设定“OCR每日5万次” “翻译每月200万字节”，套餐剩余10%或20万字节时提醒。
【时间】每年每月每日/自定义，【计数方式】字节/次数，【余额提醒】%/字节/次数
多套餐混合（用不到，划掉）

**Comment by HIllya51** [comment]
太麻烦了，懒得弄。如有需要欢迎自行修改。
