### ISSUE TITLE
hook提取到的文本自动换行，导致翻译的时候也分开翻译

### ISSUE THREAD

**Issue by lqwkukuku** [HIllya51/LunaTranslator#243]
如图
![联想截图_20230402131738](https://user-images.githubusercontent.com/129644030/229333428-359f968e-03aa-4b0a-964e-aff0050a6767.png)
![联想截图_20230402132041](https://user-images.githubusercontent.com/129644030/229333436-abc7ea50-8731-404b-beda-5a299d1c8971.png)
![屏幕截图 2023-04-02 132332](https://user-images.githubusercontent.com/129644030/229333439-d8bbd59e-0575-4227-ac81-8a66b6b89d41.png)
也试过文本处理的过滤换行符，没有效果，游戏是DC4 sweet harmony

**Comment by HIllya51** [comment]
提高刷新延迟

**Comment by lqwkukuku** [comment]
解决了，大佬太棒了
