### ISSUE TITLE
好像不能自动选择文本了？

### ISSUE THREAD

**Issue by lnusyaha** [HIllya51/LunaTranslator#244]
![image](https://user-images.githubusercontent.com/116066807/229333801-8d530eea-d088-4724-907e-55fe795e6afd.png)
每次打开后就算有之前选过的文本或特殊码，下次打开后也不会自动选择、要自己手动选择。不太确定是不是ｂｕｇ，请大佬看看

**Comment by HIllya51** [comment]
和游戏有关，有的游戏每次打开context不一样。

**Comment by lnusyaha** [comment]
啊这，那不是得每次都选择了吗（

**Comment by HIllya51** [comment]
那也没办法，游戏的问题
