### ISSUE TITLE
manabu ocr dont working

### ISSUE THREAD

**Issue by lizakovalsky** [HIllya51/LunaTranslator#245]
error: manabu KeyError 'ocrContents'
Traceback (most recent call last):
  File "Z:\******\____~KK3\LUNA~5PX\LUNA~5PX\textsource\ocrtext.py", line 163, in ocrtest
  File "Z:\*******\LunaTranslator\LunaTranslator\ocrengines\manabu.py", line 32, in ocr
    return self.space.join((response.json()['ocrContents'][0][0][0]['description']).split('\n'))
KeyError: 'ocrContents'

**Comment by HIllya51** [comment]
manabu is not a stable interface。please use other OCR engine。

**Comment by HIllya51** [comment]
this interface will be depracated.

**Comment by lizakovalsky** [comment]
I have such a situation, I need to read the Russian text from the picture and translate it into text that I can copy. Only manabu coped well with this. Can you help me with this? I use Linux, so neither windowsOCR nor local OCR works. All other OCR is translated into Chinese or incorrectly.

**Comment by HIllya51** [comment]
Manabu is an online ocr, and its ocr interface has expired, how I can make this website to restore it?
You can only use docsumo or ocrspace as a substitute.
And this program is only for Galgame and although it can be used for other purposes, it is not my intention. If it still cannot solve your problem, please use another program.
