### ISSUE TITLE
横  横过来了 

### ISSUE THREAD

**Issue by lhj5426** [HIllya51/LunaTranslator#246]
![image](https://user-images.githubusercontent.com/30548000/229809833-3e0d878e-7590-4e82-be79-73369262179e.png)
  一打开就这样了 
  
![image](https://user-images.githubusercontent.com/30548000/229810154-dd6f4734-3a56-4f8a-88f1-860c2e8b075a.png)
整个就 很奇怪 了
![image](https://user-images.githubusercontent.com/30548000/229810607-8c5adf30-a19d-4b8b-b18f-c07281ab6465.png)
这里的提示没跟着旋转

版本是最新的2100 版  我就是勾选了一下 在任务栏中显示 重启 就这样了  降低版本之后发现 还是有这个问题
只有把配置删了 了才行  而且 有的时候 启动的时候 这个配置 config.json 会变成0KB 导致 EXE无法启动

**Comment by HIllya51** [comment]
![屏幕截图 2023-04-04 215133](https://user-images.githubusercontent.com/101191390/229814502-2eb29b23-fa32-46a4-9e89-4261723a6d34.jpg)

**Comment by lhj5426** [comment]
> 

可能不小心碰到了吧。。  居然还有这种功能
