### ISSUE TITLE
windows ocr 英文识别单词之间没有空格

### ISSUE THREAD

**Issue by zmm147** [HIllya51/LunaTranslator#248]
比如：i  love you 变成了 iloveyou。
请问这个问题应该怎么解决呢？虽然也不是什么大问题，可以用本地ocr替代，但是想要更完美一些。谢谢！

**Comment by HIllya51** [comment]
系统不知道为什么装不上英语，所以我无法测试。等有缘人来搞吧。

**Comment by zmm147** [comment]
> 系统不知道为什么装不上英语，所以我无法测试。等有缘人来搞吧。

好吧 - -！

**Comment by HIllya51** [comment]
已修正
