### ISSUE TITLE
能否考虑一下按“游戏名 + API类型”的方式缓存翻译记录呢？

### ISSUE THREAD

**Issue by 2-3-5-7** [HIllya51/LunaTranslator#25]
能否考虑一下按“游戏名 + API类型”的方式缓存翻译记录呢？

如果这样缓存的话，我能想到几个好处。
- 查询更快了，离线也可以用，节省付费 API 的次数
- 同一个游戏的缓存文件可以分享给别人用

目前“录制翻译文件”的功能最接近，但只能选择记录其中一个 API。

如果改成按 “游戏名 + API类型” 的方式储存，即每个游戏按照不同翻译 API 各缓存一个文件。
在查询翻译时，先查询本地的缓存，没有时再发起 API 请求。

可能还是会有考虑不到的地方，只是想问问大佬的意见。

**Comment by HIllya51** [comment]
好

**Comment by HIllya51** [comment]
已支持

**Comment by 2-3-5-7** [comment]
能否（在加载机器预翻译的设置中）加一个是否显示翻译源的开关呢？想把前面的翻译来源（下图红框中）的文字去掉

<img width="645" alt="无标题" src="https://user-images.githubusercontent.com/79762374/198756357-bc0ec7aa-55de-4536-85be-fd2cc93424da.png">

**Comment by HIllya51** [comment]
已修正

**Comment by 2-3-5-7** [comment]
谢谢！
