### ISSUE TITLE
关于翻译优化

### ISSUE THREAD

**Issue by renkejinQVQ** [HIllya51/LunaTranslator#250]
我记得以前的旧版本有挺多翻译结果修正的词条的，新版本没有了么？

**Comment by HIllya51** [comment]
？？？从来就没有内置的翻译结果修正过啊，都是自己自定义的。

**Comment by renkejinQVQ** [comment]
> ？？？從沒有內部設置的翻譯結果正確修改過啊，都是自己正確的。

难道是咱看错了吗==，记得原来有500多条修正。

**Comment by HIllya51** [comment]
你记错了。
