### ISSUE TITLE
OpenAI翻译有点问题大多数都翻译不了

### ISSUE THREAD

**Issue by king2335** [HIllya51/LunaTranslator#251]
翻译的时候经常显示timeout，要点重新翻译才可以已经挂了代理了，我用别的翻译软件openai是没问题的

**Comment by HIllya51** [comment]
肯定是你设置的问题，很多人都没问题。

**Comment by HIllya51** [comment]
方便的话，把你的配置发我看一下？

**Comment by HIllya51** [comment]
我知道了，你把在线翻译超时时间调高一点就行了。

**Comment by wannengcong** [comment]
youdao图片翻译挂了么？怎么总是显示errorcode403。还有，大佬你的这个有没有教程？

**Comment by HIllya51** [comment]
> youdao图片翻译挂了么？怎么总是显示errorcode403。还有，大佬你的这个有没有教程？
有qps限制
无。
