### ISSUE TITLE
建议功能：当 显示假名 开启时，按假名长度调整汉字间隔

### ISSUE THREAD

**Issue by illusiwind** [HIllya51/LunaTranslator#252]
目前如果开启“显示假名”，当遇到比较长的汉字在一起时，假名会重叠看不清。建议如果返回的假名长度大于汉字长度，在汉字上添加空白字符使其和假名长度一致。谢谢。

**Comment by HIllya51** [comment]
使用把假名字体缩放比率缩小点就行了，没必要搞这么麻烦

**Comment by HIllya51** [comment]
> +1，还有窗口宽度不够时，每行最后一个词不显示假名的问题 ![image](https://user-images.githubusercontent.com/127029904/230779968-a22f241b-b576-44cb-9b03-1c0812d4e8db.png) ![image](https://user-images.githubusercontent.com/127029904/230779994-5a1f0adf-fe92-4046-97ef-8902e9fa06d3.png)

这玩意儿没有现成的控件，都素我手算的偏移量打的标注，实在太难弄了。。

**Comment by HIllya51** [comment]
改了一下，应该好点了

**Comment by illusiwind** [comment]
> +1，还有窗口宽度不够时，每行最后一个词不显示假名的问题 ![image](https://user-images.githubusercontent.com/127029904/230779968-a22f241b-b576-44cb-9b03-1c0812d4e8db.png) ![image](https://user-images.githubusercontent.com/127029904/230779994-5a1f0adf-fe92-4046-97ef-8902e9fa06d3.png)

说一下我的处理吧，我就直接在 LunaTranslator/gui/textbrowser.py 的 append 里 一开始加了这么一段：
```
        if len(tag)>0:
            #print(f"x was {x}")
            ori=""
            for _ in tag:
                lenDiff=len(_["hira"])-len(_["orig"])
                if lenDiff>0:
                    _["orig"]="  "*(lenDiff//2)+_["orig"]+"  "*((lenDiff+1)//2)
                ori+=_["orig"]
            x=ori
        #print(f"now x is {x}")```
也就是相差几个字符就添了几个空格。试了下看着还行。当然，只是凑合的办法，会不会造成什么其他异常我就不知道了。
三个版本比较：
更新前：

![compare0](https://user-images.githubusercontent.com/14990031/230902279-3a414e39-d319-4894-9fc0-ad55ca4cc475.PNG)
合并连续假名更新：
![compare1](https://user-images.githubusercontent.com/14990031/230902288-b9f6358e-c93f-4cc6-9483-dd9d64664e3d.PNG)
我上面的修改效果：
![compare2](https://user-images.githubusercontent.com/14990031/230902290-e82e4798-93dd-489c-9aaf-1a42fa15fb79.PNG)

**Comment by HIllya51** [comment]
我不太喜欢这样，我觉得原文是比注音更重要的，为了注音降低原文的可读性我觉得不太好。而且加空格会导致选取的内容多出很多空格。

**Comment by illusiwind** [comment]
是这样，如果不开 显示假名 的话，原文是不变的。至于有开启 显示假名 需求的用户，我觉得应该是希望假名和汉字的对应清晰一些的。这个注音叫做 furigana，你可以搜一下japanese articles with furigana，大部分有注音的文档都要调整汉字的间距，标准的做法是均匀增加每个汉字之间的间距。不过这种fancy的效果不好达到的话，前后加空格是个省事的办法。主要是 汉字和假名上下对应 比较重要。
而且这一步对 翻译、复制到剪切板 等功能都没有影响。单击查词 会多出空格，不过对结果也没有影响。
我觉得有不同喜好的话，可以把这个设为一个新的选项放在 显示假名 下边，想开启就开启？

**Comment by HIllya51** [comment]
这个东西牵涉的内容太多啦，改起来太麻烦啦
如果你感兴趣的话欢迎pr。
