### ISSUE TITLE
假名显示问题

### ISSUE THREAD

**Issue by blucca** [HIllya51/LunaTranslator#254]
首先感谢作者的改动

但改后的效果还是不好…

如图，显示不全
![image](https://user-images.githubusercontent.com/127029904/230813233-ea2f7721-78c7-40a4-b12e-6b3aafc0c4bd.png)

并且合并以后有些假名偏移距离过大
![image](https://user-images.githubusercontent.com/127029904/230813777-3e33c23d-4ca1-4ec4-ba84-31b09978ddf7.png)

能不能改成这种的
![image](https://user-images.githubusercontent.com/127029904/230814266-4f706def-adc6-49b3-8b50-2a177dc67bdd.png)

当宽度不够显示最后一个词时，把这个词移到下一行，每个词的宽度是 max(假名宽度, 词汇宽度)

**Comment by HIllya51** [comment]
不好意思，做不到

**Comment by HIllya51** [comment]
试了，没什么用，看不出来

**Comment by illusiwind** [comment]
@blucca 我fork了一个，加了 汉字加空格 的功能，按假名比汉字多出的字符个数添加。欢迎测试。测试够了就合并回来。
https://github.com/illusiwind/LunaTranslator/releases/tag/0.1

**Comment by HIllya51** [comment]
> @blucca 我fork了一个，加了 汉字加空格 的功能，按假名比汉字多出的字符个数添加。欢迎测试，多多测试。测试够了就合并回来。 https://github.com/illusiwind/LunaTranslator/releases/tag/0.1


间距太大了。用(fm.width(hira)-fm.width(orig))/(2*fm.width(' '))能好一点，但不能整除的时候间距还是会用问题。要想达到理想的样子只能全用qlabel自己算位置。

**Comment by illusiwind** [comment]
更新了下，用实际的像素宽度计算了。应该好些了。
https://github.com/illusiwind/LunaTranslator/releases
