### ISSUE TITLE
能否给专有名词或共享辞书修改过的翻译文字添加下划线或其他种类的突出选项？

### ISSUE THREAD

**Issue by deadblue0910** [HIllya51/LunaTranslator#256]
![Snipaste_2023-04-12_19-50-30](https://user-images.githubusercontent.com/48860218/231454677-311b2b07-ca98-450f-b3a5-d225d510ec89.png)
![Snipaste_2023-04-12_19-50-16](https://user-images.githubusercontent.com/48860218/231454689-daa36471-f5f8-48d3-8f29-3eb7bcdefbb5.png)

**Comment by HIllya51** [comment]
这个太麻烦了。等看有没有有缘人愿意奉献吧。
