### ISSUE TITLE
[功能建议] 添加一个“更多翻译”按钮

### ISSUE THREAD

**Issue by blucca** [HIllya51/LunaTranslator#257]
点击这个按钮可以调用更多的翻译。
这样，平时只用开启配额大但可能质量一般的翻译，当遇到长难句或者当前翻译不佳时，就可以调用效果好但配额小、限制多的翻译。
比如有道翻译，如果一直开着一会就被限制用不了了，有道api也没有免费配额。而如果采用这种方式调用，就能撑更长时间。

还有一种使用场景是啃生肉学日语，平时不开启翻译，实在读不懂时点击这个按钮可以抢救一下。

**Comment by HIllya51** [comment]
这要怎么弄呢。。。要搞只能在配置里面加这么一项，然后你自己去手改了吧？不然这么多设置得放到哪里呢。
按钮就用原来的手动翻译按钮就行了，让翻译不能在自动模式运行只能手动翻译。

**Comment by HIllya51** [comment]
我加到配置文件里面了，在config.json中对应的翻译中添加"manual":true即可。

**Comment by HIllya51** [comment]
![批注 2023-04-14 125410](https://user-images.githubusercontent.com/101191390/231945079-80425dd6-0116-41c2-b2cb-767d647fef67.png)

**Comment by HIllya51** [comment]
不会重新调用，有缓存。

**Comment by HIllya51** [comment]
我测试没问题
