### ISSUE TITLE
moji net token应该如何获取

### ISSUE THREAD

**Issue by wulianlian123** [HIllya51/LunaTranslator#258]

**Comment by HIllya51** [comment]
不知道 我没用过 你问他 @Titvt

**Comment by Titvt** [comment]
需要有moji的会员，然后在网页版发起一次请求，F12里可以看到token，只要不手动退出登录token一般不会掉

**Comment by raindrop213** [comment]
> 需要有moji的会员，然后在网页版发起一次请求，F12里可以看到token，只要不手动退出登录token一般不会掉

现在好像很难获取token了，能说说现在是怎么弄的吗
