### ISSUE TITLE
专有名词翻译可否添加一个文本搜索功能？

### ISSUE THREAD

**Issue by DDRRINON** [HIllya51/LunaTranslator#26]
文本一多找起来也不方便了，希望能上一个搜索功能方便搜索翻译文本

不过我还是希望可以按游戏来读取独立的文本，不然那些同名同姓翻译会撞在一起
![QQ截图20221028050750](https://user-images.githubusercontent.com/50374271/198399700-e8fc8f77-a241-4f57-82b6-dea6508d86b8.png)

**Comment by acteds** [comment]
翻译文本分为全局和某游戏独有,数据库加个字段根据游戏添加特征,全局为0,其他按特征来就很容易实现

**Comment by HIllya51** [comment]
已支持分游戏设置
搜索太麻烦了，要搜索直接打开useconfig/noundictconfig.json用文本编辑器来改吧，注意别把格式弄错了就行了。

**Comment by DDRRINON** [comment]
> 已支持分游戏设置 搜索太麻烦了，要搜索直接打开useconfig/noundictconfig.json用文本编辑器来改吧，注意别把格式弄错了就行了。

**Comment by HIllya51** [comment]
你这是开了过滤英文字母了吧？
访问不能太快啊，毕竟免费。

**Comment by HIllya51** [comment]
。。。我用你这个句子试了一下是没问题的

**Comment by DDRRINON** [comment]
但是在闪耀十字军上的确是这样子
