### ISSUE TITLE
文字显示效果没有之前好

### ISSUE THREAD

**Issue by blucca** [HIllya51/LunaTranslator#260]
原文：

更新前：<img src="https://user-images.githubusercontent.com/127029904/232470803-efe50ec1-fe37-44b9-bf13-c613b503eaf9.png"> 更新后：<img src="https://user-images.githubusercontent.com/127029904/232470839-ea68522e-6f17-45c2-9087-f03243579333.png">

<br>
字体设置界面：

更新前：<img src="https://user-images.githubusercontent.com/127029904/232470282-838fd25d-c0e0-4ade-8320-2f88ea3ab73f.png" width=30%> 更新后：<img src="https://user-images.githubusercontent.com/127029904/232471687-77c37f26-7c4f-46f5-b70f-8ecd17de780c.png" width=33%>

**Comment by HIllya51** [comment]
已回档
