### ISSUE TITLE
LunaTranslator窗口嚴重地放大

### ISSUE THREAD

**Issue by AyaRu97** [HIllya51/LunaTranslator#261]
版本 : LunaTranslator v2.12.7
主螢幕:3840x2160 x150%，副螢幕:1920x515 x100%
問題 : 當將LunaTranslator窗口移到其他顯示器時，會嚴重地放大。之前的版本並不會發生這問題。
影片 : https://streamable.com/vg6oaf

**Comment by HIllya51** [comment]
回调了
