### ISSUE TITLE
[暂存功能异常]预翻译与缓存

### ISSUE THREAD

**Issue by y49711** [HIllya51/LunaTranslator#262]
游戏文本即使translation_record内sqlite中已经有翻译的结果了
程序还是会优先使用API再重新翻译一次(会有0.5秒延迟,多吃一次流量) 
之前的版本是优先调用sqlite的结果 (一定sqlite优先 然后才调用api翻译)

现在如果要优先调用sqlite一定手动进入预翻译介面把sqlite手动选好
然后勾选预翻译功能才能优先使用sqlite内的翻译结果

不知道算不算BUG 希望可以修正一下 谢谢

**Comment by HIllya51** [comment]
开启使用持久化翻译缓存
