### ISSUE TITLE
一个关于字幕美观的问题。

### ISSUE THREAD

**Issue by lnusyaha** [HIllya51/LunaTranslator#263]
![IMG_20230421_195742](https://user-images.githubusercontent.com/116066807/233630083-8ac877b6-b4d4-451a-9e18-2b514fa05ff9.jpg)
正常清况
![IMG_20230421_195727](https://user-images.githubusercontent.com/116066807/233630129-07a32792-2ac9-4ff5-aa45-cd4cc8e53243.jpg)
使用Magpie10放大后的情况

不知道为什么截图拍不出差别，就用手机拍了。简单来说用Magpie10放大后字幕的阴影会变浅，导致在游戏看不清字。不知道怎么解决，请大佬指教。

**Comment by HIllya51** [comment]
不知道。这不属于我的问题。
