### ISSUE TITLE
高DPI缩放问题

### ISSUE THREAD

**Issue by PepperYouth** [HIllya51/LunaTranslator#265]
3200x2000分辨率，200%缩放，默认打开部分选项重叠，鼠标点到OCR会变成退出，如下：
![屏幕截图 2023-04-22 183833](https://user-images.githubusercontent.com/32806605/233779107-78af8ebc-cb6c-4df8-8bdf-214d569be359.png)
![屏幕截图 2023-04-22 183839](https://user-images.githubusercontent.com/32806605/233779113-33ade416-c58a-4839-b671-19214c17b735.png)

虽然能用鼠标调整窗口大小拉开，
![屏幕截图 2023-04-22 184532](https://user-images.githubusercontent.com/32806605/233779453-82d561cd-72fd-4377-9c3d-8b21e15559e6.png)
但是对于第一次使用的人来说确实有点小坑。

**Comment by PepperYouth** [comment]
以后版本能不能改改高DPI的默认窗口大小以完全显示？

**Comment by HIllya51** [comment]
改了一下 隐藏了几个没什么用的按钮 不会重叠了
