### ISSUE TITLE
希望增加azure openai接口

### ISSUE THREAD

**Issue by chunzhimoe** [HIllya51/LunaTranslator#266]
现在azure的openai接口已经出来了，而且很容易申请，所以想让作者大大适配一下。
# 方案
https://github.com/haibbo/cf-openai-azure-proxy
使用cloudflare进行反代azure的openai接口，然后反代域名作为请求的终结点，然后代码就不需要做改动，直接添加一个反代域名选项就行了。
我已经用这个反代项目测试了https://github.com/Yidadaa/ChatGPT-Next-Web
完全行的通.关于key和反代域名的话，我可以提供给大大，我已经加大大QQ了，可以直接发给你.

**Comment by chunzhimoe** [comment]
大佬用的openai库好像可以调用azure的api
https://learn.microsoft.com/zh-cn/azure/cognitive-services/openai/quickstart?tabs=command-line&pivots=programming-language-python

**Comment by chunzhimoe** [comment]
![image](https://user-images.githubusercontent.com/60135925/233782128-45273667-ba60-4ca8-a2ab-fa0fe29c64dd.png)
经过测试，最简单的办法是
api_base = os.environ.get("OPENAI_API_BASE", "反代域名")
直接替换掉就可以了

**Comment by HIllya51** [comment]
没看明白，怎么一会儿反代一会cloudfare一会azure。。。到底啥意思

**Comment by chunzhimoe** [comment]
打字的时候没想太多，意思表述可能不太明白


大多数 OpenAI 客户端不支持 Azure OpenAI Service，但Azure OpenAI Service的申请和绑卡都非常简单，并且还提供了免费的额度。此脚本使用免费的 Cloudflare Worker 作为代理，使得支持 OpenAI 的客户端可以直接使用 Azure OpenAI Service ，然后就可以反代域名作为请求的终结点，从而实现利用azure api接口进行翻译的功能。有了这个反代项目代码就不需要做改动，直接添加一个反代域名选项就行了。经过测试，最简单的办法是
api_base = os.environ.get("OPENAI_API_BASE", "反代域名")
直接替换掉就可以了https://github.com/HIllya51/LunaTranslator/blob/941c43d590c1f344842c33db793eaefc168acced/dependence/dependence_common/openai/__init__.py
第37行，其他不用做修改，可以正常识别。
然后我想作者大大，能在chatgpt翻译界面增加一个openai的api域名反代选项，让国内也可以用。

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/00afe28d89bc1cbcaff334ea71c6c9645bbb294e
https://github.com/HIllya51/LunaTranslator/releases/download/v2.12.9/Lunatranslator.zip
已加

**Comment by chunzhimoe** [comment]
感谢

**Comment by ikemenrourou** [comment]
@HIllya51 大大能否再支持下api2d，https://api2d.com/wiki/doc，这个几乎没有门槛很方便。

**Comment by HIllya51** [comment]
> @HIllya51 大大能否再支持下api2d，https://api2d.com/wiki/doc 这个几乎没有门槛很方便。

这不是官方的接口，看起来是私人部署，故不会去做支持。

**Comment by ikemenrourou** [comment]
> > @HIllya51 大大能否再支持下api2d，https://api2d.com/wiki/doc 这个几乎没有门槛很方便。
> 
> 这不是官方的接口，看起来是私人部署，故不会去做支持。

原来是这样，了解惹~
