### ISSUE TITLE
请问windows ocr怎么用的

### ISSUE THREAD

**Issue by zwj-lambda** [HIllya51/LunaTranslator#267]
开启后显示未安装该语言ocr模型，翻得日语，自带的有些汉字识别错误，想试试windows的，但是不成功

**Comment by HIllya51** [comment]
设置->时间和语言->语言->首选语言中添加语言日语

**Comment by zwj-lambda** [comment]
我有日语的
![image](https://user-images.githubusercontent.com/39145008/233840952-43998ab2-65fb-4447-87ba-bc21b4124532.png)

**Comment by HIllya51** [comment]
手写输入也要安装上
![批注 2023-04-23 214208](https://user-images.githubusercontent.com/101191390/233843244-a8b6b1a7-6ff4-4aaf-8c53-aa00175632cb.png)
