### ISSUE TITLE
请问下HOOK设置里面的问题

### ISSUE THREAD

**Issue by ddsongdd** [HIllya51/LunaTranslator#268]
![QQ图片20230424005858](https://user-images.githubusercontent.com/131602993/233854989-eb454a8f-030f-4293-86c6-2d7878262c91.png)
数字显示不出来对程序会有所影响吗？
![微信图片_20230424012442](https://user-images.githubusercontent.com/131602993/233855276-d88893dc-f40d-4ac9-857f-087b26d95a52.png)
![微信图片_20230424013052](https://user-images.githubusercontent.com/131602993/233855280-53917600-c56a-444a-b640-aa0e79751546.png)
文本抓取的也比较怪异，自动断句了直接去到最后一小段，还有些没弹出翻译字幕的

**Comment by HIllya51** [comment]
1、更换显示字体，不换也行，无所谓没影响
2、往下翻，换别的kirikiri开头的HOOK

**Comment by ddsongdd** [comment]
把kirikiri开头的都试过了，只有这个可以进行正常化翻译，但还是会有部分小段不翻（图一），大段自行断开的情况（图二）
![微信图片_20230424013052](https://user-images.githubusercontent.com/131602993/233856835-d513eb14-e2f6-473b-8a6d-de6c57ab3786.png)
![微信图片_20230424015810](https://user-images.githubusercontent.com/131602993/233856838-18bab038-34e0-4338-a6c2-0050d7fc8380.png)

**Comment by ddsongdd** [comment]
![微信图片_20230424015533](https://user-images.githubusercontent.com/131602993/233856966-ce86d255-1db7-4849-a3ed-c09ade7fe38c.png)
xiaoduan小段是这图 刚才卡了

**Comment by HIllya51** [comment]
把刷新延迟调高
