### ISSUE TITLE
文字显示不全

### ISSUE THREAD

**Issue by acteds** [HIllya51/LunaTranslator#27]
# 在Windows设置100%缩放后文字会显示不全  
[![2022-10-28-08-41-55.png](https://i.postimg.cc/j51nB9s8/2022-10-28-08-41-55.png)](https://postimg.cc/DJqzXx4s)
# 设置-系统-显示选项卡-缩放与布局项-设置100%,重新关闭程序后打开,文字显示不全  
[![2022-10-28-08-30-08.png](https://i.postimg.cc/4d06Bgrp/2022-10-28-08-30-08.png)](https://postimg.cc/1npV3LRz)  
[![2022-10-28-08-31-09.png](https://i.postimg.cc/g0NqLRsS/2022-10-28-08-31-09.png)](https://postimg.cc/GBTsZ4ZG)  
[![2022-10-28-08-33-25.png](https://i.postimg.cc/wj5kHnmd/2022-10-28-08-33-25.png)](https://postimg.cc/TKwbJ70k)

**Comment by HIllya51** [comment]
已修正
