### ISSUE TITLE
ChatGpt api

### ISSUE THREAD

**Issue by Hikura1** [HIllya51/LunaTranslator#270]
在chat上复制了api 但是翻译时显示错误
错误码：OpenAl-ChatGPT KeyError 'SECRET KEY
ChatGPT ValueError check hostname requires server hostname

**Comment by HIllya51** [comment]
放截图。

**Comment by Hikura1** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月30日(星期天) 中午1:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HIllya51/LunaTranslator] ChatGpt api (Issue #270)






放截图。

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by HIllya51** [comment]
？

**Comment by Hikura1** [comment]
发了呀……

---Original---
From: ***@***.***&gt;
Date: Sun, Apr 30, 2023 16:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HIllya51/LunaTranslator] ChatGpt api (Issue #270)




 
？

**Comment by Hikura1** [comment]
![44a175a842b3ae191aa4100e8c879d3](https://user-images.githubusercontent.com/132186119/235344726-285c0e93-b338-4473-93c2-7cc613380b66.png)

**Comment by HIllya51** [comment]
没开代理。

**Comment by Hikura1** [comment]
> 没开代理。

我是开着代理在chat上复制api的也没有关，不应该呀

**Comment by 17858911252** [comment]
> 没开代理。

我也是同样的问题，但我chatgptAPI能用，这个在线用不了，API免费用户每分钟限制3次太难受了

**Comment by HIllya51** [comment]
> 开了代理后ChatgptAPI能用了，但是Open ai的还是显示key错误，是我哪里设置错了吗？

删掉LunaTranslator/translators/openai.py
