### ISSUE TITLE
数据库明文？ 

### ISSUE THREAD

**Issue by lhj5426** [HIllya51/LunaTranslator#273]
以前的数据库里都是明文 可以直接手动修改

![image](https://user-images.githubusercontent.com/30548000/235702045-75520ec1-a015-4417-9616-e6ae62356f18.png)

现在的数据库 都不是明文了？
![image](https://user-images.githubusercontent.com/30548000/235702274-ff5f2ba7-904f-4840-bf38-5040e6005f6b.png)
e而且修改无效

本来还想 直接 GPT输出 大段之后 写到数据库里

![image](https://user-images.githubusercontent.com/30548000/235702493-194164a5-49d9-47aa-8f56-42b0a4ce6b2a.png)

但是现在 只能导出json 是明文 但是无法批量替换
只能一句一句的 复制粘贴？
![image](https://user-images.githubusercontent.com/30548000/235702660-7dfbf349-5052-4d14-adbc-7af6d62253ca.png)

可以让shuj数据库明文显示  方便修改吗？

https://github.com/HIllya51/LunaTranslator/issues/12

之前这样直接在数据里修改很方便 而且 现在用GPT输出大段 然后用数据库导入也很方便 

如果不是明文的话就无法这么操作

**Comment by HIllya51** [comment]
已改，可以兼容非json格式
