### ISSUE TITLE
关于假名的显示问的小细节

### ISSUE THREAD

**Issue by chienchen0405** [HIllya51/LunaTranslator#274]
你好你好，在使用假名的时候发现促音和拗音会和正常原文一样的字体大小显示出来，这里贴一张图片，想问问这个还能怎么在设置里面调整吗。想一下这个本身也非常难从ocr识别之后再识别到促音和拗音，不算会影响阅读原文的体验，很喜欢这个程序嘿嘿所以想多反馈一些，非常感谢。
![IMG_3257](https://user-images.githubusercontent.com/50726798/235863822-cc4750d6-08af-4711-b144-c35fb04af7b4.jpeg)

**Comment by HIllya51** [comment]
不能，别用OCR，用HOOK
