### ISSUE TITLE
语音合成AzureTTS没有反应

### ISSUE THREAD

**Issue by chienchen0405** [HIllya51/LunaTranslator#275]
你好你好，我先在语音合成中选择了AzureTTS,并且在翻译设置里面使用了Azure translator的API，翻译可以运行，但是没有出现朗读声音，我填了火山的API然后选火山的TTS是有朗读声音的。想问下这个TTS是和翻译那边填的API有关联的吗？ 之前我在Azure里面也创建了一个speech service的功能然后在一个chatgpt的客户端调用key可以使用Azure TTS，但是这里我不知道是我操作有问题吗？ 谢谢你

**Comment by HIllya51** [comment]
没关系。这个接口可能已经失效，用别的。
