### ISSUE TITLE
一个想法

### ISSUE THREAD

**Issue by 17858911252** [HIllya51/LunaTranslator#276]
是不是可以通过翻译器获取原文，让Chatgpt翻译完再通过预翻译导入，chatgptAPI免费账户有每分钟3次的使用限制，太不方便了，要付费也好麻烦

**Comment by 17858911252** [comment]
晚上试了下是可行，导出翻译记录后，让Chatgpt帮我写了一个提取文字和写入文字的代码，最后在把译文写进json文件里用人工翻译可以正常运行

**Comment by HIllya51** [comment]
？然后呢，你想说什么？
