### ISSUE TITLE
ChatGPT API无反应

### ISSUE THREAD

**Issue by umonaca** [HIllya51/LunaTranslator#277]
## 问题描述

尽管选中了`注册在线翻译`下的`ChatGPT`，并且填上了自己的API Key，但是翻译游戏时既不显示相应的翻译条目，也不报错。我不知道怎么输出日志调试，试了一下用Fiddler劫持网络，也只能看到别的引擎（比如DeepL API）的网络访问记录，完全没有访问过openai.com的迹象。也就是说LunaTranslator完全忽略了这个翻译引擎。

## 设置截图
![LunaTranslator_main_iq9ajhi5RG](https://user-images.githubusercontent.com/53662960/236108565-248b2415-323f-4f95-a677-757b14db4133.jpg)
![LunaTranslator_main_DT3JaAA6AD](https://user-images.githubusercontent.com/53662960/236108587-1d841e22-7985-4439-998b-eb8abf95c3b3.jpg)

## 排除问题
我的网络是物理上在海外的家用网络，用其它软件访问ChatGPT API是正常的。确定不是错误设置了代理或者API被封之类的问题。如果是这些问题，我应该能在Fiddler里面看见openai.com的访问记录，但是完全没有，只能看见别的网址。我觉得就是出于某种原因ChatGPT选项被忽略了。当然也不是Fiddler的问题，因为其它的比方说DeepL API都正常。

## 版本
v2.16.2 64位版，没有用新版覆盖旧版而是整个删掉重新解压缩的。

## 一点额外问题
像这种问题该如何看日志调试呢？

**Comment by HIllya51** [comment]
你这都截出来了还不懂吗。。。没设置代理啊

**Comment by HIllya51** [comment]
呃  那这我也不知道是什么问题😂我很多人都能用的啊应该没问题的 要不你就clone下来看看什么问题 我没做日志系统。。

**Comment by umonaca** [comment]
好吧，等周末我debug一下……Python好久没写了。

**Comment by umonaca** [comment]
截止目前测试的结论是：
- 这是一个`v2.15.1`到`v2.16.2`最近这四天之内引入的bug，所以没有人报。`v2.15.1`完全正常运行ChatGPT翻译，但昨天刚出的`v2.16.2`则完全跳过了ChatGPT引擎。
- `LunaTranslator\translator\chatgpt.py`在新版`v2.16.2`中完全没有被调用过的迹象，而上一个版本是正常调用的。
- 以上测试全部都是重新下载、解压到各自的空文件夹，应用的相同配置。
更详细的debug需要些时间。

**Comment by HIllya51** [comment]
已修正

**Comment by umonaca** [comment]
确实解决了，不过很好奇为什么问题出在`import asyncio`这一行上。。。
