### ISSUE TITLE
全局ID0似乎没效？

### ISSUE THREAD

**Issue by lnusyaha** [HIllya51/LunaTranslator#28]
![`$N9NG4_ZFN@ZF4K}{ZQQ(Q](https://user-images.githubusercontent.com/116066807/198682701-f0cbf3dd-7787-4b19-b025-ce698cafd1fb.png)
如图，专用名词没效果

**Comment by lnusyaha** [comment]
另外，对于专用名词特别多的人，可能需要一个搜索功能比较方便。

**Comment by HIllya51** [comment]
已修正。
