### ISSUE TITLE
关于有道在线翻译出问题

### ISSUE THREAD

**Issue by Chunshu123** [HIllya51/LunaTranslator#284]
最近一直用自己润色词和有道3、有道5搭配，但是今天突然有道3和有道5不行了，请问这是出了什么问题
![1683455370](https://user-images.githubusercontent.com/117711790/236672239-2bc42c98-636a-403b-957a-84a397d00d8b.png)

**Comment by HIllya51** [comment]
![批注 2023-05-07 183507](https://user-images.githubusercontent.com/101191390/236672519-3204407a-fa22-4d47-89ce-acffd8ca47a7.png)
试了一下没问题呀。是不是你不小心哪里设置错了？

**Comment by HIllya51** [comment]
或者是不是今天用的太频繁了被限制了？或者代理设置的问题之类的？

**Comment by Chunshu123** [comment]
今天不知道是不是我快进的问题，有道3快进快进着就突然显示这个了，然后就用有道5，结果有道5没快进正常用突然也不行了。我换了游戏，又把大大你今天更新的版本下载下来，也还是这样。
我看了一下后台的vpn，也以为是vpn的问题，关掉vpn也不行，难不成我的ip被有道拉黑名单了么

**Comment by Chunshu123** [comment]
可能还真是用的太频繁了被暂时拉黑了吗，这种大概得持续多久呀，有道3和5的在线翻译配合一些特定润色词真的比正常机翻好太多了，没了有道3和5就推不动游戏了

**Comment by HIllya51** [comment]
如果是快进着快进着突然这样，那99%是被限制了。。。
不过一般是暂时的，过上一会儿应该就可以了，具体多长时间不太确定。。。
为了防止这种情况，翻译设置中有一个翻译请求间隔的设置，可以稍微调一下防止C的太快被限制。

**Comment by Chunshu123** [comment]
好的，明白，那就明天再试试了，谢谢大大

**Comment by HIllya51** [comment]
不过我可以偷偷教你一个办法白嫖有道的api
https://github.com/CYZZ/MyAfred_flow/blob/1c1c88ef0f7e92ac8f77d27f6f4522a514c8a2cc/youdao_test.py
这里面APP_KEY和APP_SECRET是有效😊
一会儿删~

**Comment by Chunshu123** [comment]
c感谢！！！
