### ISSUE TITLE
重新翻译能不能加一个重新提交文本再翻译

### ISSUE THREAD

**Issue by 17858911252** [HIllya51/LunaTranslator#288]
翻译出了一个结果，点重新翻译后翻译内容也不会变，用chatgpt翻译时有时内容不让翻译，我就要把gpt翻译关了再重开一次，点那个重新翻译就只是出现内容不让翻译的一句话

**Comment by HIllya51** [comment]
![批注 2023-05-08 201658](https://user-images.githubusercontent.com/101191390/236821649-99860388-3ba8-4203-bc6e-07e00af6dd44.png)
