### ISSUE TITLE
存在英语省略问题

### ISSUE THREAD

**Issue by DDRRINON** [HIllya51/LunaTranslator#29]
如图，没有开英语省略功能，但是确实自动把英语无视了，我不知道其他游戏是不是会有和闪耀十字军一样的问题
![QQ截图20221029013138](https://user-images.githubusercontent.com/50374271/198698284-e473f6dd-f7ad-4058-b91e-fa8e1e30ac25.png)
![QQ截图20221029013205](https://user-images.githubusercontent.com/50374271/198698342-1b53907e-4cf4-45bc-b3e0-9776136c4ae9.png)

**Comment by HIllya51** [comment]
你看一下hook提取到的原文里面有没有英语。

**Comment by DDRRINON** [comment]
的确没有，那句英语被完全忽略了
![QQ截图20221029014626](https://user-images.githubusercontent.com/50374271/198699988-486e7378-609a-4f94-b7a3-bedaec7f880c.png)

**Comment by HIllya51** [comment]
链接发我

**Comment by HIllya51** [comment]
我没有找到可用的下载资源。

**Comment by DDRRINON** [comment]
magnet:?xt=urn:btih:0dfb8aec7715470f9b226cd6422727b4b8dbfab4

离线就能下了，我没找到有效的度盘资源

**Comment by HIllya51** [comment]
存档点发我，找不到你说的位置。
如果只是偶尔会出现就算了，感觉很难解决。。。

**Comment by DDRRINON** [comment]
不用特意翻找的，就开头op对话第二段

**Comment by HIllya51** [comment]
搞不定，ctrl了一会就开头有这么一句，影响不大

**Comment by HIllya51** [comment]
解决了，用特殊码HS932#18@4A7A00，然后开正则替换可解。当然感觉也没啥必要，就这么一两句。。。
