### ISSUE TITLE
Hook闪退

### ISSUE THREAD

**Issue by Betrayer-Zhu** [HIllya51/LunaTranslator#290]
Hook“选择游戏”面板中点击游戏进程后即闪退，是什么原因？

**Comment by HIllya51** [comment]
说清楚。

**Comment by Betrayer-Zhu** [comment]
> 说清楚吗能？

就是打开软件，通过Hook方式获取文本源时，不是会出现选择哪个游戏进程的面板吗，可以输入进程号或者直接下方点击选择那个面板。我选择好游戏之后点“OK”，接着就会闪退。同一款游戏，之前的版本是没有这个问题的，不过不知道从哪个版本开始的，因为中间有一段时间没更新了。

**Comment by Betrayer-Zhu** [comment]
> > 说清楚吗能？
> 
> 就是打开软件，通过Hook方式获取文本源时，不是会出现选择哪个游戏进程的面板吗，可以输入进程号或者直接下方点击选择那个面板。我选择好游戏之后点“OK”，接着就会闪退。同一款游戏，之前的版本是没有这个问题的，不过不知道从哪个版本开始的，因为中间有一段时间没更新了。

看了下之前应该是用的2.0.0或2.5.4，因为我用的有Hook内嵌选项

**Comment by HIllya51** [comment]
什么游戏？

**Comment by HIllya51** [comment]
最好给我个百度网盘资源 我试一下

**Comment by Betrayer-Zhu** [comment]
> 最好给我个百度网盘资源 我试一下

链接: https://pan.baidu.com/s/16LALVXAofBQBfvQjnLBHiQ?pwd=mmxp 提取码: mmxp

**Comment by HIllya51** [comment]
![批注 2023-05-09 200437](https://github.com/HIllya51/LunaTranslator/assets/101191390/61477cae-469f-42d9-affe-3c4b81a07225)
我这里没问题。。你可以试一下删掉userconfig再试试，可能存在不兼容的设置。或者一会儿我打包一个debug版本给你试一下

**Comment by Betrayer-Zhu** [comment]
> ![批注 2023-05-09 200437](https://user-images.githubusercontent.com/101191390/237091176-61477cae-469f-42d9-affe-3c4b81a07225.png) 我这里没问题。。你可以试一下删掉userconfig再试试，可能存在不兼容的设置。

我之前就试过了，没有效果。我能想到的唯一一点可能有关系的原因是我的系统非Unicode语言是日语，但是这款游戏需要这个设置，转区没有意义，也就没换回来。先这样吧，老版本也没差，我的使用频率也不高。不过你这翻译器我得赞一个，此类游戏就玩过一两款，但是翻译器接触过不少个，你这个综合来看做得最好。

**Comment by HIllya51** [comment]
我佛，这也太坑了。我也搞不懂，内容不变杀有的时候就不杀。
之后加个校验吧。
