### ISSUE TITLE
请问luna内嵌目前支持的引擎有哪些

### ISSUE THREAD

**Issue by Kaitokur** [HIllya51/LunaTranslator#291]
部分支持也行，有哪些可以告知吗

**Comment by HIllya51** [comment]
bgi debonosu horkeye lucifen nexton retouch system4 will age circus elf kirikiriz luna nitro rgss system43 willplus3 aoi cmvs escude lcse malie pal rio taskforce wolf aos cotopha fvp leaf minori pensil siglus unicorn artemis cs2 gxp lova mono qlie silkys waffle

**Comment by HIllya51** [comment]
https://github.com/Dangetsu/vnr/tree/master/Frameworks/Sakura/cpp/plugins/vnragent
拿这个改的
