### ISSUE TITLE
[功能请求] API 轮询

### ISSUE THREAD

**Issue by blucca** [HIllya51/LunaTranslator#293]
小牛API现在限制每天20万字符了，有些不够用。 #278 也是类似的需求。求支持一下…

**Comment by HIllya51** [comment]
怎么设计呢。。

**Comment by HIllya51** [comment]
报错关了不就行了，理解不能。

**Comment by HIllya51** [comment]
靠 我还以为是baidu xiaoniu baidu xiaodu 这样子呢 都弄完了

**Comment by HIllya51** [comment]
[xiaoniu.txt](https://github.com/HIllya51/LunaTranslator/files/11465862/xiaoniu.txt)
这样就行了
