### ISSUE TITLE
Mecab 假名标注错误

### ISSUE THREAD

**Issue by blucca** [HIllya51/LunaTranslator#294]
用的是  [UniDic v2023.3](https://clrd.ninjal.ac.jp/unidic_archive/2302/unidic-cwj-202302.zip)

![image](https://github.com/HIllya51/LunaTranslator/assets/127029904/30f1ef32-b4ae-48c2-9ad7-f1558afc4c3e)

**Comment by HIllya51** [comment]
已修

**Comment by HIllya51** [comment]
fugashi不支持新版
