### ISSUE TITLE
反馈两个bug

### ISSUE THREAD

**Issue by hzl2010** [HIllya51/LunaTranslator#295]
一个是去除重复字符的时候，如果调成自动字数模式的话，偶尔生效，偶尔去重不生效。
（但是手动输入去重次数的话，就没有这个问题）

另一个是去重后的文字偶尔会改变字符顺序。
![image](https://github.com/HIllya51/LunaTranslator/assets/65847388/75cfda2a-fecc-4e13-b38e-a5ae83a13c54)

原文：明日美明日美明日美明日美明日美「「「「「あああああはははははっっっっっ、、、、、
然后去重后就变成了“明美日”，但一般都是人名的字符顺序会改变，其他都是正常的，不知道是不是和符号有关？

**Comment by HIllya51** [comment]
没有bug，就是这样的。

**Comment by HAIZAKURA** [comment]
因为规则就是去重次数5次，后面对话没问题，前面"明"开始数5个，三次过后就剩下 明美日 了。
