### ISSUE TITLE
ocrspace好像有點問題(?)

### ISSUE THREAD

**Issue by a6070160701** [HIllya51/LunaTranslator#297]
如題
申請了free api key
可是使用時總是顯示
![image](https://github.com/HIllya51/LunaTranslator/assets/122324759/a07663df-770e-45a6-8510-c90eb495a05d)

這是我今天才申請的key
K88975345788957

**Comment by HIllya51** [comment]
![批注 2023-05-15 194843](https://github.com/HIllya51/LunaTranslator/assets/101191390/23fa0f73-587e-45d3-aa42-9764e267a7cf)
并没有问题

**Comment by HIllya51** [comment]
看了一下 目前用的是pro的接口，不支持free

**Comment by a6070160701** [comment]
> 晚点改一下

好的
感謝你的修改

**Comment by ACG-ZH** [comment]
![image](https://github.com/HIllya51/LunaTranslator/assets/113082765/904cd40e-d219-4cde-b0ae-3b356179b4dc)
如图，翻译出的条列太多，应该如何控制？太占屏幕了

**Comment by a6070160701** [comment]
> ![image](https://user-images.githubusercontent.com/113082765/238352038-904cd40e-d219-4cde-b0ae-3b356179b4dc.png) 如图，翻译出的条列太多，应该如何控制？太占屏幕了

![image](https://github.com/HIllya51/LunaTranslator/assets/122324759/a198fe74-00fc-4a60-b8f1-beaa7c8dbf4e)
只打勾你需要的翻譯源就好了

另外你的問題跟本主題應該毫無關係
下次可以自己另外開個issue
