### ISSUE TITLE
历史翻译的字体是否可以设置？

### ISSUE THREAD

**Issue by 2-3-5-7** [HIllya51/LunaTranslator#298]
历史翻译似乎没有使用 “文本字体” 中设置的字体，能否改成用这里的字体，或者可单独设置也行。

因为我会一直打开历史翻译，拖动到另一台显示器，看之前的 backlog，历史翻译的字体能设置的话看起来好看些。感谢作者！

**Comment by HIllya51** [comment]
![批注 2023-05-16 132730](https://github.com/HIllya51/LunaTranslator/assets/101191390/c960bdd8-e585-4170-a537-56295f1870c5)
