### ISSUE TITLE
voiceroid2用不了，点朗读也没反应，在线的tts都可以用。

### ISSUE THREAD

**Issue by asdtm1** [HIllya51/LunaTranslator#299]
是不是要在voiceroid2里做什么设置？可是路径里已经识别出结月的语音包了呀。求大佬救救。（最新版本，之前旧版本也是这样）

**Comment by HIllya51** [comment]
你用的voiceroid2是什么版本

**Comment by HIllya51** [comment]
另外，放截图。

**Comment by asdtm1** [comment]
版本就是翻译器里你给的链接。结月缘。

**Comment by asdtm1** [comment]
![image](https://github.com/HIllya51/LunaTranslator/assets/133833812/a78a1cf3-895e-4d41-8b0e-a48c8a855339)

**Comment by HIllya51** [comment]
VoiceroidEditor能运行吗？

**Comment by asdtm1** [comment]
能运行

**Comment by HIllya51** [comment]
那我也不知道了
