### ISSUE TITLE
請問會考慮增加全域快捷鍵功能嗎?

### ISSUE THREAD

**Issue by AyaRu97** [HIllya51/LunaTranslator#30]
先感謝大佬，用過不少翻譯器，這個對我來說最好用 ! 更新又快
然後請問會考慮增加全域快捷鍵功能(自定義)嗎 ? 
因為有些遊戲當鼠標點擊了其他視窗，會自動停止或自動最小化...
例如這樣
![image](https://user-images.githubusercontent.com/115739200/198826485-9df17cfe-23f0-436e-8467-790d5019d13d.png)

**Comment by HIllya51** [comment]
可以

**Comment by HIllya51** [comment]
已更新
