### ISSUE TITLE
[Feature Request] Add an option to adjust font size of title of the tab widgets

### ISSUE THREAD

**Issue by davuses** [HIllya51/LunaTranslator#301]
Hi 恍兮惚兮, first off, thank you for this handy software, it really helps a lot when I was playing through a few untranslated VNs in the past weeks.

For the moment, the font size change in the interface settings doesn't seem to get applied by the title of the tab widgets:

![image](https://github.com/HIllya51/LunaTranslator/assets/54793121/6f3745a6-0b4a-45d8-a334-6fca4ffc227e)
![image](https://github.com/HIllya51/LunaTranslator/assets/54793121/7151d5d7-2ef8-4ca6-bf31-1d3a5235ab99)

You can see the titles on the left side didn't pick up the font change while the text within the tab widget became larger just as expected. I suppose the font size settings for those two intend to work separately, so could you maybe add an option to adjust the font size for the title as well?

Once again, thanks for everything you've done and continue to do with this fantastic program!

**Comment by HIllya51** [comment]
Due to some design flaws, this is difficult to implement. Moreover, allowing font adjustments is only to prevent some languages from being too long to display completely, so there is no need to modify the title font.

**Comment by davuses** [comment]
> Due to some design flaws, this is difficult to implement. Moreover, allowing font adjustments is only to prevent some languages from being too long to display completely, so there is no need to modify the title font.

Thanks for your response, larger title size could be easier for me to read, It seems the tab title font size is configured at [this part of the code](https://github.com/HIllya51/LunaTranslator/blob/5c0988e9620d7e494c324bfdaf7d817be9af74fc/LunaTranslator/LunaTranslator/gui/settin.py#L206), so I changed the font size and built another program for myself.
