### ISSUE TITLE
[Bug report] Issue with resizing setup window horizontally

### ISSUE THREAD

**Issue by davuses** [HIllya51/LunaTranslator#302]
I've encountered this weird behavior when trying to resize the setup window horizontally. I can drag the edge on right side to make the window wider, but after that I'm not able to drag it back and reduce the width.

**Comment by HIllya51** [comment]
I haven't encountered this problem before. If you encounter it, please attach a screen recording video or gif to show it.

**Comment by HIllya51** [comment]
Please confirm that the version of your program is the latest. I remember this is a resolved issue.

**Comment by HIllya51** [comment]
Please confirm that the version of your program is the latest. I remember this is a resolved issue.


If you still have this problem, please attach a screen recording video or gif to show it.
