### ISSUE TITLE
正则表达式的一些问题

### ISSUE THREAD

**Issue by hhyacg** [HIllya51/LunaTranslator#303]
![image](https://github.com/HIllya51/LunaTranslator/assets/40420771/079c83c0-15c7-4ce1-909a-0ac21dc879fc)
如图，这边的正则表达式怎么做到##去除"『"或”「"之前的所有文本”##和##去除"』"或”」"之后的所有文本##呢？这个.*(?=[「|『]) 正则表达式好像不通用。

人物名称「xxxxxxxxxxxxxxx」人物名称，人物名称的位置看游戏，有些游戏会把人物名称放在对话文本前，有些会放在对话文本后面，括号里一般是对话文本位置。上面的正则表达式会有误伤，比如有时对话文本里面会有xxxx「xxxx『1234』xxxx」xxxx，为了避免误伤『1234』文本，只需用把这俩括号「                    」的前后的文本去除就行。

**Comment by HIllya51** [comment]
？？？发错地方了吗？

**Comment by hhyacg** [comment]
> ？？？发错地方了？

没有，我想知道luna翻译器怎么使用正则表达式实现上述功能

**Comment by HIllya51** [comment]
![批注 2023-05-22 012639](https://github.com/HIllya51/LunaTranslator/assets/101191390/6daa6354-45b8-411f-b77b-b8600aa42edd)

**Comment by HIllya51** [comment]
![批注 2023-05-22 012819](https://github.com/HIllya51/LunaTranslator/assets/101191390/d7cdf65a-f0f8-4060-a2b8-7593387e38e5)

**Comment by hhyacg** [comment]
![9WN53GDSO@AA82Y@EX R2 P](https://github.com/HIllya51/LunaTranslator/assets/40420771/3d1cdc5d-a000-49d2-875e-45f03e9814e6)
ok了，感谢
