### ISSUE TITLE
[Bug Report] 打开游戏失去焦点窗口隐藏时，无法正常关闭游戏

### ISSUE THREAD

**Issue by luojunyuan** [HIllya51/LunaTranslator#305]
关闭弹窗不知为什么会和游戏窗口争夺。

https://github.com/HIllya51/LunaTranslator/assets/28323948/31bbe7ad-6b85-4278-b352-427e27ea9342

**Comment by HIllya51** [comment]
从最小化恢复后会对游戏窗口SetForegroudWindow，游戏窗口的hwnd和MessageBox的hwnd争夺前台窗口导致的。已修正。
