### ISSUE TITLE
Chat gpt

### ISSUE THREAD

**Issue by toxinios** [HIllya51/LunaTranslator#306]
Is it possible to implement a translation function via gpt, using automatic text input into the browser and then displaying it in the program window, to bypass the api key in this way?

**Comment by HIllya51** [comment]
It can be achieved by manipulating the browser through selenium, but I do not want to do so.

**Comment by allebar** [comment]
> It can be achieved by manipulating the browser through selenium, but I do not want to do so.

Can you please make instructions for achieving this? I just can't buy api in my country.

**Comment by HIllya51** [comment]
> > It can be achieved by manipulating the browser through selenium, but I do not want to do so.
> 
> Can you please make instructions for achieving this? I just can't buy api in my country.

You can refer to https://www.bilibili.com/read/cv20610733

**Comment by timeance** [comment]
In fact, you can also access it through reverse API. However, I do not recommend obtaining translation services in ways other than using the API. This method is not only unstable, but also violates the Terms of Service (ToS), which could lead to your account being banned by OpenAI.

>https://github.com/acheong08/ChatGPT

**Comment by HIllya51** [comment]
I have implemented automatic translation on a free third-party platform at Chatgpt, but it is not very stable. If you want to implement it, you can refer to it.

https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/LunaTranslator/translator/poe_dev.py
