### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by XIAOMNBVCXZ** [HIllya51/LunaTranslator#309]
能不能添加UTF-16的编码页啊，好多都需要这种才能正常显示文本

**Comment by HIllya51** [comment]
UTF16是没有代码页的，W/Q就是UTF16的内容。

**Comment by XIAOMNBVCXZ** [comment]
dead days

**Comment by HIllya51** [comment]
测了，这作没任何问题，你哪来的乱码？截图看一下？

**Comment by XIAOMNBVCXZ** [comment]
![_BE%}I~2IS$ F~65@3892QX](https://github.com/HIllya51/LunaTranslator/assets/134617933/d3193a19-8a59-4275-b56c-e1fcd1c86418)

**Comment by XIAOMNBVCXZ** [comment]
好的，懂了
