### ISSUE TITLE
问一下专有名词翻译设置中的游戏 ID 是？

### ISSUE THREAD

**Issue by 2-3-5-7** [HIllya51/LunaTranslator#31]
问一下专有名词翻译设置中的游戏 ID 是什么？

0 是全局生效，如果想只对某个游戏生效，游戏 ID 填游戏程序的 MD5 还是 已保存游戏中的序号呢？

![1](https://user-images.githubusercontent.com/79762374/198833085-c5fba8ef-56c6-4a6d-a9d4-02d57a8087e5.png)
![2](https://user-images.githubusercontent.com/79762374/198833089-3a5bd04c-ff8a-44c6-b87a-2c1d408d23c3.png)

**Comment by HIllya51** [comment]
md5

**Comment by 2-3-5-7** [comment]
好的
