### ISSUE TITLE
调用 VoiceVox 的语音名称和实际语音对不上

### ISSUE THREAD

**Issue by prts64** [HIllya51/LunaTranslator#310]
目前版本 2.20.1 ，VoiceVox 版本 0.14.6，
在 VoiceVox 的语音名称和实际语音对不上，
例如选 No.7 才是 冥鳴ひまり，
最后两个 猫使アル 和 猫使ビイ 对应的是 WhileCUL 的前两个风格的发音。

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/issues/145
参见这个。列表里往下找一下对应的就行了。
