### ISSUE TITLE
通过"打开保存的游戏"运行游戏时出现无法自动hook到游戏的情况

### ISSUE THREAD

**Issue by naclgeorge** [HIllya51/LunaTranslator#311]
上个月是正常的，通过"打开保存的游戏"打开游戏并读取存档后，会自动hook然后显示出原文和翻译。但是这个月突然不灵了，打开游戏需要手动hook才行。之前也出现过这个问题，然后某一天突然就正常了，现在又出现。
不知道是我哪里操作不对，还是bug
期间软件未更新过，设定也未更改过，游戏也没换。设定里能看到特殊码是存在的

**Comment by HIllya51** [comment]
什么游戏，以及userconfig打包发给我看一下。

**Comment by naclgeorge** [comment]
[userconfig.zip](https://github.com/HIllya51/LunaTranslator/files/11576874/userconfig.zip)
游戏是華は短し、踊れよ乙女

**Comment by HIllya51** [comment]
你把自定义的特殊码去掉，内置的本来就能提取了，插码把内置的顶掉了。

**Comment by naclgeorge** [comment]
我并没有手动添加过特殊码，都不知道是怎么来的，是手动选择文本时候来的么。现在已经在游戏设置里删掉了，好像没用。还是说要从其他什么地方删

**Comment by HIllya51** [comment]
你用这个特殊码：HWN-20@A22E:AdvHD.exe

**Comment by naclgeorge** [comment]
试过了，确实是游戏的问题，其他游戏都正常。换了你给的特殊码以后这个游戏也可以了。
谢谢，问题解决
