### ISSUE TITLE
快捷键和工具栏配合的问题

### ISSUE THREAD

**Issue by 1789984734** [HIllya51/LunaTranslator#313]
在不锁定工具栏的情况下（此时工具栏处于隐藏状态），在使用过任意快捷键后工具栏就会变成类似锁定状态，必须鼠标回到软件上再移除软件界面才能重新隐藏工具栏。

希望可以做到使用完快捷键后不会改变工具栏的状态或者过几秒后自动隐藏。

谢谢。

**Comment by HIllya51** [comment]
已改
