### ISSUE TITLE
develop該如何使用

### ISSUE THREAD

**Issue by bernie84** [HIllya51/LunaTranslator#314]
您好，想請教新增的develop功能該如何使用呢？
不太知道chrome路徑該怎麼獲取。

謝謝您的開發與付出。

**Comment by EXBJAN** [comment]
首先你应该安装一个chrome浏览器，然后桌面找到其快捷图标，鼠标右键>属性>目标，复制路径，然后粘贴保存即可。

**Comment by bernie84** [comment]
想再請教將chrome路徑貼上去之後，並已勾選翻譯器，卻無翻譯結果。
請問還有哪些需要做的嗎。
抱歉 不太懂develop的運作。
感謝您的回覆

**Comment by HIllya51** [comment]
不是，选路径都不会吗，这让我该怎么回你啊。。。

**Comment by HIllya51** [comment]
还是用普通的翻译吧，develop这个东西坑和bug比较多，不是很建议完全不懂的人用。

**Comment by bernie84** [comment]
好的，感謝您的回覆
