### ISSUE TITLE
话说现在各种api不都有字数限制吗，要不加一个页面显示在前台表示当日和当月你这个软件使用的字符数

### ISSUE THREAD

**Issue by wycstc353** [HIllya51/LunaTranslator#316]
话说现在各种api不都有字数限制吗，要不加一个页面显示在前台表示当日和当月你这个软件使用的字符数

**Comment by HIllya51** [comment]
到限制不就自动停了吗 搞这个这有什么意义吗

**Comment by wycstc353** [comment]
> 到限制不就自动停了吗 搞这个这有什么意义吗

 我api没超过不知道是不是自动停，我主要怕是和电信一样的，怕出现哪个api搞个欠费模式，超了还让你翻的情况，这样的话，这功能就很有用了

**Comment by HIllya51** [comment]
那我还得去查每个api的限额，麻烦的要死。而且要是人家花钱买了额度呢，那岂不是还有额度却用不了，那不是更恶心。况且目前所有的api都是到额度就停，考虑这个没有意义。

**Comment by wycstc353** [comment]
> 那我还得去查每个api的限额，麻烦的要死。而且要是人家花钱买了额度呢，那岂不是还有额度却用不了，那不是更恶心。况且目前所有的api都是到额度就停，考虑这个没有意义。

额，虽然已经知道直接停了之后感觉没意义了，但你理解错我的意思了，我的意思就是弄一个窗口在左边，只是显示一下当天和当月已经使用的字符数，没让你停止发送，只是显示一下
