### ISSUE TITLE
请问如何增加chatgpt第三方接口的延迟时间，每次响应就差不到1秒但依然报超时

### ISSUE THREAD

**Issue by CatCars** [HIllya51/LunaTranslator#317]
![1](https://github.com/HIllya51/LunaTranslator/assets/44657929/b83236d3-9cb2-4654-8c08-2a2f845f42d2)
![2](https://github.com/HIllya51/LunaTranslator/assets/44657929/50583d6c-92e5-4d29-84af-9fb371dc597e)
每次句子刚显示一大半，就报请求超时。请问如何才能延长超时时间。
这是在用Claude_slack,代替chatgpt3.5，因为Claude_slack响应要稍微慢一点，所以一直报请求超时但是我点重新翻译它并不会重新请求而是直接显示结果，盲猜其实已经获取到了完整数据。
![3](https://github.com/HIllya51/LunaTranslator/assets/44657929/3bd47dc1-d042-4241-8aef-8621acc7a478)

**Comment by CatCars** [comment]
红的有道，懒得gpt3.5，棕色Claude_slack

**Comment by HIllya51** [comment]
![批注 2023-06-04 124601](https://github.com/HIllya51/LunaTranslator/assets/101191390/89aaf124-232e-4c36-99c4-6b9106053a7b)

**Comment by HIllya51** [comment]
全改了 之后不再timeout了
