### ISSUE TITLE
建议：文字添加阴影

### ISSUE THREAD

**Issue by Ptilopsis01** [HIllya51/LunaTranslator#32]
如题，希望翻译内容可添加阴影（就是类似vnr的那种），可以比较好的把字幕内容和游戏画面区分开，描边字体虽然效果不错但体感还是有些累眼睛

**Comment by HIllya51** [comment]
截个图看一下。

**Comment by Ptilopsis01** [comment]
> 截个图看一下。

是说VNR吗？像这样：
<img width="1280" alt="屏幕截图_20221031_230832" src="https://user-images.githubusercontent.com/93318731/199042508-3cb3c263-b6aa-43ce-954a-ffbb4fd459bf.png">

**Comment by Ptilopsis01** [comment]
> https://p.inari.site/guest/22-11/01/635ff9c5b6a75.jpg
> 
> 可以实现出来，但是不知道怎么和既有功能兼容。。。所以可能会需要一段时间

好哎，非常感谢，大佬加油
