### ISSUE TITLE
希望增加一个新的文本处理规则，用于正常处理【人名 「对话」】的文本

### ISSUE THREAD

**Issue by EXBJAN** [HIllya51/LunaTranslator#326]
如图所示：（这类文本并不算少见）
![未标题-1](https://github.com/HIllya51/LunaTranslator/assets/117036098/00ed4ba3-ecbf-493c-903f-ba9b43db3967)
这类情况一般是对话，往往遇到这种【重复的人名+重复的带有“「」”的文本时】由于“人名”部分与“「对话」”部分文本结构不一致，导致处理不了。但只要删除了“「”前的文本就能正常处理了。

**Comment by HIllya51** [comment]
这个用正则表达式就行。不过好像确实挺常见的，我回头加一下吧。

**Comment by EXBJAN** [comment]
好的，辛苦了
