### ISSUE TITLE
可能有内存泄漏？

### ISSUE THREAD

**Issue by blucca** [HIllya51/LunaTranslator#327]
运行几个小时后占用500M内存了
![image](https://github.com/HIllya51/LunaTranslator/assets/127029904/464881bb-1f4b-4e2e-81d9-013b0de62ce7)

**Comment by HIllya51** [comment]
怎么复现？

**Comment by luojunyuan** [comment]
打开后启动了哪些界面，界面打开后占用多少。用了哪些功能？如果你有在使用mecab读入字典那几百mb完全是正常现象。
