### ISSUE TITLE
fix deepl browser

### ISSUE THREAD

**Issue by KirpichKrasniy** [HIllya51/LunaTranslator#330]
Hello, it's me again. Please change the method of entering text in deepl translator in develop mode via the format link:

https://www.deepl.com/ru/translator#ru/en/TEXT (the page will be refreshed every time)

at the moment this translation mode does not work in the background if the window is inactive. you can also try to perform this operation in chromedriver. (the browser can work in the background)

the only problem is that you have to clear the link of characters:

%
/
\#
|

I will also update the Russian translation later and send you the translation

Thank you for your hard work!

**Comment by KirpichKrasniy** [comment]
Sometimes in the background it is stable. I don't quite understand what it depends on...

**Comment by KirpichKrasniy** [comment]
I don't know if you were asked for this, but is it possible to include a voiceover just for the translation and not for the original text?

**Comment by KirpichKrasniy** [comment]
Also... maybe I don't see it, but is it possible to copy the translated text to the clipboard?

**Comment by HIllya51** [comment]
develop translators is not stable translators... it has many bug, I also don't know how to solve...
you can open translation history window to copy the translated text

**Comment by KirpichKrasniy** [comment]
I think it is possible to run chromedriver on pithon and work with it. I will try to write the translator code, because I already have an example, only in autohotkey language. deepl translator works fine. I will try to adapt it to pithon.
![image](https://github.com/HIllya51/LunaTranslator/assets/109726461/1d5c384c-650b-4416-b035-91b1fd5e91f6)
It looks crooked, but it works great

**Comment by HIllya51** [comment]
I won't use chromedriver because usually it must strictly match the browser version. And for edge and chrome, it cannot be generalized. The current method does not need to consider these issues, only a browser is needed, and there is no need to consider version issues. Moreover, using chromedriver will reference many additional libraries, and I hope to minimize external dependencies as much as possible.

**Comment by KirpichKrasniy** [comment]
I get it. Then I think we should start by clearing the link of characters that break the link % / | \#

**Comment by KirpichKrasniy** [comment]
Perhaps you should keep only one browser page open in the background, so that other processes in the browser do not interrupt

**Comment by HIllya51** [comment]
...didn't understand

**Comment by KirpichKrasniy** [comment]
https://www.deepl.com/ru/translator-mobile#en/ru/hello all#guys/aboba|aaaa

I don't understand what you don't understand. 

These characters make the link not work: # / | %

You need to get rid of them when you enter a link with text in the search bar

**Comment by HIllya51** [comment]
I don't think this seems to have much meaning, such a sentence doesn't seem like a meaningful sentence, so I don't intend to waste many energy on this. Of course, if you are willing to solve this problem, I would welcome it.

**Comment by KirpichKrasniy** [comment]
I have one more question. Can I make it so that certain words are not translated in the text? 
For example, I have a line:

«Nicholas said he needed a block of red stone»

I want it to be in translation:

«Nicholas сказал, что ему нужен block of red stone»

**Comment by KirpichKrasniy** [comment]
> I don't think this seems to have much meaning, such a sentence doesn't seem like a meaningful sentence, so I don't intend to waste many energy on this. Of course, if you are willing to solve this problem, I would welcome it.

I gave this as an example. Sometimes similar symbols may appear in the text. I think you could add a regex to get rid of them specifically for the deepl translator, which stops working or trims sentences when it encounters these characters

**Comment by HIllya51** [comment]
> I have one more question. Can I make it so that certain words are not translated in the text? For example, I have a line:
> 
> «Nicholas said he needed a block of red stone»
> 
> I want it to be in translation:
> 
> «Nicholas сказал, что ему нужен block of red stone»

![批注 2023-06-11 141015](https://github.com/HIllya51/LunaTranslator/assets/101191390/aa9e92d3-1f20-41aa-bf96-37174b723f28)

**Comment by KirpichKrasniy** [comment]
> ![批注 2023-06-11 141015](https://user-images.githubusercontent.com/101191390/244916903-aa9e92d3-1f20-41aa-bf96-37174b723f28.png)

can you make it with regex support?

**Comment by HIllya51** [comment]
I don't how to implement it with regex...it's too difficult, and usually not useful.

**Comment by KirpichKrasniy** [comment]
if it's complicated, then don't. it would help me in my tasks, but I'll make a separate macro for myself. thanks!
