### ISSUE TITLE
关于启动游戏自动翻译的问题

### ISSUE THREAD

**Issue by SakiBiAnNya** [HIllya51/LunaTranslator#331]
好像有些游戏是可以在翻译器里启动了，然后自动hook到文本地址进行翻译，但有些游戏则不行，每次启动都得手动hook一下，这个问题有办法解决吗？

**Comment by HIllya51** [comment]
改特殊码，后面加个N。例如HS-4@1234:haha.exe，改成HSN-4@1234:haha.exe

**Comment by hhyacg** [comment]
> 改特殊码，后面加个N。例如HS-4@1234:haha.exe，改成HSN-4@1234:haha.exe

是直接hook到的，不用特殊码的，也是复制下来文本地址自己改为特殊码形式吗？

**Comment by hhyacg** [comment]
> > 改特殊码，后面加个N。例如HS-4@1234:haha.exe，改成HSN-4@1234:haha.exe
> 
> 是直接hook到的，不用特殊码的，也是复制下来文本地址自己改为特殊码形式吗？

我自己改了还是不行，HW8:4@A1C0:ハジラブ.exe为HWN8:4@A1C0:ハジラブ.exe，还是不能重启游戏再打开自动hook并翻译（有些游戏在翻译器游戏管理的详情界面已经添加有了特殊码，但是开启游戏并不会同时注入特殊码）

**Comment by HIllya51** [comment]
盲猜插的太快顶掉了，我加个延迟。

**Comment by hhyacg** [comment]
> 盲猜插的太快顶掉了，我加个延迟。

延迟插入是插入了，但是选择文本仍然不会自动选中到那个hook，主要问题是，不会记住上一次"选中"的文本地址
![TG3G)AGVI){P~R$1 6L2$73](https://github.com/HIllya51/LunaTranslator/assets/40420771/3889c130-5e2c-4b06-a4fa-7b00eaf8e8f5)

**Comment by HIllya51** [comment]
HQN-4@A30E0:ハジラブ.exe

**Comment by hhyacg** [comment]
> HQN-4@A30E0:ハジラブ.exe

还是不行，这个游戏添不添加特殊码都能hook到正确的文本，主要是指其他能正常hook文本的游戏，启动时也会不自动选中上次启动后选中的hook地址

**Comment by HIllya51** [comment]
这个和游戏引擎有关。

**Comment by hhyacg** [comment]
> 这个和游戏引擎有关系。

能不能做一个强制记住上次启动已保存的hook并注入、并自动勾选上的功能？提示改一下：“由于游戏引擎不同，文本hook地址也可能会随之改变，按实际hook到的正常文本来参考”

如果觉得太麻烦就无视吧

**Comment by HIllya51** [comment]
我不知道你那里什么情况，反正我这里测试这样是可以开始翻译的。
