### ISSUE TITLE
Speech synthesizer for translation results

### ISSUE THREAD

**Issue by geo7027** [HIllya51/LunaTranslator#335]
Hi! Thank you for the LunaTranslator, it's awesome work!
Help me with setting up the speech synthesizer, please. How can I set it up to read text translation? Is this feature implemented? Right now, the speech synthesizer only voices the original text. If there is no such feature, can you add that? Thank you!

**Comment by HIllya51** [comment]
already supported

**Comment by geo7027** [comment]
Can you tell me how to configure this feature? In my situation, the speech synthesiser only reads the original text, not the translation.

**Comment by HIllya51** [comment]
![批注 2023-06-11 064249](https://github.com/HIllya51/LunaTranslator/assets/101191390/bc6b944d-ad8e-48f9-8cbe-65427478d67f)

**Comment by geo7027** [comment]
![lt-2](https://github.com/HIllya51/LunaTranslator/assets/136200501/126d70ee-8d83-4387-898e-4824469bac3a)

**Comment by HIllya51** [comment]
re download it

**Comment by geo7027** [comment]
Unbelievable! Its works great, thank you very much!
You need to expand your donation options so that users from Russia can support your work (qiwi, webmony, boosty etc).
