### ISSUE TITLE
历史文本显示

### ISSUE THREAD

**Issue by 102757017** [HIllya51/LunaTranslator#336]
目前的历史文本里面只显示译文，能否同时显示原文与译文呢。这个工具用来推英文gal学英语非常好，但是有一些游戏过场动画的字幕很快，还没看明白就下一句了，所以需要回看之前的文本。
另外我实时翻译的结果是正常的，为什么我的历史文本里面显示的都是乱码，难道是因为翻译的是英文？

**Comment by HIllya51** [comment]
？本来就有原文

**Comment by 102757017** [comment]
我的文本历史记录如下图所示，看不到原文，很多空白项，而且有乱码。但是可以看到下方的翻译条显示内容是正常的。
我使用的是读取剪切板文本的方式翻译，我猜测可能与提取的文本有关系，我剪切板提取的文本如下所示，没有过滤掉前后缀，但是LunaTranslator显示出来的内容是没有前后缀的，可能是自动帮我过滤了，是历史记录里面没有过滤前后缀导致的异常吗？
<FONT size='33' face='$DialogueFont' color='#ffffffff'>You did read the chapters, right?</font> 
<FONT size='33' face='$DialogueFont' color='#ffffffff'>Your silence is deafening.</font> 
<FONT size='33' face='$DialogueFont' color='#ffffffff'>If this were a photo, I'd call it a still life.</font> 
<FONT size='33' face='$DialogueFont' color='#ffffffff'>Anybody? … This does not bode well.</font> 
<FONT size='33' face='$DialogueFont' color='#ffffffff'>Just jump right in with an answer.</font> 
<FONT size='33' face='$DialogueFont' color='#ffffffff'>This was in the chapters you read.</font> 

![image](https://github.com/HIllya51/LunaTranslator/assets/30728579/3fcfa77c-6046-41a7-bb0e-3a1dfd975feb)

**Comment by HIllya51** [comment]
什么鬼，怎么字都不一样大

**Comment by 102757017** [comment]
是不是LunaTranslator把下面的这个文本前后缀当成代码了，而不是字符串，所以导致历史记录里面显示异常。
’‘’<FONT size='33' face='$DialogueFont' color='#ffffffff'>                           </font>‘’‘
