### ISSUE TITLE
关于选取OCR范围与多显示器的问题

### ISSUE THREAD

**Issue by Boxkun** [HIllya51/LunaTranslator#340]
在使用多于一台显示器时，选取OCR范围只会在当前设定的主显示器上显示可选范围，如下图左侧

![Snipaste_2023-06-15_16-36-05](https://github.com/HIllya51/LunaTranslator/assets/50022810/b53c1ff5-54c7-4719-a05d-34174ce508a1)

**Comment by HIllya51** [comment]
已修正
