### ISSUE TITLE
竖行文字识别

### ISSUE THREAD

**Issue by ikazoa** [HIllya51/LunaTranslator#344]
能否对竖行文字识别功能附加“从左至右/从右至左”的识别选项呢？竖行文字识别通常应用于日文，而日本的行文习惯是从右至左。

**Comment by HIllya51** [comment]
现在就是从右向左的。这个问题早已考虑过了。
https://github.com/HIllya51/LunaTranslator/issues/154

**Comment by ikazoa** [comment]
例如百度ocr，返回参数可以选择有位置信息的版本
通用文字识别（标准含位置版）：https://ai.baidu.com/ai-doc/OCR/vk3h7y58v
如果太复杂的话就算了吧，应该可以从其他软件找到类似的功能

**Comment by HIllya51** [comment]
这个不难。但是死妈百度把我手机号封了，我没兴趣弄了。
如果你有需要的话可以修改ocrengines/baiduocr.py和baiduocr_accurate.py，并不复杂。

**Comment by HIllya51** [comment]
已支持。

**Comment by ikazoa** [comment]
谢谢

**Comment by l758593904** [comment]
> 已支持。

请问调用百度接口 识别结果是从左到右 这种有办法解决吗 已更新最新版

**Comment by HIllya51** [comment]
> > 已支持。
> 
> 请问调用百度接口 识别结果是从左到右 这种有办法解决吗 已更新最新版

使用含位置版接口。

**Comment by l758593904** [comment]
> > > 已支持。
> > 
> > 
> > 请问调用百度接口 识别结果是从左到右 这种有办法解决吗 已更新最新版
> 
> 使用含位置版接口。

非常感谢！我还以为位置是地理位置所以未勾选
