### ISSUE TITLE
功能请求：快进键

### ISSUE THREAD

**Issue by SakiBiAnNya** [HIllya51/LunaTranslator#348]
未来能给窗口的功能栏增加一个快进键吗？（Ctrl键或者回车键，都是触发长按）有些游戏不能设定未读文本快进，串流时有点麻烦（小私心）

**Comment by HIllya51** [comment]
啥意思，没明白。。。

**Comment by SakiBiAnNya** [comment]
> 啥意思，没明白。。。

就是当初还以为这个自动翻译键是强制快进键。。。结果翻了一下设置没有这个功能，可以的话希望在这边加一个强制快进键
![7J~SDS7(E4 RB18TV${F{0](https://github.com/HIllya51/LunaTranslator/assets/40420771/0110fc5c-6741-4e49-b2d3-7bbba789964d)

**Comment by HIllya51** [comment]
我的意思是你说的这个功能是啥要干什么？

**Comment by SakiBiAnNya** [comment]
> 我的意思是你说的这个功能是啥要干什么？

上面说了啊，有些游戏不能设定未读文本快进，只能ctrl强制快进，串流时有点麻烦（无键盘状态）

**Comment by HIllya51** [comment]
还是没懂。我猜一下，你是这个意思：让程序模拟键盘按键按下ctrl？

**Comment by SakiBiAnNya** [comment]
> 

是的，而且有些游戏还是回车键快进的

**Comment by HIllya51** [comment]
已加

**Comment by SakiBiAnNya** [comment]
> 已加

感谢
