### ISSUE TITLE
初めての彼女 二次运行提取不到任何文本

### ISSUE THREAD

**Issue by EXBJAN** [HIllya51/LunaTranslator#35]
我又来了反馈了
[](链接：https://pan.baidu.com/s/1MDM8iDji_XPOVcMDWHYp5w?pwd=4mzq 
提取码：4mzq )
解压密码：0000
游戏特殊码：/HBN4*4@12BAF0:fgf.exe
每次都需要将该游戏从Luna中删除，然后运行该游戏，重新配置一遍才行。只要使用Luna运行了其他游戏和二次打开翻译器都需要重新删除再配置一遍。
另外，Luna是不是不能对每个游戏单独记忆其特殊码，二次打开翻译器后特殊码也消失了。

**Comment by HIllya51** [comment]
下下来试了，不需要删除啊，在文本选择器里面重新选取一下就好了。。。
因为这个游戏重新启动之后ctx地址变了，所以没有自动选取hook，但是已经attach了。。。
这个选取hook的逻辑后面我再优化一下。。。

**Comment by HIllya51** [comment]
没有消失啊？？

**Comment by EXBJAN** [comment]
啊，我发现了，确实是不需要删除。
但是，神奇的是，关闭游戏从翻译器的已保存游戏里启动该游戏就提取不到文本。而从游戏目录启动游戏程序，翻译器又会自动提取到文本，特殊码也在正常生效。

**Comment by HIllya51** [comment]
你更新了吗？更新之后应该不存在这个问题了。

**Comment by EXBJAN** [comment]
大佬辛苦！你那边测试是不是一切正常了啊？
我刚更新了。然后就测试了下，为了排除影响，删除19.0重新配置的。问题依然存在。
我不知道是不是我的电脑环境跟你的有啥差异，反正依然是从翻译器二次启动会提取不到文本。

**Comment by HIllya51** [comment]
。。。算了我也不知道你是咋回事
选择文本界面正常不？正常的话重新选一下就好了。

**Comment by EXBJAN** [comment]
从翻译器打开的话选择文本界面空白，反而手动打开游戏程序选择界面也能提取到全部文本可供选择

**Comment by HIllya51** [comment]
能不能把具体的操作过程说一下，有点不太清楚。。。就是怎么操作能，怎么操作不能

**Comment by EXBJAN** [comment]
首先保证该游戏已经用翻译器+插入特殊码配置过，在翻译器的“已保存游戏”里能找到。
这里我首次配置选择了蓝色选中的条目
![RU9KHP3O3VGU6V5X_OSEVU5](https://user-images.githubusercontent.com/117036098/199492431-76433715-6789-4030-b5d3-334f717ee5d3.png)

【不能的情况】在翻译器运行的情况下，从翻译器的“已保存游戏里”选择该游戏，然后选择用“使用LocaleEmulator开始游戏”会导致文本选择器一片空白，提取不到文本。

【能的情况】翻译器运行后，我从资源管理器的游戏安装目录下找到并选择fgf.exe(也就是该游戏的主程序)>然后右键鼠标>在右键菜单里选择LocaleEmulator>选择Run in Japanese或Run in Japanese(Admin)，均能正常启动游戏，翻译器在游戏读档产生新文本后便能提取到首次配置时选择好的条目，如图，和之前选择的相同同时在文本选择界面里也能看到其他条目的文本。

另外我还尝试过将fgf.exe拖扯到LEGUI.exe和LEProc.exe上启动，均能使翻译器正常提取到文本。
最后，我个人的一点愚见，其实除了每次启动日区游戏都得通过右键选择LE启动的方式外，还可以用LE给游戏程序生成一个快捷启动方式，直接双击该图标即可转区启动，这或许可以给翻译器启动游戏提供一个方法，可以规避掉一些奇怪的问题。

**Comment by EXBJAN** [comment]
首先保证该游戏已经用翻译器+插入特殊码配置过，在翻译器的“已保存游戏”里能找到。
这里我首次配置选择了蓝色选中的条目
![RU9KHP3O3VGU6V5X_OSEVU5](https://user-images.githubusercontent.com/117036098/199492431-76433715-6789-4030-b5d3-334f717ee5d3.png)

【不能的情况】在翻译器运行的情况下，从翻译器的“已保存游戏里”选择该游戏，然后选择用“使用LocaleEmulator开始游戏”会导致文本选择器一片空白，提取不到文本。

【能的情况】翻译器运行后，我从资源管理器的游戏安装目录下找到并选择fgf.exe(也就是该游戏的主程序)>然后右键鼠标>在右键菜单里选择LocaleEmulator>选择Run in Japanese或Run in Japanese(Admin)，均能正常启动游戏，翻译器在游戏读档产生新文本后便能提取到首次配置时选择好的条目，如图
![Uploading }2TJJSDGOVD16DNE_B$RNHT.png…]()
和之前选择的相同同时在文本选择界面里也能看到其他条目的文本。

另外我还尝试过将fgf.exe拖扯到LEGUI.exe和LEProc.exe上启动，均能使翻译器正常提取到文本。
最后，我个人的一点愚见，其实除了每次启动日区游戏都得通过右键选择LE启动的方式外，还可以用LE给游戏程序生成一个快捷启动方式，直接双击该图标即可转区启动，这或许可以给翻译器启动游戏提供一个方法，可以规避掉一些奇怪的问题。

**Comment by EXBJAN** [comment]
首先保证该游戏已经用翻译器+插入特殊码配置过，在翻译器的“已保存游戏”里能找到。
这里我首次配置选择了蓝色选中的条目
![RU9KHP3O3VGU6V5X_OSEVU5](https://user-images.githubusercontent.com/117036098/199492431-76433715-6789-4030-b5d3-334f717ee5d3.png)

【不能的情况】在翻译器运行的情况下，从翻译器的“已保存游戏里”选择该游戏，然后选择用“使用LocaleEmulator开始游戏”会导致文本选择器一片空白，提取不到文本。

【能的情况】翻译器运行后，我从资源管理器的游戏安装目录下找到并选择fgf.exe(也就是该游戏的主程序)>然后右键鼠标>在右键菜单里选择LocaleEmulator>选择Run in Japanese或Run in Japanese(Admin)，均能正常启动游戏，翻译器在游戏读档产生新文本后便能提取到首次配置时选择好的条目，如图
![}2TJJSDGOVD16DNE_B$RNHT](https://user-images.githubusercontent.com/117036098/199495537-dcbe153b-7f31-477a-abe3-a9125adc3fe6.png)
和之前选择的一样，且能浏览到其他文本。

另外我还尝试过将fgf.exe拖扯到LEGUI.exe和LEProc.exe上启动，均能使翻译器正常提取到文本。
最后，我个人的一点愚见，其实除了每次启动日区游戏都得通过右键选择LE启动的方式外，还可以用LE给游戏程序生成一个快捷启动方式，直接双击该图标即可转区启动，这或许可以给翻译器启动游戏提供一个方法，可以规避掉一些奇怪的问题。

**Comment by EXBJAN** [comment]
对了！还有个细节，上次反馈问题给你分享的那个游戏，其实不用LE转区也能正常启动，但如果通过翻译器的“已保存游戏”选择“开始游戏”（不使用LE启动）则会报错，如图所示 （或许跟这次反馈的问题有什么关联）
![image](https://user-images.githubusercontent.com/117036098/199496756-00e5319a-2fb0-4ae2-85f9-7ff64f5d0066.png)

**Comment by HIllya51** [comment]
确实是有一点问题。。一会改一下
