### ISSUE TITLE
可以开放提示词自定义功能吗

### ISSUE THREAD

**Issue by lhj5426** [HIllya51/LunaTranslator#350]
端午节好 开发者大佬
如题 可以 开放 GPT提示词的自定义功能吗
![image](https://github.com/HIllya51/LunaTranslator/assets/30548000/b1000c4d-2e3f-48c2-85ce-66fa4f95440d)
如图 您看到的那样 同样是GPT 相同的话
luna 上的GPT 就拒绝了
我是用来制作漫画字幕
会同时参考十几个传统翻译引擎 以及 多个 ai 的结果 来拼凑出
一句通顺 或者大概通顺的话 所以希望能开放 提示词的自定义功能 
![image](https://github.com/HIllya51/LunaTranslator/assets/30548000/d2c0558f-ddc6-458f-a220-2d219abc8f1b)
您设置了这么多功能 就唯独没有提示词功能 就有点奇怪呀

**Comment by HIllya51** [comment]
已支持
