### ISSUE TITLE
模拟按键问题

### ISSUE THREAD

**Issue by SakiBiAnNya** [HIllya51/LunaTranslator#351]
让翻译器模拟键盘按键按下，好像前提是在翻译窗口失去交互焦点的情况下才能触发，但是点击窗口的模拟按键，游戏窗口就失去焦点了，然后这个快进操作就无效了...........这好像会涉及到对翻译窗口的修改。感觉工程量会有点巨大，想看看大佬的意见，往后会不会修改，还是说删除这个模拟按键的功能算了

**Comment by HIllya51** [comment]
只需修改simulate_key_enter和simulate_key_ctrl这两个函数即可。
在我测试的游戏上这样是没问题的。你试着改一下吧。
https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/LunaTranslator/gui/translatorUI.py#L205

**Comment by SakiBiAnNya** [comment]
> 简单修改simulate_key_enter和simulate_key_ctrl这两个函数即可。 在我测试的游戏上这样是没问题的。你试试改一下吧。 [https://github.com/HIllya51/LunaTranslator/blob/main/L una翻译/ LunaTranslator/gui/translatorUI.py#L205](https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/LunaTranslator/gui/translatorUI.py#L205)

说来惭愧，我不会写代码(ಥ_ಥ)

**Comment by HIllya51** [comment]
呃 那咋办 我测试没问题。。。

**Comment by SakiBiAnNya** [comment]
> 呃那咋办我测试没问题。。。

看了一下，游戏原生全屏状态下能用，但是点了快进后就无法再次点击取消了（点击无效），只能esc取消

**Comment by HIllya51** [comment]
这个东西可能是和具体的游戏自己的skip的实现有关的，可能不太好弄成通用的

**Comment by SakiBiAnNya** [comment]
> 这个东西可能是和具体的游戏自己的skip的实现有关的，可能不太好弄成通用的

可以做成按住快进，不按就停止了

**Comment by HIllya51** [comment]
实测不太行。。。

**Comment by HIllya51** [comment]
如果不行的话，你搞个类似按键精灵之类的专门的软件得了
