### ISSUE TITLE
功能请求：英文分词

### ISSUE THREAD

**Issue by 102757017** [HIllya51/LunaTranslator#352]
目前软件内置的分词功能只能对日语进行分词。如果原文是英文点击后获取到的是一个英文句子，而不是一个英文单词。请问是否可以设置一个英文分词的功能。

**Comment by HIllya51** [comment]
这不是脱裤子放屁？英语分什么词？

**Comment by 102757017** [comment]
学英语的时候有用啊，就是希望能选中一个单词，然后查这个单词的意思。
目前不开启分词功能，选不中文本；开启了分词功能，选择文本时选中的就是一个句子，需要把其它的单词都删除掉才能查看这个单词的翻译，操作比较麻烦。

**Comment by HIllya51** [comment]
已加

**Comment by 102757017** [comment]
最近更新了一下LunaTranslator的版本后英文取词功能失效了。

**Comment by HIllya51** [comment]
<img width="685" alt="屏幕截图 2024-03-30 234530" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/4f38ef4c-c4b5-4299-af42-158f018bb7cd">

？
