### ISSUE TITLE
翻译速度变慢了？

### ISSUE THREAD

**Issue by blucca** [HIllya51/LunaTranslator#353]
用 v2.25.2 和 v2.20.1 剪贴板模式对比测试了几遍，明显感觉 v2.25.2 翻译出现的速度要慢于 v2.20.1…

**Comment by HIllya51** [comment]
![批注 2023-06-26 204157](https://github.com/HIllya51/LunaTranslator/assets/101191390/fee07d8b-91b9-4012-a57e-e267a72f4a1a)
