### ISSUE TITLE
更新2.25.3后，人工翻译读取报错

### ISSUE THREAD

**Issue by OYcedar** [HIllya51/LunaTranslator#357]
「教えるわけないです」
人工翻译  UnboundLocalError local variable 'jc' referenced before assignment
彩云  “我不会告诉你的。”
百度  “我不会告诉你的。”
用2.25.1可以正常游玩
或者说luna推荐的人工翻译的json格式是怎样的？

**Comment by HIllya51** [comment]
已修正

**Comment by OYcedar** [comment]
OK，可以了
