### ISSUE TITLE
回報錯誤

### ISSUE THREAD

**Issue by bernie84** [HIllya51/LunaTranslator#358]
requests.exceptions.JSONDecodeError Expecting value: line 1 column 1 (char 0)
請問偶爾會跳出這項錯誤訊息，按重新翻譯就能解決，但出現頻率有點高，請問是哪邊出問題呢？
感謝回復

**Comment by HIllya51** [comment]
在线翻译有访问速度限制

**Comment by bernie84** [comment]
好的 感謝您回覆
