### ISSUE TITLE
大佬，一个老游戏提取不到文本

### ISSUE THREAD

**Issue by wycstc353** [HIllya51/LunaTranslator#359]
BISHOP社的特別授業，
https://kf.miaola.work/read.php?tid=888285&sf=ffc&keyword=%CC%D8%84e%CA%DA%98I
我在这里下载的，
链接:https://caiyun.139.com/m/i?105CfTMBjoT5m
提取码:7WEx
win10没法玩，只能win7玩，然后提取不到文本，希望大佬有空的话，研究下

**Comment by HIllya51** [comment]
传个正常点的盘发给我，这玩意没下载速度。

**Comment by HIllya51** [comment]
传个正常点的盘发给我

**Comment by HIllya51** [comment]
已更新
