### ISSUE TITLE
mecab 分詞顏色

### ISSUE THREAD

**Issue by sky456757** [HIllya51/LunaTranslator#36]
希望可以把mecab分詞上的顏色增加一點規則，像是照詞性分之類的，現在看起來像是random，還有希望可以自定義分詞上色的顏色和透明度

**Comment by HIllya51** [comment]
ok

**Comment by sky456757** [comment]
剛剛在試了一下，調整完好像還是random指定顏色

**Comment by HIllya51** [comment]
你设置的啥？要在辞书那里设置。

**Comment by sky456757** [comment]
<img width="1660" alt="截圖 2022-11-03 下午8 07 25" src="https://user-images.githubusercontent.com/22101536/199716665-b7fd7ab5-5efd-4c76-9852-fc63975f3322.png">
<img width="1432" alt="截圖 2022-11-03 下午8 07 33" src="https://user-images.githubusercontent.com/22101536/199716700-c27175ef-6504-46b1-8151-d5698bbb2d46.png">
大概像這樣

**Comment by HIllya51** [comment]
你设置mecab路径了吗？没有的话不行。

**Comment by sky456757** [comment]
可以了，好像是因為虛擬機的關係，路徑的權限有點問題
