### ISSUE TITLE
关于开启翻译器“欢迎使用”这个窗口文本

### ISSUE THREAD

**Issue by SakiBiAnNya** [HIllya51/LunaTranslator#360]
可以做一下这个的提示词的隐藏吗？我使用窗口延迟隐藏发现不能隐藏（因为不用提取文本）。

原因是我是需要使用从翻译器启动的Magpie放大，再加上Moonlight串流，并且只有从翻译器启动的Magpie，Moonlight串流时才不会卡屏，这样一些有汉化的游戏也可以放大并串流使用了（Magpie那边也说串流卡屏是Moonlight的原因，不过Moonlight的开发者好像不想解决这个问题）

**Comment by SakiBiAnNya** [comment]
> 你给他最小化不就行了，为什么要他自己隐藏。

最小化串流就会卡屏......不知道不卡屏是不是因为有个窗口在上面

**Comment by HIllya51** [comment]
你手动最小化和他自动最小化没区别啊。或者你设置个快捷键最小化

**Comment by SakiBiAnNya** [comment]
> 你手动最小化和他自动最小化没区别啊。或者你设置个快捷键最小化

可以了。怪了，之前的版本使用Magpie放大后+翻译窗口最小化后我串流就会卡屏

**Comment by HIllya51** [comment]
emmm...👌
