### ISSUE TITLE
使用预翻译报错

### ISSUE THREAD

**Issue by lqw1260** [HIllya51/LunaTranslator#361]
如图，导入json文件，翻译了一句之后报错
UnboundLocalError local variable 'savet' referenced before assignment
![图片](https://github.com/HIllya51/LunaTranslator/assets/129644030/865efc41-2cc3-4727-bd04-afb46f65c2e2)

**Comment by lqw1260** [comment]
初步排查了一下，基本上在出现对话有“「」”就会报错，其他文本不会报错，是我json格式有问题吗？
![图片](https://github.com/HIllya51/LunaTranslator/assets/129644030/7c11ea7d-2630-4459-bd21-33c5df555850)

**Comment by HIllya51** [comment]
你重下一下试试，我更新过。

**Comment by lqw1260** [comment]
重下后基本上解决了，之前是用设置里的自动更新更新到2.25.4。
