### ISSUE TITLE
wolfRPG2提取文本大量重复

### ISSUE THREAD

**Issue by hormenks** [HIllya51/LunaTranslator#362]
如下图，针对《in by side》这个rpg游戏。wolfRPG2提取的文本大量重复，就算使用了去除重复行也依然影响翻译，因为它好像一直在提取文本，导致翻译也反复刷新。请问有没有办法解决？

![反馈](https://github.com/HIllya51/LunaTranslator/assets/25704833/d4559538-bae2-4b25-b93e-e70fdfe9f484)

另外，文本编码能否增加UTF16？

**Comment by ZZZWWWJJJ** [comment]
我用vnr3试了一下，UTF16编码提取《in by side》这个游戏的文本有不错的效果，所以想请问作者有没有计划加入UTF16

**Comment by HIllya51** [comment]
游戏发我。

**Comment by hormenks** [comment]
> 游戏发我。

https://pan.baidu.com/s/1q57J4u5uK0bOW35E3bUVCw
提取码：1234

**Comment by HIllya51** [comment]
已修正

**Comment by hormenks** [comment]
> 已修正

太高效了，我稍后试试！

想请问一下，每次更新是否把老文件夹的userconfig复制到新版本的文件夹即可保留用户设置（api的key等）？

**Comment by HIllya51** [comment]
![批注 2023-07-10 142140](https://github.com/HIllya51/LunaTranslator/assets/101191390/379e74dd-5482-44af-b232-fedf3043e043)

**Comment by HIllya51** [comment]
> 想请问一下，每次更新是否把老文件夹的userconfig复制到新版本的文件夹即可保留用户设置（api的key等）？

显然是。

**Comment by hormenks** [comment]
> ![批注 2023-07-10 142140](https://user-images.githubusercontent.com/101191390/252252024-379e74dd-5482-44af-b232-fedf3043e043.png)

好的，我来试试，感谢回复和修正~

**Comment by hormenks** [comment]
> 打开这个。 ![批注 2023-07-10 142140](https://user-images.githubusercontent.com/101191390/252252024-379e74dd-5482-44af-b232-fedf3043e043.png)

经测试，已经解决提取文本重复刷新的问题，十分感谢！
