### ISSUE TITLE
软件资源包里的Jbeijing7userdict.zip下载链接失效了

### ISSUE THREAD

**Issue by Ywocp** [HIllya51/LunaTranslator#364]
开发者你好，在昨天我使用露娜翻译器的时候，Jbeijing7的翻译效果不太好，想要下载用户词典来提高翻译质量，但是我发现资源包的下载链接已经缺失了，可以补一下链接吗？

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/releases/download/v1.0/JBeijing7UserDict.zip
