### ISSUE TITLE
GPT第三方接口这个，模型的选项有影响吗？

### ISSUE THREAD

**Issue by Joackk** [HIllya51/LunaTranslator#365]
比如说第三方有3.5、gpt4这些，如果想使用gpt4  model该怎么写哇？直接写gpt-4  似乎会被提示不存在

**Comment by HIllya51** [comment]
有可能你用的第三方不支持gpt-4，openai官方接口就是gpt-4

**Comment by Joackk** [comment]
> 有可能你用的第三方不支持gpt-4，openai官方接口就是gpt-4

我用的第三方的，所以选择的是第三方接口，这个模型的选项有影响吗？因为第三方接口有多个模型设置

**Comment by HIllya51** [comment]
那你去查他文档看他支持什么模型啊，我都不知道你说的是什么网站我怎么知道。😓

**Comment by Joackk** [comment]
> model

我的意思是翻译其中第三方gpt接口设置里的model选项，对使用模型有影响吗？它是根据这里填写的来决定使用那个模型吗？

**Comment by HIllya51** [comment]
是的呢。

**Comment by Joackk** [comment]
> 是的呢。

soga
