### ISSUE TITLE
无法使用chatgpt翻译

### ISSUE THREAD

**Issue by ikazoa** [HIllya51/LunaTranslator#366]
帮朋友问的，用gpt官方接口会出现如下的报错：

openai.error.APlConnectionError Error communicating with OpenAl: HT TPSConnectionPool(host='api.openai.com,
port=443): Max retries exceeded with url: Iv 1/chat/completions (Caused by
NewConnectionError( kurlib3.connection.HTTPSConnection object at 0x00000245C9F534C8>: Failed to establish a
new connection: [WinError 10060]由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

key经过其它软件测试是有效的（同时也代表不是网络问题），luna翻译器已更新至最新版，其它翻译接口如有道等能正常使用

**Comment by HIllya51** [comment]
设置代理啊代理

**Comment by ikazoa** [comment]
翻译器代理设置里两个都勾选了（自动获取）。并且确实挂着梯子，网页版chatgpt都能用

**Comment by HIllya51** [comment]
这个就是网络错误，肯定是他代理设置的不对。那我也不知道了。
