### ISSUE TITLE
请问可以直接提取原文文本为json吗？

### ISSUE THREAD

**Issue by hormenks** [HIllya51/LunaTranslator#367]
请问可否直接提取原文全文的文本，提取为 { 日文原文：日文原文 } 这样的json格式。貌似mtool有这个功能，但是我有个游戏mtool不支持引擎——老版本kirikiri2——您的翻译器可以支持，所以问问。

**Comment by HIllya51** [comment]
不能。你应该去寻找解包程序。mtool应该就是内置了krkr的解包程序。
