### ISSUE TITLE
第三方gpt报错，之前可用

### ISSUE THREAD

**Issue by Joackk** [HIllya51/LunaTranslator#370]
报错如下，前两天时候还是正常用的，今天再用时候就一直提示这个，第三方gpt的key也本地测试了是可用的，奇怪的是除了更新了下翻译的版本，其他没有进行操作，突然就报了这个错误
![image](https://github.com/HIllya51/LunaTranslator/assets/45162558/29d9a293-3965-46ca-aaf2-a101a94e4b69)

**Comment by HIllya51** [comment]
> 第三方gpt的key也本地测试了是可用的

怎么测得？这个东西我根本就没有改过，所以之前能用现在不能用肯定不是我的问题。

**Comment by Joackk** [comment]
> > 第三方gpt的key也本地测试了是可用的
> 
> 怎么测得？这个东西我根本就没有改过，所以之前能用现在不能用肯定不是我的问题。

我用的ChimeraGPT，他只提供了api，使用就是用py脚本，用py脚本发消息得到的回复也是正常，只是反应有点慢

**Comment by Joackk** [comment]
> > 第三方gpt的key也本地测试了是可用的
> 
> 怎么测得？这个东西我根本就没有改过，所以之前能用现在不能用肯定不是我的问题。

找到问题了，之前接口用地址我直接填的，他现在似乎更新了一波，直接填写xxx/v1不行了，我填写了完整的api地址就正常了，感谢
