### ISSUE TITLE
[功能建议] 建议增加一个显示/隐藏 翻译结果的快捷键

### ISSUE THREAD

**Issue by YWtheGod** [HIllya51/LunaTranslator#372]
翻译内容有时会遮挡画面内容，建议增加一个快捷键切换翻译内容的显示/隐藏，当前可以用鼠标进行最小化，然后再在右下图标恢复显示方式实现，比较麻烦

**Comment by HIllya51** [comment]
![批注 2023-08-02 001652](https://github.com/HIllya51/LunaTranslator/assets/101191390/46fd52df-ba89-4712-b6f4-ef9259eb00bc)
本来就有。
