### ISSUE TITLE
[功能建議] 增加類似VRN可以指定不同角色名稱來呼叫不同語音合成的角色

### ISSUE THREAD

**Issue by SyaoranChang** [HIllya51/LunaTranslator#374]
你好,

希望能增加類似VRN可以指定不同角色名稱來呼叫不同語音合成的角色
預設一個沒有名稱的為旁白
然後使用者可以自行新增其他角色名稱

如:常沒有被配音的主角
和一些沒有被配音到的配角

如果新發現的角色能自動新增到清單中
或許會更方便使用?

![Snipaste_2023-08-07_00-51-14](https://github.com/HIllya51/LunaTranslator/assets/18550228/38d9333f-9a16-4138-95c3-6321fcfe3168)

**Comment by HIllya51** [comment]
曾经有，但是有的游戏引擎只有人名改变才输出，有的引擎每句话都输出人名，完全没有办法准确的判断当前是人名还是旁白。而且很多引擎没办法提取人名。所以感觉根本没什么意义，干脆砍掉了。

**Comment by SyaoranChang** [comment]
原來如此，感謝回覆了
