### ISSUE TITLE
用内嵌功能某些文字不显示

### ISSUE THREAD

**Issue by ttkk907** [HIllya51/LunaTranslator#376]
如图，对escude这个引擎内嵌会出现某些文字不显示的情况，试了几个别的引擎好像没有这种问题
![QQ截图20230810100433](https://github.com/HIllya51/LunaTranslator/assets/125134527/37fd3f9b-3934-4362-b575-2d871cd8a1ea)

**Comment by HIllya51** [comment]
将汉字转换成繁体/日式汉字。

**Comment by ttkk907** [comment]
感觉还是有一些字不会显示
![QQ截图20230810155109](https://github.com/HIllya51/LunaTranslator/assets/125134527/8da47c19-6cb8-491d-927e-946672b57706)

**Comment by HIllya51** [comment]
就这样，没办法，除非改游戏程序

**Comment by zhw910713** [comment]
@ttkk907 可以下个中日匹配的字体安装后把内嵌翻译的字体改成中日匹配的字体，我是用的github里面大老修改过的中日匹配字体
