### ISSUE TITLE
如何在自定义翻译中使用分词结果

### ISSUE THREAD

**Issue by blucca** [HIllya51/LunaTranslator#378]
我想在 `.\userconfig\selfbuild.py` 中使用 `.\LunaTranslator\hiraparse\mecab.py` 返回的 `result` 分词结果，请问要怎么写呢…

**Comment by HIllya51** [comment]
翻译用这个干什么。。。

**Comment by HIllya51** [comment]
![批注 2023-08-13 200322](https://github.com/HIllya51/LunaTranslator/assets/101191390/b7648282-6adf-48a7-9750-8abae508dd2c)
刚刚更新了一下，定义translate_with_extra函数按照如图方式即可。

**Comment by HIllya51** [comment]
已修
