### ISSUE TITLE
能不能增加ocr和剪切板的翻译记录保存

### ISSUE THREAD

**Issue by yui799** [HIllya51/LunaTranslator#38]
大大，能不能像御坂一样ocr翻译后自动生成编号为-1文件的sqlite文件，剪切板翻译后自动生成编号为0的sqlite的文件，这样用这两种方法提取出的原文文本和翻译文本也能导出，等玩完游戏后把sqlite文件移走，玩下一个游戏再生成新的缓存

**Comment by HIllya51** [comment]
ok
