### ISSUE TITLE
windows10 启动文件无法打开

### ISSUE THREAD

**Issue by 397764842** [HIllya51/LunaTranslator#383]
WINDOWS10系统，昨天用一半突然跳闸 电脑关机， 重启后 启动软件无法打开 求解答。 感觉是注册表丢失了

**Comment by HIllya51** [comment]
删了重新下载吧。软件不访问注册表。

**Comment by 397764842** [comment]
> Owner

可是加载好的很多游戏文件都没了，，又要重弄能弄个修复吗？

**Comment by HIllya51** [comment]
把userconfig打包发给我

**Comment by 397764842** [comment]
星天成龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HIllya51/LunaTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月2日(星期六) 下午3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HIllya51/LunaTranslator] windows10 启动文件无法打开 (Issue #383)





 
把userconfig打包发给我

**Comment by HIllya51** [comment]
？

**Comment by 397764842** [comment]
星天成龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "星天成龙"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月2日(星期六) 晚上7:01
***@***.***&gt;;

主题:&nbsp;回复： [HIllya51/LunaTranslator] windows10 启动文件无法打开 (Issue #383)









星天成龙
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "HIllya51/LunaTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月2日(星期六) 下午3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HIllya51/LunaTranslator] windows10 启动文件无法打开 (Issue #383)





 
把userconfig打包发给我

**Comment by HIllya51** [comment]
？
