### ISSUE TITLE
win10 19045.3324 每次启动都要确认

### ISSUE THREAD

**Issue by 123456ds** [HIllya51/LunaTranslator#384]
![屏幕截图 2023-08-22 114740.png](https://p.inari.site/guest/23-08/22/64e4301a2d560.png)
![屏幕截图 2023-08-22 115032.png](https://p.inari.site/guest/23-08/22/64e430975dfe4.png)

**Comment by HIllya51** [comment]
https://www.baidu.com/s?ie=UTF-8&wd=%E8%A6%81%E5%9C%A8microsoft%20store%E4%B8%AD
https://zhuanlan.zhihu.com/p/636154009?utm_id=0
能不能自己百度一下？不要什么都来问我。😓

**Comment by 123456ds** [comment]
> https://www.baidu.com/s?ie=UTF-8&wd=%E8%A6%81%E5%9C%A8microsoft%20store%E4%B8%AD https://zhuanlan.zhihu.com/p/636154009?utm_id=0 能不能自己百度一下？不要什么都来问我。😓

谢谢提示，主要是以前没有遇到过这样的弹窗
