### ISSUE TITLE
文本中的空白行

### ISSUE THREAD

**Issue by a73420521** [HIllya51/LunaTranslator#385]
dROSEra ～レディ・バッドエンドの初恋～的文本在提取時經常出現空白行，跳過本應被翻譯的文本，請問要如何設置才能避免出現空白行?
![01](https://github.com/HIllya51/LunaTranslator/assets/87113124/0fa4e67f-e5f0-4c0f-929b-68f781acbfe5)
紅點標示處
![02](https://github.com/HIllya51/LunaTranslator/assets/87113124/d9196939-7fdc-4904-abd1-6ecfd4d24d78)

**Comment by HIllya51** [comment]
![批注 2023-08-22 223201](https://github.com/HIllya51/LunaTranslator/assets/101191390/52b67b24-d377-4c85-80ae-6cd9096816d8)

**Comment by a73420521** [comment]
> ![批注 2023-08-22 223201](https://user-images.githubusercontent.com/101191390/262386273-52b67b24-d377-4c85-80ae-6cd9096816d8.png)

試過了還是會，遊戲中角色立繪的動作有變化就會有一個空白的文本出現。
![01](https://github.com/HIllya51/LunaTranslator/assets/87113124/d5fdcf83-9651-4ebc-b496-e2441e1bb64c)
![02](https://github.com/HIllya51/LunaTranslator/assets/87113124/0bdf8537-505e-475c-82c7-09a1b36e5fb2)

**Comment by HIllya51** [comment]
你把空白选取复制出来加到过滤里面，应该是有不可见的字符。
