### ISSUE TITLE
游戏《エクソダスギルティー・オルタナティブ》HOOK到的文本处理问题

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#387]
游戏：https://bbs.kfpromax.com/read.php?tid=797961&sf=596
![QQ截图20230825020008](https://github.com/HIllya51/LunaTranslator/assets/137600501/5af72d5d-6c06-4e72-8530-04fd688001f3)

**Comment by dnadash** [comment]
处理不成游戏原文本的样子，不知道大佬能不能给一个方案

**Comment by HIllya51** [comment]
(.*)】(.*?)
![批注 2023-08-25 020833](https://github.com/HIllya51/LunaTranslator/assets/101191390/ab2f7a3a-829d-4ff8-a716-124641d4face)

**Comment by dnadash** [comment]
> ![批注 2023-08-25 020833](https://user-images.githubusercontent.com/101191390/263064829-ab2f7a3a-829d-4ff8-a716-124641d4face.png)

![QQ截图20230825041714](https://github.com/HIllya51/LunaTranslator/assets/137600501/9c1b5e33-799b-467c-a6c8-dbd4f01e090c)
![QQ截图20230825041704](https://github.com/HIllya51/LunaTranslator/assets/137600501/2b79ddc3-db16-4494-8546-bbc7b1676b37)
如何处理能得到前面这段文字？前后文字一样的时候没影响，有时候经常后段文字会多

**Comment by HIllya51** [comment]
重新下载，已内置完美支持
