### ISSUE TITLE
專有名詞翻譯MD5會自己轉變

### ISSUE THREAD

**Issue by a73420521** [HIllya51/LunaTranslator#389]
新增專有名詞時，當前遊戲的MD5為2e8be3edfd9fe60e0676929ee07df1b5，但關閉後文本讀取到設定的名詞時會自動變成另一款遊戲的MD5：8656a58af5b6e82efdc2a4ea323f89b8，而手動更改MD5後再新增新的就不會再變更，但重開LunaTranslator後又會再發生，兩款遊戲分別是「戦国†恋姫ＥＸ 壱 ～奥州の独眼竜編～」與「戦国†恋姫ＥＸ 参 ～毛利家の絆編～」

**Comment by HIllya51** [comment]
啥意思，我完全看不懂你在说什么。。。

**Comment by a73420521** [comment]
> 啥意思，我完全看不懂你在说什么。。。
我重拍了一個影片，新增一個專有名詞翻譯時，遊戲的ID MD5是正常的，但只要再次HOOK到新增的名詞時，ID MD5會自動跳成另一部遊戲的ID MD5
[85a46007-f6db-4851-906a-02dfbbccfe1d.webm](https://github.com/HIllya51/LunaTranslator/assets/87113124/4011d2d1-0d17-4dbf-bc2d-35d3233ab5f8)

**Comment by HIllya51** [comment]
应该是之前有不同md5的同名词条。已修正

**Comment by a73420521** [comment]
謝謝，因為是系列遊戲，但又不想設成全域，所以只能每一部都手動新增一次。
