### ISSUE TITLE
数据库的翻译求助

### ISSUE THREAD

**Issue by yui799** [HIllya51/LunaTranslator#39]
大佬，我用不同的ocr提取出的文字有些不同，昨天用新版本玩游戏发现只要提取出的文字不完全一致就没法用机器预翻译和人工翻译，所以我想提议一下，能不能提取出的文字只要大致相符，数据库里的翻译就能匹配上去。谢谢了！

**Comment by HIllya51** [comment]
ok 就是速度会比较卡。
