### ISSUE TITLE
在线翻译有道3和有道5这俩是不能一直用吗？偶尔会错误

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#390]
![QQ截图20230827014445](https://github.com/HIllya51/LunaTranslator/assets/137600501/846d6265-35ee-4478-81b2-b3159fbeabb6)
是不是有道特有的问题？感觉有道翻译日文效果很好，挺想一直免费用的

**Comment by dnadash** [comment]
自己打开代理设置，好像又能用了

**Comment by HIllya51** [comment]
这不是废话，免费的能让你无限随便用？
