### ISSUE TITLE
Lingva 修改默认域名 & 允许设置自建实例

### ISSUE THREAD

**Issue by Vinfall** [HIllya51/LunaTranslator#394]
根据 https://github.com/thedaviddelta/lingva-translate/issues/169 ，在线翻译里Lingva默认域名`lingva.ml`已经被收回，建议改成`translate.plausibility.cloud`。

https://github.com/HIllya51/LunaTranslator/blob/e7101e0ef9dd7434047eb9fc8ce6c6d23be9f3fc/LunaTranslator/LunaTranslator/translator/lingva.py#L9-L28

最好能顺带加个自定义功能，避免使用自建的lingva translate每次都手动替换域名。

**Comment by HIllya51** [comment]
已修
