### ISSUE TITLE
v2.28.1 64bit最新版本无法使用，加载游戏就进程崩溃 无法进行

### ISSUE THREAD

**Issue by 397764842** [HIllya51/LunaTranslator#395]
v2.28.1 64bit最新版本无法使用，加载游戏就进程崩溃 无法进行。进入游戏加载读取就进程崩溃无法运行，关掉后游戏会正常运行 启动软件进行提取文本就卡死
![2023-09-02 15-37-47-99](https://github.com/HIllya51/LunaTranslator/assets/142773043/595ac31d-9056-4334-bd08-e3f5d3624c8a)
![2023-09-02 15-40-31-75](https://github.com/HIllya51/LunaTranslator/assets/142773043/1a9f5886-b4f3-4731-9ade-0088dcbd47da)

**Comment by HIllya51** [comment]
把userconfig打包发给我

**Comment by HIllya51** [comment]
兄弟，人呢？

**Comment by HIllya51** [comment]
你人呢？装高冷就当你已经解决了。

**Comment by 397764842** [comment]
抱歉 不是装高冷 。是最近有点事没肯定信息抱歉



---原始郵件---
寄件人： ***@***.***&gt;
傳送時間： 2023年9月3日(週日) 中午1:46
收件人： ***@***.***&gt;;
抄送： ***@***.******@***.***&gt;;
主旨： Re: [HIllya51/LunaTranslator] v2.28.1 64bit最新版本无法使用，加载游戏就进程崩溃 无法进行 (Issue #395)




 
你人呢？装高冷就当你已经解决了。

**Comment by 397764842** [comment]
电脑不在身边现在 。没我记得之前有发used coing什么 没收到吗朋友



---原始郵件---
寄件人： ***@***.***&gt;
傳送時間： 2023年9月3日(週日) 中午1:46
收件人： ***@***.***&gt;;
抄送： ***@***.******@***.***&gt;;
主旨： Re: [HIllya51/LunaTranslator] v2.28.1 64bit最新版本无法使用，加载游戏就进程崩溃 无法进行 (Issue #395)




 
你人呢？装高冷就当你已经解决了。

**Comment by 397764842** [comment]
我重新下载新一个就好了。好像是自带更新出的问题
。现在下的新的感觉翻译没以前快了

---原始郵件---
寄件人： ***@***.***&gt;
傳送時間： 2023年9月3日(週日) 中午1:46
收件人： ***@***.***&gt;;
抄送： ***@***.******@***.***&gt;;
主旨： Re: [HIllya51/LunaTranslator] v2.28.1 64bit最新版本无法使用，加载游戏就进程崩溃 无法进行 (Issue #395)




 
你人呢？装高冷就当你已经解决了。

**Comment by HIllya51** [comment]
没收到

**Comment by HIllya51** [comment]
> 我重新下载新一个就好了。好像是自带更新出的问题 。现在下的新的感觉翻译没以前快了
> […](#)
> ---原始郵件--- 寄件人： ***@***.***&gt; 傳送時間： 2023年9月3日(週日) 中午1:46 收件人： ***@***.***&gt;; 抄送： ***@***.******@***.***&gt;; 主旨： Re: [HIllya51/LunaTranslator] v2.28.1 64bit最新版本无法使用，加载游戏就进程崩溃 无法进行 (Issue #395) 你人呢？装高冷就当你已经解决了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可能是刷新延迟的问题，后面的版本我把默认的刷新延迟提高到0.5秒了，之前的好像是0.1秒来着。你把这个调低一下应该就会快了

**Comment by 397764842** [comment]
可以收到吗


星天成龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HIllya51/LunaTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月2日(星期六) 下午3:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HIllya51/LunaTranslator] v2.28.1 64bit最新版本无法使用，加载游戏就进程崩溃 无法进行 (Issue #395)





 
把userconfig打包发给我
