### ISSUE TITLE
游戏提取文本不全

### ISSUE THREAD

**Issue by yaekemono** [HIllya51/LunaTranslator#397]
名字是痕きずあと。这游戏会在同一页逐行显示多行对话，hook之后会把该页所有文本都直接显示出来，但有时只能提取到头一句，而且提取出来的文本频繁出现各种标记符干扰翻译。但似乎回滚到上一页能顺利读取文本
![](https://i.imgur.com/CgGBZWP.png)

**Comment by HIllya51** [comment]
哪一版

**Comment by HIllya51** [comment]
这作不是已经汉化了吗。你在玩旧版吗？

**Comment by yaekemono** [comment]
09版，没有完全汉化吧，找到的都是V0.8补丁。标记符我用正则表达式替换勉强去掉，虽说不知道全不全。就是这个文本不全比较难受，因为它一旦没读到文本，就只能一直按到第二页再回头看第一页，而且点之前的对话它也会把整页的翻译结果给刷没，然后第二页一开始它按惯例把那页的文字全发出来了，等到看完第一页再继续看第二页，因为前面已经判断提取完第二页的文本了，所以不能重新翻译，只能把历史翻译找出来看，体验极其割裂……

**Comment by HIllya51** [comment]
HS34@4AF290
没有找到更好的了。这个也是一次会显示一整页，但可以提取全了。

**Comment by yaekemono** [comment]
感谢大佬，现在可读性恢复到正常水平了
