### ISSUE TITLE
游戏《DUEL SAVIOR JUSTICE》英译和日文原版都无法hook文本

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#399]
![QQ截图20230906212313](https://github.com/HIllya51/LunaTranslator/assets/137600501/2c5bd74a-b76a-4a26-ba63-d9dd8946e67f)
![QQ截图20230906214546](https://github.com/HIllya51/LunaTranslator/assets/137600501/44c53e6c-4e54-4099-9431-0500a3621aeb)

**Comment by dnadash** [comment]
本体镜像+英译补丁+win10兼容补丁链接：https://pan.baidu.com/s/1w4qsR8j48TNrKZJjb2ha4w 
提取码：fbwz

**Comment by HIllya51** [comment]
？
![批注 2023-09-07 124246](https://github.com/HIllya51/LunaTranslator/assets/101191390/38725149-dd82-476a-af57-599746a294db)
