### ISSUE TITLE
正则表达式替换的一点问题

### ISSUE THREAD

**Issue by neetnya** [HIllya51/LunaTranslator#40]
似乎不支持 $1 的写法？
比如我想要把
⌈台词⌋ 替换成 台词

那么正则表达式的写法就是 ⌈(.*)⌋ 替换成 $1
实际使用后并没有把内容提取出来 而是显示$1

**Comment by HIllya51** [comment]
首先$1并不是python的语法。
其次这个功能用的是re.sub，并不能进行提取，只能进行替换。而且这种复杂的功能很难做成gui的。
如果确实有需要，建议直接修改专门为此预留的LunaTranslator\LunaTranslator\postprocess\post.py文件进行想要的操作。（简单学一下python的re的用法就可以了）

**Comment by HIllya51** [comment]
例如你想要的这个功能只需要在文件倒数第二行加上：
line=re.search('⌈(.*)⌋ ',line).group()
即可。

**Comment by neetnya** [comment]
好的 谢谢大佬
