### ISSUE TITLE
可否添加一个额外的deelp接口？

### ISSUE THREAD

**Issue by Joackk** [HIllya51/LunaTranslator#402]
社区里某大佬搭建的有一个免费的deelp接口https://api.deeplx.org/translate  并且没有限制并发
可否吧这个加入一个自定义的deelp接口来调用这个？

**Comment by HIllya51** [comment]
不舍得说一下怎么调用吗？

**Comment by Joackk** [comment]
> 不舍得说一下怎么调用吗？

这个似乎就是[DeepLX](https://github.com/OwO-Network/DeepLX)这个项目搭建的，调用应该和deelp是一样的，py调用是下面这样
```
import httpx, json

deeplx_api = "https://api.deeplx.org/translate"

data = {
	"text": "Hello World",
	"source_lang": "EN",
	"target_lang": "ZH"
}

post_data = json.dumps(data)
r = httpx.post(url = deeplx_api, data = post_data).text
print(r)
```

**Comment by HIllya51** [comment]
既然这样你自己用就好了，这边不打算添加非官方接口，PR除外。

**Comment by Joackk** [comment]
> 既然这样你自己用就好了，这边不打算添加非官方接口，PR除外。

但这个要怎么在Tr里调用？我看了在线翻译部分接口地址都固定住了

**Comment by HIllya51** [comment]
直接改代码啊 LunaTranslator/translator/deeplapi.py

**Comment by Joackk** [comment]
> 直接改代码啊 LunaTranslator/translator/deeplapi.py

soga，感谢
