### ISSUE TITLE
又出问题了。。。这第三次了。。之前弄重装修复，可每次这样用户资料又嘚重弄，这次研究下咋回事吧。求解决下

### ISSUE THREAD

**Issue by 397764842** [HIllya51/LunaTranslator#403]
![M{LAMO~9)DWTLV(LCUQGMU4](https://github.com/HIllya51/LunaTranslator/assets/142773043/e0d4afe6-6c1b-487f-af2e-330726f26f71)
![4395SZO F{_ERC ~YVFPFZJ](https://github.com/HIllya51/LunaTranslator/assets/142773043/77e61819-91dd-4f70-8877-362355a58c14)
![}%88W~YK@LQ 91YIRO%}KIT](https://github.com/HIllya51/LunaTranslator/assets/142773043/35a7f6d8-d512-4b71-b7db-b3d2df2fb510)

**Comment by 397764842** [comment]
userconig发过去了

**Comment by HIllya51** [comment]
> userconig发过去了

？你发哪去了？

**Comment by 397764842** [comment]
还是没吗

星天成龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HIllya51/LunaTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月14日(星期四) 中午11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HIllya51/LunaTranslator] 又出问题了。。。这第三次了。。之前弄重装修复，可每次这样用户资料又嘚重弄，这次研究下咋回事吧。求解决下 (Issue #403)





  
userconig发过去了
  
？你发哪去了？

**Comment by HIllya51** [comment]
你直接整个软件打包百度网盘发我

**Comment by 397764842** [comment]
链接：https://pan.baidu.com/s/1nY006fXkZUI8jy2VY_J8hA?pwd=1w3q&nbsp;
提取码：1w3q&nbsp;
--来自百度网盘超级会员V5的分享

星天成龙
***@***.***


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HIllya51/LunaTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月14日(星期四) 下午4:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HIllya51/LunaTranslator] 又出问题了。。。这第三次了。。之前弄重装修复，可每次这样用户资料又嘚重弄，这次研究下咋回事吧。求解决下 (Issue #403)





 
你直接整个软件打包百度网盘发我

**Comment by HIllya51** [comment]
测试没有任何问题。。。卡住的时候软件会卡住吗？

**Comment by 397764842** [comment]
是的 游戏卡住应该是读取游戏文本时候出错。关了软件后正常运行。。游戏就没事



---原始郵件---
寄件人： ***@***.***&gt;
傳送時間： 2023年9月14日(週四) 晚上8:02
收件人： ***@***.***&gt;;
抄送： ***@***.******@***.***&gt;;
主旨： Re: [HIllya51/LunaTranslator] 又出问题了。。。这第三次了。。之前弄重装修复，可每次这样用户资料又嘚重弄，这次研究下咋回事吧。求解决下 (Issue #403)




 
测试没有任何问题。。。卡住的时候软件会卡住吗？

**Comment by HIllya51** [comment]
所以你测试一下截图给我看看呀

**Comment by HIllya51** [comment]
人呢🙃

**Comment by HIllya51** [comment]
可能已修正
