### ISSUE TITLE
xp系统里的游戏hook到文本后，在宿主机内剪贴板翻译相关问题

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#405]
看到露娜佬发的帖了，说是可以用宿主机的翻译器翻译，难道每次翻译都得点一次虚拟机里的“复制到剪切板”吗？

**Comment by HIllya51** [comment]
![批注 2023-09-16 115719](https://github.com/HIllya51/LunaTranslator/assets/101191390/747ff007-d136-4e6c-bb10-8f7545a39e19)
