### ISSUE TITLE
退出重进后不显示之前设置的快捷键&快捷键中 `Win` 键仍然显示为 `Meta` 键

### ISSUE THREAD

**Issue by F-park** [HIllya51/LunaTranslator#407]
> 之前的 #377 中的不支持的键位 `Win` 已修复，现已可以使用win+其他键的快捷键的组合，但 `Win` 键在当前版本仍显示为 `Meta` 键（显示有问题，功能没问题）
![image](https://github.com/HIllya51/LunaTranslator/assets/52167622/6ef3bb61-2928-48e9-b1a1-38bb5fb14ffb)
退出重进后，之前设置的快捷键看不到了（又是显示有问题，功能没问题）
![image](https://github.com/HIllya51/LunaTranslator/assets/52167622/93df69e9-fd55-4572-a5e6-198b22a2eaa2)

我找到了如下代码，看起来将 `Meta` 的文本替换成了 `Win`，但好像并没有显示出来？
https://github.com/HIllya51/LunaTranslator/blob/8a0ec1114764cc296d60d787dee53e3ce3a2812e/LunaTranslator/LunaTranslator/gui/settingpage_quick.py#L66-L72

> LunaTranslator版本：2.28.2 64bit

**Comment by HIllya51** [comment]
QKeySequence在Windows上就是用Meta表示Win的
