### ISSUE TITLE
关于设置界面激活显示

### ISSUE THREAD

**Issue by Moecg** [HIllya51/LunaTranslator#41]
如果设置界面已经在桌面的非最高层，再次点击设置按钮，就不会像最小化，或者关闭后直接激活在顶层。点了设置半天没反应，才发现原来已经在桌面上被档起来了，如果能直接再跑到顶层就好了，小白不太懂，先谢谢佬了

**Comment by HIllya51** [comment]
ok

**Comment by Moecg** [comment]
> ok

刚试用了下新版，已经没问题了。谢谢大佬，这个软件体验真的挺不错，推gal去，逃~
