### ISSUE TITLE
hook到人名和对话在一起

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#410]
文本处理里面过滤XX框外内容没用，游戏对话没有框。如何处理能过滤掉人物说话时自己的名字，且不影响这个名字出现在别的对话里
![QQ截图20231002023909](https://github.com/HIllya51/LunaTranslator/assets/137600501/d1344455-1fa1-44c5-aa04-69ce3d90955c)

**Comment by dnadash** [comment]
<>里的我自己过滤掉了

**Comment by HIllya51** [comment]
![批注 2023-10-02 095554](https://github.com/HIllya51/LunaTranslator/assets/101191390/ef9a363c-bcac-4078-bebb-311330b043f7)

**Comment by dnadash** [comment]
> ![批注 2023-10-02 095554](https://user-images.githubusercontent.com/101191390/271867861-ef9a363c-bcac-4078-bebb-311330b043f7.png)

![QQ截图20231002151228](https://github.com/HIllya51/LunaTranslator/assets/137600501/40691648-ca25-4152-a403-d1baae702b42)
![QQ截图20231002151244](https://github.com/HIllya51/LunaTranslator/assets/137600501/918c699d-b771-4824-8112-cebf62b53764)
当名字出现在对话句首，也会屏蔽掉，这种是不是就没办法了。

**Comment by dnadash** [comment]
> ![批注 2023-10-02 095554](https://user-images.githubusercontent.com/101191390/271867861-ef9a363c-bcac-4078-bebb-311330b043f7.png)

当名字出现在对话框句首时，也会屏蔽掉，这种是不是没办法了
![QQ截图20231002151228](https://github.com/HIllya51/LunaTranslator/assets/137600501/fdcd2090-9ef8-4d15-8e9d-d6214d8108c1)
![QQ截图20231002151244](https://github.com/HIllya51/LunaTranslator/assets/137600501/1aed573c-779c-4cf6-ab8d-6d746b00a465)

**Comment by HIllya51** [comment]
你重新下一下，我改了点东西

**Comment by HIllya51** [comment]
然后改成：弥生\n

**Comment by dnadash** [comment]
> 然后改成：弥生\n

重下了，两个正则应该要一起用吧？我单用“\n”没效果，但是两个一起用也还是不行
![QQ截图20231002192422](https://github.com/HIllya51/LunaTranslator/assets/137600501/12ff552a-6300-40a6-b6ce-9c8f3c7f2433)
![QQ截图20231002192507](https://github.com/HIllya51/LunaTranslator/assets/137600501/b8d909e0-f268-423d-a8c7-827d92d6dde6)
![QQ截图20231002192528](https://github.com/HIllya51/LunaTranslator/assets/137600501/ef28880f-0ed2-43bd-b1ef-dc25323a2b71)
![QQ截图20231002192546](https://github.com/HIllya51/LunaTranslator/assets/137600501/134aa859-9103-4af0-84b6-4fa59fa91107)

**Comment by HIllya51** [comment]
“改成”

**Comment by dnadash** [comment]
> “改成”

OK了，这样处理好像行了，虽然没过滤掉，但是不影响翻译效果了，麻烦露娜佬了
