### ISSUE TITLE
“目标计算机积极拒绝，无法连接”

### ISSUE THREAD

**Issue by MayJIAbai** [HIllya51/LunaTranslator#411]
<img width="983" alt="屏幕截图 2023-10-05 203201" src="https://github.com/HIllya51/LunaTranslator/assets/147061140/12fdebbf-3c1f-474b-a6e3-2ebe7d82c51d">
请问这种情况怎么解决？

**Comment by MayJIAbai** [comment]
> 什么情况？为什么这么惜字如金呢？

抱歉，我也不知道具体的情况是什么。 如果我知道具体原因的话我会尝试自行解决的

**Comment by MayJIAbai** [comment]
> 什么情况？为什么这么惜字如金呢？

另外我想询问，使用本地OCR时会出现识别错误的情况，即使是重装和安装新的OCR也没用，去请问这种情况如何解决？

**Comment by HIllya51** [comment]
> <img alt="屏幕截图 2023-10-05 203201" width="983" src="https://user-images.githubusercontent.com/147061140/272903152-12fdebbf-3c1f-474b-a6e3-2ebe7d82c51d.png"> 请问这种情况怎么解决？

你在用yakuyaku的离线翻译？那你去手动运行run.bat，还不行就没救换别的用。


> 另外我想询问，使用本地OCR时会出现识别错误的情况，即使是重装和安装新的OCR也没用，去请问这种情况如何解决？

看不懂你在说什么
