### ISSUE TITLE
关于“预翻译”功能的改进

### ISSUE THREAD

**Issue by TXT2GAM** [HIllya51/LunaTranslator#412]
希望在预翻译功能下新增一个选项：“临时替代翻译”。
如果出现报错`UnboundLocalError local variable 'savet' referenced before assignment`（预翻译字典中找不到对应游戏文本），则启用用户提前设定的其它翻译接口进行临时的替代翻译；如果无报错则不启用。

**Comment by HIllya51** [comment]
这有什么意义吗？直接开着要替代成的那个翻译不就行了

**Comment by xylyyy** [comment]
> 这有什么意义吗？直接开着要替代成的那个翻译不就行了

这样json文件不报错不就会同时显示两个翻译结果而影响美观吗？有的游戏部分文本在一处文本时会先显示第一行，点击之后再显示第二行，但是翻译器在游戏显示第二行时会同时读取一二两行的内容，导致json文件找不到对应文本，这样的话感觉这个功能还是挺有用的，希望作者大大考虑下
