### ISSUE TITLE
nation & lather 字母會改變

### ISSUE THREAD

**Issue by JWanShen** [HIllya51/LunaTranslator#414]
OCR擷取 lathe & ather 顯示的原文會正常, 但是擷取lather會變成father。
OCR擷取 na & ation 顯示的原文會正常, 但是擷取nat會變成not、nation會變成notion。
請問這能修改正常嗎?

**Comment by HIllya51** [comment]
![批注 2023-10-10 100540](https://github.com/HIllya51/LunaTranslator/assets/101191390/a98301a3-4144-480b-99f0-f69bf1aeef1c)
把这玩意儿关了

**Comment by JWanShen** [comment]
感謝您耐心的解答!
