### ISSUE TITLE
v2.26.3之后的版本无法hook大部分日区游戏

### ISSUE THREAD

**Issue by zzwbdz** [HIllya51/LunaTranslator#418]
![截图](https://github.com/HIllya51/LunaTranslator/assets/47297257/c37b28a2-df3a-4d2b-a368-ae05df8764ba)

v2.28.x版均无法hook到完整句子，测试对象为大部分需转日区运行的galgame，如《樱之诗》《素晴日》《夜行侦探重制版A》《desire重制版A》

目前只能用v2.26.3版提取到特殊码再注入到最新版本中，才能提取到完整文本。

**Comment by HIllya51** [comment]
感谢提醒，已修正。
