### ISSUE TITLE
软件在已保存的游戏经常奔溃

### ISSUE THREAD

**Issue by qstdnx** [HIllya51/LunaTranslator#419]
首先感谢作者大大的无私奉献。
软件版本：2.28.2
windows版本：win10  22H2 (操作系统内部版本 19045.3271)
问题描述：从开始用luna的时候就一直存在的问题，期间重装过一次系统，问题依旧，基本可以排除系统问题，软件也重新下载过。我在已保存的游戏界面整理游戏时经常崩溃溃，而且崩溃后之前的操作会全部重置，就好像软件只有在关闭时才会保存一次。最常触发奔溃的情况是打开目录来定位游戏启动程序之后。当我移动游戏后，需要批量重新定位，这个bug确实令人头疼。
如果需要其他信息或者无法复现请告诉我
复现视频，点击预览即可查看
https://pan.huang1111.cn/s/VXPnud

**Comment by HIllya51** [comment]
？你这视频是个什么鬼，什么都看不见

**Comment by qstdnx** [comment]
> ？你这视频是个什么鬼，什么都看不见

不好意思，因为封面很多18x内容所以模糊了，操作就是找到一个位置改动的游戏（我标红的），点击游戏设置，点修改路径小齿轮，重新寻找位置后过一会儿游戏就崩溃了

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/releases/download/v2.28.1/LunaTranslator_x86_debug.zip
你用这个debug版测试一下，把错误截图给我看看。

**Comment by qstdnx** [comment]
> https://github.com/HIllya51/LunaTranslator/releases/download/v2.28.1/LunaTranslator_x86_debug.zip 你用这个debug版测试一下，把错误截图给我看看。
我试了几下，你给的debug版本暂时没有出现崩溃现象，怎么把已保存游戏的数据迁移到这个版本，我看下游戏多了会不会出问题。

**Comment by HIllya51** [comment]
直接复制userconfig文件夹

**Comment by qstdnx** [comment]
目前没找到稳定触发的方法，试用debug版本一直没有崩溃，但是用正常版有崩溃，就是触发方式很混沌。大部分时候添加游戏都正常，偶尔添加游戏会崩溃。可能要一直用debug版本才能触发。

**Comment by HIllya51** [comment]
那就没办法咯，等你debug触发了给我说吧。。。
