### ISSUE TITLE
有没有办法让语音合成时，不进行女主文本的自动朗读？

### ISSUE THREAD

**Issue by fanglangxinghai** [HIllya51/LunaTranslator#420]
当自动朗读时，当女主文本时，就会和游戏里的女主声音重叠的情况。希望有一个功能可以，当出现指定女主名字的对话时，语音合成功能就不会自动朗读。

**Comment by HIllya51** [comment]
曾经可以，后来砍了。。

**Comment by fanglangxinghai** [comment]
> 曾经可以，后来砍了。。

啊？为什么？是会有bug吗？

**Comment by HIllya51** [comment]
由于问这个问题的人有点多，故恢复此功能。
HOOK设置中选择区分人名和文本后，在选择文本窗口中设置对应的项目为人名，然后在游戏设置中添加禁止朗读的文本即可。

**Comment by fanglangxinghai** [comment]
> 由于问这个问题的人有点多，故恢复此功能。 HOOK设置中选择区分人名和文本后，在选择文本窗口中设置对应的项目为人名，然后在游戏设置中添加禁止朗读的文本即可。

确实是能用了，但是如果人名和文本混合在一条里面怎么办？没有单独的人名的项目。比如某一条项目：  美香「おはよう」

**Comment by HIllya51** [comment]
那没办法咯
