### ISSUE TITLE
新版本的額外行間距設定

### ISSUE THREAD

**Issue by a73420521** [HIllya51/LunaTranslator#421]
請問新版本的「額外行間距」要設定多少才不會和原文黏在一起？預設為0的情況下會黏在一起，我自己調不是分的太開就是沒變化，找不到合適的數字
舊版↓
![2](https://github.com/HIllya51/LunaTranslator/assets/87113124/b37276df-429b-4610-90b3-2414a42ac69b)
新版↓
![0](https://github.com/HIllya51/LunaTranslator/assets/87113124/f1a1c0b4-26d5-47b2-b3a6-1dd5660b81b5)

**Comment by HIllya51** [comment]
把userconfig打包发给我看一下

**Comment by a73420521** [comment]
> 把userconfig打包发给我看一下

[userconfig.zip](https://github.com/HIllya51/LunaTranslator/files/13029853/userconfig.zip)

**Comment by HIllya51** [comment]
![批注 2023-10-18 224128](https://github.com/HIllya51/LunaTranslator/assets/101191390/2c6a5de8-30e2-4679-b229-b75f1faf96ac)
啊？测试没问题啊
而且为什么你这个截图里每行间距不一样，甚至会错位啊，不可能啊，理解不能。。。

**Comment by HIllya51** [comment]
你操作系统什么版本？

**Comment by HIllya51** [comment]
win7上测了也没有问题。
你用的不是最新版本啊，看了下你的config里面缺少很多相关配置项

**Comment by a73420521** [comment]
> win7上测了也没有问题。 你用的不是最新版本啊，看了下你的config里面缺少很多相关配置项

目前用的版本是2.26.3，有下載最新版本重新設定，但還是一樣，但將原文字體及譯文字體換成標楷體後就不會黏在一起了，感覺是新細明體的問題

**Comment by HIllya51** [comment]
你把你用的字体的ttf文件发我一下

**Comment by a73420521** [comment]
> 你把你用的字体的ttf文件发我一下
電腦2天前才剛重灌好，內部字體都是預設沒動過，平常使用的字體為「ＭＳ 明朝」，系統是Win7旗艦版，地區及語言的設定如下
![1](https://github.com/HIllya51/LunaTranslator/assets/87113124/8fff24f1-cc81-4b74-8877-2b1197bf2021)
![2](https://github.com/HIllya51/LunaTranslator/assets/87113124/87bac1ed-227a-499f-8a0b-841df09f0c58)
![3](https://github.com/HIllya51/LunaTranslator/assets/87113124/ae122121-ccea-4276-b386-ebb7ea8144ec)

[msmincho.zip](https://github.com/HIllya51/LunaTranslator/files/13037452/msmincho.zip)

**Comment by HIllya51** [comment]
已修
