### ISSUE TITLE
[Feature Request] 希望专有名词的每个条目增加开启/关闭状态

### ISSUE THREAD

**Issue by Ptilopsis01** [HIllya51/LunaTranslator#423]
如题，希望专有名词的条目可以设置是否启用，最好能批量设置

**Comment by HIllya51** [comment]
这个会破坏兼容性，而且本来就能根据不同游戏判断是否生效，功能差别太小，有点重复了。

**Comment by Ptilopsis01** [comment]
> 这个会破坏兼容性，而且本来就能根据不同游戏判断是否生效，功能差别太小，有点重复了。

这个词条有存储在本地文件里吗，我想手动批量改下

**Comment by HIllya51** [comment]
userconfig/noundictconfig.json

**Comment by Ptilopsis01** [comment]
> userconfig/noundictconfig.json

OK谢谢
