### ISSUE TITLE
[Feature Request] 鼠标离开翻译窗口时自动隐藏图标

### ISSUE THREAD

**Issue by Ptilopsis01** [HIllya51/LunaTranslator#424]
如题，有时候翻译窗口上的图标对画面会有一定的遮挡，希望在不操作时可以自动隐藏

**Comment by HIllya51** [comment]
![无标题](https://github.com/HIllya51/LunaTranslator/assets/101191390/94768a18-9474-41b5-b5af-15036e7a94a8)

呃。本来就可以。。。

**Comment by Ptilopsis01** [comment]
> ![无标题](https://user-images.githubusercontent.com/101191390/277389638-94768a18-9474-41b5-b5af-15036e7a94a8.png)
> 
> 呃。本来就可以。。。

哦草我一直开着的，没注意到
感谢
