### ISSUE TITLE
hook导致游戏闪退游戏

### ISSUE THREAD

**Issue by AdarkYesha** [HIllya51/LunaTranslator#426]
如题，hook游戏Hyper→Highspeed→Genius 时，会导致游戏闪退。

**Comment by HIllya51** [comment]
？
![批注 2023-10-25 004515](https://github.com/HIllya51/LunaTranslator/assets/101191390/5463c427-2011-4225-aee5-1f8c83fe6412)

**Comment by AdarkYesha** [comment]
> ？ ![批注 2023-10-25 004515](https://user-images.githubusercontent.com/101191390/277742023-5463c427-2011-4225-aee5-1f8c83fe6412.png)

好吧。突然发现我太久没更新了。用最新版hook没闪退。
