### ISSUE TITLE
ferq: 点击原文将词汇复制到剪贴板

### ISSUE THREAD

**Issue by blucca** [HIllya51/LunaTranslator#429]
希望有一个点击原文中的词汇后可以将将词汇复制到剪贴板的功能

**Comment by HIllya51** [comment]
意义不明

**Comment by HIllya51** [comment]
> 现在不是有一个点击原文查词的功能吗，像那个一样，点击词汇后自动把词汇复制到剪贴板里

完全可以手动复制，用处太小了，不值得

> 突然发现把点击原文查词关了还是能点击原文打开查词面板，这个选项是不是没有用了…

有用。

**Comment by HIllya51** [comment]
顶多从2秒缩成1秒
