### ISSUE TITLE
日文系统软件字体显示异常

### ISSUE THREAD

**Issue by Laniaidea** [HIllya51/LunaTranslator#43]
个人偏好直接把非Unicode语言改成日文系统 导致Luna的字体显示异常
![屏幕截图 2022-11-04 232419](https://user-images.githubusercontent.com/84361865/200012688-0218cb52-5de3-41e1-96d6-45e32a64b4b1.png)

**Comment by HIllya51** [comment]
可能是日语系统缺少微软雅黑字体

**Comment by Laniaidea** [comment]
> 可能是日语系统缺少微软雅黑字体

继续使用日文系统的话有解决方法吗

**Comment by HIllya51** [comment]
从网上找下字体文件安装一下就行了。。。而且这也不影响使用啊又不是看不懂。。。

**Comment by Laniaidea** [comment]
> 从网上找下字体文件安装一下就行了。。。而且这也不影响使用啊又不是看不懂。。。

 试了下 ，找微软雅黑安装提示系统自带了微软雅黑，非Unicode程序为日文的系统字体还是有主楼的问题（其它系统语言没测），比较影响观感

**Comment by HIllya51** [comment]
之后调一下让他可以选择设置界面字体。

**Comment by HIllya51** [comment]
可以自己选择界面的字体了。你试试看。

**Comment by Laniaidea** [comment]
> 可以自己选择界面的字体了。你试试看。

已解决，感谢。
