### ISSUE TITLE
建议gpt翻译接口加入流式响应功能

### ISSUE THREAD

**Issue by TXT2GAM** [HIllya51/LunaTranslator#431]
gpt的回复速度慢，但是流式响应可以实现每生成一个字就立刻显示，而不是生成全部内容再一起显示。是一个非常有用的功能。

**Comment by HIllya51** [comment]
太麻烦，懒得弄。

**Comment by TXT2GAM** [comment]
关于流式输出的api官方文档里面有写，并不复杂: [这里](https://cookbook.openai.com/examples/how_to_stream_completions)
我也写了一个简洁的测试脚本，填入自己的key和接口（如果用中转或自己搭建的）就可以使用: [这里](https://gist.github.com/TXT2GAM/a2062a3caa89a547d1bbd653142caf46)
对于1106这种快速新模型基本可以做到无延迟回答。

可能还需要调整Translator文本显示部分相关的代码，设计这方面我怕自己改了会报错。

**Comment by HIllya51** [comment]
刚刚做了流式更新的支持，兼容普通翻译（不过目前只能同时有一个流式的翻译否则会错版，不过一般也没人开好几个吧hh）
但我没有openai账号，所以如果你有兴趣的话，可以看一下。只需稍微修改增加流式接口的访问就行，例如stream=self.config["stream"]，然后：
```
import time
from translator.basetranslator import basetrans
class TS(basetrans): 
    def translate(self,content):  
        if len(content)%2==0:   #if self.config["stream"]==False:   #兼容流式和普通
            yield content   #原版return改成yield
            return
        else:
            for c in content:
                print(c)
                time.sleep(1)
                yield c+"???"   #stream
```

**Comment by mrl998** [comment]
v2.37.4使用sakura翻译器，勾选流式输出后没有效果，依然是翻完一句输出一次

**Comment by HIllya51** [comment]
我只是做了框架上支持流式输出，但是还没有适配它的api（因为我搞了半天环境也没配好），我看你会写代码所以来问一下你能不能帮忙搞一下，这样的。😂

**Comment by HIllya51** [comment]
> v2.37.4使用sakura翻译器，勾选流式输出后没有效果，依然是翻完一句输出一次


我只是做了框架上支持流式输出，但是还没有适配它的api（因为我搞了半天环境也没配好），我看他会写代码所以来问一下你能不能帮忙搞一下，这样的。😂
