### ISSUE TITLE
能否增加关键词触发屏蔽语音模式> 由于问这个问题的人有点多，故恢复此功能。 HOOK设置中选择区分人名和文本后，在选择文本窗口中设置对应的项目为人名，然后在游戏设置中添加禁止朗读的文本即可。

### ISSUE THREAD

**Issue by zzwbdz** [HIllya51/LunaTranslator#432]
一点思路，如果太麻烦的话close即可

方法1：星号正则表达式屏蔽，只要”关键字“开头就触发，与句子后面内容无关：

人名1*|人名2*|

方法2：语音设置界面增加功能：用户输入关键词，分号隔开，hook到设定的关键词不自动发音

              > 由于问这个问题的人有点多，故恢复此功能。 HOOK设置中选择区分人名和文本后，在选择文本窗口中设置对应的项目为人名，然后在游戏设置中添加禁止朗读的文本即可。

确实是能用了，但是如果人名和文本混合在一条里面怎么办？没有单独的人名的项目。比如某一条项目：  美香「おはよう」

_Originally posted by @fanglangxinghai in https://github.com/HIllya51/LunaTranslator/issues/420#issuecomment-1763462721_

**Comment by HIllya51** [comment]
已修正（按方法1）

**Comment by fanglangxinghai** [comment]
这个方法1不知道为什么对我没用，设置了“人名1*|人名2*|”，依旧会读出来这个句子。（其实我在刚一开始就尝试过这个方法。。）而且就算这个方法能用，其实还有一个问题，就是tts在读男性对话时，每次都会将男性的名字也念出来。

所以我现在想了另一个办法。（这个方法的问题是女主的对话不会被识别，不会被翻译）
1.进入设置中的【文本处理】
2.排序，让【正则表达式替换】位于【过滤「」以外的字符】上面
3.【正则表达式替换】，“原文内容”输入：人名「.*?」，“替换为”不输入任何内容。（如果有多个女主，则添加行，重复这个操作）
4.打开【过滤「」以外的字符】

![Uploading 2.jpg…]()

**Comment by zzwbdz** [comment]
> 这个方法1不知道为什么对我没用，设置了“人名1*|人名2*|”，依旧会读出来这个句子。（其实我在刚一开始就尝试过这个方法。。）而且就算这个方法能用，其实还有一个问题，就是tts在读男性对话时，每次都会将男性的名字也念出来。
> 
> 所以我现在想了另一个办法。（这个方法的问题是女主的对话不会被识别，不会被翻译） 1.进入设置中的【文本处理】 2.排序，让【正则表达式替换】位于【过滤「」以外的字符】上面 3.【正则表达式替换】，“原文内容”输入：人名「.*?」，“替换为”不输入任何内容。（如果有多个女主，则添加行，重复这个操作） 4.打开【过滤「」以外的字符】

已经修复了，但不用自己加星号，《最后的现在》实测，像我这样加入“沙也加|笛子|章二|あずさ|葉子|紅緒|千鳥”，主要角色不再触发ai语音了。
![](https://github.com/HIllya51/LunaTranslator/assets/47297257/532dd86a-9ad0-48b3-b2a1-15e97cbd71db)

**Comment by fanglangxinghai** [comment]
@zzwbdz 
非常感谢，已经能完美运行了。
