### ISSUE TITLE
Yandex Translate 

### ISSUE THREAD

**Issue by allebar** [HIllya51/LunaTranslator#434]
In some novellas words stick together during the transition to a new line, but the yandex translator automatically corrects this, i.e. the text in the browser itself looks corrected, but in the program window the translation is different, as if there was no automatic correction. Is there any possibility to fix this? 
![2023-11-11_22-14-11](https://github.com/HIllya51/LunaTranslator/assets/75815491/26147896-a045-4b8e-b63e-c59cd4b7f760)

**Comment by zzwbdz** [comment]
文本处理-过滤换行符✔
