### ISSUE TITLE
老板能否添加腾讯ocr跟图片翻译

### ISSUE THREAD

**Issue by 2ooo18** [HIllya51/LunaTranslator#436]

**Comment by HIllya51** [comment]
腾讯有图片翻译吗？
你给我个密钥做测试，我不想注册。

**Comment by 2ooo18** [comment]
AKIDAC5nR0QfmokcRExbFqLgpnlbEmAQeicO
fAc5nNzUwDF4gOuEMJRYikw7JV0TtESl
这是图片翻译

恍兮惚兮 ***@***.***> 于2023年11月15日周三 17:03写道：
