### ISSUE TITLE
火山跟百度ocr识别漫画日文是从左到右顺序。但是日本漫画应该是日文是从右到左读法顺序，

### ISSUE THREAD

**Issue by 2ooo18** [HIllya51/LunaTranslator#438]

**Comment by HIllya51** [comment]
百度OCR使用含位置版接口

**Comment by 2ooo18** [comment]
> 百度OCR使用含位置版本接口

火山ocr如何更正？

**Comment by HIllya51** [comment]
暂不支持

**Comment by HIllya51** [comment]
> > 百度OCR使用含位置版本接口
> 
> 火山ocr如何更正？

没API，做不了。

**Comment by 2ooo18** [comment]
> > > 百度OCR使用含位置版本接口
> > 
> > 
> > 火山ocr如何更正？
> 
> 没API，做不了。你给我个钥匙我改一下。

你邮箱多少

**Comment by HIllya51** [comment]
你直接comment完过一会儿删了就行了

**Comment by 2ooo18** [comment]
> 你直接comment完过一会儿删了就行了

AKLTYTUxZWM5MWUxNGI2NDQyZTk1YWI1ZmVmYzEzMDIzNTQ
WmpObFptVTFPVGxqTWpVMk5HTXdaamxrWm1WbU5XUTNabVEwTnpWaVptVQ==
