### ISSUE TITLE
希望加个文本强制合并的功能

### ISSUE THREAD

**Issue by yui799** [HIllya51/LunaTranslator#44]
又来麻烦大佬了，就是有的游戏原游戏文本以句号或逗号分成两行，ocr提取出的文字是两行，翻译也是两行，看起来很不舒服，能不能加一个小功能让剪切板的文字能强制合并成一行，这样翻译也能变成一整行。拜托了。

**Comment by HIllya51** [comment]
设置-翻译优化-过滤换行符。

**Comment by yui799** [comment]
成功了，谢谢大佬
