### ISSUE TITLE
mT5翻译器int8量化权重分发

### ISSUE THREAD

**Issue by chaihahaha** [HIllya51/LunaTranslator#440]
我把huggingface上的larryvrh/mt5-translation-ja_zh量化为了int8精度的onnx模型权重，请您考虑在后续测试和下载链接分发时使用int8量化模型而不是原模型。

我按您的修正代码把整个mt5翻译器目录打包为了7zip压缩包（~~其中ortmt5.exe和onnxruntime.dll是64位的，32位可能需要重新编译~~  已另外编译为32位：[ortmt5_x86_win32.tar.gz](https://github.com/HIllya51/LunaTranslator/files/13399975/ortmt5_x86_win32.tar.gz)），上传到了夸克网盘（大小为820MB），下载链接如下：

「mt5-translator.7z」
/!f1ee32P48t!:/
链接：https://pan.quark.cn/s/5510aeaaef9b

通过百度网盘分享的文件：
链接:https://pan.baidu.com/s/1cPjD7l6nhYI1e2Ev34fCqA?pwd=59c6 
提取码:59c6

阿里云盘：
 https://www.aliyundrive.com/t/QFQqrvoTW1Rtus4e5DWg

**Comment by chaihahaha** [comment]
win32的ortmt5.exe我编译好了（见附件），也许在分发时可以把win32的ortmt5.exe和win64的分成两个不同文件夹存放？
[ortmt5_x86_win32.tar.gz](https://github.com/HIllya51/LunaTranslator/files/13399975/ortmt5_x86_win32.tar.gz)

**Comment by chaihahaha** [comment]
刚才测试了一下，win32编译后的程序不能直接使用较大的onnx权重文件，为了通用性，必须在保存onnx权重文件时打开`save_as_external_data`选项，随后我会重新打包，并修改网盘链接。

**Comment by HIllya51** [comment]
就算能加载有啥用？得慢成啥了？

**Comment by HIllya51** [comment]
😬别给我发这种劣质网盘好吗，百度我都不是很想用。

**Comment by HIllya51** [comment]
你可以自己开个release存资源，然后改掉[https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/files/defaultconfig/static_data.json](https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/files/defaultconfig/static_data.json)里的对应下载链接然后PR，我懒得下载测试了

**Comment by chaihahaha** [comment]
好的，我传到谷歌网盘吧，里面包含了量化后的权重，x32的二进制和x64的二进制。因为我发现量化后推理速度还挺快的，就想着换成这个权重。

**Comment by chaihahaha** [comment]
> 你可以自己开个release存资源，然后改掉[https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/files/defaultconfig/static_data.json](https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/files/defaultconfig/static_data.json)里的对应下载链接然后PR，我懒得下载测试了

好的，多谢。

**Comment by chaihahaha** [comment]
我试了在github release页面里上传，但是一直失败，请问我可以先用网盘给你一份好吗？之后我找个网络好点的地方，在github desktop里上传一下看看，估计要花点时间。

阿里云盘：

https://www.aliyundrive.com/t/zSeMYa2RFB5ZhJxGWsJe
