### ISSUE TITLE
源文本出现部分字符时会出现显示问题

### ISSUE THREAD

**Issue by Lain1984** [HIllya51/LunaTranslator#443]
目前发现的有句子中任何地方出现"——"和句子末尾出现"……"的两种符号会导致这样错位显示，或者字整体变得非常小
![Quicker_20231122_012225](https://github.com/HIllya51/LunaTranslator/assets/97153006/0c680f6c-d5de-4c86-bac5-69190883b533)

**Comment by HIllya51** [comment]
把html标签过滤掉
