### ISSUE TITLE
有时候翻译器设置无法保存

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#446]
有时候添加一些关键词，第二天开机就没了，我知道得用管理员模式打开，我一直这样的，不过这情况不多发，但偶尔来一次也挺烦的（不知道会不会和我挂着梯子的情况有关）。请问露娜佬我能不能备份当天的相关翻译器文件，如果第二天发现一些添加的设置没了，替换文件？如果可行，那得备份哪些文件？

**Comment by dnadash** [comment]
不知道会不会和我挂着梯子的情况有关

**Comment by HIllya51** [comment]
userconfig
