### ISSUE TITLE
您好，哪个文件是记录自定义的专有名词的文件呢？

### ISSUE THREAD

**Issue by BigZhangHui** [HIllya51/LunaTranslator#449]
您好，哪个文件是记录自定义的专有名词的文件呢？有时候想要全新安装应用或者在另一台电脑使用，我还想使用之前自定义的专有名词。还有在玩神のラプソディ这个游戏时，用软件自带的Locale Emulator打开游戏时，点击load game游戏会崩溃。但用电脑装的Locale Emulator打开游戏，点击load game并不会崩溃。lunaTranslator用的是2.29.6版本。

**Comment by HIllya51** [comment]
> 您好，哪个文件是记录自定义的专有名词的文件呢？有时候想要全新安装应用或者在另一台电脑使用，我还想使用之前自定义的专有名词。

userconfig/noundictconfig.json

>还有在玩神のラプソディ这个游戏时，用软件自带的Locale Emulator打开游戏时，点击load game游戏会崩溃。但用电脑装的Locale Emulator打开游戏，点击load game并不会崩溃。lunaTranslator用的是2.29.6版本。

给我资源测试。

**Comment by BigZhangHui** [comment]
好的，了解。
