### ISSUE TITLE
request.expecting.JSONDecodeError value line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by allebar** [HIllya51/LunaTranslator#450]
This error occurs when using the api key 'one api' for gpt chat

**Comment by HIllya51** [comment]
I guess it might be like xxx/chat/v1

**Comment by allebar** [comment]
> I guess it might be like xxx/chat/v1

I tried, but the same error occurs

Can you please write step by step what needs to be done.

**Comment by allebar** [comment]
> > I guess it might be like xxx/chat/v1
> 
> I tried, but the same error occurs
> 
> Can you please write step by step what needs to be done.

Now everything has started working, strangely.

**Comment by HIllya51** [comment]
can you give me your api key to let me test it?

**Comment by allebar** [comment]
> can you give me your api key to let me test it?

I tried the same thing, but only in a different version of lunatranslation, after which everything started working. Here's the key - sk-LoYSVwkDpt6BWlTv9e06F2100cD745929205A88cCdF856C6

**Comment by allebar** [comment]
> can you give me your api key to let me test it?

I forgot to write that I changed the api address to this one "https://neuroapi/chat/v1 "

**Comment by HIllya51** [comment]
> > can you give me your api key to let me test it?
> 
> I forgot to write that I changed the api address to this one "https://neuroapi/chat/v1 "

I don't understand what you mean

**Comment by HIllya51** [comment]
where did you find "openai.justsong.cn"? It should have a document.

**Comment by HIllya51** [comment]
I found the url actually is "https://openai.justsong.cn/v1"
