### ISSUE TITLE
火山ocr TypeEeero noneType object is not subacriptable

### ISSUE THREAD

**Issue by 2ooo18** [HIllya51/LunaTranslator#453]

**Comment by HIllya51** [comment]
把问题描述清楚。

**Comment by HIllya51** [comment]
{'ResponseMetadata': {'RequestId': '20231204204223FC9BF9484286CA466CF6', 'Action': 'MultiLanguageOCR', 'Version': '2022-08-31', 'Service': 'cv', 'Region': 'cn-north-1', 'Error': {'CodeN': 100013, 'Code': 'AccessDenied', 'Message': 'User is not authorized to perform: cv:MultiLanguageOCR on resource: '}}}

你这个密钥根本没有访问权限。

**Comment by 2ooo18** [comment]
你在试一试
