### ISSUE TITLE
內嵌功能失效

### ISSUE THREAD

**Issue by y49711** [HIllya51/LunaTranslator#455]
新增的內嵌功能一開始可以正常使用
突然就都不能了 重開等方法都無效 清掉文本擷取重用也不行
使用的遊戲是ANIM team MM的壁聲3

內嵌功能真是很神奇 超好用低 突然不能用 難受

**Comment by wycstc353** [comment]
> 测试并没有失效，截图看一下？

 内嵌功能咋使用的啊，感觉没有开关啊

**Comment by HIllya51** [comment]
> > 测试并没有失效，截图看一下？
> 
> 内嵌功能咋使用的啊，感觉没有开关啊
就HOOK，如果支持内容就有这个按钮，没有就不支持。
![批注 2023-12-11 205709](https://github.com/HIllya51/LunaTranslator/assets/101191390/438a9db5-85f6-42f9-b5f4-727ff5752587)
![批注 2023-12-11 205638](https://github.com/HIllya51/LunaTranslator/assets/101191390/0075840b-c4bf-4f0c-bcc1-48cfedac6271)
