### ISSUE TITLE
文本处理 -> 过滤换行符失效

### ISSUE THREAD

**Issue by JetpackPrime** [HIllya51/LunaTranslator#457]
如题，新版本的过滤换行符处理好像失效了，至少在我这边是这样
![RKB}D {BR`T(RFYM%R3%%BV](https://github.com/HIllya51/LunaTranslator/assets/118692280/255f1c4a-7096-42f5-8adc-8072fd3c777f)

**Comment by HIllya51** [comment]
已修正，感谢提醒。
