### ISSUE TITLE
一句话结尾的一个表情独占了一行

### ISSUE THREAD

**Issue by 31653526619211a** [HIllya51/LunaTranslator#458]
![スクリーンショット 2023-12-10 184027](https://github.com/HIllya51/LunaTranslator/assets/118968217/fc5b433a-ee78-4f3b-afc5-a3b56a7c2080)
![スクリーンショット 2023-12-10 184249](https://github.com/HIllya51/LunaTranslator/assets/118968217/5705d9d8-020a-4ac8-ac64-7c182e9b6cc7)

**Comment by HIllya51** [comment]
过滤掉不就行了😴

**Comment by 31653526619211a** [comment]
![スクリーンショット 2023-12-10 194836](https://github.com/HIllya51/LunaTranslator/assets/118968217/8c9cda2a-85d1-4605-bce6-8f6c8a779bae)


> 过滤掉不就行了😴


![image](https://github.com/HIllya51/LunaTranslator/assets/118968217/4a42fdf5-b194-4603-94c8-49e8d4c1b46c)
