### ISSUE TITLE
你好 關於 Tesseract 的使用方式

### ISSUE THREAD

**Issue by a6070160701** [HIllya51/LunaTranslator#459]
我知道作者很常說它的功能不是很好
不過我還是想盡量嘗試看看各種工具用起來的感覺
因為其他大陸的我都沒辦法註冊使用
我目前最常用的還是ocrspace的免費版本
以上為題外話

我想請教Tesseract該怎麼使用才對
我點入此連結後
https://github.com/UB-Mannheim/tesseract/wiki
下載
[tesseract-ocr-w64-setup-5.3.3.20231005.exe](https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-5.3.3.20231005.exe) (64 bit)
之後把Luna的選擇檔案導向到上面那個下載後安裝後的tesseract.exe
語言選擇英文
附加參數則保持為--psm 6
沒有改動

不過好像沒有功用
想問問是不是我哪裡操作有問題

**Comment by HIllya51** [comment]
如果正常的话这里会有已安装的语言显示
![批注 2023-12-10 195404](https://github.com/HIllya51/LunaTranslator/assets/101191390/10b8334c-0e27-4ee3-87af-26741c32982a)

如果没有的话，测试"C:/Program Files/Tesseract-OCR/tesseract.exe" --list-langs看一下有没有输出
![批注 2023-12-10 195612](https://github.com/HIllya51/LunaTranslator/assets/101191390/b98fcb97-86f3-45f9-9228-3e9943e68373)

**Comment by a6070160701** [comment]
![image](https://github.com/HIllya51/LunaTranslator/assets/122324759/e1e1d3a4-92c9-4c69-8c6f-20252596c852)

![image](https://github.com/HIllya51/LunaTranslator/assets/122324759/edaaff34-02b5-4a4a-ab92-e82f3ea743a0)

我自己這邊是顯示這個樣子
因為我目前只需要eng
所以目前沒jpn也沒關係
語言怎麼添加jpn我可能之後再問問

主要是我怕的是因為我不會安裝tesseract
才導致我沒辦法使用...

**Comment by HIllya51** [comment]
我修改了代码，你重下下最新的试试

**Comment by a6070160701** [comment]
> 我修改了代码，你重下下最新的试试

可以了!!
非常感謝你的修復

另外想請問一下
我剛剛去找了怎麼加其他語言進去
然後找到了這個
https://github.com/UB-Mannheim/tesseract/wiki/Install-additional-language-and-script-models

然後在下面這連結下了日文的jpn.traineddata丟到C:\Tesseract-OCR\tessdata這資料夾
https://tesseract-ocr.github.io/tessdoc/Data-Files

之後在LUNA內選擇日文
使用新加的日文
出現以下錯誤
![image](https://github.com/HIllya51/LunaTranslator/assets/122324759/cf2c16e3-ed39-418c-b4ea-e46d1b0ead17)

是參數需要修改成什麼嗎?

**Comment by HIllya51** [comment]
不知道。肯定是你没加对。我是安装的时候就安了日语的。

**Comment by a6070160701** [comment]
> 不知道。肯定是你没加对。我是安装的时候就安了日语的。

好的.那我再研究研究看看是不是安裝時有問題或者下載的地方有問題
感謝你的修復

**Comment by a6070160701** [comment]
> 不知道。肯定是你没加对。我是安装的时候就安了日语的。

可以了
再次感謝你
聽到你說是安裝時就裝了
才發現安裝時有附加語言可以選
我用另外頁面下的語言包可能是舊版本使用的語言包
