### ISSUE TITLE
关于窗口调整相关功能的问题反馈及功能建议

### ISSUE THREAD

**Issue by EXBJAN** [HIllya51/LunaTranslator#46]
首先感谢大佬日夜更新迭代，生产队的驴都没你勤快。实在辛苦！

**问题反馈**

- 窗口调整无效，游戏窗口大小不随调整改变
  这类游戏一般自带全屏功能都是通过更改电脑分辨率实现的，随各自不同，有的从屏幕左上角改分辨率，比如elf加的游戏使用翻译器全屏则会如下图所示，且会出现与使用游戏自带全屏功能同样的问题，导致键盘按键失效。
<img width="1440" alt="屏幕截图 2022-11-05 131939" src="https://user-images.githubusercontent.com/117036098/200105723-4f13aacf-1b4d-45c7-aa27-525652f5f6b5.png">
  另一种是从屏幕右下角改变屏幕分辨率，比如下面这个在使用翻译器的全屏后只有右下角那部分是真的，左上角那两个都是残留
<img width="1440" alt="屏幕截图 2022-11-05 133623" src="https://user-images.githubusercontent.com/117036098/200105848-e8261376-47e3-49e7-824d-1e713729e76d.png">
 还有樱花社的游戏，这是最近两个月出的游戏，其游戏系统好多年都是这个，只是增加了更多高分辨率的窗口模式选项，这里为突出对比，我选择了其最低分辨率使用翻译器自带的全屏功能，如下图。
<img width="1440" alt="屏幕截图 2022-11-05 134208" src="https://user-images.githubusercontent.com/117036098/200106024-86484fab-69a4-48ee-be66-e13f19ff87a9.png">

- 窗口调整有效，但会引发其他问题
  比如anim家的游戏，其自带全屏也是通过修改电脑分辨率实现。使用翻译器自由调整窗口功能可将画面随意拉伸，使用翻译器全屏后立绘产生明显锯齿，且均会导致游戏选项触发位置与画面不一致，无法操作。如下图
 调整前
<img width="1136" alt="屏幕截图 2022-11-05 133318" src="https://user-images.githubusercontent.com/117036098/200106410-8eaebcce-d40c-44f2-bb0f-17900e511436.png">
翻译器全屏后（画面产生了异常拉伸和立绘锯齿，且下面的游戏选项均选不到）
<img width="1440" alt="屏幕截图 2022-11-05 133426" src="https://user-images.githubusercontent.com/117036098/200106436-58fe40d7-af51-411b-bbfa-4959f35d12e0.png">

- 翻译器的窗口全屏触发了游戏内的全屏功能，但不能通过该功能使游戏回到窗口模式
 比如mink ego的部分游戏，其内置全屏并不更改电脑分辨率而是（极为先进的）缩放立绘和cg。

- 大部分游戏窗口比例均有个最小尺寸，且窗口调整画面比例依然保持不变，比这个尺寸更小的调整也只是对画面进行了裁切。但有部分游戏会对画面造成拉伸，如下图所示
<img width="731" alt="屏幕截图 2022-11-05 134753" src="https://user-images.githubusercontent.com/117036098/200107016-d84b8941-108b-4841-ae3a-d02fd1c1722e.png">
<img width="1329" alt="屏幕截图 2022-11-05 145356" src="https://user-images.githubusercontent.com/117036098/200107049-a5c5d4b7-3f80-4205-8211-d0abbaa111cb.png">

稍微总结一下，我觉得以上问题也只是这个功能使用体验中诸多bug的一部分而已，毕竟galgame千千万，总还会有别的问题。
待会发我的一点点建议，

**Comment by EXBJAN** [comment]
**功能建议**

- 建议窗口自由调整功能增加鼠标处于四个角时默认按当前横纵比例缩放。以避免部分游戏画面比例失调

- 关于全屏功能建议
 首先明确我们何时会使用到该功能？我总结了下一般是这几种情况：
 一、该游戏无全屏功能，不能全屏。
 二、部分游戏对高分辨率（≥2k）屏幕支持不佳，全屏后画面有限放大，不能填满屏幕两边；或者是全屏后导致游戏黑屏，比如樱花两年前的游戏。
 三、翻译器界面与游戏内置全屏后产生交互冲突：游戏全屏点击翻译窗口区域造成游戏最小化（比如elf、mink ago等家的游戏）许多游戏通过更改分辨率实现全屏，翻译器UI显得很大，很占屏幕，且致使翻译界面在全屏后推出平面，找不到，看不见（如elf、anim等的游戏）
综上可见，galgame系统的庞杂导致这个功能很难做得尽善尽美，不过这里有个参考。
目前对于以上这些情况我都是使用一个窗口全屏工具去解决的，但大部分玩家并不知道这种工具，而且其使用体验也与翻译器有些冲突，比如其对缩放窗口失焦后会自动将窗口还原，所以当玩家点击翻译窗口任何位置时就会这样。
目前我用的那个工具叫magpie，github上也有它的项目，其是对3d游戏开发的一个全屏工具，能力强大，放大画面的原理是直接实时放大窗口画面的分辨率来实现的，挺简单粗暴的。撇开跟翻译器的冲突不谈，除了对电脑功耗有所增加外，其挺好用的，还能优化低分辨率游戏的画质。我觉得可以的话翻译器的全屏采用这种形式，只要解决了点击翻译器使得游戏窗口还原的问题就行。

**Comment by HIllya51** [comment]
这个全屏只是简单做的预留接口，我正在编写调用magpie的超分辨率全屏方法，还请期待。

**Comment by EXBJAN** [comment]
ok，很期待

**Comment by EXBJAN** [comment]
真快啊，坐等优化
