### ISSUE TITLE
好き好き大好き!读不到文本

### ISSUE THREAD

**Issue by wycstc353** [HIllya51/LunaTranslator#462]
好き好き大好き!读不到文本
https://www.ggbases.com/search.so?p=0&title=%E5%A5%BD%E3%81%8D%E5%A5%BD%E3%81%8D%E5%A4%A7%E5%A5%BD&advanced=
https://www.ggbases.com/view.so?id=20477
老游戏了，太老了，读不到文本，希望大佬能找到办法读文本

**Comment by HIllya51** [comment]
HBN4*0@25490:AVG3216D.EXE

**Comment by wycstc353** [comment]
> HBN4*0@25490:AVG3216D.EXE
 谢谢哈，自从用了你这个软件后，很久没用特殊码了，还以为不需要特殊码了呢
