### ISSUE TITLE
可以加个按钮，暂时把翻译结果和原文不显示吗？有时候正好是翻译结果挡住了选项，导致选项看不清

### ISSUE THREAD

**Issue by wycstc353** [HIllya51/LunaTranslator#463]
可以加个按钮，暂时把翻译结果和原文不显示吗？有时候正好是翻译结果挡住了选项，导致选项看不清，希望加个按钮，把这一次翻译的不显示，然后游戏里点击下一个文本的时候继续显示原文和翻译

**Comment by HIllya51** [comment]
你把他挪开不就行了，或者你把窗口高度缩回去不就行了。。。

**Comment by wycstc353** [comment]
> 你把他挪开不就行了，或者你把窗口高度缩回去不就行了。。。

就是每次都要挪嫌麻烦才想要加这个功能的，或者把自动翻译关掉时改成都不显示也行，像vnr暂停时一样，都不显示

**Comment by HIllya51** [comment]
那你不如开个快捷键，显示/隐藏窗口

**Comment by wycstc353** [comment]
> 那你不如开个快捷键，显示/隐藏窗口

哎，原来有快捷键功能啊，试了一下，挺符合我的要求的，那就这样吧
