### ISSUE TITLE
剪贴板翻译问题

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#464]
文本提取到剪贴板后，翻译器有相当的延迟，才会识别到文本并翻译。但鼠标立马移动到翻译器上，翻译器就能无缝识别文本并翻译。不知道这是个什么问题，露娜佬可以试试看有没有这问题

**Comment by HIllya51** [comment]
读取剪贴板并不是一个耗时操作。有没有可能你以为文字提取到剪贴板了其实并没有，你可以拿个别的监听剪贴板的软件试一下。

**Comment by dnadash** [comment]
> 读取剪贴板并不是一个耗时操作。有没有可能你以为文字提取到剪贴板了其实并没有，你可以拿个别的监听剪贴板的软件试一下。

我是用翻译器HOOK文本到剪贴板，然后再用翻译器的剪贴板翻译的

**Comment by dnadash** [comment]
> 什么莫名奇妙的。你拿个别的监听剪贴板的软件试一下不就知道了？

https://gofile.io/d/16mgca

**Comment by HIllya51** [comment]
盲猜你这个游戏有焦点的时候就会不停的getglyphoutline，失去焦点停止绘制。
和剪贴板不剪贴板半毛钱关系没有。

**Comment by dnadash** [comment]
> 盲猜你这个游戏有焦点的时候就会不停的getglyphoutline，失去焦点停止绘制。 和剪贴板不剪贴板半毛钱关系没有。

这游戏本身确实有点问题，不过翻译起来没问题，以后有机会换个游戏看看吧，麻烦了
