### ISSUE TITLE
更新过后就不显示文本了

### ISSUE THREAD

**Issue by liuxinyuzhou** [HIllya51/LunaTranslator#465]
一直用的是老版本用的好好的，今天手贱点了自动更新，更新完之后就不能翻译了，文本不显示了。选择文本那一块就是空白了，不出原文。

**Comment by liuxinyuzhou** [comment]
用的是hook

**Comment by liuxinyuzhou** [comment]
我是很久之前在vnr吧看到您推荐自己软件试着用了一下，比vnr方便很多。现在更新完之后界面也没变我也没动东西就是不显示文本不翻译了。就来这里看看新版本，但发现和我的那个出入很大，这新的我也不会装了，求教啊
![屏幕截图 2023-12-20 005439](https://github.com/HIllya51/LunaTranslator/assets/154357992/d7372e37-0769-4d5a-9252-2da3a6d3d2c2)

**Comment by HIllya51** [comment]
所以你是自行解决了吗。

**Comment by liuxinyuzhou** [comment]
是的，我在这里重新下了一个最新的，可以用了就。之前的那个软件自动更新的那个就不用了，因为不能显示，原因我不清楚，可能是更新过程中出了什么问题，但我的问题算解决了。

**Comment by liuxinyuzhou** [comment]
另外想问一下这个软件可以翻译rpg类的吗？
