### ISSUE TITLE
百度在线翻译怎么用不了了？

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#468]
百度注册API翻译没问题

**Comment by HIllya51** [comment]
已经确定是和ssl有关，估计是因为python3.10之前是ssl-1-1，python3.11之后是ssl3。
但是为了兼容win7不可能仅为此升级到3.11。
故此暂时提供一个[特别版](https://github.com/HIllya51/LunaTranslator/releases/download/v2.29.11/LunaTranslator_python311_win10+.zip)，此版本之后不会更新。

**Comment by HIllya51** [comment]
已修

**Comment by dnadash** [comment]
> 已修

![QQ截图20231223223854](https://github.com/HIllya51/LunaTranslator/assets/137600501/fda6b6e2-c451-48b2-b351-6fa9ac866ed1)
又遇到同样的问题

**Comment by wycstc353** [comment]
> 已修

最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着

**Comment by dnadash** [comment]
> > 已修
> 
> 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着

修复版本昨天下了，今天用的好好的，不过晚上十点半突然又用不了了，刚才又好了，很怪

**Comment by dnadash** [comment]
> 已修
用着用着就又遇到同样的问题了
![QQ截图20231224003442](https://github.com/HIllya51/LunaTranslator/assets/137600501/5f1f8590-1d77-4478-8f23-82bebaf9f754)

**Comment by dnadash** [comment]
> > 已修
> 
> 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着

也不行，反复横跳，一会行一会不行的

**Comment by HIllya51** [comment]
> > 已修
> 
> 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着



> > > 已修
> > 
> > 
> > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> 
> 也不行，反复横跳，一会行一会不行的

昨天测试python3.7+最新版urllib3是可以的来着，今天又不行了，不知道为什么。
但是python3.11是可以的。已经确定就是python3.11中使用的openssl-3，python3.10及以下是openssl-1-1，里面可能有一些实现有问题。但是win7最高支持到python3.8，不可能为此放弃win7的支持。
你们要是一定要用的话我会打一个python311的包，但之后这个包不会更新。

**Comment by dnadash** [comment]
> > > 已修
> > 
> > 
> > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> 
> > > > 已修
> > > 
> > > 
> > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > 
> > 
> > 也不行，反复横跳，一会行一会不行的
> 
> 昨天测试python3.7+最新版urllib3是可以的来着，今天又不行了，不知道为什么。 但是python3.11是可以的。已经确定就是python3.11中使用的openssl-3，python3.10及以下是openssl-1-1，里面可能有一些实现有问题。但是win7最高支持到python3.8，不可能为此放弃win7的支持。 你们要是一定要用的话我会打一个python311的包，但之后这个包不会更新。 https://github.com/HIllya51/LunaTranslator/releases/download/v2.29.11/LunaTranslator_x64_python311_win10+.zip

这个版本翻译是没问题了，但是好像查词——原文这边有问题，开启原文点几下翻译器直接就闪退了

**Comment by wycstc353** [comment]
> > > > 已修
> > > 
> > > 
> > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > 
> > 
> > > > > 已修
> > > > 
> > > > 
> > > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > > 
> > > 
> > > 也不行，反复横跳，一会行一会不行的
> > 
> > 
> > 昨天测试python3.7+最新版urllib3是可以的来着，今天又不行了，不知道为什么。 但是python3.11是可以的。已经确定就是python3.11中使用的openssl-3，python3.10及以下是openssl-1-1，里面可能有一些实现有问题。但是win7最高支持到python3.8，不可能为此放弃win7的支持。 你们要是一定要用的话我会打一个python311的包，但之后这个包不会更新。 https://github.com/HIllya51/LunaTranslator/releases/download/v2.29.11/LunaTranslator_x64_python311_win10+.zip
> 
> 这个版本翻译是没问题了，但是好像查词分析器——原文这边有问题，开启原文点几下翻译器直接就闪退了

还有问题是吧，那我暂时不下他那个，等没问题了再下载

**Comment by HIllya51** [comment]
> > > > 已修
> > > 
> > > 
> > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > 
> > 
> > > > > 已修
> > > > 
> > > > 
> > > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > > 
> > > 
> > > 也不行，反复横跳，一会行一会不行的
> > 
> > 
> > 昨天测试python3.7+最新版urllib3是可以的来着，今天又不行了，不知道为什么。 但是python3.11是可以的。已经确定就是python3.11中使用的openssl-3，python3.10及以下是openssl-1-1，里面可能有一些实现有问题。但是win7最高支持到python3.8，不可能为此放弃win7的支持。 你们要是一定要用的话我会打一个python311的包，但之后这个包不会更新。 https://github.com/HIllya51/LunaTranslator/releases/download/v2.29.11/LunaTranslator_x64_python311_win10+.zip
> 
> 这个版本翻译是没问题了，但是好像查词分析器——原文这边有问题，开启原文点几下翻译器直接就闪退了

修复了，小问题。

**Comment by HIllya51** [comment]
> > > > > 已修
> > > > 
> > > > 
> > > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > > 
> > > 
> > > > > > 已修
> > > > > 
> > > > > 
> > > > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > > > 
> > > > 
> > > > 也不行，反复横跳，一会行一会不行的
> > > 
> > > 
> > > 昨天测试python3.7+最新版urllib3是可以的来着，今天又不行了，不知道为什么。 但是python3.11是可以的。已经确定就是python3.11中使用的openssl-3，python3.10及以下是openssl-1-1，里面可能有一些实现有问题。但是win7最高支持到python3.8，不可能为此放弃win7的支持。 你们要是一定要用的话我会打一个python311的包，但之后这个包不会更新。 https://github.com/HIllya51/LunaTranslator/releases/download/v2.29.11/LunaTranslator_x64_python311_win10+.zip
> > 
> > 
> > 这个版本翻译是没问题了，但是好像查词分析器——原文这边有问题，开启原文点几下翻译器直接就闪退了
> 
> 还有问题是吧，那我暂时不下他那个，等没问题了再下载



> > > > 已修
> > > 
> > > 
> > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > 
> > 
> > > > > 已修
> > > > 
> > > > 
> > > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > > 
> > > 
> > > 也不行，反复横跳，一会行一会不行的
> > 
> > 
> > 昨天测试python3.7+最新版urllib3是可以的来着，今天又不行了，不知道为什么。 但是python3.11是可以的。已经确定就是python3.11中使用的openssl-3，python3.10及以下是openssl-1-1，里面可能有一些实现有问题。但是win7最高支持到python3.8，不可能为此放弃win7的支持。 你们要是一定要用的话我会打一个python311的包，但之后这个包不会更新。 https://github.com/HIllya51/LunaTranslator/releases/download/v2.29.11/LunaTranslator_x64_python311_win10+.zip
> 
> 这个版本翻译是没问题了，但是好像查词分析器——原文这边有问题，开启原文点几下翻译器直接就闪退了

我TM编译了一个openssl3的_ssl.pyd到python37上去了，没问题了。

**Comment by wycstc353** [comment]
> > > > > > 已修
> > > > > 
> > > > > 
> > > > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > > > 
> > > > 
> > > > > > > 已修
> > > > > > 
> > > > > > 
> > > > > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > > > > 
> > > > > 
> > > > > 也不行，反复横跳，一会行一会不行的
> > > > 
> > > > 
> > > > 昨天测试python3.7+最新版urllib3是可以的来着，今天又不行了，不知道为什么。 但是python3.11是可以的。已经确定就是python3.11中使用的openssl-3，python3.10及以下是openssl-1-1，里面可能有一些实现有问题。但是win7最高支持到python3.8，不可能为此放弃win7的支持。 你们要是一定要用的话我会打一个python311的包，但之后这个包不会更新。 https://github.com/HIllya51/LunaTranslator/releases/download/v2.29.11/LunaTranslator_x64_python311_win10+.zip
> > > 
> > > 
> > > 这个版本翻译是没问题了，但是好像查词分析器——原文这边有问题，开启原文点几下翻译器直接就闪退了
> > 
> > 
> > 还有问题是吧，那我暂时不下他那个，等没问题了再下载
> 
> > > > > 已修
> > > > 
> > > > 
> > > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > > 
> > > 
> > > > > > 已修
> > > > > 
> > > > > 
> > > > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > > > 
> > > > 
> > > > 也不行，反复横跳，一会行一会不行的
> > > 
> > > 
> > > 昨天测试python3.7+最新版urllib3是可以的来着，今天又不行了，不知道为什么。 但是python3.11是可以的。已经确定就是python3.11中使用的openssl-3，python3.10及以下是openssl-1-1，里面可能有一些实现有问题。但是win7最高支持到python3.8，不可能为此放弃win7的支持。 你们要是一定要用的话我会打一个python311的包，但之后这个包不会更新。 https://github.com/HIllya51/LunaTranslator/releases/download/v2.29.11/LunaTranslator_x64_python311_win10+.zip
> > 
> > 
> > 这个版本翻译是没问题了，但是好像查词分析器——原文这边有问题，开启原文点几下翻译器直接就闪退了
> 
> 我TM编译了一个openssl3的_ssl.pyd到python37上去了，没问题了。

还是不行，下载最新版本后，行了一段时间，然后又不行了

**Comment by dnadash** [comment]
> > > > > > 已修
> > > > > 
> > > > > 
> > > > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > > > 
> > > > 
> > > > > > > 已修
> > > > > > 
> > > > > > 
> > > > > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > > > > 
> > > > > 
> > > > > 也不行，反复横跳，一会行一会不行的
> > > > 
> > > > 
> > > > 昨天测试python3.7+最新版urllib3是可以的来着，今天又不行了，不知道为什么。 但是python3.11是可以的。已经确定就是python3.11中使用的openssl-3，python3.10及以下是openssl-1-1，里面可能有一些实现有问题。但是win7最高支持到python3.8，不可能为此放弃win7的支持。 你们要是一定要用的话我会打一个python311的包，但之后这个包不会更新。 https://github.com/HIllya51/LunaTranslator/releases/download/v2.29.11/LunaTranslator_x64_python311_win10+.zip
> > > 
> > > 
> > > 这个版本翻译是没问题了，但是好像查词分析器——原文这边有问题，开启原文点几下翻译器直接就闪退了
> > 
> > 
> > 还有问题是吧，那我暂时不下他那个，等没问题了再下载
> 
> > > > > 已修
> > > > 
> > > > 
> > > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > > 
> > > 
> > > > > > 已修
> > > > > 
> > > > > 
> > > > > 最近一直没用，今天用了一下，我这边百度也不行，有没有可能是你修复的版本没有发布来着
> > > > 
> > > > 
> > > > 也不行，反复横跳，一会行一会不行的
> > > 
> > > 
> > > 昨天测试python3.7+最新版urllib3是可以的来着，今天又不行了，不知道为什么。 但是python3.11是可以的。已经确定就是python3.11中使用的openssl-3，python3.10及以下是openssl-1-1，里面可能有一些实现有问题。但是win7最高支持到python3.8，不可能为此放弃win7的支持。 你们要是一定要用的话我会打一个python311的包，但之后这个包不会更新。 https://github.com/HIllya51/LunaTranslator/releases/download/v2.29.11/LunaTranslator_x64_python311_win10+.zip
> > 
> > 
> > 这个版本翻译是没问题了，但是好像查词分析器——原文这边有问题，开启原文点几下翻译器直接就闪退了
> 
> 我TM编译了一个openssl3的_ssl.pyd到python37上去了，没问题了。

百度在线翻译又用不了了，最新版和这个python311版
![QQ截图20240131140625](https://github.com/HIllya51/LunaTranslator/assets/137600501/2776088e-1e9f-49a5-8304-df79a8189483)
