### ISSUE TITLE
mecab 上色錯位 

### ISSUE THREAD

**Issue by sky456757** [HIllya51/LunaTranslator#47]
在1.19.2版還是正常的，在最新版出現了如下圖的移位情況
1.19.2:
<img width="1728" alt="截圖 2022-11-05 下午6 58 37" src="https://user-images.githubusercontent.com/22101536/200116713-ab9bb663-035c-4eb0-9649-1ca2d71ed471.png">
latest:
<img width="1741" alt="截圖 2022-11-05 下午6 59 45" src="https://user-images.githubusercontent.com/22101536/200116718-ad52afc8-05fe-485a-a0d9-5791b53d31cb.png">

**Comment by wwchy** [comment]
好
