### ISSUE TITLE
请问能否让LunaTranslator在配合miteiru使用时HooK不读取注音呢？

### ISSUE THREAD

**Issue by ads233** [HIllya51/LunaTranslator#470]
我现在用github里的一款叫做miteiru的软件边看视频边学习日语，这个软件能把日文字幕附带注音辅助我理解汉字发音，但是它不支持用中文辅助我理解陌生句子的含义，于是我选用LunaTranslator的hook进行实时翻译。但是LunaTranslator会把注音一起翻译造成日文文本+注音一起翻译导致翻译效果下降）
miteiru地址：https://github.com/hockyy/miteiru

**Comment by HIllya51** [comment]
你这样说谁能看懂啊 能不能放截图。

**Comment by ads233** [comment]
好的，明天早上我发图片给你看看，现在凌晨睡觉时间了不方便

**Comment by ads233** [comment]
如下图所示，我用faster-whisper制作的字幕投喂给miteiru让它在播放日文字幕的过程中给日文汉字自动注音。然后我再用LunaTranslator的HOOK吸收我投喂给miteiru的字幕进行实时翻译。但是HOOK在提取字幕的过程中会把汉字注音和日文字幕一起吸收导致翻译结果不理想。
![2](https://github.com/HIllya51/LunaTranslator/assets/153071412/bc920af4-94ba-4b85-ae00-f2314181cf85)
所以我想问一下能否让LunaTranslator避免提取miteiru的汉字注音造成翻译混乱？
又或者能否在LunaTranslator添加功能：直接将字幕投喂给LunaTranslator让它预先翻译好全部内容，然后LunaTranslator检测视频播放器的实时进度进行对应翻译服务？
通过这种方式从而在功能上达到类似于谷歌拓展插件Language Reactor那样，手上拿着翻页笔在需要中文解释时按下翻页笔的快捷键显示中文翻译，达到一边看剧一遍学习的目的。
![3](https://github.com/HIllya51/LunaTranslator/assets/153071412/095606ed-c49d-4bf4-aeb0-e873ffb669d8)
![4](https://github.com/HIllya51/LunaTranslator/assets/153071412/26205141-e47e-48df-ba2c-4badb2f83bf7)

**Comment by HIllya51** [comment]
看一下hook提取的原文是什么样的。盲猜里面是有<ruby>之类的标签的

**Comment by ads233** [comment]
我刚才试了一下，奇怪的是现在Hook 捉取不到任何文本了😭。我吃完饭再试一下

**Comment by ads233** [comment]
![Uploading QQ拼音截图20231226132818.png…]()

**Comment by fanyingfx** [comment]
> 类似于谷歌拓展插件Language Reactor那样，手上拿着翻页笔在需要中文解释时按下翻页笔的快捷键显示中文翻译，下一句字幕来临时Language Reactor会将翻译隐藏，从而达到一边看剧一遍学习的目的。

我有个类似的学日语需求，希望LunaTranslator可以支持显示原文不显示翻译(主要是LunaTranslator有假名标注而且可以方便的查词)，然后通过快捷键/窗口按钮的方式翻译当前句子，触发的时候翻译当前句子并显示原文，不会自动翻译下一句。
我改了部分代码通过开启/关闭在用的所有翻译器实现了类似的功能，不过感觉这样实现不太好，而且没法把开关翻译器和刷新翻译结果做到一个功能上

**Comment by HIllya51** [comment]
如果没有标签那么没有办法。

**Comment by ads233** [comment]
如果能解决HooK会提取字幕注音这个问题，那样LunaTranslator在配合miteiru一起使用就非常完美了。
miteiru可以提供汉字注音（也可以顺便看一下部分日文的英文表达以及部分外来词的英文来源）。
LunaTranslator可以实现类似Language Reactor那样在需要中文辅助理解文意时迅速通过按下手里的翻页笔快捷键来显示中文解释。

**Comment by HIllya51** [comment]
试了一下好难用，等了半天一直still loading subtitle，什么都不显示，没兴趣弄。

**Comment by ads233** [comment]
字幕是本地字幕直接扔进去就迅速显示的啊

**Comment by ads233** [comment]
有些没有字幕的视频可以通过Google Colab的notebook使用faster-whisper V3大模型来提取日文字幕，直接在看剧的时候手机打开谷歌浏览器的Google Colab的notebook分配到免费的T4显卡让他跑下一集的字幕就行。这样就实现一边看剧一边手机负责生成字幕（手机端锁定窗口不让谷歌浏览器关闭或在后台被清理），等到番剧看完的时候就在电脑上的谷歌云端页面下载下一集的字幕然后扔进去miteiru继续看下一集。
这里提供2个notebook有兴趣就试试：
https://github.com/lewangdev/autotranslate
https://github.com/Ayanaminn/N46Whisper

**Comment by HIllya51** [comment]
太麻烦了，没兴趣。

**Comment by 31653526619211a** [comment]
用gpt翻译的话改一下prompt让它输出你想要的翻译格式就能行
