### ISSUE TITLE
hook时闪退，游戏目录生成crash冲突日志

### ISSUE THREAD

**Issue by xylyyy** [HIllya51/LunaTranslator#474]
麻烦看下怎么回事，最新版及其上一版本都试过了，一选择游戏就闪退，てんぷれっ!!这个

**Comment by HIllya51** [comment]
你难道不应该先把游戏发给我吗？另外我不接受要登录的网盘。

**Comment by xylyyy** [comment]
> 你难道不应该先把游戏发给我吗？另外我不接受要登录的网盘
好的，是我考虑不周，已补 https://mega.nz/folder/oC9TDSoA#UihGSpk7IHiXOLNT7rBnuw

**Comment by HIllya51** [comment]
修了

**Comment by xylyyy** [comment]
感谢作者大大
