### ISSUE TITLE
HOOK获取到的单次文本像被按字符遍历输出一样分成了多行导致无法有效翻译

### ISSUE THREAD

**Issue by cclcc6** [HIllya51/LunaTranslator#476]
有的gal游戏引擎HOOK获取到的单次文本会像被按字符遍历输出一样分成了多行，这种情况下就没法翻译了。
另外，本来想试试【文本处理】里的【自定义python处理】功能的，发现点击旁边的齿轮后有时任务栏会出现python图标后闪退（电脑里有python环境）。

**Comment by HIllya51** [comment]
截图。。你描述的这么抽象谁能看懂。
闪退是因为会尝试打开.py文件，你可以自己手动打开./userconfig/mypost.py

**Comment by cclcc6** [comment]
![PixPin_2024-01-02_23-14-47](https://github.com/HIllya51/LunaTranslator/assets/55901706/cba9f67f-bb2b-4cd3-897e-8ef2c593ea0d)

**Comment by HIllya51** [comment]
我还以为什么呢。把刷新延迟调高就行了。

**Comment by cclcc6** [comment]
完美解决，这么晚还回复谢谢大佬

**Comment by 31653526619211a** [comment]
> 完美解决，这么晚还回复谢谢大佬

能调文本显示速度的话调高也行

**Comment by cclcc6** [comment]
了解，谢谢ꉂ(ˊᗜˋ*)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月2日(周二) 晚上11:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [HIllya51/LunaTranslator] HOOK获取到的单次文本像被按字符遍历输出一样分成了多行导致无法有效翻译 (Issue #476)




  
完美解决，这么晚还回复谢谢大佬
  
能调文本显示速度的话调高也行
