### ISSUE TITLE
win7系统用最新版有报错弹窗

### ISSUE THREAD

**Issue by KAllen233** [HIllya51/LunaTranslator#48]
![Snipaste_2022-11-06_12-06-06](https://user-images.githubusercontent.com/117556330/200153694-28402d64-baee-4f7b-bc49-bd16811e1c37.png)
今天更新了最新版，然后win7报了这个弹窗，但是翻译器本身好像还能正常使用，请问这是什么问题，能修复这个弹窗吗

**Comment by HIllya51** [comment]
不知道，有可能是部分插件的问题

**Comment by HIllya51** [comment]
你操作系统是64位的吗？

**Comment by KAllen233** [comment]
是的，之前的版本都没出现过这个弹窗，只有最新版出现了

**Comment by HIllya51** [comment]
查到了 是magpie调用的CreateFile2 回头改一下。

**Comment by KAllen233** [comment]
大佬辛苦
