### ISSUE TITLE
無法安裝新版本，舊版本也不行

### ISSUE THREAD

**Issue by burger2077** [HIllya51/LunaTranslator#484]
安裝後跳出錯誤訊息，省略後，檔案跟以前很不同，不知從何使用？無法確定還能使用
<img width="223" alt="image" src="https://github.com/HIllya51/LunaTranslator/assets/155927712/bac72891-2b0a-4736-b2ff-467682c31e9c">
<img width="562" alt="image01png" src="https://github.com/HIllya51/LunaTranslator/assets/155927712/1137658f-9269-4358-8f85-23af142e7e0d">
<img width="561" alt="image02" src="https://github.com/HIllya51/LunaTranslator/assets/155927712/08a66257-1896-4449-9bef-45ed52b39150">
<img width="561" alt="image03" src="https://github.com/HIllya51/LunaTranslator/assets/155927712/3313f2dd-2c65-4a2b-8b52-c73c269d112c">

**Comment by HIllya51** [comment]
你下的啥啊，这全是空文件夹啊😅

**Comment by HIllya51** [comment]
😅重新下
