### ISSUE TITLE
Any chance you could add Sugoi translator?

### ISSUE THREAD

**Issue by Sarata137** [HIllya51/LunaTranslator#485]
I think it's the best free translator available, on the level of Deepl. Thanks

我认为它是 Deepl 级别上最好的免费翻译器。 谢谢

**Comment by HIllya51** [comment]
我不知道从哪里可以下载。

**Comment by HIllya51** [comment]
？

**Comment by Sarata137** [comment]
抱歉，他现在只在每月 15 日提供。 您只能在 1 月 15 日下载。 抱歉浪费了时间，我将在 1 周内重新创建该线程。
