### ISSUE TITLE
HOOK文本处理问题

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#487]
文本只有一行没问题（去重就行
![1](https://github.com/HIllya51/LunaTranslator/assets/137600501/e8ca0328-13f3-4014-a72d-c531d1d5d1e4)
文本占两行
![2](https://github.com/HIllya51/LunaTranslator/assets/137600501/56b28c3f-3a3c-409a-a1e0-922efae80a5c)
3行
![3](https://github.com/HIllya51/LunaTranslator/assets/137600501/33516be7-fc21-47b4-80ac-1e3673ec5b10)

两行以上过滤换行去重整不明白了

游戏：链接: https://pan.baidu.com/s/12vWZodW5N0x4EhiXE7ALhw 提取码: resb

**Comment by HIllya51** [comment]
已修
