### ISSUE TITLE
关于内嵌翻译

### ISSUE THREAD

**Issue by csquya** [HIllya51/LunaTranslator#489]
能不能在内嵌翻译的时候，依旧保留原先原文的显示方式， 即原文显示在在游戏窗口上方，这样便于分词取词和查词典。

现在的内嵌翻译是译文和原文在一起的。这个似乎没必要，而且显示原文的时候由于2个文本在一起，影响显示效果。

谢谢，其实这个翻译器已经很完美了，总觉得提这些要求有些难为情。

**Comment by HIllya51** [comment]
我咋看不明白你的话呢。

**Comment by csquya** [comment]
![捕获](https://github.com/HIllya51/LunaTranslator/assets/23205595/6cb779cd-007e-4962-bf0a-0f8afa00a5bf)
不好意思，重新下载之后似乎可以了。
但是有个小小的新问题，内嵌之后，是否可以取消图示中原来的翻译（就是原文下面的，因为重复了）？

看设置似乎是内嵌的翻译器和非内嵌的翻译器可以是不同的，但我取消掉非内嵌的翻译器以后，内嵌的也没有了。

内嵌的还有个选项，就是“使用最快翻译而非指定翻译器”， 这意思是在所有可用的里选择还是“翻译设置”里指定的？ 我看结果似乎是后者，但是指定太多了上面就一大堆文字。

理想状况就是指定几个用来内嵌翻译，但只显示在内嵌里。像那个选项说的“使用最快翻译而非指定翻译器”一样只显示一个。

**Comment by csquya** [comment]
![捕获2](https://github.com/HIllya51/LunaTranslator/assets/23205595/dd724dc9-fa90-4d2e-aebb-6cf74007d555)
另外，这个游戏里我设置了人名文本分开，也设置了女性的声音不自动朗读，但还是朗读了， 这个社的所有游戏只要是原有声音的，都会在人名之前有个“voice”的标志。是不是这个引起的，或者根据这个标志能否屏蔽掉设置的自动朗读。

**Comment by HIllya51** [comment]
> ![捕获](https://private-user-images.githubusercontent.com/23205595/296249710-6cb779cd-007e-4962-bf0a-0f8afa00a5bf.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzA0MzYsIm5iZiI6MTcwNTA3MDEzNiwicGF0aCI6Ii8yMzIwNTU5NS8yOTYyNDk3MTAtNmNiNzc5Y2QtMDA3ZS00OTYyLWJmMGEtMGY4YWZhMDBhNWJmLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE0MzUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMGIyNzk1OTlhYThjNDdjMzAxYWVmYjQzNzExMzg1MTNjMWFhOGYzYmFmMmJhNGNiMzU2M2NiYzY0M2QxYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sTbOgIzsFKE9x7wnognfqU4Rc55NELST68B75rzZ1oo) 不好意思，重新下载之后似乎可以了。 但是有个小小的新问题，内嵌之后，是否可以取消图示中原来的翻译（就是原文下面的，因为重复了）？
> 
> 看设置似乎是内嵌的翻译器和非内嵌的翻译器可以是不同的，但我取消掉非内嵌的翻译器以后，内嵌的也没有了。
> 
> 内嵌的还有个选项，就是“使用最快翻译而非指定翻译器”， 这意思是在所有可用的里选择还是“翻译设置”里指定的？ 我看结果似乎是后者，但是指定太多了上面就一大堆文字。
> 
> 理想状况就是指定几个用来内嵌翻译，但只显示在内嵌里。像那个选项说的“使用最快翻译而非指定翻译器”一样只显示一个。

只按下使用内嵌翻译，不打对勾就行了。

**Comment by csquya** [comment]
> 只按下使用内嵌翻译，不打对勾就行了。 什么莫名其妙，不管选不选都只会显示一种翻译。

1.如果不打对勾，原文好像就不会显示，或者内嵌里选择保留原文，那内嵌里也不好看了
2.内嵌里是只显示一种翻译，但是非内嵌的显示一大堆啊

**Comment by csquya** [comment]
> 看不懂你在说什么。如果是文本里面带voice就把voice过滤掉。

请原谅我表达能力比较差，这个你用空的话可以用这个社的游戏试一下。voice这个字现在是hook不到的，所以无法过滤。

**Comment by HIllya51** [comment]
如果要问某个游戏，那你就把游戏资源给我，不要让我自己去找资源。（不接受需要登录的网盘）

**Comment by csquya** [comment]
> 如果要问某个游戏，那你就把游戏资源给我，不要让我自己去找资源。（不接受需要登录的网盘）

我不知道哪有不需要登陆的网盘，就连百度盘也需要登陆的吧， 我尝试将一个游戏上传到自建网盘，不知道你能否下载到。 https://zyaqu.com/file/wl/?id=mv4xgoPlATnDAh5Cq2arlRmZIZ4W6u5U  此游戏不是我贴出的那个，但是同一社的， 体积比较小便于下载，里边默认是chatgpt， 但我保留了原版文件，从相应文件夹拷贝替换就恢复原版。

**Comment by HIllya51** [comment]
测试没有问题。

**Comment by csquya** [comment]
> 测试没有问题。

好吧，那可能是我的设置问题，麻烦你了，我自己再看看。

**Comment by csquya** [comment]
> 盲猜一下，你没有设置文本类型为语音

没有看到”文本类型为语音“这个设置， 容我再找找。

不过我有个建议提一下，不知是否妥当？

以男性向游戏为例，需要朗读的地方一般就是旁白和主角， 其他女主和杂鱼角色都有语音的，而女主和杂鱼角色众多，去挑选比较困难。 所以应该反向挑选，在玩家开了朗读的前提下，旁白默认朗读，如此大多数情况下只需要填一个主角名字即可。

更简单的做个选项，让玩家选择

1. 全朗读 （针对某些无语音游戏）
2. 只朗读旁白
3. 朗读旁白和指定角色 （指定角色需玩家自行填入人名）
