### ISSUE TITLE
建议：可以设置调用本地已有的magpie

### ISSUE THREAD

**Issue by Ptilopsis01** [HIllya51/LunaTranslator#49]
如题，因为本地已经配置了magpie且进行了自定义配置
（而且尝试了一下似乎直接替换配置文件并不能应用我自定义的配置，可能是因为设置里的选项并非从配置文件里读取而是写在代码里了？）

**Comment by HIllya51** [comment]
magpie本地配置保存在哪了？我没找到，直接全用的默认

**Comment by Ptilopsis01** [comment]
> magpie本地配置保存在哪了？我没找到，直接全用的默认

就是在安装文件夹的那个json啊

**Comment by HIllya51** [comment]
ScaleModels.json？这个只是对于缩放算法的一些设置，并不是界面里显示的那些东西的设置。。。

**Comment by Ptilopsis01** [comment]
> ScaleModels.json？这个只是对于缩放算法的一些设置，并不是界面里显示的那些东西的设置。。。

我指的就是这个缩放算法的配置来着（）

**Comment by HIllya51** [comment]
本来就是读的这个文件啊。。。这里面都是一些超参数，效果区别不大你没看出来吧

**Comment by Ptilopsis01** [comment]
> 本来就是读的这个文件啊。。。这里面都是一些超参数，效果区别不大你没看出来吧

我指的是我自己配置了一些原本没有的算法组合，但是软件设置里可选算法组合仍然只有默认的几种
（其实我主要想问的是直接自定义设置本地的magpie路径是否可行）

**Comment by HIllya51** [comment]
哦哦 我明白你的意思了
