### ISSUE TITLE
Oyako Rankan Alicesoft Game special code

### ISSUE THREAD

**Issue by chaihahaha** [HIllya51/LunaTranslator#491]
请问母娘乱馆的特殊码应该怎么找？我尝试了用文本搜索，但是找到的都只有半句的（换行以后的句子无法检测到）。

另外想问下怎么把VNR的特殊码转为Luna的特殊码？这个游戏的VNR特殊码是"/HS-20@53D8F5"。如果想要自己从游戏二进制逆向分析出特殊码应该怎么做？

**Comment by HIllya51** [comment]
直接用不用转。

**Comment by HIllya51** [comment]
用默认搜索或者自定义搜索啊，文本搜索最没用。
