### ISSUE TITLE
hook終わる世界とバースデイ文本时遇到的问题。

### ISSUE THREAD

**Issue by AdarkYesha** [HIllya51/LunaTranslator#493]
作者大大能不能解决一下hook終わる世界とバースデイ文本时遇到的问题：一段文本分为两部分显示，这就导致第一部分的文本没看完就显示了下一部分文本。虽然能通过查看历史翻译解决，但还是有些不便利。
![屏幕截图 2024-01-15 134715](https://github.com/HIllya51/LunaTranslator/assets/25260461/b90b6eca-2ea6-4540-b444-3bda8d20ce16)

**Comment by HIllya51** [comment]
刷新延迟
