### ISSUE TITLE
选择游戏进程点击OK后，翻译器白屏卡死

### ISSUE THREAD

**Issue by tdstorm** [HIllya51/LunaTranslator#498]
作者大大你好，今天更新版本后发现在选择特定游戏进程点击OK后，翻译器会白屏卡死，测试了v2.34.0~v2.36.0版本都有这个情况，v2.33.1可以正常使用。选择的游戏是“逢魔ガ刻・弐 夜闇ニ祈ル少女”，电脑上的其他游戏能正常使用，但是当选择这款游戏点OK后翻译器就会白屏卡死，而如果换成v2.33.1版本就能正常显示提取到的游戏内文本。

v2.34.0~v2.36.0版本选择“逢魔ガ刻・弐 夜闇ニ祈ル少女”游戏进程后，点OK后的样子
![123](https://github.com/HIllya51/LunaTranslator/assets/47531411/bf48a5e2-3bee-4c22-832c-125452c5d3c0)

非常感谢

**Comment by HIllya51** [comment]
资源。

**Comment by tdstorm** [comment]
https://mega.nz/file/dYdmQTDR#c4bj_plovKeWO4iAiixlo1OcIopMvpBihG0OefLKh14
不好意思，已经上传

**Comment by HIllya51** [comment]
已修正
