### ISSUE TITLE
使用手动翻译统一翻译内容

### ISSUE THREAD

**Issue by acteds** [HIllya51/LunaTranslator#5]
类似https://github.com/hanmin0822/MisakaTranslator  的翻译优化系统  
但他那个功能是在将待翻译内容直接替换为手动翻译,然后上传在线翻译可能被二次翻译  
可以在提交给在线翻译前用一些不会被翻译的中间字符替换原有字符串,然后待翻译结果出来后再替换为本地添加的手动翻译  
这样就和以前的Visual Novel Reader一样了,手动翻译的内容还是建议使用SQLite方便连数据库,或作一个管理工具  
详细议题见https://github.com/hanmin0822/MisakaTranslator/issues/211

**Comment by acteds** [comment]
毕竟某些词语在线翻译是不可能翻译正确的结果的

**Comment by HIllya51** [comment]
可以，我下午搞一下

**Comment by HIllya51** [comment]
真的可以吗。。。
https://i.postimg.cc/nzwXtrrZ/2022-10-05-124527.jpg
为什么我简单试了一下百度的就根本没法搞QAQ

**Comment by HIllya51** [comment]
好吧。我试了一下，有的时候行有的时候不行，全凭运气。。。

**Comment by acteds** [comment]
> 好吧。我试了一下，有的时候行有的时候不行，全凭运气。。。
可以换点其他的占位符,实在不行可以分段翻译.
[![2022-10-05-13-07-50.png](https://i.postimg.cc/DZsvZzGT/2022-10-05-13-07-50.png)](https://postimg.cc/R6S5p4Gs)  
不行的话就只能蠢蠢的在翻译前替换内容,然后可能被二次翻译

**Comment by neetnya** [comment]
这个问题 我拿御坂翻译器魔改试过
(我只用腾讯API那个，其他翻译源不清楚)
比如说 咲 这个字 翻译器是会直接翻译成 开花 之类的，但是实际语境可能就是人名
如果单纯的使用文本替换功能 实际上没有任何用处
所以我直接定义两层转换  提交翻译的时候 把 咲 替换成 SAKI ，于是因为整句话是日语，翻译回来的结果这里依旧是SAKI，然后对结果二次处理，把SAKI替换成咲
占位符其实没啥必要，直接罗马音或者拼音就行了
不过要是大写，作为句首可能会首字母自动大写

**Comment by acteds** [comment]
$1、#1、@1这些都可以试试

**Comment by acteds** [comment]
> 这个问题 我拿御坂翻译器魔改试过 (我只用腾讯API那个，其他翻译源不清楚) 比如说 咲 这个字 翻译器是会直接翻译成 开花 之类的，但是实际语境可能就是人名 如果单纯的使用文本替换功能 实际上没有任何用处 所以我直接定义两层转换 提交翻译的时候 把 咲 替换成 SAKI ，于是因为整句话是日语，翻译回来的结果这里依旧是SAKI，然后对结果二次处理，把SAKI替换成咲 占位符其实没啥必要，直接罗马音或者拼音就行了 不过要是大写，作为句首可能会首字母自动大写

和你想的一样,但替换为字母可能被翻译,且可能有同罗马音的词语

**Comment by HIllya51** [comment]
https://i.postimg.cc/4xDMWRg3/2022-10-05-132005.jpg
把人名换成占位符，语义可能就变了。
https://i.postimg.cc/DyDYz3mc/2022-10-05-131951.jpg
换成大写罗马音也不行啊。。。这罗马音直接被改了

**Comment by neetnya** [comment]
> > 这个问题 我拿御坂翻译器魔改试过 (我只用腾讯API那个，其他翻译源不清楚) 比如说 咲 这个字 翻译器是会直接翻译成 开花 之类的，但是实际语境可能就是人名 如果单纯的使用文本替换功能 实际上没有任何用处 所以我直接定义两层转换 提交翻译的时候 把 咲 替换成 SAKI ，于是因为整句话是日语，翻译回来的结果这里依旧是SAKI，然后对结果二次处理，把SAKI替换成咲 占位符其实没啥必要，直接罗马音或者拼音就行了 不过要是大写，作为句首可能会首字母自动大写
> 
> 和你想的一样,但替换为字母可能被翻译,且可能有同罗马音的词语

至少我是没遇到过被翻译的情况，或者可能没在意吧，同音的问题，因为我是手动配置的，所以倒是没考虑过这个

**Comment by HIllya51** [comment]
算了 我就用大写的办法加上吧，反正提供个设置项就行了

**Comment by HIllya51** [comment]
已采用占位符方式实现。过会release一下。

**Comment by umichan0621** [comment]
可以试一下A-01 B-02这种，tx的api是保留的

**Comment by umichan0621** [comment]
> 可以试一下A-01 B-02这种，tx的api是保留的

之前做机翻的时候收集了一些和谐词，觉得比较合理的可以拿去做预设词

**Comment by HIllya51** [comment]
可以 确实行
