### ISSUE TITLE
关于magpie全屏模式的问题反馈

### ISSUE THREAD

**Issue by ssincxv** [HIllya51/LunaTranslator#50]
目前使用magpie跑全屏模式后，如果点击LunaTranslator的窗口或者翻译的文字或者图标，magpie将会从全屏模式还原到窗口模式，能否让magpie全屏始终维持，除非再点击magpie开启或者关闭的图标，否则一直维持全屏模式。

**Comment by HIllya51** [comment]
臣妾做不到啊

**Comment by EXBJAN** [comment]
我已经跑过去反馈了https://github.com/Blinue/Magpie/issues/447#issue-1437894320

**Comment by EXBJAN** [comment]
卒
![QQ截图20221107161005](https://user-images.githubusercontent.com/117036098/200258444-19509d38-3df6-4bfb-b90f-131eb11110e1.png)

**Comment by HIllya51** [comment]
那就算了，多按一下全屏又无所谓。

**Comment by HIllya51** [comment]
好的  谢谢

**Comment by HIllya51** [comment]
已完工。
