### ISSUE TITLE
区分人名和文本问题

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#502]
这功能咋用
![2](https://github.com/HIllya51/LunaTranslator/assets/137600501/df3a2817-8509-46a3-ab6b-f1de08ba4aa4)
这种人名在最前面，文本紧接其后，「  」和【】这俩框也没HOOK到，不好过滤。

**Comment by HIllya51** [comment]
找特殊码

**Comment by dnadash** [comment]
> 找特殊码

没特殊码是不是没办法了

**Comment by HIllya51** [comment]
你觉得呢
