### ISSUE TITLE
json文件翻译功能

### ISSUE THREAD

**Issue by xylyyy** [HIllya51/LunaTranslator#503]
有的游戏部分文本在同一画面时会先显示第一行，点击之后再显示第二行，但是翻译器在游戏显示第二行时会同时读取一二两行的内容，导致json文件找不到对应文本，通过脚本提取的json文件也没有办法将这两行串起来翻译，这样的话可以考虑出一个json文件出错时自动切换成在线翻译吗？希望作者大大考虑下，同时开两个翻译的话内容太多也会影响游戏窗口美观

**Comment by HIllya51** [comment]
如果找不到文本，说明你使用的json文件是其他来源的json文件，不是此程序生产的json文件

**Comment by xylyyy** [comment]
是的，通过游戏脚本得到的json,解包的游戏脚本那两行本来就是单独的，没法串到一起去，所以想到了翻译出错时能否自动切换成在线翻译，自带的gpt延时太高，开两个翻译又显得繁杂

**Comment by HIllya51** [comment]
显然，你更应该去处理json文件。
