### ISSUE TITLE
The text is broken into paragraphs 

### ISSUE THREAD

**Issue by allebar** [HIllya51/LunaTranslator#504]
How can I make sure that the text is not transferred to a new line? Previously, this happened automatically, but now it remains in the form in which it was originally extracted. I tried to solve this using "text processing", the result of this is in the second screenshot. The text is glued together, whereas previously a space was automatically placed and the text was not divided into paragraphs.
![2024-01-27_18-30-31](https://github.com/HIllya51/LunaTranslator/assets/75815491/f295b68f-80a4-4961-8af5-80100c4ef91f)
![2024-01-27_18-35-19](https://github.com/HIllya51/LunaTranslator/assets/75815491/25d24345-25ab-487f-a59e-29a4ef0a949c)

**Comment by HIllya51** [comment]
use "Escape string replacement" to replace "\n" to " "

**Comment by allebar** [comment]
> use "Escape string replacement" to replace "\n" to " "

I tried to use this but why didn't it work.  
![2024-01-27_18-50-17](https://github.com/HIllya51/LunaTranslator/assets/75815491/5696a2d7-0317-47eb-af8a-796dc4491d4d)

**Comment by HIllya51** [comment]
"Escape string replacement"

**Comment by allebar** [comment]
> "Escape string replacement"


> "Escape string replacement"

I messed up the setting at first, so I had to switch the language. But it still doesn't help to notice \n on the space bar. 
![2024-01-27_18-59-44](https://github.com/HIllya51/LunaTranslator/assets/75815491/271ed928-f354-484b-be4a-b179f1de35f5)

**Comment by allebar** [comment]
> "Escape string replacement"

![2024-01-27_19-02-24](https://github.com/HIllya51/LunaTranslator/assets/75815491/e8fffc00-79f4-49a5-a5c5-30401c440790)

**Comment by allebar** [comment]
> "Escape string replacement"

I tried to do the same thing, but on an older version of lunatranslatoin, everything turned out without problems.

**Comment by HIllya51** [comment]
this bug has been fixed.
