### ISSUE TITLE
文本处理去除重复行(AABABCABCD->ABCD)只对首行生效

### ISSUE THREAD

**Issue by DavidZhang53** [HIllya51/LunaTranslator#506]
请问类似逆转裁判那样一个字一个字跳的字幕怎么翻译，抓取的形式类似A AB ABC ABCD
用软件内置文本处理：去除重复行(AABABCABCD->ABCD)可以解决首行问题，
但是第二行就不行了，从第二行开始一直出现AABCD的情况，请问大佬有好方法解决吗

**Comment by DavidZhang53** [comment]
![Uploading QQ截图20240128123528.png…]()

**Comment by DavidZhang53** [comment]
![QQ截图20240128123528](https://github.com/HIllya51/LunaTranslator/assets/49602757/bb8ee075-d70a-4407-9b92-6a2cb7a6d5b2)
提取的是：
念
念の
念のた
念のため
念のため、
念のため、停
念のため、停電
念のため、停電の
念のため、停電の記
念のため、停電の記録
念のため、停電の記録を
提
提出
提出し
提出しま
提出します
提出します。

输出：
念のため、停電の記録を提提出します。
多一个“提”

**Comment by HIllya51** [comment]
更新程序，已解决。
