### ISSUE TITLE
火山翻译api报错

### ISSUE THREAD

**Issue by KAllen233** [HIllya51/LunaTranslator#509]
今天在用最新版本的翻译器的时候发现注册的火山api用不了，出现了这个报错
![PixPin_2024-01-30_11-51-36](https://github.com/HIllya51/LunaTranslator/assets/117556330/f62b9014-306d-4188-9bfa-c14b47a50460)
用了别的翻译软件测试同一个api是可以正常翻译的

**Comment by HIllya51** [comment]
已修正
