### ISSUE TITLE
在线翻译游戏中自带的片假名容易错误，建议增加读取平假名进行翻译的功能

### ISSUE THREAD

**Issue by DavidZhang53** [HIllya51/LunaTranslator#510]
在线翻译游戏中自带的片假名容易错误，建议增加读取平假名后再进行翻译的功能
比如游戏中句子里是メイワク，在线翻译句子会翻成“梅瓦克”，如果先转换成“めいわく”再翻译就不会错误了

**Comment by HIllya51** [comment]
文本处理->翻译优化
