### ISSUE TITLE
求助，请问azure openai 的key要如何添加到翻译器中

### ISSUE THREAD

**Issue by scp23328** [HIllya51/LunaTranslator#513]
![屏幕截图 2024-02-08 1733351](https://github.com/HIllya51/LunaTranslator/assets/55753366/83f34cb9-c024-4d3d-bd78-70221b8598cf)
 各位大佬好，请问我在部署完azure的openai后获得了这些信息，请问要怎么样能让azure在翻译器中运行

**Comment by HIllya51** [comment]
你这。。我也不知道啊，你直接私信我无码的行不？我又没用过。

**Comment by HIllya51** [comment]
![屏幕截图 2024-02-08 224420](https://github.com/HIllya51/LunaTranslator/assets/101191390/7978da4f-0607-4b4a-80ee-df5e12b45bed)

api_type改成azure，OPENAI_API_BASE改成你链接里的/chat/completions前面的。
你这码打的，我也不知道你这链接是什么，要是你链接里面没有/chat/completions，就把Appendix删了，把OPENAI_API_BASE改成你链接。
