### ISSUE TITLE
谢谢，这是最好的游戏翻译器！请教一个问题。 

### ISSUE THREAD

**Issue by lvcloudgit** [HIllya51/LunaTranslator#514]
内置假名标注有很多不准确的地方，尝试使用MeCab指定目录后没有作用，请问有什么需要注意的地方吗？

**Comment by HIllya51** [comment]
？什么莫名其妙的

**Comment by HIllya51** [comment]
没有什么需要注意的地方，这么很简单的东西，只有可能是你资源下的有问题

**Comment by lvcloudgit** [comment]
我从包括官网在内的三个不同的地址下载过（比较了一下尺寸，应该都是同一个版本0.996），然后卸载重装多次，换过不同的编码，都没有任何反应，应该跟下载的资源无关。MeCab本身是可以运行使用的，但是会显示乱码，这个问题我没搜到解决方法，不知道跟LUNA翻译器中没反应有没有关系。

**Comment by HIllya51** [comment]
config文件夹和你的mecab文件夹，都打包发给我。

**Comment by lvcloudgit** [comment]
[MeCab_userconfig.zip](https://github.com/HIllya51/LunaTranslator/files/14218640/MeCab_userconfig.zip)

谢谢！

**Comment by HIllya51** [comment]
下载最新版，路径选择ipadic，然后切换codec为shitjis

**Comment by lvcloudgit** [comment]
谢谢回复，虽然您提供的方案没有解决问题，哈哈，但是给了我思路，我没想到要指定字典目录。我从“辞书”界面里下载了Mecab.zip，解压后考到字典目录里，然后指定这个新的辞书目录终于可以了。祝新年快乐！🎆🧨🎊
