### ISSUE TITLE
文本过滤问题

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#515]
HOOK到这个小倒三角，一直刷新盖过文本导致翻译器来不及翻译，单独过滤掉没用
https://gofile.io/d/cYARCx
![QQ截图20240209154733](https://github.com/HIllya51/LunaTranslator/assets/137600501/f943de5b-d3b5-4efb-935a-6c6ab8da88fc)

**Comment by HIllya51** [comment]
你倒是选取他啊，谁说会来不及翻译的，过滤完了是空就直接跳过了
