### ISSUE TITLE
在真・恋姫†夢想系列中有部份文本無法讀取，從而無法翻譯的問題？

### ISSUE THREAD

**Issue by owentom401** [HIllya51/LunaTranslator#517]
紅色圈的地方是無法讀取的文本
![擷取](https://github.com/HIllya51/LunaTranslator/assets/156678839/38be8818-998d-4b45-b4ef-7502f5160ec5)

**Comment by HIllya51** [comment]
给我个跳转的存档。

**Comment by owentom401** [comment]
我不知道跳轉的存檔在哪個位置或檔名是叫甚麼，可以說一下如何看嗎？

**Comment by HIllya51** [comment]
你在有问题的地方之前存个存档，然后把存档打包发给我，不然我怎么找到哪里有缺少呢。

默认情况下，存档位置如下：

　　Windows 7/8/8.1/10
　　　C:\Users\你的用户名\AppData\Roaming\BASESON\真・恋姫†夢想-革命- 孫呉の血脈\

**Comment by owentom401** [comment]
[save0119.zip](https://github.com/HIllya51/LunaTranslator/files/14229880/save0119.zip)
發了

**Comment by HIllya51** [comment]
![屏幕截图 2024-02-11 004619](https://github.com/HIllya51/LunaTranslator/assets/101191390/a487eca5-d9dc-4083-93c4-ed5c0ee1d4f8)

**Comment by HIllya51** [comment]
我这里是能提取到的。那就没办法咯，这属于无法复现的问题，不行的话就用临时OCR来看吧。
存在这样一个按钮可以在用Hook提取的时候，对于无法提取的文本，临时使用一次OCR来进行识别，主要是是针对选项的，对于你这种情况也差不多吧。在显示设置->界面设置->窗口按钮设置里面可以开启这个功能。
![屏幕截图 2024-02-11 004845](https://github.com/HIllya51/LunaTranslator/assets/101191390/99be9afd-5c10-4da3-ac18-72714bb41bcb)

**Comment by HIllya51** [comment]
![屏幕截图 2024-02-11 005139](https://github.com/HIllya51/LunaTranslator/assets/101191390/766ec608-2be5-41ee-b1e9-b41ff692ea09)

**Comment by owentom401** [comment]
ok! 我再試試再看。
