### ISSUE TITLE
hook不到文本

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#518]
![1](https://github.com/HIllya51/LunaTranslator/assets/137600501/aabd6859-e7b6-4b3f-9cdb-15ca69d3e540)
游戏下载，解压即玩。链接: https://pan.baidu.com/s/1A9S1WtIzBeqFEj5I3g8pHQ 提取码: m5xg

**Comment by HIllya51** [comment]
HB-1C*-1@39A5B:ScrPlayer.exe

**Comment by HIllya51** [comment]
或者HS18@41DC10
