### ISSUE TITLE
功能建议：保存的游戏中，一些游戏无法拾取相应的图标

### ISSUE THREAD

**Issue by ssincxv** [HIllya51/LunaTranslator#52]
![QQ截图20221107043914](https://user-images.githubusercontent.com/116273073/200193918-11f572c9-35a8-4fe5-a59a-ab5cfbd3ad04.png)
添加手动替换图标或者图片功能

**Comment by HIllya51** [comment]
感觉意义不是很大，能区分是哪个游戏不就行了。

**Comment by EXBJAN** [comment]
那要不增加个可自定义游戏图标
