### ISSUE TITLE
win7虚拟机，彩云翻译失效

### ISSUE THREAD

**Issue by wycstc353** [HIllya51/LunaTranslator#520]
win7虚拟机，彩云翻译失效，不是api，就是直接的彩云翻译

**Comment by HIllya51** [comment]
截图。

**Comment by HIllya51** [comment]
其他设置->其他设置->Internet->libcurl

**Comment by wycstc353** [comment]
> 其他设置->其他设置->Internet->libcurl

![image](https://github.com/HIllya51/LunaTranslator/assets/39401653/90a2e888-9c2c-4bfc-87e0-e66644f73a4f)
改了，不行

**Comment by HIllya51** [comment]
重启。
