### ISSUE TITLE
最新版提示Wqoqv.exe報錯

### ISSUE THREAD

**Issue by a73420521** [HIllya51/LunaTranslator#521]
Windows 7系統使用最新版會出現下列報錯，64位元版本是出現Wqoqv.exe報錯，32位元則是dveBJw.exe、Wqoqv.exe、UpHUJL.exe三種報錯，在最新版的前2~3個版本，開啟LunaTranslator時都會聽見報錯的提示音，但沒有顯示報錯窗口。
找到問題點了，是J北京，把J北京關掉就不會報錯了
![2](https://github.com/HIllya51/LunaTranslator/assets/87113124/ee673906-2c34-4e45-b329-cd017e4a16fe)

**Comment by HIllya51** [comment]
我修复了一下，你试试看？

**Comment by a73420521** [comment]
謝謝，已經不會報錯了
