### ISSUE TITLE
Request: Multiple OCR Regions Functionality

### ISSUE THREAD

**Issue by creature93x** [HIllya51/LunaTranslator#523]
I've been utilizing the OCR feature quite extensively, and while it's proven to be efficient in many cases, I've encountered instances where using a single OCR region doesn't always yield the desired results. I was wondering if it's possible to incorporate functionality for multiple OCR regions in future updates. This would greatly enhance the accuracy and versatility of the OCR feature.

**Comment by HIllya51** [comment]
Please give me a design plan, otherwise I don't know how to do it.

**Comment by creature93x** [comment]
Add a button labeled "Multiple Regions" to the menu bar.
When users click on this button, the interface switches to a mode where users can draw boxes around each region they want to perform OCR on.
Each drawn region will have an index or label to distinguish it.
Modify the OCR functionality to work separately for each drawn region, so that the translation appears in the main window alongside its corresponding index or label if choosing in the settings.
This enhancement will allow users to select multiple areas of text for OCR, with translations displayed accordingly.
Here is an example:
![426586954_1559052234844482_3685808178767450299_n](https://github.com/HIllya51/LunaTranslator/assets/38745587/f94c85f8-4849-44fe-8977-a11527e6693a)

**Comment by HIllya51** [comment]
I can't understand what you mean, so I made it simple according to my ideas.

**Comment by XiaoXiaoYanHe** [comment]
> 我不明白你的意思，所以我按照我的想法把它简化了。

关于屏幕中间的“游戏选项、引导、物品说明”翻译问题
当前HOOK和OCR实际上只能读取“游戏对话”，HOOK可以读取选项，但常常混做一团，分辨起来很吃力。
某软件的解决方案，“OCR设置”下添加“固定截图/游戏截图”选项，点开单独给界面——序列号01 丨 自定义名称 丨 固定截图区域 丨快捷键自定义 alt+1
个人通过其他软件，快捷键-划拉出翻译基本够用，毕竟频率不高，固定截图反倒麻烦。 
所以，单纯加一个“快捷键截图翻译”基本够用，解决与原本的自动翻译的冲突就好，手动截图后暂停自动翻译-键鼠按动恢复。

**Comment by HIllya51** [comment]
> In numerous games, particularly those featuring intricate interfaces or dialogue boxes, players frequently encounter multiple sections of text they might wish to translate individually. For instance, various characters might be speaking simultaneously, or there could be in-game instructions dispersed across different areas of the screen. To elevate the gaming experience for users, I propose integrating support for scanning multiple zones simultaneously, as opposed to the current limitation of scanning just one zone at a time. This enhancement could entail implementing a multi-select functionality, enabling users to designate and translate multiple zones concurrently, rather than being confined to selecting only one.
> 
> 다양한 게임에서, 특히 복잡한 인터페이스나 대화 상자가 있는 게임에서 플레이어들은 자주 개별적으로 번역하고 싶은 텍스트 부분을 여러 번 만납니다. 예를 들어, 여러 캐릭터가 동시에 말할 수도 있고, 게임 안내가 화면의 다른 영역에 흩어져 있을 수도 있습니다.
> 
> 사용자들의 게임 경험을 높이기 위해, 현재 한 번에 한 영역만 스캔할 수 있는 제한을 해제하고 여러 영역을 동시에 스캔할 수 있도록 지원을 통합하는 것을 제안합니다. 이 개선은 다중 선택 기능을 구현하여 사용자가 한 번에 여러 영역을 지정하고 번역할 수 있도록 하는 것을 포함할 수 있으며, 한 가지만 선택할 수 있도록 제한되지 않도록 할 것입니다.

alright，actually now has already supportted multi-select

**Comment by HIllya51** [comment]
> > 我不明白你的意思，所以我按照我的想法把它简化了。
> 
> 关于屏幕中央“选项、引导、物品说明”的翻译问题 当前HOOK和OCR只能读取“游戏对话”，HOOK可以读取选项，但常常混做一团，分辨起来很吃力。 某软件的解决方案，“OCR设置”下添加“固定截图/游戏截图”选项，点开单独给界面——序列号01 丨 自定义名称 丨 固定截图区域 丨快捷键自定义 alt+1 个人通过其他软件，快捷键-划拉出翻译基本够用，毕竟频率不高，固定截图反倒麻烦。 所以，单纯加一个“快捷键截图翻译”基本够用，解决与原本自动翻译的冲突就好，手动截图后暂停自动翻译-键鼠按动恢复。

可能你说的这个功能早就已经包含了，不过藏得比较深，界面设置->窗口按钮设置->进行一次OCR，感觉和你说的差不多
事实上有很多隐藏功能，我不说你们基本不可能知道2333

**Comment by HIllya51** [comment]
you can find it in ocr settings.
