### ISSUE TITLE
关于aabbcc—abc预处理测试中发现的小问题（重复次数超过2 预处理就无法正常运行）

### ISSUE THREAD

**Issue by chibayuna** [HIllya51/LunaTranslator#524]
首先感谢一下大佬的神速，发现更新后今天我测试了一下文本框只读功能和aabbcc—abc预处理的保持未重复文本功能，在使用中发现了aabbcc—abc预处理的一个小问题，那就是（重复次数超过2）预处理就无法运行，虽然不知道算不算bug不过还是在这里反馈一下。
起因是发现更新后的aabbcc—abc预处理默认设置（重复次数为1）遇到如下图演示的（非连续待处理文本）运行后无法正常处理
![20240221185221](https://github.com/HIllya51/LunaTranslator/assets/160449286/7a55b3a6-d5fb-45b4-af8a-74e3fc1a93cb)
但预处理默认设置（重复次数为1）却可以正常处理（连续待处理文本）
![20240221191837](https://github.com/HIllya51/LunaTranslator/assets/160449286/9aee6add-73b7-4a44-bebd-91f458b9975a)
在将重复次数设置为2后，原本（重复次数为1）不能处理的（非连续待处理文本）运行后可以被正常处理
![20240221185307](https://github.com/HIllya51/LunaTranslator/assets/160449286/c3be6e78-3106-4d8a-9455-99656ef02df2)
为了试验预处理重复次数超过2的效果，之后我用3-5分别测试了两种文本（连续待处理文本）与（非连续待处理文本），意外发现预处理重复次数超过2后便无法正常运行，虽然这只是一个小问题，不过还是随手反馈一下。
![20240221185519](https://github.com/HIllya51/LunaTranslator/assets/160449286/cfebd63d-5e7a-42b0-b3b7-d825c4eb9ee9)
![20240221192924](https://github.com/HIllya51/LunaTranslator/assets/160449286/fb3f7104-1b02-420a-b3d0-e5019e2e5beb)

**Comment by HIllya51** [comment]
😑你这例子里面重复次数是2，你设置成3肯定不行啊。。。

**Comment by chibayuna** [comment]
我重新测试了一下3次重复的文本，确实可以正常使用， 是我一开始理解有误，我以为重复次数是指预处理的运行次数，现在才发现是指重复字数的数量，实在不好意思，感觉自己犯了个蠢。
文本框编辑现在是设置为切换文本条目后，自动覆盖已编辑内容吗？我一开始还奇怪开启了文本框编辑，怎么其他文本条目还在加载缓存，后来才发现原来是采用了自动覆盖来避免文本条目缓存过多。

**Comment by HIllya51** [comment]
> 文本框编辑现在是设置为切换文本条目后，自动覆盖已编辑内容吗？我一开始还奇怪开启了文本框编辑，怎么其他文本条目还在加载缓存，后来才发现原来是采用了自动覆盖来避免文本条目缓存过多。

啥意思，你想问什么捏。。
