### ISSUE TITLE
app keeps getting blocked

### ISSUE THREAD

**Issue by qgdsqgs** [HIllya51/LunaTranslator#525]
chrome won't allow installation an virus total gives a lot of red
![Capture d’écran_22-2-2024_201715_www virustotal com](https://github.com/HIllya51/LunaTranslator/assets/138653446/6a6b6968-a18b-44f9-8b53-f4009f31368f)

**Comment by HIllya51** [comment]
If you don't want to use it, don't use it. This is an open-source software. You said it has a virus. Do you have a virus in your mind?🙃
