### ISSUE TITLE
Error with fb_nllb_translate Translator

### ISSUE THREAD

**Issue by DarkVN101** [HIllya51/LunaTranslator#526]
An error happens in offline translation, I want to translate from Japanese to Spanish and the translation text comes out in English. Is there a solution or a file that I have to modify?

**Comment by HIllya51** [comment]
what is "fb_nllb_translate"？

**Comment by HIllya51** [comment]
I noticed that "fb_nllb_translate" is supported by "OneRingTranslator". You should find help at https://github.com/janvarev/OneRingTranslator/issues rather than me because I never used it.
