### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by creature93x** [HIllya51/LunaTranslator#527]
I suggest adding these features to the OCR multi-region option:

Option to close a selected regions by a button(close button) or a shortcut(like double clicking the region).
Remembering the last drawn boxes positions when the program reopens.
Rather than emptying the translation window, append to it because sometimes it is so hard to keep up.
Option to show translation result of a region with the region number 

these features will enhance the application a lot

**Comment by HIllya51** [comment]
what is "Rather than emptying the translation window, append to it because sometimes it is so hard to keep up."
and "Option to show translation result of a region with the region number"？ I can't understand.

**Comment by HIllya51** [comment]
I understand. But I won't do it because it's too complicated to implement.

For "Rather than emptying the translation window, append to it because sometimes it is so hard to keep up" , you can see past records in historical translation.

**Comment by HIllya51** [comment]
"Instead of erasing everything in the translation box, just add the new translations." You can see them in Historical translation.
"give ocr box a number and in translation window show the box number+translation" it's too complicated to implement, so I don't plan to do it.

**Comment by HIllya51** [comment]
In fact, this is a software mainly designed for visual novels, and some of your suggestions are too far from this application scenario, which may even disrupt the original usage. Therefore, I cannot fully adopt your suggestion.

**Comment by HIllya51** [comment]
In fact, this is a software mainly designed for visual novels, and some of your suggestions are too far from this application scenario, which may even disrupt the original usage. Therefore, I cannot fully adopt your suggestion.

**Comment by HIllya51** [comment]
In fact, this is a software primarily designed for visual novels, and in most cases we use HOOK instead of OCR. I cannot compromise the original user experience just to make OCR more universal

**Comment by HIllya51** [comment]
I have supported "Option to close a selected regions by a button(close button) or a shortcut(like double clicking the region)."
and "Remembering the last drawn boxes positions when the program reopens.".
"Rather than emptying the translation window, append to it because sometimes it is so hard to keep up." and  "Option to show translation result of a region with the region number" will not be supported in the short term.
