### ISSUE TITLE
OCR选取框颜色闪退和界面颜色设置问题

### ISSUE THREAD

**Issue by SaraKale** [HIllya51/LunaTranslator#528]
当前版本：v2.37.0

### OCR选取框选择其他颜色会闪退

因为默认是黑色框，在黑夜背景下看不太清有没有画框，想换成别的颜色，结果按确定它就闪退了……
![ocr](https://github.com/HIllya51/LunaTranslator/assets/42092947/1390b098-b2fa-4920-bee9-0787f5502418)

### 界面设置按钮过淡颜色会看不到

界面设置的颜色我选择了一个颜色后，按钮也会跟着变，如果选了白色就会看不到，感觉可以不用同时改变按钮颜色，因为点击按钮后就知道之前是设置什么颜色了。
![color](https://github.com/HIllya51/LunaTranslator/assets/42092947/51d9c042-b374-4a1d-ab0c-d26b8a86eb0a)

其他的设置暂时没遇到问题。

**Comment by HIllya51** [comment]
其实所有带颜色的按钮你设置成背景色之后都看不到了，包括翻译的颜色等等。
但你唯独可以看到“特殊字体样式填充颜色”这个颜色选择按钮有个明显的区分，这是因为这个按钮是默认白色，所以专门做了区分，但看起来很丑陋。
所以这个懒得改了，因为没有好的办法。反正猜也能猜到旁边有个按钮。

**Comment by SaraKale** [comment]
啊，才发现“特殊字体样式填充颜色”多了方形按钮，这个可以诶！选择白色依然能看清，噢噢原来是这样，没有好的方法，没事，我备忘下，回头告诉小伙伴，这工具是我第一次使用，还蛮好用的！还有多语言界面和多语言翻译，我和小伙伴正好需要，非常感谢您的开发！

**Comment by HIllya51** [comment]
主要是我审美太耿直了不太会设计2333

**Comment by SaraKale** [comment]
我觉得设计还行呀，还蛮好看的！刚看到更新了，这次OCR范围框颜色不闪退啦！太感谢你了！送上小花花以表谢意～ :hibiscus:
