### ISSUE TITLE
为什么会在这一行中断运行

### ISSUE THREAD

**Issue by Stillily** [HIllya51/LunaTranslator#529]
我down了代码下来运行，试了好几次了，每次都会在雪菜说完这句话后程序崩溃
![WeChat截图_20240224141834](https://github.com/HIllya51/LunaTranslator/assets/9026752/ec66dcbd-9758-4e1d-8613-33ff77319913)

控制台的输出如下
![WeChat截图_20240224141817](https://github.com/HIllya51/LunaTranslator/assets/9026752/f725bbe4-d875-466f-b6f1-7d2450248b75)

**Comment by HIllya51** [comment]
请给我【游戏资源】和【跳转到这里的存档】以及你的【userconfig】

**Comment by Stillily** [comment]
游戏还在上传，后面又有个地方也出现同样问题，感觉应该是这个・字符导致的
![WeChat截图_20240224174631](https://github.com/HIllya51/LunaTranslator/assets/9026752/60e04d4b-4120-4f03-b69a-219acc6b27d4)

![WeChat截图_20240224174601](https://github.com/HIllya51/LunaTranslator/assets/9026752/5ab5164f-a0d5-4828-8d44-2693659e228d)

**Comment by Stillily** [comment]
【游戏资源】和【跳转到这里的存档】以及【userconfig】
https://pan.quark.cn/s/f161f68a7c7c

**Comment by HIllya51** [comment]
你还要我去开个会员吗难道。算了，你光把userconfig和存档给我吧，资源我自己去找总行了吧？

**Comment by Stillily** [comment]
打扰了，刚刚试一下把自己加的代码删了就正常了

**Comment by HIllya51** [comment]
> 打扰了，刚刚试一下把自己加的代码删了就正常了

emmm，有点小好奇加的什么代码👀

**Comment by Stillily** [comment]
> > 打扰了，刚刚试一下把自己加的代码删了就正常了
> 
> emmm，有点小好奇加的什么代码👀

 就是输出进文件没用utf8而已，python没用习惯，原来它不会自动报哪行错的，刚开始以为自己就写这么简单的代码肯定没问题所以是别的地方出问题，以后要加try except。幸好发现了不然要让你白折腾了。

**Comment by HIllya51** [comment]
> > > 打扰了，刚刚试一下把自己加的代码删了就正常了
> > 
> > 
> > emmm，有点小好奇加的什么代码👀
> 
> 就是输出进文件没用utf8而已，python没用习惯，原来它不会自动报哪行错的，刚开始以为自己就写这么简单的代码肯定没问题所以是别的地方出问题，以后要加try except。幸好发现了不然要让你白折腾了。

pyqt有点问题，在他的signal函数和event里面写的代码出了错，经常不报错就写个unhandled python exception，我经常遇到，挺恶心的
