### ISSUE TITLE
[BUG] wrong translation text direction

### ISSUE THREAD

**Issue by qgdsqgs** [HIllya51/LunaTranslator#530]
Right now, the translation shows up from the left side to the right side (LTR), but that's not right for Arabic and Hebrew and many more languages. These languages should go from right to left (RTL) to be easier to read and understand. Just changing the alignment to right isn't good enough because it can make things messy when English words mix with Arabic or Hebrew.

**Comment by HIllya51** [comment]
Even for some large companies, supporting Arabic is a complex matter, and I am only creating software for free, so I have no intention of doing such a thing

**Comment by qgdsqgs** [comment]
it is not just Arabic. if you can just please guide me to the file of the gui where the translation is displayed i can fix thanks.

**Comment by qgdsqgs** [comment]
Here are my added lines to ensure right-to-left (RTL) text is displayed correctly in case anyone is interested:
in textbrowser.py:

```
def append(self, x, tag, origin):
		if self.cleared:
            _space = ''
            self.blockcount = 0
            self.b1 = 0
        else:
            _space = '\n'
            self.b1 = self.textbrowser.document().blockCount()
        self.cleared = False

      ----->  font = QFont()
      ----->  font.setBold(globalconfig['showbold'])
      ----->   font.setFamily(globalconfig['fonttype2'])
      ----->   font.setPointSizeF(globalconfig['fontsize'])
      ----->   x = f"<p dir='rtl'>{x}</p>"
      ----->   if self.needdouble:
      ----->       self.textbrowserback.setFont(font)
      ----->      self.textbrowserback.setHtml(_space+x)
      ----->   self.textbrowser.setFont(font)
      ----->   self.textbrowser.setHtml(_space+x)
```
in  transhist.py:
   def getnewsentence(self,sentence):

```
        sentence= '<hr>' if globalconfig['hist_split'] else '\n'+sentence
        if self.hiderawflag:
            sentence=''
        -----> self.textOutput.append(f"<p dir='rtl'>{sentence}</p>")
    def getnewtrans(self,api,sentence):
        if self.hideapiflag:
            res=sentence
        else:
            res=api+'  '+sentence
        -----> self.textOutput.append(f"<p dir='rtl'>{res}</p>")

```

**Comment by HIllya51** [comment]
If necessary, you can fork one yourself. This modification is not compatible with many of the original features, so I cannot adopt it.

**Comment by qgdsqgs** [comment]
ok i did find a much elegant solution all i had to do is add this unicode **'\u200F'** to the translation and use ftfy lib like this:
in transhist:
```
 def getnewsentence(self,sentence):
       sentence= '<hr>' if globalconfig['hist_split'] else '\n'+sentence
       if self.hiderawflag:
           sentence=''
       -----> self.textOutput.append(ftfy.fix_text('\u200F'+sentence))
   def getnewtrans(self,api,sentence):
       if self.hideapiflag:
           res=sentence
       else:
           res=api+'  '+sentence
       -----> self.textOutput.append(ftfy.fix_text('\u200F'+res))

```
in textbrowser.py:
```
        if self.needdouble:
   ---->         self.textbrowserback.insertPlainText(_space+ftfy.fix_text('\u200F'+x))
  ----->      self.textbrowser.insertPlainText(_space+ftfy.fix_text('\u200F'+x))
```
