### ISSUE TITLE
Add custom translator with REST API server with multi-language offline translation capacity

### ISSUE THREAD

**Issue by DarkVN101** [HIllya51/LunaTranslator#531]
Hillya, You could add a custom offline translator option with web app rest api server capable of using huggingface AI-trained models, there are many on github, I think it would be very useful
here are some examples...

https://github.com/thammegowda/nllb-serve
https://github.com/winstxnhdw/nllb-api
https://github.com/LibreTranslate/LibreTranslate

(By the way, I'm waiting for a response about OneRingTranslator issues but I think this is a good option)

Certainly you program is the best translator, I recommend it 100%.

**Comment by HIllya51** [comment]
I don't want to add so many interfaces with almost identical functions, it doesn't make much sense.

Moreover, the calls to the few things you listed are too simple, so I don't need to build them in. You can use "Custom translator" to call them yourself within 5 lines of code

If you don't know how to write code, you can ask chatgpt to write such a simple code for you.

![批注 2024-02-25 101847](https://github.com/HIllya51/LunaTranslator/assets/101191390/940154ca-c728-456c-adde-8fca0ac5aeb2)

**Comment by DarkVN101** [comment]
I had not seen this option but when I load it with my interface in Spanish, that window falls t_t 
![2024-02-25_002216](https://github.com/HIllya51/LunaTranslator/assets/159744725/d42d42ec-f287-47d1-87a4-7150d3e1bdb9)

**Comment by HIllya51** [comment]
🙃This is obviously the English. How can you find it on the Spanish? Switch to English and check it and switch back to Spanish.
Click the gear near and it will auto open the file which you need to add code. Or else you can find any useless file in "LunaTranslator/translator/*.py" and replace the origin code with your code.

**Comment by DarkVN101** [comment]
It is not a language configuration problem... a black screen appears when you click on the custom translator gear...

https://github.com/HIllya51/LunaTranslator/assets/159744725/1451ec08-ed1b-43d0-a71c-1a51e0e0e6c9

**Comment by HIllya51** [comment]
open "userconfig/selfbuild.py"
