### ISSUE TITLE
最新版的被报毒了，不知道为啥

### ISSUE THREAD

**Issue by wycstc353** [HIllya51/LunaTranslator#532]
最新版的被报毒了，不知道为啥，以前的版本都没报过，最新版的一下载就被报毒了，反馈下，反正我之前的版本还能用，以防万一，要不作者你坚持下？

**Comment by HIllya51** [comment]
直接信任啊，难道你觉得有病毒？反正我是没兴趣去做免杀。

**Comment by wycstc353** [comment]
> 直接信任啊，难道你觉得有病毒？反正我是没兴趣去做免杀。
 主要从来没遇到过下载了压缩包就直接报毒的，一般都是解压后报毒，所以我还是来反馈了一下，反正新更新版本的是ocr的，ocr我也不用，所以我就反馈下和你说下

**Comment by HIllya51** [comment]
不加密压缩和不压缩对杀毒软件来说没什么区别
