### ISSUE TITLE
Magpie缩放时，点击到翻译框，Magpie会退出缩放

### ISSUE THREAD

**Issue by lawiest** [HIllya51/LunaTranslator#533]
使用Magpie缩放时，点击到翻译框，Magpie会退出缩放，自带的缩放有些问题4K不能全屏只有中间有图像四周黑的。选择外部缩放路径LunaTranslator会闪退。很好的软件，但是这个不能在缩放下调整翻译框很痛苦。

**Comment by HIllya51** [comment]
“自带的缩放有些问题4K不能全屏只有中间有图像四周黑的”，可能是你没有正确选择默认降采样效果之类的。因为不好设计所以也没有做更复杂的设置界面，但你其实可以把你下载的Magpie的config.json的内容复制到userconfig/magpie10_config.json中（关闭软件后复制）（注意是userconfig/magpie10_config.json，不要覆盖userconfig/config.json了）

**Comment by HIllya51** [comment]
测试了一下还真会闪退。等下我修一下。

**Comment by HIllya51** [comment]
md，不知道什么时候不小心把这个默认配置的键给丢掉了，好弱智啊我hh

**Comment by HIllya51** [comment]
可以了，你重新下载最新版，使用软件来引导启动magpie全屏，就不会退出缩放了。

**Comment by HIllya51** [comment]
已修

**Comment by lawiest** [comment]
缩放问题还是没有解决，复制了config.json也还是四周黑，现在选外部Magpie虽然不会奔溃，但是没效果，还是会退出缩放

**Comment by HIllya51** [comment]
你要用软件里的那个缩放按钮进行缩放而非用magpie的快捷键缩放，否则不行。

**Comment by lawiest** [comment]
是用的软件里的那个缩放按钮，都试过，都不行

**Comment by HIllya51** [comment]
1、magpie是否以管理员启动？
2、你看一下files/plugins里面是否有shareddllproxy64.exe和hookmagpie.dll？

**Comment by lawiest** [comment]
是的 shareddllproxy64.exe和hookmagpie.dll都有，是不是和版本有关啊，我用的最新的magpie

**Comment by lawiest** [comment]
是管理员启动的

**Comment by HIllya51** [comment]
你改成非管理员启动magpie试试

**Comment by HIllya51** [comment]
你把userconfig和你magpie的config都发给我看一下。

**Comment by plainround** [comment]
不能放大到全屏，我认为问题是这样的。
anime4k放大倍数是2倍，窗口分辨率低于1080p的游戏，在一次anime4k放大下本来就是无法放大到4k全屏的。
对于1080p以上的游戏，可以这么写
``
        {
            "name": "galgame-one step upscale",
            "effects": [
                {
                    "name": "Anime4K\\Anime4K_Upscale_VL"
                }
            ]
        },
``
对于540p至1080p的游戏，可以这么写，Anime4K两倍，ACNet再放大两倍，这样就可以放大4倍，一般都够用了
``
        {
            "name": "galgame",
            "effects": [
                {
                    "name": "Anime4K\\Anime4K_Upscale_VL"
                },
                {
                    "name": "ACNet"
                }
            ]
        },
``
如果更小的游戏也需要放大至4k全屏，可以再加一个任意比例放大的算法，比如fsr
``
        {
            "name": "test",
            "effects": [
                {
                    "name": "Anime4K\\Anime4K_Upscale_VL"
                },
                {
                    "name": "ACNet"
                },
                {
                    "name": "FSR\\FSR_EASU",
                    "scalingType": 1,
                    "scale": {
                        "x": 1.0,
                        "y": 1.0
                    }
                }
            ]
        }
``
以上都可以在magpie gui里调整好。
降采样算法这么写，个人认为Lanczos效果好一点，降采样效果应该是无法放大的。
``
    "downscalingEffect": {
        "name": "Lanczos"
    },
``
具体可以看magpie效果介绍，有的效果支持任意倍数放大，有的效果只支持2倍https://github.com/Blinue/Magpie/wiki/%E5%86%85%E7%BD%AE%E6%95%88%E6%9E%9C%E4%BB%8B%E7%BB%8D

LunaTranslator的magpie10_config.json里
这两个应该可以任意分辨率，但画质太差了,
``
        {
            "name": "Lanczos",
            "effects": [
                {
                    "name": "Lanczos",
                    "scalingType": 1,
                    "scale": {
                        "x": 1.0,
                        "y": 1.0
                    }
                }
            ]
        },
        {
            "name": "FSR",
            "effects": [
                {
                    "name": "FSR\\FSR_EASU",
                    "scalingType": 1,
                    "scale": {
                        "x": 1.0,
                        "y": 1.0
                    }
                },
                {
                    "name": "FSR\\FSR_RCAS",
                    "parameters": {
                        "sharpness": 0.8700000047683716
                    }
                }
            ]
        },
``
还有几个都是放大两倍的，所以小于1080p的游戏肯定放不满全屏
``
        {
            "name": "FSRCNNX",
            "effects": [
                {
                    "name": "FSRCNNX\\FSRCNNX"
                }
            ]
        },
        {
            "name": "ACNet",
            "effects": [
                {
                    "name": "ACNet"
                }
            ]
        },
        {
            "name": "Anime4K",
            "effects": [
                {
                    "name": "Anime4K\\Anime4K_Upscale_Denoise_L"
                }
            ]
        },
``
--
所以需要先关闭LunaTranslator，删除LunaTranslator\userconfig\magpie10_config.json，然后修改LunaTranslator\files\defaultconfig\magpie10_config.json
ACNet修改，用于放大4倍
``
        {
            "name": "ACNet",
            "effects": [
                {
                    "name": "Anime4K\\Anime4K_Upscale_VL"
                },
                {
                    "name": "ACNet"
                }
            ]
        },
``
打开LunaTranslator，效果选择ACNet这样就没问题了。
1080p游戏还请切换为Anime4K效果放大两倍，不然白放大还影响画质。软件原来的默认设置是Anime4K_Upscale_Denoise_L。
如果好显卡随便开Anime4K_Upscale_UL就可以了，如果核显就用Anime4K_Upscale_S

**Comment by HIllya51** [comment]
luna内置的magpie就是我自己实现的一个cli版本，和原版按理说没有区别。但我刚才想到了一个可能性，就是你magpie的”配置文件“的设置可能不是在“默认“上进行的，而是在你新建的配置上进行的，而luna只会读取”默认“配置，所以复制过去才会有有不一样的表现。

然后对于外部magpie的话，你不要用管理员权限启动magpie。然后如果你magpie版本不是0.10.5可能也有问题。

还不行我也不知道哪里可能有问题了，我这里全都正常。

**Comment by lawiest** [comment]
那应该是默认配置问题，应该最新的magpie不提供默认配置的，必须自己配

**Comment by HIllya51** [comment]
不是，我看错了，和默认配置没有关系。所以说我要你看一下你magpie的config啊，你咋不给我啊。。。。

**Comment by lawiest** [comment]
在搬砖阿？最近有些忙，今晚回去给你，其实我还是想用外部magpie功能，只要不退出缩放就好，团子这块就做的比较好。

**Comment by lawiest** [comment]
这是你的config
[config.json](https://github.com/HIllya51/LunaTranslator/files/14433998/config.json)
[magpie10_config.json](https://github.com/HIllya51/LunaTranslator/files/14433999/magpie10_config.json)

这是magpie的
[config.json](https://github.com/HIllya51/LunaTranslator/files/14434007/config.json)

两个config.json是一样的，因为我之前按照你说的复制过来的

**Comment by lawiest** [comment]
那个，刚刚，就在刚刚我又试了下，居然可以啊，没有退出缩放！不是很明白为什么，感谢大佬。

**Comment by HIllya51** [comment]
。。。
