### ISSUE TITLE
setting up dev environments 

### ISSUE THREAD

**Issue by creature93x** [HIllya51/LunaTranslator#534]
i am trying to do some modification on the code but i am getting this error when i try to run the run.bat, run37.bat and run3732.py
![image](https://github.com/HIllya51/LunaTranslator/assets/38745587/d8d65a18-1aab-46d7-85a8-4d5b334b7020)

and when i try to build the project i did manage to launch build32.bat and build64.bat successfully but when i try to pack using either pack32.cmd or pack64.cmd i get this error:
![image](https://github.com/HIllya51/LunaTranslator/assets/38745587/74433c0a-4bf2-4726-9ae1-b06213e9e774)

i am guessing that i need some additional files? if so were to get them thanks in advance.

**Comment by HIllya51** [comment]
download the releases and copy “files” directory, there include some precompiled dlls by me.
or else you can enter “plugins” directory and compile the c++ code by yourself.

**Comment by creature93x** [comment]
ok this did fix the run.bat issue the i had but no luck with pack32.cmd nor pack64.cmd

![image](https://github.com/HIllya51/LunaTranslator/assets/38745587/e562959c-abfd-4489-ac9c-eeaf4debc336)

**Comment by HIllya51** [comment]
copy this file from releases to target directory.

**Comment by HIllya51** [comment]
these file is a precompiled c++ program in plugins. if you don't want to compile, just copy it from releases.
