### ISSUE TITLE
magpie缩放时不能全屏展示有黑边

### ISSUE THREAD

**Issue by plainround** [HIllya51/LunaTranslator#535]
https://github.com/HIllya51/LunaTranslator/issues/533
这个里面也提到这个问题，我检查了files/plugins的文件，两个程序都是管理员运行的。
我的做法是添加了magpie10路径，magpie原生可以全屏，缩放按钮不能全屏，magpie设置移过去也一样。
效果是这样，1080p游戏，4k屏幕
![屏幕截图(155)](https://github.com/HIllya51/LunaTranslator/assets/33506166/12a671d4-e14d-4c92-8665-2cb536b1bb85)

还想请教下大大隐藏按钮栏是怎么做到的，没找到怎么设置，我觉得理想的是按钮栏透明，鼠标移上去时展示，鼠标离开过几秒消失。
效果是看到有人可以这样，感觉很美观
https://user-images.githubusercontent.com/116066807/233630129-07a32792-2ac9-4ff5-aa45-cd4cc8e53243.jpg

**Comment by HIllya51** [comment]
你把userconfig和你magpie的config都发给我看一下。

**Comment by HIllya51** [comment]
<img width="823" alt="屏幕截图 2024-02-27 122856" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/686816fa-8daa-4790-aad9-eb83b51705f9">

**Comment by plainround** [comment]
> 你把userconfig和你magpie的config都发给我看一下。

[config.json](https://github.com/HIllya51/LunaTranslator/files/14414664/config.json)
[magpie10_config这是从magpie复制来的.json](https://github.com/HIllya51/LunaTranslator/files/14414665/magpie10_config.magpie.json)
[magpie10_config这是软件自带的.json](https://github.com/HIllya51/LunaTranslator/files/14414666/magpie10_config.json)

原来锁定工具栏是这个效果，感谢大佬指点

**Comment by plainround** [comment]
我下载的releases里的版本，json里添加了原来设置会报错的magpie路径

**Comment by HIllya51** [comment]
你这没设置外部magpie的路径啊

**Comment by plainround** [comment]
> 你这没设置外部magpie的路径啊

之前传的defaultconfig文件夹的内容
浪费您时间了，不好意思

已经搞懂了，是我自己的问题。千恋万花用日本版没有固定分辨率，打开时窗口分辨率小于1080。我以为和steam版一样打开就是1080...

非常感谢帮助

**Comment by plainround** [comment]
发现一个bug
开启软件，点击“打开保存的游戏_新”，会打开已保存的游戏窗口

点击游戏设置，会打开设置窗口

修改路径F:\_Visual Novel\SenrenBanka 1.2 CHS\SenrenBanka.exe
至F:\_Visual Novel\SenrenBanka\SenrenBanka.exe

点击关闭设置窗口

再次点击游戏设置，这时软件会闪退

**Comment by HIllya51** [comment]
建议不要修改路径。可以删掉重新添加。不然我还得处理各种多线程并行问题。

**Comment by plainround** [comment]
好的，谢谢
