### ISSUE TITLE
语音合成可否加入Bert-VITS2

### ISSUE THREAD

**Issue by barbasting** [HIllya51/LunaTranslator#537]
请问大佬，语音合成里可否加入Bert-VITS2用自己训练的模型来读呢？

**Comment by HIllya51** [comment]
给我个链接看看

**Comment by barbasting** [comment]
https://github.com/fishaudio/Bert-VITS2/releases/tag/v2.3 本地训练的这种

**Comment by HIllya51** [comment]
我对此没啥兴趣，还要配环境下模型太麻烦了。你要是会写代码就参考这个自己写一下吧。
https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/LunaTranslator/tts/youdaotts.py
然后 https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/files/defaultconfig/config.json#L611 在这里加一条就行了。

**Comment by barbasting** [comment]
好的，收到，感谢指教
