### ISSUE TITLE
两个小问题：全屏模式下历史窗口未能前置 和 貌似锁定工具栏按钮无效

### ISSUE THREAD

**Issue by EXBJAN** [HIllya51/LunaTranslator#54]
目前在翻译器全屏模式下仅有历史翻译窗口不能前置了，望调整

锁定工具栏按钮的功能是什么? 我的理解是上锁状态下工具栏不可拖动，如果真是如此，该功能貌似无效

最后，翻译器全屏真的很好用了，大佬棒棒！现在全游戏默认用翻译器全屏了。

**Comment by HIllya51** [comment]
好的。
