### ISSUE TITLE
hook不到死印:NG的文本

### ISSUE THREAD

**Issue by lawiest** [HIllya51/LunaTranslator#540]
![QQ截图20240229201428](https://github.com/HIllya51/LunaTranslator/assets/50625377/752390fe-af0f-4e35-972e-346155d4d013)
hook不到NG的日文文本，使用特殊码文本所有也啥都都不到

**Comment by HIllya51** [comment]
资源。

**Comment by HIllya51** [comment]
我没会员。。。

**Comment by HIllya51** [comment]
okk

**Comment by HIllya51** [comment]
已支持
