### ISSUE TITLE
LunaTranslator

### ISSUE THREAD

**Issue by romans77-pixel** [HIllya51/LunaTranslator#541]
Hello! I have a problem, I can’t add Chinese from Github. Message "not found"... Need help
![Скриншот 29-02-2024 192700](https://github.com/HIllya51/LunaTranslator/assets/161745289/76194cdb-529d-4287-9c28-f5d10df28f83)

**Comment by HIllya51** [comment]
Can you explain it clearly?

**Comment by romans77-pixel** [comment]
sorry, reinstalled, everything is fine
