### ISSUE TITLE
text not fully captured

### ISSUE THREAD

**Issue by creature93x** [HIllya51/LunaTranslator#542]
when i use ocr with this text it  doesn't capture the end of the sentence:

https://github.com/HIllya51/LunaTranslator/assets/38745587/0b76f2aa-0c6e-4117-8867-29873aa626af

![1](https://github.com/HIllya51/LunaTranslator/assets/38745587/598d6b43-b506-4116-8cf3-a555c9d1c0ee)
![2](https://github.com/HIllya51/LunaTranslator/assets/38745587/8fb3e7b5-14c1-4863-9985-792c10b1b2ce)
![3](https://github.com/HIllya51/LunaTranslator/assets/38745587/b8fedaa9-9280-43df-b336-51acf3e9bd2a)

**Comment by HIllya51** [comment]
Text input->OCR Settings->OCR automation method->Periodic execution

**Comment by creature93x** [comment]
that is what i did yet  i lowered it to 0.1 but the problem remains

**Comment by creature93x** [comment]
i am guessing it is a buffer issue or something

**Comment by HIllya51** [comment]
I thought you should know that adjusting the text display speed to the fastest when using OCR is common sense.

**Comment by creature93x** [comment]
i can't control the speed of text in the game... i have tried the period execution with different values no success.

**Comment by creature93x** [comment]
some games are designed like this

**Comment by creature93x** [comment]
besides only the last words are not captured

**Comment by HIllya51** [comment]
Re download the latest version and set "Text similarity threshold" to lower value.

**Comment by creature93x** [comment]
ok now it works but the lines are merged there is no space between them
![Annotation 2024-03-02 074324](https://github.com/HIllya51/LunaTranslator/assets/38745587/eeec97b6-433c-4a86-bd55-f21c0a69806e)
![Annotation 2024-03-02 074405](https://github.com/HIllya51/LunaTranslator/assets/38745587/65c83a1b-4acc-4b16-bfa7-8b6fef2cb203)

**Comment by HIllya51** [comment]
what's your current source language?

**Comment by creature93x** [comment]
english

**Comment by creature93x** [comment]
it fine my bad all works good thanks
