### ISSUE TITLE
json翻译文件根据游戏自动切换

### ISSUE THREAD

**Issue by owninnn** [HIllya51/LunaTranslator#544]
现在有不少gpt翻译是通过外挂的方式提供，能否添加一个功能记忆上次该游戏的所选择的翻译文件从而自动切换呢？

如果这样涉及的改动比较大，也可以在当前游戏所在目录，检测是否存在某个约定好的文件名称如“translated_db.json”

**Comment by HIllya51** [comment]
现在你可以在游戏的设置里面为游戏设置专用的预翻译文件
