### ISSUE TITLE
麻烦大佬有空添加个 已保存游戏里的游戏 移动图标位置的功能

### ISSUE THREAD

**Issue by k40free** [HIllya51/LunaTranslator#545]
我想让同一类型的游戏放在一起 看着没这么乱

**Comment by HIllya51** [comment]
没啥用啊，一运行就自动挪到最前面去了

**Comment by k40free** [comment]
用处还是有一些的， 大部分游戏玩完之后基本也就收藏不碰了，偶尔玩一下也可以移动回去

**Comment by HIllya51** [comment]
我建议你直接关掉程序以后去修改userconfig/savehook_new_1.39.4.json里这块地方：
<img width="778" alt="屏幕截图 2024-03-03 214850" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/e3518c2c-e372-482a-88df-5ead5e56a9a0">
这个list就是游戏的顺序。
我不是很好改gui，因为这部分gui里面现在都有一大坨我不知道该咋修的bug，猛猛闪退。😂

**Comment by k40free** [comment]
好的，多谢大佬
