### ISSUE TITLE
功能请求：通过一个快捷键用日语语音朗读原文，另一个快捷键用英语语音朗读原文

### ISSUE THREAD

**Issue by ads233** [HIllya51/LunaTranslator#546]
看一些英日双语节目时有时候需要日语语音朗读示范，有时候需要英语语音朗读示范。

**Comment by HIllya51** [comment]
首先我不知道TTS里哪个是日语哪个是英语。这个功能我不知道如何设计。

**Comment by ads233** [comment]
好吧......那我开多另外一个软件来进行另一种语言的发音......

**Comment by HIllya51** [comment]
主要是你这个功能和galgame完全不沾边，我完全不知道怎么加进去。。。

**Comment by ads233** [comment]
其实我用其他软件的OCR后通过剪贴板把信息传递到LunaTranslator读取，然后想要运用不同快捷键触发LunaTranslator采用日语朗读剪贴板原文以及英语朗读剪贴板原文啦。暂时找到Balabolka 文本转语音来进行朗读英文，LunaTranslator负责朗读日文。
