### ISSUE TITLE
renpy8.0内嵌翻译是方块字

### ISSUE THREAD

**Issue by 2607627233** [HIllya51/LunaTranslator#547]
RT

**Comment by HIllya51** [comment]
如果源语言是英文的话，不支持中文字体

**Comment by HIllya51** [comment]
你可以尝试使用mtool来引导启动游戏，mtool会把游戏字体改掉

**Comment by 2607627233** [comment]
> 你可以尝试使用mtool来引导启动游戏，mtool会把游戏字体改掉
一起用总是报错

**Comment by HIllya51** [comment]
我正在研究如何动态修改renpy的字体，或许之后可以支持。

**Comment by HIllya51** [comment]
下载最新版，内嵌设置里面开启修改游戏字体就行了

**Comment by 2607627233** [comment]
> 下载最新版，内嵌设置里面开启修改游戏字体就行了

史诗级更新
