### ISSUE TITLE
A small text selection area.

### ISSUE THREAD

**Issue by 1N0NaMae** [HIllya51/LunaTranslator#548]
The problem is that the text is translated only in a small translation zone, if this zone is enlarged, nothing happens, the text is also not included in the text processing. I will additionally attach screenshots.

A small area is highlighted in the first screenshot and it is being translated.

In the second screenshot, the area is slightly larger, but the text is no longer translated and is not displayed in text processing.

I will be grateful if you help!

![B_aVmLtNLsU](https://github.com/HIllya51/LunaTranslator/assets/124863422/8944fb06-f28b-4cf2-8682-8a26c6b49bc1)
![rTrEikew4s4](https://github.com/HIllya51/LunaTranslator/assets/124863422/c3af6520-dfdc-4a51-b5ea-3e0b239bec8a)

**Comment by HIllya51** [comment]
Why you only select such a small area??

**Comment by 1N0NaMae** [comment]
> Why you only select such a small area??

Any other area that is larger than the first screenshot will not translate the text, I have tried different options. If the area is larger than the first one, then nothing happens.

**Comment by HIllya51** [comment]
click the first button to force it to run ocr

**Comment by 1N0NaMae** [comment]
If you are talking about starting the translation (update), then I also pressed it, nothing changed.

**Comment by HIllya51** [comment]
which ocr engine are you using? show me you ocr settings.

**Comment by 1N0NaMae** [comment]
I have a local ocr.
![W-UltJ0pUNo](https://github.com/HIllya51/LunaTranslator/assets/124863422/ce106f20-66db-4a30-b094-eb1a60dc12d5)
![qlJ3i1R_Mrk](https://github.com/HIllya51/LunaTranslator/assets/124863422/8780652f-ede0-44b1-9f77-b494c5f2d4ec)

**Comment by HIllya51** [comment]
I don't know the reason. Please pack "userconfig" directory and send it to me
<img width="988" alt="屏幕截图 2024-03-03 151356" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/adf11bb3-6722-4c97-b59c-f3834d473c32">

**Comment by 1N0NaMae** [comment]
I have installed windows ocr and everything is working correctly, thank you very much!)
