### ISSUE TITLE
新版本翻译无法使用的问题

### ISSUE THREAD

**Issue by UchiteZero** [HIllya51/LunaTranslator#549]
大佬你好，今天我下载了新版本的luna翻译器，但是翻译器里一直不出现翻译结果，查看调试输出那一栏里发现一只在报：TypeError: GetTranslationCallback() takes 10 positional arguments but 11 were given的错误，问了下朋友说这是传参出错了，于是我换了两周前的旧版本翻译又出来了，请问这是新版本翻译器的问题吗？

**Comment by HIllya51** [comment]
有点小bug，等下

**Comment by HIllya51** [comment]
你更新一下试试
