### ISSUE TITLE
建议可以自定义ocr边框颜色

### ISSUE THREAD

**Issue by FreelyMoon** [HIllya51/LunaTranslator#55]
如果游戏自带对话框是黑的，根本看不清ocr的边框，翻译选项时可以盲拉上去，但拉回去时要么翻译框框到了半截人名，要么翻译框偏左，翻译少半截,太费眼了。
感谢！
![1](https://user-images.githubusercontent.com/110982246/200951875-bbaa2085-12d3-42dd-bdc6-3ca18228fde4.png)

**Comment by HIllya51** [comment]
已修正
