### ISSUE TITLE
使用Sakura大模型翻译，在开启专有名词翻译功能之后，偶尔有一些名词会翻译成Z XB Z

### ISSUE THREAD

**Issue by BBBBBSM** [HIllya51/LunaTranslator#550]
![{B7061D76-252E-4509-A465-A0375FDD50BA}](https://github.com/HIllya51/LunaTranslator/assets/50542985/31a9cc86-870b-43e1-8264-c1315e77a927)
像这样，我将三国さん用专有名词功能指定翻译为三国同学
上一句还正常，下一句就变成了Z XB Z

**Comment by HIllya51** [comment]
没办法啊，这个我是抄的vnr里的做法，把名词替换成一般不会被翻译的一个字符串（ZXBZ，ZXCZ，ZXDZ……），然而没想到这样的字符串却被sakura修改了，那我也没办法啊，不这样做还能怎么做啊😂

**Comment by BBBBBSM** [comment]
> 没办法啊，这个我是抄的vnr里的做法，把名词替换成一般不会被翻译的一个字符串（ZXBZ，ZXCZ，ZXDZ……），然而没想到这样的字符串却被sakura修改了，那我也没办法啊，不这样做还能怎么做啊😂

原来如此 感谢答疑

**Comment by HIllya51** [comment]
除非api是支持自定义词典的（例如有道，可以在网页里面去加自定义词典，或者例如j北京7也可以自定义词典（这个格式是二进制的，更难复杂）），不然我只能【传入一个原文，得到一个翻译】，所以这是没有办法的事。

**Comment by BBBBBSM** [comment]
> 除非api是支持自定义词典的（例如有道，可以在网页里面去加自定义词典，或者例如j北京7也可以自定义词典（这个格式是二进制的，更难复杂）），不然我只能【传入一个原文，得到一个翻译】，所以这是没有办法的事。

https://books.fishhawk.top/workspace/sakura
我之前在用这个机翻机器人的术语表功能，使用Sakura翻译了一些较长的小说，替换没有出现bug

**Comment by HIllya51** [comment]
添加术语表和我说的”有道，可以在网页里面去加自定义词典“应该比较类似吧。
应该是额外在翻译之前把名词输进去作为prompt的，不过我并不擅长搞prompt。

**Comment by AkikazeQ** [comment]
我用LUNA配合SAKURA0.9的时候，翻译前替换人名的时候，
一般替换成【<p1>】【<p2>】【<p3>】，翻译结果处理里再匹配括号去掉，
在我的记忆里没看到过被SAKURA修改翻译，你看看能否作为参考。

**Comment by chimiansw** [comment]
我刚才尝试了一下，直接把名字在文本设定里面，用简单转换换成简体中文，就不会再翻译了，也算曲线救国，基本实现想要的功能

**Comment by dnadash** [comment]
> 我刚才尝试了一下，直接把名字在文本设定里面，用简单转换换成简体中文，就不会再翻译了，也算曲线救国，基本实现想要的功能，这个仅限Sakura大模型有效，其他在线、api之类的基本还是会重新翻译一下

请问兄弟，你别的在线经常会出现专有名词变成数字吗？我有道和彩云频发，百度好点

**Comment by chimiansw** [comment]
> > 我刚才尝试了一下，直接把名字在文本设定里面，用简单转换换成简体中文，就不会再翻译了，也算曲线救国，基本实现想要的功能，这个仅限Sakura大模型有效，其他在线、api之类的基本还是会重新翻译一下
> 
> 请问兄弟，你别的在线经常会出现专有名词变成数字吗？我有道和彩云频发，百度好点

没有出现过，我之前用辞书、还有那个专有名词的时候只有Sakura大模型会出现变成数字的情况，在线的没有出现过这样的问题
