### ISSUE TITLE
关于OCR功能

### ISSUE THREAD

**Issue by 1a1s4d5f1g4** [HIllya51/LunaTranslator#552]
大佬可以给“进行一次OCR”这个功能加个快捷按键设置么，“选取OCR范围”虽然可以设置快捷按键，但是选取之后留下的OCR框会一直获取内容，需要自己手动关闭或者调整。“进行一次OCR”选取之后不会一直留下框，可以自由选择要翻译的地方，但是目前设置不了快捷键，这样每次翻译都要鼠标去点图标比较麻烦。

**Comment by HIllya51** [comment]
以支持
