### ISSUE TITLE
最新版本，腾讯Api翻译无效

### ISSUE THREAD

**Issue by ParanoiaIsGreat** [HIllya51/LunaTranslator#556]
昨天开始是上一个小版本，译文压根不显示，升级到最新版后依然无法显示，随便换成qqimt翻译没问题。
今天再度尝试，腾讯Api翻译变成了不翻译，显示的“译文”为未经翻译的原文
![image](https://github.com/HIllya51/LunaTranslator/assets/10475153/07870172-1181-4cc5-8c57-ee14b6170fec)

**Comment by HIllya51** [comment]
测试没有问题。

**Comment by HIllya51** [comment]
盲猜语言设置不对

**Comment by ParanoiaIsGreat** [comment]
在哪设置？我印象中没有单独的设置？

**Comment by ParanoiaIsGreat** [comment]
牛的。问题解决。
