### ISSUE TITLE
sakura模型流式输出导致阴影字体渲染不完整

### ISSUE THREAD

**Issue by signin404** [HIllya51/LunaTranslator#558]
只有前几个字能渲染
而且不知为何会多一行报错

![QQ截图20240306043107](https://github.com/HIllya51/LunaTranslator/assets/145902543/45e290e4-2043-4f67-95e3-83e5dbba3991)

**Comment by pipixia244** [comment]
![image](https://github.com/HIllya51/LunaTranslator/assets/56287117/82c56e90-5caa-4e72-a77c-8182994dfec7)

按一下这个图标按钮，把里面的stderr和stdout的内容发一下

**Comment by signin404** [comment]
stderr

> Traceback (most recent call last):
  File "D:\LunaTranslator\App\LunaTranslator\translator\basetranslator.py", line 273, in _fythread
    timeoutfunction(_iterget,checktutukufunction=checktutukufunction )
  File "D:\LunaTranslator\App\LunaTranslator\translator\basetranslator.py", line 48, in timeoutfunction
    return t.get_result(timeout,checktutukufunction)
  File "D:\LunaTranslator\App\LunaTranslator\translator\basetranslator.py", line 42, in get_result
    raise self.exception
  File "D:\LunaTranslator\App\LunaTranslator\translator\basetranslator.py", line 26, in run
    self.result = self.func( )
  File "D:\LunaTranslator\App\LunaTranslator\translator\basetranslator.py", line 270, in _iterget
    for _res in res:
  File "D:\LunaTranslator\App\LunaTranslator\translator\sakura.py", line 259, in translate
    self.sliding_window(query, output_text)
UnboundLocalError: local variable 'output_text' referenced before assignment


stdout

> {"choices":[{"delta":{"content":"我觉得"},"finish_reason":null,"index":0}],"created":1709702051,"id":"chatcmpl-OGKQvQmRJI3Ols8LIs93C0qIilWMsPVp","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"她"},"finish_reason":null,"index":0}],"created":1709702052,"id":"chatcmpl-8n0oGSsUsRme2FCB6R7snXbC0RoNzaDL","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"很"},"finish_reason":null,"index":0}],"created":1709702052,"id":"chatcmpl-hRNnShw7E0eAfNUTQ4lCuC1dxU8h4IhR","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"像"},"finish_reason":null,"index":0}],"created":1709702052,"id":"chatcmpl-HudKDdcDe3HVdbPFaEQvqtROksecTMPl","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"原"},"finish_reason":null,"index":0}],"created":1709702052,"id":"chatcmpl-x0fr9ckASPDu9xLwRJLlURAmo3Da0c6x","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"神"},"finish_reason":null,"index":0}],"created":1709702052,"id":"chatcmpl-0vphaiNbKxkeQX3lkdHnz0oOxhP1SQM7","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"在"},"finish_reason":null,"index":0}],"created":1709702052,"id":"chatcmpl-ukXm0ZFtfhrScyzqK6g89IUQB2bMHB7M","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"演"},"finish_reason":null,"index":0}],"created":1709702052,"id":"chatcmpl-tpcJPRVDfKhiMjjecyGWnRRx2vlwfdn0","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"莫"},"finish_reason":null,"index":0}],"created":1709702052,"id":"chatcmpl-Yr3iin4VN54vx6KREuaaf7h57CWF2pMh","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"娜"},"finish_reason":null,"index":0}],"created":1709702052,"id":"chatcmpl-BWnhCZHXYVXUREobS5AzYUHbYv0ayTwT","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"时"},"finish_reason":null,"index":0}],"created":1709702052,"id":"chatcmpl-Us3WzPJsu1nvpxayBBOL1hOpWt9qOhIi","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"的小"},"finish_reason":null,"index":0}],"created":1709702052,"id":"chatcmpl-9Ee5XOtKhPacgWwKkEgMN496jTe0vGoT","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"原"},"finish_reason":null,"index":0}],"created":1709702053,"id":"chatcmpl-UxKokXGkh2sETJxbX4ADfFK8dljiDPvf","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"好"},"finish_reason":null,"index":0}],"created":1709702053,"id":"chatcmpl-VurNx6XlTs4DMmhQTKZeIPmxHdJJ8sV6","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"美"},"finish_reason":null,"index":0}],"created":1709702053,"id":"chatcmpl-zLcoBuqshnUcG6pQA8H43toUVF3d9mOH","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"。"},"finish_reason":null,"index":0}],"created":1709702053,"id":"chatcmpl-ITHgiwzNsGCW2lRXhtAf6NrHlr2TQJCE","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"虽然"},"finish_reason":null,"index":0}],"created":1709702053,"id":"chatcmpl-cT9HqCjv9PYCExe4hSVPWbSqv4K42UZF","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"只是"},"finish_reason":null,"index":0}],"created":1709702053,"id":"chatcmpl-45KKWehM9WruGqYFoRoysNYcVZV76IZ5","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"像"},"finish_reason":null,"index":0}],"created":1709702053,"id":"chatcmpl-nL5lToaUuEnvi8YVzclJPHM9jywBsXuy","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"，"},"finish_reason":null,"index":0}],"created":1709702053,"id":"chatcmpl-kpPRVF1S2PrIe40aJ6mAjDNUARjjYuOE","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"但"},"finish_reason":null,"index":0}],"created":1709702053,"id":"chatcmpl-OUNB4DHn4jzOdrkwmjhoXDADJrM7AUtm","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"绝对是"},"finish_reason":null,"index":0}],"created":1709702054,"id":"chatcmpl-XlQ6SgWgiG7De6b3QQmspB2vRcIdXECl","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"不同"},"finish_reason":null,"index":0}],"created":1709702054,"id":"chatcmpl-62Gz2vO8osZSx6CvkPQGNjRDeKpsv63t","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"人"},"finish_reason":null,"index":0}],"created":1709702054,"id":"chatcmpl-QfHHQxMPMKzBqSF99o9FrqtTLQIkJJXl","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"。"},"finish_reason":null,"index":0}],"created":1709702054,"id":"chatcmpl-IhTnqS0MA8LmQGFL4ESLtSIonQesljzc","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"我"},"finish_reason":null,"index":0}],"created":1709702054,"id":"chatcmpl-Aef8mQBnk6asB6Flg6mphRBnHN2PjB83","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"怀疑"},"finish_reason":null,"index":0}],"created":1709702054,"id":"chatcmpl-JhrC1pVc4HmLDOb8fJvli0ZeWmcrxhoS","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"她是"},"finish_reason":null,"index":0}],"created":1709702054,"id":"chatcmpl-VU1bM2ZMfzufJif3hZioqc4zRCCBlxXh","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"和"},"finish_reason":null,"index":0}],"created":1709702054,"id":"chatcmpl-I0FW4VGOh4HrPXJbMDTaeTyDTU9dZQyh","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"沙"},"finish_reason":null,"index":0}],"created":1709702054,"id":"chatcmpl-ukB68QDH0L6KeVYzW2NKfj5iUH2FlaM6","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"的"},"finish_reason":null,"index":0}],"created":1709702055,"id":"chatcmpl-LP0LAd5JVLS2WU0GDGorkvZHy3hguJ5E","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"配音"},"finish_reason":null,"index":0}],"created":1709702055,"id":"chatcmpl-0sR9Ev9volCzyOApsZnC5EZgdbqm4WAi","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"员"},"finish_reason":null,"index":0}],"created":1709702055,"id":"chatcmpl-d4sloTrGw1hRSmBYsc07dalzQ2wvoebf","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"而"},"finish_reason":null,"index":0}],"created":1709702055,"id":"chatcmpl-YgRBdkusBXuB4qY4ZdxD5AVQkVAAnKqw","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"问"},"finish_reason":null,"index":0}],"created":1709702055,"id":"chatcmpl-Hj2O1Lfbgxfnq96Yf4re1q1OzCeswsRK","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"了"},"finish_reason":null,"index":0}],"created":1709702055,"id":"chatcmpl-i5wVVmtyPPiSS7Fod8OoLryUcE3DE8AM","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"，"},"finish_reason":null,"index":0}],"created":1709702055,"id":"chatcmpl-skRc0kXrNPXmNR0asY7lZPDReouIpO1F","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"结果"},"finish_reason":null,"index":0}],"created":1709702055,"id":"chatcmpl-p37OC1tctKttG8NkHMJtIiBoZZRqN6rr","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"不是"},"finish_reason":null,"index":0}],"created":1709702056,"id":"chatcmpl-oMY4lk1x0y3a83E7ZJ48fzIybh6dwol1","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"。"},"finish_reason":null,"index":0}],"created":1709702056,"id":"chatcmpl-rBdB1wLks7x2weM2NDINCHMWk1iwUQ0v","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{},"finish_reason":"stop","index":0}],"created":1709702056,"id":"chatcmpl-ETKF8YkR5NdP1g8EIrmkn7GPRv37CkhI","model":"sukinishiro","object":"chat.completion.chunk"}

40

**Comment by pipixia244** [comment]
fixed，已经pr

**Comment by signin404** [comment]
关闭显示原文字体会变得很小
报错变成别的了

![QQ截图20240307001216](https://github.com/HIllya51/LunaTranslator/assets/145902543/9d412589-589e-4810-80d7-4a960e081a6b)

`Traceback (most recent call last):
  File "D:\LunaTranslator\App\LunaTranslator\translator\basetranslator.py", line 284, in _fythread
    timeoutfunction(_iterget,checktutukufunction=checktutukufunction )
  File "D:\LunaTranslator\App\LunaTranslator\translator\basetranslator.py", line 48, in timeoutfunction
    return t.get_result(timeout,checktutukufunction)
  File "D:\LunaTranslator\App\LunaTranslator\translator\basetranslator.py", line 42, in get_result
    raise self.exception
  File "D:\LunaTranslator\App\LunaTranslator\translator\basetranslator.py", line 26, in run
    self.result = self.func( )
  File "D:\LunaTranslator\App\LunaTranslator\translator\basetranslator.py", line 280, in _iterget
    for _res in res:
  File "D:\LunaTranslator\App\LunaTranslator\translator\sakura.py", line 227, in translate
    text_partial = o['choices'][0]['delta']['content']
KeyError: 'content'
`

`{"choices":[{"delta":{"content":"虽然"},"finish_reason":null,"index":0}],"created":1709741524,"id":"chatcmpl-pc85kLH1UcOAMzhVrilOuE5YsVZqcwNn","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"不知道"},"finish_reason":null,"index":0}],"created":1709741524,"id":"chatcmpl-XZE9DYtyXCHVdzRJhxlTn1vpMjnELTHX","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"是谁"},"finish_reason":null,"index":0}],"created":1709741524,"id":"chatcmpl-Fi1jLuik6xkgsiQNnsRsT9GyUGE2uIEF","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"，"},"finish_reason":null,"index":0}],"created":1709741524,"id":"chatcmpl-VJA1Z3azp8cH0KM1KpogYeFf4NPi9m7P","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"但"},"finish_reason":null,"index":0}],"created":1709741524,"id":"chatcmpl-NLLe9LoCidrSwCAqz9bSa7jeYTJkxrOi","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"幸好"},"finish_reason":null,"index":0}],"created":1709741524,"id":"chatcmpl-LWWnVB3bFv9DYgGGOjfLDNIFUOOQujuh","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"是个"},"finish_reason":null,"index":0}],"created":1709741524,"id":"chatcmpl-kcjcP49ktfx4JneSQfBUIyxPMvADOSRR","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"色"},"finish_reason":null,"index":0}],"created":1709741525,"id":"chatcmpl-a8wtv7Udw2IPnnsZyt4v1uikcn6R9D9i","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"胚"},"finish_reason":null,"index":0}],"created":1709741525,"id":"chatcmpl-JFPlDtBg3IabqdHodpn5xn4AkhF80TiQ","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{"content":"。"},"finish_reason":null,"index":0}],"created":1709741525,"id":"chatcmpl-dC8PDivUzrI42CA8GN7hWpnHItnft9qv","model":"sukinishiro","object":"chat.completion.chunk"}
{"choices":[{"delta":{},"finish_reason":"stop","index":0}],"created":1709741525,"id":"chatcmpl-7YN7i1Dw38DQYKPwcaklVDlA50KL14I1","model":"sukinishiro","object":"chat.completion.chunk"}
`

**Comment by pipixia244** [comment]
#560
