### ISSUE TITLE
sakura流式输出，字体显示错误

### ISSUE THREAD

**Issue by mrl998** [HIllya51/LunaTranslator#561]
![96B~L1TYU3G1OB_A0{UT H5](https://github.com/HIllya51/LunaTranslator/assets/18524100/1d078862-1ec5-4a89-aece-2567baf62afa)
![CAW4%(@()W2K8O4X~S)9Y V](https://github.com/HIllya51/LunaTranslator/assets/18524100/c525a46e-3520-41bd-9e6e-587578b8dad7)

图1勾选显示原文，译文正常显示
图2取消显示原文，译文会变成字号极小的字体

另外下面一直有个KeyError，关闭流式输出后Error消失

**Comment by HIllya51** [comment]
已修正
