### ISSUE TITLE
关于正则替换的边界问题

### ISSUE THREAD

**Issue by k2250761** [HIllya51/LunaTranslator#562]
![Quicker_20240307_194526](https://github.com/HIllya51/LunaTranslator/assets/61865659/878be461-b10b-4430-9bf5-4db9be891733)
能否增加一个原文匹配边界开关，像VNR辞书那样。
例如「はぁ、ああぁ、ああぁ……」，能够独立匹配到  はぁ和ああぁ 这种的。

**Comment by HIllya51** [comment]
什么意思，不明白。

**Comment by k2250761** [comment]
就是能够单独匹配到两个标点符号之间的原文

**Comment by HIllya51** [comment]
说得太抽象了，看不懂。请举例子。

**Comment by k2250761** [comment]
比如这句话「あ、待ってね」我要用正则匹配“あ”替换成“啊”，但是如果直接替换掉“あ=啊 ”
之后遇到类似这种的句子：あいうのが好きか 就会变成  啊いうのが好きか，所以需要一个边界能够独立匹配到「あ、待ってね」中的あ，这样不会出现原文被误伤

**Comment by HIllya51** [comment]
你正则后面建一个判断有没有标点不就行了。

**Comment by k2250761** [comment]
之前我也是这样想的，但是标点符号太多，还有一些类似特殊符号的，太长了

**Comment by HIllya51** [comment]
又没必要把所有标点全加进去，考虑这么多干什么

**Comment by k2250761** [comment]
因为VNR辞书是有边界宏的，这个就是为了自己替换的内容不被误匹才弄出来的，但是软件的正则跟VNR又不一样，所以我搬不过来，也没想到别的方法，如果太麻烦弄不了，就算了。我在想别的办法

**Comment by HIllya51** [comment]
VNR辞书格式太复杂了，我看的头大，只做了最基本的支持。如果你感兴趣可以修改甚至重写 https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/LunaTranslator/myutils/vnrshareddict.py 。

**Comment by k2250761** [comment]
我也不懂代码，只是稍微研究过一点辞书，太复杂就算了，没事的

**Comment by k2250761** [comment]
> VNR辞书格式太复杂了，我看的头大，只做了最基本的支持。如果你感兴趣可以修改甚至重写 https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/LunaTranslator/myutils/vnrshareddict.py 。

作者大大，这个正则替换能增加一个搜索栏吗，我突然发现这个正则替换里面没有搜索栏
