### ISSUE TITLE
查词不管用了吗?

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#567]
![QQ截图20240308232944](https://github.com/HIllya51/LunaTranslator/assets/137600501/6a5b390f-5949-45a5-8a95-1f37cbd58427)

**Comment by dnadash** [comment]
![1](https://github.com/HIllya51/LunaTranslator/assets/137600501/89eb2328-a947-425d-aa44-0472580bc7ec)

**Comment by HIllya51** [comment]
你网络问题吧

**Comment by HIllya51** [comment]
<img width="907" alt="屏幕截图 2024-03-08 235737" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/10f5e728-cdbe-4389-a2ac-85442533e1f7">
