### ISSUE TITLE
去除重复行无效

### ISSUE THREAD

**Issue by lnusyaha** [HIllya51/LunaTranslator#57]
![PBYHG@GZXF}1~2(MM7_MG(V](https://user-images.githubusercontent.com/116066807/201178596-5dfb6dcb-e9dc-4c12-8e9d-3576468bbbc4.png)
如图，开启了却没效果。然后希望去除重复行能增加重复次数，有时候会重复好几行然后去除不了。

**Comment by HIllya51** [comment]
你把原句复制出来给我看一下，我试了可以的

**Comment by HIllya51** [comment]
哦 我还真是改错了点东西

**Comment by HIllya51** [comment]
已修正
