### ISSUE TITLE
請問更新後縮放模式放大畫面後，為什麼有設定滑鼠穿透視窗後工具列就沒辦法移動跟使用了?

### ISSUE THREAD

**Issue by gyes990508** [HIllya51/LunaTranslator#570]
如標題，以前就算是用縮放模式放大畫面，有設定滑鼠穿透視窗也一樣可以操作工具列跟移動視窗

然後我剛剛更新到最新版後只要一放大畫面，有設定滑鼠窗透視窗後，工具列就不能用了也不能移動視窗，這樣就變成玩到一半如果要去按工具列那欄的時候就還要先縮小到原本的視窗才能去按工具列那欄跟移動視窗，感覺變麻煩了

請問是作者大大改成這樣的嗎?

上面這張是有點選滑鼠穿透視窗的功能，滑鼠移到翻譯上面就跑不出工具列了，我之前就算有點選滑鼠穿透視窗的功能，依然可以在放大的畫面去點工具列的東西跟移動視窗
![sassasasa](https://github.com/HIllya51/LunaTranslator/assets/109327024/27dd13a9-8e0f-4d94-9a39-e1c86d52d9bc)

下面這張是沒有點選滑鼠穿透視窗的功能
![image](https://github.com/HIllya51/LunaTranslator/assets/109327024/f7ec8254-4bcc-4bd5-b989-57142ec13bb4)

再麻煩作者大大解答了，謝謝~

**Comment by HIllya51** [comment]
没有办法，magpie内部改了鼠标映射逻辑

**Comment by gyes990508** [comment]
了解感謝，太難過了

另外我看release那邊好像只剩兩個最近的版本能下載了? 

想說如果還能下載以前版本的話就不用擔心這個問題了

**Comment by HIllya51** [comment]
你可以下载旧版的正版magpie，现在用外部magpie也不会退出全屏了
