### ISSUE TITLE
請問文字預處理裏面的規則運算式替換可以進行組替換操作嗎?

### ISSUE THREAD

**Issue by junkpunk1122** [HIllya51/LunaTranslator#571]
你好，情況是這樣的：
我勾選了兩個去除重複行的選項，得到下面的結果
![image](https://github.com/HIllya51/LunaTranslator/assets/162812538/96dbd8e3-d03c-42b4-9e65-514b5dca364d)

如果我再勾選"去除重複字元AAAABBBBCCC->ABC"就會把"もぐもぐ"取替成"もぐ" (もぐもぐ和もぐ翻譯後的意思會不一樣)
![image](https://github.com/HIllya51/LunaTranslator/assets/162812538/a9bfe687-ca99-4d54-8d88-5b525fdc9a12)

所以我打算添加運算式：(.{1})(.{2})，並將它取代成：$1
無法獲得預期內容
![image](https://github.com/HIllya51/LunaTranslator/assets/162812538/a9da902b-cdc2-4778-aef9-8f8ad36837a2)

我不知道用戶設置文件是哪一個，這裏我就提供測試時的設置截圖：
![image](https://github.com/HIllya51/LunaTranslator/assets/162812538/be647ac2-3287-4b3d-9ba1-6700789c1a27)
![image](https://github.com/HIllya51/LunaTranslator/assets/162812538/9d893bd7-8a20-472d-8a70-1180f9b5f172)

**Comment by HIllya51** [comment]
这是python，请用\\1而非$1

**Comment by junkpunk1122** [comment]
> 这是python，请用\\1而非$1

可以了，感謝你

**Comment by junkpunk1122** [comment]
@HIllya51 不好意思再次打擾，請問多個規則運算式的情況下可以設置執行順序嗎?

**Comment by HIllya51** [comment]
在前面的先执行，在后面的后执行
