### ISSUE TITLE
Problems with Cyclet games

### ISSUE THREAD

**Issue by Vincent-Dawn** [HIllya51/LunaTranslator#573]
When I hook Cyclet games, I get a lot of repeating text with the games main hook. If I'm using LunaHook and using the filtering options to remove repeating text, then the game's text will appear out of order.

**Comment by HIllya51** [comment]
You should take a screenshot instead of just describing it to me in text.
And you should tell me the name of the game and the VNDB ID

**Comment by HIllya51** [comment]
I have fixed this problem, tested on《復讐の女仕官ハイネ ～肢体に刻まれる淫欲のプログラム～》

**Comment by Vincent-Dawn** [comment]
Sorry to reopen this issue, but I noticed that text in the game that is more than one line in the dialogue box is split into multiple lines in LunaTranslator (middle) and LunaHook (bottom):

![Screenshot 2024-03-10 140054](https://github.com/HIllya51/LunaTranslator/assets/103087027/86d53375-873c-4e65-9a1b-70f91278d7ec)
![Screenshot 2024-03-10 140115](https://github.com/HIllya51/LunaTranslator/assets/103087027/813a077a-403e-4c52-85dd-825e259bf237)
![Screenshot 2024-03-10 144525](https://github.com/HIllya51/LunaTranslator/assets/103087027/338f8626-c7a1-4505-b72a-6343c098b191)

The VN I'm playing is [Konchuu Kansatsu ](https://vndb.org/v10294)
