### ISSUE TITLE
女系家族hook不到文本

### ISSUE THREAD

**Issue by lawiest** [HIllya51/LunaTranslator#574]
![image](https://github.com/HIllya51/LunaTranslator/assets/50625377/98db2e75-14a7-4a57-8ff4-b0f2285d14ec)

游戏：
https://1drv.ms/u/c/d0994c518dc5fead/EeCIkHts3cxOlrrcxj72DHoBB-o9pkLiH4QefKMY6xRHaQ?e=EyPNDp

搜索特殊码也没用

先导入注册表mfamily.reg后运行mfamily.exe

**Comment by HIllya51** [comment]
1+
