### ISSUE TITLE
chatGpt(第三方)开启流式输出后，翻译优化显示有问题

### ISSUE THREAD

**Issue by meissica** [HIllya51/LunaTranslator#575]
使用第三方chatgpt翻译的时候，开启流式输出后，遇到原文包含翻译优化设置的替换单词，第一个字会显示成Z。不开流式输出显示是正常的。这个修改好吗？感谢大佬！
![Screenshot_20240310_192201](https://github.com/HIllya51/LunaTranslator/assets/155863019/60bee58a-34d2-4333-b2a3-ecea8d35004c)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/issues/550

**Comment by HIllya51** [comment]
而且测试最新版不存在问题
