### ISSUE TITLE
Dialogue lines in Cyclet games get separated  

### ISSUE THREAD

**Issue by Vincent-Dawn** [HIllya51/LunaTranslator#576]
Sorry about not identifying the VN or showing pictures with my last issue. I noticed that text in Cyclet games that is more than one line in the dialogue box is split into multiple lines in LunaTranslator (middle) and LunaHook (bottom):

![Screenshot 2024-03-10 140054](https://github.com/HIllya51/LunaTranslator/assets/103087027/86d53375-873c-4e65-9a1b-70f91278d7ec)
![Screenshot 2024-03-10 140115](https://github.com/HIllya51/LunaTranslator/assets/103087027/813a077a-403e-4c52-85dd-825e259bf237)
![Screenshot 2024-03-10 144525](https://github.com/HIllya51/LunaTranslator/assets/103087027/338f8626-c7a1-4505-b72a-6343c098b191)

The VN I'm playing is [Konchuu Kansatsu ](https://vndb.org/v10294). I trying to use two along with Sugoi Translator.

**Comment by HIllya51** [comment]
You can use "text processing"->"Filter line breaks" in LunaTranslator
