### ISSUE TITLE
Used filter line breaks, still getting line breaks in Cyclet games.

### ISSUE THREAD

**Issue by Vincent-Dawn** [HIllya51/LunaTranslator#577]
As the title says I used filter line breaks and it's still happening on the VN I mentioned in the previous issue.

**Comment by HIllya51** [comment]
give me the game resource by onedrive/googledrive/mega

**Comment by Vincent-Dawn** [comment]
Here is the google drive link:

[https://drive.google.com/drive/folders/1jMNRvwtH9Wv8uOloE1lkOzICOn90eh_a](https://drive.google.com/drive/folders/1jMNRvwtH9Wv8uOloE1lkOzICOn90eh_a)

You have the download the file as a zip file.

**Comment by HIllya51** [comment]
<img width="1171" alt="屏幕截图 2024-03-12 143512" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/5fd9ca9c-b583-4be5-ad70-b0515d430f29">

I have tested and it works fine.

**Comment by HIllya51** [comment]
If you still have questions, please release more complete screenshots instead of just taking a small, meaningless piece of the image

**Comment by Vincent-Dawn** [comment]
It works now, next time there is an issue I will screenshot the entire window with hooks on it.
