### ISSUE TITLE
English Translation?

### ISSUE THREAD

**Issue by rasbayri** [HIllya51/LunaTranslator#58]

**Comment by HIllya51** [comment]
。。。What do you want to ask?

**Comment by rasbayri** [comment]
It says in the title, will you make an English translation? And also, how to make azure tts work?

**Comment by HIllya51** [comment]
In fact, the software now supports English translation
https://p.inari.site/guest/22-11/12/636f4438e5e91.jpg
The software can also set the interface to English
https://p.inari.site/guest/22-11/12/636f44bd8a73f.jpg
https://p.inari.site/guest/22-11/12/636f44bcee6a4.jpg

**Comment by HIllya51** [comment]
Azure tts is a free interface obtained through reverse engineering, which may be invalid now.

**Comment by HIllya51** [comment]
I will repair azure tts interface later

**Comment by rasbayri** [comment]
> Azure tts is a free interface obtained through reverse engineering, which may be invalid now.

I meant the interface
