### ISSUE TITLE
The problem with Yandex and deepl.

### ISSUE THREAD

**Issue by allebar** [HIllya51/LunaTranslator#582]
In the case of Yandex, I don't always project text into the program window. If I log into the browser, there is a translation, but it is not displayed in the program, and if it is displayed, it is incorrect. This happens once every 10 transfers. The situation with deepl is as follows: quite often only half of the text is translated. This definitely didn't happen before.

**Comment by allebar** [comment]
![55444](https://github.com/HIllya51/LunaTranslator/assets/75815491/06a2a6d6-bfed-43a5-94ee-50aedf93df18)
Here is an example. Translated only half of the text. If I log into the browser and try to write new words for translation, the final translation does not change.  This happens only in conjunction with the program.

**Comment by HIllya51** [comment]
can't understand your problem.

**Comment by HIllya51** [comment]
fixed.

**Comment by allebar** [comment]
> fixed.

The transfer via Yandex is still problematic. If the current and correct translation is in the browser itself, then in the program window the translation of the previous text. Thus, the translation lags behind.

**Comment by allebar** [comment]
> fixed.

I also checked Google. The translation is not displayed in the program window, although everything is fine in the browser itself

**Comment by HIllya51** [comment]
I cannot reproduce the problem you mentioned, so please use another translation that is not problematic

**Comment by allebar** [comment]
> I cannot reproduce the problem you mentioned, so please use another translation that is not problematic

I fixed the problem with yandex as follows: I used the "dev yandex" file from version 2.38.5 and moved it to the folder with the new program. After that, the problem with the translation lag disappeared.

**Comment by allebar** [comment]
> I cannot reproduce the problem you mentioned, so please use another translation that is not problematic

The problem with Google disappeared when I downloaded the program again.

**Comment by HIllya51** [comment]
> > I cannot reproduce the problem you mentioned, so please use another translation that is not problematic
> 
> I fixed the problem with yandex as follows: I used the "dev yandex" file from version 2.38.5 and moved it to the folder with the new program. After that, the problem with the translation lag disappeared.

you can see the file history https://github.com/HIllya51/LunaTranslator/commits/main/LunaTranslator/LunaTranslator/translator/dev_yandex.py
I only edited this file after you raised this question yesterday, but now you're telling me that switching to the previous version won't be a problem. Are you trying to make me happy?

**Comment by allebar** [comment]
> > > I cannot reproduce the problem you mentioned, so please use another translation that is not problematic
> > 
> > 
> > I fixed the problem with yandex as follows: I used the "dev yandex" file from version 2.38.5 and moved it to the folder with the new program. After that, the problem with the translation lag disappeared.
> 
> you can see the file history https://github.com/HIllya51/LunaTranslator/commits/main/LunaTranslator/LunaTranslator/translator/dev_yandex.py I only edited this file after you raised this question yesterday, but now you're telling me that switching to the previous version won't be a problem. Are you trying to make me happy?

The problem started to repeat itself. If I am using an old file, then the sentence is sometimes not output, if updated, then the previous translation is output, and not the current one. In any case, this is not critical, because there are other ways to translate.
