### ISSUE TITLE
 v2.39.1  4ff39a8 HOOK报错

### ISSUE THREAD

**Issue by AkikazeQ** [HIllya51/LunaTranslator#584]
HOOK游戏会直接 error Uncaught SyntaxError: Unexpected token {
全新下载后，测试了好几个游戏都报一样错，旧版不会。

**Comment by HIllya51** [comment]
截图。

**Comment by AkikazeQ** [comment]
![image](https://github.com/HIllya51/LunaTranslator/assets/96406562/b2bf70db-1fd8-4d5b-bd33-249b544edaab)

复现方法：点击工具快捷栏的手铐图标，选择GAME.TXT

另外sakura无法工作，显示
![image](https://github.com/HIllya51/LunaTranslator/assets/96406562/1eb7c01d-5fd7-4653-a1ec-19bc997c6ba2)
老版本本地sakura可以正常工作。

**Comment by HIllya51** [comment]
> ![image](https://private-user-images.githubusercontent.com/96406562/313374717-b2bf70db-1fd8-4d5b-bd33-249b544edaab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NjUxNzgsIm5iZiI6MTcxMDU2NDg3OCwicGF0aCI6Ii85NjQwNjU2Mi8zMTMzNzQ3MTctYjJiZjcwZGItMWZkOC00ZDViLWJkMzMtMjQ5YjU0NGVkYWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDA0NTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0OGNkYjAyZjY4NDgxYTgwMWIyYmVjMDMxZGYwOTU4MDFiYWEyMjVjZmExOTBhY2NlZjMxNDMzZjE2MTNmNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hKkO_8fPERyR2kEFr5hossquAvZAlXgRYt__Kq-x8AQ)
> 
> 复现方法：点击工具快捷栏的手铐图标，选择GAME.EXE
> 
> 另外新版下，本地sakura CMD窗口无法接到翻译申请，LUNA显示 ![image](https://private-user-images.githubusercontent.com/96406562/313374791-1eb7c01d-5fd7-4653-a1ec-19bc997c6ba2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NjUxNzgsIm5iZiI6MTcxMDU2NDg3OCwicGF0aCI6Ii85NjQwNjU2Mi8zMTMzNzQ3OTEtMWViN2MwMWQtNWZkNy00NjUzLWExZWMtMTliYzk5N2M2YmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDA0NTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1Nzg4OWQ1MDkwZGU0ZDY1ZTY1YmNmZjdiYjhhZGJmYTExMTY4YTMzMmJmYWViYTk2OGViNmE1NzJjNjc3YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ldJ_m6kdxtaEYGIuIsdU1fczun8D-fXPwBJY_Y1YNHg) 老版本本地sakura可以正常工作，确认端口输入正确。

sakura的问题已修正，游戏的问题先等下吧

**Comment by HIllya51** [comment]
均已修复
