### ISSUE TITLE
新版部分游戏的hook仍然有点问题

### ISSUE THREAD

**Issue by AkikazeQ** [HIllya51/LunaTranslator#586]
![image](https://github.com/HIllya51/LunaTranslator/assets/96406562/a4af88b3-8433-4228-bafa-ecfcd51da917)
老版本HOOK正常
![image](https://github.com/HIllya51/LunaTranslator/assets/96406562/8b603cd1-1248-4501-a99a-e05e3377a9ef)

另外用无气力天使测试了一下内嵌翻译，
似乎不管等待设置5秒还是10秒，第一次对话仍然是日文，第二次重复对话有了缓存才是内置中文。

**Comment by HIllya51** [comment]
已修正
