### ISSUE TITLE
大佬，有办法提取这个游戏的文本吗?我hook不行

### ISSUE THREAD

**Issue by wycstc353** [HIllya51/LunaTranslator#587]
大佬，有办法提取这个游戏的文本吗?我hook不行
https://www.east-plus.net/read.php?tid-2007717-keyword-%E9%9B%BB%E8%BB%8A%E9%80%9A%E5%AD%A6%E5%B0%91%E5%A5%B3.html

https://www.dlsite.com/maniax/work/=/product_id/RJ01117329.html

**Comment by HIllya51** [comment]
给我OD/MG/GD

**Comment by wycstc353** [comment]
> 给我OD/MG/GD

https://mega.nz/file/i6hCVB4J#2eEddrlTAauph5lJoguYOFEGlLmiIKNfWtZnzRNn6SE
这样可以不？我这三个盘基本不用

**Comment by HIllya51** [comment]
可以

**Comment by HIllya51** [comment]
已支持

**Comment by wycstc353** [comment]
> 已支持

 没看到有新版本啊，是没上传还是？

**Comment by HIllya51** [comment]
改动较小，直接重下最新版就行了
