### ISSUE TITLE
最新版本的内嵌还是会出现口口以及TGW翻译时会多一行PADXXX

### ISSUE THREAD

**Issue by Z9wind** [HIllya51/LunaTranslator#588]
游戏为使用英文的renpy出现问题多一些，考虑到字库问题我尝试了系统自带的Arial和微软雅黑，还尝试了一些美化大佬自补的字体，还是显示口口，且偶尔游戏还会报错。然后TGW翻译结果下面会多一行东西，B站有UP好像说是流失翻译导致的，希望修复，感恩的心。
![Uploading 2615760_20240317223207_1.png…]()

**Comment by HIllya51** [comment]
<img width="350" alt="屏幕截图 2024-03-17 223624" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/6709cb34-62e0-4346-840c-eb97176630e0">

**Comment by Z9wind** [comment]
![2615760_20240317223207_1](https://github.com/HIllya51/LunaTranslator/assets/107527857/a5421b99-fc4b-4669-a107-46f5c702bb80)
没上传好，重新上传一下

**Comment by Z9wind** [comment]
刚刚我使用那位UP的旧版居然可以内嵌了，但是字体好像被强制成黑体，我选啥别的都没用。然后旧版hook提取到的文本不如新版，如果可以的话辛苦大佬留意一下，感恩感恩。
![2615760_20240317224459_1](https://github.com/HIllya51/LunaTranslator/assets/107527857/8f149509-209e-4d91-a5fd-a5d8a3e4ce23)

**Comment by Z9wind** [comment]
然后新版TGW多出来的东西是这个样子的
![Snipaste_2024-03-17_22-48-25](https://github.com/HIllya51/LunaTranslator/assets/107527857/601fe786-cf6b-4e72-8102-2a53c2493b80)

**Comment by HIllya51** [comment]
> 然后新版TGW多出来的东西是这个样子的 ![Snipaste_2024-03-17_22-48-25](https://private-user-images.githubusercontent.com/107527857/313481740-601fe786-cf6b-4e72-8102-2a53c2493b80.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODc3ODYsIm5iZiI6MTcxMDY4NzQ4NiwicGF0aCI6Ii8xMDc1Mjc4NTcvMzEzNDgxNzQwLTYwMWZlNzg2LWNmNmItNGU3Mi04MTAyLTJhNTNjMjQ5M2I4MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QxNDU4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzY5MmIwYzMzMDQ0ODA1MWNhZGNhMWUzMDQyODcyNWZjYTc4YTBjYmQyOGQzNzEzMzE1OWE2MWJiZGVkYTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h9ZoR9XiSRKuqLxRNMO6Mdmvs_rUuIEPzNX2oqt-kho)

已修正

**Comment by HIllya51** [comment]
> ![2615760_20240317223207_1](https://private-user-images.githubusercontent.com/107527857/313480685-a5421b99-fc4b-4669-a107-46f5c702bb80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODc3ODYsIm5iZiI6MTcxMDY4NzQ4NiwicGF0aCI6Ii8xMDc1Mjc4NTcvMzEzNDgwNjg1LWE1NDIxYjk5LWZjNGItNDY2OS1hMTA3LTQ2ZjVjNzAyYmI4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QxNDU4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNmZhM2Y4N2Y4OTZkYWUwMmQ3NWI4N2M2OTQ4YzcyMTUxNWMyZWI2OTc1MWQ0YWRmOGE0YTUyMTg3ZWIzYmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.npHrszW76yVGWpOUjP5vj-fDBwX7XXKOJ15fswPNgCo) 没上传好，重新上传一下
