### ISSUE TITLE
OCR 选取框二次选择错位

### ISSUE THREAD

**Issue by BrokenMyth** [HIllya51/LunaTranslator#589]
![bitza-4hr25](https://github.com/HIllya51/LunaTranslator/assets/69298820/ee1f775f-0e9a-498b-b1ab-ed1c1e48ce6a)

如图所示, 第一次选取正常, 但是第二次选取的时候出现错误, 无法正常选取范围。
使用的软件版本是 v2.37.4 (最新版v2.39.1 也试过也会复现)
双显示器(4k+2k扩展屏)下运行，只在4k显示器上运行测试，不确定是否是2k扩展屏导致

**Comment by HIllya51** [comment]
OCR设置->查看处理效果

**Comment by BrokenMyth** [comment]
![image](https://github.com/HIllya51/LunaTranslator/assets/69298820/a84cad75-d1fa-47b9-9025-685753d21b4d)

**Comment by HIllya51** [comment]
这不是全都正常吗？哪错位了？

**Comment by BrokenMyth** [comment]
看动图, 第一次选取的时候是正常选取的, 但是第二次选取的时候就错位了

**Comment by HIllya51** [comment]
是每次都会触发还是概率触发？

**Comment by BrokenMyth** [comment]
稳定复现 , 每次第二次选取都会错位, 比如说用一些快捷键 ocr 识别的时候每次都错位了

**Comment by HIllya51** [comment]
我这里完全不会触发。

**Comment by HIllya51** [comment]
那没办法了 我这里目前只有一个屏幕
