### ISSUE TITLE
朗读的问题

### ISSUE THREAD

**Issue by csquya** [HIllya51/LunaTranslator#59]
很喜欢这个翻译器。 但是有以下3个问题能否改进下，谢谢。

1. 请问朗读能否跳过游戏本身的语音？ 2个声音叠在一起乱了，vnr可以跳过。如果开自动朗读的话，那么游戏开始之前还没有正确提取文本之前会有好多杂音，容易卡死死机。
2. 这个翻译器似乎会多开，例如在切换游戏的时候， 这同样会引起乱提取文本， 从而导致卡死
3. 取词用词典查词似乎不行，只有一次成功了，其他都是点击单词无反应。 mecab分词/颜色 功能似乎没有起作用， 还在开发吗？

另外一个请求和本翻译器无关，我非常中意 pagago翻译网站，这个网站的翻译质量较高，所以能否在vnr中也做一个， vnr中有好多翻译api没用了，随便取一个修改成pagago的，理论上应该可行，大佬如能造福一下我等小白，万分感谢。

**Comment by HIllya51** [comment]
1、你可以选择将游戏内的语音静音
2、。。。那你干嘛要多开呢= = 
3、我这里很正常。你有下载词典吗？没有下载是不可以的

**Comment by HIllya51** [comment]
我直接把google改成papago了，测试可用。
直接覆盖vnr的这个文件Library\Frameworks\Sakura\py\libs\google\googletrans.py即可

**Comment by HIllya51** [comment]
# coding: utf8
# googletrans.py
# 8/2/2013 jichi

if __name__ == '__main__':
  import sys
  sys.path.append('..')

__all__ = 'GoogleTranslator', 'GoogleHtmlTranslator', 'GoogleJsonTranslator'
import uuid
import requests
from sakurakit import sknetdef
from sakurakit.skdebug import dwarn, derror
from sakurakit.skstr import unescapehtml
import googledef
import math
import re
import requests
import time


FANYI_TKK = ""
FANYI_Time = 0
FANYI_Hour = 0
TimeSpan = 1800
session = requests


def getTKK(text):
    r = re.search(r'tkk:[\S](\d+\.\d+)', text, re.M|re.S)
    if r:
        return r.group(1)
    else:
        return ""


def getSource():
    req = session.get("https://translate.google.cn")
    if req.ok:
        return req.content
    else:
        return ""


def checkTime():
    global FANYI_Time
    global FANYI_Hour
    global FANYI_TKK
    t = time.time()
    h = time.localtime(t).tm_hour
    istrue = t - FANYI_Time > TimeSpan or h != FANYI_Hour or FANYI_TKK == ""
    if istrue:
        FANYI_Time = t
        FANYI_Hour = h
        dwarn("check tkk", FANYI_TKK)
    return istrue


def tryUpdataTkk():
    global FANYI_TKK
    if checkTime():
        source = getSource()
        if source != "":
            tkk = getTKK(source)
            dwarn("updata tkk", tkk)
            if tkk != "" and tkk != FANYI_TKK:
                FANYI_TKK = tkk


def orz(x, y):
    for t in range(0, len(y) -2, 3): 
        a = y[t + 2]
        if a >= 'a':
            a = ord(a[0]) -87
        else:
            a = int(a)
        if '+' == y[t + 1]:
            a = (x >> a) & int("11111111111111111111111111111111"[a:], 2)
        else:
            a = x << a
        if '+' == y[t]:
            x = x + a & 4294967295
        else:
            x = x ^ a
    return x


def getSign(a):
    d = FANYI_TKK.split('.')
    z = int(d[0]) or 0
    s = int(d[1]) or 0
    S = []
    c = 0
    for v in range(0, len(a), 1):
        A = ord(a[v])
        if 128 > A:
            S.append(A)
        else:
            if 2048 > A :
                S.append(A >> 6 | 192)
            else:
                if (55296 == (64512 & A) and (v + 1) < len(a) and 56320 == (64512 & ord(a[v + 1]))):
                    A = 65536 + ((1023 & A) << 10) + (1023 & ord(a[++v]))
                    S.append(A >> 18 | 240)
                    S.append(A >> 12 & 63 | 128)
                else:
                    S.append(A >> 12 | 224)
                    S.append(A >> 6 & 63 | 128)
            S.append(63 & A | 128)
    p = z
    for b in range(0, len(S), 1):
        p += S[b]
        p = orz(p, '+-a^+6')
    p = orz(p, '+-3^+b+-f')
    p ^= s
    if 0 > p:
         p = (2147483647 & p) + 2147483648
    p %= 1000000
    return str(p) + '.' + str(p ^ z)


# https://translate.google.cn/translate_a/single?client=webapp&sl=ja&tl=zh-CN&hl=zh-CN&dt=t&tk=876620.785187&q=
# User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
# Host: translate.google.cn

def u_translate(text, to='zhs', fr='ja', session = requests):
    tm=str(int(time.time()*1000))
    
    if True:
        ssss=requests.session() 
        ssss.get('https://papago.naver.com/', 
        headers = {
            'authority': 'papago.naver.com',
            'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
            'accept-language': 'zh-CN,zh;q=0.9', 
            'sec-ch-ua': '"Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"',
            'sec-ch-ua-mobile': '?0',
            'sec-ch-ua-platform': '"Windows"',
            'sec-fetch-dest': 'document',
            'sec-fetch-mode': 'navigate',
            'sec-fetch-site': 'none',
            'sec-fetch-user': '?1',
            'upgrade-insecure-requests': '1',
            'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36',

        }, ).text
        import hmac,base64
        ssssuuid=uuid.uuid4().__str__()
        def get_auth( url, auth_key, device_id, time_stamp): 
                auth = hmac.new(key=auth_key.encode(), msg=(device_id+'\n'+url+'\n'+str(time_stamp)).encode() ).digest()
                return 'PPG '+device_id+':'+base64.b64encode(auth).decode()
        headers = {
            'authority': 'papago.naver.com',
            'accept': 'application/json',
            'accept-language': 'zh-CN',
            'authorization':  get_auth('https://papago.naver.com/apis/n2mt/translate','v1.7.1_12f919c9b5',ssssuuid,tm),
            'content-type': 'application/x-www-form-urlencoded; charset=UTF-8', 
            'device-type': 'pc',
            'origin': 'https://papago.naver.com',
            'referer': 'https://papago.naver.com/',
            'sec-ch-ua': '"Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"',
            'sec-ch-ua-mobile': '?0',
            'sec-ch-ua-platform': '"Windows"',
            'sec-fetch-dest': 'empty',
            'sec-fetch-mode': 'cors',
            'sec-fetch-site': 'same-origin',
            'timestamp': tm,
            'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36',
            'x-apigw-partnerid': 'papago',
        }

        data = { 
            'deviceId':ssssuuid,
            'locale': 'zh-CN',
            'dict': 'true',
            'dictDisplay': '30',
            'honorific': 'false',
            'instant': 'false',
            'paging': 'false',
            'source':'ja' ,
            'target': 'zh-CN',
            'text': text,
        }
    
        r = ssss.post('https://papago.naver.com/apis/n2mt/translate', headers= headers , data =data  )

        data = r.json()   
        return  data['translatedText'] 
     
# Remove repetive comma only before "or[ and after "or].
_re_gson_comma = re.compile(r'(?<=[\]"],),+(?=[\["])')
def eval_gson_list(data): pass
class GoogleTranslator(object): pass

class GoogleHtmlTranslator(GoogleTranslator):
  session = requests
  def translate(self, t, to='auto', fr='auto'): 
    return u_translate(t, 'zhs', 'ja', session)


class GoogleJsonTranslator(GoogleTranslator):
  session = requests
  def translate(self, t, to='auto', fr='auto', align=None): 
    return u_translate(t, 'zhs', 'ja', session)
  def _iteralign(self, data): pass
  def analyze(self, t, to='auto', fr='auto', align=None): pass


if __name__ == '__main__':
  s = u"本田"
  t = translate(s, to='zhs', fr='ja')
  #t = translate(u"神楽", to='zhs', fr='ja')
  print t

# EOF

**Comment by HIllya51** [comment]
`
# coding: utf8
# googletrans.py
# 8/2/2013 jichi

if __name__ == '__main__':
  import sys
  sys.path.append('..')

__all__ = 'GoogleTranslator', 'GoogleHtmlTranslator', 'GoogleJsonTranslator'
import uuid
import requests
from sakurakit import sknetdef
from sakurakit.skdebug import dwarn, derror
from sakurakit.skstr import unescapehtml
import googledef
import math
import re
import requests
import time


FANYI_TKK = ""
FANYI_Time = 0
FANYI_Hour = 0
TimeSpan = 1800
session = requests


def getTKK(text):
    r = re.search(r'tkk:[\S](\d+\.\d+)', text, re.M|re.S)
    if r:
        return r.group(1)
    else:
        return ""


def getSource():
    req = session.get("https://translate.google.cn")
    if req.ok:
        return req.content
    else:
        return ""


def checkTime():
    global FANYI_Time
    global FANYI_Hour
    global FANYI_TKK
    t = time.time()
    h = time.localtime(t).tm_hour
    istrue = t - FANYI_Time > TimeSpan or h != FANYI_Hour or FANYI_TKK == ""
    if istrue:
        FANYI_Time = t
        FANYI_Hour = h
        dwarn("check tkk", FANYI_TKK)
    return istrue


def tryUpdataTkk():
    global FANYI_TKK
    if checkTime():
        source = getSource()
        if source != "":
            tkk = getTKK(source)
            dwarn("updata tkk", tkk)
            if tkk != "" and tkk != FANYI_TKK:
                FANYI_TKK = tkk


def orz(x, y):
    for t in range(0, len(y) -2, 3): 
        a = y[t + 2]
        if a >= 'a':
            a = ord(a[0]) -87
        else:
            a = int(a)
        if '+' == y[t + 1]:
            a = (x >> a) & int("11111111111111111111111111111111"[a:], 2)
        else:
            a = x << a
        if '+' == y[t]:
            x = x + a & 4294967295
        else:
            x = x ^ a
    return x


def getSign(a):
    d = FANYI_TKK.split('.')
    z = int(d[0]) or 0
    s = int(d[1]) or 0
    S = []
    c = 0
    for v in range(0, len(a), 1):
        A = ord(a[v])
        if 128 > A:
            S.append(A)
        else:
            if 2048 > A :
                S.append(A >> 6 | 192)
            else:
                if (55296 == (64512 & A) and (v + 1) < len(a) and 56320 == (64512 & ord(a[v + 1]))):
                    A = 65536 + ((1023 & A) << 10) + (1023 & ord(a[++v]))
                    S.append(A >> 18 | 240)
                    S.append(A >> 12 & 63 | 128)
                else:
                    S.append(A >> 12 | 224)
                    S.append(A >> 6 & 63 | 128)
            S.append(63 & A | 128)
    p = z
    for b in range(0, len(S), 1):
        p += S[b]
        p = orz(p, '+-a^+6')
    p = orz(p, '+-3^+b+-f')
    p ^= s
    if 0 > p:
         p = (2147483647 & p) + 2147483648
    p %= 1000000
    return str(p) + '.' + str(p ^ z)


# https://translate.google.cn/translate_a/single?client=webapp&sl=ja&tl=zh-CN&hl=zh-CN&dt=t&tk=876620.785187&q=
# User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
# Host: translate.google.cn

def u_translate(text, to='zhs', fr='ja', session = requests):
    tm=str(int(time.time()*1000))
    
    if True:
        ssss=requests.session() 
        ssss.get('https://papago.naver.com/', 
        headers = {
            'authority': 'papago.naver.com',
            'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
            'accept-language': 'zh-CN,zh;q=0.9', 
            'sec-ch-ua': '"Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"',
            'sec-ch-ua-mobile': '?0',
            'sec-ch-ua-platform': '"Windows"',
            'sec-fetch-dest': 'document',
            'sec-fetch-mode': 'navigate',
            'sec-fetch-site': 'none',
            'sec-fetch-user': '?1',
            'upgrade-insecure-requests': '1',
            'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36',

        }, ).text
        import hmac,base64
        ssssuuid=uuid.uuid4().__str__()
        def get_auth( url, auth_key, device_id, time_stamp): 
                auth = hmac.new(key=auth_key.encode(), msg=(device_id+'\n'+url+'\n'+str(time_stamp)).encode() ).digest()
                return 'PPG '+device_id+':'+base64.b64encode(auth).decode()
        headers = {
            'authority': 'papago.naver.com',
            'accept': 'application/json',
            'accept-language': 'zh-CN',
            'authorization':  get_auth('https://papago.naver.com/apis/n2mt/translate','v1.7.1_12f919c9b5',ssssuuid,tm),
            'content-type': 'application/x-www-form-urlencoded; charset=UTF-8', 
            'device-type': 'pc',
            'origin': 'https://papago.naver.com',
            'referer': 'https://papago.naver.com/',
            'sec-ch-ua': '"Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"',
            'sec-ch-ua-mobile': '?0',
            'sec-ch-ua-platform': '"Windows"',
            'sec-fetch-dest': 'empty',
            'sec-fetch-mode': 'cors',
            'sec-fetch-site': 'same-origin',
            'timestamp': tm,
            'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36',
            'x-apigw-partnerid': 'papago',
        }

        data = { 
            'deviceId':ssssuuid,
            'locale': 'zh-CN',
            'dict': 'true',
            'dictDisplay': '30',
            'honorific': 'false',
            'instant': 'false',
            'paging': 'false',
            'source':'ja' ,
            'target': 'zh-CN',
            'text': text,
        }
    
        r = ssss.post('https://papago.naver.com/apis/n2mt/translate', headers= headers , data =data  )

        data = r.json()   
        return  data['translatedText'] 
     
# Remove repetive comma only before "or[ and after "or].
_re_gson_comma = re.compile(r'(?<=[\]"],),+(?=[\["])')
def eval_gson_list(data): pass
class GoogleTranslator(object): pass

class GoogleHtmlTranslator(GoogleTranslator):
  session = requests
  def translate(self, t, to='auto', fr='auto'): 
    return u_translate(t, 'zhs', 'ja', session)


class GoogleJsonTranslator(GoogleTranslator):
  session = requests
  def translate(self, t, to='auto', fr='auto', align=None): 
    return u_translate(t, 'zhs', 'ja', session)
  def _iteralign(self, data): pass
  def analyze(self, t, to='auto', fr='auto', align=None): pass


if __name__ == '__main__':
  s = u"本田"
  t = translate(s, to='zhs', fr='ja')
  #t = translate(u"神楽", to='zhs', fr='ja')
  print t

# EOF
`

**Comment by HIllya51** [comment]
链接: https://pan.baidu.com/s/1y1xe54woP9eQL_ahIrjqsw?pwd=9m9a 提取码: 9m9a 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by csquya** [comment]
>

**Comment by csquya** [comment]
> 1、你可以选择将游戏内的语音静音 2、。。。那你干嘛要多开呢= = 3、我这里很正常。你有下载词典吗？没有下载是不可以的

1. 游戏内的读音更有味啊，开朗读主要是想知道里边的汉字怎么读
2. 不是我要多开，而是有时候不小心没注意去退出，这个我碰到好几次了。
3. 当然下载词典了，4个字典都下载了。大多数时候无法查词，一直无法分词。 我的系统是windows 10

不管怎么说，这个软件已经很棒了，如果再改进些，就可以不用vnr了

**Comment by csquya** [comment]
> 我直接把google改成papago了，测试可用。 直接覆盖vnr的这个文件Library\Frameworks\Sakura\py\libs\google\googletrans.py即可
已测试，太好了，真的谢谢你！！

**Comment by HIllya51** [comment]
1、emm 我试了一下vnr似乎并不能中断 不知道你是怎么做到的。。而且要做这个也太麻烦了。而且想知道读音可以开启显示假名。。
2、有别人是有多开的需求的
3、要不然你试试重新下载解压一下？我是可以用的。

**Comment by csquya** [comment]
关于查词和分词的问题，我找到了问题所在。

原来三本词典的设置都是false， 这个设置在界面上不知道为什么没有了（我猜以前是有的，后来丢失了）， 所以只能到userconfig文件夹里手动修改config文件，而关于分词的颜色设置，界面上也没有enable按钮，设置里我找不到，还望告知。

另，多开的问题我认为还是有必要限制，我在正常关闭的情况下依旧有， 每次我都要到任务管理器里找出来关闭，一旦积累了很多个，就卡死了。ocr.exe, minmaxmoveobserve.exe 等程序也会多开， ocr即使不用他的时候也会启动。

**Comment by HIllya51** [comment]
emm 然而虽然有这么个设置 后面根本没有用它。。。算了版本太乱了
颜色分词这个只要开启了Mecab，并且开启显示分词就可以了
多开这个，我加一个设置吧。

**Comment by csquya** [comment]
> emm 然而虽然有这么个设置 后面根本没有用它。。。算了版本太乱了 颜色分词这个只要开启了Mecab，并且开启显示分词就可以了 多开这个，我加一个设置吧。

分词颜色根本没显示，开启显示分词这个按钮也是空白的，不过这倒是个小问题，只是个人认为是否美观的问题，也许需要删除userconfig文件夹让它重新恢复默认设置？

**Comment by HIllya51** [comment]
你开自动更新了吗？可能是自动更新时软件未正常退出导致的，手动解压一下试试

**Comment by HIllya51** [comment]
。。。你把你的config发给我看一下？

**Comment by csquya** [comment]
config 发在以下链接了。
https://zyaqu.com/file/wl/?id=2jnbTr2WRI0SLdNbQgHqLbTVjIG0Y5UP

**Comment by HIllya51** [comment]
。。。这几个地方本来就没有按钮

**Comment by csquya** [comment]
> 。。。这几个地方本来就没有按钮

好吧，那没有按钮，至少默认可以分词和取词， 现在每次都要 uncheck-check 一次“使用Mecab辞书分词”一次，否则就是无法显示假名，也无法取词翻译，这个设置不会保存， 退出再开就又要设置一次。 而 “不同词性颜色设置” 这个根本就从来没起过作用。请抽空看下怎么回事。谢谢

**Comment by HIllya51** [comment]
。。。你重新下载一下试试？我用你的配置完全正常

**Comment by csquya** [comment]
我已经下载无数次了， 今天换了台电脑在单位也是一样的问题， 这次这台电脑是以前从来没装过的。要不你加下我微信，晚上你远程我电脑看看？现在的情况不是无法取词和分词，而是这个设置不会保存，退出再进就没了，每次都要设置下

**Comment by HIllya51** [comment]
你把软件整个目录打包发给我看一下。

**Comment by csquya** [comment]
> 你把软件整个目录打包发给我看一下。

已经上传到了老地方，不过我这个自己做的网盘可能速度不给力，最近封网又厉害，不一定能连上。 最好还是加个微信。

**Comment by HIllya51** [comment]
检查出来了，第三方库没有处理带空格的路径🥶

**Comment by csquya** [comment]
> 检查出来了，第三方库没有处理带空格的路径🥶

1.26.6 已经修正了分词和取词的问题，太好了
