### ISSUE TITLE
新版2.39.1 的“ChatGPT_离线“ 离线翻译功能有换行 BUG

### ISSUE THREAD

**Issue by BrokenMyth** [HIllya51/LunaTranslator#591]
**环境:**  
- Luna 版本为 2.39.1 
- 只使用了一个屏幕
- 只开启了 ChatGPT_离线翻译功能
- 本地的 TGW 使用的是的 Sakura-13B 模型。

**BUG 复现流程：**
如三张图, 分别是第一, 二, 三次 ocr 翻译。
第一张图如下，使用 ocr 进行 gpt 翻译，翻译框中正常输出结果。
![Snipaste_2024-03-18_21-04-39](https://github.com/HIllya51/LunaTranslator/assets/69298820/066402f0-5a2d-40e3-9e98-c6f7194f99e3)
第二张图如下，使用 ocr 进行 gpt 翻译，控制台可以看到请求了多次 token，在翻译框中进行了多次换行并输出结果。
![Snipaste_2024-03-18_21-04-55](https://github.com/HIllya51/LunaTranslator/assets/69298820/fcfb0dcb-b250-4f51-86c2-ffdd951d3b24)
第三张图如下，同样使用 ocr 进行 gpt 翻译，控制台可以看到请求了多次 token，在翻译框中进行了多次换行并输出结果。
![Snipaste_2024-03-18_21-05-04](https://github.com/HIllya51/LunaTranslator/assets/69298820/30d0f4ad-4987-4d13-b902-02589b282f45)
**旧版本：** 2.37.4 使用 TGW 语言模型离线翻译功能，不会出现这种情况

**Comment by HIllya51** [comment]
你言语混乱，建议重新组织好语言再来问我。

**Comment by BrokenMyth** [comment]
我改了下描述，看看这样清楚不

**Comment by HIllya51** [comment]
你看一下历史翻译，看看是文字带换行还是翻译带换行

**Comment by HIllya51** [comment]
你是开了流式输出吧？
算了就这样吧，我想着这玩意儿都是和gpt一样的想整合到一起来着，我回档了，2.39.2把TGW加回去了。
