### ISSUE TITLE
百度又坏了，今天玩游戏时9点10分左右坏的，基本上都是报错了，难得有一句是正常的

### ISSUE THREAD

**Issue by wycstc353** [HIllya51/LunaTranslator#592]
百度又坏了，今天玩游戏时9点10分左右坏的，基本上都是报错了，难得有一句是正常的
![T3S3U4H`_Z%L {24TD M9OD](https://github.com/HIllya51/LunaTranslator/assets/39401653/77482258-1159-46f9-a278-635aeb9c8c0d)

**Comment by HIllya51** [comment]
你就不能换个用吗，非要盯着百度用。。。你被反爬虫了，我这里没问题。

**Comment by HIllya51** [comment]
你就不能换个用吗，非要盯着百度用。。。你被反爬虫了，我这里没问题。

**Comment by wycstc353** [comment]
> 你就不能换个用吗，非要盯着百度用。。。你被反爬虫了，我这里没问题。

……那反爬虫是我这边差不多多久不能用百度啊，习惯用这三个对比了

**Comment by HIllya51** [comment]
你可以用develop里的百度，这个不会被反爬
