### ISSUE TITLE
部分Renpy游戏开启HOOK翻译后原文本会出现乱码+使用专有名词翻译给人物命名时会固定翻译成泽贝塔（随机且只出现在彩云注册）＋内嵌翻译有时会无视选定的翻译，与选定的翻译文本有出入

### ISSUE THREAD

**Issue by Z9wind** [HIllya51/LunaTranslator#595]
RT，第一个问题正好碰到有截图，后面两个都是之前游玩时出现的没截图
<img width="971" alt="微信图片_20240320010625" src="https://github.com/HIllya51/LunaTranslator/assets/107527857/9e9ad07a-8281-46a6-9c8b-2d7ea8faa291">
<img width="963" alt="微信图片_20240320010646" src="https://github.com/HIllya51/LunaTranslator/assets/107527857/a5503d48-a5db-47bb-9d65-d8e84b259049">

**Comment by HIllya51** [comment]
设置字体了吗

**Comment by Z9wind** [comment]
> 设置字体了吗

内嵌的字体是设置了的，但是这个游戏没有勾选内嵌（我把改字体关了试试），原文也是原游戏的字体没变，luna的界面是也设置了的

**Comment by HIllya51** [comment]
回复之前自己读一下行不行？完全看不懂你在说什么

**Comment by Z9wind** [comment]
> 回复之前自己读一下行不行？完全看不懂你在说什么

意思是内嵌的字体我都有更改的，但是这个游戏没有勾选内嵌功能（截图里也能看到）。然后原文这里指的是如果我改的字体生效的话游戏界面的字体也会变化，但我截图中游戏界面的字体就是原游戏的字体，所以我想就算我内嵌选项卡这里勾选了更改字体对游戏也是没影响的。然后以防万一你问的是LUNA界面的字体，我也回答了更改了字体。就是这样。
顺便我把字体更改×上了，游戏内文本还是受到了影响。
<img width="1227" alt="微信截图_20240320011828" src="https://github.com/HIllya51/LunaTranslator/assets/107527857/deb9d5cb-7194-4e81-8f2b-fda5ce92569b">

**Comment by HIllya51** [comment]
沟通困难 算了 你直接把游戏发给我吧（谷歌/onedrive）

**Comment by Z9wind** [comment]
我并没觉得我说得很混乱，那就这样吧辛苦你了，当我没说。

**Comment by HIllya51** [comment]
看了半天我还是没理解你怎么操作的。
你要是觉得有兴趣发游戏给我我可以自己试试，你要是觉得无所谓那就这样吧

**Comment by HIllya51** [comment]
下了个demo测试了。你换成internal_renpy_call_host这个内嵌翻译就行了。
<img width="1128" alt="屏幕截图 2024-03-20 131046" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/04171a38-b209-4a39-b281-6d19f01e5e74">

**Comment by HIllya51** [comment]
我自己找到你这个游戏复现并修复了这个bug，重新下载最新版就可以了

**Comment by Z9wind** [comment]
谢谢, 辛苦您了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月20日(周三) 中午1:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [HIllya51/LunaTranslator] 部分Renpy游戏开启HOOK翻译后原文本会出现乱码+使用专有名词翻译给人物命名时会固定翻译成泽贝塔（随机且只出现在彩云注册）＋内嵌翻译有时会无视选定的翻译，与选定的翻译文本有出入 (Issue #595)




 
我自己找到你这个游戏复现并修复了这个bug，重新下载最新版就可以了
