### ISSUE TITLE
这个游戏hook的文本不全

### ISSUE THREAD

**Issue by lawiest** [HIllya51/LunaTranslator#596]
![image](https://github.com/HIllya51/LunaTranslator/assets/50625377/76a35046-b1a7-4aa9-a6bb-127ebb16e4de)

如图，他也不是完全hook不到，有时候是全的，有时候不全，感觉挺奇怪

游戏：
https://1drv.ms/u/c/d0994c518dc5fead/Ec2r6D74JK5IqSsssEgszp8B3dqZ0FLFC3xigfusWan5pQ?e=LoxXdF

**Comment by HIllya51** [comment]
HA4@425E26
