### ISSUE TITLE
功能建议：UI窗口、文本并行翻译

### ISSUE THREAD

**Issue by mutouchan** [HIllya51/LunaTranslator#6]
1、UI窗口：
允许越过翻译框进行点击等操作，即可以对翻译框底下的窗口进行操作。

2、文本并行翻译：
简单来说是允许同时选中两种或多种文本提取方式进行翻译，**参考VNR**。
因为像是HULOTTE这种公司的游戏，会用不同尺寸的字体表示角色说话情绪：像是表示角色激动大声说话时用“放大、加粗字体”，细语的时候又用更小一号的字体。**这类文本没法从原先正常文本提取方式（方式A）中找到，会单独出现在别的提取方式（方式B），方式A和方式B文本不重复**，因为目前没在玩HULOTTE的游戏，没法提供截图说明，趁开发大佬还没躺平，提前建议一下OTZ。

**Comment by HIllya51** [comment]
1已实现，2比较难搞，还得等一短时间。。。

**Comment by HIllya51** [comment]
2功能已实现，可以选择多个条目了，而且选择文本窗口进行了大改，马上更新。

**Comment by login404** [comment]
能否在重启后保持鼠标穿透的开关?
