### ISSUE TITLE
工具栏按钮上悬停时的提示文字不显示或显示后很快消失

### ISSUE THREAD

**Issue by 2-3-5-7** [HIllya51/LunaTranslator#60]
当我想看看新添加的工具栏按钮是什么功能时，我把指针悬停在按钮上，但提示文字很快消失，或根本不显示。
比如我想看看这个全屏按钮的提示文字
![image](https://user-images.githubusercontent.com/79762374/201554088-02b9be03-a1e0-4e3b-aeb4-08cd5910d6dd.png)

我不确定是否和系统有关，用的 win11

**Comment by HIllya51** [comment]
已修正
