### ISSUE TITLE
功能请求 语音合成添加正则表达式替换

### ISSUE THREAD

**Issue by Hooll31saz** [HIllya51/LunaTranslator#600]
1)可以在只有语音合成所使用的文本上添加自订的正则表达式替换吗?
我希望可以对某些汉字名称的角色读音进行修正，及让某些文本不朗读出来。

2)请帮助添加NeoSpeech的Show语音
档案https://mega.nz/file/BzIWBYJR#s0fZh_kX4EB4Y6DJmKi9UZad9qbbEpvoESQ4foqVW9o

**Comment by HIllya51** [comment]
ok
