### ISSUE TITLE
我无法启动.exe文件

### ISSUE THREAD

**Issue by joty7845** [HIllya51/LunaTranslator#602]
你好，我想请问一下，我无法启动.exe文件，我的系统是win10，第一次使用的时候启动成功设置完离线chat后加载进游戏窗口就消失了，后面重新下和设置win10病毒排除项都无法解决这个问题

![屏幕截图 2024-03-23 235816](https://github.com/HIllya51/LunaTranslator/assets/144857075/f74ca42e-8fdd-4585-a936-6d5245c95632)
![屏幕截图 2024-03-23 235728](https://github.com/HIllya51/LunaTranslator/assets/144857075/f3dd9aa3-edd8-4f94-8e85-ad97921e8700)

**Comment by LCFjive** [comment]
encounter same problem

**Comment by HIllya51** [comment]
如何复现。

**Comment by joty7845** [comment]
我没办法打开.exe启动程序了，复现不了之前的问题，这是不是跟系统有关？

**Comment by HIllya51** [comment]
看一下是不是LunaTranslator/LunaTranslator_main.exe没了 外面的那两个exe没什么卵用

**Comment by joty7845** [comment]
嗷，是的,确实不见了
