### ISSUE TITLE
我游戏怎么翻译不出来了

### ISSUE THREAD

**Issue by 2262953850** [HIllya51/LunaTranslator#604]
![屏幕截图 2024-03-24 161243](https://github.com/HIllya51/LunaTranslator/assets/125784110/65f09849-7623-4f42-b0af-43318fa6b036)
一翻译就这样了，用其他的翻译源也翻译不了

**Comment by 2262953850** [comment]
gpt翻译以前没问题的，那个地址也是对的，代理也开了，用其他的翻译源那个中文文本都不显示，日文倒是显示了

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/issues/603
