### ISSUE TITLE
Systemnnn Hook失效

### ISSUE THREAD

**Issue by Refrain69** [HIllya51/LunaTranslator#607]
游戏：褐色の性戦士アイシャ
问题：
之前的2.28.3版本可以正常hook文本，现有的两个release版本均无法正常hook：1.文本刷新延迟严重 2.部分hook只能提取到一小部分文本。
然而提取出来的文本是正常的（预处理后），翻译时延迟严重
![2024-03-27_21 02 29--2024-03-27 20-41-37 (1) mp4--00 00 00--11 0s](https://github.com/HIllya51/LunaTranslator/assets/121091208/1e21cbe4-249f-4661-a980-34b518a8074d)
如图

**Comment by Refrain69** [comment]
正在传od，度盘可以吗

**Comment by HIllya51** [comment]
不行 没会员。

**Comment by Refrain69** [comment]
https://1drv.ms/u/s!Aj-UH23UOmFNg1nNmkBZ-5l_jSQ8?e=Bbgt0I

**Comment by HIllya51** [comment]
<img width="490" alt="屏幕截图 2024-03-28 003504" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/2e33ec57-39ee-4c00-bbad-36f627d35941">


我佛了 这游戏有两个hook啊，你干嘛非得选那个刷新的，另一个根本不刷新。

**Comment by Refrain69** [comment]
我知道…………hook出来的文本没问题，但是翻译时有问题：
比如一长句话，前面那几个短句快速略过了，只剩最后半句。
<img width="1109" alt="屏幕截图 2024-03-28 184812" src="https://github.com/HIllya51/LunaTranslator/assets/121091208/1e69d78a-bd6f-41ea-8762-5e135b9110d7">
如图，原句是
だが、何よりアイシャを美しく見せているのは、
その絹のようにきめ細やかな褐色の肌だった。
hook出来也正确，但是翻译框只剩后半句了

**Comment by HIllya51** [comment]
刷新延迟++

**Comment by Refrain69** [comment]
解决，谢谢
