### ISSUE TITLE
v2.40版的问题

### ISSUE THREAD

**Issue by Hooll31saz** [HIllya51/LunaTranslator#608]
1)v2.40版汇出的json档，原文是没有进行过优化处理的文本。
左边是v2.40版，右边是v2.39版
![螢幕擷取畫面 2024-03-27 224613](https://github.com/HIllya51/LunaTranslator/assets/164517422/7b807aeb-3a97-4312-87ba-4b7ca11e0cd2)

2)使用语音合成NeoSpeech朗读时，会有叠合的问题。
例：原文
第1段	そんな言葉を言ったのは誰だったろう？
第2段	誰が言ったのかは思い出せないが、その言葉はまさに真実だと思う。
第3段	今まで生きていて、楽しかった思い出なんてほとんどない。
第4段	そのうえ、俺の日常はとても退屈だ。

朗讀時	
第1段	そんな言葉を言ったのは誰だったろう？
第2段	誰が言ったのかは思い出せないが、その言葉はまさに真実だと思う。
第3段	今まで生きていて、楽しかった思い出なんてほとんどない。と思う。
第4段	そのうえ、俺の日常はとても退屈だ。なんてほとんどない。と思う。

**Comment by HIllya51** [comment]
已修正
