### ISSUE TITLE
Google Dev Extension problem

### ISSUE THREAD

**Issue by RkSense** [HIllya51/LunaTranslator#609]
Translation from Google Dev extension doesnt appear in textbox of luna translator but in browser it works just fine.
![2024-03-28](https://github.com/HIllya51/LunaTranslator/assets/62306978/7c7904a4-62c6-499d-888b-9c8a42028ecc)

**Comment by HIllya51** [comment]
<img width="811" alt="屏幕截图 2024-03-28 153837" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/295d46f9-d1ab-46b6-a6a4-4505964add09">

show me the error log.

**Comment by RkSense** [comment]
> <img alt="屏幕截图 2024-03-28 153837" width="811" src="https://private-user-images.githubusercontent.com/101191390/317638503-295d46f9-d1ab-46b6-a6a4-4505964add09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NDc5ODksIm5iZiI6MTcxMTY0NzY4OSwicGF0aCI6Ii8xMDExOTEzOTAvMzE3NjM4NTAzLTI5NWQ0NmY5LWQxYWItNDZiNi1hNmE0LTQ1MDU5NjRhZGQwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxNzQxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjY1MzNmNDFlZThjNmU3NmVhYTRiZDdhOWU2MDY2ZGYxMjE1ZWNmOTllMDllNDZiMDY2Mjg5NmE0ZmU1NmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NFvRcOKgzf38xtDat5HhMXGKMmo0B4Ws1nHwUKFhmzY">
> show me the error log.

![2024-03-28 (2)](https://github.com/HIllya51/LunaTranslator/assets/62306978/df894888-f0a4-42be-9f0a-66a832aea9ec)

**Comment by HIllya51** [comment]
It's not the log of the error "KeyError 'method'". You should show me the log of the error "KeyError 'method'".

**Comment by HIllya51** [comment]
fixed
