### ISSUE TITLE
建议优化一下自动更新

### ISSUE THREAD

**Issue by EXBJAN** [HIllya51/LunaTranslator#61]
目前自动更新总是失败，无论挂不挂梯子。
此外，我发现手动下载压缩包解压覆盖的方法会无形中增加多余文件导致越来越大，我从1.20版本一直覆盖更新，今天发现文件夹总大小达到了200多兆。但其实只需要保留userconfig即可，其余都可以删了用新版本替代

**Comment by HIllya51** [comment]
和你所建议的相反，我反而打算移除自动更新功能了。😂

**Comment by HIllya51** [comment]
因为总是更新失败（版本号变了但是程序还是旧版。。。）（因为经常发生退出软件了但是没退出游戏，然后触发更新了。。。但是因为没退出游戏导致有dll没法释放。。。）
改来改去没卵用，现在已经改成躺平策略，只下载zip，剩下的交给用户手动了😂

**Comment by EXBJAN** [comment]
好的吧

**Comment by EXBJAN** [comment]
那就保留个新版本检测得了。
