### ISSUE TITLE
这个游戏有点奇怪，等待三角图标一直在闪，但是个文本一直刷

### ISSUE THREAD

**Issue by lawiest** [HIllya51/LunaTranslator#610]
![image](https://github.com/HIllya51/LunaTranslator/assets/50625377/d619a9b2-a07f-4420-ac87-6ab534cfd63e)

这个游戏的等待闪烁三角居然是文本，而且一直刷，导致翻译一直刷。这个要怎么处理呢？简单的字符替换试过会有问题，文本偶尔会丢失。

游戏
https://1drv.ms/u/c/d0994c518dc5fead/EXSsv7U8VjRHsC_fx4OdxLUB-19TJaJkXcl7_CNXTwtzEQ?e=Ztuf8l

**Comment by HIllya51** [comment]
有什么问题？我试了把三角过滤掉就行了啊

**Comment by lawiest** [comment]
大佬，求问怎么过滤阿，救救孩子

**Comment by HIllya51** [comment]
就简单的字符替换啊，什么怎么过滤

**Comment by lawiest** [comment]
但是我替换了，用有道可以正常翻译，但是用chagpt会偶尔丢失，就是没反应，概率还挺大。我一开始怀疑是chagpt的问题，但是我换个游戏就很正常。
