### ISSUE TITLE
关于语言设置的问题

### ISSUE THREAD

**Issue by ilbuco** [HIllya51/LunaTranslator#611]
开发者你好，有一个关于语言设置的问题，在使用过程中发现，如果我选择翻译及OCR语言的“源语言”是法语或西班牙语等语言后，会显示“本地OCR Exception未下载该语言的OCR模型...”，而我在其他设置的资源下载页面语言包里并没有也没有找到这些语言的OCR包，虽然英文OCR可以识别出没有音符的字母，但出来的结果离原本的意思差距挺远的，甚至有些文本不会被翻译，如方便的话可以改善这方面的问题吗，谢谢。

**Comment by HIllya51** [comment]
不可以，paddleocr不支持的语言我怎么凭空变出来

**Comment by ilbuco** [comment]
或者可以在翻译端选择它的翻译源语言吗，因为感觉尽管英语OCR能识别到，但他的翻译逻辑仍然是按英语的，所以会有差异，因为直接选择翻译源的话部分语言它会显示没有OCR，通常情况下OCR和翻译一一对应即可。

**Comment by HIllya51** [comment]
把模型目录复制一下，改名成fr/es
