### ISSUE TITLE
使用内置和外置的magpie都无法使翻译窗口置顶

### ISSUE THREAD

**Issue by harrylisen** [HIllya51/LunaTranslator#612]
简单的说就是使用缩放软件放大游戏之后就看不到翻译窗口了，不知道是否是我设置的问题，工具栏最右侧的窗口置顶已打开
Luna版本为2.40.5
magpie版本为0.10.6 x64位

**Comment by HIllya51** [comment]
测试未发现问题。

**Comment by harrylisen** [comment]
可能是magpie的原因，关掉这两项就可以置顶了
![image](https://github.com/HIllya51/LunaTranslator/assets/46640121/52531ba7-89d9-4531-9cef-085ef8104f7d)
，但是不能选中翻译栏
