### ISSUE TITLE
[Feature Request] 自动暗黑模式

### ISSUE THREAD

**Issue by Ptilopsis01** [HIllya51/LunaTranslator#614]
如题，晚上推gal的时候lunar白色的界面会非常刺眼，希望可以加入根据系统主题自动切换的暗黑模式

**Comment by HIllya51** [comment]
不会做。。。

**Comment by HIllya51** [comment]
我完全不懂qss，你会搞不？

**Comment by Ptilopsis01** [comment]
不会啊😂

**Comment by HIllya51** [comment]
那没辙咯

**Comment by HIllya51** [comment]
1+

**Comment by HIllya51** [comment]
<img width="963" alt="屏幕截图 2024-04-01 145521" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/c97817f8-3617-4cea-9b40-d0ff0a16a6b3">


ok 全黑了

**Comment by Ptilopsis01** [comment]
好好好
