### ISSUE TITLE
Where to download other language packages for Local OCR

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#617]
My version of Windows doesn't have OCR. I use local OCR from Luna. 
Luna offers to download only 5 language packages from other settings. Where I can download arabic, italian packages for Local OCR?

**Comment by HIllya51** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/paddleocr.py#135 
Download other language rec model and use paddle2onnx to transform it to onnx model.
This program is Visual Novel translate tool, and I don't know any VN which is arabic/italian.

**Comment by Farooq87** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/paddleocr.py#135 Download other language rec model and use paddle2onnx to transform it to onnx model.

You meant to download Paddle OCR and extract from there language folders? And then convert?

**Comment by HIllya51** [comment]
yes

**Comment by Farooq87** [comment]
And paddle2onnx is not a simple software for users like me. Its for programmers. I don't understand how to run it.

**Comment by HIllya51** [comment]
use other ocr functions.

**Comment by Farooq87** [comment]
> Paddle OCR

Could you please add these converted languages models for future Luna updates?

**Comment by HIllya51** [comment]
This OCR is just for Visual Novel, so I'm not interested in other language

**Comment by HIllya51** [comment]
actually, for other language, the paddleocr based local OCR is very poor. I recommand you to use other OCR function rather than local OCR if you use other language.

**Comment by Farooq87** [comment]
> actually, for other language, the paddleocr based local OCR is very poor. I recommand you to use other OCR function rather than local OCR if you use other language.

Since I dont have Windows OCR, I installed Tesseract OCR software and added exe path in Luna.
Is it good?
