### ISSUE TITLE
[Feature Request] 文本框的单行字数限制和换行问题

### ISSUE THREAD

**Issue by Echorish** [HIllya51/LunaTranslator#618]
刚从VNR换来Luna，果断卸载VNR，感觉打开新世界大门。但有时候用多个翻译引擎对照观看，游戏文本稍微长点就自动换行了，导致文本遮盖很大一块画面，尤其是在高分辨率屏幕上这个问题更明显。然而设置中没有找到翻译文本的单行字数限制或者文本栏宽度调整的选项，请问能够加一下这个功能吗？

**Comment by HIllya51** [comment]
显示设置->文本设置->最长显示字数

**Comment by HIllya51** [comment]
显示设置->文本设置->最长显示字数
