### ISSUE TITLE
v2.41版的问题 

### ISSUE THREAD

**Issue by Hooll31saz** [HIllya51/LunaTranslator#619]
1)部分游戏在v2.41版不支援HOOK，在v2.40版却可以
例：風雲相討学園フラットhttps://negativegang.uijin.com/flat.html
檔案：https://drive.google.com/file/d/1tJ_U74358455gWxvu8gNkO5gHoqjtd8d/view

2)![2024-04-02 0147202](https://github.com/HIllya51/LunaTranslator/assets/164517422/aae58c18-8c38-417e-93cc-168fc985ea92)
1：勾选[朗读翻译]后，朗读的是原文。
2：[语音修正]勾选或不勾选一样在执行。

**Comment by HIllya51** [comment]
fixed
