### ISSUE TITLE
快捷键不生效

### ISSUE THREAD

**Issue by 2-3-5-7** [HIllya51/LunaTranslator#62]
看了之前的 issue，特意换到窗口模式。快捷键还是不生效。把焦点给到翻译器，按快捷键也不生效。

<img width="677" alt="11" src="https://user-images.githubusercontent.com/79762374/201805609-6160b145-1d80-4faa-a2e2-c1493c2e9df3.png">

**Comment by HIllya51** [comment]
已修复
