### ISSUE TITLE
[ Feature Request ] 在语音合成中识别人名的更好解决方案

### ISSUE THREAD

**Issue by tiehu** [HIllya51/LunaTranslator#622]
**以下只是我一个粗略的想法，并不要求立即实现功能，只是探讨一下可行性。可以的话希望保留此Issue开启，给日后相关功能的开发（无论是开发者自行实现还是其他人PR）提供一个大致的思路。**

根据#432中提到的，当前如果想实现根据人名判断是否自动朗读文本，是通过一个专门输出人名的hook来判断当前文本的人名的，但这么做也带来了一些问题：
1.就像开发者在#374中提到的一样，部分引擎仅在有人名时才会更新人名，否则就保持不变。这导致翻译器无法正确区分角色对话及跟在角色对话之后的旁白。
2.部分引擎可能只能找到混合了文本和人名的hook，而缺少一个只输出人名的hook。

对于这些问题，我想到一个或许可行的解决方案：
当前hook到的文本有“人名”和“文本”两个类型，可以新增一个“混合”类型，用于处理上面第2点提到的文本。这种文本混合了人名的类型，每次更新对话时都会更新，而且在几乎所有引擎中它的格式都是这样的：
`人名 「对话内容」`
对于旁白，则是这样的：
`对话内容`
关键点就在于引号`「」`，可以发现，只要是对话内容则必定有`「」`，而旁白内容则没有，故可以想到以下逻辑实现人名的判断和与文本的分离（以下只是示例，非实际实现）：
```
#假设text是翻译器拿到的文本对象，且已经过去重等基础文本处理。name代表人名，dialog代表对话或旁白的实际内容。

if "「" not in text:
    name = None
    dialog = text
else:
    textItem = text.split("「")
    name = textItem[0]
    dialog = textItem[1].replace("」", "")
```

现在，我们就可以实现清楚区分旁白和对话，如果是旁白则没有人名，如果是对话则可以将人名和对话分离开来（注意按上面逻辑人名后可能会包含空格）。
接着只要检查`name`来判断是否需要自动朗读，如果需要，再将`dialog`传给TTS引擎。如此一来，就解决了上面提到的两个问题，同时还能保证TTS不会把人名也一起读出来。

如果某些游戏找不到这个”混合“输出（实测大部分游戏都有），则沿用目前的方案，让用户自己选择某个hook输出的类型是”文本“还是”人名“，然后将其直接传给`name`和`dialog`即可。

同时，对于人名的匹配，个人更建议使用（用户端可配置的）正则表达式，而非简单的黑名单屏蔽。因为正则能够实现更高级和复杂的需求（例如结果取反变成白名单、或非全字匹配等）。

**Comment by HIllya51** [comment]
你这说得内容现在本来就已经有了，你在语音合成->语音修正里面把不要读的内容过滤掉不就行了，原文写NAME「(.*?)，替换成空的，这样不就行了。

**Comment by HIllya51** [comment]
莫名其妙，我说的不就是解决这两个的问题的吗。

**Comment by HIllya51** [comment]
哦。”NAME「(.*?)“，你漏看了”(.*?)“吧，加上这个不久把文本也过滤掉了吗。

**Comment by HIllya51** [comment]
打错了，应该是NAME「(.\*)，没有?

**Comment by HIllya51** [comment]
新的规则肯定优先级是最高的，这个没什么好优化的。列表更改顺序太麻烦了，不打算弄。
不过我可以在游戏的独有设置里面添加专用的正则过滤，这样你只在专用过滤里添加就行了
