### ISSUE TITLE
[ Feature Request ] 读完一句对话再读下一句（语音合成缓存机制）

### ISSUE THREAD

**Issue by bzkmsjy** [HIllya51/LunaTranslator#623]
首先非常感谢这款工具，本人由于先天性疾病视力丧失大半，多亏了这款工具能让我在失去大部分视力的情况下依旧能坚持自己的爱好，真的很感谢作者！

我碰到的问题是，在一些AUTO模式最低速度也比较快的游戏里，比如最近的《ROOT DOUBLE》，游戏自动推进对话的速度经常超过了OCR+语音合成的速度，导致经常一句对话还没读完就被下一句对话打断，而纯手工点击对话的话又会太慢，如果能给语音合成增加一个缓存机制，在朗读时做到完全读完一句对话再读下一句，就帮大忙了，因为大部分游戏存在“……”这样的对话和场景转场的时间，总体上朗读速度是能追得上游戏推进速度的，而单纯把语速调快的收听体验并不好。

另外就是深色模式的适配如果能更全面一些就好了，比如设置界面，任务栏右键菜单之类的，我开设置界面的时候需要屏幕反转颜色，如果OCR没关闭有时候程序会直接闪退掉。

**Comment by HIllya51** [comment]
似乎你的意思并不是”缓存“，而是不打断吧。
任务栏右键菜单忘了弄了。设置界面有啥问题吗？
另外”需要屏幕反转颜色，如果OCR没关闭有时候程序会直接闪退掉。“这个我不太理解是什么含义。

**Comment by HIllya51** [comment]
重下最新版，打开“不被打断”即可。
