### ISSUE TITLE
有道翻译问题

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#624]

**Comment by HIllya51** [comment]
测试不存在问题。你把你的userconfig打包给我看看
<img width="907" alt="屏幕截图 2024-04-05 004218" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/6b757704-8eba-446f-ad91-3170000f87cc">

**Comment by dnadash** [comment]
> 测试不存在问题。你把你的userconfig打包给我看看 <img alt="屏幕截图 2024-04-05 004218" width="907" src="https://private-user-images.githubusercontent.com/101191390/319686432-6b757704-8eba-446f-ad91-3170000f87cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTA2ODQsIm5iZiI6MTcxMjI1MDM4NCwicGF0aCI6Ii8xMDExOTEzOTAvMzE5Njg2NDMyLTZiNzU3NzA0LThlYmEtNDQ2Zi1hZDkxLTMxNzAwMDBmODdjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxNzA2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2JhZTE3OTY3OGQxNWI3ODQ1MmFjMWQ2Y2ZkODkyZWUxMjdlNzc1OTQ5ZWUzZDRmNmNmZDZiODMyNTIwMTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NlCDWh6d405lkeGQX4gF4Jn9T0Qz9uwX-sgzgeSXksM">

https://gofile.io/d/wl7qoh

**Comment by dnadash** [comment]
> > 测试不存在问题。你把你的userconfig打包给我看看 <img alt="屏幕截图 2024-04-05 004218" width="907" src="https://private-user-images.githubusercontent.com/101191390/319686432-6b757704-8eba-446f-ad91-3170000f87cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTA2ODQsIm5iZiI6MTcxMjI1MDM4NCwicGF0aCI6Ii8xMDExOTEzOTAvMzE5Njg2NDMyLTZiNzU3NzA0LThlYmEtNDQ2Zi1hZDkxLTMxNzAwMDBmODdjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxNzA2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2JhZTE3OTY3OGQxNWI3ODQ1MmFjMWQ2Y2ZkODkyZWUxMjdlNzc1OTQ5ZWUzZDRmNmNmZDZiODMyNTIwMTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NlCDWh6d405lkeGQX4gF4Jn9T0Qz9uwX-sgzgeSXksM">
> 
> https://gofile.io/d/wl7qoh

刚刚又看了下，不止是有道，百度和彩云也会时不时变成数字和括号

**Comment by HIllya51** [comment]
额 我测的没问题
<img width="1083" alt="屏幕截图 2024-04-05 011455" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/27a0e12f-dfca-4857-b71a-ef66ead77c38">
<img width="1148" alt="屏幕截图 2024-04-05 011403" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/728a9bde-5fdf-4c69-933c-606de776904a">

**Comment by HIllya51** [comment]
不过就算有问题，这个问题也是无法解决的问题，原因参考 https://github.com/HIllya51/LunaTranslator/issues/550
之前更糟糕，用的是vnr的ZXBZ/ZXCZ这种莫名其妙的东西，现在换成了{0}，{1}，比之前好一点但肯定不会100%没问题，但就算有问题也没办法。

**Comment by dnadash** [comment]
> 不过就算有问题，这个问题也是无法解决的问题，原因参考 #550 之前更糟糕，用的是vnr的ZXBZ/ZXCZ这种莫名其妙的东西，现在换成了{0}，{1}，比之前好一点但肯定不会100%没问题，但就算有问题也没办法。

zxbz这些以前也是遇到过，但情况非常少，今天遇到{0}这些非常频繁，这种没添加专有名词的也会出问题
![1](https://github.com/HIllya51/LunaTranslator/assets/137600501/83d8fd32-28b5-42fb-88f6-5abedf6f0578)
