### ISSUE TITLE
The issue occurs when using the Russian language.

### ISSUE THREAD

**Issue by TildaRu** [HIllya51/LunaTranslator#626]
In version 2.42.0, when using the Russian language, the "Register for online translation" tab disappears. Please fix it.
English -
![image](https://github.com/HIllya51/LunaTranslator/assets/107315419/29265f6b-3b69-4622-8867-db0c07448fbe)

Russian - 
![image](https://github.com/HIllya51/LunaTranslator/assets/107315419/97dd8a20-f668-4c84-8c0e-c7578e637bca)

**Comment by HIllya51** [comment]
fixed
