### ISSUE TITLE
选取OCR范围 功能失效

### ISSUE THREAD

**Issue by EvanTheGuy** [HIllya51/LunaTranslator#628]
版本2.42.0
ocr本身没有问题，但选取范围的功能失效。
如：
选取ocr范围 视窗按钮消失
选取ocr范围 快捷键失效

**Comment by HIllya51** [comment]
？哪失效了

**Comment by HIllya51** [comment]
莫名其妙，如果选取范围的功能失效，那你怎么知道ocr本身没有问题的

**Comment by EvanTheGuy** [comment]
介面設定的視窗按鈕設定，"進行一次ocr"可以顯示在工具列中、掃描並且翻譯，但"選取ocr範圍(僅ocr)"不會顯示在列中。
快捷按鍵中，設定"進行一次ocr"可以作用，但"選取ocr範圍"、"選取ocr範圍--立即"沒有反應。

**Comment by EvanTheGuy** [comment]
不好意思，是我的问题，已解决。
