### ISSUE TITLE
游戏hook文本不全

### ISSUE THREAD

**Issue by 431568** [HIllya51/LunaTranslator#631]
鬼畜中出し水泳部这个游戏hook文本不全，添加MisakaHookFinder的特殊码也没用
![QQ图片20240407084956](https://github.com/HIllya51/LunaTranslator/assets/139386734/374409d2-80e7-4457-9ad0-e18716b8e50f)
https://1drv.ms/u/s!Aqukap-4n3uyoD1hZxl-JLQ-BP_o?e=gTL9ip

**Comment by HIllya51** [comment]
哪不全了😅

**Comment by 431568** [comment]
不好意思，刚重新试了下可以了
