### ISSUE TITLE
不再支持yakuyaku了吗

### ISSUE THREAD

**Issue by Tokuda-Harukasora** [HIllya51/LunaTranslator#632]
更新到最新版本之后似乎不再支持yakuyaku翻译了吗？
我用起来感觉这是个效果比较好的本地翻译

**Comment by Tokuda-Harukasora** [comment]
> 如果你是从旧版升级过来的，那么并不会删除对它的支持，除非你删除了你的旧的config和translator/yakuyaku.py。 这个东西效果太烂了，被sakura完爆，速度也差不多（sakura-1b8-qwen2beta-v0.9.1-fp16）

我这破电脑跑不了任何大语言模型，我再看看吧

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/32db3e2433b1acd9e0bb267366d475b00da800eb

如果非要用的话，你把这个yakuyaku.py自己复制到对应目录里面，然后在配置里面加上就行了。但资源我早就删了，如果你也删了的话那没辙。

**Comment by Tokuda-Harukasora** [comment]
我修补了一下确实是能用了，我也在考虑换电脑了，笔记本4060能跑sakura模型吗

**Comment by HIllya51** [comment]
我cpu跑的。。
