### ISSUE TITLE
hook不到文本

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#633]
![1](https://github.com/HIllya51/LunaTranslator/assets/137600501/a0a83e3b-a3cb-4f9e-8723-d130048419a9)
游戏下载，我传了MEGA
https://mega.nz/file/ZDVE2CpK#HhFAtwPSV3AEBU16F9QPZDhUbIBen90Bkn_YG52-mRM

**Comment by HIllya51** [comment]
1+
