### ISSUE TITLE
关于Mecab？

### ISSUE THREAD

**Issue by edr1412** [HIllya51/LunaTranslator#636]
你好，不知道这里能否提个问题，回答完可以关这个issue

外部文件的「Mecab」是不是指的是「词典」呢？
我把 https://clrd.ninjal.ac.jp/unidic/ 这里下载的unidic词典放进去好像也能分词，这个可能版本新一点（2023.02）？体积比你提供的2.1.2大很多，准确度、速度暂时没发现很大区别。
用这个会不会更好？最佳推荐用什么呢？

谢谢

**Comment by HIllya51** [comment]
是词典，mecab运行时已经内置。新的应该好一点吧，不过我没试过

**Comment by edr1412** [comment]
好的。
另外2.1.2好像是2013年发布的，建议大家用新版吧。

**Comment by HIllya51** [comment]
绝大多数情况下够用了，新版体积太大了。之后加个新版的链接进去。

**Comment by edr1412** [comment]
嗯，用起来差不多的。我记得新版链接你已经给了的。
