### ISSUE TITLE
新的版本能hook到文本但是不翻译(英文)

### ISSUE THREAD

**Issue by Z9wind** [HIllya51/LunaTranslator#637]
是有什么新的地方需要设置吗
![fd](https://github.com/HIllya51/LunaTranslator/assets/107527857/ea4394d7-011a-4bcc-bf00-cc21dadb7f45)
![fd2](https://github.com/HIllya51/LunaTranslator/assets/107527857/d19532d2-6e23-44d3-adbd-f72cc05dc255)
-----------------------------
然后在游戏开着的情况下重启luna会直接hook不到游戏文本(以前玩过这个游戏luna里有记录
![fd3](https://github.com/HIllya51/LunaTranslator/assets/107527857/b87c01e4-85f8-415c-8d96-29bf8c7856d7)
-----------------------------
上面两个情况都试过管理员启动, 没有得到解决

**Comment by Z9wind** [comment]
语言翻译那里设置成英译英再改回英译中, 重启两次后能得到解决;;

**Comment by HIllya51** [comment]
后台有僵死的进程 命令行管理员运行taskkill /F /IM LunaTranslator_main.exe
