### ISSUE TITLE
无法使用翻译

### ISSUE THREAD

**Issue by vtalisman1360** [HIllya51/LunaTranslator#638]
如图，无论使用何种翻译方式都会显示一样的错误提示
<img width="901" alt="屏幕截图(16)" src="https://github.com/HIllya51/LunaTranslator/assets/166541226/1c26bec6-dd89-4c32-8fb8-39ca8ba99d3c">

**Comment by HIllya51** [comment]
改了代码忘了更新了。更新可解。
