### ISSUE TITLE
无法HOOK文本

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#640]
![1](https://github.com/HIllya51/LunaTranslator/assets/137600501/052cc366-3bd2-4754-b40a-78cc2cfff79a)
（300MB大小）游戏下载https://mega.nz/file/MPVEVaRY#KjAITinaENZGnKWrow8vJm_5Ru3uSy81X-m3UOyn9Y4

**Comment by HIllya51** [comment]
1+
