### ISSUE TITLE
[Feature Request] 希望“点击单词复制”能直接复制辞书形

### ISSUE THREAD

**Issue by edr1412** [HIllya51/LunaTranslator#641]
你好，感谢你的软件，在游戏同时学习日语很方便。目前我在使用Mecab分词+点击单词复制，然后配合能监听剪切板的词典软件（如GoldenDict、Dictionaries by Monokakido）可以实现直接查词。
但是很多时候单词是有各种活用的，导致词典查不到，需要自己再编辑修改一下。
所以我想能否让“点击单词复制”直接复制辞书形（终止形）呢？或者，给一个这样的选项也不错。Mecab好像是有给出基本形的功能的。
当然“点击单词查词”也可以有这样的功能。
谢谢

**Comment by HIllya51** [comment]
done

**Comment by edr1412** [comment]
多谢
