### ISSUE TITLE
Sugoi translate differently & replace person name with VNDB data didnt work

### ISSUE THREAD

**Issue by Fetch11** [HIllya51/LunaTranslator#642]
Sugoi translator translate is different than the online version, i already make sure that they use same model (v4), how to fix this ?
Oh, also the "replace person name with VNDB data" didnt work out of the box, or it need to edit some config first ? its supposed to convert char name from vndb to romaji before the translation, but it didnt
![sugoi diff](https://github.com/HIllya51/LunaTranslator/assets/69702556/669ee907-983e-4bfa-9c10-f32c83cfc1e7)

**Comment by HIllya51** [comment]
I don't know what model this website using, but I add a new interface in online translator now. Re download the latest version can find it.
"replace person name with VNDB data" need to know the vndb id of the current game, id can be found in game's setting.
<img width="1194" alt="屏幕截图 2024-04-11 123426" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/592e62a6-4b09-4733-b93c-e7cbf691a932">
