### ISSUE TITLE
VNR人工字幕报错

### ISSUE THREAD

**Issue by edr1412** [HIllya51/LunaTranslator#644]
不确定是不是我的理解不对，这个功能是不是可以用VNR的人工字幕来作为翻译文本？
还是我找的字幕有问题？不会用VNR。。。
游戏是サクラノ詩，字幕文件是贴吧上找的这个
[bab61fb3bd98ef1f1538ee47a8a46a26.xml.zip](https://github.com/HIllya51/LunaTranslator/files/14947174/bab61fb3bd98ef1f1538ee47a8a46a26.xml.zip)

打开翻译设置>显示错误信息后，报错KeyError '...'

![Screenshot 2024-04-11 at 22 13 36](https://github.com/HIllya51/LunaTranslator/assets/40953911/ba80b044-08cf-4dc8-9853-339aa787e5aa)

开启「预翻译采用模糊匹配」后，报错 UnboundLocalError: local variable 'savet' referenced before assignment

如果是我放的字幕文件不对的话，麻烦问问怎么找正确的人工字幕呢

**Comment by HIllya51** [comment]
不推荐使用这个东西，这个已经计划移除。

**Comment by edr1412** [comment]
可惜 我觉得人工字幕这个功能还蛮好的。。哈哈

**Comment by HIllya51** [comment]
这个和旁边的json功能等同，且格式乱七八糟，已经没有任何人维护了

**Comment by HIllya51** [comment]
这个东西太老了，基本没人用。
