### ISSUE TITLE
[Feature Request] 能否给“模拟按键Enter”分配一个快捷键

### ISSUE THREAD

**Issue by edr1412** [HIllya51/LunaTranslator#645]
能不能把这个按钮的功能也加到快捷按键里？
![Screenshot](https://github.com/HIllya51/LunaTranslator/assets/40953911/9e89163a-5333-4857-9499-167d32e808d6)

这样除了可以作为模拟enter使用，还可以每次鼠标点到翻译器或者其他app后，也能用一个快捷键就把窗口焦点切回到游戏中，继续用键盘来操作游戏。

**Comment by HIllya51** [comment]
1+
