### ISSUE TITLE
建议Sugoi支持中文

### ISSUE THREAD

**Issue by fmaxyou** [HIllya51/LunaTranslator#646]
发现Sugoi的效果比很多在线翻译都好，但目前只能输出英文，能否输出到中文？
我看[这个网站](https://sugoitranslator.com/)是支持转到中文，但是目前网站的接口有问题，无法访问到
或者就是再套一层英文转中文，感觉效果都会好很多

**Comment by HIllya51** [comment]
本来就支持，是这个网站的接口垃圾

**Comment by fmaxyou** [comment]
> 本来就支持，是这个网站的接口垃圾

怎么设置？默认是英文的

**Comment by fmaxyou** [comment]
离线翻译里的sugoi，不是在线翻译

**Comment by HIllya51** [comment]
离线的你发我这个网站干什么？

**Comment by HIllya51** [comment]
你用什么模型就翻成什么，要什么设置？

**Comment by HIllya51** [comment]
你用什么模型就翻成什么，要什么设置？

**Comment by fmaxyou** [comment]
> 你用什么模型就翻成什么，要什么设置？

好的，多谢，这个离线模型是只支持到英文的
