### ISSUE TITLE
怎麼爆毒啊！？

### ISSUE THREAD

**Issue by love80312** [HIllya51/LunaTranslator#648]
剛剛電腦下載2.45.3 zip解壓，微軟掃毒擋住，我以為我解壓縮軟體中毒了
後用手機下載這個zip放virustotal掃

![Screenshot_2024-04-13-10-19-14-67_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/HIllya51/LunaTranslator/assets/10782728/a55d3b91-bf05-4a3a-ac76-078830f9aa6d)

**Comment by love80312** [comment]
2.41.1版就正常了

**Comment by HIllya51** [comment]
virscan 扫描没有问题
64位 https://www.virscan.org/report/b0c2c848e31020e7b4b7a3ae72f5929df523ee33f58c3facb8585813429fe233
32位 https://www.virscan.org/report/7c608629a4e60a57e8b69b400449aceabafa791d4e153661bcc9d7fbf75c9d6d
我都装了360了，咋可能有问题呢？

**Comment by love80312** [comment]
我也不知道，還是我個人問題，可是2.41.1版就正常了

**Comment by HIllya51** [comment]
我用virscan扫了一下2.41.1 64位 https://www.virscan.org/report/4746b349e4af63b240d4e22d6b16c60b892c884da4d5d44693941a2e7cb03499 是9/47
2.45.3是7/47，变少了。
用你的网站扫2.41.1 https://www.virustotal.com/gui/file/4746b349e4af63b240d4e22d6b16c60b892c884da4d5d44693941a2e7cb03499 是11/62 
扫2.45.3 https://www.virustotal.com/gui/file/b0c2c848e31020e7b4b7a3ae72f5929df523ee33f58c3facb8585813429fe233 是22/62 反而变多了呢。

**Comment by HIllya51** [comment]
没什么意义，加起来比不过360一根儿毛。
