### ISSUE TITLE
How do I use the VNDB name replacer?

### ISSUE THREAD

**Issue by ripdog** [HIllya51/LunaTranslator#649]
Hi there,

I see you added the VNDB name replacer I suggested on reddit - thanks! However, I haven't been able to get it to work.

How does Luna try and find the VN name or VNDB id? As far as I know, Luna only knows the game .exe name, and VNDB doesn't list those. 

The plugin which I referenced simply asked the user to input a list of VNDB ids - perhaps this is a better way?

**Comment by HIllya51** [comment]
![屏幕截图 2024-04-13 223229](https://github.com/HIllya51/LunaTranslator/assets/101191390/a757258e-ce41-4285-89df-b8461a15abc3)

**Comment by HIllya51** [comment]
give me you config.json and savehook_new_1.39.4.json

**Comment by ripdog** [comment]
[config.json](https://github.com/HIllya51/LunaTranslator/files/14967679/config.json)
[savehook_new_1.39.4.json](https://github.com/HIllya51/LunaTranslator/files/14967680/savehook_new_1.39.4.json)

**Comment by HIllya51** [comment]
it seems you are using a old version. Update to latest first.
Then just wait a minute for load datas of vndb.

**Comment by ripdog** [comment]
Oh, I am using the latest. I just haven't quit it yet, so it hasn't saved the files. I've quit now: 

[config.json](https://github.com/HIllya51/LunaTranslator/files/14967697/config.json)
[savehook_new_1.39.4.json](https://github.com/HIllya51/LunaTranslator/files/14967698/savehook_new_1.39.4.json)

**Comment by HIllya51** [comment]
maybe because the japanese name is splited by " " rather than "・". 
I just fixed this problem. re download the latest version and try ?

**Comment by HIllya51** [comment]
I tested it work fine now.
<img width="872" alt="屏幕截图 2024-04-13 225454" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/a8cff4cb-87e9-4fef-b10f-70e388ce1936">

**Comment by ripdog** [comment]
Do you mean the names in game or in VNDB?

Will you push a new version or do I redownload [v2.45.4](https://github.com/HIllya51/LunaTranslator/releases/tag/v2.45.4)?

**Comment by HIllya51** [comment]
v2.45.4

**Comment by HIllya51** [comment]
> Do you mean the names in game or in VNDB?
> 

can't understand.

**Comment by ripdog** [comment]
It's ok, I read the commit, you meant the names in VNDB. I don't recall any VNDB character names being split with "・", splitting on " " is correct.

Thank you for the fix! I can confirm it works now. Your support is amazing!

**Comment by HIllya51** [comment]
actually some is "・" and some is " "
