### ISSUE TITLE
VNR共享辞书读取问题

### ISSUE THREAD

**Issue by Ptilopsis01** [HIllya51/LunaTranslator#65]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/93318731/201994427-581e5b78-af78-42c7-b390-9c7cab789bb4.png">
如图，有时会出现这种似乎是翻译结果被替换了的情况
vnr共享辞书我记得是有区分翻译前和翻译后替换的来着，用vnr没发生过这种情况

**Comment by lnusyaha** [comment]
大佬能不能发下你的版本呢？感觉直接用大佬的版本比较方便。

**Comment by HIllya51** [comment]
我根本不用共享辞书，只有一个很小的版本用来测试写代码，不然干嘛找你要。。。

**Comment by HIllya51** [comment]
> 大佬能不能发下你的版本呢？感觉直接用大佬的版本比较方便。

我根本不用共享辞书，只有一个很小的版本用来测试写代码。。。

**Comment by Ptilopsis01** [comment]
> 有些格式因为我没有注意到所有没有做兼容。我的版本的共享辞书里面不含有你说的这个情况，你的共享辞书能否发我一下看一下我来搞一下。
[gamedic.zip](https://github.com/HIllya51/LunaTranslator/files/10019854/gamedic.zip)

**Comment by HIllya51** [comment]
已支持

**Comment by Ptilopsis01** [comment]
> 已支持

感谢大佬
