### ISSUE TITLE
[Feature Request] 根据词性进行文本处理

### ISSUE THREAD

**Issue by blucca** [HIllya51/LunaTranslator#651]
现在的文本处理只能进行简单字符串替换，能不能添加一个功能，当字符串是名词并且原文内容匹配时才进行替换。这样能更好的匹配文本中的人名而不会误伤其他词汇

**Comment by HIllya51** [comment]
这也太麻烦了。

**Comment by HIllya51** [comment]
而且感觉没什么卵用

**Comment by HIllya51** [comment]
我想起来了 这好像是因为win10还是win11的某个版本开始，加强的安全策略，必须要用户手动激活窗口。不然随便一个窗口都能置顶的话，病毒把自己置顶了怎么办。

**Comment by HIllya51** [comment]
> 顺便 #639 还有问题…

已修

**Comment by HIllya51** [comment]
现在已支持自定义优化方法，你可以直接修改transoptimi/noundict.py或者自己创建自定义方法后把它复制过去。然后自行在其中添加相应的处理。
