### ISSUE TITLE
[Feature Request] Cohere API

### ISSUE THREAD

**Issue by Bionagato** [HIllya51/LunaTranslator#653]
Can you add Cohere API? Command and Command R+ are great models for translating from Japanese to other languages like English, Chinese, and Spanish And they are offering free API. https://docs.cohere.com/reference/about

**Comment by HIllya51** [comment]
it seems same as openai chat format. did you try use it via openai_unofficial interface?

**Comment by HIllya51** [comment]
this api is unavailable in my country. and its documentation is not enough for me to implement it.
so it will be no support unless you give me a working API for me to test.

**Comment by HIllya51** [comment]
ok

**Comment by HIllya51** [comment]
ready
