### ISSUE TITLE
内嵌翻译无法作用

### ISSUE THREAD

**Issue by jyxjyx1234** [HIllya51/LunaTranslator#654]
游戏是exhabit引擎，选择文本时显示了内嵌翻译，但是游戏中没有翻译。
![image](https://github.com/HIllya51/LunaTranslator/assets/86876769/67902261-8fe0-4ea2-b230-1b5fcca66a71)
![image](https://github.com/HIllya51/LunaTranslator/assets/86876769/e4525fcd-228d-4a77-9b95-3cc79fa6d5b9)
![image](https://github.com/HIllya51/LunaTranslator/assets/86876769/03b83e12-4789-4d05-9ad5-b544554d4388)

**Comment by HIllya51** [comment]
没有变化那就是不支持

**Comment by HIllya51** [comment]
你翻译等待时间0能嵌进去个啥？
