### ISSUE TITLE
选择文本时，可以显示操作说明吗？（双击文本让它变成对号）

### ISSUE THREAD

**Issue by xuejianxianzun** [HIllya51/LunaTranslator#657]
我已经把这个软件文件夹添加进杀毒软件的白名单，然后重新解压以确保文件完整。
使用管理员权限运行。
游戏则是使用 Locale Emulator 转区运行。
翻译引擎只选择谷歌v2翻译，并且我的网络代理是没有问题的。

我看到教程上是这么写的：
![image](https://github.com/HIllya51/LunaTranslator/assets/17283977/15a98d47-e76b-40ab-9c7f-3316ac376604)
实际上：
![image](https://github.com/HIllya51/LunaTranslator/assets/17283977/8c712ab3-0ac3-4b0b-807b-30d3d35b8c52)
没有OK按钮。我也没搞明白如何开始翻译。点击“文本处理”的话翻译器会闪退。
我刚注意到一个奇怪的地方，上面的截图右上角有个“内置翻译”，但之后我再尝试的时候右上角却始终没有这个东西。
![image](https://github.com/HIllya51/LunaTranslator/assets/17283977/c624533a-1a1c-4272-be8d-361f39b77782)

**Comment by xuejianxianzun** [comment]
另外，我也不知道如何设置翻译源。
教程上是这样的：
![image](https://github.com/HIllya51/LunaTranslator/assets/17283977/ad8a2e2c-1216-4664-893d-ad20de5c3a21)
实际上：
![image](https://github.com/HIllya51/LunaTranslator/assets/17283977/2403aebc-182b-4a37-b0ef-bd6ddac4e802)
没找到如何选择使用谷歌翻译。

**Comment by xuejianxianzun** [comment]
我之前用的是 MisakaTranslator，现在想用这个试试，但是我反复尝试了半小时连怎么开始翻译都没搞明白，大佬你能把设置或引导流程优化一下吗？

**Comment by xuejianxianzun** [comment]
有一次突然可以了。之前是选择进程，然后弹出选择文本，就一直不会消失，并且也没有开始翻译：
![20240415_032600](https://github.com/HIllya51/LunaTranslator/assets/17283977/d71ae38e-9bbc-4e06-8312-36d80cc478fc)

在一次尝试中，我把游戏和这个翻译器都关闭，然后重新打开就可以了。
![20240415_032630](https://github.com/HIllya51/LunaTranslator/assets/17283977/eafb4832-7329-4fd6-8141-693a823d09de)

然后我把这个翻译器删除，重新解压运行，试图搞懂是怎么回事。并把游戏也关掉。
先运行游戏，再打开翻译器，选择进程，还是和一开始一样无法翻译。
先打开翻译器，再运行游戏，翻译器会在游戏启动后直接显示选择文本窗口。依然无法翻译：
![20240415_032507](https://github.com/HIllya51/LunaTranslator/assets/17283977/742184d1-445a-4fc7-a9ab-3c6eecf53e5b)

我还是没搞懂怎么用这个翻译器。

**Comment by xuejianxianzun** [comment]
我好像明白了，需要在选择的那条文本上双击，让前面变成粉红的对号

**Comment by HIllya51** [comment]
本来就可以单击，单击×或者双击整行。
