### ISSUE TITLE
hook文本问题

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#658]
![1](https://github.com/HIllya51/LunaTranslator/assets/137600501/7f60e5c7-12db-4225-9621-dd47e3885d8c)
![2](https://github.com/HIllya51/LunaTranslator/assets/137600501/76c200cb-9dd8-4b10-9a5c-be24984fe0dc)
文本会中间和末尾多字（标点隔开导致无法去重干净）上面HOOK的几条文本没问题，但不是一句句显示，而是前面所有文本都有
游戏下载（400MB）https://mega.nz/file/0Lki1DpQ#mRQWmxvAzTeHRKIJARAFBkqkSxlXlwvDMGiAsR1Nw44

**Comment by HIllya51** [comment]
你就不能换一条吗？lstrlenw一点问题都没有。

**Comment by dnadash** [comment]
> 你就不能换一条吗？lstrlenw一点问题都没有。
lstrlenw前面没问题，往后C一点（我这个地方以后）就有问题了
