### ISSUE TITLE
使用软件内方式启动游戏后部分外部快捷键无法正常使用

### ISSUE THREAD

**Issue by Ptilopsis01** [HIllya51/LunaTranslator#66]
如题，软件内启动游戏后，如print screen键和本地magpie启动快捷键alt+F11键无法正常触发，不清楚是不是还有更多

**Comment by Ptilopsis01** [comment]
> 试了没问题啊 你设置的快捷键冲突了吧？而且软件内内置了一个修改版的magpie，可以在全屏模式下操作软件而不退出全屏。

翻译器我只设置了一个全屏的快捷键，如果是先启动游戏再启动翻译器不会有问题，但是先启动翻译器再用翻译器内置的方式启动游戏就会出现prtscr键无法使用的情况

**Comment by wwchy** [comment]
。。。要不你说一下是哪个游戏？我测试了好几个游戏一点问题没有。

**Comment by HIllya51** [comment]
。。。要不你说一下是哪个游戏？我测试了好几个游戏一点问题没有。

**Comment by HIllya51** [comment]
青春fragile？刚好最近我也打算打，试了一下，一点问题没有。。

**Comment by HIllya51** [comment]
我在两台电脑上都试没问题。。。感觉这个bug完全没道理啊，我完全想不通怎么才能做到挤占printscreen键。。😂
