### ISSUE TITLE
文本栏能否改为不可拖动

### ISSUE THREAD

**Issue by edr1412** [HIllya51/LunaTranslator#660]
我觉得按住工具栏可以拖动窗口是合理的，但下面显示游戏文本和翻译的位置，能否加个选项让用户决定能否拖动呢？目前未开启「可选取模式」时，是可以在这个区域拖动窗口的。
主要是如果从这里可以拖动的话，在频繁使用“点击单词查词”“点击单词复制”功能时就容易误触发为拖动窗口，必须要小心控制鼠标不移动，有点影响体验。

**Comment by HIllya51** [comment]
改成不会拖动了。
