### ISSUE TITLE
> 你就不能换一条吗？lstrlenw一点问题都没有。

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#662]
> 你就不能换一条吗？lstrlenw一点问题都没有。
lstrlenw前面没问题，往后C一点（我这个地方以后）就有问题了

_Originally posted by @dnadash in https://github.com/HIllya51/LunaTranslator/issues/658#issuecomment-2055565271_

**Comment by HIllya51** [comment]
给我个存档

**Comment by dnadash** [comment]
> 给我个有问题的存档
录了个1分钟不到的视频，感觉挺直观的https://gofile.io/d/JiZzuA

**Comment by dnadash** [comment]
> 给我个存档 不然我怎么测试新加的hook对不对
得让游戏显示一段时间文本，它才会有堆积问题，直接给你我的档也得点一段时间文本
视频例：https://gofile.io/d/mn6nWX
存档位置：
![1](https://github.com/HIllya51/LunaTranslator/assets/137600501/84846317-30d2-464e-b205-16bee3eddd81)

存档：https://mega.nz/file/8fNnjaSa#TmQE_P1b8fMoOdHrAGGjpvQtH7y0wpBDMqX3wKHeyEE

**Comment by dnadash** [comment]
> > 给我个存档 不然我怎么测试新加的hook对不对
> > 得让游戏显示一段时间文本，它才会有堆积问题，直接给你我的档也得点一段时间文本
> >比如这个档就是上个视频文本堆积的地方，重启游戏读档它没问题了，再显示一会文本就又有问题。视频例：https://gofile.io/d/mn6nWX
> > 存档位置：
> > ![1](https://private-user-images.githubusercontent.com/137600501/322415352-84846317-30d2-464e-b205-16bee3eddd81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzE0MjcsIm5iZiI6MTcxMzE3MTEyNywicGF0aCI6Ii8xMzc2MDA1MDEvMzIyNDE1MzUyLTg0ODQ2MzE3LTMwZDItNDY0ZS1iMjA1LTE2YmVlM2VkZGQ4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwODUyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGI1MDMwODAxZmQ1Y2E2MGFhMGFhOGFjY2RkNjk5ZjU3OGU1YzM2ZGQ0YjFhZTE5YmE4ZGYzNmM5MmM5YTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rAasnnUl9-Yl6LaiiSR4s79RwXArNTpJgMoWyIc79YY)
> 
> 存档：https://mega.nz/file/8fNnjaSa#TmQE_P1b8fMoOdHrAGGjpvQtH7y0wpBDMqX3wKHeyEE

**Comment by HIllya51** [comment]
done
