### ISSUE TITLE
这个改动都是一个月以前的了，如果今天才遇到这个问题，可能是翻译源在你所在区域的服务器节点抽风了吧，甚至我拿你的设置测试都没有任何问题。

### ISSUE THREAD

**Issue by dnadash** [HIllya51/LunaTranslator#667]
这个改动都是一个月以前的了，如果今天才遇到这个问题，可能是翻译源在你所在区域的服务器节点抽风了吧，甚至我拿你的设置测试都没有任何问题。

_Originally posted by @HIllya51 in https://github.com/HIllya51/LunaTranslator/issues/624#issuecomment-2037792652_

**Comment by dnadash** [comment]
电脑里留了老版本的LUNA，已测试（2.33）完全不会遇到专有名词替换成ZXBZ这类情况（翻译体验和以前一样，玩几个小时能碰见ZXBZ这种都算运气不好了），新版本替换数字非常非常频繁，严重影响体验。露娜佬能不能把新版翻译器的专有名词改回老版本的ZXBZ那样，单独传我一份，不需要后续和Releases的同步更新，我自用。

**Comment by HIllya51** [comment]
我把默认的改回ZXBZ这个东西了
我也不知道到底怎么做才好，我不是很常用这个东西。
不过目前有几种方案，分别是ZXBZ，{1}，以及或者直接把结果在翻以前直接替换回去（好像英语的喜欢这么干）。
在transoptimi/noundict.py里面的第十行，我用___idx=1（或者2、3）分别控制可以选用3种方法中的一个，你或许可以改一改试试哪种方法效果最好告诉我一下
