### ISSUE TITLE
带人名的重复文本无法过滤

### ISSUE THREAD

**Issue by hzl2010** [HIllya51/LunaTranslator#67]
把去重的选项都勾了，然而带人名的文本依然无法去重。

![image](https://user-images.githubusercontent.com/65847388/202201463-e1e7dd6b-c0b5-433f-9c37-bc63a0c1fa47.png)

**Comment by HIllya51** [comment]
设置重复次数为5。

**Comment by hzl2010** [comment]
> 好了，是每个游戏都要手动调节吗？还是说设置完，这个游戏下次就不用调节了？



> 设置重复次数为5。

**Comment by wwchy** [comment]
有的游戏需要手动设置。嗯。
