### ISSUE TITLE
专有名词建议

### ISSUE THREAD

**Issue by k2250761** [HIllya51/LunaTranslator#670]
很多引擎在翻译带专有名词的句子时会出现类似(ZXED)之类的字母
我测试了一下其实引擎是把这字母当成一个词组在翻译，只要把这些字母换回替换的文本，应该就能有很好的体验

例如：りんご=苹果

翻译出来可能是：这是ZXED。
这时候把ZXED换回苹果，应该能有很好的体验

**Comment by HIllya51** [comment]
没看懂你想表达什么意思

**Comment by k2250761** [comment]
比如在名词替换添加了：りんご=苹果

这句话：これはりんご。
因为bug就有可能翻译成：这是ZXED。

这时候把ZXED调回苹果。不就是正确的翻译了吗

**Comment by HIllya51** [comment]
翻译api是不支持这种东西的，只能硬往上面加能咋办。错成ZXED我也没办法去知道要对应是什么啊。
