### ISSUE TITLE
能否实现任务栏不显示软件窗口但是游戏中仍能看见翻译的功能

### ISSUE THREAD

**Issue by sekurodesu** [HIllya51/LunaTranslator#672]
![无标题](https://github.com/HIllya51/LunaTranslator/assets/51750095/0e01ed16-3868-4e61-a22e-594c456b3606)
![无标题1](https://github.com/HIllya51/LunaTranslator/assets/51750095/ad443223-0d02-4f6c-b88c-4b2005a4d1c2)
如图，想把任务栏这个窗口去掉，但是保留翻译部分。
现在点击翻译窗口的缩小按钮只会把翻译窗口去掉，任务栏仍旧存在；而点击关闭按钮，整个程序就被退出了。

**Comment by HIllya51** [comment]
显示设置->任务栏中显示
