### ISSUE TITLE
TTS for Narration only

### ISSUE THREAD

**Issue by carycary246** [HIllya51/LunaTranslator#673]
Is there an option like VNR where the TTS will only automatically read the narration? I don't need it to read the voiced lines.

**Comment by HIllya51** [comment]
The format of the Narration sentence differs greatly from voiced lines. You can filter the voiced lines before read.
<img width="937" alt="屏幕截图 2024-04-19 101844" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/ff9085db-3fc5-4bcc-835c-a75b45242b3f">

**Comment by carycary246** [comment]
Do you have an example of how that works? I don't understand how I can use that function to stop it from reading voiced lines.

**Comment by qwer666qwer** [comment]
> Do you have an example of how that works? I don't understand how I can use that function to stop it from reading voiced lines.

Perhaps you could add a regex to transform text with Japanese parentheses into blank lines.
![Snipaste_2024-04-20_01-43-42](https://github.com/HIllya51/LunaTranslator/assets/79153400/ea5c7276-9639-4fc1-b81f-632010428ad3)
regex: ^.*[「」].*$
