### ISSUE TITLE
还是HOOK不到文本

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaTranslator#676]
fixed

_Originally posted by @HIllya51 in https://github.com/HIllya51/LunaTranslator/issues/675#issuecomment-2067543584_

**Comment by qscasdasd** [comment]
![3](https://github.com/HIllya51/LunaTranslator/assets/167575533/05fba100-eac4-48af-875b-12d0064ee748)
不用特殊码没HOOK，用特殊码游戏还是崩了

**Comment by HIllya51** [comment]
给我硬盘版

**Comment by qscasdasd** [comment]
> 给我硬盘版

给硬盘版你不一定能打开，有工具能让16位安装程序运行，win10上玩
我录的视频安装过程：https://gofile.io/d/WEy8TY
工具：https://mega.nz/file/IbkhwSga#_Ssl06e4JP5cFNWgYXKCg1szzSrg6r2qdFNH9mtHRkk

**Comment by HIllya51** [comment]
给我硬盘版。

**Comment by HIllya51** [comment]
我当然是试过了才给你要的。我前面拿32位虚拟机装了复制出来弄得，弄完就删了

**Comment by qscasdasd** [comment]
> 我当然是试过了才给你要的。我前面拿32位虚拟机装了复制出来弄得，弄完就删了

https://1drv.ms/u/c/3baa305c04c34a19/EUw5PzNBr1xEs0_OQv6Z90gBgZcQBnOlwcfep2nlp5m-TQ?e=NcHHZj

**Comment by HIllya51** [comment]
<img width="1120" alt="屏幕截图 2024-04-21 000853" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/7d50a93d-6c03-4c51-b1fb-dffbcd02fedd">

**Comment by HIllya51** [comment]
没一点问题，不知道为什么你不行

**Comment by qscasdasd** [comment]
> 没一点问题，不知道为什么你不行

知道问题在哪了，文字显示速度不能调到最快“0”，只要不是0就能HOOK到，感谢
