### ISSUE TITLE
大佬，很久没看设置界面了，发现多了很多个东西，有些东西能解释下吗?

### ISSUE THREAD

**Issue by wycstc353** [HIllya51/LunaTranslator#677]
大佬，很久没看设置界面了，发现多了很多个东西，有些东西能解释下吗?
比如那个YAPI注入是啥，使用和不使用有啥区别呢？
还有那个翻译设置里的均衡负载是干啥的

**Comment by HIllya51** [comment]
不用管，默认就行

**Comment by wycstc353** [comment]
> 不用管，默认就行

 对了，还有我现在玩了好几个游戏都是一个游戏会用到多个hook，这也是正常的吗？经常一个游戏选项选了之后hook就变成另外一个了

**Comment by HIllya51** [comment]
正常
