### ISSUE TITLE
文本预处理-正则表达式：无法处理换行符

### ISSUE THREAD

**Issue by edr1412** [HIllya51/LunaTranslator#678]
如图，预览中可以处理，但主窗口中仍然没有处理掉
![Screenshot](https://github.com/HIllya51/LunaTranslator/assets/40953911/e40ce5ec-9580-4f89-b77f-665b778de1ae)

测试用例：

<table>
<tr>
 <td>原文
 <td>替换为
<tr>
 <td>」\n(.*\n)*
 <td>
<tr>
 <td>^「
 <td>
</table>

```
「文本
文本」
ゴミ
ゴミ
ゴミ
```

**Comment by HIllya51** [comment]
\r\n

**Comment by edr1412** [comment]
好吧可以 但\r\n的话预览窗口又不对了

**Comment by HIllya51** [comment]
qt的问题，他自动把clrf给改了
