### ISSUE TITLE
Duplicate Lines On Luna Hook Do i need to this Check mark this 3 Remove Duplicate Lines?

### ISSUE THREAD

**Issue by Machinamochi** [HIllya51/LunaTranslator#679]
![Capture2](https://github.com/HIllya51/LunaTranslator/assets/167679284/71773a36-301e-491f-8870-f3b98acc5288)

Am i Doing Right ?

**Comment by HIllya51** [comment]
can't understand your meaning. pls describe more clearly.

**Comment by Machinamochi** [comment]
the word on the left Lines is the vn game i play  the proble is the word is double like AABBCCDD i need to change it to normal like  ABCD 
so to fix it You need to check mark 
![Capture2](https://github.com/HIllya51/LunaTranslator/assets/167679284/82384e65-248a-4bd0-bf10-7d3e1611a9b4)
remove duplicate lines 
i dont understand the meaning you put this can you explain it clearly ? i just casually checkmark all three of them

**Comment by Machinamochi** [comment]
To put it simply 
can you explain when should i use this ?

![Capture2](https://github.com/HIllya51/LunaTranslator/assets/167679284/b1e3f21c-bf90-404d-817c-7ba18cd333ab)

i have some vn game that use luna Translator but the hook it appear are mostly word like this 
違違ううんんだだ、、そそううじじゃゃなないい

i need to change it to normal like this
違うんだ、、そうじゃない

how to do  it ?

**Comment by HIllya51** [comment]
<img width="527" alt="屏幕截图 2024-04-21 184843" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/33b6ef1b-4ee7-4797-8c67-d4a02b687835">

**Comment by Machinamochi** [comment]
ahh i understand thankz for the help 
btw do you have paypal email ? i want to donate  with paypal transfer  cannot donate in patreon cause it need credit card

**Comment by HIllya51** [comment]
1173718158@qq.com

**Comment by Machinamochi** [comment]
Already send it check your PayPal account thanks

**Comment by HIllya51** [comment]
Thanks for your support~
