### ISSUE TITLE
您好，请问方便与您取得进一步联系吗？

### ISSUE THREAD

**Issue by C4a15Wh** [HIllya51/LunaTranslator#68]
您好，我在贴吧上看到了你的翻译器，实际体验了一下感觉非常不错！我们也在做翻译器的开发，很想和你沟通交流一下，不知道是否方便
您可通过下列地址联系到我们: 
邮箱: contact#stariver.org
QQ: 3039504176

**Comment by HIllya51** [comment]
我很久不使用qq了。。。有需要的话在这里交流就可以了。

**Comment by C4a15Wh** [comment]
您不方便用QQ的话，微信也是可以的
我的微信号: C4a15WhRC2
我们有一些事情需要与您私下商议，给您带来了不便，我们深感歉意

**Comment by HIllya51** [comment]
我的邮箱是1871535768@qq.com

**Comment by HIllya51** [comment]
我的邮箱是1871535768@qq.com
