### ISSUE TITLE
Sogou translate

### ISSUE THREAD

**Issue by Partridgemk1532** [HIllya51/LunaTranslator#680]
Hello i use Sogou translate but this happens
![Bug](https://github.com/HIllya51/LunaTranslator/assets/167683603/0b981344-ecd5-4dcc-bc4f-aefbf4d71502)

**Comment by HIllya51** [comment]
It has been depracated because the website usually crash.

<img width="1142" alt="屏幕截图 2024-04-21 190800" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/1eb7c58e-7e9b-492e-a527-b14e148f8501">
