### ISSUE TITLE
使用内置magpie让游戏全屏时点击查词，指针无法移进弹出来的查词窗口

### ISSUE THREAD

**Issue by cclcc1** [HIllya51/LunaTranslator#681]
系统：win11
显示配置里的magpie的设置为初始状态。

详细情况如录屏所示（黄色那个指针是录屏软件添加的，实际可见的指针是底部那个，怎么也移不进查词窗口）。

然后我试着勾选了一下调试模式，发现查词接口可以正常移进去了，但是全屏效果异常，如截图。

https://github.com/HIllya51/LunaTranslator/assets/160860434/36daaac5-018f-4044-ba24-05be4ef83a5b

![スクリーンショット 2024-04-21 215140](https://github.com/HIllya51/LunaTranslator/assets/160860434/4295a70a-e2c4-4f6d-976c-823382fe64e3)

**Comment by HIllya51** [comment]
这是magpie的问题，它会隐藏鼠标指针，你看到的鼠标指针不是真实指针，是它画出来的，所以这里没有办法解决。

**Comment by Blinue** [comment]
这个错误已经修复，谢谢反馈！
