### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by EruOia** [HIllya51/LunaTranslator#682]
when translating, this appears

阿里_v2 Exception {"rgv587_flag": "sm", "url": "/translationopenseviceapp/trans/Translate TextAddAlignment.do/
tmd /punish?
x5secdata=xd476fd4c6c266465f00cb48a95f419e0b437e47648f79f7bc171371980482025037794a-361759657abaz c2aaa_bx_translate.alibaba.com%3A443%2Ftranslationopenseviceapp%2Ftrans%2FTranslate TextAddAlignment.d o&x5step=2"}

what to do?

**Comment by HIllya51** [comment]
this api is invalid now. please use other apis

**Comment by EruOia** [comment]
Tell me how to do it please
