### ISSUE TITLE
Cannot Hook this game with luna textractor https://vndb.org/v24351

### ISSUE THREAD

**Issue by Machinamochi** [HIllya51/LunaTranslator#685]
It seems when i try to hook this game with luna translator
Luna translatorr Forced Closed it self
can you please check ?
i have the  game if you want it

**Comment by Machinamochi** [comment]
https://mega.nz/folder/PaRWHDzC#L7CjDL36MSe8x1jbB5AFFw

How about MEGA ?

**Comment by HIllya51** [comment]
:)
<img width="604" alt="屏幕截图 2024-04-22 233034" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/73342e6a-c200-4eac-bc47-04e14bb481ff">

**Comment by HIllya51** [comment]
Fortunately, I found a valid torrent

**Comment by HIllya51** [comment]
> i can make a google link but it takes time to make it


I say I found a valid torrent.

**Comment by Machinamochi** [comment]
ahh ok i am just gonna wait for your update thanks

**Comment by Machinamochi** [comment]
ahh it seems i input wrong attachment  crack 
i can properly hook it know 
thanks for the help

**Comment by HIllya51** [comment]
Haha. OK~
