### ISSUE TITLE
关于使用VNR共享辞书

### ISSUE THREAD

**Issue by k2250761** [HIllya51/LunaTranslator#686]
### Question 问题

![tmpE6F7](https://github.com/HIllya51/LunaTranslator/assets/61865659/78cd9c51-d28d-40d5-9907-7ff482624b45)
问下这个使用共享辞书，为什么加载了，没有效果

**Comment by HIllya51** [comment]
文件给我

**Comment by k2250761** [comment]
[gamedic (1).zip](https://github.com/HIllya51/LunaTranslator/files/15104522/gamedic.1.zip)

**Comment by HIllya51** [comment]
已修复
