### ISSUE TITLE
大佬以后是否会对竖行文字进行从右往左读的阅读顺序的优化？日文游戏基本都是从右往左的，目前竖行识别是从左往右

### ISSUE THREAD

**Issue by Z9wind** [HIllya51/LunaTranslator#688]
### Expected behavior 预期的功能

实现竖行文字从右往左的识别

**Comment by HIllya51** [comment]
不会。为什么不用hook？用ocr不是找罪受吗？

**Comment by Z9wind** [comment]
好的谢谢回复，因为是PSV的采集投屏...

**Comment by HIllya51** [comment]
好吧。不过psv如果用vita3k模拟器是可以hook的，不过需要针对游戏特化
如有需要， https://github.com/HIllya51/LunaHook/issues/new?assignees=&labels=enhancement&projects=&template=01_game_request.yaml

**Comment by HIllya51** [comment]
而且ocr模型本地是用的paddleocr模型，在线是api，都基本没有优化的空间。

**Comment by Z9wind** [comment]
遥远的时空中3, 很古早的乙游() 没啥官中的可能(悲

**Comment by HIllya51** [comment]
贴吧里搜了点图试了试，自带的内置ocr完全不管用，不过用windowOCR效果感觉还是可以的。如果效果不好也可以尝试进行预处理。

![屏幕截图 2024-04-26 001154](https://github.com/HIllya51/LunaTranslator/assets/101191390/09f676ed-a611-4953-b94d-6a8f9be87878)
