### ISSUE TITLE
部分游戏会自动输出文本到剪贴板，如果不使用相关hook，能否停止输出

### ISSUE THREAD

**Issue by shinslashisuka** [HIllya51/LunaTranslator#689]
### Expected behavior 预期的功能

![捕获](https://github.com/HIllya51/LunaTranslator/assets/167951765/2520c2f4-febd-4347-8c6b-e3ada36f78ee)
![微信图片_20240426230159](https://github.com/HIllya51/LunaTranslator/assets/167951765/e9b44371-5169-4765-bb95-43dfc1ca9db1)

类似上图，不管选择哪个hook，都会输出文本到剪贴板。
因为经常使用win+v历史剪贴板功能，会造成不便。能否手动选择其他hook后停止输出文本

**Comment by HIllya51** [comment]
更新提取器之后，在游戏exe目录里创建一个disable.clipboard文件
