### ISSUE TITLE
“显示历史翻译”的快捷键配置可否改成“显示/隐藏历史翻译”

### ISSUE THREAD

**Issue by 2-3-5-7** [HIllya51/LunaTranslator#69]
就像其它快捷键有显示/隐藏窗口一样，“显示历史翻译”可否变成一个开关，“显示/隐藏历史翻译”？
不过这样工具栏的按钮也要改成开关指示的样式，像“显示/隐藏原文”按钮一样，不知道好不好改。

**Comment by HIllya51** [comment]
已修正。不过按钮没改。

**Comment by 2-3-5-7** [comment]
谢谢大佬！
