### ISSUE TITLE
老版本renpy游戏保存以后，从“打开保存的游戏“界面打开会找不到hook

### ISSUE THREAD

**Issue by shinslashisuka** [HIllya51/LunaTranslator#690]
### Version 程序版本

v2.45.14

### Reproduction steps 复现步骤

例如这个renpy 7.3.5游戏：https://drive.google.com/file/d/1mEmaPAqvpNXRYnuuGYcUjnndwT7x5_Sd/view?usp=sharing
首次hook保存后，从“打开保存的游戏“界面启动游戏会找不到正确hook，
如果从游戏文件夹根目录exe启动游戏，则可以正确hook

**Comment by HIllya51** [comment]
已修，更新提取器
