### ISSUE TITLE
整合 Python 阿拉伯语重塑器以改进游戏中的阿拉伯文本支持

### ISSUE THREAD

**Issue by DiNaSoR** [HIllya51/LunaTranslator#691]
### Expected behavior 预期的功能

**评论:**
您好，

我一直在探索 LunaTranslator 工具，并对其增强游戏翻译体验的广泛功能表示赞赏。我有一个建议，可能会改善阿拉伯语用户的功能。

**问题描述:**
许多游戏不支持阿拉伯文本原生显示，通常会以孤立形式（单个字符）显示阿拉伯文字，而没有正确的从右到左的文本方向和字符重塑。这导致了文本显示分散且难以阅读，影响了讲阿拉伯语的玩家的游戏体验。

**功能建议:**
我建议在 LunaTranslator 中整合 [Python 阿拉伯语重塑器](https://github.com/mpcabd/python-arabic-reshaper) 库。该库通过转换孤立的阿拉伯字符为其正确的上下文形式，并确保正确的从右到左文本方向，重构阿拉伯句子以用于不支持阿拉伯脚本的应用程序。

**工作原理:**
Python 阿拉伯语重塑器通过将文本中的每个字符转换为其在词中的正确形式（初始、中间、末尾或孤立）来工作。对于阿拉伯语这样的脚本来说，这一点至关重要，因为字母的形状会根据其在词中的上下文而改变。重塑字符后，应通过双向算法（如 python-bidi）处理文本，以确保它从右到左阅读。

**实施建议:**
1. **文本获取：** 将此重塑过程整合到 LunaTranslator 的现有文本获取管道中，文本通过 OCR 或钩子提取。
2. **重塑过程：** 一旦获取文本，在将其发送到翻译引擎之前，应用重塑：
   - 使用 `arabic_reshaper.reshape(text)` 转换文本。
   - 使用 `bidi.algorithm.get_display(reshaped_text)` 确保正确的方向。
3. **翻译和显示：** 重塑和重新定向文本后，可以将其传递给翻译引擎，然后在游戏界面中正确显示。

**好处:**
- 允许讲阿拉伯语的玩家用正确格式的文本完全享受他们的母语游戏。
- 提高 LunaTranslator 对不支持阿拉伯语的游戏的可用性。

我相信这个功能将是 LunaTranslator 的一个宝贵补充，显著增强它对阿拉伯语区域用户的吸引力和功能性。

感谢您考虑这一增强功能。我期待您对这个建议的看法。

此致，
DiNaSoR
-----------------------------------------------------------------------------------

Request to Integrate Python Arabic Reshaper for Improved Arabic Text Support in Games

Hello,

I've been exploring the LunaTranslator tool and appreciate its extensive capabilities in enhancing game translation experiences. I have a suggestion that could potentially improve its functionality for Arabic-speaking users.

**Problem:**
Many games do not natively support Arabic script, often displaying Arabic text in isolated forms (individual characters), without the proper right-to-left orientation and character reshaping. This results in a disjointed and unreadable text display which impacts gameplay for Arabic-speaking players.

**Suggested Feature:**
I propose integrating the [Python Arabic Reshaper](https://github.com/mpcabd/python-arabic-reshaper) library into LunaTranslator. This library reconstructs Arabic sentences to be used in applications that do not support Arabic script by transforming isolated Arabic characters into their correct contextual forms and ensuring proper right-to-left text orientation.

**How It Works:**
The Python Arabic Reshaper works by converting each character in the text into its correct form based on its position in a word (initial, medial, final, or isolated). This is crucial for scripts like Arabic, where the shape of the letter changes depending on its context in the word. After reshaping the characters, the text should be processed through a bidirectional algorithm (such as python-bidi) to ensure it reads from right to left.

**Implementation Suggestion:**
1. **Text Fetching:** Integrate this reshaping process into the existing text fetching pipeline in LunaTranslator, where text is extracted via OCR or hooks.
2. **Reshaping Process:** Once the text is fetched and before it is sent to the translation engines, apply the reshaping:
   - Use `arabic_reshaper.reshape(text)` to transform the text.
   - Use `bidi.algorithm.get_display(reshaped_text)` to ensure proper orientation.
3. **Translation and Display:** After reshaping and reorienting the text, it can be passed to the translation engines and subsequently displayed correctly in the game interface.

**Benefits:**
- Allows Arabic-speaking players to fully enjoy games in their native language with properly formatted text.
- Enhances the usability of LunaTranslator for games that lack native Arabic support.

I believe this feature would be a valuable addition to LunaTranslator, significantly enhancing its appeal and functionality for users in Arabic-speaking regions.

Thank you for considering this enhancement. I am looking forward to your thoughts on this suggestion.

Best regards,
DiNaSoR

**Comment by DiNaSoR** [comment]
![image](https://github.com/HIllya51/LunaTranslator/assets/8531014/8681e98f-e038-4cb7-8fda-690768faef21)

**Comment by DiNaSoR** [comment]
Example Correct font but no reshaping for the letters
![image](https://github.com/HIllya51/LunaTranslator/assets/8531014/d53b9710-0929-4082-b876-714c4bb43816)

**Comment by HIllya51** [comment]
看您的意思似乎只需要对提取到的文本和翻译完的文本进行一些简单的文本处理就可以了？
那么其实您可以通过非常简单的操作实现您的目标：
<img width="809" alt="屏幕截图 2024-04-27 001458" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/eea52076-ce8d-4ce3-805a-6f374215f488">

![屏幕截图 2024-04-27 001618](https://github.com/HIllya51/LunaTranslator/assets/101191390/eef40986-4179-4082-be18-ec24cb8afdb2)
只需在process_before和process_after中使用你所说的方法就可以实现你的目标。
因为我不懂阿拉伯语，所以很难判断结果是否正确。看您也是应该会编程的，应该可以自行实现这个功能。当您实现了这个功能后，届时我可以帮您把这个功能添加到内置中，或者由您进行pr。

————————
It seems that you only need to perform some simple text processing on the extracted text and the translated text?
You can actually achieve your goal through very simple operations:
<img width="809" alt="屏幕截图 2024-04-27 001458" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/eea52076-ce8d-4ce3-805a-6f374215f488">

![屏幕截图 2024-04-27 001618](https://github.com/HIllya51/LunaTranslator/assets/101191390/eef40986-4179-4082-be18-ec24cb8afdb2)
Just implement process_before and process_after maybe can achieve your goal.
Since I don't understand Arabic, it's hard to determine if the results are correct. It seems that you are also good at programming, so you should be able to implement this function by yourself. After you implement this function, I can help you add this function to the built-in, or you can perform PR.

**Comment by DiNaSoR** [comment]
I add this

```Py
from arabic_reshaper import ArabicReshaper

class Process:
    def __init__(self):
        self.reshaper = ArabicReshaper()

    def process_before(self, text):
        context = {}
        return text, context

    def process_after(self, res, context):
        reshaped_text = self.reshaper.reshape(res)
        return reshaped_text
```

Seems not working

**Comment by HIllya51** [comment]
you should install arabic_reshaper ...

**Comment by HIllya51** [comment]
how do you run this code? if you run it via source code, you should pip install; if you run it via exe, you should pip install it and then copy the site-packages/arabic_reshaper to LunaTranslator/LunaTranslator directory.

**Comment by q8fft2** [comment]
Hooray! I've solved the problem—it's truly amazing. Thank you for your time; without your insights, I wouldn't have reached this solution.
I hope there won't be any problems..
![image](https://github.com/HIllya51/LunaTranslator/assets/34658107/b0de7141-0ed4-4ee3-9ec5-5106a19dc6ae)

**Comment by q8fft2** [comment]
Here what i did for Arabic users:
import arabic_reshaper

class Process:
    def process_before(self, text):
        # إعداد سياق المعالجة إذا لزم الأمر
        context = {}
        # تُرجع النص كما هو مع السياق
        return text, context

    def process_after(self, res, context):
        # إعادة تشكيل النص العربي ليظهر متصلاً بعد المعالجة
        reshaped_text = arabic_reshaper.reshape(res)
        # عكس النص
        reversed_text = ''.join(reversed(reshaped_text))
        # يمكنك هنا إضافة تحويل النص إلى UTF-8 إذا لزم الأمر أو أية معالجات إضافية
        return reversed_text

**Comment by HIllya51** [comment]
> Already installed
> 
> C:\Users\user>pip show arabic_reshaper Name: arabic-reshaper Version: 3.0.0 Summary: Reconstruct Arabic sentences to be used in applications that do not support Arabic Home-page: https://github.com/mpcabd/python-arabic-reshaper/ Author: Abdullah Diab Author-email: [mpcabd@gmail.com](mailto:mpcabd@gmail.com) License: MIT Location: C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages Requires: Required-by:
> 
> C:\Users\user>pip list | findstr /I "arabic-reshaper" arabic-reshaper 3.0.0
> 
> C:\Users\user>
> 
> Using embedded feature with check on Use custom optimization
> 
> ![image](https://private-user-images.githubusercontent.com/8531014/326056868-ce97437e-86d2-42bb-aa9a-14caf5403cfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxOTk5MzUsIm5iZiI6MTcxNDE5OTYzNSwicGF0aCI6Ii84NTMxMDE0LzMyNjA1Njg2OC1jZTk3NDM3ZS04NmQyLTQyYmItYWE5YS0xNGNhZjU0MDNjZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjdUMDYzMzU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzRkZjBkN2JjY2VkZjk4MDMxMGU0OTkwZTRmMWVjZjk4ZDY3MjYwYjk5Nzk5YWU3YzMwZTczNmI0Y2UxOTAyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iHuoWRVbGh2zisBOIvEswBCDa7vNwk3q3CEw2J0ZK08)
> 
> ```python
> from arabic_reshaper import ArabicReshaper
> from arabic_reshaper.config import DEFAULT_CONFIG
> 
> class Process:
>     def __init__(self):
>         config = DEFAULT_CONFIG.copy()
>         config['delete_harakat'] = False  # You can modify other settings as needed
>         self.reshaper = ArabicReshaper(config)
> 
>     def process_before(self, text):
>         context = {}
>         return text, context
> 
>     def process_after(self, res, context):
>         reshaped_text = self.reshaper.reshape(res)
>         return reshaped_text
> ```

I don't know why it not work. I recommand you to run it via source code first because it can show more error log.

**Comment by HIllya51** [comment]
ok, if everything works fine, i will include it into program

**Comment by HIllya51** [comment]
> Already installed
> 
> C:\Users\user>pip show arabic_reshaper Name: arabic-reshaper Version: 3.0.0 Summary: Reconstruct Arabic sentences to be used in applications that do not support Arabic Home-page: https://github.com/mpcabd/python-arabic-reshaper/ Author: Abdullah Diab Author-email: [mpcabd@gmail.com](mailto:mpcabd@gmail.com) License: MIT Location: C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages Requires: Required-by:
> 
> C:\Users\user>pip list | findstr /I "arabic-reshaper" arabic-reshaper 3.0.0
> 
> C:\Users\user>
> 
> Using embedded feature with check on Use custom optimization
> 
> ![image](https://private-user-images.githubusercontent.com/8531014/326056868-ce97437e-86d2-42bb-aa9a-14caf5403cfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMDAwNTIsIm5iZiI6MTcxNDE5OTc1MiwicGF0aCI6Ii84NTMxMDE0LzMyNjA1Njg2OC1jZTk3NDM3ZS04NmQyLTQyYmItYWE5YS0xNGNhZjU0MDNjZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjdUMDYzNTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTRlMTNkNDU1MjliZDk2MTUxN2M0M2JmMTA0OTVkZGY0MGYxZDkwMzY2ZjBjMzVlZGZiMmY4YmRkMTRiZWE4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CD2JNxeQsx7XVI72Oh0XaLoObm_6QzFtGnJjGKA-oHs)
> 
> ```python
> from arabic_reshaper import ArabicReshaper
> from arabic_reshaper.config import DEFAULT_CONFIG
> 
> class Process:
>     def __init__(self):
>         config = DEFAULT_CONFIG.copy()
>         config['delete_harakat'] = False  # You can modify other settings as needed
>         self.reshaper = ArabicReshaper(config)
> 
>     def process_before(self, text):
>         context = {}
>         return text, context
> 
>     def process_after(self, res, context):
>         reshaped_text = self.reshaper.reshape(res)
>         return reshaped_text
> ```



> Here what i did for Arabic users:
> 
> ```
> 
> import arabic_reshaper
> 
> class Process:
>     def process_before(self, text):
>         # إعداد سياق المعالجة إذا لزم الأمر
>         context = {}
>         # تُرجع النص كما هو مع السياق
>         return text, context
> 
>     def process_after(self, res, context):
>         # إعادة تشكيل النص العربي ليظهر متصلاً بعد المعالجة
>         reshaped_text = arabic_reshaper.reshape(res)
>         # عكس النص
>         reversed_text = ''.join(reversed(reshaped_text))
>         # يمكنك هنا إضافة تحويل النص إلى UTF-8 إذا لزم الأمر أو أية معالجات إضافية
>         return reversed_text
> ```

Oh, which one of the two codes works better?

**Comment by q8fft2** [comment]
Note: You need to close the program and restart it for the code changes to take effect, otherwise it will not work.

**Comment by q8fft2** [comment]
> > Already installed
> > C:\Users\user>pip show arabic_reshaper Name: arabic-reshaper Version: 3.0.0 Summary: Reconstruct Arabic sentences to be used in applications that do not support Arabic Home-page: https://github.com/mpcabd/python-arabic-reshaper/ Author: Abdullah Diab Author-email: [mpcabd@gmail.com](mailto:mpcabd@gmail.com) License: MIT Location: C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages Requires: Required-by:
> > C:\Users\user>pip list | findstr /I "arabic-reshaper" arabic-reshaper 3.0.0
> > C:\Users\user>
> > Using embedded feature with check on Use custom optimization
> > ![image](https://private-user-images.githubusercontent.com/8531014/326056868-ce97437e-86d2-42bb-aa9a-14caf5403cfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMDAwNTIsIm5iZiI6MTcxNDE5OTc1MiwicGF0aCI6Ii84NTMxMDE0LzMyNjA1Njg2OC1jZTk3NDM3ZS04NmQyLTQyYmItYWE5YS0xNGNhZjU0MDNjZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjdUMDYzNTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTRlMTNkNDU1MjliZDk2MTUxN2M0M2JmMTA0OTVkZGY0MGYxZDkwMzY2ZjBjMzVlZGZiMmY4YmRkMTRiZWE4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CD2JNxeQsx7XVI72Oh0XaLoObm_6QzFtGnJjGKA-oHs)
> > ```python
> > from arabic_reshaper import ArabicReshaper
> > from arabic_reshaper.config import DEFAULT_CONFIG
> > 
> > class Process:
> >     def __init__(self):
> >         config = DEFAULT_CONFIG.copy()
> >         config['delete_harakat'] = False  # You can modify other settings as needed
> >         self.reshaper = ArabicReshaper(config)
> > 
> >     def process_before(self, text):
> >         context = {}
> >         return text, context
> > 
> >     def process_after(self, res, context):
> >         reshaped_text = self.reshaper.reshape(res)
> >         return reshaped_text
> > ```
> 
> > Here what i did for Arabic users:
> > ```
> > 
> > import arabic_reshaper
> > 
> > class Process:
> >     def process_before(self, text):
> >         # إعداد سياق المعالجة إذا لزم الأمر
> >         context = {}
> >         # تُرجع النص كما هو مع السياق
> >         return text, context
> > 
> >     def process_after(self, res, context):
> >         # إعادة تشكيل النص العربي ليظهر متصلاً بعد المعالجة
> >         reshaped_text = arabic_reshaper.reshape(res)
> >         # عكس النص
> >         reversed_text = ''.join(reversed(reshaped_text))
> >         # يمكنك هنا إضافة تحويل النص إلى UTF-8 إذا لزم الأمر أو أية معالجات إضافية
> >         return reversed_text
> > ```
> 
> Oh, which one of the two codes works better?

my last code i put its work for me, i don't use the first code..

**Comment by q8fft2** [comment]
First, you need to download the library.
https://github.com/mpcabd/python-arabic-reshaper/

Then, place the latest code in the myprocess.py file inside the userconfig document.

```
import arabic_reshaper

class Process:
    def process_before(self, text):
        # إعداد سياق المعالجة إذا لزم الأمر
        context = {}
        # تُرجع النص كما هو مع السياق
        return text, context

    def process_after(self, res, context):
        # إعادة تشكيل النص العربي ليظهر متصلاً بعد المعالجة
        reshaped_text = arabic_reshaper.reshape(res)
        # عكس النص
        reversed_text = ''.join(reversed(reshaped_text))
        # يمكنك هنا إضافة تحويل النص إلى UTF-8 إذا لزم الأمر أو أية معالجات إضافية
        return reversed_text
```

![image](https://github.com/HIllya51/LunaTranslator/assets/34658107/b0d0c707-ff83-4f3a-becc-efaed4a60157)

Note: You need to close the program and restart it for the code changes to take effect, otherwise it will not work.

**Comment by DiNaSoR** [comment]
> First, you need to download the library.
> 
> https://github.com/mpcabd/python-arabic-reshaper/
> 
> 
> 
> Then, place the latest code in the myprocess.py file inside the userconfig document.
> 
> 
> 
> ```
> 
> import arabic_reshaper
> 
> 
> 
> class Process:
> 
>     def process_before(self, text):
> 
>         # إعداد سياق المعالجة إذا لزم الأمر
> 
>         context = {}
> 
>         # تُرجع النص كما هو مع السياق
> 
>         return text, context
> 
> 
> 
>     def process_after(self, res, context):
> 
>         # إعادة تشكيل النص العربي ليظهر متصلاً بعد المعالجة
> 
>         reshaped_text = arabic_reshaper.reshape(res)
> 
>         # عكس النص
> 
>         reversed_text = ''.join(reversed(reshaped_text))
> 
>         # يمكنك هنا إضافة تحويل النص إلى UTF-8 إذا لزم الأمر أو أية معالجات إضافية
> 
>         return reversed_text
> 
> ```
> 
> 
> 
> ![image](https://github.com/HIllya51/LunaTranslator/assets/34658107/b0d0c707-ff83-4f3a-becc-efaed4a60157)
> 
> 
> 
> Note: You need to close the program and restart it for the code changes to take effect, otherwise it will not work.
> 
> 

That why its was not working for me i pulled my hair so many times.

First you need to include the arabic reshaper folder inside userconfig..

Second you need to restart the software... 🥲 

I don't know you have to do that or restart it

I will do more experiments and i will let you know which part to include in next release @HIllya51 

I need to do more reshaping configuration for the users.

**Comment by HIllya51** [comment]
now you can only edit [this file](https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/LunaTranslator/transoptimi/arabic_reshaper.py) to implement your idea. if you need a setting window for this process, define a staticmethod called get_setting_window.

**Comment by HIllya51** [comment]
if you change this process's name ,edit [this line](https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/files/defaultconfig/static_data.json#L364)

**Comment by DiNaSoR** [comment]
i tried this one

```py
import arabic_reshaper
from bidi.algorithm import get_display

class Process:
    def __init__(self):
        self.reshaper = arabic_reshaper.ArabicReshaper()

    def process_before(self, text):
        # إعداد سياق المعالجة إذا لزم الأمر
        context = {}
        # تُرجع النص كما هو مع السياق
        return text, context

    def process_after(self, res, context):
        reshaped_text = self.reshaper.reshape(res)
        bidi_text = get_display(reshaped_text)
        return bidi_text

    @staticmethod
    def get_setting_window(parent_window):
        pass
```

but seems its broken here with this line from bidi.algorithm import get_display
Here userconfig
![image](https://github.com/HIllya51/LunaTranslator/assets/8531014/646b2e7e-f834-49eb-845c-681288bb310c)

and LunaTranslator file
![image](https://github.com/HIllya51/LunaTranslator/assets/8531014/b81c0119-c863-408d-a1c0-d769505ac566)

@HIllya51 Need help with this please

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/actions/runs/8861269908
If you don't want to run it via source code, you can download the debug version from actions' Artifacts. It can show more error logs.

**Comment by HIllya51** [comment]
I tested it and found the reason: you should also copy the six.py
