### ISSUE TITLE
Game Forced Closed after Inject Luna translator V49274

### ISSUE THREAD

**Issue by Machinamochi** [HIllya51/LunaTranslator#692]
vndb link/id
https://vndb.org/v49274

Game resource 游戏资源
Link for the Crack https://www.mediafire.com/file/77ljp8rj46l9trz/Shiniyuku_Kishi_kerak.rar/file
Link for the game https://cloud.ryuugames.com/2024/april/v49274

The Game is Forced Close at 10-20 Second game play after i Inject Lunatranslator Inside . Can you please fix it ?

**Comment by HIllya51** [comment]
no error found.

**Comment by Machinamochi** [comment]
Ok No problem thanks for the info
