### ISSUE TITLE
辞书相关功能失效

### ISSUE THREAD

**Issue by JetpackPrime** [HIllya51/LunaTranslator#694]
### Version 程序版本

v2.46

### Related screenshot (optional) 相关截图（可选）

![image](https://github.com/HIllya51/LunaTranslator/assets/118692280/1e99f07f-95d2-421a-924e-66bc33b32f50)

### Reproduction steps 复现步骤

1. 开启了单词查词，但无法点出原有的查词页面
2. 辞书在只选中一种的情况下也会全部展示出来

**Comment by HIllya51** [comment]
内置辞书已被废弃，用mecab试一下

**Comment by JetpackPrime** [comment]
依然无法单击查词

**Comment by HIllya51** [comment]
测试没有任何问题。
![屏幕截图 2024-04-27 223429](https://github.com/HIllya51/LunaTranslator/assets/101191390/e92b9fac-d84f-42fd-a4c3-ceb148d4fee1)

**Comment by HIllya51** [comment]
配置发我

**Comment by JetpackPrime** [comment]
[config.json](https://github.com/HIllya51/LunaTranslator/files/15138499/config.json)

**Comment by HIllya51** [comment]
![屏幕截图 2024-04-27 223914](https://github.com/HIllya51/LunaTranslator/assets/101191390/bf248431-1cae-43a7-8413-c7df5d7980db)

**Comment by JetpackPrime** [comment]
版本兼容问题，重装最新版本已解决
（因为用了一年多了，是从v1.x版本升上来的，可能是历史遗留问题吧）
