### ISSUE TITLE
Bidi lib not working

### ISSUE THREAD

**Issue by DiNaSoR** [HIllya51/LunaTranslator#695]
### Expected behavior 预期的功能

i tried this one

```py
import arabic_reshaper
from bidi.algorithm import get_display

class Process:
    def __init__(self):
        self.reshaper = arabic_reshaper.ArabicReshaper()

    def process_before(self, text):
        # إعداد سياق المعالجة إذا لزم الأمر
        context = {}
        # تُرجع النص كما هو مع السياق
        return text, context

    def process_after(self, res, context):
        reshaped_text = self.reshaper.reshape(res)
        bidi_text = get_display(reshaped_text)
        return bidi_text

    @staticmethod
    def get_setting_window(parent_window):
        pass
```

but seems its broken here with this line from bidi.algorithm import get_display
Here userconfig
![image](https://github.com/HIllya51/LunaTranslator/assets/8531014/646b2e7e-f834-49eb-845c-681288bb310c)

and LunaTranslator file
![image](https://github.com/HIllya51/LunaTranslator/assets/8531014/b81c0119-c863-408d-a1c0-d769505ac566)

@HIllya51 Need help with this please

**Comment by HIllya51** [comment]
see response in https://github.com/HIllya51/LunaTranslator/issues/691
