### ISSUE TITLE
caiyunapp translate 

### ISSUE THREAD

**Issue by allebar** [HIllya51/LunaTranslator#698]
### Version 程序版本

2.46.1

### Related screenshot (optional) 相关截图（可选）

![2123](https://github.com/HIllya51/LunaTranslator/assets/75815491/a70d4f90-f076-4baf-abc0-f3dc50557bd4)

### Reproduction steps 复现步骤

Instead of a translation, just this inscription. Previously, it alternated with the translation, which was one step behind.

**Comment by allebar** [comment]
I'm talking about the inscription "general model", it refers to the translation using caiyunapp

**Comment by HIllya51** [comment]
fixed
