### ISSUE TITLE
Can't select OCR region on right display

### ISSUE THREAD

**Issue by izogfif** [HIllya51/LunaTranslator#699]
### Version 程序版本

v2.46.1

### Reproduction steps 复现步骤

* Connect two or more displays to Windows.
* Enable OCR in "Text input" settings.
* Click the "crop" button on toolbar.
* Move mouse pointer around all displays.

Expected behavior: mouse pointer changes its shape to "cross". When left-clicking and dragging the mouse, a rectangle with black border should appear.

What actually happens: mouse pointer changes its shape to "cross" only when it's on top-left display. It turns back to normal "arrow" pointer when mouse pointer is on the top-right, bottom-left, or bottom-right display.

Is there a check that mouse is within top-left screen's borders? There seems to be a code in `rangeselect.py`, but it's commented for some reason. Was multi-display configuration support removed? Why?
```
        # screens = QDesktopWidget().screenCount()
        # desktop = QDesktopWidget().screenGeometry(0)
        # for i in range(1, screens):
        #     desktop = desktop.united(QDesktopWidget().screenGeometry(i))
        desktop = QApplication.primaryScreen().virtualGeometry()
```

**Comment by izogfif** [comment]
Apparently, it's possible to achieve the desired result via these changes:

In `LunaTranslator\LunaTranslator\gui\rangeselect.py` remove these lines:
```
        self.setWindowFlags(
            Qt.FramelessWindowHint | Qt.Tool
        )  # |Qt.WindowStaysOnTopHint  )
```
After
```
        self.setAttribute(Qt.WA_TranslucentBackground)
```
add these lines:
```
        self.setWindowOpacity(0.6);
        self.setStyleSheet("QWidget{background: #000000}")
```
under `def reset(self):` uncomment these lines:
```
        # screens = QDesktopWidget().screenCount()
        # desktop = QDesktopWidget().screenGeometry(0)
        # for i in range(1, screens):
        #     desktop = desktop.united(QDesktopWidget().screenGeometry(i))
```

and remove this one:
```
        desktop = QApplication.primaryScreen().virtualGeometry()
```

**Comment by HIllya51** [comment]
In my environment, QApplication.primaryScreen().virtualGeometry() 's result is same to the previous 4 lines.
I don't know what's your error, but it works fine for my 2 screens.

**Comment by izogfif** [comment]
@HIllya51 I have 4 displays with 1920 x 1080 resolution on Windows 11 Pro Version 22H2 (OS Build 22621.3155). Displays are arranged like this:
```
4  2
3  1
```
Display 1 is marked as "main display" in Windows settings. Display 4 has top-left corner (-1920; -1080). Display 1 has bottom-right corner (1920; 1080).
When I start the application on display 1 (bottom right), I can't select an area on it. I can only select an area on display 4 (top-left). 
You may be able to reproduce the issue using virtual machine (e.g. Oracle VM VirtualBox) and attaching 4 virtual displays to it.

After I've done the changes I mentioned (removing `setWindowFlags` call and uncommenting those commented out lines with `QDesktopWidget().screenCount()`), I finally got black rectangle covering all 4 displays.

**Comment by HIllya51** [comment]
You can do more test and make a pr to fix it

**Comment by HIllya51** [comment]
Another issue that needs attention is, are the resolutions and dpi scaling of these four screens the same?

**Comment by izogfif** [comment]
Yes, all 4 screens have the same resolution and DPI (96).

**Comment by HIllya51** [comment]
If the screen has different scale rate, your code will not work.

**Comment by HIllya51** [comment]
you can make a pr and i will try it later.

**Comment by HIllya51** [comment]
tested on vbox with two screen and the code is not work.
