### ISSUE TITLE
建议增加翻译器版本相关信息

### ISSUE THREAD

**Issue by mutouchan** [HIllya51/LunaTranslator#7]
现在看最新版是1.5.1，当前没找着在哪里可以看本地是哪个版本的，如果能在设置添加“关于”栏，然后把翻译器版本、git项目地址啥的写出来就好了，望采纳。

**Comment by HIllya51** [comment]
好的好的

**Comment by HIllya51** [comment]
已支持，且可以自动获取最新版本号
