### ISSUE TITLE
请问方便增添竖向文本ocr功能吗？

### ISSUE THREAD

**Issue by kannaginomori** [HIllya51/LunaTranslator#70]
我印象中以前的老版本露娜翻译器有这个功能，但最新版就没有，请问方便加上吗？还有就是方便加上百度ocr的竖向文本识别和高精度ocr这两个功能吗？很抱歉打扰大佬了。

**Comment by HIllya51** [comment]
竖向ocr请使用百度ocr等在线ocr，离线版的ocr竖向识别效果很差，没什么意义。
高精度ocr可以添加。

**Comment by kannaginomori** [comment]
> 竖向ocr请使用百度ocr等在线ocr，离线版的ocr竖向识别效果很差，没什么意义。 高精度ocr可以添加。

但是百度ocr是默认识别横向文本的，它识别竖向文本需要另外设置，而露娜翻译器没有设置百度ocr识别竖向文本的功能，感觉不太方便，毕竟也有些游戏是竖向文本的。

**Comment by wwchy** [comment]
我加一下就行了。

**Comment by HIllya51** [comment]
我加一下

**Comment by kannaginomori** [comment]
> 我加一下

非常感谢您！！！
