### ISSUE TITLE
The issue with the software version 2.46.2

### ISSUE THREAD

**Issue by TildaRu** [HIllya51/LunaTranslator#702]
### Version 程序版本

2.46.2

### Related screenshot (optional) 相关截图（可选）

Details are in the screenshot.
![1](https://github.com/HIllya51/LunaTranslator/assets/107315419/9da7918a-3a3c-4ed4-8d60-87737df02083)

### Reproduction steps 复现步骤

.

**Comment by HIllya51** [comment]
try it now.
