### ISSUE TITLE
Unity内嵌字体缺失导致全部变方框

### ISSUE THREAD

**Issue by BonBonCure** [HIllya51/LunaTranslator#704]
### Question 问题

Unity翻译，选用的字体无法被内嵌到程序中，被替换为方框\u25A1，也就是中文字体没生效还是原字体
<img width="1083" alt="内嵌" src="https://github.com/HIllya51/LunaTranslator/assets/67302548/800f1c84-e32f-420e-8467-df0e1edbea68">

The character with Unicode value \u(字符) was not found in the [Caudex-Regular] font asset or any potential fallbacks. It was replaced by Unicode character \u25A1 in text object [Game Button 2(Clone)].

字符串选择情况，能替换；但无法在游戏内显示。
<img width="1036" alt="内嵌设置" src="https://github.com/HIllya51/LunaTranslator/assets/67302548/39e3b746-cd99-41ef-ae79-510e38ae0496">

**Comment by BonBonCure** [comment]
我查了原因貌似是添加到 TextMeshProUGUI 对象的文本包含了不支持的中文字符之类的报警提示。目前不清楚问题的关键，是否应在本地添加所修改的字体，可能换成系统字体也无济于事。Unity如内嵌成功的流程需要哪些步骤呢？
https://forum.unity.com/threads/issue-with-unsupported-text.1037230/ 这是引擎里调整字体的，部分描述重合上了。

**Comment by HIllya51** [comment]
unity必须自己制作字体文件，没法用系统字体
https://github.com/bbepis/XUnity.AutoTranslator

**Comment by BonBonCure** [comment]
好的，原来两个工具可以叠加使用，XUnity AutoTranslator先帮助替换字体。原文生僻词较多，需要翻译记忆库来避免生硬的专有名词
