### ISSUE TITLE
设定简单字符串替换会导致程序崩溃

### ISSUE THREAD

**Issue by MidoriG** [HIllya51/LunaTranslator#705]
### Version 程序版本

2.48.0

### Reproduction steps 复现步骤

设定简单字符串替换会导致程序崩溃

**Comment by HIllya51** [comment]
命令行运行debug版截图

**Comment by HIllya51** [comment]
运行路径是什么

**Comment by HIllya51** [comment]
管理员运行debug版给我看下。如果不崩就算了，不处理无法复现的问题。
