### ISSUE TITLE
中文路径报错

### ISSUE THREAD

**Issue by XiaoXiaoYanHe** [HIllya51/LunaTranslator#706]
### Version 程序版本

v2.48.0

### bug's screenshot 错误截图

This application failed to start because no Qt platform plugin could be
initialized. Reinstalling the application may fix this problem.

### Reproduction steps 复现步骤

中文路径v2.45.6更新v2.48.0报错，纯英文路径正常

**Comment by HIllya51** [comment]
修过了，重下 https://github.com/HIllya51/LunaTranslator/commit/c62e9fd7f6ff5d148cfed866d80cb36cc652e515
