### ISSUE TITLE
部分REN'PY游戏界面上的数据会被锁死

### ISSUE THREAD

**Issue by AbsordH2Odemon** [HIllya51/LunaTranslator#708]
### Question 问题

有些游戏会在游戏主界面上显示日期,上午下午之类的,开启了luna之后这个数据就不会变化了.
存档然后读档的话会发现数据已经变化,但是无法自动在UI上更新了.

**Comment by HIllya51** [comment]
不要说什么什么类，这你让我怎么测试？拿具体的游戏onedrive发给我。
而且renpy一般都是有两到三个不同的hook的，你换另一个就行了

**Comment by AbsordH2Odemon** [comment]
您好,具体比如这个游戏 sovereign

作者提供的是mega盘下载地址,如下
https://mega.nz/file/I6tGkAhS#wF4DTL-sh4m0ovhUtopKxPk7O-Vb6iuAa5s4Rol5sUQ
提供地址是这里
https://www.patreon.com/posts/sovereign-9-1-101379650

应该和hook选择哪个无关,我试过只要启动hook,就算不点选择文本按钮,不选择翻译,一样会导致问题.
有可能是REN'PY的版本问题?我这里找到别的会锁的游戏,ren'py的log显示版本都是在8.1以下的(比如FriendHarem也是会锁).
不会锁的那个游戏log中显示ren'py版本是8.2的

**Comment by HIllya51** [comment]
已修正，不开启internal_renpy_call_host的内嵌时不会锁定了，虽然我也没明白为什么会这样。

**Comment by HIllya51** [comment]
已修正，不开启internal_renpy_call_host的内嵌时不会锁定了，虽然我也没明白为什么会这样。
