### ISSUE TITLE
ChatGpt develop works incorrect

### ISSUE THREAD

**Issue by RkSense** [HIllya51/LunaTranslator#709]
### Version 程序版本

Latest version

### bug's screenshot 错误截图

![2024-05-03 (1)](https://github.com/HIllya51/LunaTranslator/assets/62306978/fa4a3498-772d-4944-aad0-9082ca3639b4)

### Reproduction steps 复现步骤

Might not work after recent open ai new domain change
After enabling chatgpt develop feature it copies text from luna to openai website but doesnt auto-send it as it used to be

**Comment by HIllya51** [comment]
fixed
