### ISSUE TITLE
请问方便增添设置翻译历史的显示效果的功能吗？

### ISSUE THREAD

**Issue by kannaginomori** [HIllya51/LunaTranslator#71]
我个人感觉最新版v1.28.2的翻译历史的显示效果还不如老版本，感觉翻译历史每段文本中间的横线属于画蛇添足，老版本没有横线看着更舒服，如果可以设置是否显示横线，自由调整翻译历史的文字大小/颜色/字体之类的就好了。

**Comment by HIllya51** [comment]
好吧

**Comment by kannaginomori** [comment]
> 好吧

非常感谢大佬！您辛苦了！
