### ISSUE TITLE
Problem with second screen when using OCR

### ISSUE THREAD

**Issue by SaniaSok** [HIllya51/LunaTranslator#710]
### Version 程序版本

Last Version 2.48.1

### bug's screenshot 错误截图

Screenshot from the new version where the frame sees only part, and the old version where it sees the entire area: 
![Last Version](https://github.com/HIllya51/LunaTranslator/assets/168916271/fadc192e-ae1f-4a3b-bb69-40ab5f4378c0)
![Old Version](https://github.com/HIllya51/LunaTranslator/assets/168916271/b950b1e8-974c-481f-a21f-bb0dcd4a9f25)

### Reproduction steps 复现步骤

When the second screen is turned on, instead of OCR capturing both screens, for some reason it captures only the second and only a small part of the first screen, all new versions have this problem, both in the new version 2.48.1 and in 2.45.1, which I recently used I was sitting, but what’s remarkable is that on version 2.28.2 everything works as it should and captures both screens as it should, please correct this disgrace due to which it is impossible to use the program comfortably and without nerves

**Comment by HIllya51** [comment]
99% of people including me only use a single screen, so I have no interest in looking into this problem, and taking multiple screenshots is very difficult even with some commercial software. So unless someone does a PR, this problem will never be resolved.

**Comment by SaniaSok** [comment]
But this is not convenient, if you have a second screen, you want to use it and not clutter the main screen with unnecessary elements, but what you are offering is to not care about your convenience and tolerate it, if only you would at least leave the old versions for people so that they can If you didn’t tolerate this problem, there wouldn’t be any questions, but you didn’t do that either

**Comment by HIllya51** [comment]
I am just doing this out of interest, and there is almost no benefit, almost no contribution from anyone else, and I have no obligation to meet any of your requirements.
