### ISSUE TITLE
And you completely broke Hook, it doesn't work at all

### ISSUE THREAD

**Issue by SaniaSok** [HIllya51/LunaTranslator#711]
### Version 程序版本

Last Version

### bug's screenshot 错误截图

![Безымянный](https://github.com/HIllya51/LunaTranslator/assets/168916271/7cf0e2e9-5b23-47dd-bc1f-30ef9a143391)
![Безымянный2](https://github.com/HIllya51/LunaTranslator/assets/168916271/ae1599b5-e16f-42a1-bbfa-76a15fa94314)
![Безымянный3](https://github.com/HIllya51/LunaTranslator/assets/168916271/a5f64640-1926-46f2-9bf4-503ba4ff83b3)
![Безымянный4](https://github.com/HIllya51/LunaTranslator/assets/168916271/dd2d112e-a331-46b6-835c-554490fb3486)
![Безымянный5](https://github.com/HIllya
![7](https://github.com/HIllya51/LunaTranslator/assets/168916271/7d702d5b-5dd7-467c-8ea1-ddacb3f25dc4)
![8](https://github.com/HIllya51/LunaTranslator/assets/168916271/9f247ae8-5394-474d-b437-86ffc372ce82)
![9](https://github.com/HIllya51/LunaTranslator/assets/168916271/cf31ac79-4c6d-4760-8922-7c141bd10cbc)

### Reproduction steps 复现步骤

The tool simply doesn’t translate, it seems to see the text at first, and you can even select it, but then you can’t translate or reselect the text, it just stops seeing, should I remind you how it works on the old version?

**Comment by HIllya51** [comment]
I'm always playing game via hook and never meet bug, this can only due to some your incorrect settings.

If it not work with some game, you should create this issue rather than Report a bug. 

![屏幕截图 2024-05-04 232648](https://github.com/HIllya51/LunaTranslator/assets/101191390/135271f1-ea6c-48ab-ad29-1f97ef49d7fb)

**Comment by HIllya51** [comment]
If you are upgrading from a very old version, there may be unknown errors in the configuration, you can package the userconfig folder to me.

**Comment by SaniaSok** [comment]
This cannot be so, no matter how much I changed the settings when I installed the new version, I just launched it and it didn’t work, when the old version and version 45.1 worked fine

**Comment by HIllya51** [comment]
You should check your settings instead of suspecting such simple errors.

![屏幕截图 2024-05-05 025851](https://github.com/HIllya51/LunaTranslator/assets/101191390/401538f3-e026-4f50-afc9-15106ec261da)
