### ISSUE TITLE
Best OCR settings for blurred or pixel images in old games

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#712]
### Question 问题

Please help me to configure Luna OCR for pixel writings in emulator. I have problems with recognizing it by all OCRs. Solution must be somewhere in processing method. What to choose better? Grayscale, threshhold binarization, OTSU? And what threshhold exactly. Its configured at 128 initially.
![news2](https://github.com/HIllya51/LunaTranslator/assets/80591773/c0a80f42-ebc3-42cb-869c-474e37641b33)

**Comment by HIllya51** [comment]
This has nothing to do with preprocessing. Both built-in OCR and Windows OCR are trained on simple text data, and it is impossible to recognize such low-resolution text. You should choose a professional online API to recognize such difficult text.

For example, I can directly recognize these texts  using Youdao OCR. However, this api may not be accessible in your country. You can try other online apis.

![屏幕截图 2024-05-05 030500](https://github.com/HIllya51/LunaTranslator/assets/101191390/615064f3-e14c-463b-b857-bf6264fc20d6)

**Comment by Farooq87** [comment]
HIllya51,
What are alternatives to Youdao OCR in english and preferably free?

**Comment by HIllya51** [comment]
I don't know.
