### ISSUE TITLE
Update/Fix Hook code for Shin Koihime † Musou -Kakumei- Son Go no Ketsumyaku (Catsystem3 new engine)

### ISSUE THREAD

**Issue by tbhoang12** [HIllya51/LunaTranslator#714]
### Question 问题

https://vndb.org/v20591#main
I use your program to hook and play this game, but your automatic Hook codes aren't hooking the sentences and dialogues in-game perfectly.
For example, many times Luna Translator output sentences which are missing kanjis, character names were put backward at the end of dialogues ( they're supposed to be at the beginning of a voice line like [Character name 1st] > [Dialogues here 2nd])
**Hope you can update the perfect hook for this program, many thanks for your time o/**

More example in-game hook :
「あー、一刀！やっときたー」雪蓮 >> character names should be at the 1st position of a sentence like this
>>雪蓮 (Character name)「あー、一刀！やっときたー」

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/issues/new?assignees=&labels=enhancement&projects=&template=01_game_request.yaml
