### ISSUE TITLE
使用vits-simple-api语音合成的问题

### ISSUE THREAD

**Issue by luoliyushu** [HIllya51/LunaTranslator#715]
### Version 程序版本

v2.48.1

### bug's screenshot 错误截图

作者您好，我在使用语音合成的vits-simple-api的时候出现了问题
![1714906488560](https://github.com/HIllya51/LunaTranslator/assets/112807173/c74d5fd0-f58f-4d47-8625-f93c67bcc93c)

### Reproduction steps 复现步骤

我排查了一下，发现是 vitsSimpleAPI.py 里面的 lang=ja 出现了问题，当我把它改成 lang=auto 的时候就能正常合成语音了。

**Comment by HIllya51** [comment]
好的 已修
