### ISSUE TITLE
Broken replacement feature and chatgpt develop

### ISSUE THREAD

**Issue by RkSense** [HIllya51/LunaTranslator#716]
### Version 程序版本

Last version

### bug's screenshot 错误截图

![2024-05-05](https://github.com/HIllya51/LunaTranslator/assets/62306978/d44074db-ca07-42a0-b331-bb0e83d9df08)

### Reproduction steps 复现步骤

After enabling any replacement feature luna just straight up crashes. And also sorry for bothering again but after enabling gpt develop it infinetly opens open ai site

**Comment by HIllya51** [comment]
If it crash, use LunaTranslator_debug and show me the error log

Re download the latest version, it now only opens chatgpt.com rather than open the chat.openai.com.
