### ISSUE TITLE
白描OCR

### ISSUE THREAD

**Issue by blucca** [HIllya51/LunaTranslator#717]
### Expected behavior 预期的功能

能否支持白描OCR？感觉挺准的，也支持竖排识别

https://web.baimiaoapp.com/

**Comment by HIllya51** [comment]
营销味儿太冲了，而且就是套壳的讯飞
<img width="785" alt="屏幕截图 2024-05-05 203613" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/9579431d-3b2d-4a0d-96d2-bbcd4b9362d9">

**Comment by HIllya51** [comment]
可以，但你得给我一个测试api

**Comment by HIllya51** [comment]
什么叫怎么给。

**Comment by HIllya51** [comment]
已支持

**Comment by HIllya51** [comment]
考虑完了，太垃圾了，注册还必须要下app，不予支持。
