### ISSUE TITLE
32位和64位的程序能否合并发布

### ISSUE THREAD

**Issue by edr1412** [HIllya51/LunaTranslator#718]
### Expected behavior 预期的功能

HIllya51 你好，
如果我没有理解错，对于64位的Windows系统，目前的`LunaTranslator_x86.zip`只能hook到32位的游戏，`LunaTranslator.zip`只能hook到64位的游戏，对吗？（我机器上的情况是`LunaTranslator_x86.zip`遇到64位游戏会闪退，`LunaTranslator.zip`遇到32位游戏会hook不到任何文本）

但这两个分开用的话，如果同时玩32位的和64位的游戏，每次改配置时，就还得手动改另一个程序的配置
另外也有别的麻烦，比如游戏管理功能无法统一统计到所有游戏

所以我想问下，对于64位的机器，32位和64位程序方不方便放一个目录里，共用同一个配置文件？比如说在同一个目录下区分`LunaTranslator.exe`和`LunaTranslator_x86.exe`，这样体验可能更好

**Comment by HIllya51** [comment]
理解错了，都是能hook32/64的，如果不能那就是你遇到bug了

**Comment by HIllya51** [comment]
如果不能hook，那么 https://github.com/HIllya51/LunaHook/issues/new?assignees=&labels=enhancement&projects=&template=01_game_request.yaml
  
如果会闪退，那么运行_debug.exe在闪退处截图 https://github.com/HIllya51/LunaTranslator/issues/new?assignees=&labels=bug&projects=&template=01_bug.yaml

**Comment by HIllya51** [comment]
如果不能hook，那么 https://github.com/HIllya51/LunaHook/issues/new?assignees=&labels=enhancement&projects=&template=01_game_request.yaml
  
如果会闪退，那么运行_debug.exe在闪退处截图 https://github.com/HIllya51/LunaTranslator/issues/new?assignees=&labels=bug&projects=&template=01_bug.yaml

**Comment by edr1412** [comment]
@HIllya51  哦 我忘了我用的是arm架构64位的Windows11… 是不是这个原因？平常x86程序都能跑，都没这个意识了…
运行_debug.exe时，你的64位程序hook32位游戏还是没有信息；然后你的32位程序hook64位程序时，打印了这2行就闪退了
![Screenshot 2024-05-06 at 22 03 46](https://github.com/HIllya51/LunaTranslator/assets/40953911/8683be20-430b-42ab-8c0b-6d42e34cdf67)
别的就没信息了，日志不知道在哪，有的话我提供
应该和游戏没关系，我试了几个都这样。您看看，搞不定就算了

**Comment by HIllya51** [comment]
arm😅

那你试试把这个去掉


![屏幕截图 2024-05-06 221520](https://github.com/HIllya51/LunaTranslator/assets/101191390/1b02a71a-763e-4c95-96e9-c0284671685e)

**Comment by edr1412** [comment]
@HIllya51  大佬YAPI是啥呀 文档里也没找着
咋还改defaultconfig了咧😂

**Comment by HIllya51** [comment]
交叉注入器，可以不用中间进程来注入，但是可能兼容性有点问题

**Comment by edr1412** [comment]
@HIllya51 那能否针对每个游戏决定是否使用YAPI注入呀

**Comment by HIllya51** [comment]
没什么意义
