### ISSUE TITLE
Unobvious behavior of the "re-translation" (重新翻译) and "translation cache" (使用翻译缓存) functions.

### ISSUE THREAD

**Issue by AnLimt** [HIllya51/LunaTranslator#719]
### Version 程序版本

v2.48.1

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/107651742/6987e492-77b3-4f83-a8bf-f7eec6598e57)

### Reproduction steps 复现步骤

Observation:
When using the "re-translate" function, the text from the translation cache is output, even if the "use cache" checkbox is checked off."

Expected Behavior:
When using the "re-transfer" function a new request to the translation service will be generated and sent, and the translation cache will be overwritten (if cache saving is enabled).

Detection features:
I use gemini for translation, so any change in promt greatly affects the output, however, this is not the case with this error, you can see that no re-request is sent to the translation service.
In general, this error is also repeated for other translation services.

**Comment by HIllya51** [comment]
fixed https://github.com/HIllya51/LunaTranslator/commit/d648913f6626e38179f9d62e51ae274d33d48927

now all gpt like apis will re translate when use this button. for other apis, if you want, you can add the config "is_gpt_like"=true to make it can be re translated.
