### ISSUE TITLE
试了几个游戏都不能用自带的 Magpie 全屏

### ISSUE THREAD

**Issue by 2-3-5-7** [HIllya51/LunaTranslator#72]
试了几个游戏都不能用自带的 Magpie 全屏，已用 HOOK 方式运行游戏，试了下工具栏的“游戏静音”功能可用，但全屏不好使。
我一共只有 3 个游戏，最終痴漢電車3、鬼父2、JK妹，都不行，我甚至怀疑是否是我设置的问题。

我用独立的同版本 Magpie，使用“5秒后缩放” 功能，是可以把这些游戏正常全屏的，然而翻译器自带的就不行。

我一会把“最終痴漢電車3”传到百度网盘上，麻烦大佬看一下。

**Comment by 2-3-5-7** [comment]
https://pan.baidu.com/s/1hre0puEK3fbBGiYqZHwOPw 
t0s2
解压密码是  LunaTranslator  ，运行的日文原版 GAME_SYS.exe

**Comment by HIllya51** [comment]
如果你的mapie是0.91版本的，可以试一下将Magpie_RT.dll替换成我修改的，这样也可以做到点击软件不会退出全屏，除了不能点击按钮全屏外也没什么区别了。

**Comment by HIllya51** [comment]
找了个gf2的资源，确实如你所说的那样。但是不知道为什么命令行调试可以全屏，导出exe就不行了。。。。。。。。。

**Comment by HIllya51** [comment]
唉 我sb了 。已修复。

**Comment by 2-3-5-7** [comment]
鬼父2 是可以的，另外两个（最終痴漢電車3、JK妹）不行，好像都是竹子社的？鼠标会无法点到工具栏按钮，穿透过去。
试了替换 Magpie_RT.dll ，用独立的 Magpie 全屏，也是鼠标会无法操作工具栏按钮。与不替换没看出区别。

也就是只有鬼父2，在翻译器里全屏，是可操作工具栏按钮的。

如果不好改就算了，用快捷键来操作也行。或者暂时退出全屏再切回去。
