### ISSUE TITLE
Youdao OCR in Luna

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#722]
### Question 问题

I have recently tried to obtain APP_key and Secret_Key on Youdao through my  aunt who is teacher of Chinese. She has some friends from People's Republic of China.
Could you tell me, friend, is chinese sim-card would be enough to register and use Youdao OCR from Russia?
Second question is what are the limits of free use of Youdao OCR?

**Comment by HIllya51** [comment]
1、Can't you just try it yourself? How do I know？

2、Determined by the server, there is no information available for reference
