### ISSUE TITLE
翻译缓存开启的状态下，翻译之前翻译过的句子会出现不显示的问题（翻译记录里能正常显示）

### ISSUE THREAD

**Issue by Z9wind** [HIllya51/LunaTranslator#723]
### Version 程序版本

2.48.1

### bug's screenshot 错误截图

<img width="921" alt="微信图片_20240507022220" src="https://github.com/HIllya51/LunaTranslator/assets/107527857/2e2dc1c6-e880-4e3b-834b-f14cc6761804">

### Reproduction steps 复现步骤

重现已翻译场景时会出现如上问题

**Comment by HIllya51** [comment]
fixed
