### ISSUE TITLE
“打开保存的游戏”封面图缩放效果比较差

### ISSUE THREAD

**Issue by shinslashisuka** [HIllya51/LunaTranslator#724]
### Expected behavior 预期的功能

记得不能调整封面图大小的老版本，虽然显示图片小，但是缩放效果比较好。
目前版本如果设置小于250x350，缩放图片会细节丢失。老版本虽然模糊但是缩放很平滑。

**Comment by HIllya51** [comment]
改成适应

![屏幕截图 2024-05-07 165216](https://github.com/HIllya51/LunaTranslator/assets/101191390/b93d7763-7cf2-4994-9265-74872aa31a8b)
