### ISSUE TITLE
VOICEVOX无法使用

### ISSUE THREAD

**Issue by Huang-Yujie** [HIllya51/LunaTranslator#725]
### Version 程序版本

v2.48.1

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/52700998/af90ffaa-6543-4394-817e-f14edc6fe902)
![image](https://github.com/HIllya51/LunaTranslator/assets/52700998/f066688b-f087-48fc-b329-33f6a2ec7872)

### Reproduction steps 复现步骤

VOICEVOX版本是最新的v0.19.1
无论VOICEVOX程序本身是否启动，在Lunatranslator中选择路径之后都无法选择音色，也无法进行TTS

**Comment by HIllya51** [comment]
已修

**Comment by HIllya51** [comment]
或者路径选择vv-engine
