### ISSUE TITLE
文本選擇問題

### ISSUE THREAD

**Issue by rain22127** [HIllya51/LunaTranslator#726]
### Question 问题

您好，我很喜歡這款程式。想請教開啟「死神商館RExEX ～ カネのチカラをマシマシして女冒険者のハーレムを作るRPG」此遊戲並翻譯過後的文本，遊玩時都很正常。但當我重新開啟遊戲時，都要重新選擇文本，請問這是我設定沒有調整好？

**Comment by HIllya51** [comment]
图。

**Comment by rain22127** [comment]
這是最一開始有點選文本及顯示正常的狀態
![number1](https://github.com/HIllya51/LunaTranslator/assets/169276601/63f99b8a-63b2-43e2-91f3-16ca0c988103)

然後是重新遊戲後的遊戲
![number2](https://github.com/HIllya51/LunaTranslator/assets/169276601/a50324b6-d573-439f-827f-fc75673ee698)
![number3](https://github.com/HIllya51/LunaTranslator/assets/169276601/60e118e1-867e-41fb-addc-8878f70ef728)

**Comment by HIllya51** [comment]
哦，这个是unity引擎，没有固定的hook地址，没法自动选择

**Comment by HIllya51** [comment]
更新了文本提取器，现在应该可以固定了

**Comment by rain22127** [comment]
測試成功！
