### ISSUE TITLE
描边字体注音样式问题

### ISSUE THREAD

**Issue by blucca** [HIllya51/LunaTranslator#728]
描边字体，注音也变粗以后变得难以阅读了，能否给一个恢复原来样式的选项

现在的样子：
<img width="83" alt="image" src="https://github.com/HIllya51/LunaTranslator/assets/127029904/78a8f711-a572-4fb2-8572-f8c9e2691dd0">

之前的样子：
<img width="82" alt="image" src="https://github.com/HIllya51/LunaTranslator/assets/127029904/a1831a8f-f9d7-41f5-8393-33be130b3c8e">

**Comment by HIllya51** [comment]
已修
