### ISSUE TITLE
文本处理/正则表达式替换——正则表达式pattern存在二次转义

### ISSUE THREAD

**Issue by wqhanginge** [HIllya51/LunaTranslator#729]
### Question 问题

![image](https://github.com/HIllya51/LunaTranslator/assets/54838305/99d5d1f5-0975-41a4-96fe-42348ef2fdfc)

**正则表达式替换**的功能中对正则表达式的**pattern**执行了额外的转义处理，即如果希望`pattern = "\\."`，则需要`原文内容 = "\\\\."`。如上图第1条不能匹配字符串`"test\; string"`中的`"\;"`，而第2条才能正确匹配。

直觉上讲，UI界面的"原文内容"字段是应该是输入**pattern**的地方，不应该再对输入的内容额外转义，也不应该取名"原文内容"，容易让人误解。此外，**正则表达式替换**和**转移字符串替换**的"替换为"字段都是支持带转义字符的字符串，而**简单字符串替换**的"替换为"字段不支持转义字符，两者一致性有问题。事实上，**转义字符串替换**的功能可以完全替代**简单字符串替换**，建议直接删去**简单字符串替换**功能以避免混淆。

**Comment by HIllya51** [comment]
当然要转义，不然你怎么输\n？

**Comment by HIllya51** [comment]
怎么可能删去，我要是就想过滤掉个.，难道还要转译成\.吗？又不是所有人都懂程序。

**Comment by wqhanginge** [comment]
正则表达式本身是支持`\n`的，`pattern = r"\n"`可以直接匹配到换行符，其他非显示字符也都有对应的语法。正则表达式本身的语法中就存在大量转义，在此之上再叠一层字符串的转义难免过于啰嗦。

**Comment by HIllya51** [comment]
啰嗦就罗嗦了，也没办法，已经这样了，总不能破坏兼容吧。

**Comment by wqhanginge** [comment]
了解了，多谢。

**Comment by HIllya51** [comment]
没办法，早期设计的时候没考虑这么远，有很多简陋的设计，但已经有很多人用了而且有很多设置了，没办法去破坏这种设置很麻烦的东西的兼容的，只能做加法不能做减法，或者做一个格式的转换，但正则这种东西不好转换，所以只好这样了。
