### ISSUE TITLE
用显示/隐藏翻译窗口快捷键隐藏窗口后，再次按快捷键窗口无法恢复显示

### ISSUE THREAD

**Issue by 2-3-5-7** [HIllya51/LunaTranslator#73]
用显示/隐藏翻译窗口快捷键隐藏窗口后，再次按快捷键窗口无法恢复显示

比如我配置 Win + F3，换成 Alt + F3 也一样。
![image](https://user-images.githubusercontent.com/79762374/202586069-c5e84da5-49a7-409f-8986-408231b260d4.png)

**Comment by HIllya51** [comment]
。。测试未发现任何问题
可能是win快捷键和系统一些原有快捷键有冲突

**Comment by 2-3-5-7** [comment]
我是隐藏窗口，然后点一下别的窗口，比如资源管理器，再按快捷键显示窗口，软件就会卡死。
应该不是冲突，我把窗口快捷键改成给历史翻译用的 win+F2，也是一样的效果。

**Comment by HIllya51** [comment]
我仍未发现任何问题。不过我上传了一个debug版本的程序，你可以在卡死的时候截个图给我看一下是什么问题。。

**Comment by 2-3-5-7** [comment]
嗯，用 debug 版本就是卡死了，没显示什么信息。
我在 win11 的沙盒中运行，发现快捷键没问题。可能就是和我装的软件有什么冲突吧，会导致它卡死。谢谢了！
