### ISSUE TITLE
Promt memorization system for saved games

### ISSUE THREAD

**Issue by AnLimt** [HIllya51/LunaTranslator#730]
### Expected behavior 预期的功能

Add a "Promt" tab for each game in their personal settings menu and a setting that will automatically allow it to be used (or not) in gpt_like translators if possible....

**Comment by HIllya51** [comment]
can't understand

**Comment by AnLimt** [comment]
This feature request proposes the implementation of a "Prompt" tab within each game's settings menu. This tab would empower users to:
Create, edit, and delete game-specific prompts: This allows for personalized instruction sets tailored to each game's unique context and translation needs.
Enable automatic prompt integration with GPT-based translators: Upon switching between games, the corresponding prompt would be automatically loaded into the translator (if such integration is feasible).
Control global prompt automation: A checkbox would dictate whether all prompts are automatically applied to GPT or require manual selection.

**Comment by HIllya51** [comment]
This doesn't make any sense. If you need it, you can create a txt to record it.
