### ISSUE TITLE
hook文本不全

### ISSUE THREAD

**Issue by 668668acg** [HIllya51/LunaTranslator#731]
### Question 问题

The Genesis Order 创世纪秩序
hook出来的文本永远缺少开头的单词
![屏幕截图 2024-05-10 224517](https://github.com/HIllya51/LunaTranslator/assets/169470320/aa1f7492-cd9e-4bb7-83ef-b4548c1a9448)
![屏幕截图 2024-05-10 224538](https://github.com/HIllya51/LunaTranslator/assets/169470320/ea157e4d-3a80-4d4e-9b52-0c74c9e3b220)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/issues/new?assignees=&labels=enhancement&projects=&template=01_game_request.yaml

**Comment by HIllya51** [comment]
这b游戏搜都搜不到，不主动给我，让我上哪里去找啊，简直了。

**Comment by 668668acg** [comment]
不好意思，上传有点慢，拖到今天了，麻烦大佬看一下
