### ISSUE TITLE
v2.50.0 问题

### ISSUE THREAD

**Issue by AkikazeQ** [HIllya51/LunaTranslator#734]
### Version 程序版本

RPG MAKER MV

### bug's screenshot 错误截图

似乎更新了LUNA HOOK，因为选择hook文本的时候，比昨天的版本多识别到了一个hookClipboard文本框可供选择

### Reproduction steps 复现步骤

但部分RPG MAKER游戏，如クロアxスクランブル 製品版 ver1.092，
进入战斗后的技能菜单会比上个版本LUNA变得明显卡顿（变成不间断卡顿或几帧），
LLAMA CPP后台往上跑了一坨东西，似乎接到了一些翻译任务（但是技能菜单并没有任何可供翻译的内容文本），
部分战斗后会导致游戏直接崩溃。更换回昨天的上个版本，一切恢复正常。

**Comment by HIllya51** [comment]
游戏给我。

**Comment by HIllya51** [comment]
已修

**Comment by AkikazeQ** [comment]
另外报告一个游戏。修复后的新版本仍然存在问题。
https://mexa.sh/5bfcbkgquved/240415-G1116257.zip.html
下载地址
セリカマギア ～王都アダルトショップ編～ 
HOOK游戏后，
跳过OP，按X进入菜单会非常非常卡的要死，正常打开游戏不HOOK则不会。
