### ISSUE TITLE
另外报告一个修复后仍然存在卡顿问题的游戏

### ISSUE THREAD

**Issue by AkikazeQ** [HIllya51/LunaTranslator#735]
### Version 程序版本

RPG MAKER MV

### bug's screenshot 错误截图

问题描述：跳过OP进入可以操作的状态，X进入菜单，如果游戏HOOK了，会非常非常卡。
没HOOK的话，游戏则不会。

### Reproduction steps 复现步骤

セリカマギア ～王都アダルトショップ編～
https://mexa.sh/5bfcbkgquved/240415-G1116257.zip.html
下载地址

**Comment by HIllya51** [comment]
😅为什么要给我这么个垃圾网盘恶心我啊

**Comment by HIllya51** [comment]
给我od/gd，否则我不管了。

**Comment by AkikazeQ** [comment]
这个网盘是不限速网盘，有ADBLOCK也没广告，除了要等60S，有啥不好？不明白。

**Comment by HIllya51** [comment]
我打开三次，全都打不开，恶心我三次。

**Comment by AkikazeQ** [comment]
这个是国外资源站得一个常用不限速下载网盘，我平时用着挺好的，虽然没megaup这些快，
没遇到过你遇到这种情况，我自己传了一个。
https://megaup.net/40adfee55c7d7baaff7146492f3977b1/240505-G419055-v1.03.rar

**Comment by HIllya51** [comment]
这个能下的动了。

测试了下感觉应该是因为加壳导致一些系统调用速度会很慢，因为是通过剪贴板交互的，所以变卡。我加个判断有没有壳，有壳就把这个hook点去掉就行了。

**Comment by AkikazeQ** [comment]
嗯，这类游戏可以通过用https://lifeinhex.com/的EnigmaVBUnpacker解包，然后游戏就跟正常rpg maker游戏一样了。

**Comment by HIllya51** [comment]
已修复，等待CI
