### ISSUE TITLE
Import Textractor Plugins

### ISSUE THREAD

**Issue by Hanifahreza** [HIllya51/LunaTranslator#736]
### Expected behavior 预期的功能

I'm aware that you can import Textractor plugins with LunaHook, but I haven't found any option to do this with LunaTranslator. I need this feature to use the [TextractorSender](https://github.com/KamWithK/TextractorSender) plugin for exSTATic.

Thank you for your hard work.

**Comment by HIllya51** [comment]
Textractor plugins' design is not good, this program will never support them. Even in LunaHook, I don’t want to support them.

If you want to output the text to other program, LunaTranslator natively supports it via Clipboard and Websocket.

![屏幕截图 2024-05-12 161113](https://github.com/HIllya51/LunaTranslator/assets/101191390/878e5097-b551-45e4-80c7-66ffd979ac58)
