### ISSUE TITLE
hook can't show "ruby in html"，文字注音或字符注释

### ISSUE THREAD

**Issue by asukaminato0721** [HIllya51/LunaTranslator#737]
### Version 程序版本

v2.50.0

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/30024051/672de5d8-f9ca-4176-88af-86e30242a5c8)

### Reproduction steps 复现步骤

游戏是 サクラノ刻，这个在 web 里叫 <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby>

**Comment by HIllya51** [comment]
这个游戏带注音的和不带注音的不在一个函数里绘制，没办法咯。
