### ISSUE TITLE
移动翻译窗口跨显示器时，翻译窗口的大小会突然鬼畜变得巨大，然后程序崩溃

### ISSUE THREAD

**Issue by faker2048** [HIllya51/LunaTranslator#739]
### Version 程序版本

latest

### bug's screenshot 错误截图

如题所述，翻译的窗口大小会铺满两边的屏幕，不太好截图，应该很好复现。

### Reproduction steps 复现步骤

我的环境：
显示器1（主显示器）: 2560*1440 分辨率，100缩放比例
显示器2  ： 4k 分辨率，150缩放比例

1. 拖动翻译窗口从显示器1到显示器2

**Comment by HIllya51** [comment]
没有实现适应dpi变化而已，正常，懒得弄，太麻烦。
