### ISSUE TITLE
关于v1.28.4的一个小小的bug

### ISSUE THREAD

**Issue by kannaginomori** [HIllya51/LunaTranslator#74]
首先感谢大佬更新，我用v1.28.4的时候，发现我在翻译历史里选中一段文本，单击鼠标右键准备复制文本的时候，copy那个框没有出现，而是闪了一下就消失了，但是我用v1.28.2做同样的操作的时候，copy那个框就是正常出现的，希望能修复一下这个小bug。

**Comment by HIllya51** [comment]
已修正
