### ISSUE TITLE
关于正则表达式替换

### ISSUE THREAD

**Issue by k2250761** [HIllya51/LunaTranslator#740]
### Question 问题

![tmp3D1F](https://github.com/HIllya51/LunaTranslator/assets/61865659/0e0fbd70-4226-49d2-9e97-bbc04bf86def)
填入替换内容之后要关闭这个窗口，才能生效。有什么方法能够，填完之后就生效，方便多次填入测试翻译结果。
不要填入一个词条要关闭一次，太麻烦

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/af91d678ddbbb63ff20e30cb06913f524689f6ac

**Comment by k2250761** [comment]
> [af91d67](https://github.com/HIllya51/LunaTranslator/commit/af91d678ddbbb63ff20e30cb06913f524689f6ac)

我不太会操作，能麻烦简单点吗
