### ISSUE TITLE
彩云在线WIN7错误

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaTranslator#741]
### Version 程序版本

V2.50.2

### bug's screenshot 错误截图

![1](https://github.com/HIllya51/LunaTranslator/assets/167575533/c5ebf297-305f-4f9d-960f-573b5863668b)

### Reproduction steps 复现步骤

WIN7彩云API没问题，在线翻译错误。WIN10均无问题

**Comment by HIllya51** [comment]
其他设置->internet->libcurl
