### ISSUE TITLE
恋狱月狂病FHD部分文本识别不了

### ISSUE THREAD

**Issue by darkness151103** [HIllya51/LunaTranslator#742]
### Question 问题

是在序章离开和菜家的对话场景里，如图，下面这句话hook根本没有读取到，请问这怎么解决？
![image](https://github.com/HIllya51/LunaTranslator/assets/60108657/e084ac58-7072-404e-a61d-23a3f8095640)

**Comment by HIllya51** [comment]
存档

**Comment by darkness151103** [comment]
> 存档
没事，已经解决了，把这个×掉就能显示了
![image](https://github.com/HIllya51/LunaTranslator/assets/60108657/5cea83cc-bf9c-40ac-983d-03f07c605513)
