### ISSUE TITLE
ChatGPT develop bug

### ISSUE THREAD

**Issue by RkSense** [HIllya51/LunaTranslator#743]
### Version 程序版本

Latest Version

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/62306978/d1dd4c10-af0f-45ad-9bba-31abaa25a5d1)
![image](https://github.com/HIllya51/LunaTranslator/assets/62306978/7c0eb049-0943-46f8-9b06-c2aaff1dda59)

### Reproduction steps 复现步骤

After recent gpt update to new version and ui update at site it stopped sending text after copy-pasting it.

**Comment by HIllya51** [comment]
fixed
