### ISSUE TITLE
Error when using the "Difference between name and text" option

### ISSUE THREAD

**Issue by AnLimt** [HIllya51/LunaTranslator#744]
### Version 程序版本

2.50.4

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/107651742/9b3d9fbd-5e43-40ac-a59d-4caa2256f65f)

### Reproduction steps 复现步骤

**Description:**
When trying to open and capture a hook with text, if you then go to the settings and enable the "Difference between name and text" option, then close the program and launch it again, the program crashes when trying to automatically install the saved hook.

**Steps to reproduce:**
1. Open the game and capture a hook with text.
2. Open the settings and enable the "Difference between name and text" option.
3. Close and relaunch the program.
4. The program should attempt to automatically install the saved hook, resulting in a crash.

**Expected behavior:**
The program should correctly install the saved hook, even if the "Difference between name and text" option is enabled.
Additional information:
The error occurs in different games.
The crash does not happen when the "Difference between name and text" option is disabled.

**Comment by HIllya51** [comment]
ok, later it will be fixed
