### ISSUE TITLE
能将语音合成里面的vits-simple-api功能支持GPT-SOVITS嘛？

### ISSUE THREAD

**Issue by luoliyushu** [HIllya51/LunaTranslator#745]
### Expected behavior 预期的功能

目前的vits-simple-api功能，我只能使用 BERT-VITS2 和 VITS，但是我感觉GPT-SOVITS的效果更好一些

### Alternative behavior (optional) 近似的功能（可选）

我在 vitsSimpleAPI.py 里面的接口改成以下样子勉强支持了 GPT-SOVITS 但是很局限。
![1715857140453](https://github.com/HIllya51/LunaTranslator/assets/112807173/cfbb7dd5-207f-4d8b-9a01-247d9246cfac)
局限：GPT-SOVITS 生成语音需要提前选一段语音作为参考，preset=default5 就是自己的参考音频预设，所以每次想换模型的时候都要自己去对应代码里面改参考音频预设，所以能不能实现类似于 vits-simple-api 一样的切到 GPT-SOVITS 模型就能够自己选参考语音？
我修改的接口代码：
            f"http://127.0.0.1:23456/voice/{model}?text={encoded_content}&id={idx}&lang=auto&format=wav" \
            if model != "gpt-sovits" \
            else f"http://127.0.0.1:23456/voice/{model}?id={idx}&prompt_lang=auto&preset=default5&text={encoded_content}"

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/df5297e67fb583046e0f3574c7327f9bc3fd7e58

**Comment by luoliyushu** [comment]
> 您可以使用它来教一下，GPT-SOVITS 预设里面该怎么填才能读取到wav路径和参考文本内容 不会代码所以没看懂/(ㄒoㄒ)
> 
> 这里：https://cdn.statically.io/gh/Ameryou/picx-images-hosting@master/20240612/GPT-SOVITS_preset.1758kmm7y4.png

填自己在config.yaml里面的预设语音的default就可以了，而且我上面也说了preset是参考音频预设。
例如：
![1718249144441](https://github.com/HIllya51/LunaTranslator/assets/112807173/689cd589-6d2a-46f6-8ec5-643c5649a631)

**Comment by Ameryou** [comment]
> > 您可以使用它来教一下，GPT-SOVITS 预设里面该怎么填才能读取到wav路径和参考文本内容 不会代码所以没看懂/(ㄒoㄒ)
> > 这里：https://cdn.statically.io/gh/Ameryou/picx-images-hosting@master/20240612/GPT-SOVITS_preset.1758kmm7y4.png
> 
> 填自己在config.yaml里面的预设语音的default就可以了，而且我上面也说了preset是参考音频预设。 例如： ![1718249144441](https://private-user-images.githubusercontent.com/112807173/339199845-689cd589-6d2a-46f6-8ec5-643c5649a631.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTI3NjksIm5iZiI6MTcxODI1MjQ2OSwicGF0aCI6Ii8xMTI4MDcxNzMvMzM5MTk5ODQ1LTY4OWNkNTg5LTZkMmEtNDZmNi04ZWM1LTY0M2M1NjQ5YTYzMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwNDIxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODU4MzBiYjQwZWE4NzQ5NmE3ZjZiYWY5MjhjYjA0ZjVjOTQyNmQ2N2UwNGIyM2JjN2VhNjk4MTZhYWFlZjdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pgxtciN1UQYMR1pe9Hiz3TF-gGmmO6sHkGBsH3XE5Dw)

感谢大佬
