### ISSUE TITLE
VALKYRIA会社游戏文本Hook不全

### ISSUE THREAD

**Issue by kunger97** [HIllya51/LunaTranslator#747]
### Version 程序版本

2.51.4

### bug's screenshot 错误截图

![QQ截图20240517220843](https://github.com/HIllya51/LunaTranslator/assets/1808555/79c6362b-126c-4b29-ba5e-1de628fc7ea5)
![QQ截图20240517220917](https://github.com/HIllya51/LunaTranslator/assets/1808555/3a5d6502-f61f-4c6a-99a8-32a0a18a27f2)

### Reproduction steps 复现步骤

VALKYRIA会社游戏（测试过魔法少女フーワ～触手狂精姦～(DL版)/プレイ！プレイ！プレイ！ロック！）都存在这个问题，但是表现一样，我认为可能可以一起解决。
#### 复现步骤
1.使用LE转区运行游戏
2.使用Hook方式获取文本，由于获取到的文本存在重复问题，所以启用了文本处理规则。（请参考截图）
3.进行游戏，直到出现如图所示的无法获取到完整对话的情况（该问题并不出现在每一段对话，而是在某些特定对话出现，可能是剧本存在什么控制字符）

#### 游戏资源
我在这提供プレイ！プレイ！プレイ！ロック！的OneDrive
https://nyaastar-my.sharepoint.com/:u:/g/personal/ns-uid-0001_nyaa-star_88688886_xyz/ETv7jhVgMfZPtLDk8D8IlDoBESiVWXqnWuDCF-GGbz3teA?e=sjOpnK

**Comment by HIllya51** [comment]
给我存档点

**Comment by kunger97** [comment]
https://sagaoz.net/savedata/ha/play6_seiya.zip
试试这个

**Comment by HIllya51** [comment]
我不是要全cg，我是要你截图的这个地方的存档点

**Comment by kunger97** [comment]
![image](https://github.com/HIllya51/LunaTranslator/assets/1808555/d69da593-0559-497e-ac4f-4601e0db3c26)
回想选择这个即可

**Comment by HIllya51** [comment]
![屏幕截图 2024-05-17 233933](https://github.com/HIllya51/LunaTranslator/assets/101191390/01c1a8e5-9b80-400c-a92a-d44d984db717)

**Comment by HIllya51** [comment]
没任何问题。。不知道你是不是改了什么设置导致的。

**Comment by kunger97** [comment]
好吧，如果用全新的确实可以。我再看看吧。谢谢
