### ISSUE TITLE
选取多条HOOK文本时的前后排序功能

### ISSUE THREAD

**Issue by AkikazeQ** [HIllya51/LunaTranslator#748]
### Expected behavior 预期的功能

![image](https://github.com/HIllya51/LunaTranslator/assets/96406562/fa52df3a-14ec-4b5c-a1f9-23acfba268d4)
如图，部分avg HOOK后，人名和内容是分开的，为了翻译效果，
带上人名的句子，提交给模型，比不带的，能获得更正确的翻译结果。

部分游戏也存在游戏AVG本文框内的内容分成了2段HOOK的情况。

目前LUNA会根据HOOK到文本的先后，随机前后顺序组合2~3个HOOK点的内容。
如：人名「句子」，或「句子」人名
如：第一句 + 第二句 或 第二句 + 第一句

我尝试在文本预处理里，依靠自定义PY里实现这个功能，把「」外的内容永远固定在文本之前，
但是似乎预处理是分别对每个HOOK到的文本内容进行单独处理，
自定义的PY无法控制最终提交给翻译引擎的文本组合顺序。

希望能在LUNA HOOK自定义，多选情况下，HOOK内容组合后顺序，这样遇到需要2~3个HOOK点内容组合的时候，
能根据每个游戏的具体情况，和用户各自的阅读习惯，将文本正确组装。

**Comment by HIllya51** [comment]
已修

**Comment by HIllya51** [comment]
另外，可以通过翻译优化里的自定义优化来做这件事。

**Comment by AkikazeQ** [comment]
请问翻译优化里自定义优化具体是修改文件目录下的哪个文件？
我之前都是用的userconfig/mypost.py 来根据每个游戏做自定义处理，
遇到这种2个~3个HOOK点组合文本，文本全程随机组合的情况就没办法了。

**Comment by HIllya51** [comment]
userconfig/myprocess.py 一点那个尺寸他会自动打开

**Comment by AkikazeQ** [comment]
谢谢
