### ISSUE TITLE
cohere调用问题

### ISSUE THREAD

**Issue by magicdmer** [HIllya51/LunaTranslator#749]
### Version 程序版本

2.51.5

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/5556368/b50eab50-0191-4bcb-ab02-71156808f5d8)
![image](https://github.com/HIllya51/LunaTranslator/assets/5556368/3d49ed0a-6794-4d6b-a7a9-7feb343170de)

### Reproduction steps 复现步骤

配置好cohere后，打开游戏进行翻译，报错了，已经走了代理

**Comment by HIllya51** [comment]
给我个测试key

**Comment by magicdmer** [comment]
> 给我个测试key

加群了，qq私发你？

**Comment by HIllya51** [comment]
已修
