### ISSUE TITLE
请问方便增加一个新功能吗？

### ISSUE THREAD

**Issue by kannaginomori** [HIllya51/LunaTranslator#75]
我发现有些游戏开了游戏设置里内置的全屏之后，露娜翻译器就会被游戏的全屏窗口完全挡住，所以大佬方便增加一个不管游戏窗口怎么样，翻译器窗口始终位于游戏窗口上方的新功能吗？以免有些游戏一开内置全屏就挡翻译器。非常感谢您！

**Comment by wwchy** [comment]
显示设置里

**Comment by HIllya51** [comment]
已修正

**Comment by kannaginomori** [comment]
> 已修正

我用v1.29.0试了一下某个游戏，发现该游戏设置了内置全屏之后挡住翻译器窗口的情况仍然存在，其他游戏目前好像没再遇到这个问题，具体情况我会通过邮件发送给您，如果您愿意百忙之中排查一下这个奇怪的bug，我将不胜感激。

**Comment by HIllya51** [comment]
你倒是说一下是哪个游戏啊。。。

**Comment by kannaginomori** [comment]
> 你倒是说一下是哪个游戏啊。。。

邮件现在已经发送到您的邮箱里了，不好意思，因为邮箱上传附件很慢所以没能及时发送邮件，具体情况如邮件中所述，反正那个游戏让我很无语，麻烦您了。

**Comment by HIllya51** [comment]
。。。这根本不是没有置顶，是游戏把系统分辨率改了。你把软件挪到左上角在全屏就知道了。

**Comment by kannaginomori** [comment]
> 。。。这根本不是没有置顶，是游戏把系统分辨率改了。你把软件挪到左上角在全屏就知道了。

挪到左上角试了一下，好吧我知道了，非常感谢您

**Comment by LakeishaKowalczyk** [comment]
> 邮件现在已经发送到您的邮箱里了
你小子玩小黄游还怕别人知道，是吧

**Comment by kannaginomori** [comment]
> > 邮件现在已经发送到您的邮箱里了
> 
> 你小子玩小黄游还怕别人知道，是吧

第一，我玩不玩小黄油怕不怕别人知道都是我的私事，和你没有任何关系。你知道小明的爷爷为啥能活一百岁吗？因为他从不多管闲事。温馨提示你一下：多吃蔬菜身体好，少管闲事威信高。
第二，你根据什么判断我用邮件发游戏就是因为玩小黄油怕别人知道？你怎么凭空污人清白？我实话告诉你，我用邮件发游戏是因为：我朋友买了我用邮件发的那个全年龄游戏的正版光盘，他从光盘里面提取的游戏文件，他把游戏文件分享给我的时候，特意跟我说了不能公开传播但可以私下分享，所以我凭什么不能发私人邮件私下分享游戏？难道我要把他禁止公开的游戏文件用网盘链接公开在github上传播？我不知道别人会不会做这种缺德事，就算别人这么做了我也管不着，我反正做不出来这种事。
第三，我这么久之前的并且跟你毫无关系的回复，你都要特意回我一条，无凭无据地揣测我一句，你真是够无聊的。我招你惹你了？你这么毫无根据地揣测我，既不尊重我也对我很不礼貌，希望你能停止你的行为。
最后，退一万步说，就算我像你说的一样，我就是玩小黄油还怕别人知道，那又关你什么事？碍着你的眼了吗？用了你的电脑玩小黄油吗？我的私事和你没有任何关系，如果你不知道什么叫【各人自扫门前雪，莫管他人瓦上霜】，那我建议你打开百度搜索，百度一下你就知道。
我言尽于此，如果你还要继续回复我这一条，那我不会再理你，多说无益，你爱咋地咋地吧。

**Comment by LakeishaKowalczyk** [comment]
> 第一，我玩不玩小黄油怕不怕 ``````

哈哈哈哈，我天 
![图片](https://user-images.githubusercontent.com/14090545/210676641-5576e2bb-5241-42db-8e68-2e4290f3890b.png)
