### ISSUE TITLE
增强AI模型在线翻译设置功能

### ISSUE THREAD

**Issue by magicdmer** [HIllya51/LunaTranslator#750]
### Expected behavior 预期的功能

现在国内用户很多都是用的中转服务，中转服务一般是oneapi，oneapi支持通过openai一种接口规范访问其他各大厂商的模型，很方便。

建议可以专门弄个oneapi模式的AI设置栏目，可以自己无限添加各种模型支持，方便同时查看对比各个模型翻译。现在的设置最多只能同时设置两个AI大模型，使用“ChatGPT_非官方” 和 “ChatGPT”，无法自由添加

这样之后扩展就方便了，不需要出了一个新模型就要重新对接实现

**Comment by HIllya51** [comment]
没什么意义
