### ISSUE TITLE
A problem in recent versions after version 48 

### ISSUE THREAD

**Issue by Abo3loosh** [HIllya51/LunaTranslator#751]
### Version 程序版本

49 or +

### bug's screenshot 错误截图

The error is that the translation text appears outside the translation frame In Arabic language only 
![image-18](https://github.com/HIllya51/LunaTranslator/assets/170181236/9243b801-3f4e-487b-8b57-d5828a8d9cea)

### Reproduction steps 复现步骤

The translation appears on the right so I can't see it

**Comment by HIllya51** [comment]
fixed
