### ISSUE TITLE
Correction using translation results

### ISSUE THREAD

**Issue by noideaforeal** [HIllya51/LunaTranslator#753]
### Version 程序版本

v2.51.7

### bug's screenshot 错误截图

The replace translation doesn't replace whole word only. For example: replace 'her' to 'him' make some words like 'further' be replace as 'furthim' which is incorrect. It would be nice to add option to replace whole word instead.

### Reproduction steps 复现步骤

Step 1: text processing
Step 2: Translation optimization
Step 3: Correction using translation results

**Comment by HIllya51** [comment]
fixed https://github.com/HIllya51/LunaTranslator/commit/16ea48eb7feb825740397cd2c11f25051fa57592
