### ISSUE TITLE
Chatgpt develop doesn't auto sent text

### ISSUE THREAD

**Issue by scese250** [HIllya51/LunaTranslator#755]
### Version 程序版本

2.51.8

### bug's screenshot 错误截图

![DDTFaFN8Hy](https://github.com/HIllya51/LunaTranslator/assets/12405564/5502b4b8-d2c1-4728-9179-ec76d452b011)

![bug05nknk_jukKFrzvSH](https://github.com/HIllya51/LunaTranslator/assets/12405564/8dc89f69-b663-4742-959c-9dc6f6f9ece2)

### Reproduction steps 复现步骤

I don't know if it's on purpose since it's my first time using it but it doesn't send the text automatically

**Comment by HIllya51** [comment]
This interface is unstable, I suggest not using it, and I have no intention of continuing to maintain it
