### ISSUE TITLE
有關ラブピカルポッピー！的問題

### ISSUE THREAD

**Issue by a73420521** [HIllya51/LunaTranslator#757]
### Question 问题

ラブピカルポッピー！在讀取文本時，若遇到立繪變動，則會讀取一個空格，導致常常還沒翻譯完就讀取空格來翻譯，請問有辦法透過設定解決嗎?
![未命名](https://github.com/HIllya51/LunaTranslator/assets/87113124/0833432d-07d0-45bd-b0db-a77bff4ed952)

**Comment by HIllya51** [comment]
把这个空格过滤掉

**Comment by HIllya51** [comment]
给我看一下特殊码

**Comment by HIllya51** [comment]
好的。这个是单字符输出，不太好在提取器里过滤，那就只能这样了
