### ISSUE TITLE
更新到v2.52.1后sakura大模型设置闪退

### ISSUE THREAD

**Issue by YRSB** [HIllya51/LunaTranslator#758]
### Version 程序版本

v2.52.1

### bug's screenshot 错误截图

无

### Reproduction steps 复现步骤

打开翻译器，依次点击 设置——翻译设置——离线翻译——sakura大模型设置的图标，然后程序崩溃闪退。

**Comment by HIllya51** [comment]
debug截图。

**Comment by YRSB** [comment]
![屏幕截图 2024-05-21 191650](https://github.com/HIllya51/LunaTranslator/assets/32013347/90f3f209-1725-4433-9ab5-676b00765be5)

**Comment by HIllya51** [comment]
userconfig打包给我看一下

**Comment by YRSB** [comment]
[userconfig.zip](https://github.com/HIllya51/LunaTranslator/files/15389358/userconfig.zip)

**Comment by HIllya51** [comment]
已修复，等下更新
