### ISSUE TITLE
无法换行显示长文本的翻译

### ISSUE THREAD

**Issue by jijinganhe** [HIllya51/LunaTranslator#760]
### Version 程序版本

v2.52.4

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/161006461/c6a5ff3d-fccc-479e-9f35-37b5ef3dcfc3)

### Reproduction steps 复现步骤

2.47.1之后的版本，在开启固定窗口尺寸后会这样，希望能看一下谢谢

另外请问如何固定多个在线翻译的顺序，比如总是先显示谷歌翻译，再必应，后百度。
再另可以提供支付宝打赏吗，用不了微信支付

**Comment by HIllya51** [comment]
已修

**Comment by HIllya51** [comment]
本来就不能滚动。

**Comment by HIllya51** [comment]
能滚动才是bug，本来就没有设计滚动功能。
