### ISSUE TITLE
does not translate

### ISSUE THREAD

**Issue by 1Lucky11** [HIllya51/LunaTranslator#763]
### Version 程序版本

2.52.5

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/170607181/315130d9-2fa4-4280-8752-20e7915f6e3b)
![image](https://github.com/HIllya51/LunaTranslator/assets/170607181/2a2aaa43-5fff-44b6-8336-9e2f38802c96)

### Reproduction steps 复现步骤

just reprints the text

**Comment by HIllya51** [comment]
didn't you activate any translator?

**Comment by Kripozawr** [comment]
where can I find the text selection button?
![Снимок экрана 2024-05-23 172431](https://github.com/HIllya51/LunaTranslator/assets/170643960/dee79f62-955a-43a5-9b27-9fa90b6f783e)
