### ISSUE TITLE
Problem with deepl (develop) displaying "complete" instead of translation

### ISSUE THREAD

**Issue by iyuka888** [HIllya51/LunaTranslator#764]
### Version 程序版本

2.52.5

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/170653130/b225606f-47ee-43cc-ae44-a38c3c95b87d)

### Reproduction steps 复现步骤

First of all, thank you for your work in creating a great tool.

I have found the following issue using deepl (develop):

1. Game used to reproduce bug (but may not be limited to this one): "美衣菜△です！－Loveイチャ同居生活のススメ－"
2. Go to settings > translation settings > **'develop' tab** > check/activate 'deepl'
3. Link the game mentioned above and start
4. You will see chrome window's deepl tab will successfully translate, but Lunatranslator is not displaying the translation anymore with random behaviour including: it displays text "complete" instead of the translation OR it displays the original text sometimes OR it displays nothing.

This issue was reproduced with version 2.52.5, but started occuring about a week ago. 

Other translation platforms from the develop tab such as Google are working fine.

**Comment by HIllya51** [comment]
.6 has repaired it.
