### ISSUE TITLE
使用相關問題

### ISSUE THREAD

**Issue by ghuangjack** [HIllya51/LunaTranslator#766]
### Expected behavior 预期的功能

我下載資料夾後，並沒有在裡面看到執行的.exe檔；同時，如果想翻譯多張圖片、而非遊戲，可行嗎？

> 

>

**Comment by HIllya51** [comment]
你下错了。 https://github.com/HIllya51/LunaTranslator/releases/download/v2.52.6/LunaTranslator.zip
不能。
