### ISSUE TITLE
拉伸翻译器后，电脑会突然变“卡”

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaTranslator#767]
### Question 问题

这问题好几天了，一直不知道啥原因（每次遇到都要重启电脑），今天终于试出来了。拉伸翻译器后，电脑就是各种方面都卡。

**Comment by HIllya51** [comment]
看任务管理器。

**Comment by qscasdasd** [comment]
> 看任务管理器。

![QQ截图20240524144709](https://github.com/HIllya51/LunaTranslator/assets/167575533/64bcf981-d27d-4690-b553-c1ffd84c9957)

**Comment by HIllya51** [comment]
无法复现。你还是看看是不是你其他软件是不是有什么问题吧。别人都没有问题，只能是你环境的问题了。

**Comment by qscasdasd** [comment]
> 无法复现。你还是看看是不是你其他软件是不是有什么问题吧。别人都没有问题，只能是你环境的问题了。

实在不知道哪里的环境问题，拉伸翻译器的原因还是今天突然发现的，打开新的初始设置翻译器试了下也一样有问题，难受。

**Comment by HIllya51** [comment]
你把整个文件夹打包给我

**Comment by qscasdasd** [comment]
> 你把整个文件夹打包给我

打包给你大概率没用，上面说了用新下载的初始翻译器也会有这问题。https://mega.nz/file/kecCALKA#cCs8ghLTF4wCt5Kp4GMZNU6b7Y-AfpuWbOSW2SBT_3k（好像把翻译缓存也打包了，有点大）再说一下：用旧版翻译器都没这问题

**Comment by HIllya51** [comment]
复现不了。

**Comment by qscasdasd** [comment]
> 复现不了。

哎，算了吧，我以后自己注意下这问题吧
