### ISSUE TITLE
TGW翻译刷新后其他翻译会消失

### ISSUE THREAD

**Issue by Z9wind** [HIllya51/LunaTranslator#768]
### Version 程序版本

2.52.6

### bug's screenshot 错误截图

https://pan.quark.cn/s/6c2c12f02393
直接录屏了一下更直观
![5](https://github.com/HIllya51/LunaTranslator/assets/107527857/57318407-7b62-4ea8-acdd-47e2e8b874eb)
如图是TGW的设置，我仅仅只关闭了流式，别的都没动
补充一个录屏：https://pan.quark.cn/s/c6117217960f ←翻译历史也只显示一句，但按一下重新翻译会显示所有
### Reproduction steps 复现步骤

进行翻译时等待TGW翻译，TGW翻译完成后其他翻译消失

**Comment by HIllya51** [comment]
@https://github.com/HunterShenSmzh

**Comment by HIllya51** [comment]
@HunterShenSmzh

**Comment by HunterShenSmzh** [comment]
收到，我看一下情况。

**Comment by HunterShenSmzh** [comment]
@Z9wind 能提供一下luna的版本号么，我和作者都没复现出这个问题。

**Comment by HunterShenSmzh** [comment]
@Z9wind 我和作者都没复现出这个问题，我思考了一下也许是其他翻译器影响？能否提供更多信息。

**Comment by HIllya51** [comment]
你把整个文件夹打包给我

**Comment by Z9wind** [comment]
> 你把整个文件夹打包给我

我用夸克网盘分享了「LunaTranslator.zip」，点击链接即可保存。打开「夸克APP」，无需下载在线播放视频，畅享原画5倍速，支持电视投屏。
链接：https://pan.quark.cn/s/efaf415610f7
麻烦大大了！

**Comment by HIllya51** [comment]
别发网赚盘行吗。。。

**Comment by Z9wind** [comment]
> 别发网赚盘行吗。。。

我赚什么呢？酷安大家都讨厌百度和诚通，很多人都用夸克和阿里，我还特地穿夸克，我百度夸克都有会员我会想要赚什么？我要赚你钱我就不会给你赞助了

**Comment by HIllya51** [comment]
我又没说你靠这个赚钱，我只是不想下这个垃圾网盘，或者说我讨厌所有需要登录/下载客户端的网盘，包括百度，而这个夸克是比百度更恶心的网盘。

**Comment by HIllya51** [comment]
我不知道酷安怎么说得，但很多gal论坛都是把诚通、夸克、阿里都归到网赚盘里的。我说网赚盘只是说这个网盘很垃圾，而且是公认的垃圾，不是说你怎么样，如果感到冒犯，那我说对不起了。

**Comment by HIllya51** [comment]
![屏幕截图 2024-05-26 193332](https://github.com/HIllya51/LunaTranslator/assets/101191390/7b7c8fba-f6d1-4cf9-9956-07cbbefe25ad)

丢到虚拟机里跑了一个小时，就这样，hh。

**Comment by Z9wind** [comment]
那是我理解错了，不过下次大大你可以跟我说你要哪个盘。然后我试了一天发现有可能是"收到翻译结果时才刷新"这个功能的问题，我原先一直都是开启状态，刚刚突发奇想把这个关了玩了半小时没有出现翻译消失的问题。

**Comment by HIllya51** [comment]
onedrive/谷歌/mega是最好的，或者其他一些国外不限速盘，实在不行百度也行。

我测试过这个设置了，好像和这个没什么关系。

不过有个可能就是，如果你是从旧版本一路升级上来的，可能有未知的累积bug，保留用户数据（userconfig/cache/translation_record）后删了重下或许就能解决（好多人都这样解决过bug）
