### ISSUE TITLE
使用翻译器时会把游戏对话框上说话人的人们翻译成中文并有识别不出来的字

### ISSUE THREAD

**Issue by akkkca** [HIllya51/LunaTranslator#769]
### Version 程序版本

v2.52.7

### bug's screenshot 错误截图

![微信图片_20240524232733](https://github.com/HIllya51/LunaTranslator/assets/170782628/70e83263-a136-4bcf-8189-01668f22aa24)
![微信图片_20240524232806](https://github.com/HIllya51/LunaTranslator/assets/170782628/3a7d9839-5d61-43d0-ac71-2c79d2e2cf86)

### Reproduction steps 复现步骤

使用的是HOOK，翻译的时候会把游戏里对话框上的人名翻译成中文，且会出现识别不出来的情况，名字里会出现口。文本框里的文字都不会变成中文，只有文本框上表示正在说话人的名字会变成中文。
怎么调整可以让名字保持英文不变成中文？

**Comment by akkkca** [comment]
![image](https://github.com/HIllya51/LunaTranslator/assets/170782628/8bc175bf-cf09-483d-a939-c3b0bf22c190)
原本应该是这样

**Comment by HIllya51** [comment]
你把内嵌翻译关了啊

**Comment by akkkca** [comment]
关掉了
