### ISSUE TITLE
1.29 tts问题

### ISSUE THREAD

**Issue by onisaki92** [HIllya51/LunaTranslator#77]
刚更新1.29后TTS无法使用了..点击没反应..各种TTS的选项也是空白点击没反应除了voicevox可以选，但是也是没语音。换回旧版本就没问题..旧版本是1.8

**Comment by HIllya51** [comment]
截个图看一下

**Comment by csquya** [comment]
从1.26.10就开始这个问题了， 1.26.9是好的。以后版本的在线TTS都不行，除了离线的，其实离线的也没有选择，下拉菜单只有1个可选。 而且很多翻译api失效了， 比如 pagago， deepl等（排除网络问题，因为1.26.9是可以的）。
我试了很多次才确定这些bug是从1.26.10开始的。

**Comment by HIllya51** [comment]
> 从1.26.10就开始这个问题了， 1.26.9是好的。以后版本的在线TTS都不行，除了离线的，其实离线的也没有选择，下拉菜单只有1个可选。 而且很多翻译api失效了， 比如 pagago， deepl等（排除网络问题，因为1.26.9是可以的）。 我试了很多次才确定这些bug是从1.26.10开始的。

除了这两个，还有哪个翻译失效了？

**Comment by HIllya51** [comment]
> 从1.26.10就开始这个问题了， 1.26.9是好的。以后版本的在线TTS都不行，除了离线的，其实离线的也没有选择，下拉菜单只有1个可选。 而且很多翻译api失效了， 比如 pagago， deepl等（排除网络问题，因为1.26.9是可以的）。 我试了很多次才确定这些bug是从1.26.10开始的。

papago修复了，deepl需要设置代理。

**Comment by onisaki92** [comment]
个人测试了至今，除去私人API,用过VPN 试也无效的API有
百度(重来没成功过)，火山，byte
有时有效有时没反应，然后一两句后又不能的API
Yeekit,
ichiba,
papago,
Deep L.
Bing.
Tx
Byte.
Qqimt.


HIllya51 <

HIllya51 ***@***.***> 于 2022年11月20日周日 01:40写道：

**Comment by onisaki92** [comment]
截图太大发送不到不懂下面有收到吗？

HIllya51 ***@***.***> 于 2022年11月19日周六 23:58写道：

**Comment by onisaki92** [comment]
HIllya51 ***@***.***> 于2022年11月19日周六 23:58写道：

**Comment by onisaki92** [comment]
你要win TTS截图对吗？

HIllya51 ***@***.***> 于2022年11月19日周六 23:58写道：

**Comment by HIllya51** [comment]
呃 我试了都没问题啊

**Comment by HIllya51** [comment]
我发了个debug版本，你试一下。

**Comment by onisaki92** [comment]
1.29.2吗？

**Comment by onisaki92** [comment]
baidu第一次成功刷新又不能了..

Oni Saki ***@***.***> 于2022年11月20日周日 22:19写道：

**Comment by HIllya51** [comment]
放一下失败时的控制台截图。
