### ISSUE TITLE
JSON预翻译无法正常匹配，始终卡在同一个翻译中

### ISSUE THREAD

**Issue by yihaoyu** [HIllya51/LunaTranslator#770]
### Version 程序版本

2.52.7

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/46690913/11452a5f-eba4-478a-8192-6b2a489dcfd4)

### Reproduction steps 复现步骤

0. 挺久之前用的时候没问题，JSON格式参照的[这里](https://github.com/HIllya51/LunaTranslator/issues/212)。已尝试删除文件夹后重新下载新版，无效。翻译器配置：
[config.json](https://github.com/HIllya51/LunaTranslator/files/15442308/config.json)。

1. 在“游戏设置”或总的“翻译设置”下的"预翻译“中设置JSON翻译文件（文件路径全英文）。JSON文件是通过汉化组的对照文本制作的：
[CROSSCHANNEL_JP_CN.json](https://github.com/HIllya51/LunaTranslator/files/15442333/CROSSCHANNEL_JP_CN.json)

2. 游戏中目前不论原文是什么都会显示同一句且不匹配的“翻译”。[如上图](https://github.com/HIllya51/LunaTranslator/assets/46690913/d7cc8e4d-d415-4d08-ae69-957e1210f50d)。相似度设置尝试过：10，80，90，100%。
2. 5 若勾选”使用翻译缓存“设置，会在JSON翻译后显示错误信息：AttributError 'NoneType' Object has no attribute 'put'。[如图](https://github.com/HIllya51/LunaTranslator/assets/46690913/1cb03abe-d667-4558-ac83-b971f064f209)
3. 手动删除cache文件夹重启后仍会出现上述情况（”显示错误信息“始终是勾选的状态）。
4. 在JSON文件的该条中文翻译处未发现明显的异常。

另外不知可否顺便问一下（不好的话我删了再开一个Q&Aissue），
今天刚开始用Anki做卡片学日文，外国目前的做法比较繁琐，是通过将hook中的语句复制到剪切板，然后用Clipboard Inserter类的插件将文本发到一个空网页，再从网页通过Anki的浏览器插件制作卡片。我看到在”文本输入“下的”文本输出“选项中有”WebSocket"的设置，不知道是否能用来稍微简化下操作。另外不知是否有比较合适本翻译器的Anki卡的模板可以推荐的。

**Comment by HIllya51** [comment]
已修

**Comment by HIllya51** [comment]
![屏幕截图 2024-05-25 171856](https://github.com/HIllya51/LunaTranslator/assets/101191390/57ca92da-7405-4c25-abb1-ac2395b607b0)

内置anki模板。
