### ISSUE TITLE
建议增加配置文件按照不同的游戏导出和导入功能

### ISSUE THREAD

**Issue by jeshs** [HIllya51/LunaTranslator#771]
### Expected behavior 预期的功能

每个游戏的配置都不一样，每次打开luna都要进行一大堆配置，包括python脚本、正则表达式、简单字符串替换、英文日文切换、翻译器、代理、以及各种其它设置等，需要耗费大量时间，还经常忘记某个配置。因此希望可以导出所有配置到一个文件或文件夹，每个游戏单独一份配置，使用时可以导入这些配置，这些会方便很多

**Comment by HIllya51** [comment]
连接到游戏之后是可以保存当前游戏的文本处理方法的。至于语音、翻译、代理，没有特化的必要。

![屏幕截图 2024-05-25 173650](https://github.com/HIllya51/LunaTranslator/assets/101191390/edb72f71-b06f-4ac7-a836-4cee5c6f232c)
