### ISSUE TITLE
使用develop的deepl在很快的刷新文本的时候会只显示complete

### ISSUE THREAD

**Issue by hkyear** [HIllya51/LunaTranslator#772]
### Version 程序版本

2.52.6

### bug's screenshot 错误截图

![Snipaste_2024-05-26_05-59-37](https://github.com/HIllya51/LunaTranslator/assets/106646630/b0761b64-0f1b-4fe4-ab70-6f0480a67f87)

### Reproduction steps 复现步骤

快速刷新文本的时候会只回复complete，然后不管怎么刷新文本都只回复这个，在直接查看它打开的浏览器的网页翻译的时候发现是正常输入文本翻译的，网页也正常翻译好了，但是结果没有在文本框反应出来，而是输出complete。在设置里重新开关develop的deepl翻译开关可以恢复正常，但一旦文本刷新过快又只输出complete

**Comment by HIllya51** [comment]
已修
