### ISSUE TITLE
Doesn't work anymore in windows 7 due to winsharedutils32.dll

### ISSUE THREAD

**Issue by iu3kxa** [HIllya51/LunaTranslator#776]
### Version 程序版本

3.0.1 and upper

### bug's screenshot 错误截图

open and immediately close, not able to determine exact error except for what dll cause crash

### Reproduction steps 复现步骤

replacing winsharedutils32.dll 3.0.2.0 with winsharedutils32.dll 3.0.0.0 from 3.0.0 get lunatranslator to start, but i didn't check if thi cause other issues

**Comment by HIllya51** [comment]
Very strange bug. Repaired.

**Comment by iu3kxa** [comment]
Confirming that both 32bit and 64bit had the issue and both works now, thanks.
When i figure it what happen exactly I will report later a strange, easily wakaroundable bug, that cause an error in python3.dll;
it always happen on same specific windows installs and affect every version of lunatranslator;
i suppose there are certain conditions of the environments that trigger the issue and doesn't happen in the moment i try to debug it.

**Comment by iu3kxa** [comment]
I have this problem again, except that replacing winsharedutils32.dll doesn't work anymore, i get a bunch of python error; unfortunately i don't know from what version happened, since i jumped from 3.0.2 to 3.2.0

**Comment by HIllya51** [comment]
no any error found.

**Comment by HIllya51** [comment]
😅Why don't you post a screenshot? Instead of saying a bunch of meaningless words. How can I know what’s wrong with you if you don’t post screenshots? Do you want me to tell your fortune?

![屏幕截图 2024-06-05 182813](https://github.com/HIllya51/LunaTranslator/assets/101191390/eaa2c5fe-0c5e-45b2-a94d-f97f0666add2)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/issues/799
fixed.

**Comment by iu3kxa** [comment]
My bad; the issues happening on win7 that i mentioned, have a impact so low that o don't think to deserve attention and often i'm not even able to reproduce them when i need;

like the main panel going offscreen if i change the resolution of the secondary monitor, and the desktop is located on the left; i just close the program from the task manager and relaunch.

Or the debug windows that doesn't open on the debug version; i discovered only yesterday that happen when the 3dvision is enabled even if driver is in 2d mode.

Only one issue i was able to reproduce:
![error in python3 dll](https://github.com/HIllya51/LunaTranslator/assets/55386281/e6387736-0926-42b0-86a0-06db543f8031)
This error, win7 only,  happen casually when opening the exe from windows explorer or other filemanagers. 
I was able to 'always' reproduce the error by launching the exe ffom inside a total commander panel (demo version and registered), but if launch from a link o from .bat the error never happen.

regarding the previous problems, i tested version 3.2.3 and it work well, thank you.
