### ISSUE TITLE
problem of selecting an arbitrary area for OCR

### ISSUE THREAD

**Issue by welcomesun** [HIllya51/LunaTranslator#777]
### Version 程序版本

v3.0.3

### bug's screenshot 错误截图

Hi, In the new Luna v3.0.3 , it is not possible to select an area outside the translation window. The cross indicating the capture status simply disappears.

*in the earlier build there is no such problem. 

### Reproduction steps 复现步骤

![111](https://github.com/HIllya51/LunaTranslator/assets/14134409/e129065b-4ffb-49c2-bddd-27aa2946a17e)

**Comment by HIllya51** [comment]
fixed in 3.0.4
