### ISSUE TITLE
关于游戏翻译缓存的问题

### ISSUE THREAD

**Issue by k2250761** [HIllya51/LunaTranslator#778]
### Question 问题

因为我用的是Sakura本地模型，所以不想用到翻译缓存，因为会影响模型的推理、翻译质量。
但是我基本把翻译设置中的，使用翻译缓存勾掉，还是会调用到翻译缓存。
现在只能每次重新启动软件时，把之前翻译缓存的文件删掉才能不影响翻译的质量。
请问能有什么好的方法解决一下吗

**Comment by HIllya51** [comment]
sakura如果命中缓存觉得质量不行，可以手动点重新翻译，重新翻译不会调用缓存。
