### ISSUE TITLE
无法打开游戏设置

### ISSUE THREAD

**Issue by JiaChen-Zeng** [HIllya51/LunaTranslator#781]
### Version 程序版本

3.0.6

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/3676278/f2f67dfd-2bf7-467e-8c05-0ba177216cd5)

### Reproduction steps 复现步骤

第一次打开游戏设置，然后关闭，再想打开就无法打开了

**Comment by HIllya51** [comment]
截图就截全。

**Comment by JiaChen-Zeng** [comment]
就是指我说的是这个按钮的意思，没有反应，没有视觉上的症状

A quick update on the go.
移動中に取り急ぎご連絡まで。

**Comment by HIllya51** [comment]
![屏幕截图 2024-06-01 084352](https://github.com/HIllya51/LunaTranslator/assets/101191390/92b6af83-f3bc-404f-b0b7-6182fa51c054)
运行_debug，给我看log
