### ISSUE TITLE
功能请求：将翻译自动发送到剪贴板，以及用快捷键一键复制翻译到剪贴板

### ISSUE THREAD

**Issue by jpACGlover** [HIllya51/LunaTranslator#782]
### Expected behavior 预期的功能

![截图_20240601132235](https://github.com/HIllya51/LunaTranslator/assets/171327971/1ef52835-81f1-4d2d-bf5f-6a825d526a91)
1、在玩英文游戏的时候想顺便学习一下日语，这时将LunaTranslator设定翻译为英文转日文，翻译出来的日语如果能自动发送到剪贴板的话，就可以将日文顺便传递给https://github.com/ks233/ja-learner这个应用程序进行汉字假名标注和形态分析，进行英日双语一起学习。
2、添加一个快捷键用于一键发送翻译到剪贴板，这样可以用于在任何聊天程序里输入中文并发送给LunaTranslator，然后LunaTranslator设定翻译为转成各种外语再发送回任何聊天窗口，方便在各种程序里用外语进行交流。

**Comment by HIllya51** [comment]
2加了
