### ISSUE TITLE
Automatically does not send text to gpt chat. 

### ISSUE THREAD

**Issue by allebar** [HIllya51/LunaTranslator#783]
### Version 程序版本

last

### bug's screenshot 错误截图

![dfdfs](https://github.com/HIllya51/LunaTranslator/assets/75815491/592c4b84-9c25-4eae-a935-2471946a8230)

### Reproduction steps 复现步骤

While I am using the GPT translation via browser, the text is not sent automatically, I have to press ENTER myself

**Comment by allebar** [comment]
In addition, the translation to GPT itself is not displayed in the program window

**Comment by HIllya51** [comment]
I no longer intend to support dev-ChatGPT translation. Please use the API.
﻿
