### ISSUE TITLE
在自定义翻译的Python环境中希望附带requests库

### ISSUE THREAD

**Issue by YWtheGod** [HIllya51/LunaTranslator#784]
### Expected behavior 预期的功能

在自定义翻译的Python环境中缺少requests库，这个库在调用云端翻译API时经常用到，希望能够内建附带
自定义翻译的Python脚本被加载调用后再修改源码似乎不能立即生效，可否添加重启Python环境的功能?

**Comment by HIllya51** [comment]
谁给你说没有requests的，不然其他api怎么访问的
文本处理立即生效还有点意义，翻译立即生效有什么意义吗，难道不应该你调试好了再复制进去吗。。

**Comment by YWtheGod** [comment]
的确是没有requests
我是选用了彩云api的翻译方法发现没反应，才去选择自己写一个脚本调用彩云api，然后发现没有requests
![屏幕截图 2024-06-01 202155](https://github.com/HIllya51/LunaTranslator/assets/41936459/3d9b7a36-90d2-4845-9355-b9e667549f22)

**Comment by HIllya51** [comment]
sys.path.append('./LunaTranslator/network/winhttp')，我自己实现的。
