### ISSUE TITLE
翻译器最小化后，当翻译成功时依然在游戏画面上绘制翻译器界面

### ISSUE THREAD

**Issue by YWtheGod** [HIllya51/LunaTranslator#785]
### Version 程序版本

3.0.6

### bug's screenshot 错误截图

![屏幕截图(1)](https://github.com/HIllya51/LunaTranslator/assets/41936459/75e9c03e-30c3-47da-bd19-4901de17c43f)

### Reproduction steps 复现步骤

在对Unity引擎游戏进行翻译时，成功用Hook方式获取到文本，成功设置了内置翻译替换了译文和字体
已经不需要在翻译器窗口内显示译文了，故此将翻译器窗口最小化。
但在每次新文本出现并成功翻译时，带新译文的翻译器窗口依然在游戏画面上被绘制，仅仅是绘制翻译器窗口，上面的图标按钮都是不可点击的，真实的翻译器窗口依然在最小化状态，需要还原窗口才可以进行点击操作。

**Comment by HIllya51** [comment]
关掉自动隐藏
