### ISSUE TITLE
Google OCR in Luna

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#786]
### Expected behavior 预期的功能

Is it possible to integrate Google OCR in Luna? As far as I know its free, but main advantage of it is ability to recognize text in low-resolution images. 
For now I am only able to use it in Google Docs when open my image as text. Would be nice to have it in Luna.

**Comment by HIllya51** [comment]
<img width="473" alt="屏幕截图 2024-06-01 225224" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/34eec622-202d-4c44-b29b-54d073dbde4e">

**Comment by Farooq87** [comment]
> <img alt="屏幕截图 2024-06-01 225224" width="473" src="https://private-user-images.githubusercontent.com/101191390/335809133-34eec622-202d-4c44-b29b-54d073dbde4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjY4MzksIm5iZiI6MTcxNzI2NjUzOSwicGF0aCI6Ii8xMDExOTEzOTAvMzM1ODA5MTMzLTM0ZWVjNjIyLTIwMmQtNGM0NC1iMjliLTU0ZDA3M2RiZGU0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxODI4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGZkOGYyNDYzZmZmMjk0MGMyYzgxMjYxYWVjZmJjOWQ0NTNjMmVlZTk3NDM0YzY3YjY4M2JmOTI3YzM3ZDg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M-itacmN3nk3lZaQkZ9BA_zUNClbKg9k_Um6vGenXqQ">

I have old version of Luna presumably. Is googlecloudvision OCR free to use?

**Comment by HIllya51** [comment]
i dont know.
