### ISSUE TITLE
ChatGPT (Develop) 'Send' button automatisation 

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#789]
### Expected behavior 预期的功能

Thanks for adding ChatGpt free option in develop section. It works just fine except one little feature which I kindly ask you to add.
OCRed text automatically being sent to ChatGPT in browser with clear command to translate. Could you please also program this to press 'Send' button automatically.
Otherwise user has to go to browser window each time to do it manually. This is tiresome.

**Comment by HIllya51** [comment]
I no longer intend to support dev-ChatGPT translation. Please use the API.

**Comment by Farooq87** [comment]
API is not free, Not many people can afford to use it without limits. dev-ChatGPT is the best oprion.
