### ISSUE TITLE
请问能加一个（百度图片翻译文字识别）OCR接口吗？

### ISSUE THREAD

**Issue by jpACGlover** [HIllya51/LunaTranslator#790]
### Expected behavior 预期的功能

百度图片翻译文字识别每月都有1万次免费的OCR额度，刚才用另外一个软件测试了觉得OCR精度也挺好的。
![截图_20240602231557](https://github.com/HIllya51/LunaTranslator/assets/171327971/556c2d5e-cab3-464c-86e5-2f926d9201d7)
官网申请地址 https://fanyi-api.baidu.com/product/22

**Comment by asukaminato0721** [comment]
api 定义 <https://fanyi-api.baidu.com/product/223>

**Comment by HIllya51** [comment]
![Uploading 屏幕截图 2024-06-03 021106.png…]()

给我个测试密钥

**Comment by HIllya51** [comment]
![屏幕截图 2024-06-03 021106](https://github.com/HIllya51/LunaTranslator/assets/101191390/fb954231-3999-47a6-9dba-eeafc8444240)
给我个测试密钥

**Comment by jpACGlover** [comment]
百度图片翻译文字识别OCR
20220802001290760
PyDACBhPjziEgCPUAfmR
