### ISSUE TITLE
Issue with text filtering

### ISSUE THREAD

**Issue by NekoIriyaRu** [HIllya51/LunaTranslator#791]
### Version 程序版本

3.0.1

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/171213503/d7b87000-f5fe-46d7-be2c-325b631abfa9)

### Reproduction steps 复现步骤

The program does a poor job of filtering English text.

**Comment by HIllya51** [comment]
？

**Comment by NekoIriyaRu** [comment]
Here's another example, the program does a poor job of filtering text in the English version of the game, even with different filter settings. - v[195](https://vndb.org/v195)
 
![image](https://github.com/HIllya51/LunaTranslator/assets/171213503/27379515-5a0e-4243-b2eb-96448ee0a22a)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaHook/issues/new?assignees=&labels=enhancement&projects=&template=01_game_request.yaml
