### ISSUE TITLE
Game used with Magpie reverts to original size

### ISSUE THREAD

**Issue by blastentwice** [HIllya51/LunaTranslator#793]
### Version 程序版本

3.1.4

### bug's screenshot 错误截图

Game used with Magpie reverts to original size

### Reproduction steps 复现步骤

When the Lunar translator window is pressed or moved on top of a game with Magpie, the game shrinks back to it's original size. This occurs with both external Magpie and the one built in to Magpie. 

This issue does not occur with version 2.52.6.

**Comment by HIllya51** [comment]
fixed
