### ISSUE TITLE
String repeatedly copied in rpgmaker games

### ISSUE THREAD

**Issue by Goon33** [HIllya51/LunaTranslator#795]
### Question 问题

![huh](https://github.com/HIllya51/LunaTranslator/assets/171668224/342cc9b2-4542-4978-9ef9-fc69492d862c)
When trying to use LunaTranslator to grab text from rpgmaker games for sugoi it copies this to clipboard in-between the real text 4+ times, I assume I'm doing something wrong but seemingly it wont stop even if all threads are turned off

**Comment by HIllya51** [comment]
it use clipboard to send the text from javascript of rpgmaker to cpp of LunaHook. so if the game engine is rpgmaker/tyranoscript, don't use other program which monitor the clipboard.
