### ISSUE TITLE
Q: chatgpt 离线怎么用

### ISSUE THREAD

**Issue by asukaminato0721** [HIllya51/LunaTranslator#797]
### Question 问题

默认打开是这个。

![XX`418DUXUVG3F_UW2_NGU0](https://github.com/HIllya51/LunaTranslator/assets/30024051/d761dded-8592-4d90-9d08-9a03030ce4d2)

---

需要在本地或者 ~~ssh 转发端口到本地(能看懂这句话那不需要继续了)~~

仅提供一种解法。别的兼容 gpt api 的都可以。

下载 ollama <https://www.ollama.com/>

以 llama3 举例。

<https://www.ollama.com/library/llama3>

下载好模型，后台跑起来后，在

![image](https://github.com/HIllya51/LunaTranslator/assets/30024051/915f17c5-27a4-465f-9b4e-7a547ba5029f)

改成自己在跑的模型，端口改成对应的。就行了。

**Comment by HIllya51** [comment]
建议使用 https://github.com/SakuraLLM/SakuraLLM/wiki

使用llama.cpp部署，最简单。然后使用sakura大模型的专用接口，里面有一些模型作者写的prompt。
