### ISSUE TITLE
Sites with translation in the Develop section open in the browser only if there is a check mark initially and this is the first launch of the program, this function does not work in real time.

### ISSUE THREAD

**Issue by allebar** [HIllya51/LunaTranslator#798]
### Version 程序版本

last

### bug's screenshot 错误截图

![Uploading iasd.png…]()

### Reproduction steps 复现步骤

Sites with translation in the Develop section open in the browser only if there is a check mark initially and this is the first launch of the program, this function does not work in real time.

**Comment by HIllya51** [comment]
![屏幕截图 2024-06-05 183348](https://github.com/HIllya51/LunaTranslator/assets/101191390/d819f252-2746-40ea-9d6c-d4a9edef155e)
