### ISSUE TITLE
crashes when hovering the mouse over any control

### ISSUE THREAD

**Issue by shiinamashiro20** [HIllya51/LunaTranslator#799]
### Version 程序版本

3.2.2.0

### bug's screenshot 错误截图

![изображение](https://github.com/HIllya51/LunaTranslator/assets/171804607/a7ae3dc6-46fb-48f3-9773-c7cdcbbf123e)
![изображение](https://github.com/HIllya51/LunaTranslator/assets/171804607/2d016112-ef24-457f-a244-068f0607d167)

### Reproduction steps 复现步骤

crashes when hovering the mouse over any control
windows 7 32-bit

**Comment by HIllya51** [comment]
run LunaTranslator_debug.exe and show me the log.

**Comment by shiinamashiro20** [comment]
![изображение](https://github.com/HIllya51/LunaTranslator/assets/171804607/400e0b43-fef6-42fe-9c6f-0e102c66436e)
![изображение](https://github.com/HIllya51/LunaTranslator/assets/171804607/8d0413bb-f117-4844-807d-415a3a750b0a)


the same thing, when you hovering at any object - the program crashes

**Comment by HIllya51** [comment]
I dont know why. Is 64 bit version runable?

**Comment by shiinamashiro20** [comment]
I'm sorry, but I don't have 64-bit, only 32-bit.
downloaded version: v3.22 LunaTraslator_x86.zip

I learned about this program for the first time only today, that it can translate visual novels using text reading from the screen and translation.

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/releases/download/v3.2.2/LunaTranslator.exe

test 64 bit version

**Comment by shiinamashiro20** [comment]
I also tried running LunaTranslator_x86 as an administrator, but the program crashes the same way.

**Comment by HIllya51** [comment]
what? are you using 32-bit windows?

**Comment by shiinamashiro20** [comment]
yes

**Comment by HIllya51** [comment]
Oh my goodness, I really didn't expect anyone to be using a 32 bit system. I tested it on a 64 bit Win7 without any issues. Afterwards, I will find a 32 bit virtual machine to test.

**Comment by shiinamashiro20** [comment]
Thank you, sorry for coming here with errors; xD

**Comment by HIllya51** [comment]
![屏幕截图 2024-06-05 203316](https://github.com/HIllya51/LunaTranslator/assets/101191390/7e980cf0-1124-465a-8423-04180ac580fc)

tested on win7-sp1-32，no error found.

**Comment by HIllya51** [comment]
oh shit. it only few times crash and most time works fine, so i don't know why.

**Comment by HIllya51** [comment]
Should be fixed, try it now.

**Comment by shiinamashiro20** [comment]
thank you, everything works!;3♡
