### ISSUE TITLE
转区运行游戏后识别不到进程

### ISSUE THREAD

**Issue by chuanqi80** [HIllya51/LunaTranslator#8]
游戏不转区运行不了，转区了识别不到，窗口无法识别到，用转区管理员运行也无法识别

**Comment by HIllya51** [comment]
用的什么转区工具？我locale emulator可以的啊

**Comment by HIllya51** [comment]
https://i.postimg.cc/t4HSSXXm/2022-10-06-183303.jpg
emmm，我win10系统，用的le转区，没遇到问题啊。。。
