### ISSUE TITLE
点击打开设置无反应

### ISSUE THREAD

**Issue by lhj5426** [HIllya51/LunaTranslator#80]
从124版本到129全部版本 点打开设置无反应 什么都没有发生
123没问题 系统 WIN 21H2

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/202903981-b79468a3-6a9f-4990-a209-7cdf8909ad54.png)
这个之后的版本 全部 是全部 都打不开设置
![image](https://user-images.githubusercontent.com/30548000/202904002-b3961b80-f777-44ff-b8cf-a1fca8709d32.png)
点这个 齿轮或者任务栏右键里的设置都无任何反应

**Comment by HIllya51** [comment]
。。。21h2上测试未发现任何问题。。。
1、可能旧版本userconfig兼容性出了点问题，把他剪切走在打开试试？
2、可能是你装的一些软件存在冲突？

**Comment by lhj5426** [comment]
> 。。。21h2上测试未发现任何问题。。。 1、可能旧版本userconfig兼容性出了点问题，把他剪切走在打开试试？ 2、可能是你装的一些软件存在冲突？

都是新解压试的 无反应
 如果是冲突。。。 这装的软件可多了。。。 好尴尬
![image](https://user-images.githubusercontent.com/30548000/202905963-49785e2b-ee69-4c93-8fe9-b0acff4abcf5.png)

**Comment by HIllya51** [comment]
我放了个debug版本，你下一下试试把。

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/202927226-a57e4984-b587-49e9-9f0f-61496b0e79df.png)
 涛声依旧

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/202927338-0b65f998-07b9-4000-a855-07929eaa1d69.png)
好像是 系统缺东西？

**Comment by HIllya51** [comment]
不是 你点设置再看一下

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/202977894-11199dd7-23f4-4468-bf43-5ec2943ac1f8.mp4

点不开 涛声依旧

**Comment by lhj5426** [comment]
O:\dupan\LunaTranslator_debug\LunaTranslator\LunaTranslator\js2py\constructors\time_helpers.py:10: UserWarning: Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time
  warnings.warn(
感觉好像是缺什么东西？

**Comment by HIllya51** [comment]
和这个没有关系。
涛声依旧是啥？
你解压到另外的文件夹试一下啊，不要有旧的userconfig。。。

**Comment by lhj5426** [comment]
> 和这个没有关系。 涛声依旧是啥？

涛声依旧 就是依然不好使。。。。

基本解释涛声依旧　　涛，指海涛；声：声音；涛声：海涛的声音；依旧：和以前一样，没有改变，又回到原来了。表面上是指海涛的声音和以前一样，还是那个样子，深层次是指某件事情经过一段波折，到最后波折平息了，事情又回到了以前的状态或样子。

**Comment by lhj5426** [comment]
那为啥不好使呢= =124只会 开发的时候增加了什么东西么 123最后一个好使的版本

**Comment by lhj5426** [comment]
我电脑里的Python 因为要用
这个OCR https://github.com/kha-white/manga-ocr
所以  版本停留在3.9

**Comment by HIllya51** [comment]
和这个没关系，不用本地python的。

**Comment by lhj5426** [comment]
挺烦的 就我反馈了 可能就我有这个问题 ？但是我找不到问题的根源

**Comment by HIllya51** [comment]
我换了几个系统试了(win10 win1121h2 win7)，都没有任何问题。。。你这我真没办法了。😂

**Comment by lhj5426** [comment]
哈哈 行吧 反正我主要是翻译漫画 只要翻译引擎和剪切板功能就够了
不更新其实也没事哈哈 辛苦了  下次换系统再更新试试

**Comment by lhj5426** [comment]
我按照提示在本地安装了 这个也不行 如果不是调用本地的py 是不是软件的安装包里的缺少？
![image](https://user-images.githubusercontent.com/30548000/202990443-75be1823-e746-4f81-8b1b-db4c5873e04d.png)

**Comment by HIllya51** [comment]
和这个没任何关系，这个是用来调用js的库。而且软件又不会用你本地的python你装这个有啥用啊？

**Comment by GiGaFotress** [comment]
1.28升级到1.30,修改设置中的翻译选项后,退出再进软件,也是复现设置窗口再也打不开问题,
之前遇到过因为配置文件未删除,软件报QTcore错误退出,这次删除配置文件也不行.系统win10 22H2

**Comment by HIllya51** [comment]
> 1.28升级到1.30,修改设置中的翻译选项后,退出再进软件,也是复现设置窗口再也打不开问题, 之前遇到过因为配置文件未删除,软件报QTcore错误退出,这次删除配置文件也不行.系统win10 22H2

修改了哪些配置？能否把配置文件发我一份？

**Comment by GiGaFotress** [comment]
> > 1.28升级到1.30,修改设置中的翻译选项后,退出再进软件,也是复现设置窗口再也打不开问题, 之前遇到过因为配置文件未删除,软件报QTcore错误退出,这次删除配置文件也不行.系统win10 22H2
> 
> 修改了哪些配置？能否把配置文件发我一份？

客户端已经做了反复删除处理,现在只有打不开的现象还在.

**Comment by HIllya51** [comment]
> 链接：https://pan.baidu.com/s/1QD7TxkqYT910ZzA-8XYlBg?pwd=pvjm 提取码：pvjm 打不开的客户端我打了个包,不确定在你的环境是否还能复现

。。。完全正常运行 
win10 20H2 或许是系统的问题 我装个虚拟机试试

**Comment by HIllya51** [comment]
> 链接：https://pan.baidu.com/s/1QD7TxkqYT910ZzA-8XYlBg?pwd=pvjm 提取码：pvjm 打不开的客户端我打了个包,不确定在你的环境是否还能复现

仍然未发现任何问题，22H2虚拟机中完全正常运行。。。。。。。。。

**Comment by HIllya51** [comment]
> 链接：https://pan.baidu.com/s/1QD7TxkqYT910ZzA-8XYlBg?pwd=pvjm 提取码：pvjm 打不开的客户端我打了个包,不确定在你的环境是否还能复现

我release了一个test版本，你试试？瞎猜的可能存在的问题。

**Comment by GiGaFotress** [comment]
运行了你这个测试版本之后,当前的版本问题也没了,都能正常运行了,非常奇妙

**Comment by HIllya51** [comment]
> 运行了你这个测试版本之后,当前的版本问题也没了,都能正常运行了,非常奇妙

我佛 
不过也是奇怪哦 我这里就没问题

**Comment by GiGaFotress** [comment]
> > 运行了你这个测试版本之后,当前的版本问题也没了,都能正常运行了,非常奇妙
> 
> 我佛 不过也是奇怪哦 我这里就没问题

对了,一个小问题,unity游戏在textractor下有严重的性能问题,因为钩住了太多不必要的地方,textctor的作者的解决方案是第一次找到钩子之后自己写一个配置文件来下次只钩住配置文件里有的部分hook点,这个功能有支持么?
https://github.com/Artikash/Textractor/issues/307

**Comment by lhj5426** [comment]
玄学 我也试了下 依旧不好使

**Comment by HIllya51** [comment]
> 玄学 我也试了下 依旧不好使
啊这  那我实在不知道咋回事了。

**Comment by HIllya51** [comment]
> > > 运行了你这个测试版本之后,当前的版本问题也没了,都能正常运行了,非常奇妙
> > 
> > 
> > 我佛 不过也是奇怪哦 我这里就没问题
> 
> 对了,一个小问题,unity游戏在textractor下有严重的性能问题,因为钩住了太多不必要的地方,textctor的作者的解决方案是第一次找到钩子之后自己写一个配置文件来下次只钩住配置文件里有的部分hook点,这个功能有支持么? [Artikash/Textractor#307](https://github.com/Artikash/Textractor/issues/307)

没用过 举个例子看看

**Comment by HIllya51** [comment]
> > > 运行了你这个测试版本之后,当前的版本问题也没了,都能正常运行了,非常奇妙
> > 
> > 
> > 我佛 不过也是奇怪哦 我这里就没问题
> 
> 对了,一个小问题,unity游戏在textractor下有严重的性能问题,因为钩住了太多不必要的地方,textctor的作者的解决方案是第一次找到钩子之后自己写一个配置文件来下次只钩住配置文件里有的部分hook点,这个功能有支持么? [Artikash/Textractor#307](https://github.com/Artikash/Textractor/issues/307)

魔改了一下，已支持

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/206611658-5ad1f742-741d-4237-b4cc-512da4cf433f.png)
之后的每个版本我都有试过 这个最新版 终于 又看到 设置界面了 哈哈哈哈

**Comment by BWR-forWork** [comment]
同样的问题，v1.23.0能打开设置，1.24.0及之后的版本就无法打开设置了……
