### ISSUE TITLE
现在的release无法打开

### ISSUE THREAD

**Issue by JiaChen-Zeng** [HIllya51/LunaTranslator#802]
### Version 程序版本

3.2.2 （2024‎年‎6‎月‎6‎日, ‏‎21:03:14下载的最新）

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/3676278/7905cec8-5b52-4441-97ad-105003545db7)

### Reproduction steps 复现步骤

打开exe，出错

**Comment by HIllya51** [comment]
1x
