### ISSUE TITLE
查词与原文显示问题

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaTranslator#804]
### Question 问题

显示原文的工具按钮经常失效；每当使用查词功能后，翻译器的CPU占用率就高很多，不查词的情况下基本0占用。
二者之间疑似有关联，查词CPU占用率升高的问题在遇到这显示原文的工具按钮失效后就有了
![1](https://github.com/HIllya51/LunaTranslator/assets/167575533/c97b7f75-8e3b-4012-8a91-46e37a10be21)

**Comment by HIllya51** [comment]
1x
