### ISSUE TITLE
去除重复行会影响到英文游戏

### ISSUE THREAD

**Issue by shinslashisuka** [HIllya51/LunaTranslator#808]
### Version 程序版本

v3.5.1

### bug's screenshot 错误截图

![捕获](https://github.com/HIllya51/LunaTranslator/assets/167951765/b07dae7d-dccc-4fc7-8364-1a51e6dddea4)

### Reproduction steps 复现步骤

文本处理选择如图“去除重复行”，第一种会去掉结尾若干个字母，第二种会去掉开头若干个字母。第一种影响较大，出现频率很高，第二种偶尔出现。

单个游戏设置文本处理方式可以彻底解决类似问题

**Comment by HIllya51** [comment]
什么意思

**Comment by shinslashisuka** [comment]
> 什么意思

勾选图上“去除重复行”选项，然后随便开个英文游戏就可以再现

**Comment by HIllya51** [comment]
莫名其妙
