### ISSUE TITLE
“文本处理”功能里面的“去除重复行”会导致英文游戏文本不完整（本人经过多次测试，确定存在此问题，请不要无视）

### ISSUE THREAD

**Issue by shinslashisuka** [HIllya51/LunaTranslator#809]
### Version 程序版本

v3.5.1

### bug's screenshot 错误截图

![捕获](https://github.com/HIllya51/LunaTranslator/assets/167951765/076da230-e067-4a4f-999b-0257c6c9dbc6)
游戏中出现文本不全情况

![捕1获](https://github.com/HIllya51/LunaTranslator/assets/167951765/4cd4576f-44df-4448-ab6d-66c39aed445c)
经过反复测试，选中“去除重复行ABCDBCDCDD→ABCD“和“去除重复行AABABCABCD→ABCD“会导致此问题，请看红线圈出内容

![捕2获](https://github.com/HIllya51/LunaTranslator/assets/167951765/4874ad75-e6d4-4ca6-9937-b9932f6537b4)
取消“去除重复行ABCDBCDCDD→ABCD“和“去除重复行AABABCABCD→ABCD”，文本即正确，请看红线圈出内容

### Reproduction steps 复现步骤

经过多次测试，“去除重复行ABCDBCDCDD→ABCD“会去掉结尾若干个字母，“去除重复行AABABCABCD→ABCD”会去掉开头若干个字母。第一种情况出现频率很高，对英文游戏影响很大，第二种偶尔出现。
当然，手工不勾选这两项可以解决问题，但是提出该问题是希望软件自动解决，

**Comment by HIllya51** [comment]
本来就是正确的文本你干什么要勾选，真是莫名其妙的

**Comment by HIllya51** [comment]
你是不是其实是想给游戏单独进行配置。

<img width="972" alt="F497220F38BEEC23F1BA60685EF8938F" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/b4b974a1-2e4e-41ee-84de-a8af0d8fc555">

**Comment by shinslashisuka** [comment]
就是这个意思，完美
