### ISSUE TITLE
熟した果実たちママ隷奴・完全版 不能提取含特殊符号的文本

### ISSUE THREAD

**Issue by EXBJAN** [HIllya51/LunaTranslator#81]
游戏链接：https://pan.baidu.com/s/1xo0yHaAx7wZ5jf2Qg5H00w?pwd=62a1 
提取码：62a1 
--来自百度网盘超级会员V6的分享

凡是含特殊符号（如：♪、♥、♡等）文本，在文本选择器里均不会被提取。但vnr是完全正确提取的
，包括特殊符号。
此外，我还测试了我游戏库里的其他游戏，除去这个，其余游戏的含特殊符号文本翻译器虽都能提取到文本，但对特殊符号的提取不太正常：
有的游戏里含特殊符号的文本，翻译器会正常提取标点符号和文字，但会省略特殊符号；
有的游戏则是把特殊符号提取成其他符号，比如：
<img width="305" alt="屏幕截图 2022-11-21 145859" src="https://user-images.githubusercontent.com/117036098/202988001-8a9e37b7-3ec9-4b16-807e-7f5ade811a17.png">
虽然对游戏翻译不影响，之前我也没在意，这次这个游戏的问题让我觉得这些现象估计是同一问题造成的。

**Comment by HIllya51** [comment]
关闭过滤乱码文本

**Comment by EXBJAN** [comment]
我才发现有这功能，不过接受的编码设置里，直接输入编码名称添加就有效？

**Comment by EXBJAN** [comment]
好吧，确实有效，我自行添加了utf-8和16编码

**Comment by HIllya51** [comment]
加utf8/utf16的话相当于允许全部字符集，不如直接关了。。。

**Comment by EXBJAN** [comment]
有道理，这就去关了
