### ISSUE TITLE
如何使用manga-ocr（第一步）

### ISSUE THREAD

**Issue by kousakaharuka9** [HIllya51/LunaTranslator#811]
### Question 问题

首先在https://github.com/raindrop213/LunaTranslator-re/releases/download/v0.0.2/manga-ocr_cpu_v0.1.11.zip 或者 
 https://github.com/raindrop213/LunaTranslator-re/releases/download/v0.0.2/manga-ocr_gpu_v0.1.11.7z下载整合包

之后解压并打开
![f086b987b745418b8579496dd4def5db](https://github.com/HIllya51/LunaTranslator/assets/172193461/05668752-ecd7-4cc9-9309-c0763ffb37cd)

之后打开自己的代理器
![304fc7d7746e0a74ea545613b7cf3be4](https://github.com/HIllya51/LunaTranslator/assets/172193461/8c17f2ae-47b9-4d48-9a18-02bbf3ee7fc6)
将service右边的小地球变绿以及打开TUN MOD
小地球是灰色的用户点击service旁的Mange
![8429c0f0007b7847ddacbc3a07d610ea](https://github.com/HIllya51/LunaTranslator/assets/172193461/e00d4957-cdaf-4dc1-b2ce-29a8319ad72c)
点击Install即可

之后打开powershell，cd到整合包下载的文件夹，输入 ./start.bat （以下为演示）
![dd1750e19e451418b29a980a24469ab8](https://github.com/HIllya51/LunaTranslator/assets/172193461/5f576e49-8a6a-4bff-947b-7eb7d2ba8282)点击整合包的文件夹，点击导航栏输入powershell
![6a2acd913037afc9cc5eb2ab8cba72af_720](https://github.com/HIllya51/LunaTranslator/assets/172193461/c0c2102c-01d0-40c8-97be-69a82f3defda)
然后按回车，会出现以下画面
![0665012ec17649dd03ea78fad03c7a43](https://github.com/HIllya51/LunaTranslator/assets/172193461/0334302f-0694-4b3d-9713-7b724c531b0d)
然后输入./start.bat
![e840f2dcac8a332b4301e810b2d3b35a](https://github.com/HIllya51/LunaTranslator/assets/172193461/37737dc1-4efa-4797-b6c3-0228337f4abf)
之后回车等待即可
![cad2c35489c38f97db6685e7ed2f38df](https://github.com/HIllya51/LunaTranslator/assets/172193461/035f9414-f1da-4281-bf63-231e198b561f)出现这样的画面就意味着成功了
![6f13183b8b50be9ed4a103bf04336c49](https://github.com/HIllya51/LunaTranslator/assets/172193461/96bf7afb-3df6-4438-bb03-04dfe8776cd1)
将这个数字填入luna里的端口
![9a3c671d8d966c414779d0375b012a26](https://github.com/HIllya51/LunaTranslator/assets/172193461/6ecd1167-0e25-4cda-9537-f073af90536c)
或许你就可以用了

方案提供者：飛鳥凑
![181d132a0d1c210f3bbd06d2b1f8c0fe](https://github.com/HIllya51/LunaTranslator/assets/172193461/316edd83-fbcc-4385-b910-89540f3b43ce)
感谢提供方案

**Comment by kousakaharuka9** [comment]
最后记得关闭恢复代理器的设置

**Comment by HIllya51** [comment]
这个qa已过时，我打了一份hf镜像的整合包，不再需要这些操作了。
