### ISSUE TITLE
Replace name with vndb data doesn't work

### ISSUE THREAD

**Issue by Fetch11** [HIllya51/LunaTranslator#812]
### Version 程序版本

v3.6.0

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/69702556/096cd8cd-f400-4fdb-99a2-3b53beba0107)
![image](https://github.com/HIllya51/LunaTranslator/assets/69702556/6f83ad94-a4ed-4491-9b5a-ac455529c1f7)

just in case if you need this 
[config.json](https://github.com/user-attachments/files/15776145/config.json)
[savehook_new_1.39.4.json](https://github.com/user-attachments/files/15776147/savehook_new_1.39.4.json)

### Reproduction steps 复现步骤

- open luna
- open game
- play the game
- expect name replacer will work
- it didn't

**Comment by HIllya51** [comment]
it work.

![屏幕截图 2024-06-11 002954](https://github.com/HIllya51/LunaTranslator/assets/101191390/a9a10fcf-6dc3-438b-b7fc-ff5778901604)
![屏幕截图 2024-06-11 003001](https://github.com/HIllya51/LunaTranslator/assets/101191390/df8a12f6-daef-457f-b9b7-2f0189b80b73)
