### ISSUE TITLE
能否放出旧版本的下载

### ISSUE THREAD

**Issue by sekurodesu** [HIllya51/LunaTranslator#813]
### Expected behavior 预期的功能

如题，之前用的貌似是2.52版本，现在装了最新的3.6.1版本感觉获取文本加翻译的速度比起原来至少慢了两倍左右，以前点击到下一句话基本马上就出翻译了，现在点完要等差不多2秒才出翻译，很影响使用体验，可以在release放出旧版本供使用吗？

**Comment by HIllya51** [comment]
怎么放 我又没存。
