### ISSUE TITLE
请问我该如何使用manga-ocr

### ISSUE THREAD

**Issue by kousakaharuka9** [HIllya51/LunaTranslator#814]
### Question 问题

我已下载并解压了整合包，但是manga-ocr还是不能使用。
![5951da2dceda11e576b7637692a38079](https://github.com/HIllya51/LunaTranslator/assets/172193461/0f071b2c-ac81-45f2-902a-21a821ea9c1d)

![4c9194c06cce5260318263dce155cc3e](https://github.com/HIllya51/LunaTranslator/assets/172193461/7e99d1f2-c744-477f-a708-9b36e32a58c2)

请问我该如何操作？

这是我的设置
![e3cf9cf61d3490a6eb81adbf54e625fc](https://github.com/HIllya51/LunaTranslator/assets/172193461/8c53eb58-932c-4c07-80b6-02284149b497)
麻烦了

**Comment by HIllya51** [comment]
你启动服务了吗。。。

**Comment by kousakaharuka9** [comment]
我应该如何启动服务？

**Comment by kousakaharuka9** [comment]
> 你启动服务了吗。。。

我应该如何启动服务？

**Comment by kousakaharuka9** [comment]
> start.bat

好的，谢谢
