### ISSUE TITLE
讯飞OCR TypeError get_body() got an unexpected keyword argument 'file_path'

### ISSUE THREAD

**Issue by charlespfan** [HIllya51/LunaTranslator#815]
### Version 程序版本

v3.6.1 64bit

### bug's screenshot 错误截图

![屏幕截图 2024-06-12 125519](https://github.com/HIllya51/LunaTranslator/assets/125957646/04ed590b-5d79-4989-995b-e7f0e71acecd)

### Reproduction steps 复现步骤

使用讯飞OCR时报这段：讯飞OCR TypeError get_body() got an unexpected keyword argument 'file_path'

**Comment by HIllya51** [comment]
1x
