### ISSUE TITLE
能否增加把OCR识别结果自动复制到剪贴板上的功能

### ISSUE THREAD

**Issue by charlespfan** [HIllya51/LunaTranslator#816]
### Expected behavior 预期的功能

能否增加把OCR识别结果自动复制到剪贴板上的功能，现在已有的功能需要手动点一下，有点麻烦
![屏幕截图 2024-06-12 145038](https://github.com/HIllya51/LunaTranslator/assets/125957646/daad890a-f5fb-46cb-a722-24bb3e3e2012)

**Comment by HIllya51** [comment]
![屏幕截图 2024-06-12 155148](https://github.com/HIllya51/LunaTranslator/assets/101191390/fc113f35-75ef-4eed-80d7-9f13d557c580)
