### ISSUE TITLE
Antivirus complains about files.

### ISSUE THREAD

**Issue by Sonado47** [HIllya51/LunaTranslator#817]
### Version 程序版本

3.6.1

### bug's screenshot 错误截图

1.
![Снимок экрана 2024-06-12 140901](https://github.com/HIllya51/LunaTranslator/assets/172497270/c74ae431-31e0-42dc-8262-726c2963ce7a)
![Снимок экрана 2024-06-12 140941](https://github.com/HIllya51/LunaTranslator/assets/172497270/2bc8c7ec-d03a-4d4a-a2b5-564af8f59efe)
2.
![Снимок экрана 2024-06-12 140932](https://github.com/HIllya51/LunaTranslator/assets/172497270/5ac0a6bc-8ef8-4b9e-a49e-26809f95e992)
![Снимок экрана 2024-06-12 140915](https://github.com/HIllya51/LunaTranslator/assets/172497270/62960a85-06e4-44b3-b0ba-431689453bc7)

### Reproduction steps 复现步骤

I downloaded the current version and here it is. Can you fix these problems?

**Comment by HIllya51** [comment]
do not use
