### ISSUE TITLE
点击“已保存游戏”的按钮出现报错

### ISSUE THREAD

**Issue by luoliyushu** [HIllya51/LunaTranslator#818]
### Version 程序版本

v3.6.1

### bug's screenshot 错误截图

![1718252583911](https://github.com/HIllya51/LunaTranslator/assets/112807173/dd07cb32-2fa5-429e-853a-62b65e2430cb)

### Reproduction steps 复现步骤

点击“已保存游戏”的按钮出现报错，不知道是不是我自己的原因

**Comment by HIllya51** [comment]
1x
