### ISSUE TITLE
OCR模式，最小化还原之后左边两个按钮无法点击

### ISSUE THREAD

**Issue by fatecyx** [HIllya51/LunaTranslator#819]
### Version 程序版本

3.6.2

### bug's screenshot 错误截图

鼠标移到按钮（重新翻译和自动翻译）上，没有高亮，点击也无效

### Reproduction steps 复现步骤

OCR模式，选择范围，打开自动翻译，最小化
然后会发现左边两个无法点击了

**Comment by HIllya51** [comment]
什么意思

**Comment by HIllya51** [comment]
什么意思

**Comment by HIllya51** [comment]
录个视频。

**Comment by fatecyx** [comment]
https://drive.google.com/file/d/1TpqgwMu_-l-AmqV0YTysbU8qmsjQmtTn/view?usp=drive_link

**Comment by HIllya51** [comment]
已修
