### ISSUE TITLE
能否在翻译选项增加kimi的develop或者api

### ISSUE THREAD

**Issue by charlespfan** [HIllya51/LunaTranslator#821]
### Expected behavior 预期的功能

能否在翻译选项增加kimi的develop或者api，我觉得翻译效果很好，有时比chatgpt4还要好，https://kimi.moonshot.cn/

**Comment by HIllya51** [comment]
https://platform.moonshot.cn/docs/api/chat#api-%E8%AF%B4%E6%98%8E
兼容chatgpt-非官方接口
