### ISSUE TITLE
程序初始化时属性缺失

### ISSUE THREAD

**Issue by BonBonCure** [HIllya51/LunaTranslator#822]
### Version 程序版本

2.37.4

### bug's screenshot 错误截图

![图片](https://github.com/HIllya51/LunaTranslator/assets/67302548/c6a1221e-8328-4d49-9a74-3db70ea8e9dd)
![图片](https://github.com/HIllya51/LunaTranslator/assets/67302548/0cbd750f-5f4c-4fb4-b256-d871d6c3c52b)

### Reproduction steps 复现步骤

好像是一次崩溃后发生的，就再也无法重启软件

**Comment by HIllya51** [comment]
重下。
