### ISSUE TITLE
What's the problem?

### ISSUE THREAD

**Issue by Tara-369** [HIllya51/LunaTranslator#823]
### Version 程序版本

v3.6.3

### bug's screenshot 错误截图

![التقاط](https://github.com/HIllya51/LunaTranslator/assets/172912749/8b52b5b7-a583-4a5c-8528-ed3b8e9d836d)

### Reproduction steps 复现步骤

i have tried many times to open exe and admin_exe but it's the same i don't really know what's the issue

**Comment by HIllya51** [comment]
Do not use non-English paths

**Comment by Tara-369** [comment]
![التقاط](https://github.com/HIllya51/LunaTranslator/assets/172912749/7e439a0e-d7f6-463d-946d-648860cf6577)
  Well i tried that but it's still gives me the same error

**Comment by HIllya51** [comment]
try 64 bit version

**Comment by asukaminato0721** [comment]
![image](https://github.com/HIllya51/LunaTranslator/assets/30024051/afdf2c4f-f950-406a-b566-ed146b3c4818)

works well.

**Comment by HIllya51** [comment]
show me the content of LunaTranslator\runtime\python37._pth , it should be :
![屏幕截图 2024-06-16 014527](https://github.com/HIllya51/LunaTranslator/assets/101191390/6f9b0f59-17dd-4f75-a526-42cf4c5d45a8)

**Comment by HIllya51** [comment]
![屏幕截图 2024-06-16 014814](https://github.com/HIllya51/LunaTranslator/assets/101191390/426fc03b-e515-4a97-aab9-67a7b5a271b3)
This is my only guess that can reproduce this problem, although it doesn't seem to be the problem.

**Comment by Tara-369** [comment]
![التقاط](https://github.com/HIllya51/LunaTranslator/assets/172912749/e6cf4f3d-49f7-4efa-972c-aec6b3119665)
Yes, I do not think that this file is the problem for me. I do not really know what is the reason for this, and even if I wanted to try the 64bit version, I will not be able to, unfortunately, my computer is 32bit.

**Comment by HIllya51** [comment]
Try running LunaTranslator_debug.exe using the Run as Administrator option in the right-click menu.

**Comment by Tara-369** [comment]
I tried that and nothing changed. I also tried re-downloading the zip and exe file and it did not work in both cases either. I think that my problem has no solution in the end, unfortunately.
I was really looking forward to trying out your translator
