### ISSUE TITLE
翻译窗口和文字变透明了

### ISSUE THREAD

**Issue by naclgeorge** [HIllya51/LunaTranslator#824]
### Version 程序版本

3.6.4

### bug's screenshot 错误截图

![luna-tr](https://github.com/HIllya51/LunaTranslator/assets/94028626/90b81c3b-42ad-4317-a62b-5a17568af070)

### Reproduction steps 复现步骤

前两天一次使用中停止响应后再打开就出现了，工具栏窗口、翻译窗口以及里面的文字都变透明了。查看设置里面工具栏和窗口的透明度都已经是100%，应该已经是不透明，文字没看到有设置透明度的，请问这算是什么情况，谢谢

**Comment by HIllya51** [comment]
userconfig打包给我

**Comment by naclgeorge** [comment]
[userconfig.zip](https://github.com/user-attachments/files/15857143/userconfig.zip)

**Comment by HIllya51** [comment]
哪透明了，你这不是纯白色背景吗。

**Comment by naclgeorge** [comment]
> 哪透明了，你这不是纯白色背景吗。

背景不是主要的，怎么样都行。关键是文字完全看不清，就像一楼的图上那样，文字上像颜色调淡以后是打了阴影一样

**Comment by HIllya51** [comment]
你换个字体样式不就行了吗 无语。
