### ISSUE TITLE
Non-Auto OCR

### ISSUE THREAD

**Issue by zigma9114** [HIllya51/LunaTranslator#827]
### Expected behavior 预期的功能

Currently OCR has to be automatic either through text change detection or through interval

This becomes an issue when using API based OCR like Google Vision: they works per call and auto OCR is causing billing issue. 

### Alternative behavior (optional) 近似的功能（可选）

Option to trigger OCR only on button press (can be set by user prefferably) so user has control when OCR is done

**Comment by HIllya51** [comment]
<img width="587" alt="屏幕截图 2024-06-18 130751" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/80558f58-0f8c-404a-97da-593f842848ab">
