### ISSUE TITLE
google翻译大陆有镜像站可用，大佬可以试试？

### ISSUE THREAD

**Issue by leejiaming02** [HIllya51/LunaTranslator#83]
google翻译有个镜像：https://gtranslate.cdn.haah.net
这是在网页翻译插件上发现的： https://addons.mozilla.org/zh-CN/firefox/addon/hcfy/
大陆应该还能用，不知道大佬是否方便修改试试，或者加一个功能指定镜像

**Comment by HIllya51** [comment]
502 Bad Gateway

**Comment by leejiaming02** [comment]
直接访问域名不行，可以用python直接访问接口，参数格式和原来的接口是一样的：
https://zhuanlan.zhihu.com/p/346484391?ivk_sa=1024320u
我用postman也可以访问：
![图片](https://user-images.githubusercontent.com/16527074/203778505-7a5aa6f4-3306-4461-8c40-37f7bc00c589.png)

**Comment by HIllya51** [comment]
放弃了。这个镜像有点lj。
Our systems have detected unusual traffic from your computer network. Please try your request again later. [Why did this happen?] 
IP address: 
Time: 2022-11-24T12:19:35Z
URL: https://gtranslate.cdn.haah.net/translate_a/single?client=at&sl=zh-CN&tl=en&dt=t&q=%E8%AF%95%E4%B8%80%E8%AF%95

**Comment by leejiaming02** [comment]
这有点蠢…之前没发现这个问题…那算了  感谢
