### ISSUE TITLE
识别操作完成后，打开设置菜单OCR相关页中的“查看处理效果”后的图片按钮，窗口会无限放大

### ISSUE THREAD

**Issue by flyingcrylife** [HIllya51/LunaTranslator#831]
### Version 程序版本

5.0.1

### bug's screenshot 错误截图

![76cb2d12f8af7bec2e9172bdd0f3b625](https://github.com/HIllya51/LunaTranslator/assets/38677562/bf4d360e-e272-4332-b243-c58e32eadf7c)

### Reproduction steps 复现步骤

进行一次OCR识别操作，然后打开设置-文本输入-OCR设置-查看处理效果-图片按钮

**Comment by HIllya51** [comment]
1x
