### ISSUE TITLE
主题设置为QTwin11时，字体会强制变为宋体

### ISSUE THREAD

**Issue by Ptilopsis01** [HIllya51/LunaTranslator#832]
### Version 程序版本

5.0.1

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/93318731/8a39ba98-79bb-4ac1-b4ab-7903bd871b20)

### Reproduction steps 复现步骤

如上所述
顺便翻译窗口的不透明度不能降到0吗

**Comment by HIllya51** [comment]
这个是抄的https://github.com/witalihirsch/QTWin11的样式文件，他把字体写死了。如果要改只能改LunaTranslator\files\themes\QTWin11\light.py文件

**Comment by HIllya51** [comment]
ok
0和1根本看不出来区别的。非要0可以用这个按钮
![屏幕截图 2024-06-19 165818](https://github.com/HIllya51/LunaTranslator/assets/101191390/30e83334-ff64-4063-83bc-9ea6901dfb28)
