### ISSUE TITLE
关于翻译窗口工具栏

### ISSUE THREAD

**Issue by k2250761** [HIllya51/LunaTranslator#833]
### Version 程序版本

5.0.1

### bug's screenshot 错误截图

重新启动软件时，翻译窗口的工具栏不会自动隐藏，需要把鼠标移动到翻译窗口激活，才会自动隐藏
以前的版本能够不需要鼠标移动到窗口也能隐藏，能否修复

**Comment by HIllya51** [comment]
我专门改成这样的
