### ISSUE TITLE
只能用一次

### ISSUE THREAD

**Issue by Raiter123** [HIllya51/LunaTranslator#835]
### Version 程序版本

5.1.0

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/153535038/d67cff5d-c5c8-424c-9c2f-03c11d96bf04)

### Reproduction steps 复现步骤

我只用過一次，再打開時就無法打開了

**Comment by HIllya51** [comment]
重下 丢文件了
