### ISSUE TITLE
Proxy not working for vndb

### ISSUE THREAD

**Issue by iu3kxa** [HIllya51/LunaTranslator#836]
### Version 程序版本

5.1.0 3.6.5 and others

### bug's screenshot 错误截图

Getting metadata from vndb does not work using proxy.
Getting metadata from dlsite does work using proxy.
Get lastest version fail with proxy.

If the pc is connected directly to internet or if i create same static routes to vndb (i'm using this method) then metadata are get correctly, with proxy enabled or disabled.

https://api.vndb.org/kana/vn {'filters': ['id', '=', 'v2002'], 'fields': 'image.url'}
https://api.vndb.org/kana/vn {'filters': ['id', '=', 'v2002'], 'fields': 'title,titles.title,titles.main'}
https://api.vndb.org/kana/character {'filters': ['vn', '=', ['id', '=', 'v2002']], 'fields': 'name,original'}
https://vndb.org/v2002 cache/vndb/e0412a000831f0cdb2206addd80e7ef0.html
https://api.vndb.org/kana/vn {'filters': ['id', '=', 'v2002'], 'fields': 'developers.name,developers.original'}
https://api.vndb.org/kana/vn {'filters': ['id', '=', 'v2002'], 'fields': 'screenshots.url'}
Traceback (most recent call last):
  File "S:\programs\LunaTranslator32\LunaTranslator\myutils\utils.py", line 195, in trysearchfordata
    data = targetmod[key].searchfordata(vid)
  File "S:\programs\LunaTranslator32\LunaTranslator\metadata\vndb.py", line 263,  in searchfordata
    _image = self.dispatchdownloadtask(img)
  File "S:\programs\LunaTranslator32\LunaTranslator\metadata\abstract.py", line 90, in dispatchdownloadtask
    if "." in url[5:]:
TypeError: 'NoneType' object is not subscriptable

### Reproduction steps 复现步骤

Remove the gateway from the network card.
Start a proxy in another machine; i use tinyproxy but fiddler2 or fiddler4 or anything else is fine.
Set proxy manually , for me is 10.0.0.254:8888 
Add or choose a game from game management, set vndb id and click lens icons result in error. 
Set dlsite id and click lens icons result in success. 
in setup/configuratio panel, in Check Other Settings, Other settings read Latest version:Get Failed
Bangumi seem also to work , fanza is not accessible from my country so i didnt try.
And thanks fro your great work.

**Comment by HIllya51** [comment]
Don't come to me with your network problems.
