### ISSUE TITLE
辞书优先度的设置会影响辞书的显示

### ISSUE THREAD

**Issue by kousakaharuka9** [HIllya51/LunaTranslator#837]
### Version 程序版本

5.0

### bug's screenshot 错误截图

![ad27ce685b0e416ad7b045f3737c43b6](https://github.com/HIllya51/LunaTranslator/assets/172193461/d963b35f-32e6-4d81-8580-0ae91ab44ef4)

### Reproduction steps 复现步骤

有且只有一本辞书有这个词时，如果优先度设置不是100，会出现无法直接显示情况。这里以“もしものとき”为例。
![ad27ce685b0e416ad7b045f3737c43b6](https://github.com/HIllya51/LunaTranslator/assets/172193461/d963b35f-32e6-4d81-8580-0ae91ab44ef4)

这是“moji辞书”优先度设置为“99”时的情况，尽管没有出现其他辞书也需要再点击一下上面的“moji辞书”才会显示
![16daf7df1fac08e627b6a5fa3122d8af](https://github.com/HIllya51/LunaTranslator/assets/172193461/d47be959-126c-4845-8914-38785b888901)
而如果优先度设置成100，则不会出现这种情况

**Comment by HIllya51** [comment]
1x
