### ISSUE TITLE
你好，我发现在使用hook读取的某个游戏的文本时候，翻译框一定会上文和下文一起显示

### ISSUE THREAD

**Issue by bzxbao123** [HIllya51/LunaTranslator#84]
游戏内文本显示为B
翻译文本显示为A+B，A是上一句话
再下一句话的时候，翻译文本就显示B+C了

**Comment by bzxbao123** [comment]
文本没有乱码问题

**Comment by HIllya51** [comment]
截图看一下。

**Comment by bzxbao123** [comment]
![QQ截图20221125163255](https://user-images.githubusercontent.com/45854057/204013247-571daf3e-f3a7-4f85-af5e-e625ada5c0d4.png)

**Comment by HIllya51** [comment]
给我看一下原文

**Comment by HIllya51** [comment]
截一下文本选择窗口下面的文本，多截一点我好分析。。

**Comment by bzxbao123** [comment]
![捕获](https://user-images.githubusercontent.com/45854057/204014448-92339758-5a04-49a7-b318-a97087791a28.PNG)

**Comment by bzxbao123** [comment]
这样行吗

**Comment by bzxbao123** [comment]
可以视为“忍”的前后文字实际上是分开的上下文

**Comment by HIllya51** [comment]
设置自定义python处理，把下面这些内容复制进去。

last='' 
lastlast=''
savename=set()
ii=0 
def solve(line):
    global ii,last,lastlast
    if ii==0:
        lastlast=line
         
    elif ii==1:
        last=line
    else:
         
        for i1 in range(len(line)): 
            if line[:i1]==last[-i1:]:
                
                break
         
        for i2 in range(len(last)):
            if last[:i2]==lastlast[-i2:]:
                break
          
        savename.add(last[i2:-i1]) 
        iii=0
        for name in savename: 
            if line[i1:][:len(name)]==name:
                iii=max(len(name),iii)
        lastlast=last
        last=line
        line=line[i1:][iii:]  
    ii+=1 
    return line

**Comment by HIllya51** [comment]
设置自定义python处理，把这个文件里面的内容复制进去。

[1.zip](https://github.com/HIllya51/LunaTranslator/files/10094027/1.zip)

**Comment by HIllya51** [comment]
我函数名好像写错了 记得改一下

**Comment by bzxbao123** [comment]
感谢。我试了下，翻译显示还是一样的。这个是已经复制内容进去自定义处理的文件，用vscode打开，提示似乎是last没有被声明
[mypost - 副本.txt](https://github.com/HIllya51/LunaTranslator/files/10095566/mypost.-.txt)

**Comment by HIllya51** [comment]
修复了

**Comment by bzxbao123** [comment]
已经正常了，感谢
