### ISSUE TITLE
想问一下怎样解决LunaTranslator配合MPV视频播放器的animecards_v35.lua脚本自动复制字幕到剪贴板出现的无法显示翻译的问题

### ISSUE THREAD

**Issue by jpACGlover** [HIllya51/LunaTranslator#840]
### Question 问题

使用LunaTranslator通过剪贴板吸收animecards_v35.lua脚本发出的字幕只能显示原文，不能显示翻译。（通过Ctrl+c手动复制的文本能正常显示翻译......）
我的谷歌云端硬盘链接：https://drive.google.com/file/d/1dBcX7I1i4sr04jQ-q3Tz8xlaigUA_YYX/view?usp=drive_link
（压缩文件里面有：测试用的视频和字幕 + 我的测试视频演示 + [MPV播放器（带有animecards_v35.lua脚本，打开有字幕的视频后能自动开启复制字幕到剪贴板））
![截图_20240622090912](https://github.com/HIllya51/LunaTranslator/assets/171327971/4d74760b-e57a-42d2-ad2a-601ca217d684)
MPV播放我选用了这个（但是即使选用其他MPV播放器也一样不能显示翻译）：https://github.com/dyphire/mpv-config
最后我在（吾爱破解论坛https://www.52pojie.cn/thread-1813670-1-1.html找了一个旧版的LunaTranslator它能正常显示翻译，而新版这个LunaTranslator却不能显示翻译......）

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/assets/101191390/28b8a889-abc0-4b6e-a610-c8936cb8ffc8

**Comment by HIllya51** [comment]
你重下一下吧  可能后面我修过了

**Comment by jpACGlover** [comment]
哦，搞明白了，原来是要用LunaTranslator_admin.exe才能配合animecards_v35.lua脚本正常显示翻译！我之前还奇怪为什么你的能正常显示翻译......原来因为我使用的是LunaTranslator.exe......

**Comment by jpACGlover** [comment]
原来要用LunaTranslator_admin.exe来配合animecards_v35.lua脚本才能正常显示翻译！我之前还奇怪为什么你的能正常显示翻译......原来是因为我之前一直用LunaTranslator.exe。
另外想问一下是否能添加这种功能呢？：开启原文+翻译都显示时，使翻译处于隐藏状态，当原文看不懂时通过按住快捷键来显示翻译，松开快捷键后立即隐藏翻译。（这种功能类似于https://github.com/chocovon/subtitle-mask，它通过按住Ctrl来显示被遮挡字幕，当松开Ctrl时恢复遮挡字幕的效果）
