### ISSUE TITLE
LunaTranslator isn't sending text to koboldcpp via gpt api

### ISSUE THREAD

**Issue by rikimtasu** [HIllya51/LunaTranslator#842]
### Version 程序版本

v5.2.1

### bug's screenshot 错误截图

![LunaTranslator_5koAOBPHiZ](https://github.com/HIllya51/LunaTranslator/assets/1460843/a4df73f6-a31c-4870-af2e-f21126cc84e3)
![シークレットラブ（仮）_e2Qk7v2aug](https://github.com/HIllya51/LunaTranslator/assets/1460843/0a0578f6-1add-4916-bd19-a879e557f6c8)
![WindowsTerminal_KAYJ6ARx5k](https://github.com/HIllya51/LunaTranslator/assets/1460843/5cbc66ec-7408-42fa-9737-6b59587b023a)

### Reproduction steps 复现步骤

1.launch koboldcpp 1.68 with a model loaded (Oumuamua-7b-instruct-v2.Q5_K_M)
https://github.com/LostRuins/koboldcpp/releases/tag/v1.68
2.launch a game and hook it with the text loaded
3.Turn on ChatGPT Compatible interface from translation settings->Offline translation
API address is set to http://localhost:5001/
4.it wont send the text at all to koboldcpp. error message is as shown in screenshot

**Comment by HIllya51** [comment]
1x
