### ISSUE TITLE
通过露娜搜索特殊码后，游戏乱码了

### ISSUE THREAD

**Issue by liseerqaz22** [HIllya51/LunaTranslator#843]
### Version 程序版本

luna

### bug's screenshot 错误截图

![36c757a5f618fb997bbf7ce2c84ee1d0](https://github.com/HIllya51/LunaTranslator/assets/173562606/f7e83b71-42a0-4e97-b237-110f34f4e95c)
![image](https://github.com/HIllya51/LunaTranslator/assets/173562606/3e33248e-5c3f-4d19-8ccd-bc7cbe0d6f01)
![3c6460d7065af97896c406050f529203](https://github.com/HIllya51/LunaTranslator/assets/173562606/ac97c916-4ab9-4757-b8f7-d35834944ba9)

### Reproduction steps 复现步骤

ren，py引擎的游戏Monster Girl Dreams，网址是：https://www.patreon.com/MonsterGirlDreams/posts
之前尝试汉化，搜索特殊码后就乱码了，怎么都恢复不了，原本是开始，存档等文字的地方变成了黑色小方块，再次搜索特殊码，黑色小方块更小了
现在是重新下载这个游戏，删除再安装，更换路径，更换游戏版本，打开都是这个问题。
现在想问一下该如何恢复？让游戏不再乱码呢

**Comment by HIllya51** [comment]
什么意思

**Comment by liseerqaz22** [comment]
> 什么意思

我尝试通过露娜汉化一个游戏，点了搜索特殊码的功能，游戏崩溃了，再次打开游戏游戏就乱码了。
然后无论是重新删除安装这个游戏，还是下载其他版本，还是更换安装路径，打开这个游戏，这个游戏都是乱码，恢复不了。
在其他设备上可以正常运行。而且一开始这个电脑也能正常打开这个游戏

**Comment by HIllya51** [comment]
![屏幕截图 2024-06-23 011904](https://github.com/HIllya51/LunaTranslator/assets/101191390/8c5eb192-2678-4dba-a8c4-b80e3ba052aa)
不要拿旧版来问我行吗，很无语。
