### ISSUE TITLE
托盘的设置按钮按一下就会闪退

### ISSUE THREAD

**Issue by jpACGlover** [HIllya51/LunaTranslator#844]
### Version 程序版本

v5.2.2

### bug's screenshot 错误截图

![截图_20240623164920](https://github.com/HIllya51/LunaTranslator/assets/171327971/5298e795-d4e2-451f-8d5c-ece2e788d616)

### Reproduction steps 复现步骤

每按一下任务栏的设置按钮按一下就会闪退

**Comment by HIllya51** [comment]
1x
