### ISSUE TITLE
最新版5.2.2 bug汇报

### ISSUE THREAD

**Issue by ssincxv** [HIllya51/LunaTranslator#846]
### Version 程序版本

V5.2.2

### bug's screenshot 错误截图

<img width="864" alt="Snipaste_2024-06-24_17-34-29" src="https://github.com/HIllya51/LunaTranslator/assets/116273073/2276c70b-056b-411d-ac22-4be63be68946">
Magpie路径一点就崩溃。
内嵌翻译导出翻译补丁和内嵌安全性检测右边的齿轮图标一点就崩溃
文本处理—文本预处理—使用自定义优化点右边的齿轮弹几个框
<img width="1826" alt="Snipaste_2024-06-24_17-40-35" src="https://github.com/HIllya51/LunaTranslator/assets/116273073/e1a14206-27db-43e3-96c8-1aa045d2f132">
就没了
语言设置—软件显示语言 重启生效 右边的齿轮一点就崩溃
<img width="867" alt="Snipaste_2024-06-24_17-41-56" src="https://github.com/HIllya51/LunaTranslator/assets/116273073/cf8c642c-57e5-4955-aeb7-2ba6ff81d9c1">

### Reproduction steps 复现步骤

<img width="864" alt="Snipaste_2024-06-24_17-34-29" src="https://github.com/HIllya51/LunaTranslator/assets/116273073/2276c70b-056b-411d-ac22-4be63be68946">
Magpie路径一点就崩溃。
内嵌翻译导出翻译补丁和内嵌安全性检测右边的齿轮图标一点就崩溃
文本处理—文本预处理—使用自定义优化点右边的齿轮弹几个框
<img width="1826" alt="Snipaste_2024-06-24_17-40-35" src="https://github.com/HIllya51/LunaTranslator/assets/116273073/e1a14206-27db-43e3-96c8-1aa045d2f132">
就没了
语言设置—软件显示语言 重启生效 右边的齿轮一点就崩溃
<img width="867" alt="Snipaste_2024-06-24_17-41-56" src="https://github.com/HIllya51/LunaTranslator/assets/116273073/cf8c642c-57e5-4955-aeb7-2ba6ff81d9c1">

**Comment by ssincxv** [comment]
<img width="915" alt="Snipaste_2024-06-24_17-53-12" src="https://github.com/HIllya51/LunaTranslator/assets/116273073/66647e1e-edb1-4a92-8cd7-43636385ef0d">
无法自定义封面，更改标题后无法立即生效，必须退出游戏管理再打开游戏管理才能生效

**Comment by HIllya51** [comment]
> 更改标题后无法立即生效，必须退出游戏管理再打开游戏管理才能生效

这个我早就改了，简化了一些实现，不然会有一致性问题

> 无法自定义封面

![屏幕截图 2024-06-24 181222](https://github.com/HIllya51/LunaTranslator/assets/101191390/f6e9c68a-4cdb-4bcb-a558-5a795e6dd950)
