### ISSUE TITLE
闪退bug报告

### ISSUE THREAD

**Issue by qstdnx** [HIllya51/LunaTranslator#847]
### Version 程序版本

6月24-最新

### bug's screenshot 错误截图

点击游戏管理搜索框左边齿轮闪退，第一次闪退后软件无法启动，应该是后台更新被打断导致，更新覆盖后可以启动，debug如下

![WindowsTerminal_tBmTLjaHuU](https://github.com/HIllya51/LunaTranslator/assets/20844622/9a2f3c96-4814-40c4-90a8-9df9bc9ebd78)

更新后，点齿轮还是闪退，debug如下

![WindowsTerminal_zjb1FI1ZIL](https://github.com/HIllya51/LunaTranslator/assets/20844622/aaf50f9a-5f1f-43c9-84ef-dc361c2806e9)

### Reproduction steps 复现步骤

1
![LunaTranslator_admin_yxvdXUpBv6](https://github.com/HIllya51/LunaTranslator/assets/20844622/39a41605-113c-4dcb-b7ff-7a2a035cb32a)
2
![LunaTranslator_admin_7QgBfrRSra](https://github.com/HIllya51/LunaTranslator/assets/20844622/56778770-8af7-4302-af45-52d04552eb1c)

**Comment by HIllya51** [comment]
1x
