### ISSUE TITLE
HOOK页勾选多个HOOK文本自动合并的功能，升级后失效了

### ISSUE THREAD

**Issue by AkikazeQ** [HIllya51/LunaTranslator#848]
### Expected behavior 预期的功能

之前，按顺序勾选
1、人名
2、对话文本
能99%的情况下输出
===> 人名「对话文本」

这个功能最近的升级版本失效了，只能单纯输出其中一个，希望能恢复这个功能，这对翻译效果提升很大。

因为 人名一般带有明显的性别信息，比如"爱丽丝"，"洛恩"等等

 HOOK出"人名「对话文本」" 相比 单纯   " 「对话文本」"
能让大模型翻译的时候，更正确的根据上下文补充日文原文中缺失的使用他/她，明显的降低翻译错误率。

### Alternative behavior (optional) 近似的功能（可选）

如果可以的话，希望额外有一个功能，
选定的HOOK框，其中一个识别到刷新内容后，等待下一个框内容的延迟量，给用户设置，
这样能适应不同的游戏引擎延迟（不同的游戏人名和文本框文本之间的延迟可能会差异很大），
提高人名和文本获取组合功能的稳定性。

**Comment by HIllya51** [comment]
1x
