### ISSUE TITLE
An uncomfortable choice of image for the cover.

### ISSUE THREAD

**Issue by TildaRu** [HIllya51/LunaTranslator#849]
ver 5.3.1
An uncomfortable choice of image for the cover.

https://github.com/HIllya51/LunaTranslator/assets/107315419/03e563cb-88c2-4772-8fb2-8aa8800e942c

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/6c4aa72b07e810039ee1afba087d586b55b43e0b

**Comment by TildaRu** [comment]
> Waiting for background download of images

The website vndb is blocked in the Russian Federation by Roskomnadzor - Federal Service for Supervision of Communications, Information Technology and Mass Media, therefore the automatic image loading is not available.
