### ISSUE TITLE
请问能否方便在文本输入源里增加一个导入.txt文本的功能或者提高翻译字数限制

### ISSUE THREAD

**Issue by ikemenrourou** [HIllya51/LunaTranslator#85]
想拿来看ASMR的台本或者web小说，最大翻译字数只有500，一段一段的翻译体验有点难受，希望大大能增加一个批量翻译的功能，例如导入.txt原文，翻译完成后就能直接导出翻译后的.txt文本，感谢！

(之前一直用着VNR就是因为它有共享辞书的功能可以优化翻译，最近无意中发现了大大的翻译器，也有同样的功能，添加专有名词的时候还不会像VNR共享辞书一样动不动就崩溃，这真是太酷了！再次表达感谢:>)

**Comment by HIllya51** [comment]
以支持

**Comment by ikemenrourou** [comment]
> 以支持

谢谢大大，试了试，翻译的结果只能在历史翻译里查看嘛，想只保留翻译结果然后复制到txt文件上，但那个录制翻译文件的功能俺研究了半天还是没搞懂，不好意思，方便的话能再增加一个把翻译好的文本直接导出成txt文件的功能嘛？（原文和翻译器名称不想保留）。

或是在历史翻译里增加一个显示/隐藏 原文或翻译器名称的选项，同时加个清空历史翻译的选项方便俺复制黏贴到txt文件上。

像这样！
![QQ截图20221127055909](https://user-images.githubusercontent.com/34646702/204111429-8984d665-d176-4667-a239-93bb24c37b68.png)

**Comment by HIllya51** [comment]
加到右键菜单里了。

**Comment by ikemenrourou** [comment]
> 加到右键菜单里了。

酷诶！非常感谢！大大效率太高了：P
