### ISSUE TITLE
能否增加一个保存tts为本地音频的功能？

### ISSUE THREAD

**Issue by ZoeyNya** [HIllya51/LunaTranslator#850]
### Expected behavior 预期的功能

因为想服用句子朗读tts在anki中，想问下能否增加这么一个功能？最好还可以选一下音频格式就更好了

**Comment by HIllya51** [comment]
<img width="436" alt="屏幕截图 2024-06-26 135412" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/95383b7b-225d-49a6-8ba9-4869a5830d87">
