### ISSUE TITLE
V5.3.0无法使用DEEPLX在线翻译

### ISSUE THREAD

**Issue by 668668acg** [HIllya51/LunaTranslator#851]
### Version 程序版本

V5.3.0

### bug's screenshot 错误截图

![屏幕截图 2024-06-26 133937](https://github.com/HIllya51/LunaTranslator/assets/169470320/f745084a-5e02-4c06-b21f-912298145238)

### Reproduction steps 复现步骤

V5.3.0无法使用DEEPLX在线翻译，使用旧版本就可以

**Comment by HIllya51** [comment]
https://linux.do/t/topic/111737
