### ISSUE TITLE
Hook翻译过程中不断有LUNAFROMJS5% 添加到剪切板

### ISSUE THREAD

**Issue by 668668acg** [HIllya51/LunaTranslator#852]
### Question 问题

Hook翻译过程中不断有LUNAFROMJS5% 添加到剪切板，是否能取消

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/issues/689

**Comment by 668668acg** [comment]
![image](https://github.com/HIllya51/LunaTranslator/assets/169470320/b4d9e58a-dda1-462b-9ecf-7d72708c713b)
添加disable.clipboard文件后，如图所示的hook的语句就消失了，提取不出想要的句子

**Comment by HIllya51** [comment]
就是这样实现的，你不要去读剪贴板。

**Comment by 668668acg** [comment]
好的，感谢
