### ISSUE TITLE
Bug: Translation of type 'debugging browser' Google (only Google) not always updated

### ISSUE THREAD

**Issue by iyuka888** [HIllya51/LunaTranslator#853]
### Version 程序版本

5.3.1

### bug's screenshot 错误截图

![screen_bug_luna _2png](https://github.com/HIllya51/LunaTranslator/assets/170653130/f7c35931-aca0-4a69-9788-3cae630a2243)
![screen_bug_luna](https://github.com/HIllya51/LunaTranslator/assets/170653130/1b6addfe-84a9-44bb-80a6-04d6bc207b5b)

### Reproduction steps 复现步骤

Hello,

1. Navigate to: Settings > Translation Settings > tab 'Debugging browser'
2. Activate 'Google' and eventually others like deepl, bing, ... for comparison
3. Start game
4. Sometimes, Google translation is not being updated while it is being translated in the browser (see screenshot)

This seems to be unique to Google. Bing and deepl are working fine.
One screenshot shows deepl working fine (black color in interface), the other shows the browser correctly translating Google but not updating the text in the Luna interface (yellow color in interface).

Sometimes, opening the debugging browser and going to the Google tab then going back to the game fixes it temporarily.

Thank you in advance. Great work

**Comment by HIllya51** [comment]
![屏幕截图 2024-06-26 182101](https://github.com/HIllya51/LunaTranslator/assets/101191390/216d40f3-faba-4250-b142-8a229482cbd3)
This is Google's fault, please do not report it to me.
