### ISSUE TITLE
浏览器翻译可以输入内容，但是无法在网页提交，无法获取结果

### ISSUE THREAD

**Issue by TobyLi223** [HIllya51/LunaTranslator#856]
### Version 程序版本

最新

### bug's screenshot 错误截图

![屏幕截图 2024-06-27 220354](https://github.com/HIllya51/LunaTranslator/assets/96031501/046d96fb-fe21-4b43-aef1-544e1ce8ecdd)
点下一句它会把未发送的文本替换掉，之前几句是我手动点的。

### Reproduction steps 复现步骤

我所做的只是把chromium的链接定位到了桌面的快捷方式，我由于各种原因似乎只能使用这一种AI翻译

**Comment by HIllya51** [comment]
刷新
