### ISSUE TITLE
關於一些功能的添加建議，與一些其他功能上的問題

### ISSUE THREAD

**Issue by chlbc** [HIllya51/LunaTranslator#857]
### Expected behavior 预期的功能

作者您好，非常感謝您先前增加了專有名詞相關的功能，真的滿不錯用的！
不過在測試之後，有遇到一些問題，
希望如果可以的話，是否能請您考慮新增以下的功能，
以及調整一些功能的處理方式。

目前版本：v5.3.3 64bit

* **同時移動多個詞條的順序**
在「專有名詞優化」和「翻譯結果修正」中，
目前上移、下移功能只能對單個詞條作用，
但如果想一次移動多個詞條的順序的話就只能一條一條地移，
因此希望上移、下移可以添加一次移動所有選取詞條的功能。
（類似刪除詞條可以一次刪掉已選取的多個詞條那樣）

* **匯入詞條功能**
在「專有名詞優化」和「翻譯結果修正」中，
目前若要把其他電腦、使用者的詞條匯入本地的話，
只能打開該 json 檔來手動將差異處複製到本地的 json 中，
對於詞條的分享比較沒有那麼方便。
因此建議可以新增匯入功能，
讓程式可以直接讀取對應的 json 設定檔，
使那些與本地端「不完全相同的詞條」能夠匯入，
如此對於詞條的共享也會比較方便。
（匯出的話感覺可以以「匯出目前已選取的詞條」來處理，
不過因為目前可以直接複製整個 json 設定檔，
感覺相對來說該功能的重要性比較低些）

* **歷史翻譯無法自動捲動到最新紀錄的問題**
一般情況下開啟歷史翻譯時，
會自動將內容捲動到最下方，
以看到最新一筆的翻譯紀錄。
不過如果在頁面中往上捲動，點擊或選取先前的翻譯文字後，
關閉歷史翻譯並讓遊戲跳個幾句對話後，
再開啟歷史翻譯，
就會發現歷史翻譯不會自動將內容捲動到最下方，
而是卡在先前點擊或選取文字的地方。
目前若要再讓它能夠自動捲動到最下方的話，
只能手動將歷史翻譯捲到最下方，
並且點擊最新翻譯下方的空白處，
才能再次讓歷史翻譯自動將內容捲動到最下方。
因此建議可以修改該部份處理方式，
使一開啟歷史翻譯時，內容必定捲動到最下方，
比較符合 Galgame 中履歷的邏輯。

* **goo 辭書網頁顯示問題**
在辭書選擇「goo」、網頁顯示方法選擇目前三種方式任意一種、
並勾選「使用原型查詢」的情況下，
若查詢的辭彙有多個查詢結果的話，
會直接以原始網頁顯示，而非僅顯示辭彙解釋本身。
例如點擊：「あんなでかい地震があったっていうのに、 たいしたもんだ。」
之中的「いう」來查詢，結果如下：
![image](https://github.com/HIllya51/LunaTranslator/assets/42777336/7bac9900-2844-4124-baae-1e364b4e1259)
點擊第一個詞條後，就會顯示：
![image](https://github.com/HIllya51/LunaTranslator/assets/42777336/e029f262-19cd-4626-8306-cd70da9009e6)
而非單純的辭彙解釋。

* **在 4K 等高 DPI 環境下，高質量算法的縮放黑邊問題**
在解析度為 3840 x 2160 的環境中，
使用 Anime4K 和 ACNet 縮放某些遊戲時會出現遊戲四周有黑邊的問題，
但若使用其他不會發生黑邊的 FSR 等算法，放大後畫面會不太清晰。
目前有參閱[這篇 Issue](https://github.com/HIllya51/LunaTranslator/issues/533#issuecomment-1966039970) 和[這篇 Magpie 的效果說明](https://github.com/Blinue/Magpie/wiki/%E5%86%85%E7%BD%AE%E6%95%88%E6%9E%9C%E4%BB%8B%E7%BB%8D)，
閱覽後發現應該是因為 Anime4K 和 ACNet 只能放大兩倍、
而遊戲畫面尺寸低於 1920 x 1080 的遊戲放大兩倍無法完整覆蓋 3840 x 2160 所致。
目前我這邊透過上面 Issue 給的方法，直接修改 Magpie 的設定檔，
多加一條 Anime4K + ACNet 的設定後，
就不會發生黑邊問題了，且畫面也滿清晰的。
因此建議要不要考慮直接在原始設定中先加入：
`{ "name": "Anime4K + ACNet (High DPI Use)", "effects": [ { "name": "Anime4K\\Anime4K_Upscale_VL" }, { "name": "ACNet" } ] },`
`{ "name": "Anime4K + ACNet + FSR (High DPI Use)", "effects": [ { "name": "Anime4K\\Anime4K_Upscale_VL" }, { "name": "ACNet" }, { "name": "FSR\\FSR_EASU", "scalingType": 1, "scale": { "x": 1.0, "y": 1.0 } } ] }`
或者是其他可用於高 DPI 環境的初始設定呢

### Alternative behavior (optional) 近似的功能（可选）

以上，謝謝大佬閱讀我上面的這篇文字！

**Comment by HIllya51** [comment]
> * **同時移動多個詞條的順序**
>   在「專有名詞優化」和「翻譯結果修正」中，
>   目前上移、下移功能只能對單個詞條作用，
>   但如果想一次移動多個詞條的順序的話就只能一條一條地移，
>   因此希望上移、下移可以添加一次移動所有選取詞條的功能。

不可以，太麻烦，实际上这可以通过几个键的组合来时间，所以没必要。
 
> * **匯入詞條功能**
>   在「專有名詞優化」和「翻譯結果修正」中，
>   目前若要把其他電腦、使用者的詞條匯入本地的話，
>   只能打開該 json 檔來手動將差異處複製到本地的 json 中，
>   對於詞條的分享比較沒有那麼方便。
>   因此建議可以新增匯入功能，
>   讓程式可以直接讀取對應的 json 設定檔，
>   使那些與本地端「不完全相同的詞條」能夠匯入，
>   如此對於詞條的共享也會比較方便。
>   （匯出的話感覺可以以「匯出目前已選取的詞條」來處理，
>   不過因為目前可以直接複製整個 json 設定檔，
>   感覺相對來說該功能的重要性比較低些）

可以

> * **歷史翻譯無法自動捲動到最新紀錄的問題**
>   一般情況下開啟歷史翻譯時，
>   會自動將內容捲動到最下方，
>   以看到最新一筆的翻譯紀錄。
>   不過如果在頁面中往上捲動，點擊或選取先前的翻譯文字後，
>   關閉歷史翻譯並讓遊戲跳個幾句對話後，
>   再開啟歷史翻譯，
>   就會發現歷史翻譯不會自動將內容捲動到最下方，
>   而是卡在先前點擊或選取文字的地方。
>   目前若要再讓它能夠自動捲動到最下方的話，
>   只能手動將歷史翻譯捲到最下方，
>   並且點擊最新翻譯下方的空白處，
>   才能再次讓歷史翻譯自動將內容捲動到最下方。
>   因此建議可以修改該部份處理方式，
>   使一開啟歷史翻譯時，內容必定捲動到最下方，
>   比較符合 Galgame 中履歷的邏輯。

就是专门这样做的，不然我想看前面的内容，一下子给我刷到最后了怎么办。

> * **goo 辭書網頁顯示問題**
>   在辭書選擇「goo」、網頁顯示方法選擇目前三種方式任意一種、
>   並勾選「使用原型查詢」的情況下，
>   若查詢的辭彙有多個查詢結果的話，
>   會直接以原始網頁顯示，而非僅顯示辭彙解釋本身。
>   例如點擊：「あんなでかい地震があったっていうのに、 たいしたもんだ。」
>   之中的「いう」來查詢，結果如下：
 
>   點擊第一個詞條後，就會顯示：
 
>   而非單純的辭彙解釋。

goo就是这样的，没有办法。

> * **在 4K 等高 DPI 環境下，高質量算法的縮放黑邊問題**
>   在解析度為 3840 x 2160 的環境中，
>   使用 Anime4K 和 ACNet 縮放某些遊戲時會出現遊戲四周有黑邊的問題，
>   但若使用其他不會發生黑邊的 FSR 等算法，放大後畫面會不太清晰。
>   目前有參閱[這篇 Issue](https://github.com/HIllya51/LunaTranslator/issues/533#issuecomment-1966039970) 和[這篇 Magpie 的效果說明](https://github.com/Blinue/Magpie/wiki/%E5%86%85%E7%BD%AE%E6%95%88%E6%9E%9C%E4%BB%8B%E7%BB%8D)，
>   閱覽後發現應該是因為 Anime4K 和 ACNet 只能放大兩倍、
>   而遊戲畫面尺寸低於 1920 x 1080 的遊戲放大兩倍無法完整覆蓋 3840 x 2160 所致。
>   目前我這邊透過上面 Issue 給的方法，直接修改 Magpie 的設定檔，
>   多加一條 Anime4K + ACNet 的設定後，
>   就不會發生黑邊問題了，且畫面也滿清晰的。
>   因此建議要不要考慮直接在原始設定中先加入：
>   `{ "name": "Anime4K + ACNet (High DPI Use)", "effects": [ { "name": "Anime4K\\Anime4K_Upscale_VL" }, { "name": "ACNet" } ] },`
>   `{ "name": "Anime4K + ACNet + FSR (High DPI Use)", "effects": [ { "name": "Anime4K\\Anime4K_Upscale_VL" }, { "name": "ACNet" }, { "name": "FSR\\FSR_EASU", "scalingType": 1, "scale": { "x": 1.0, "y": 1.0 } } ] }`
>   或者是其他可用於高 DPI 環境的初始設定呢

有需要的自会自己设置，没必要画蛇添足。

**Comment by chlbc** [comment]
> 同時移動多個詞條的順序
> 不可以，太麻烦，实际上这可以通过几个键的组合来时间，所以没必要。
原本是預想說是否能夠透過類似迴圈的方式，依序一個一個修改選取的詞條順序，
可能沒考慮到該需求的麻煩之處，不好意思

另外方便詢問下「通过几个键的组合来时间」是指使用者可以透過一些其他的方法來達到同樣的效果嗎？
如果是的話具體而言大概該如何操作呢


> 匯入詞條功能
> 想了一下 感觉没什么意义。
好的，那我這邊還是在需要時手動匯入好了。

> 歷史翻譯無法自動捲動到最新紀錄的問題
> 就是专门这样做的，不然我想看前面的内容，一下子给我刷到最后了怎么办。
那如果可以的話，能否考慮加一個「捲動至最下」的按鈕，或者是類似「自動捲動」的 checkbox 或設定呢
因為若使用 Moonlight、於手機端進行操作的話，
若捲動到太上面的地方，要再捲動到最下方的話在操作上不是那麼地方便，
因此想請您能否考慮看看加上此功能。


> 在 4K 等高 DPI 環境下，高質量算法的縮放黑邊問題
> 有需要的自会自己设置，没必要画蛇添足。
我這邊是想說不是每個使用者都了解如何直接透過修改設定檔來處理這種黑邊的情況，
才提出此建議。
還是我這邊之後有時間的話，
能否撰寫該部份的說明文檔，
並於最後提到此情況之解法， 
然後 pull 到 LunaTranslator_tutorial 那邊去呢


以上，也謝謝作者的回覆！

**Comment by HIllya51** [comment]
> > 歷史翻譯無法自動捲動到最新紀錄的問題
> > 就是专门这样做的，不然我想看前面的内容，一下子给我刷到最后了怎么办。
> 
> 那如果可以的話，能否考慮加一個「捲動至最下」的按鈕，或者是類似「自動捲動」的 checkbox 或設定呢 因為若使用 Moonlight、於手機端進行操作的話， 若捲動到太上面的地方，要再捲動到最下方的話在操作上不是那麼地方便， 因此想請您能否考慮看看加上此功能。

https://github.com/HIllya51/LunaTranslator/commit/53cb12f5586dc3e89bc1927774a2c3de8e394c30

> 
> > 在 4K 等高 DPI 環境下，高質量算法的縮放黑邊問題
> > 有需要的自会自己设置，没必要画蛇添足。
> 
> 我這邊是想說不是每個使用者都了解如何直接透過修改設定檔來處理這種黑邊的情況， 才提出此建議。 還是我這邊之後有時間的話， 能否撰寫該部份的說明文檔， 並於最後提到此情況之解法， 然後發 pull request 到 LunaTranslator_tutorial 那邊去呢
> 

你想写的话可以写一下，我其实也没怎么用过magpie的高级功能，不知道怎么弄。
