### ISSUE TITLE
DeepLX no longer working due to changed API call requirement?

### ISSUE THREAD

**Issue by theboymeister** [HIllya51/LunaTranslator#858]
### Version 程序版本

5.5.0

### bug's screenshot 错误截图

DeepLX used to work flawlessly, but there's apparently an issue with the host at some point and it needed to be taken down. And I'm not sure if it's up again, but it points to this thread: https://linux.do/t/topic/111737/271

Sorry if I'm not being clear, I'm not too good with backend stuff.

### Reproduction steps 复现步骤

Use DeepLX to translate anything; though I used OCR.
![image](https://github.com/HIllya51/LunaTranslator/assets/163517230/4bb1b331-6f16-422d-b725-c9cf1ba83bde)

**Comment by HIllya51** [comment]
😅use your api
![屏幕截图 2024-06-29 142924](https://github.com/HIllya51/LunaTranslator/assets/101191390/4ed42625-305e-4061-994b-8833c8634e5c)
