### ISSUE TITLE
随机出现的漏翻现象

### ISSUE THREAD

**Issue by Laniaidea** [HIllya51/LunaTranslator#86]
用的原版Textractor提取文本+Luna监视剪切板，任意翻译api，由于找不到规律不太好复现。随机出现的漏翻，之后跳回去重来一遍未见漏翻，可见不是原文本或者api的问题
![2022-11-27](https://user-images.githubusercontent.com/84361865/204108816-2de307d8-2be8-453a-86f3-2045de37408f.png)
![2022-11-27 (1)](https://user-images.githubusercontent.com/84361865/204108819-17e31298-34a2-40e9-b6c8-82d6947d2515.png)

**Comment by HIllya51** [comment]
这个是textractor的问题，偶尔会有句子没有复制到剪贴板，我也遇到过。

**Comment by Laniaidea** [comment]
> 这个是textractor的问题，偶尔会有句子没有复制到剪贴板，我也遇到过。
用隔壁的tsubaki监视剪切板不会漏翻

**Comment by HIllya51** [comment]
漏的时候你开个记事本ctrlv一下就知道了，就是没有复制到剪贴板，我都遇到好几次了
