### ISSUE TITLE
这个功能失效了：自动隐藏窗口

### ISSUE THREAD

**Issue by jpACGlover** [HIllya51/LunaTranslator#862]
### Version 程序版本

5.6.0

### bug's screenshot 错误截图

![截图_20240701084232](https://github.com/HIllya51/LunaTranslator/assets/171327971/ea10baba-1dd8-4393-ab80-488658811293)

### Reproduction steps 复现步骤

无论设置多少秒隐藏延时都不会自动隐藏

**Comment by HIllya51** [comment]
1x
