### ISSUE TITLE
内嵌翻译增加设定多少个文字换行功能

### ISSUE THREAD

**Issue by yogai0319** [HIllya51/LunaTranslator#865]
### Expected behavior 预期的功能

在设置/文本处理/文本预处理设置中，如果启用“过滤换行符”规则，可以减少因为文本换行导致翻译时语义不完整或错误的情况。但是过滤换行符后，翻译结果只有一行文字，字数较多时会导致内嵌翻译的文字超过游戏文字框显示的字数，翻译内容显示不全。希望能在内嵌翻译里增加设定多少个文字换行的功能。
![文本处理设置过滤换行符](https://github.com/HIllya51/LunaTranslator/assets/174312700/ff34c8a6-0033-4f7b-a07b-5c5faab24dfb)

**Comment by HIllya51** [comment]
翻译优化->自定义优化->自己写脚本把翻译加换行。

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/af553fa06e97c935323fcf2ebff23ae86221fd87

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/57a2531729193708c009e3c25e5e12fd962b1bdd
