### ISSUE TITLE
BGI引擎游戏闪退问题及其他

### ISSUE THREAD

**Issue by bzkmsjy** [HIllya51/LunaTranslator#866]
### Version 程序版本

5.6.0

### bug's screenshot 错误截图

无

### Reproduction steps 复现步骤

首先说明我是视障，主要用这个工具自动朗读游戏文本来了解剧情（上次反馈加入的语音不被打断很好用，谢谢），我的Luna设置全部默认简体中文，语音合成是EdgeTTS，开游戏就用HOOK自动搜到的结果基本都能搜到文本。

我最近在推kirakira煌煌舞台和超电激冲锋卫士这两个游戏，都是BGI的程序，游玩过程中Luna会随机发生爆音+闪退，有时候能玩几个小时，有时候十几分钟就会闪退一次。本来以为是网络问题或者微软的语音合成引擎问题，但是试了试别的游戏没有碰到这个问题，只有BGI的程序能复现。

另外，频繁闪退似乎会让“检测到游戏时自动开始”这个功失效，我的Luna现在都不会自动开始了，每次都要去已保存的游戏里双击游戏封面才能恢复，或者重新选择一次游戏和文本。

还有一个闪退问题是快捷键里的“选择游戏”，我不管设置什么快捷键，使用的时候Luna都会闪退，必须鼠标按菜单栏按钮才行。

**Comment by HIllya51** [comment]
是游戏闪退还是软件闪退？把游戏发给我。

**Comment by bzkmsjy** [comment]
> 是游戏闪退还是软件闪退？把游戏发给我。

是Lunatranslator爆音和闪退，游戏没闪退，游戏链接，无密码https://apps.lexar.com/s/Q5mzlSQW

**Comment by HIllya51** [comment]
应该修复了
