### ISSUE TITLE
内嵌卡顿问题是否有可能解决？

### ISSUE THREAD

**Issue by LeftOwlRight** [HIllya51/LunaTranslator#867]
### Question 问题

启用内嵌后，每次有新文本弹出，游戏都会卡住半秒左右，这个问题稍微搜索了一下issue和discussion，没有看到有人提。
不知是否是因为我玩的不是galgame而是3D游戏才有的情况？亦或是我选用了TGW语言模型翻译导致的？不知这个问题是否有办法解决？
玩的游戏是jazzpunk，程序设置除了为使TGW语言模型翻译能正常运行和文本内嵌显示的设置以外，基本都是默认设置了。
软件版本是5.6
![F516C8A413247D049772C1619675AC8B](https://github.com/HIllya51/LunaTranslator/assets/78366427/1e744759-345d-4c22-b0ac-1c5eae9a2332)

**Comment by HIllya51** [comment]
他是在等待翻译，不是卡顿。不然日文都显示出来了，还怎么内嵌？

**Comment by LeftOwlRight** [comment]
> 他是在等待翻译，不是卡顿。不然日文都显示出来了，还怎么内嵌？

是的，我清楚这是在等待翻译，就是想问一下能不能在翻译出来之前先显示原文，翻译好后再内嵌。就是...分布计算？看看这样能不能解决卡顿问题？

**Comment by LeftOwlRight** [comment]
@HIllya51 
如果at您打扰到您了真是不好意思！
只是担心您过早地关闭了这一话题没有看到我的解释。再次表示抱歉。

**Comment by HIllya51** [comment]
> 他是在等待翻译，不是卡顿。不然日文都显示出来了，还怎么内嵌？

我都说了，根本不可能做到。
