### ISSUE TITLE
V5.7.0文本字體樣式

### ISSUE THREAD

**Issue by a73420521** [HIllya51/LunaTranslator#868]
### Question 问题

請問最新版中有考慮將V3.7.0中的空心字體加回來嗎?
V5.7.0中的4種字體無論怎麼設定都沒法呈現空心字體的效果。
![1](https://github.com/HIllya51/LunaTranslator/assets/87113124/c6af4ce1-a2ae-42f0-8f01-f79e541bfda8)
![2](https://github.com/HIllya51/LunaTranslator/assets/87113124/765a291f-8649-4ba8-86d4-1bc9b825123f)

**Comment by HIllya51** [comment]
描边字体1
