### ISSUE TITLE
Brief translation

### ISSUE THREAD

**Issue by Detemis** [HIllya51/LunaTranslator#869]
### Question 问题

I have a maximum word limit of 1000 words for translation, but when I translate a text, the program translates a maximum of 10-20 words.

![photo_2024-07-02_09-58-18](https://github.com/HIllya51/LunaTranslator/assets/125899628/d45861c2-6286-49b6-b546-be31fad2b079)

Here you can see that the limit is 1000
![photo_2024-07-02_10-00-56](https://github.com/HIllya51/LunaTranslator/assets/125899628/bfb712d5-f8a1-4be7-9b8b-6088154782fd)

How to fix it?

**Comment by Detemis** [comment]
> ### Question 问题
> I have a maximum word limit of 1000 words for translation, but when I translate a text, the program translates a maximum of 10-20 words.
> 
> ![photo_2024-07-02_09-58-18](https://private-user-images.githubusercontent.com/125899628/344910053-d45861c2-6286-49b6-b546-be31fad2b079.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDQwMTEsIm5iZiI6MTcxOTkwMzcxMSwicGF0aCI6Ii8xMjU4OTk2MjgvMzQ0OTEwMDUzLWQ0NTg2MWMyLTYyODYtNDliNi1iNTQ2LWJlMzFmYWQyYjA3OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwNzAxNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzU2OWNkNTMyMzA5M2IzZGRlZGY2ZmYwNzIwMTkxYjk3NjlmOTg3NTNjYjAyZTVkZjk0ZTFjNGUwMGJiNmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qak6LGvSOT_uD_DWLhpFvgO8bG3oMZ4Ug7YKofWzVjg)
> 
> Here you can see that the limit is 1000
![photo_2024-07-02_10-00-56](https://github.com/HIllya51/LunaTranslator/assets/125899628/958f96bd-a588-4885-868e-a39e819b88df)

> How to fix it?

**Comment by HIllya51** [comment]
don't know.

**Comment by Ameryou** [comment]
<img width="626" alt="kk" src="https://github.com/HIllya51/LunaTranslator/assets/100940911/5c104438-bc5b-4015-8614-c11139934a2c">
