### ISSUE TITLE
建议hook到的文本可以更改页码

### ISSUE THREAD

**Issue by Laniaidea** [HIllya51/LunaTranslator#87]
一个特殊情况，如天津罪的汉化版，h无汉化所以要用翻译器，但是直接直接注入这个汉化的程序会因为页码问题导致乱码，建议可以手动改成932、936等以解决这类问题
![屏幕截图 2022-11-27 185733](https://user-images.githubusercontent.com/84361865/204131710-6620bb5b-e349-4ebe-b21a-8858387eeb38.png)
![屏幕截图 2022-11-27 185904](https://user-images.githubusercontent.com/84361865/204131712-726511f5-4c08-4a4c-a680-7ed9c68c176e.png)

**Comment by HIllya51** [comment]
以支持
