### ISSUE TITLE
Q&A tesseract 全是乱码

### ISSUE THREAD

**Issue by asukaminato0721** [HIllya51/LunaTranslator#872]
### Question 问题

![10WVF7MZJ6 }Z(RAGVYB(WL](https://github.com/HIllya51/LunaTranslator/assets/30024051/1e62290c-ab6e-442e-a72a-84d728d5c06d)

A: 把对话框背景透明度改一下
群主: tess 就是很垃圾，有背景干扰啥都识别不了。

**Comment by HIllya51** [comment]
😂
