### ISSUE TITLE
deepseek启用流式出现报错

### ISSUE THREAD

**Issue by TXT2GAM** [HIllya51/LunaTranslator#875]
### Version 程序版本

5.7.2exe版

### bug's screenshot 错误截图

![image](https://github.com/HIllya51/LunaTranslator/assets/134926662/fbb47c70-1bcd-437a-b1e6-686dba6e2fef)

### Reproduction steps 复现步骤

api官网：https://platform.deepseek.com/
官网写的这个模型完全支持openai的请求格式，模型名deepseek-chat
不启用流式是正常的，但是启用就会如图上报错。

来自官网：
stream
如果设置为 True，将会以 SSE（server-sent events）的形式以流式发送消息增量。消息流以 data: [DONE] 结尾。

**Comment by TXT2GAM** [comment]
key：sk-806b260d338647a083b23b585b6674d5
base_ur：https://api.deepseek.com
model：deepseek-chat
用我的key测试，看到这条回复请删除

**Comment by HIllya51** [comment]
我测试没问题啊。你运行一下LunaTranslator_debug.exe给我看看详细的报错

**Comment by TXT2GAM** [comment]
![image](https://github.com/HIllya51/LunaTranslator/assets/134926662/89cfec51-b9f9-4502-9e6f-35b4b7576391)

**Comment by HIllya51** [comment]
你把这个文件替换到network/libcurl里面再给我看看log？好像和代理有关系

[requests.zip](https://github.com/user-attachments/files/16125652/requests.zip)

**Comment by TXT2GAM** [comment]
试了下可以了
