### ISSUE TITLE
Request to add "eztrans" offline translation

### ISSUE THREAD

**Issue by fsdfoijwe4orhj34** [HIllya51/LunaTranslator#876]
### Expected behavior 预期的功能

Request to add "eztrans" offline translation
eztrans is a program that translates Japanese into Korean
a place to refer to
https://github.com/sokcuri/anemone
https://github.com/sokcuri/ehnd
https://github.com/Dangetsu/vnr
I think LunaTranslator is a very good program.
I am not good at English, so I used Papago translation.

**Comment by HIllya51** [comment]
1. I can't get the program
2. Why you want to use such a old program, it must even be much worse than google.

**Comment by HIllya51** [comment]
![屏幕截图 2024-07-09 200823](https://github.com/HIllya51/LunaTranslator/assets/101191390/4ae39595-3903-43ae-b1f7-6052b0e37379)

What the hell is this? I can't understand it at all.
