### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by NekoIriyaRu** [HIllya51/LunaTranslator#877]
### Version 程序版本

5.8.0

### bug's screenshot 错误截图

https://github.com/HIllya51/LunaTranslator/assets/171213503/7d144013-cd61-49b5-90ee-7d9d413a5950

### Reproduction steps 复现步骤

...

**Comment by HIllya51** [comment]
what do you want to say

**Comment by NekoIriyaRu** [comment]
> what do you want to say
In previous versions of the program, this image was displayed across all language options.
--
Эта картинка в более старых версиях программы раньше отображалась во всех языках.
![image](https://github.com/HIllya51/LunaTranslator/assets/171213503/b98f6402-0643-4f67-8758-66a420d224c8)

**Comment by HIllya51** [comment]
this is wechat's QR code for sponsorship, it is not available in other countries.

**Comment by NekoIriyaRu** [comment]
> this is wechat's QR code for sponsorship, it is not available in other countries.

Are you planning on creating a boosty.to account specifically for residents of CIS countries and Russia?

**Comment by NekoIriyaRu** [comment]
boosty.to is like a Russian version of patreon.com

**Comment by HIllya51** [comment]
Registering foreign platforms in China is  very inconvenient, and registering patreon has already taken a lot of effort from me, so I have no plans to register other platforms

**Comment by NekoIriyaRu** [comment]
> Registering foreign platforms in China is very inconvenient, and registering patreon has already taken a lot of effort from me, so I have no plans to register other platforms

Users from CIS countries often experience problems with paying for Patreon subscriptions.
