### ISSUE TITLE
新版本的在线翻译结果获取比老版本的慢一点

### ISSUE THREAD

**Issue by 123456ds** [HIllya51/LunaTranslator#879]
### Question 问题

翻译过程没有启动代理服务；
尝试过纯净运行新版本还是比老版本慢；
请求间隔设置为0.1一样比老版本慢
https://p.sda1.dev/18/18860f6c60cc8781b36edabd92d276a8/屏幕截图 2024-07-10 100933.png
录屏文件：
https://pixeldrain.com/u/xiMKvuGF

**Comment by HIllya51** [comment]
3.14是什么鬼。。根本没有这个版本
你把旧版打包发我看一下

**Comment by HIllya51** [comment]
已修复

**Comment by 123456ds** [comment]
> 3.14我是什么鬼 。
旧版本
https://pixeldrain.com/u/8sTi1XmU

5.9.1相对于5.9的在线翻译速度有提升

**Comment by HIllya51** [comment]
重新下，我后面又改了
