### ISSUE TITLE
The program doesn't save the selected hook after restarting.

### ISSUE THREAD

**Issue by NekoIriyaRu** [HIllya51/LunaTranslator#882]
### Version 程序版本

5.9.0

### bug's screenshot 错误截图

https://ttneko.dev.tc/files/my/unhooked.mp4

### Reproduction steps 复现步骤

....

**Comment by HIllya51** [comment]
some game cant match the saved context because their contexts are depending on a runtime memory address, which is dynamic changing everytime the game started

**Comment by NekoIriyaRu** [comment]
> some game cant match the saved context because their contexts are depending on a runtime memory address, which is dynamic changing everytime the game started

Ok
