### ISSUE TITLE
默認字體修改提議

### ISSUE THREAD

**Issue by chlbc** [HIllya51/LunaTranslator#884]
### Expected behavior 预期的功能

目前 5.10.1 版本的原文字體、譯文字體和介面字體是使用 QFontDatabase.SystemFont.GeneralFont 來取得的，然而它取得的並非現在的 Windows 版本所默認的介面字體，而是比較接近 WinXP 時代的默認字體。
以繁體中文版為例，介面字體演變歷程為：PMingLiU（新細明體，WinXP）->Microsoft Jhenghei（微軟正黑體，Vista、Win7）->Microsoft Jhenghei UI（Win8 以後）
然而，目前 QFontDatabase.SystemFont.GeneralFont 於繁體中文版中仍是選擇 XP 時代默認字體的新細明體（簡體中文版應該是宋体），但這些字體不支援 ClearType，導致其在現代屏幕顯示上不如微軟正黑體（繁體）或微软雅黑（簡體）等字體，所以會建議作者您是否能考慮修改默認字體選擇，使其更接近新版本 Windows 的介面字體選擇。

參考網路上的[默認字體表](https://www.swtoo.com/extensis/suitcase_9_help/w10/)後，我這邊之前有做一份 dict：
```json
    "font_type_default": {
        "zh": "Microsoft YaHei",
        "ja": "Yu Gothic",
        "en": "Segoe UI",
        "ru": "Segoe UI",
        "es": "Segoe UI",
        "ko": "Malgun Gothic",
        "fr": "Segoe UI",
        "cht": "Microsoft JhengHei",
        "vi": "Segoe UI",
        "tr": "Segoe UI",
        "pl": "Segoe UI",
        "uk": "Segoe UI",
        "it": "Segoe UI",
        "ar": "Segoe UI",
        "th": "Leelawadee",
        "bo": "Microsoft Himalaya"
    },
    "setting_font_type_default": {
        "zh": "Microsoft YaHei UI",
        "ja": "Yu Gothic UI",
        "en": "Segoe UI",
        "ru": "Segoe UI",
        "es": "Segoe UI",
        "ko": "Malgun Gothic",
        "fr": "Segoe UI",
        "cht": "Microsoft JhengHei UI",
        "vi": "Segoe UI",
        "tr": "Segoe UI",
        "pl": "Segoe UI",
        "uk": "Segoe UI",
        "it": "Segoe UI",
        "ar": "Segoe UI",
        "th": "Leelawadee UI",
        "bo": "Microsoft Himalaya"
    },
```
以上內容是根據目前 Win10 的默認字體清單選擇，font_type_default 是用於一般文字（原文、譯文）；setting_font_type_default 則是用於介面文字。
建議作者是否能考慮參考以上的 dict，或是使用其他選擇方案，讓默認字體能更清晰地被閱讀。

---
### 原文文本字體的問題
目前翻譯來源語言預設為日文，然而原文字體卻是跟隨 QFontDatabase.SystemFont.GeneralFont，這會導致日文漢字在 OS 語言為繁體中文、簡體中文等非日文的場合以中文字體來顯示。但是很多日文漢字寫法跟簡體中文和繁體中文皆不相同，因此這樣的默認設置亦不利於日語學習者學習。
因此，建議作者您能考慮看看是否能修改成以下兩個方案之一：
1. 將原文字體默認設為「Yu Gothic」（游ゴシック）
2. 在原文字體旁多添加一個「跟隨源語言設定」的 checkbox，該 checkbox 默認勾選，在勾選時禁用原文字體的選項，且會跟隨著語言設置中源語言的修改自動更換成對應語言的原文字體
---
### 以上方案缺點
因為以上建議方案是在 WIn10 以上環境提議，因此在較低版本（Win7、WinXP 等）可能會因為系統中缺字體而導致其自動選用其他字體——繁體中文版中缺字體我這邊測試是會跳到新細明體，因此缺字體時應該也只是跳回等同 QFontDatabase.SystemFont.GeneralFont 的設置。
因此就算因系統版本較舊而缺字體，也是會變得跟目前 LunaTranslator 5.10.1 一樣的字體選擇而已，所以還是希望作者您能夠考慮看看以上的提議。

**Comment by chlbc** [comment]
其實不用額外考慮缺字體的問題，而這樣改甚至能夠在降低缺字、或者您所說的亂碼的發生率。

以英文系統用戶翻譯日文遊戲為例：
若以目前 5.10.1 版本的情況而言，原文字體會被自動設置為英文字體。然而一般英文字體並不會有假名、漢字等字符，因此在翻譯、顯示日文時，系統會自動回退到能顯示這些字符的字體來顯示（例如其他日文、中文等字體），但若失敗則會顯示空白、豆腐或方塊等（若不幸回退到純符號字體等情況也會有看似亂碼的情形發生）。
但若以我這邊上面提到的方案的話，對於 Win10 以上的英文用戶而言，因為指定的 Yu Gothic 是各個語言系統（包含日文以外）都會預載的日文字體，因此程序就可以直接以默認選擇的 Yu Gothic 顯示日文，而不用像目前的 5.10.1 版一樣：先用英文字體顯示 -> 程式發現缺字 -> 回退到其他字體，如此就降低了因字體缺字導致顯示結果不如預期的可能性；
對於舊版本 Windows 的英文用戶而言，就算沒有 Yu Gothic，程序也不會報錯，而是會像目前的 5.10.1 版類似的流程：程序發現 Yu Gothic 不存在 -> 設置裡自動改選默認英文字體 -> 翻譯原文時先嘗試用英文字體顯示 -> 程式發現缺字 -> 回退到其他字體。

故此修改對於使用默認設置的 Win10 用戶而言，用戶體驗一定是提升的；對於舊版 Windows 的用戶而言，也只是和現在的 5.10.1 版一樣而已，也不太需要做額外的相容措施，因此建議您能再考慮看看以上之提議。

**Comment by chlbc** [comment]
不過 #511 確實滿神奇的，我這邊看起來介面至少使用了三個以上的字體。我能辨識的有：英文的 Arial、日文的 MS UI Gothic，和簡體中文的宋体。該用戶應該是在日文系統下使用該程序的，但會發生這個情況我這邊能想到的只有字體回退過程中不小心回退到了某個符號字體導致的，因為這些符號字體通常會將一般文字（英文、數字等）的字碼改成顯示符號，因此就有機會發生此情況；但也不排除是其他原因就是了。

**Comment by HIllya51** [comment]
算了吧，也太麻烦了

**Comment by chlbc** [comment]
了解，那我這邊先關 Issue 好了，謝謝大佬的回覆！
