### ISSUE TITLE
截图问题

### ISSUE THREAD

**Issue by Z9wind** [HIllya51/LunaTranslator#886]
### Question 问题

以前的截图好像会创建两个文件，一个是不带窗口边缘的截图一个是带窗口边缘的截图，现在不知道为什么不带窗口边缘的截图会出现这样只截取到局部发大的部分，是bug吗？
最新版本截图的两个文件：
<img width="770" alt="2024-07-13-19-08-29_winrt" src="https://github.com/user-attachments/assets/1530f8a3-4181-4229-b8b7-bedb7192ef08">

![2024-07-13-19-08-29_gdi](https://github.com/user-attachments/assets/e819ca09-3d4d-4a9f-9c42-6fe610b6293f)

之前版本截图的两个文件：
![2024-05-30-01-13-44_gdi](https://github.com/user-attachments/assets/e3bac6f8-d9fc-48d6-ad95-d68de5738577)
<img width="1192" alt="2024-05-30-01-13-44_winrt" src="https://github.com/user-attachments/assets/e3225f2c-2909-4da8-8461-0e501a724b51">

**Comment by Z9wind** [comment]
而且还有个问题是以前好像不会截到鼠标的，现在有鼠标了

**Comment by HIllya51** [comment]
无法复现

**Comment by Z9wind** [comment]
> 无法复现

刚刚试验了下，发现好像是游戏还是MAGPIE的问题...另一个游戏打开，没用magpie就正常

**Comment by Z9wind** [comment]
又试了一下好像是这个游戏的问题，不知道是什么怪引擎TT如果大大有需要的话我可以提供

**Comment by HIllya51** [comment]
给我看看吧。
