### ISSUE TITLE
Doesn't show the translation 

### ISSUE THREAD

**Issue by Yuriuori** [HIllya51/LunaTranslator#887]
### Version 程序版本

newest version

### bug's screenshot 错误截图

I was trying to translate with Arabic language but didn't really work
![Screenshot 2024-07-13 164938](https://github.com/user-attachments/assets/ae5e5042-3716-43b7-8ea1-d1be2c3e753d)
it's working with all the language but for Arabic doesn't work at all

### Reproduction steps 复现步骤

.

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/b86f69da74d05b149ca3687853e959a344d85df7

**Comment by Yuriuori** [comment]
Does the new update fix it ? i still don't see the arabic shown
