### ISSUE TITLE
Ocr

### ISSUE THREAD

**Issue by Oplay66** [HIllya51/LunaTranslator#888]
### Expected behavior 预期的功能

是否可以加入这项lens ocr？https://github.com/AuroraWright/owocr

**Comment by HIllya51** [comment]
你知道这是个什么吗？

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/b16e6d758b5fd571955fe11b30a2246b07377722

**Comment by Oplay66** [comment]
不清楚。这是在某个项目看到的，如果造成困扰实在是不好意思。

恍兮惚兮 ***@***.***> 于 2024年7月14日周日 上午12:50写道：
