### ISSUE TITLE
BMP_Font Error 

### ISSUE THREAD

**Issue by Redevil387** [HIllya51/LunaTranslator#889]
### Version 程序版本

5.7.2

### bug's screenshot 错误截图

![Screenshot (146)](https://github.com/user-attachments/assets/117b380a-009a-40a5-8ede-d3aa99ca51dc)

### Reproduction steps 复现步骤

While playing certain Visual Novels (MahoxRoba in this case) I run into a BMP_Font error which doesn't occur while running the Visual Novel without LunaTranslator.
I'm uncertain as to what causes the error but suspect it's related to the game's connection to LunaTranslator.

The error occurs even if Hook, OCR, and Clipboard input option are disabled.

Even if its only for a handful of titles I'd appreciate assistance in identifying the cause and/or bypassing this issue.

I set up LunaTranslator_Admin.exe andgo into my games and select MaxoxRoba and play until a certain point when the BMP+Font error occurs. 
When I opened the game raw and played past a few dialogues and re-open Lunatranslator I'm able to temporarily skip the error but it reoccurs a few scenes later.

**Comment by HIllya51** [comment]
What you said is contradictory. Since you still get an error when you don't enable the hook, what does that have to do with me? It can only be due to your failure to run the game correctly.

**Comment by Redevil387** [comment]
Sorry, my ability to description wasn't the best. I'm not too familiar with programming.

However the error only occurs when the game is opened using Lunatranslator's "Game Management" program and no other program or when running the visual novel 


I've found workarounds since it only takes place at certain lines and, despite the error, it seems possible to still play the game but at other times the game crashes.

I'll keep playing ahead to see if I can found out more but I felt I should report the potential issue.
Make of it what you will.

**Comment by HIllya51** [comment]
you should launch the game via localeemulator rather than game manager.
