### ISSUE TITLE
TTS能只读取旁白么

### ISSUE THREAD

**Issue by soulrewrite** [HIllya51/LunaTranslator#89]
主要是有游戏语音的语句的会重一起，很混乱

主角一般没语音，最好还是能分类要读取哪些

**Comment by HIllya51** [comment]
提取到什么读什么，和旁不旁白有什么关系？

**Comment by pionxyz** [comment]
> 提取到什么读什么，和旁不旁白有什么关系？

已经有语音的就不需要再读一遍了吧，重叠在一起也很难受。
vnr可以这样虽然不清楚是怎么搞的
