### ISSUE TITLE
OCR选择Google Lens，在识别竖向文字时合并多行的功能失效，在识别横向文字时合并多行的功能正常。其他OCR似乎不存在这个问题。

### ISSUE THREAD

**Issue by charlespfan** [HIllya51/LunaTranslator#892]
### Version 程序版本

v5.13.0 64bit

### bug's screenshot 错误截图

![屏幕截图 2024-07-15 031435](https://github.com/user-attachments/assets/a0088755-f64a-467c-bfce-50b2d5575f01)
Google Lens

![屏幕截图 2024-07-15 033920](https://github.com/user-attachments/assets/646c5f47-c4ca-449f-a3e3-f629c65c68b2)
有道OCR

### Reproduction steps 复现步骤

OCR选择Google Lens，开启竖向识别，开启合并多行识别结果，在识别竖向文字时合并多行的功能会失效，在识别横向文字时合并多行的功能正常。其他OCR似乎不存在这个问题，如有道、讯飞。

**Comment by HIllya51** [comment]
不支持
