### ISSUE TITLE
希望增加文字可以滚动的选项

### ISSUE THREAD

**Issue by jijinganhe** [HIllya51/LunaTranslator#894]
### Expected behavior 预期的功能

因为主要用于文献研究，有时候需要翻译的字数甚至超过5000字，希望有一个开启后可以上下滚动文字的选项。

以前也提过，还是请求能够增加这个功能，非常感谢🙏

**Comment by HIllya51** [comment]
![屏幕截图 2024-07-14 234600](https://github.com/user-attachments/assets/985bf42b-1304-4f5e-87be-7368a9895b57)

切换成webview2显示
