### ISSUE TITLE
vits-simple-api新增简单的语种识别的接口调用

### ISSUE THREAD

**Issue by luoliyushu** [HIllya51/LunaTranslator#895]
### Expected behavior 预期的功能

[vitsSimpleAPI -支持语种识别.zip](https://github.com/user-attachments/files/16235365/vitsSimpleAPI.-.zip)
由于我的模型支持中、日、英三种语言，所以使用 lang=auto 时，可能会将中文字识别为日语从而报错，所以我更新了一下 vitsSimpleAPI.py 里面的代码。

speak()函数的mode参数：1就是原本的推理模式，2则是我新增的推理模式，默认为1。（但是这个mode参数并没有与UI进行绑定，如果能绑定的话麻烦绑定一下）。

detect_languages()能够将句子进行简单的语种分类，然后一一推理，最后合并成一个完整的mp3文件。但是像那种复杂的语句就无法准确分类了，毕竟不是AI分类的。

detect_languages()返回值类似于这样：
——————————————————————————————
输入:   .!?大概是叫做パートナー吧。這讓我有些高兴。Hello世界こんにちは! 12345 あいうえお 67890  
返回值: [('.!?大概是叫做', 'zh'), ('パートナー', 'ja'), ('吧。這讓我有些高兴。', 'zh'), ('Hello', 'en'), ('世界', 'zh'), ('こんにちは! ', 'ja'), ('12345 ', 'zh'), ('あいうえお ', 'ja'), ('67890', 'zh')]

输入:   ...???  
返回值: [('...???', 'zh')]

输入: ＡＢＣ１２３abc123大家好
返回值: [('ＡＢＣ', 'en'), ('１２３', 'zh'), ('abc', 'en'), ('123大家好', 'zh')]

输入: ...???!!!大家好
返回值: [('...???!!!大家好', 'zh')]

输入: ...???!!!Hello
返回值: [('...???!!!Hello', 'en')]

输入: ...???!!!こんにちは
返回值: [('...???!!!こんにちは', 'ja')]

**Comment by HIllya51** [comment]
别给我说，我没用过，你自己测试好了pr
