### ISSUE TITLE
Sakura大模型在文本结尾除会出现<|im_end|>

### ISSUE THREAD

**Issue by shiyunqwq** [HIllya51/LunaTranslator#896]
### Question 问题

![QQ图片20240715220408](https://github.com/user-attachments/assets/76cb35a0-d473-4e93-9a27-d6e8caaef6fe)
我这边用的模型是sakura-7b-lnovel-v0.9-Q6_K，如果用1.5的话就不会出现，但是会导致翻译慢一拍，所以想问一下怎么解决这个

**Comment by HIllya51** [comment]
翻译优化过滤掉

**Comment by shiyunqwq** [comment]
> 翻译优化过滤掉

![image](https://github.com/user-attachments/assets/0cbf1110-053b-4c7b-a49b-2321a52d5912)
还是不行，会莫名其妙留下两道杠

**Comment by chlbc** [comment]
> 还是不行，会莫名其妙留下两道杠
我這邊測試可以欸，試試看用「翻譯優化」下的「翻譯結果修正」
![image](https://github.com/user-attachments/assets/1a7b0bb6-f75a-48fd-bff8-79b822e56e31)
