### ISSUE TITLE
A problem with the effects of colors on the Arabic language.

### ISSUE THREAD

**Issue by q8fft2** [HIllya51/LunaTranslator#899]
### Version 程序版本

5.13.2

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/f2e7a0af-53d6-4318-89d2-04b3b4c1763c)

here after select
![image](https://github.com/user-attachments/assets/5ee727ed-af8b-48bf-a647-18abce1103dc)

### Reproduction steps 复现步骤

Everything is going well, but the text in Arabic becomes transparent and cannot be seen, but if I select it, I can see it..

If there is a mix of Arabic and English text, the first sentence determines the direction in which the text will be aligned. If it starts with English, it aligns to the left, and if it starts with Arabic, it aligns to the right.

If the problem can be solved, thank you, or at least tell me where to look so I can at least try to solve the problem.

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/issues/891

**Comment by q8fft2** [comment]
Thank you for all your effort, the program works great and I wish you success.
The LunaTranslator program and project is amazing. I advise everyone to download it, and I will recommend everyone I know to try this wonderful program... Good luck.
