### ISSUE TITLE
请问能增加 翻译回填文本替换吗 

### ISSUE THREAD

**Issue by lhj5426** [HIllya51/LunaTranslator#9]
![image](https://user-images.githubusercontent.com/30548000/194313087-5e7bd7d8-ed72-43e4-9376-720c54d12b9c.png)
现在这个是对翻译之前的内容进行预处理
是不是也可以增加一个对 得到的翻译内容再次预处理？
比如图上这个 鹿岛先生通过对得到的翻译结果预处理之后全部变成鹿岛小姐？
这种可行吗
右下角是一个 粘贴板工具 就是类似这种得到文本只会自动替换 然后粘贴出来就是被替换的字 词
可以增加这种翻译后的文本预处理嘛

**Comment by lhj5426** [comment]
如果能这样的话 通过二次对翻译文本预处理这种翻译得到的词直接替换 阅读体验会增强很多
![image](https://user-images.githubusercontent.com/30548000/194314171-cd45f673-e2b3-4b72-a1a9-4f076ca5e930.png)

**Comment by HIllya51** [comment]
其实你看一下 https://github.com/HIllya51/LunaTranslator/issues/5 可能和你说的有点类似。。。不过也不完全一样，我也加一下吧。

**Comment by lhj5426** [comment]
> 其实你看一下 #5 可能和你说的有点类似。。。不过也不完全一样，我也加一下吧。

有点类似但是不完全一样  嗯 
#5  说的是 用特殊词替换然后回填再替换
我说的是直接替换已经翻译的词 
差 那么一点 不同  谢谢大佬

**Comment by HIllya51** [comment]
嗯 我已经实现好了 过一会会在更新一下。

**Comment by HIllya51** [comment]
大概什么样子，VNR的辞书是怎么用的？

**Comment by lhj5426** [comment]
> 这和 #5 说的其实也差不多啊 这个看起来很复杂但基本上其他项都没啥用。。。

好像 其实直白点就是
在翻译之前预处理一下 喂给翻译
然后翻译完只会 再次处理一下显示出来
现在软件都有了
好像就差个正则了？ 把以上2个功能支撑正则的话基本上就差不多了？

**Comment by HIllya51** [comment]
“好像 其实直白点就是
在翻译之前预处理一下 喂给翻译
然后翻译完只会 再次处理一下显示出来”
这个已经有了，就在“使用专有名词手动翻译”那里可以设置，只是因为之前issue的想法是对名词进行翻译才这么写的，但其实你说的其实也一样。
“好像就差个正则了？ 把以上2个功能支撑正则的话基本上就差不多了？”
这个正则是个什么样子？不是很明白。。

**Comment by HIllya51** [comment]
其实我不怎么会用vnr的辞书功能。。。就是因为vnr太麻烦了我才自己做了这个一个软件🥴

**Comment by lhj5426** [comment]
> 其实我不怎么会用vnr的辞书功能。。。就是因为vnr太麻烦了我才自己做了这个一个软件🥴

不是麻烦是卡 一会儿翻译就卡 还动不动就有一句翻译 每一句翻译
而且 翻译出的速度也很慢 后续 陆陆续续出了很多基于Textractor 开发的 翻译速度都比VNR强太多了
就是功能不够完备 哈哈 羡慕有能力的大佬自己可以造新轮子 感谢 这么多翻译过段时间拿来翻译漫画哈哈

**Comment by HIllya51** [comment]
确实，用vnr的时候我都不敢乱动，不然就全屏卡住😂
漫画的后面有时间可以做一下。

**Comment by lhj5426** [comment]
> 确实，用vnr的时候我都不敢乱动，不然就全屏卡住😂 漫画的后面有时间可以做一下。

漫画方面最近我在用这2个都不错
https://www.basiccat.org/zh/imagetrans/
https://github.com/dmMaze/BallonsTranslator
各有特色 你看看 有没有可取之处 在增强优化下 
这是 用机翻漫画软件做的本子
https://exhentai.org/uploader/llflzy 诶嘿~！

**Comment by HIllya51** [comment]
看了一下这些软件已经很不错了，我感觉也卷不过，还是好好搞galgame吧= 。=
