### ISSUE TITLE
两个功能建议

### ISSUE THREAD

**Issue by EXBJAN** [HIllya51/LunaTranslator#90]
1.历史翻译常停留在上次查看的文本位置，而不是最新翻译文本位置，建议改进。毕竟使用历史翻译大多是为了查看最近几次翻译的文本，而不是许久前的。
2.已保存游戏里，建议将最后一次游玩的游戏置顶。

**Comment by HIllya51** [comment]
1、如果我就是在看过去的呢，这样一下子就找不到位置了。要看最新只要滚到最后行了，又不麻烦
2、已修正。

**Comment by EXBJAN** [comment]
好的吧
