### ISSUE TITLE
ImportError: cannot import name "MySwitch" from "gui.usefulwidget"

### ISSUE THREAD

**Issue by lenhatminh1392003** [HIllya51/LunaTranslator#900]
### Version 程序版本

5.3.3.0

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/a14f1933-48b4-4917-8b26-6dfb1ca4b289)

### Reproduction steps 复现步骤

I click on the software to open it, and then it showed the error window.

**Comment by HIllya51** [comment]
fixed

**Comment by lenhatminh1392003** [comment]
> fixed

May I ask how?
