### ISSUE TITLE
VirusTotal

### ISSUE THREAD

**Issue by RantiMeh** [HIllya51/LunaTranslator#901]
### Question 问题

New version
https://www.virustotal.com/gui/file/67cf3dd5d1306c0b57b5f28df6588cfc5c7366d33c9af0e92b4926b5ee3cdc96/detection 

Old version
https://www.virustotal.com/gui/file/9475f529d96d306d52d050cf816712894fc082da863b733cae22f9dbd3b433bd

Question: what the hell is this? why are there so many viruses?

**Comment by HIllya51** [comment]
are you brainless? this program is all built by github actions. no one forced you to use this software, I also don't welcome someone as brainless as you to use it .

https://github.com/HIllya51/LunaTranslator/actions
