### ISSUE TITLE
Translated text not showing

### ISSUE THREAD

**Issue by lenhatminh1392003** [HIllya51/LunaTranslator#904]
### Version 程序版本

5.13.4.0

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/3b02e15a-7c2b-44e6-a119-80b8afc94b9a)

I followed the instruction of this video: https://www.youtube.com/watch?v=Km8tNxfdLyM
One thing I noticed that after choosing the language, it didn't show "welcome" text after. I was wondering if that has anything with why it didn't show translated text.

### Reproduction steps 复现步骤

After open the game, I clicked "Select Game" in the setting and choose the opened game. It opened the Select Text window and I clicked "System" to show different groups of texts. I clicked "Show" on the current dialogue text and it showed on the text window, but it didn't show the translated English text.

**Comment by HIllya51** [comment]
open translate engine

**Comment by lenhatminh1392003** [comment]
> open translate engine

What do you mean? Do I need to open translator like DeepL or Google Translator?
