### ISSUE TITLE
工具按鈕設定問題

### ISSUE THREAD

**Issue by chlbc** [HIllya51/LunaTranslator#905]
### Version 程序版本

5.13.4

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/69915485-eacf-4a46-88de-b77c6a5c081d)
圖一、預設情況

![image](https://github.com/user-attachments/assets/f0323266-fdbc-491b-986a-12d60453022d)
圖二、啟用「遊戲設置」和「可選取的」

![image](https://github.com/user-attachments/assets/3aee6cbe-68aa-42e3-b32c-7f433a783756)
圖三、關閉「最小化到托盤」後重新啟用

![image](https://github.com/user-attachments/assets/36c51f34-508b-442d-b281-c0c518a653f4)
圖四、關閉程式後重新開啟

### Reproduction steps 复现步骤

1. 下載程式初次啟動，語言選簡體中文（繁體中文亦同）：圖一
2. 進入設置 -> 顯示設置 -> 工具按鈕，分別啟用「遊戲設置」和「可選取的」後，中間的按鈕會全部往右移，但左邊理應出現的「遊戲設置」和「可選取的」卻沒顯示，亦無法點擊：圖二
3. 關閉「最小化到托盤」選項，「最小化到托盤」按鈕消失，但在重新啟用「最小化到托盤」後，「最小化到托盤」按鈕卻沒重新顯示：圖三
4. 關閉程式重新啟動後，步驟 2～3 所做的設置才奏效：圖四

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/543dccfbe88412e2938b0b9283ad130f875eab00
