### ISSUE TITLE
新版WOLF RPG引擎的安全措施会导致HOOK时游戏报错退出

### ISSUE THREAD

**Issue by aa-no** [HIllya51/LunaTranslator#906]
### Version 程序版本

5.13.4

### bug's screenshot 错误截图

![英文报错提示](https://github.com/user-attachments/assets/c006b394-7591-4c65-8cfc-8c832d53dcbf)
![日文报错提示](https://github.com/user-attachments/assets/4d4f6d35-860e-414c-bb3d-238cd60ea096)

### Reproduction steps 复现步骤

示例游戏：https://drive.google.com/file/d/1-b4y9DVhrIOiFN4fi27zQuiBkAp2DLn7/view

点击Game.exe启动游戏后，使用LunaTranslator对该游戏进行HOOK，便会游戏导致报错退出，报错原因是LunaHook32.DLL没有正规签名。

WOLF引擎在2024年4月的更新（Ver3.311）中加入了这个安全机制，参见：
https://silversecond.com/WolfRPGEditor/Help/01control.html#DLL
https://sils.fc2.net/blog-entry-810.html
以后使用该引擎的新作游戏大概率都会触发这一报错，希望能想办法解决。

**Comment by L020304** [comment]
这个问题貌似还解决不了?

**Comment by HIllya51** [comment]
> 这个问题貌似还解决不了?

试试mtool行不行吧，反正我是不可能去弄反作弊的东西的。

**Comment by L020304** [comment]
> > 这个问题貌似还解决不了?
> 
> 我这边自行解决了，在自己的设备上生成自签名证书，加入信任，给那几个dll文件签名就行。

解决了！感谢

**Comment by HIllya51** [comment]
666



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年5月12日(周一) 晚上8:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [HIllya51/LunaTranslator] 新版WOLF RPG引擎的安全措施会导致HOOK时游戏报错退出 (Issue #906)


 L020304 left a comment (HIllya51/LunaTranslator#906)
   
这个问题貌似还解决不了?
  
我这边自行解决了，在自己的设备上生成自签名证书，加入信任，给那几个dll文件签名就行。
  
解决了！感谢
