### ISSUE TITLE
dont want pause game

### ISSUE THREAD

**Issue by purogram25** [HIllya51/LunaTranslator#907]
### Question 问题

when i use show\hide shortcut key,(game become paused) this problem makes me cant use gamepad i have to mouse click every time i use shorcutkey because game paused can you fix it?
(i dont want game stop when i click luna translator window or use shortcut it makes me cant use gamepad + steamlink) I don't want to have to mouse click to unlock the paused game. At least it should be able to unlock pause with the keyboard button
 p.s) thank you for make great hook&translator this is really good

**Comment by HIllya51** [comment]
not understandable

**Comment by purogram25** [comment]
> not understandable

如果您使用的是隱藏/顯示翻譯器窗口快捷方式，則必須單擊鼠標才能啓動暫停的遊戲屏幕，這很不方便。 
 創建一個功能，通過按下鍵盤按鈕解鎖暫停的遊戲屏幕 (for no mouse game pad users)
