### ISSUE TITLE
將鼠標點擊替換爲鍵盤按鈕

### ISSUE THREAD

**Issue by purogram25** [HIllya51/LunaTranslator#908]
### Expected behavior 预期的功能

如果您使用的是"隱藏/顯示翻譯器"窗口快捷方式，則必須單擊鼠標才能激活暫停的遊戲屏幕，這很不方便。

 創建一個功能，通過按下鍵盤按鈕激活暫停的遊戲屏幕（對於沒有鼠標的遊戲墊用戶）

**Comment by HIllya51** [comment]
tab alt
