### ISSUE TITLE
在使用 wine 时，ocr 在 wayland 下是黑屏，xorg 工作正常（大概不需要修）

### ISSUE THREAD

**Issue by asukaminato0721** [HIllya51/LunaTranslator#909]
### Version 程序版本

5.13.4

### bug's screenshot 错误截图

xorg works well

![image](https://github.com/user-attachments/assets/61011de0-ddb2-467a-ad5a-1d6314b497e8)

```
WM: KWin (X11)
```

![image](https://github.com/user-attachments/assets/73ede3ff-ec1b-43b6-a7cd-f52f4c1f1a84)

```
WM: KWin (Wayland)
```

### Reproduction steps 复现步骤

切换 wayland/xorg 会话即可

---

ocr 引擎是 gemini llm, 翻译后端是 gemini llm / google. ~~实现生态闭环~~

**Comment by HIllya51** [comment]
emmm 魔幻

**Comment by asukaminato0721** [comment]
相关背景：

默认 wine 是跑在 Xwayland(X Clients under Wayland) 下的，走的 Xorg 那套， https://emacs-china.org/t/archlinux-kde-wayland/22190/2

> Wayland 从设计上就是不让一个程序“看”到屏幕的其它位置。老的软件直接调用 X 的截图走 XWayland 就只能拿到一个黑的图片。

> 逻辑链是 luna 调 Qt 的截图（大概），Qt 调 winapi 的，wine 翻译成调 X 的。

---

所以解法就是让 wine 走纯 wayland 协议。

但是目前 wine 的 wayland 支持还是实验性的，试了下很多游戏会有奇妙表现，就先不管了，这个 issue 留作存档。

**Comment by HIllya51** [comment]
（其实截图并没有走qt，直接cpp重新写的winapi，因为qt的自适应缩放会把截图的坐标搞乱）
