### ISSUE TITLE
不知道为什么本来游戏文字Hook都能正常提取，然后第二天打开就什么文本都提取不到了。

### ISSUE THREAD

**Issue by a525324105** [HIllya51/LunaTranslator#91]
不知道为什么本来游戏文字Hook都能正常提取，然后第二天打开就什么文本都提取不到了，选择文本界面一片空白，什么也没有。是用的管理员打开的，也没有。

**Comment by a525324105** [comment]
Textractor: architecture mismatch: only Textractor x64 can inject this process  这个是什么原因呀？

**Comment by a525324105** [comment]
然后 我点OCR翻译直接就闪退了

**Comment by HIllya51** [comment]
放截图。

**Comment by a525324105** [comment]
![image](https://user-images.githubusercontent.com/64630163/205476226-73013ced-3638-4970-ba76-d0164e8ba3f2.png)

**Comment by a525324105** [comment]
> 放截图。

进程也选了，昨天可以直接提取出来的，也不需要特殊码。

**Comment by HIllya51** [comment]
看一下HOOk设置

**Comment by HIllya51** [comment]
勾选了移除非选定HOOK了吗？把它去掉。
