### ISSUE TITLE
支持豆包大模型（by 群友）

### ISSUE THREAD

**Issue by asukaminato0721** [HIllya51/LunaTranslator#910]
### Expected behavior 预期的功能

ref https://immersivetranslate.com/ja/docs/services/doubao/

api 地址 https://github.com/songquanpeng/one-api/issues/1436

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/a903acb75b6c00d13b994c8cea706af2acdeb8ff
