### ISSUE TITLE
关于专有名词翻译的记录新版与旧版的移植

### ISSUE THREAD

**Issue by gmgm-cell** [HIllya51/LunaTranslator#911]
请问作者，我以前在一个旧的版本中设置了许多专有名词翻译，现在我要用新的版本了，有没有办法通过粘贴复制某些文件的方式，直接把我在旧的翻译器中设置的专有名词翻译记录直接移植到新版本的翻译器中?

**Comment by HIllya51** [comment]
看文档

**Comment by gmgm-cell** [comment]
After the improvement, what should I do to transplant the proper noun records in the old translator to the new translator?



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月19日(周五) 晚上8:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HIllya51/LunaTranslator] 关于专有名词翻译的记录新版与旧版的移植 (Issue #911)




 
Closed #911 as completed.

**Comment by HIllya51** [comment]
https://docs.lunatranslator.xyz/#/zh/update
