### ISSUE TITLE
AI TRASNALTOR

### ISSUE THREAD

**Issue by Yuriuori** [HIllya51/LunaTranslator#913]
### Expected behavior 预期的功能

Hello can please add yanatranslate to the software
it's really good ai translator In terms of quality, it's up there with GPT 3.5, but it really shines with Chinese.

**Comment by Yuriuori** [comment]
https://www.yanatranslate.com/

**Comment by HIllya51** [comment]
give me a account

**Comment by Yuriuori** [comment]
Sadly i don't have account but you can create one, also i think they have github link to download the translator you can check it out

**Comment by HIllya51** [comment]
😅If you don't even use this thing yourself, why are you raising an issue?

**Comment by Yuriuori** [comment]
I talked with the creator myself and They said it's like It's using an uncensored version of Llama2, so i really wanna try it in your software Luna
