### ISSUE TITLE
Q: 各种翻译比较，从价格/门槛/效果（主观）来比较。（可能是长期 issue / 可能会变成 discussion）

### ISSUE THREAD

**Issue by asukaminato0721** [HIllya51/LunaTranslator#915]
### Question 问题

忽略质量这个主观因素

A: 
| 注册/手机号 | free | 上网工具 | 显卡 | 选择 |
| ----------- | ---- | -------- | ---- | ---- |
| n           | n    | n        |  n    | 国内翻译源|
|         n    | y     | n         |y      | sakura
|     y      | y     |  y        |   n   | gemini
|y|n|n|n| deepseek
|n|y|y|n|国内外翻译源

---

翻译质量需要群友自己贡献翻译对照，而且很难量化，先空着。

**Comment by HIllya51** [comment]
https://github.com/NEKOparapa/AiNiee/blob/main/README.md#%E5%B7%A5%E5%85%B7%E5%87%86%E5%A4%87

**Comment by HIllya51** [comment]
https://docs.lunatranslator.xyz/#/zh/manyapis
