### ISSUE TITLE
新增 OpenAI 兼容格式的 OCR

### ISSUE THREAD

**Issue by Yan-Zero** [HIllya51/LunaTranslator#916]
### Expected behavior 预期的功能

可以填写 Base URL 和 API Key，调用支持识图模型进行OCR

最近OpenAI推出了全新的大模型 GPT-4o mini，更便宜的同时还支持多模态

### Alternative behavior (optional) 近似的功能（可选）

OCR 中的 Gemini，但是建议可以填写自己的反代链接
这样子就可用使用别人部署好的反代服务器了，Gemini 对于地区限制太严格了
大部分梯子的节点都不一定能用

**Comment by HIllya51** [comment]
@asukaminato0721
