### ISSUE TITLE
使用专有名词翻译，翻译出来的文本与输入替换的文本不一致

### ISSUE THREAD

**Issue by shiyunqwq** [HIllya51/LunaTranslator#918]
### Version 程序版本

v5.15.4 64bit

### bug's screenshot 错误截图

![`I@ND1K@3ICGNW83NF4VPHV](https://github.com/user-attachments/assets/522efb1b-ce60-488b-8255-23662efa47c1)

### Reproduction steps 复现步骤

使用专有名词翻译，将魔児替换成其他词，游玩巫女喰イ～魔手ノ黒箱～(DL版)就会出现这样的情况

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/issues/550
