### ISSUE TITLE
某些老游戏文本快速换行，但翻译器过滤换行符无用，导致翻译器只来得及翻译最后一句。

### ISSUE THREAD

**Issue by EXBJAN** [HIllya51/LunaTranslator#92]
先放该引擎的一个游戏链接，只有260mb，游戏名：彼女のベッドの下の盗聴器
链接：https://pan.baidu.com/s/1wNyGXuNBU_dPlZ6atnk9iQ?pwd=jh2s 

具体问题是，游戏引擎老旧，没有文本速度调节选项，文本显示是快速逐字显示，且会多次换行，开启过滤换行符并置顶也基本无用。翻译器虽然能hook到全部文本，但因为快速更改文本只来得及显示翻译最后一句。

另外多次重启游戏读取同一进程，对同一段文本是否能完整显示，情况也不同。有事这一次能完整显示，重新读取却又快跳只显示最后一次换行的句子，反之亦然。

**Comment by HIllya51** [comment]
已修正，把刷新延迟调高一点就可以了。
