### ISSUE TITLE
您好，内嵌翻译游戏崩溃问题

### ISSUE THREAD

**Issue by CaesarJack** [HIllya51/LunaTranslator#920]
### Version 程序版本

5.15.4

### bug's screenshot 错误截图

![1](https://github.com/user-attachments/assets/16c6a9be-7784-4ac8-be66-5aef0b9053a9)
![2](https://github.com/user-attachments/assets/78b6ac0c-ba4e-4815-805f-3c19a042efa3)

### Reproduction steps 复现步骤

您好，首先非常感谢您的无私奉献！
问题见图1、图2。使用内嵌翻译时，每当遇到选择项时都会报错崩溃。个人不懂编程，查询使用说明后猜测可能是正则表达式的问题？请问如何解决呢？

另：能否添加自定义翻译文字样式的功能呢？若使用非内嵌翻译，目前字体颜色不可选的话显示效果很差、看不清楚（见图2）。非内嵌翻译的字体没有找到设置的地方。

期待您的解答！
（游戏名：Slay the Princess。运行debug版有同样问题）

**Comment by HIllya51** [comment]
https://docs.lunatranslator.xyz/#/zh/embedtranslate

**Comment by CaesarJack** [comment]
> https://docs.lunatranslator.xyz/#/zh/embedtranslate

您好，这篇引导我看过，我没有出现乱码问题。请问游戏崩溃问题如何解决？

**Comment by HIllya51** [comment]
内嵌安全性检查
