### ISSUE TITLE
原文注音行间距问题

### ISSUE THREAD

**Issue by blucca** [HIllya51/LunaTranslator#922]
### Version 程序版本

Latest

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/9546be47-d72c-439b-850b-abdeed17b805)

### Reproduction steps 复现步骤

在有多行原文的情况下注音会与原文重叠

**Comment by HIllya51** [comment]
😅
![屏幕截图 2024-07-23 170039](https://github.com/user-attachments/assets/ffc26a7c-1c65-4821-963e-5f0ebb67b6f2)
