### ISSUE TITLE
Cannot resize window

### ISSUE THREAD

**Issue by NekoIriyaRu** [HIllya51/LunaTranslator#923]
### Version 程序版本

5.15.5,5.15.6

### bug's screenshot 错误截图

https://github.com/user-attachments/assets/0fe0caa7-b268-4789-b1e7-d0b54aa07162

### Reproduction steps 复现步骤

....

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/386655c02d712ab94705ba24109176876dbaa84d
