### ISSUE TITLE
錯誤輸出調整

### ISSUE THREAD

**Issue by KingkazmaSola** [HIllya51/LunaTranslator#925]
### Expected behavior 预期的功能

當關閉顯示錯誤訊息選項時可以輸出原文(因為文字小說中很常有很多狀聲詞)

欲翻譯內容:
Hm?

原輸出:
有道_V3 AttributeError 'NoneType' object has no attribute ' groups'

預期輸出:
Hm?

**Comment by HIllya51** [comment]
？什么莫名其妙的
