### ISSUE TITLE
查词窗口--很小的样式问题

### ISSUE THREAD

**Issue by cclcc1** [HIllya51/LunaTranslator#927]
电脑暗色模式下，查词窗口（webview2）里最上面的单词意思对比度有点低，不选中的话很难看清，如图

![PixPin_2024-07-24_20-40-45](https://github.com/user-attachments/assets/8027d0f8-0046-40e2-8847-db82009bc7d0)

**Comment by HIllya51** [comment]
这是直接拿的moji自己的样式，它没做黑色模式我也没办法
