### ISSUE TITLE
能否添加导入文本文件并生成对应翻译文件的功能?

### ISSUE THREAD

**Issue by wangwangxingao** [HIllya51/LunaTranslator#929]
### Question 问题

有时可能需要对游戏内某些文件的翻译功能.

**Comment by HIllya51** [comment]
不能。有专门翻文件的软件。

**Comment by 123456ds** [comment]
https://github.com/XD2333/GalTransl

https://github.com/NEKOparapa/AiNiee?tab=readme-ov-file
