### ISSUE TITLE
遇到兩個問題和一個建議

### ISSUE THREAD

**Issue by bernie84** [HIllya51/LunaTranslator#93]
第一 13.12版以後當改變翻譯器語言為繁體中文時，翻譯會直接跑不出來。
第二 百度翻譯今日會有三句只翻出一句的問題，其他翻譯無此狀況。

有個建議是能否新增將舊版本簡單替換內容直接複製到新版本，因每次更新都須重新輸入一次簡單替換內容。

感謝您抽空回覆，也感謝您提供如此棒的翻譯器。

**Comment by HIllya51** [comment]
呃 测试均未发现问题。要不你打包发我看一下？
直接把userconfig覆盖进去就行了，一般是兼容的。

**Comment by bernie84** [comment]
![image](https://user-images.githubusercontent.com/120006764/206135342-773fd26b-2025-4f91-8b90-fe0f59eaa8d1.png)

https://drive.google.com/file/d/1v1sNZjDV2u1aqy8UAE2y2E6uhmNmW9U5/view?usp=sharing
目前第一個問題通過複製userconfig成功解決
但第二個問題仍持續

**Comment by HIllya51** [comment]
翻译调用频率太高被百度限制了。要想随便用必须注册个账号。

**Comment by bernie84** [comment]
了解，所以解決辦法就是辦個百度帳號。
只是台灣這邊辦帳號有點困難，我再想辦法解決。

謝謝您的協助

**Comment by 2-3-5-7** [comment]
@bernie84  可以用中国大陆的代理试试。因为我发现百度挂香港的代理会翻译不出来，而我不挂代理（大陆的 ip）就没问题。

**Comment by bernie84** [comment]
好的，謝謝您的建議
