### ISSUE TITLE
DeeplX: Couldn't connect server

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#930]
### Version 程序版本

5.15.4.0

### bug's screenshot 错误截图

![chatgpt](https://github.com/user-attachments/assets/6853da23-bcc3-4f65-82de-e7199f574f28)

There is problem with connection to DeeplX. I use DeeplX pre-set api in Luna.
api:  http://127.0.0.1:1188/translate
This link perhaps is a problem. Could you help please?

### Reproduction steps 复现步骤

Not possible

**Comment by Farooq87** [comment]
@HIllya51 
So what's the problem here? Should I insert some other link instead of http://127.0.0.1:1188/translate ?

**Comment by HIllya51** [comment]
dont ask me anything before update to latest version

**Comment by Farooq87** [comment]
> dont ask me anything before update to latest version

I apologize. From now I will ask only after update. Thank you.
