### ISSUE TITLE
Delay in automatic adjustment of the translation window

### ISSUE THREAD

**Issue by allebar** [HIllya51/LunaTranslator#931]
### Version 程序版本

last

### bug's screenshot 错误截图

Random screenshot
![Uploading Снимок экрана 2024-04-10 115105.png…]()

### Reproduction steps 复现步骤

I noticed that the translation window is decreasing in size with a delay. If earlier this happened simultaneously with the translation, now it first issues the translation, and only then the window size is adjusted for it. This is constantly striking. I didn't notice such a problem before.

**Comment by allebar** [comment]
This problem is not observed when the window increases relative to the previous size, only when decreasing there is a delay in adjusting the size

**Comment by HIllya51** [comment]
That's the design.
