### ISSUE TITLE
Add more european languages to Source Languages

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#933]
### Expected behavior 预期的功能

I have latest version 5.15.12. 
Could you please add some popular languages from Central/Western Europe to source languages of Luna. 
German, Sweden, Dutch. These 3 ones.
Problem is when I use DeeplX and some other translators they can't translate german text to english.
It always shows original text in german. I use Google Lens OCR

![sourcelang](https://github.com/user-attachments/assets/d7f80f45-e1ac-4d0a-98ae-1371829f1922)

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/d426ba315a559e9ce284bcfa12f6b6eaeada76bf

**Comment by Farooq87** [comment]
Thank you!
