### ISSUE TITLE
 无法打开

### ISSUE THREAD

**Issue by thomasTAT** [HIllya51/LunaTranslator#934]
### Version 程序版本

5.15.13

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/aafe8577-00bb-4bb5-8626-00d097f21e40)

### Reproduction steps 复现步骤

C:\Program Files\LunaTranslator\LunaTranslator, 已经加入windows security exclusion.
下载 LunaTranslator.zip 到这, 解压后,LunaTranslator.exe无法打开.

**Comment by HIllya51** [comment]
https://docs.lunatranslator.xyz/#/zh/cantstart?id=_2-errorpermissionerror
