### ISSUE TITLE
Why this happen ? 

### ISSUE THREAD

**Issue by Machinamochi** [HIllya51/LunaTranslator#936]
### Question 问题

It seems after i install the latest luna translator  it pop up like this how to change it normal like before ?
i can add the hook but cannot translate there is no button to click 
![Capture](https://github.com/user-attachments/assets/80b18480-feb4-46e0-8637-87da0b7fd33b)

**Comment by HIllya51** [comment]
Re-Download

**Comment by Machinamochi** [comment]
I just re download but the pop up it appear keep same no change 
![Uploading Capture.PNG…]()

**Comment by Machinamochi** [comment]
Ok thz you
