### ISSUE TITLE
辞典乱码

### ISSUE THREAD

**Issue by asukaminato0721** [HIllya51/LunaTranslator#937]
### Version 程序版本

5.15.12

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/2718f134-83ad-44c2-b329-7645b7df1dd8)
![image](https://github.com/user-attachments/assets/23f25a9b-f723-4c7b-91b8-d308b7ddc542)

只有辞典乱码，别的都是好的，感觉是哪里的编码出问题了。

按这张图应该是 gbk 编码的问题

![](https://i-blog.csdnimg.cn/blog_migrate/39c502ddd1fa18d53c7d4926b0e50156.png)

### Reproduction steps 复现步骤

启动，查词。

**Comment by HIllya51** [comment]
和wine内置ie实现的版本有关，旧的ie如果sethtml会乱码，但从本地加载相同的html文件却不会乱码，非常迷

**Comment by HIllya51** [comment]
这个我在win7上面之前遇到过，wine没测过

**Comment by HIllya51** [comment]
实在不行可以尝试把辞书设置->显示->网页显示切换到Qwebengine

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/34c5521c17701943913c7a9993a855bf7c4c82cb
