### ISSUE TITLE
去重文本问题

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaTranslator#938]
### Question 问题

正常文本是没重复的，但选项的文字是重复两次的，但为了选项的去重，正常文本里如果有重复的文字，也会被去重。这个只能是全局的吗？放两张图很明显
![1](https://github.com/user-attachments/assets/13a1395e-ee3e-4738-af44-73135e94bd81)
![2](https://github.com/user-attachments/assets/7bc492d2-c93d-4ac7-8a6e-9d4838b70ca2)
可以看到上图的文本对应游戏正常，但也会被去重；下图是选项时候

**Comment by HIllya51** [comment]
改成自动分析去重

**Comment by HIllya51** [comment]
偶发性事件，自己手动处理
