### ISSUE TITLE
some strange behavior on qwebengine（wine）

### ISSUE THREAD

**Issue by asukaminato0721** [HIllya51/LunaTranslator#940]
### Version 程序版本

5.15.12

### bug's screenshot 错误截图

already downloaded the qwebengine, put to the place.

![image](https://github.com/user-attachments/assets/dce03d7b-a7aa-4c2c-89b8-877084f1129f)

![image](https://github.com/user-attachments/assets/884009d2-738e-4a3c-a780-2907a9917b89)

然后更改样式为 QWebEngine or webview2 ，点击 额外的 html, 测试时，log

```py
Traceback (most recent call last):
  File "C:\LunaTranslator_x86\LunaTranslator\myutils\wrapper.py", line 117, in _wrapper
    return func(*args, **kwargs)
  File "C:\LunaTranslator_x86\LunaTranslator\gui\setting_display_text.py", line 57, in applyhtml
    gobject.baseobject.translation_ui.translate_text.textbrowser.set_extra_html(
AttributeError: 'TextBrowser' object has no attribute 'set_extra_html'

```

### Reproduction steps 复现步骤

如上。

**Comment by HIllya51** [comment]
qwebengien加载不出来就会这样。我已经把它删掉了 233

https://github.com/HIllya51/LunaTranslator/commit/480dc6b049d35e4545ee76f3cb5f18e7bd809f11
