### ISSUE TITLE
Ability to assign personal shortcuts for each OCR capture area.

### ISSUE THREAD

**Issue by welcomesun** [HIllya51/LunaTranslator#941]
### Expected behavior 预期的功能

Hi, thank you for your wonderful translator, the variety of its functions and capabilities is very impressive, LunaT has huge potential.

please tell me, are you planning to add the ability to assign personal shortcuts for each OCR capture area? This is the only feature that is sorely lacking so far. Currently, text capture and translation is possible from all areas at once. need the possibility of separate capture.

I will be glad to support you by subscribing to your Patreon in the near future. Thank you!

**Comment by HIllya51** [comment]
no such plan
