### ISSUE TITLE
TGW 設置頁面與一些細節的介面翻譯問題

### ISSUE THREAD

**Issue by chlbc** [HIllya51/LunaTranslator#945]
### Question 问题

您好，近日在本地化繁體中文語系檔中新增加的詞條，想詢問關於 TGW 設置頁面和一些比較細節的介面翻譯問題：
1. 目前的設置中，僅 TGW 語言模型設置頁面沒有翻譯，想詢問是否能將左邊這些文字添加到語言檔中，使其能被翻譯成各地語言呢
（有搜尋了一下過去的 Issues，不太確定是不是因為有整合進離線 GPT 的計畫之類的原因才未翻譯此頁面）
英文 UI 截圖：
![image](https://github.com/user-attachments/assets/3ead1a36-43bd-4f5f-9a41-c415383881b8)

2. 這個問題比較細節一點。目前在「文字輸入」中的`UTF8(CP65001)`字串，在繁體中文和日文 UI 中的括號顯示成全形的會較好些（即顯示成`UTF-8（CP65001）`）。想詢問是否能以添加到語言檔等方式，使該字串在繁體中文和日文 UI 中被處理呢
![image](https://github.com/user-attachments/assets/94db6630-ddaa-4563-9589-034278f99ec6)

**Comment by HIllya51** [comment]
1、这个东西不是我写的，我不想维护它，也不建议使用这个东西。
2、随便
