### ISSUE TITLE
历史翻译的空白

### ISSUE THREAD

**Issue by blucca** [HIllya51/LunaTranslator#946]
### Version 程序版本

Latest

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/e7e350b3-0b4f-43c0-9667-630b8640828e)

### Reproduction steps 复现步骤

打开历史翻译时有时最后有一页空白，希望能去除掉

**Comment by HIllya51** [comment]
qt的问题，往上滚一下就没了
