### ISSUE TITLE
遊戲設置中，「專有名詞 佔位符」視窗的標題列顯示錯誤

### ISSUE THREAD

**Issue by chlbc** [HIllya51/LunaTranslator#948]
### Version 程序版本

5.18.0

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/72ff423c-f2bf-4d64-b863-77df9adece86)

### Reproduction steps 复现步骤

遊戲管理 -> 遊戲設置 -> 翻譯優化 -> 專有名詞 佔位符
此外，繁體中文版似乎不會顯示「sakura gpt 辭典」的選項

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/773dc864435443f66177565a620ef394518ed2a6
