### ISSUE TITLE
光学字符识别设置

### ISSUE THREAD

**Issue by KirpichKrasniy** [HIllya51/LunaTranslator#95]
您使用的是 tesseract ocr 还是您的 OCR 代码？是否有可能以某种方式设置文本识别或添加程序当前无法读取的字体？

是的，非常感谢您将俄语添加到程序中！

**Comment by KirpichKrasniy** [comment]
我可以向您发送一个将界面翻译成俄语的 json 文件吗？界面的俄语翻译可能会在明天发送给您。机器翻译扭曲了 20% 的单词，误译了 30%。现在在设置中它说一只狗和一朵蓝云 :D

**Comment by HIllya51** [comment]
tesseract效果太差了，这里采用的是 https://github.com/PaddlePaddle/PaddleOCR 里的日语识别模型
想要添加其他字体，可以参考 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/training_en.md 中的方法，自己训练模型。

**Comment by HIllya51** [comment]
> 

好的

**Comment by KirpichKrasniy** [comment]
[Русский язык.zip](https://github.com/HIllya51/LunaTranslator/files/10183362/default.zip)

更准确和称职的俄语翻译

你能解决俄语不太适合的问题吗？
窗口可以调整大小吗？
![image](https://user-images.githubusercontent.com/109726461/206392234-7ae6dc57-df6a-4236-b245-44cf774e7904.png)
![image](https://user-images.githubusercontent.com/109726461/206392401-7b57f170-3b75-43e0-8990-c62568910739.png)

**Comment by KirpichKrasniy** [comment]
> tesseract效果太差了，这里采用的是 https://github.com/PaddlePaddle/PaddleOCR 里的日语识别模型 想要添加其他字体，可以参考 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/training_en.md 中的方法，自己训练模型。

感谢您的链接！

**Comment by HIllya51** [comment]
调整窗口大小会导致卡死，暂时无法解决。不过我已经把非中文的字体进行缩小，并把宽度进行放大，使其能够完整的显示俄语。

**Comment by KirpichKrasniy** [comment]
> 不过我已经把非中文的字体进行缩小，并把宽度进行放大，使其能够完整的显示俄语。

多謝。

**Comment by HIllya51** [comment]
此外WindowsOCR需要window10以上的版本，并且在时间和语言中，添加需要识别的语言才能可以使用。

**Comment by KirpichKrasniy** [comment]
> 我可以提供一个其他语言的模型包，这样需要的话自行下载就可以了。

如果你不难，那么请告诉我在哪里下载它们

> 我这里是不能直接把EasyOCR加进去的，因为这样会导致有大量的计算机视觉的相关依赖库被引入，导致程序体积急剧增大。而且EasyOCR实际上和现有的OCR都采用的相同的OCR模型：DBNet+CRNN
> 此外WindowsOCR需要window10以上的版本，并且在时间和语言中，添加需要识别的语言才能可以使用。

我明白了关于"windowsOCR"的一切。 谢谢你的回答！

**Comment by KirpichKrasniy** [comment]
我发现了一个带有ch_PP-CR v3包的在线Paddle OCR，它完美地从游戏中的图片中读取英语，您的程序没有读取信息。 我认为问题出在专门针对日语和中文的设置中。 我将等待更新与支持翻译从英语
![image](https://user-images.githubusercontent.com/109726461/206442051-43da2c6c-f845-4af5-b2ef-2fc42a4fb545.png)
![image](https://user-images.githubusercontent.com/109726461/206442130-71c338bd-de53-4a08-902d-95078c1f6ee2.png)

**Comment by HIllya51** [comment]
emmm 这个模型其实就是我发你的链接里的模型

**Comment by KirpichKrasniy** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/109726461/206462528-b2201602-c6cd-4a6a-8988-4819ec84aabd.png)
![Screenshot_38](https://user-images.githubusercontent.com/109726461/206462535-40344b4b-d684-4ec7-bb5d-1b907bea12cf.png)
我有英语，但这样一个困难的文本仍然不可读。 你做了中国和日本的设置。 还是你刚刚添加了一个你之前丢弃的库？
![image](https://user-images.githubusercontent.com/109726461/206462768-6ce78956-d1d9-451c-99c6-ebc3857b6899.png)
 我认为英语识别需要一个设置

**Comment by HIllya51** [comment]
好了，弄好了。

**Comment by KirpichKrasniy** [comment]
![image](https://user-images.githubusercontent.com/109726461/206476154-76c0632e-6440-488b-ac2c-42851a73c0fe.png)
非常感谢！ 现在没事了。 界面现在更加直观。 即使字体如此糟糕，英文文本读起来也很好。 目前，这是翻译游戏的最佳程序！

也许值得创建一个讨论，人们将翻译成他们的母语？ （用翻译上传你的文件）不幸的是，除了俄语，我不懂任何语言。

还有一个问题：我可以用俄语发表评论并在YouTube上发布节目吗？

**Comment by HIllya51** [comment]
感谢你的夸奖！
哈哈，我外语也不好，只会一点点英语和日语。
可以的~没有任何限制~

**Comment by KirpichKrasniy** [comment]
很抱歉写了太多的问题和要求。 是否有可能使一个功能，以便当按下一个键时，区域的选择立即开始？这样，当键被按下时，区域的选择开始，并且在释放或再次按下之后，区域被选择
https://user-images.githubusercontent.com/109726461/206494229-df6238e1-f220-438a-9da0-b3abd97e9524.mp4

你可以在设置中做到这一点，这样你就可以选择一个键快速按下，而不是组合。 并且，如果不需要，您可以删除旧密钥。 例如，只需点击键盘或键盘快捷键，程序就会记住它
![image](https://user-images.githubusercontent.com/109726461/206495732-44a1dd15-420c-4f46-bf3c-6226a9508e73.png)

**Comment by HIllya51** [comment]
没太明白你的意思。你是说想把快捷键做成只需要一个按键，而不是两个按键吗？

**Comment by KirpichKrasniy** [comment]
>你是说想把快捷键做成只需要一个按键，而不是两个按键吗？

![image](https://user-images.githubusercontent.com/109726461/206509935-90d5b419-1efa-4958-8e87-684b504b51c8.png)

**Comment by HIllya51** [comment]
emmmm。能不能说一下视频中的软件叫什么，我参考一下。

**Comment by KirpichKrasniy** [comment]
> emmmm。能不能说一下视频中的软件叫什么，我参考一下。

该程序称为capture2text 
但她不在github上

**Comment by HIllya51** [comment]
![屏幕截图 2022-12-09 013134](https://user-images.githubusercontent.com/101191390/206522720-6c8b0b25-a275-48f2-999c-2da81b7caf48.jpg)

我下载了这个软件，然而我并没要找到只用一个按键就能触发快捷键的办法。。。请问你是如何设置的？

**Comment by KirpichKrasniy** [comment]
![image](https://user-images.githubusercontent.com/109726461/206525201-6d6e06c3-c074-4535-92db-52cdb927190a.png)
我只是取消选中ctrl键

**Comment by HIllya51** [comment]
OK。搞定了。

**Comment by KirpichKrasniy** [comment]
> OK。搞定了。

谢谢，现在方便多了）

 您是否未能通过按下鼠标所在位置的键来选择区域？

**Comment by KirpichKrasniy** [comment]
您未能启用此功能 或键盘
使该区域在单击鼠标后立即开始突出。 鼠标从哪里来

**Comment by HIllya51** [comment]
你的意思是按下快捷键立即开始选定，而不是需要点击鼠标吗？

**Comment by KirpichKrasniy** [comment]
> 你的意思是按下快捷键立即开始选定，而不是需要点击鼠标吗？

是的，没错。 我试图从一开始就解释它，但我沟通的译者根本不想正常翻译）

我想如果你能在这两种模式之间进行选择会很方便。 如果你很难实现这样的功能，那么我就不再折磨你了。 我要求你做得够多了，这让我感到震惊。 你很酷。 你的程序也是）

**Comment by HIllya51** [comment]
其实我刚才发布了一个release，添加了一个大概是和你描述的一样的快捷键。

**Comment by KirpichKrasniy** [comment]
> 其实我刚才发布了一个release，添加了一个大概是和你描述的一样的快捷键。

我现在就来看看）我刚刚醒来，因为我们的时间已经是早上了。

不幸的是，我现在不能通过捐款在经济上感谢你，但我会尽我所能让尽可能多的人知道你在youtube俄语部分的申请。

**Comment by HIllya51** [comment]
不客气~

**Comment by KirpichKrasniy** [comment]
我检查了，一切都很酷！

**Comment by KirpichKrasniy** [comment]
我还有一个建议。 我想是后者。

是否有可能阻止一个或多个屏幕识别窗口，这些窗口在打开新的识别窗口后不会消失，所有不会被阻止的新窗口在翻译后会简单地消失。 我在视频中举了一个例子。 （我已经启动了两个程序）一个窗口用于翻译对话框（在底部），另一个时间窗口用于翻译库存或一些铭文中事物的描述。

**Comment by KirpichKrasniy** [comment]
https://user-images.githubusercontent.com/109726461/206640751-27513cbe-5423-4a21-89f7-8938769edf3d.mp4

显然，在线翻译已经厌倦了翻译我所有文本的第三天 x`D

**Comment by KirpichKrasniy** [comment]
https://user-images.githubusercontent.com/109726461/206641750-793504d7-c62c-447e-830b-c27278cae8ad.mp4

**Comment by HIllya51** [comment]
我猜一下，你的问题是不是，当游戏中的文字和翻译器的窗口重叠时，会反复的刷新？

**Comment by KirpichKrasniy** [comment]
> 要不你换成你的母语或者英语说一下试试。😂

Is it possible to pin one or more OCR windows that will not disappear after opening a new recognition window,
a new recognition window that will not be pinned will simply disappear after translation (as it was in the video where I showed the capture2text program). 
I recorded a video. (I have two programs running) 
One window for translating dialogs (at the bottom) and another time window for translating descriptions of things in the inventory or some inscriptions. it should read the text, and then just disappear. pinned OCR windows will not disappear

**Comment by KirpichKrasniy** [comment]
> 我猜一下，你的问题是不是，当游戏中的文字和翻译器的窗口重叠时，会反复的刷新？

no, I want to find out if it is possible to open multiple OCR windows

**Comment by HIllya51** [comment]
你的意思是：想要让某个窗口，在显示了翻译结果后的几秒后，自动消失吗？

**Comment by KirpichKrasniy** [comment]
> Вы имеете в виду: Вы хотите, чтобы определенное окно автоматически исчезало через несколько секунд после отображения результата перевода?

yes. and so that you can open multiple windows. perhaps there is such a function, but I did not find it

**Comment by HIllya51** [comment]
我刚刚添加了这个功能。

**Comment by KirpichKrasniy** [comment]
> 我刚刚添加了这个功能。

I meant to close the window for text recognition, not the window with the translation.
![Безымянный](https://user-images.githubusercontent.com/109726461/206659977-7853c00e-29e9-4bb8-a266-cc5c345abda7.png)

**Comment by KirpichKrasniy** [comment]
but you've also added a useful feature to keep the screen clean while playing

**Comment by HIllya51** [comment]
这张图片里翻译窗口中的第四个粉色按钮就是了。。

**Comment by KirpichKrasniy** [comment]
> 这张图片里翻译窗口中的第四个粉色按钮就是了。。

我知道这个功能。 但是，是否可以打开多个窗口从屏幕上读取文本？ 因此，从屏幕读取文本的窗口将自动关闭，就像您在新版本中添加的显示一样。

**Comment by KirpichKrasniy** [comment]
或者您可以添加自动关闭窗口以从屏幕读取文本的功能，就像您对翻译显示所做的那样。

您可以启用两个程序。 一个应该用于从屏幕上连续阅读文本，第二个-作为铭文和描述的临时翻译

**Comment by HIllya51** [comment]
不好意思，没看懂你的意思😂

**Comment by HIllya51** [comment]
是不是这个意思：仅在选择OCR范围后，自动进行一次识别，然后停止。是这个意思吗？

**Comment by KirpichKrasniy** [comment]
> 不好意思，没看懂你的意思😂
用不同的语言沟通有多困难XDDDDDDDDDD

> 是不是这个意思：仅在选择OCR范围后，自动进行一次识别，然后停止。是这个意思吗？
是的. 我想你现在明白我了

**Comment by KirpichKrasniy** [comment]
我试着解释
文本识别后删除文本识别区域
在capture2text程序中确定其操作原理后，从屏幕中识别文本的区域将消失。

**Comment by HIllya51** [comment]
感觉这个需求有点反直觉，因此我将其设置为了一个可选项。将其按如下进行设置就可以了。
![屏幕截图 2022-12-09 184616](https://user-images.githubusercontent.com/101191390/206685192-bfbc39e4-525b-49d3-9f61-18dc6c464199.jpg)

**Comment by KirpichKrasniy** [comment]
非常感谢！我认为有人用这种方式翻译一个小文本会很方便

**Comment by KirpichKrasniy** [comment]
我可以给你一个在游戏中工作的例子。 我将如何使用它

**Comment by KirpichKrasniy** [comment]
https://user-images.githubusercontent.com/109726461/206692144-843d4828-8a61-485b-9ae1-9fce8cfccfe3.mp4

我认为这个功能对某人有用。 谢谢你试图理解我）））

**Comment by HIllya51** [comment]
😊
