### ISSUE TITLE
Magpie

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#950]
### Question 问题

Please explain how to use Magpie in Luna Translator. As far as I understand with this tool I can upscale area with recognized text, right? I didn't find button to upscale on interface window. 
![ziHpUh-jsZE](https://github.com/user-attachments/assets/e1180402-3ffd-4e4b-8764-daf92d541908)

**Comment by HIllya51** [comment]
tool button

**Comment by Farooq87** [comment]
> tool button

@HIllya51 
That's exactly what puzzled me. I couldn't find that button in Tool Button section
![1](https://github.com/user-attachments/assets/79ab9f7d-aacc-4fe0-80b9-cd502c9fed9d)
![2](https://github.com/user-attachments/assets/db59d02b-f3a9-4c6c-a359-d1d6e6cf9a9b)

**Comment by HIllya51** [comment]
maximize/restore game window

**Comment by Farooq87** [comment]
> maximize/restore game window

Thank you
