### ISSUE TITLE
關於翻譯優化與 Sakura GPT 辭典的相關建議

### ISSUE THREAD

**Issue by chlbc** [HIllya51/LunaTranslator#952]
### Expected behavior 预期的功能

您好，近日想根據官網中翻譯優化的教程、將設置中翻譯優化使用 MD5 區分遊戲的辭典移到個別遊戲設置的翻譯優化中，但在移動和測試 Sakura GPT 辭典功能時，感覺有一些不甚方便的地方，因此向您提出以下建議，希望您可以考慮看看是否採納。

### 一、Sakura GPT 辭典開啟且版本為 v0.10pre1 時，Sakura 大模型的專有名詞翻譯只使用「Sakura GPT 辭典」，而不使用「直接替換」和「佔位符」

主要因為以下原因：
1. 在 Sakura 大模型中，Sakura GPT 辭典基本上能完整替代「直接替換」和「佔位符」的功能
2. 若同時激活 Sakura 大模型和其他翻譯時，基本上還是會激活「直接替換」和「佔位符」給其他翻譯使用
3. 經過「直接替換」和「佔位符」處理過的文本，再對其使用 Sakura GPT 辭典會變得意義不大

因此建議 Sakura GPT 辭典開啟且模型版本為 v0.10pre1 時，一般翻譯仍使用現行方法（直接替換、佔位符 -> 翻譯結果修正），但 Sakura 大模型僅使用 Sakura GPT 辭典進行專有名詞翻譯（Sakura GPT 辭典 -> 翻譯結果修正）。

### 二、Sakura GPT 辭典的注釋一欄可輸入繁體中文，但在傳進模型前會轉成簡體後才傳入模型

因為 Sakura 模型似乎只支持簡體中文，因此建議做此改動。

### 三、個別遊戲的翻譯優化可以同時使用默認的設置與個別設置

因為有一些詞彙或規則可能是全部或大多遊戲都會使用到的，這時會想要寫進設置中的全域設置內（像是一般 R18 遊戲比較常見的`ゴム` -> `安全套`之類的，一大堆翻譯都會翻成橡膠）。因此會建議定義設置中的翻譯優化為 Global 設置，並將個別遊戲原本的「跟隨默認」改成「同時激活全局設置」，而後將個別遊戲的「專有名詞翻譯 直接替換」的默認值設為 Disable。

### 四、對 Sakura GPT 辭典和其他專有名詞翻譯整合或連動

因為在同時激活 Sakura 大模型和其他翻譯時，人名等專有名詞除了要添加在 Sakura GPT 辭典之外，其他翻譯也需要使用直接替換、佔位符來對其處理。但這會導致說每添加一個詞條，都要在兩個地方都添加（Sakura GPT 辭典、直接替換或佔位符），對於添加詞條以及後續的修改都較為不便。因此會建議做以下其中一個修改：
1. **將 Sakura GPT 辭典整合進直接替換和佔位符中**
對於 Sakura 大模型而言，Sakura GPT 辭典基本上能完整替代其他專有名詞翻譯方法，但其他翻譯卻仍需要使用直接替換、佔位符來處理，故會建議：
   1. 將直接替換和佔位符方法多加一個 Column——注釋
   2. 將 Sakura GPT 辭典設置移除，並整合進直接替換和佔位符中
   3. 添加一個 switch——於 Sakura 大模型中使用 Sakura GPT 辭典作為專有名詞翻譯方法
      - 若要讓用戶詳細設置每個詞條的適用情況，也可以改添加在直接替換和佔位符設置的每一個 Row 中
2. **提供複製詞條功能**
如果無法整合的話，建議至少讓用戶能以 Ctrl-C 或按鈕等方式，讓用戶能同時複製多個詞條，並將其貼到其他專有名詞翻譯方法中。如此雖然用戶在後續修改方面仍然不太方便，但會比現行版本容易許多。

### 五、在「工具按鈕」中，添加當前綁定遊戲的「專有名詞翻譯與翻譯結果修正」的快捷按鈕
因為若非二周目的情況下，通常專有名詞辭典仍以邊玩邊建的情況比較多，但目前要開啟專有名詞辭典需要「遊戲設置 -> 遊戲設定 -> 翻譯優化 -> 開啟專有名詞翻譯或翻譯結果修正」，感覺有點繁瑣，因此建議添加這些選項。

### 六、添加完整將某個遊戲的翻譯優化設置完整複製（或替換）到另一個遊戲的功能
對於有 FD 或是續作的遊戲而言，其辭典可能是可以共通的，但當前卻只能一條一條手動複製。因此建議對個別遊戲的遊戲優化設置添加類似文字處理設置裡的「以當前 MD5 複製所有行」、可以複製全部詞條貼上或替換到另一個遊戲的功能（如果可以的話或許也可以考慮添加讓多個遊戲共用個別翻譯優化設置的機制，但感覺實現很麻煩）

### 七、將 Sakura 大模型設置中的「v0.10pre1」改為「v0.10pre1 / GalTransl」
目前在 [Hugging Face](https://huggingface.co/SakuraLLM) 中的 Sakura v0.10pre1 模型只有 32B 的版本；而最新的 GalTransl 模型也是 SakuraLLM 的成員，雖也支持 Sakura GPT 辭典，卻不包含 v0.10pre1 的版本號，因此建議做此更動，能讓用戶更加容易辨認當前的模型是否是支持 Sakura GPT 辭典的版本。

以上，謝謝大佬看完以上內容，也希望您能夠考慮是否採納其中的某些提議。

### Alternative behavior (optional) 近似的功能（可选）

翻譯優化、工具按鈕、以當前 MD5 複製所有行

**Comment by HIllya51** [comment]
看的我头疼

**Comment by HIllya51** [comment]
一、不可以，会无法兼容之前的设置
二、不可以，无法判断是什么语言
三、可以考虑
四、太麻烦了，懒得弄
五、可以考虑
六、太麻烦了，懒得弄，自行从json文件里去复制
七、不可以，这是官方这么写的。 https://github.com/SakuraLLM/SakuraLLM/blob/main/README.md?plain=1#L165

**Comment by chlbc** [comment]
我尽量讲短+转简中

> 一、不可以，会无法兼容之前的设置

当前若 GPT 词典和其他方法都要加同个词，
直接替换：GPT 要加替换后的词
占位符：直接没法加

因此若要用专有名词词典，
要么就只开 Sakura（GPT 词典）或其他翻译其中之一，
要么就只能回去用旧的占位符或替换。

至于兼容问题，大概就三种情况：
1. 没用 GPT 词典：没影响
2. 用了 GPT 词典，但没用其他专有名词方法：没影响
3. 用了 GPT 词典，且用其他方法：要符合最上面加同个词的规则，感觉很难想象

> 二、不可以，无法判断是什么语言

- Sakura 只支援日文转简中
- Sakura 词典只支援简体输入，连英文都不支援
- 内置简繁字典支持简入简出
- 因此建议在源语言是繁中时，将注释转简中即可

> 四、六

了解，我再去看下要怎用。
（但感觉要快速的话，
好像直接用旧版的复制功能比较快）

> 七、不可以，这是官方这么写的。

了解，但官方也没标最新模型的 Sakura 版本，
只有标 v1 和 v1.5 就是。
不过不改的话会建议在教程提一下，
不然一般初心者可能不知道新模型可用 GPT 词典

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/eb1f499ce4ce8ad26c580937e9e716804b90106c

https://github.com/HIllya51/LunaTranslator/commit/f2d9473ffe2aada8b22e88fdd3d33ffadd154c7d
