### ISSUE TITLE
manga-ocr start.bat 报错

### ISSUE THREAD

**Issue by charlespfan** [HIllya51/LunaTranslator#954]
### Version 程序版本

v5.18.4 64bit

### bug's screenshot 错误截图

![屏幕截图 2024-08-02 154935](https://github.com/user-attachments/assets/a8740733-0096-4ce1-b869-4ca26c2e2520)
![屏幕截图 2024-08-02 155947](https://github.com/user-attachments/assets/3ac231ac-3d55-41d7-84f1-b7931982af5d)

### Reproduction steps 复现步骤

正常启动manga-ocr start.bat时报错，内容如下：

以一种访问权限不允许的方式做了一个访问套接字的尝试。
请按任意键继续. . .

manga-ocr network.winhttp.winhttp.WinhttpException ERROR_WINHTTP_CANNOT_CONNECT 12029

**Comment by HIllya51** [comment]
😅百度去
