### ISSUE TITLE
OCR can't recognize all text in selected area

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#956]
### Version 程序版本

5.20.1

### bug's screenshot 错误截图

I have latest version of Luna 5.20.1
My OCR is Google Lens
Problem: Often when I select area of optical recognition OCR can't recognize full text in it. Result is only part of the text.
Example on the picture. I have to repeat OCR and then it recognizes whole text but not at the first time. It happens not always, but rather frequently.
Is it possible to fix this issue please?
![OCR latest](https://github.com/user-attachments/assets/5e30f2c7-bb15-4e98-89ab-5d7b3e0fddd7)

### Reproduction steps 复现步骤

Select OCR area with cursor -- wait processing -- not all text is recognized in window

**Comment by HIllya51** [comment]
Adjust the automatic execution parameters

**Comment by Farooq87** [comment]
> Adjust the automatic execution parameters

@HIllya51 
Currently I have execution parameters as follows below
![rttyyy](https://github.com/user-attachments/assets/0205b05d-825c-4988-8641-d0175d300050)

What parameters should be set there?

**Comment by HIllya51** [comment]
https://docs.lunatranslator.xyz/#/zh/ocrparam
