### ISSUE TITLE
Chatmiko Error

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#958]
### Version 程序版本

5.21.0

### bug's screenshot 错误截图

I have latest version of Luna 5.21.0
Issue: Error in chatmiko translation. This free service worked just fine and suddenly broken. It doesn't work on any versions of program now
![image](https://github.com/user-attachments/assets/e5b71587-18f5-4684-bcab-bc906c064b3a)

### Reproduction steps 复现步骤

select OCR area - wait processing - exception error

**Comment by HIllya51** [comment]
use other

**Comment by Farooq87** [comment]
> use other

@HIllya51 
I am sorry to see this. Very pity. Because it is one of the best free translators in Online section. Very precise and high AI quality. It is better than Google V2.

**Comment by Farooq87** [comment]
@HIllya51 
It works again.
Problem was on his web-site https://chatmiko.com/
That's why it gave error in Luna.
Best online translator (without keys)
