### ISSUE TITLE
希望查词搜索按钮与回车键绑定

### ISSUE THREAD

**Issue by kousakaharuka9** [HIllya51/LunaTranslator#959]
### Expected behavior 预期的功能

![b371cce108de15062964e784d3f097aa](https://github.com/user-attachments/assets/a3083632-21bc-4328-a518-e5ef57b0559c)
希望这个按钮能和回车键绑定（频繁查词并与anki联动的时候一直鼠标点击感觉有点麻烦。）如果可以的话，这个界面的其他按钮也能设置快捷键就好了。麻烦了。

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/fd68661981d24c34b145e2771f5112cd352a44c5

**Comment by kousakaharuka9** [comment]
> [FD68661型](https://github.com/HIllya51/LunaTranslator/commit/fd68661981d24c34b145e2771f5112cd352a44c5)

谢谢......
