### ISSUE TITLE
辭典查詞結果導出

### ISSUE THREAD

**Issue by sky456757** [HIllya51/LunaTranslator#96]
希望能添加把字典查詞結果導出成json,欄位可以包括，單字、查詢結果、當前文本句子之類的

**Comment by HIllya51** [comment]
。。。感觉没什么意义

**Comment by sky456757** [comment]
會希望會有這個功能是希望可以把這個翻譯器當成學習日文的工具，匯出的檔案可以做複習單字的用途，導入Anki 做成字卡之類的

**Comment by HIllya51** [comment]
没用过，不是很清楚anki是什么格式。

**Comment by HIllya51** [comment]
细说一下。

**Comment by sky456757** [comment]
就我所知anki應該是沒有官方的導入格式，之所以會希望輸出json是因為這樣可以比較方便用
https://github.com/FooSoft/anki-connect 這個api做字卡導入

**Comment by HIllya51** [comment]
我只把fields保存下来了，audio和picture弄不了。

**Comment by sky456757** [comment]
ok 感謝大大

**Comment by sky456757** [comment]
能否修改成可以指定要用哪一個，或是哪幾個辭典的翻譯結果做輸出的形式，全部都用的話資訊量有點太冗雜了

**Comment by HIllya51** [comment]
改成在哪个界面就保存哪个了
