### ISSUE TITLE
使用ocr时TGW翻译无法显示，再刷新一次就会出来

### ISSUE THREAD

**Issue by Z9wind** [HIllya51/LunaTranslator#960]
### Question 问题

rt
hook似乎没问题
ocr状态下不是没翻译，而是翻译了没显示，再刷新一下就会马上出来

**Comment by HIllya51** [comment]
是因为TGW太慢了吧？然后刷新之后因为有缓存就马上出来了 = =。

**Comment by Z9wind** [comment]
这样子咩，因为感觉以前好像没这样
