### ISSUE TITLE
翻译背景无法设置透明，一直是luna图片，设置没有找到对应的更改方法

### ISSUE THREAD

**Issue by nickwuster** [HIllya51/LunaTranslator#961]
### Question 问题

![屏幕截图 2024-08-04 175212](https://github.com/user-attachments/assets/e2750406-adc5-475a-92aa-ee257dff3a88)

config.json 旧版复制之后背景恢复了，但是我设置的参数变回以前的了，有没有更简单的方法可以更变呢

**Comment by HIllya51** [comment]
禁用额外的html

**Comment by nickwuster** [comment]
您好，已经收到了您的来信！
