### ISSUE TITLE
自动朗读开关 快捷键

### ISSUE THREAD

**Issue by fastfading** [HIllya51/LunaTranslator#963]
### Expected behavior 预期的功能

目前
快捷键中有“朗读”的快捷键， 但其实不是很实用
考虑《创世秩序》等游戏， 有部分自带语音的游戏。
我们需要一个自动朗读开关 的快捷键。  以便于快速切换，

**Comment by HIllya51** [comment]
1+

**Comment by fastfading** [comment]
up 主 ， 真实勤奋啊， 这么多feature这么快就完成了。
