### ISSUE TITLE
支持客户自定义的语音引擎

### ISSUE THREAD

**Issue by fastfading** [HIllya51/LunaTranslator#964]
### Expected behavior 预期的功能

如今
gpt-sovits 等ai语音模型， 逐渐成熟。
大部分语音都有角色克隆，并且可以实时tts，效果也挺好
但是需要自建ai server ， 或者本地server
这就需要 [LunaTranslator](https://github.com/HIllya51/LunaTranslator)   支持自定义的tts url

下面是一个gpt-sovits  api示例
http://10.224.10.6:9880?text=xxx，不要打游戏，赶紧写作业。&text_language=zh
能不能加一个给用户自定义tts 的接口

**Comment by HIllya51** [comment]
1+
