### ISSUE TITLE
能否给正则表达替换添加一个快捷键

### ISSUE THREAD

**Issue by k2250761** [HIllya51/LunaTranslator#967]
### Expected behavior 预期的功能

![tmpF9D](https://github.com/user-attachments/assets/1f3f1a72-a9ba-4dad-9b31-2bd9ca4632b9)
录入一千多条全是自己手点打开关闭录进去的，实在是太累了，求求了

**Comment by HIllya51** [comment]
？这有什么快捷键能加

**Comment by HIllya51** [comment]
我是说 干什么的快捷键 理解不了。

**Comment by HIllya51** [comment]
按下快捷键后，发生什么动作？

**Comment by k2250761** [comment]
按一次，打开编辑界面，再按一次关闭编辑界面

**Comment by HIllya51** [comment]
？这有什么用快捷键的必要

**Comment by HIllya51** [comment]
鼠标点一下就打开了，不懂有什么快捷键的必要

**Comment by k2250761** [comment]
每次遇到需要替换的单词，句子都要点开设置，点击文本替换，然后再点击那个齿轮，最后编辑界面操作

**Comment by HIllya51** [comment]
工具按钮有这个按钮，一键的事。

**Comment by k2250761** [comment]
工具按钮没找到正则替换的按钮
然后按钮肯定没有快捷键方面，所以才提出这个建议，因为录入需要用键盘，肯定是快捷键方便

**Comment by HIllya51** [comment]
正则这个预处理，是用来过滤错误文本的，用它来做词典，并不是预期的用法。而且你这些输入的内容，根本用不到正则，你应该使用翻译优化中的功能。

**Comment by k2250761** [comment]
这个做不单单是做词典，修正句式，还有些烫嘴的原文都用得到，而且光是能用正则就比那些专有名词效果好得多
然后那个专有名词，给sukura翻译还会出现一堆错误代码，还不如直接替换文本，单词能得到更好的翻译

**Comment by HIllya51** [comment]
修正句式，不是一个经常性的操作。正则也不是一个经常需要添加的东西。
sakura你也应该用翻译优化里sakura专用的gpt词典而不是直接替换，如果直接替换也应该用翻译优化里的直接替换，而非预处理里的。

**Comment by k2250761** [comment]
还有那个专有名词用不了正则， 例如原文出现  人名：アメリ你录完之后，遇到アメリカ，根本没办法用正则写排除，直接就会翻译错误

**Comment by k2250761** [comment]
> 修正句式，不是一个经常性的操作。正则也不是一个经常需要添加的东西。 sakura你也应该用翻译优化里sakura专用的gpt词典而不是直接替换，如果直接替换也应该用翻译优化里的直接替换，而非预处理里的。

不是经常性的操作，我怎么会录1200多条.....

**Comment by HIllya51** [comment]
> 还有那个专有名词用不了正则， 例如原文出现 人名：アメリ你录完之后，遇到アメリカ，根本没办法用正则写排除，直接就会翻译错误

这种情况是少见的。


> > 修正句式，不是一个经常性的操作。正则也不是一个经常需要添加的东西。 sakura你也应该用翻译优化里sakura专用的gpt词典而不是直接替换，如果直接替换也应该用翻译优化里的直接替换，而非预处理里的。
> 
> 不是经常性的操作，我怎么会录1200多条.....


至少你截图里的这些内容，完全没有任何正则表达式，虽然将他们写到正则表达式替换里也能工作，但这并不是正确的做法。

**Comment by k2250761** [comment]
> > 还有那个专有名词用不了正则， 例如原文出现 人名：アメリ你录完之后，遇到アメリカ，根本没办法用正则写排除，直接就会翻译错误
> 
> 这种情况是少见的。
> 
> > > 修正句式，不是一个经常性的操作。正则也不是一个经常需要添加的东西。 sakura你也应该用翻译优化里sakura专用的gpt词典而不是直接替换，如果直接替换也应该用翻译优化里的直接替换，而非预处理里的。
> > 
> > 
> > 不是经常性的操作，我怎么会录1200多条.....
> 
> 至少你截图里的这些内容，完全没有任何正则表达式，虽然将他们写到正则表达式替换里也能工作，但这并不是正确的做法。

算了，那不建议了，谢谢你的回复

**Comment by HIllya51** [comment]
我把翻译优化里直接替换改成正则表达式替换吧。

**Comment by HIllya51** [comment]
专有名词翻译将可以使用正则表达式。不过服务器DNS出了点问题，暂时无法更新
