### ISSUE TITLE
可以在離線翻譯ChatGPT 相容界面新增一個Negative Prompts選項與欄位嗎？

### ISSUE THREAD

**Issue by hongvi20240807** [HIllya51/LunaTranslator#968]
### Expected behavior 预期的功能

以前TGW 語言模型中有這一個欄位，可自行添加負向提示，避免翻譯某些敏感文本時觸發ai翻譯自我審查機制，但TGW語言模型已經被拿掉或合併進ChatGPT 相容界面中，但卻沒有可以自行添加Negative Prompts，希望可以在未來更新版本中新增這欄目

**Comment by HIllya51** [comment]
自行在其他参数中添加
