### ISSUE TITLE
Sakura：游戏个别设置的 GPT 词典完全没有作用；Global 设置则在与占位符有相同词条时没有作用

### ISSUE THREAD

**Issue by chlbc** [HIllya51/LunaTranslator#969]
### Version 程序版本

5.23.0

### bug's screenshot 错误截图

词条（占位符和 GPT 词典）：
（若游戏设置中有设置则词条设置一样的）
（マルク 兩者皆有設置；ルイリ 仅设置在 GPT 词典）
|占位符|GPT|
|---|---|
|![image](https://github.com/user-attachments/assets/b89d2b1b-6542-4b76-9fea-bda853827ad5)|![image](https://github.com/user-attachments/assets/df3b13b1-229b-4a54-9d5c-d7752eb98e4a)|

- 测试文本（Hook 游戏“百千の定にかわたれし剋体験版”）：
`マルク：「別に、このくらいならお前も出来るだろ『ルイリ』」`
- Sakura **未激活** GPT 词典时的结果：
`馬克：「這點小事，你也能做到吧，「瑠璃」」`
- Sakura（红色）激活 GPT 词典时的理想结果（Global 开 GPT 词典、游戏设置激活跟随默认）：
`馬爾克：「這點小事，你也能做到吧，「盧伊裡」」`
![image](https://github.com/user-attachments/assets/c639c9ff-961e-4351-8399-f881e5ce8f9f)

---
**以下为测试结果**

词条：仅 Global 有设置
Global：占位符 ON、GPT 词典 ON
游戏设置：跟随默认 ON
Sakura 理想结果：マルク、ルイリ 兩詞條皆使用 GPT 詞典
Sakura 实际结果：マルク 未使用任一詞典

**BUG：Sakura 未使用 GPT 词典的“占位符与 GPT 相同的词条”**
![image](https://github.com/user-attachments/assets/70b8fadf-d7d0-423e-9bfd-c7ea203d7049)

词条：仅 Global 有设置
Global：占位符 ON/OFF、GPT 词典 ON/OFF
游戏设置：跟随默认 OFF、占位符 ON、GPT 词典 ON、各自的继承默认 ON
Sakura 理想结果：マルク、ルイリ 兩詞條皆使用 GPT 詞典
Sakura 实际结果：マルク、ルイリ 未使用 GPT 詞典；マルク 使用了不应使用的占位符

**BUG：Sakura 使用了占位符，未使用 Global 的 GPT 词典**
![image](https://github.com/user-attachments/assets/9f4da1fe-3c60-47f4-a0d2-caff5421cea7)

词条：仅 Global 有设置
Global：占位符 ON/OFF、GPT 词典 ON/OFF
游戏设置：跟随默认 OFF、占位符 OFF、GPT 词典 ON（继承默认 ON）
Sakura 理想结果：マルク、ルイリ 兩詞條皆使用 GPT 詞典
Sakura 实际结果：未使用任何词典

**BUG：Sakura 未使用继承默认之 Global 的 GPT 词典**
![image](https://github.com/user-attachments/assets/db24f00c-f332-4431-9b71-3b5111e9509e)

词条：仅个别游戏有设置
Global：占位符 ON/OFF、GPT 词典 ON/OFF
游戏设置：跟随默认 OFF、占位符 OFF、GPT 词典 ON（继承默认 OFF）
Sakura 理想结果：マルク、ルイリ 兩詞條皆使用 GPT 詞典
Sakura 实际结果：未使用任何词典

**BUG：Sakura 未使用个别游戏的 GPT 词典**
![image](https://github.com/user-attachments/assets/3f00aa35-038c-459b-8434-616c2b41d071)

### Reproduction steps 复现步骤

环境：
- 词条、测试结果：如上所述
- 激活翻译：蓝色“谷歌 v2”、红色“Sakura”
- 模式：Hook（另剪贴板也会发生该 BUG）
- Sakura 模型：SakuraLLM 最新的 [GalTransl-7B-v1.5-IQ4_XS](https://huggingface.co/SakuraLLM/GalTransl-7B-v1.5)（支持 GPT 字典）

步骤：
1. 依序修改 Global 和个别游戏的占位符、GPT 词典设置
2. 使用工具按钮的“手动翻译”以重新翻译

Sakura 理想结果：
- 当版本为 0.10pre1 时，
无论 Global 还是游戏个别设置，
若激活 GPT 词典，则仅使用 GPT 词典

BUG 推论：
1. 在游戏设置“跟随默认”、与剪贴板模式时，
若 Global 设置中，占位符与 Sakura 有相同的词条，
则该相同词条不会使用任一词典（但应使用 GPT 词典）
2. 游戏个别设置的 GPT 词典完全没有作用

**Comment by HIllya51** [comment]
1x

**Comment by chlbc** [comment]
@HIllya51 
5.23.1 版的游戏个别设置的 GPT 词典有作用了。
不过“若 Global 设置中，占位符与 Sakura 有相同的词条，则该相同词条不会使用任一词典”的这个 BUG 仍存在，
且当前游戏个别设置的 GPT 词典也有同样的 BUG。
（除 Hook 外，剪贴板也一样有这个 BUG）

![image](https://github.com/user-attachments/assets/79127b71-2f02-4ba5-83d7-6a1ef9b244ee)

![image](https://github.com/user-attachments/assets/57bc2a36-d003-436d-93a9-39ceb059a97b)

**Comment by HIllya51** [comment]
http://38.46.30.10:8000/#/zh/transoptimi?id=_3-%e4%b8%93%e6%9c%89%e5%90%8d%e8%af%8d%e7%bf%bb%e8%af%91-sakura-gpt-%e8%af%8d%e5%85%b8
你没有正确使用

**Comment by chlbc** [comment]
> http://38.46.30.10:8000/#/zh/transoptimi?id=_3-%e4%b8%93%e6%9c%89%e5%90%8d%e8%af%8d%e7%bf%bb%e8%af%91-sakura-gpt-%e8%af%8d%e5%85%b8 你没有正确使用

这一篇我有看，但想询问下大佬所说的没有正确使用的部分是指哪个部分呢

我这边是想要谷歌用占位符、Sakura 用 GPT 词典。
`prompt version`我有改成`v0.10pre1`了。
而 [GalTransl](https://huggingface.co/SakuraLLM/GalTransl-7B-v1.5) 有说`支持GPT字典`，
而且只单独激活 GPT 词典确实也有效，
只有在同时激活占位符和 GPT 词典时，GPT 词典才会没有作用。

是要换成 [Sakura-32B-Qwen2beta-v0.10pre1-GGUF](https://huggingface.co/SakuraLLM/Sakura-32B-Qwen2beta-v0.10pre1-GGUF) 才能正常使用吗

![image](https://github.com/user-attachments/assets/f900ff58-a3d6-4b50-ac89-2a312b887c38)

![image](https://github.com/user-attachments/assets/6468aa71-a5f1-414b-860d-ba39cefe99c3)

**Comment by HIllya51** [comment]
那就不知道了 反正我测试没问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月7日(周三) 晚上11:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HIllya51/LunaTranslator] Sakura：游戏个别设置的 GPT 词典完全没有作用；Global 设置则在与占位符有相同词条时没有作用 (Issue #969)




  
http://38.46.30.10:8000/#/zh/transoptimi?id=_3-%e4%b8%93%e6%9c%89%e5%90%8d%e8%af%8d%e7%bf%bb%e8%af%91-sakura-gpt-%e8%af%8d%e5%85%b8 你没有正确使用
  
这一篇我有看，但想询问下大佬所说的没有正确使用的部分是指哪个部分呢
 
我这边是想要谷歌用占位符、Sakura 用 GPT 词典。
 prompt version我有改成v0.10pre1了。
 而 GalTransl 有说支持GPT字典，
 而且只单独激活 GPT 词典确实也有效，
 只有在同时激活占位符和 GPT 词典时，GPT 词典才会没有作用。
 
是要换成 Sakura-32B-Qwen2beta-v0.10pre1-GGUF 才能正常使用吗
 
image.png (view on web)
 
image.png (view on web)

**Comment by chlbc** [comment]
了解，这种情况确实满诡异的。
我这边把语言和术语表都改成简体后，
在激活 GPT 词典的情况下，
分别以“不激活占用符”和“激活占用符”测试，
结果 LOG 如下：
```
根据以下术语表（可以为空）：
ルイリ->卢伊里 #男性
マルク->马尔克 #男性

将下面的日文文本根据上述术语表的对应关系和备注翻译成中文：マルク：「別に、このくらいならお前も出来るだろ『ルイリ』」
Traceback (most recent call last):
  File "E:\Project\Test\LunaTranslator\hiraparse\basehira.py", line 58, in parseparse
    raise e
  File "E:\Project\Test\LunaTranslator\hiraparse\basehira.py", line 55, in parseparse
    hira = self.parse(text)
  File "E:\Project\Test\LunaTranslator\hiraparse\mecab.py", line 83, in parse
    for node, fields in self.kks.parse(text):
AttributeError: 'mecab' object has no attribute 'kks'
19
根据以下术语表（可以为空）：


将下面的日文文本根据上述术语表的对应关系和备注翻译成中文：マルク：「別に、このくらいならお前も出来るだろ『ルイリ』」
Traceback (most recent call last):
  File "E:\Project\Test\LunaTranslator\hiraparse\basehira.py", line 58, in parseparse
    raise e
  File "E:\Project\Test\LunaTranslator\hiraparse\basehira.py", line 55, in parseparse
    hira = self.parse(text)
  File "E:\Project\Test\LunaTranslator\hiraparse\mecab.py", line 83, in parse
    for node, fields in self.kks.parse(text):
AttributeError: 'mecab' object has no attribute 'kks'
16
```

不知为啥，激活占用符后术语表就不见了，感觉有点神奇

**Comment by HIllya51** [comment]
哦 我懂了

**Comment by chlbc** [comment]
我这边测试正常了，感谢大佬！！
