### ISSUE TITLE
日语-英语、日语-俄语词典

### ISSUE THREAD

**Issue by KirpichKrasniy** [HIllya51/LunaTranslator#97]
你能添加一个JMdict字典吗在英语和俄语支持下? (edict, edict2)

**Comment by KirpichKrasniy** [comment]
或 Jardic，它支持许多其他日语-英语和日语-俄语词典

**Comment by KirpichKrasniy** [comment]
是否可以添加翻译器"reverso context"、通常的"reverso"和"yandex translate"
他们用英语和俄语很好

**Comment by KirpichKrasniy** [comment]
https://libretranslate.com/
https://github.com/LibreTranslate/LibreTranslate

和"平衡翻译"，但我不知道它是否能很好地翻译

**Comment by HIllya51** [comment]
> 你能添加一个JMdict字典吗在英语和俄语支持下? (edict, edict2)

看了半天，JMdict格式太复杂了，一时半会儿搞不定。不多edcit和edict2可以。

**Comment by HIllya51** [comment]
> 或 Jardic，它支持许多其他日语-英语和日语-俄语词典

我没能找到你说的这个词典

**Comment by HIllya51** [comment]
> 

我可以添加reverso翻译。
yandex翻译由于有非常复杂的人机验证，因此无法添加。

**Comment by HIllya51** [comment]
> https://libretranslate.com/ https://github.com/LibreTranslate/LibreTranslate
> 
> 和"平衡翻译"，但我不知道它是否能很好地翻译

我试过这个翻译器，它的效果非常差。。。

**Comment by HIllya51** [comment]
> https://github.com/leminhyen2/Sugoi-Japanese-Translator 苏霍伊有一个很好的日语翻译. 我认为有日语单词的过滤设置，但我不知道它们是如何工作的。 你能看看吗？

没明白你说的什么意思。

**Comment by KirpichKrasniy** [comment]
> Jardic

> 我没能找到你说的这个词典

http://www.jardic.ru/index_e.htm 
不是字典，而是使用字典的程序

http://www.jardic.ru/dictionaries/dictionaries_e.htm
有各种词典，从日语到英语，从日语到俄语

**Comment by KirpichKrasniy** [comment]
>  yandex翻译由于有非常复杂的人机验证，因此无法添加。


我明白了。.Yandex被翻译成俄文，工作良好。不能加，没关系

**Comment by HIllya51** [comment]
什么叫“单词过滤”？

**Comment by KirpichKrasniy** [comment]
> 什么叫“单词过滤”？

说实话，我自己也不知道。我注意到sugoi完美的翻译。只有我打破了deepl（也许是地区限制），它对转会次数有限制

**Comment by KirpichKrasniy** [comment]
你能添加一个papago翻译器吗?

**Comment by KirpichKrasniy** [comment]
> 什么叫“单词过滤”？

质量调整

**Comment by KirpichKrasniy** [comment]
http://www.kecl.ntt.co.jp/icl/lirg/jparacrawl/

線下用日語 英語 還有英語翻譯器

**Comment by KirpichKrasniy** [comment]
> 早就有了。。

對不起，我沒注意到！ops

**Comment by KirpichKrasniy** [comment]
![image](https://user-images.githubusercontent.com/109726461/206843010-7d95e214-abcf-4dd1-8a96-efda3aca3971.png)
好像找到了修改日語對俄語翻譯的方法。 過濾器如下。
![image](https://user-images.githubusercontent.com/109726461/206843027-9ac1025a-9aae-4abb-bd83-1e70d39be26e.png)

「 ->  
」->
。->.
、->,
．->．

**Comment by KirpichKrasniy** [comment]
[textfilters.zip](https://github.com/HIllya51/LunaTranslator/files/10199604/textfilters.zip)
這裏有文本過濾器的另一個例子。 他們可能有助於提高認識和翻譯的質量。

**Comment by HIllya51** [comment]
> > 什么叫“单词过滤”？
> 
> 质量调整

哦 原来是这个意思。这个我早已经实现过了，而且还做了许多更丰富的处理。。。

**Comment by HIllya51** [comment]
> [textfilters.zip](https://github.com/HIllya51/LunaTranslator/files/10199604/textfilters.zip) 這裏有文本過濾器的另一個例子。 他們可能有助於提高認識和翻譯的質量。

这些都在“翻译优化”设置里面有。

**Comment by HIllya51** [comment]
“文本预处理”会处理原始文本。
“翻译优化”中的“翻译结果修正”会将最后的翻译结果进行修正，“专有名词翻译”可以强制要求一些词语翻译成需要的目标。

**Comment by KirpichKrasniy** [comment]
> > > 什么叫“单词过滤”？
> > 
> > 
> > 质量调整
> 
> 哦 原来是这个意思。这个我早已经实现过了，而且还做了许多更丰富的处理。。。

謝謝。你做的濾鏡怎麼打開？

重新啓動程序時，所有字段都是空的。
![Безымянный](https://user-images.githubusercontent.com/109726461/206849429-5a473a11-0e8c-4d96-966d-e1288e57b4c9.png)

**Comment by HIllya51** [comment]
你点击“保存并关闭”了吗？要点击这个按钮才会保存

**Comment by HIllya51** [comment]
你这么一说我突然发现之前也有人说重启后消失了，我现在才明白原来是这个原因，那我把这个按钮去掉好了😂

**Comment by KirpichKrasniy** [comment]
> 
> 哦 原来是这个意思。这个我早已经实现过了，而且还做了许多更丰富的处理。。。

設置了文本編輯過濾器，您說包含在上段中嗎？
![image](https://user-images.githubusercontent.com/109726461/206851698-95b2a2d9-0399-4e32-8228-80e780ceda1d.png)


我打開也翻譯不好。 按照我的設定，翻譯更準確。

**Comment by HIllya51** [comment]
呃。没懂你的意思

**Comment by KirpichKrasniy** [comment]
不是說是你做的嘛。
文本深度

您說的是用紅色四角形強調的設置嗎？

**Comment by HIllya51** [comment]
哦，是的，这是一些预设好的常见的处理。

**Comment by KirpichKrasniy** [comment]
😭翻譯器聽不懂我的話。😂 
![image](https://user-images.githubusercontent.com/109726461/206852539-2eb1b5e9-3052-462a-b5bf-959ad1f700a9.png)

**Comment by KirpichKrasniy** [comment]
> 哦，是的，这是一些预设好的常见的处理。

不能開或關嗎？ 
設置？

**Comment by HIllya51** [comment]
当然可以啊。😂？

**Comment by KirpichKrasniy** [comment]
> 当然可以啊。😂？

我們再也不能相互理解了。
說有事先安裝好的內置型濾鏡 
怎麼編輯呢？

**Comment by HIllya51** [comment]
內置的是不能编辑的。

**Comment by KirpichKrasniy** [comment]
> Встроенные нельзя редактировать.

知道了，謝謝。

**Comment by KirpichKrasniy** [comment]
我們創建了一個小文件來替換文本。)
[postprocessconfig.zip](https://github.com/HIllya51/LunaTranslator/files/10200914/postprocessconfig.zip)

**Comment by KirpichKrasniy** [comment]
[postprocessconfig.zip](https://github.com/HIllya51/LunaTranslator/files/10200981/postprocessconfig.zip)
jp + eng

**Comment by HIllya51** [comment]
谢谢

**Comment by KirpichKrasniy** [comment]
很高興能提供幫助。
我現在可以被認為是程序員嗎？😎

**Comment by KirpichKrasniy** [comment]
![image](https://user-images.githubusercontent.com/109726461/206895138-de5129d4-2a03-48bd-99ec-2571e502c439.png)
我發現了字符識別錯誤。設置中的調整被禁用！

**Comment by KirpichKrasniy** [comment]
我發現了字符識別錯誤。
校正僅在重新掃描後有效

https://user-images.githubusercontent.com/109726461/206895658-119ebac0-879e-410e-a609-09028119e0e0.mp4

**Comment by KirpichKrasniy** [comment]
text correction works only after clicking on the "repeat" button

Can you add a function to output recognized text + text after correction to a file? to make it easy to add adjustments

**Comment by KirpichKrasniy** [comment]
如果您打開自動翻譯，那麼一切正常。 詭異的

**Comment by HIllya51** [comment]
边框是有宽度的，在OCR时会进行截图，截图会把边框给截进去。

**Comment by KirpichKrasniy** [comment]
> 并不是。这其实是因为在首次选取OCR区域时，区域中并没有边框，而按下按钮时区域内存在边框。因为图像发生了变化因此导致OCR的结果不相同

ok i think i get it

**Comment by KirpichKrasniy** [comment]
I sent your app to my friends, and one of them suggested making the translation window more contrasty on the first launch so that it can be seen against a dark background

**Comment by KirpichKrasniy** [comment]
even at startup, the application automatically takes the words from the clipboard, and the greeting is not displayed. please make a stock selection on OCR

**Comment by KirpichKrasniy** [comment]
there is also a proposal to translate the page on the github into English and Russian. I can help with Russian, just tell me in what format is it better to send?

**Comment by HIllya51** [comment]
可以的，只需将README.md进行翻译即可。

**Comment by KirpichKrasniy** [comment]
> 可以的，只需将README.md进行翻译即可。

added 400 more fixes for English and 2 for Japanese

**Comment by KirpichKrasniy** [comment]
> 可以的，只需将README.md进行翻译即可。

[README.md](https://github.com/HIllya51/LunaTranslator/files/10202216/README.md)

**Comment by KirpichKrasniy** [comment]
Can I create Russian-speaking groups in VKontakte and Telegram for the program?

**Comment by KirpichKrasniy** [comment]
> 当然可以啊，这种事不用问我，你随意就好😂

I think it would be more honest to ask about such things)

**Comment by KirpichKrasniy** [comment]
Is it possible to make the text in the translation window be centered?
to be able to toggle left/right/center

**Comment by KirpichKrasniy** [comment]
my friend also has a lot of extra characters when recognizing english text. there are a lot of flashes / icons on the screen and the like. you need to find filters for correcting such characters. I will try to find

**Comment by KirpichKrasniy** [comment]
I asked a friend to collect garbage character data. just need to figure out how to sort them)

**Comment by HIllya51** [comment]
在“显示设置”中勾选“居中显示”

**Comment by KirpichKrasniy** [comment]
> 在“显示设置”中勾选“居中显示”

Thanks

**Comment by KirpichKrasniy** [comment]
> 

good afternoon, I made a correction for the translation into Russian, added a garbage recognition correction

please add these configs to the program with language selection. you need to sort the characters that should be displayed in other languages. for English, you need to leave English characters, for Chinese - Chinese characters. I do not understand them, so I ask you to do it!

[userconfig.zip](https://github.com/HIllya51/LunaTranslator/files/10207704/userconfig.zip)

**Comment by HIllya51** [comment]
为什么要添加这么多对单字符的修正呢。我认为只有对一些常见的错误字符组合进行修正才是有意义的。
甚至对于一些字符组合的替换也是有很大局限性的，例如： “青い”->“言い” ，但是“青い”并不是一个错误的词语，它的意思是“蓝色”；“あつし”->“あっし”，但是“あつし”也经常被用作人名。

**Comment by KirpichKrasniy** [comment]
> 为什么要添加这么多对单字符的修正呢。我认为只有对一些常见的错误字符组合进行修正才是有意义的。 甚至对于一些字符组合的替换也是有很大局限性的，例如： “青い”->“言い” ，但是“青い”并不是一个错误的词语，它的意思是“蓝色”；“あつし”->“あっし”，但是“あつし”也经常被用作人名。

Unfortunately, I don't understand Japanese and Chinese at all. I just took the examples from the files of another application.

and these characters were misunderstood. I wrote about this problem above:


> ![image](https://user-images.githubusercontent.com/109726461/206895138-de5129d4-2a03-48bd-99ec-2571e502c439.png) 我發現了字符識別錯誤。設置中的調整被禁用！

one character is always replaced by another. I did not find a better solution, so I did this

**Comment by HIllya51** [comment]
但也不能为此引入另一个错误。因此一些设置我不能把它们加入到预设中。
对于单字符的错误，想通过这样的规则进行修正是不可能的。

**Comment by KirpichKrasniy** [comment]
> 但也不能为此引入另一个错误。因此一些设置我不能把它们加入到预设中。 对于单字符的错误，想通过这样的规则进行修正是不可能的。

I agree. I was wrong

**Comment by HIllya51** [comment]
很抱歉，你能理解就好😂

**Comment by KirpichKrasniy** [comment]
I want to do the best, but it turns out as always bad
![image](https://user-images.githubusercontent.com/109726461/207051663-ca706f70-7271-4430-8ac3-ed115ac6a128.png)
xD

**Comment by HIllya51** [comment]
你已经提供了非常多的帮助了🙏

**Comment by KirpichKrasniy** [comment]
I searched for archives with garbage symbols that appear if not only an area with text is selected, but also all sorts of pictures, icons, and so on, but I did not find anything. I wanted to create one myself, but it didn't help much either...
in the end i just sort by english characters so they don't appear in the translation window. sort of like it helped clean up a lot of junk.

**Comment by HIllya51** [comment]
> in the end i just sort by english characters so they don't appear in the translation window. sort of like it helped clean up a lot of junk.

呃，我没理解这是什么意思。不妨举个例子。

**Comment by KirpichKrasniy** [comment]
> > in the end i just sort by english characters so they don't appear in the translation window. sort of like it helped clean up a lot of junk.
> 
> 呃，我没理解这是什么意思。不妨举个例子。

a friend in the game, where there were different flashes, icons coming out and the like, all sorts of incorrect translations from English and extra characters began to come out in the translation window. I just forbade the output of English letters and numbers

**Comment by HIllya51** [comment]
没明白。。。不如截个图看一下。

**Comment by KirpichKrasniy** [comment]
![image](https://user-images.githubusercontent.com/109726461/207063180-4e7a6c8d-8bf4-4fad-a15b-f96a7c33155a.png)
I compress the video up to 10 mb, it takes time))))))))))

**Comment by HIllya51** [comment]
“ forbade the output of English letters and numbers”，什么意思呢，禁止输出英文和数字的话那输出什么呢。。

**Comment by KirpichKrasniy** [comment]
> “ forbade the output of English letters and numbers”，什么意思呢，禁止输出英文和数字的话那输出什么呢。。

there will be only Russian letters

**Comment by KirpichKrasniy** [comment]
English-speaking users should be allowed to output English letters, because they will translate from English to English, respectively, and there will be no strange character sets

**Comment by KirpichKrasniy** [comment]
THEY DO NOT TRANSLATE FROM ENGLISH TO ENGLISH

**Comment by HIllya51** [comment]
你的意思是，想把识别到的英文和数字都去掉吗？
这个的话，其实在“翻译优化”中，有一个“过滤数字和英文字母”的选项，只需要把它打开就可以了。。。

**Comment by KirpichKrasniy** [comment]
OFF:
![image](https://user-images.githubusercontent.com/109726461/207065571-633984af-a590-412a-963c-724fba70eb2f.png)
ON:
![image](https://user-images.githubusercontent.com/109726461/207065915-d54769ec-a80f-4e88-ac52-fb11b0988cb1.png)

**Comment by KirpichKrasniy** [comment]
![image](https://user-images.githubusercontent.com/109726461/207066448-dfd36a15-fda6-4119-8695-470480fb912a.png)
this function removes English characters from the recognized text, and it becomes unreadable. and if you remove English characters from the translation window, then it simply disappears from the translation window

**Comment by KirpichKrasniy** [comment]
> 你的意思是，想把识别到的英文和数字都去掉吗？ 这个的话，其实在“翻译优化”中，有一个“过滤数字和英文字母”的选项，只需要把它打开就可以了。。。

this function is useful for translating from Japanese but not from English

**Comment by HIllya51** [comment]
哦，原来你的意思是这样啊。好吧。
不过这一设定并不是非常通用，只能作为你的个性化设置了，因为有时我也会进行一些中文到英文的翻译。。。

**Comment by KirpichKrasniy** [comment]
> 



> English-speaking users should be allowed to output English letters, because they DO NOT translate from English to English, respectively, and there will be no strange character sets

I wrote that when translating into English, you need to allow the use of English characters, which is logical.
I would suggest making a choice of different configs. jp -> eng, jp -> rus, jp -> eng  and so on

**Comment by HIllya51** [comment]
这样也太麻烦了，而且会导致旧的配置文件不再兼容。
我觉得这种设置还是交给用户自己来做吧。。。

**Comment by KirpichKrasniy** [comment]
> 



> 这样也太麻烦了，而且会导致旧的配置文件不再兼容。 我觉得这种设置还是交给用户自己来做吧。。。

then do what you think is best. I sent everything I could find and collect. I don't have any other ideas so I can't help. now you need to optimize the optimizer 😆😆😆😆

**Comment by HIllya51** [comment]
我尽量吧😂

**Comment by KirpichKrasniy** [comment]
I don't know what I did, but I accidentally broke everything, and instead of the recognized text in the window, there was text from the config.
Reinstalled the application, added the same values, and everything was repaired. I think it's worth it to stop there
but everything works now just wonderful
![d8c8cf6100d3889178f16d1ea03972f0](https://user-images.githubusercontent.com/109726461/207135250-ccf4a884-b102-4c4c-a76e-7de6e7aa5fa0.gif)

**Comment by KirpichKrasniy** [comment]
[userconfig v1.zip](https://github.com/HIllya51/LunaTranslator/files/10211359/userconfig.v1.zip)
However, now the old settings are mixed with new ones. It looks crooked, but it works. 👍

**Comment by KirpichKrasniy** [comment]
![image](https://user-images.githubusercontent.com/109726461/207139115-8a332547-2ddf-4a3b-aefb-ea831bb56115.png)
A friend asked to convey that a translation from Chinese did not work

**Comment by KirpichKrasniy** [comment]
Or he did not work before ...

**Comment by KirpichKrasniy** [comment]
A friend wanted to translate the Chinese manga (manhwa), but could not

**Comment by KirpichKrasniy** [comment]
> [zh.zip](https://github.com/HIllya51/LunaTranslator/files/10216039/zh.zip)
> 
> 将这个文件解压到files/ocr下。

is it possible to turn on text recognition from right to left, for reading manga?

**Comment by HIllya51** [comment]
这个做不到。。。这个软件一开始只是为galgame设计的，所以很多设计很难与漫画兼容。。。

**Comment by KirpichKrasniy** [comment]
> 这个做不到。。。这个软件一开始只是为galgame设计的，所以很多设计很难与漫画兼容。。。

I'm understood, thank you.
but I noticed that ![image](https://user-images.githubusercontent.com/109726461/207361318-8459b703-a4e1-4e57-8973-3f56c2d0cf2b.png) youdaOCR supports right-to-left OCR

**Comment by KirpichKrasniy** [comment]
![image](https://user-images.githubusercontent.com/109726461/207362403-e5a67d35-3085-4cd7-94ad-5bc64aceb8d3.png)
![image](https://user-images.githubusercontent.com/109726461/207362519-bfdb2e8c-a655-44e6-954d-18611abdca62.png)

**Comment by HIllya51** [comment]
YoudaoOCR使用的是通过逆向工程得到的不稳定的在线接口，它其实是一个商用接口，当然会比本地的轻量级OCR性能强的多。

**Comment by KirpichKrasniy** [comment]
![image](https://user-images.githubusercontent.com/109726461/207363321-284e892b-5de4-4485-91c1-2efcc10bd797.png)
he really recognizes very well. However, it used to be unstable and often didn't display recognized text. perhaps because of the limit on the number of views.
but now it works well and stable

**Comment by HIllya51** [comment]
这个全看运气了

**Comment by KirpichKrasniy** [comment]
> 这个全看运气了

![image](https://user-images.githubusercontent.com/109726461/207373174-584517f2-ae7d-42c8-b028-847472f104f5.png)
if I translate the instruction page into Russian, can you add it?

**Comment by HIllya51** [comment]
说明页的代码实际上在这里： https://github.com/HIllya51/HIllya51.github.io
不过，这个说明其实已经是个落后于版本很多很多的说明了，因此不是很建议你对其进行翻译。。。😂

**Comment by KirpichKrasniy** [comment]
> 说明页的代码实际上在这里： https://github.com/HIllya51/HIllya51.github.io 不过，这个说明其实已经是个落后于版本很多很多的说明了，因此不是很建议你对其进行翻译。。。😂

I want to translate at least the basic functions so that people have instructions for at least the basic settings. many new users at the first start do not understand how to configure

**Comment by HIllya51** [comment]
可以的，而且这个我也一般懒得去修改😂
如果你愿意的话，可以不只是翻译，你可以按照你所愿的那样介绍，或者添加或删除一些页，增加删除或修改一些图片都是可以的。
你可以随心所欲的去做，最后我会把你的图片+md文件，将它们制作成网页上的那个样子。

**Comment by KirpichKrasniy** [comment]
> 可以的，而且这个我也一般懒得去修改😂 如果你愿意的话，可以不只是翻译，你可以按照你所愿的那样介绍，或者添加或删除一些页，增加删除或修改一些图片都是可以的。 你可以随心所欲的去做，最后我会把你的图片+md文件，将它们制作成网页上的那个样子。

I will try to make the most complete description of the settings, but only in Russian.
if you can translate the instructions into other languages in the future, then you can try)

**Comment by KirpichKrasniy** [comment]
> 可以的，而且这个我也一般懒得去修改😂 如果你愿意的话，可以不只是翻译，你可以按照你所愿的那样介绍，或者添加或删除一些页，增加删除或修改一些图片都是可以的。 你可以随心所欲的去做，最后我会把你的图片+md文件，将它们制作成网页上的那个样子。

Can I leave links to the Russian community in VKontakte and Telegram in the readme file?

**Comment by HIllya51** [comment]
可以

**Comment by KirpichKrasniy** [comment]
thx

**Comment by KirpichKrasniy** [comment]
I will first translate the material that is already there, and then add a description of the settings that are missing

**Comment by HIllya51** [comment]
对于一些已经过时的内容，你也可以将它们删除掉

**Comment by KirpichKrasniy** [comment]
> Некоторый устаревший контент также можно удалить.

ok

**Comment by KirpichKrasniy** [comment]
> 对于一些已经过时的内容，你也可以将它们删除掉

you can remove the "[资源下载](https://hillya51.github.io/#/install)" tab and leave only "[功能支持](https://hillya51.github.io/#/README?id=%e5%8a%9f%e8%83%bd%e6%94%af%e6%8c%81)"

[README_ru.zip](https://github.com/HIllya51/LunaTranslator/files/10220521/README_ru.zip)

**Comment by KirpichKrasniy** [comment]
[README_ru.zip](https://github.com/HIllya51/LunaTranslator/files/10220910/README_ru.zip)

**Comment by KirpichKrasniy** [comment]
I was asked if the program loads the PC system too much. I don't know anything about program optimization. tests will need to be done

**Comment by KirpichKrasniy** [comment]
I was also asked about an offline translator into Russian. I understand that the built-in translators are not able to translate into Russian, but if you have the opportunity to add such, then it will be good. I will try to look for translators myself that can be easily implemented into the program, and later I will write to you

**Comment by HIllya51** [comment]
> I was asked if the program loads the PC system too much. I don't know anything about program optimization. tests will need to be done

呃，我已经做过大量优化了，很多模块我都用c++重写了，在非OCR模式下只会占用100MB内存，OCR模式也只会占用200MB内存，这并不多吧。。。

**Comment by HIllya51** [comment]
> I was also asked about an offline translator into Russian. I understand that the built-in translators are not able to translate into Russian, but if you have the opportunity to add such, then it will be good. I will try to look for translators myself that can be easily implemented into the program, and later I will write to you

我对俄语的离线翻译器不是很了解。
添加离线翻译不是一件一定能成功的事，你可以多提供一些可选的翻译器。

**Comment by KirpichKrasniy** [comment]
> > I was asked if the program loads the PC system too much. I don't know anything about program optimization. tests will need to be done
> 
> 呃，我已经做过大量优化了，很多模块我都用c++重写了，在非OCR模式下只会占用100MB内存，OCR模式也只会占用200MB内存，这并不多吧。。。

thanks for the answer

**Comment by KirpichKrasniy** [comment]
> > I was also asked about an offline translator into Russian. I understand that the built-in translators are not able to translate into Russian, but if you have the opportunity to add such, then it will be good. I will try to look for translators myself that can be easily implemented into the program, and later I will write to you
> 
> 我对俄语的离线翻译器不是很了解。 添加离线翻译不是一件一定能成功的事，你可以多提供一些可选的翻译器。

I will try to find good translators in the Russian segment of the Internet. maybe I'll find something

**Comment by KirpichKrasniy** [comment]
> > > I was also asked about an offline translator into Russian. I understand that the built-in translators are not able to translate into Russian, but if you have the opportunity to add such, then it will be good. I will try to look for translators myself that can be easily implemented into the program, and later I will write to you
> > 
> > 
> > 我对俄语的离线翻译器不是很了解。 添加离线翻译不是一件一定能成功的事，你可以多提供一些可选的翻译器。
> 
> I will try to find good translators in the Russian segment of the Internet. maybe I'll find something

Translatium Desktop
https://virtaal.translatehouse.org
https://apps.kde.org/lokalize/
https://omegat.org/es/

I found several offline translators, but I'm not sure if they can be integrated into the program without problems

I don't quite understand what to look for...

**Comment by KirpichKrasniy** [comment]
I'm sorry, I'll look and check. So far I haven't found anything...
there are only some apps for android but i don't think they fit

**Comment by KirpichKrasniy** [comment]
Is it possible to add Microsoft Offline Translator?
unfortunately I didn't find anything else(

**Comment by HIllya51** [comment]
请把软件打包发给我

**Comment by KirpichKrasniy** [comment]
it can be downloaded from the microsoft store, but I have it cut out, and I'm trying to find a crack
![image](https://user-images.githubusercontent.com/109726461/207572511-f6c31ad4-67b8-40db-ba61-310da71620f2.png)

**Comment by KirpichKrasniy** [comment]
Microsoft Translator does not want to install language packs for online work. as I understand it, this does not work even in the version from the microsoft store
![image](https://user-images.githubusercontent.com/109726461/207589759-77ab819c-568f-447c-93dc-de52b52ab0fd.png)

**Comment by HIllya51** [comment]
。。。这是在线翻译接口，并不是离线翻译。

**Comment by KirpichKrasniy** [comment]
> 。。。这是在线翻译接口，并不是离线翻译。

I understand it.
I tried to find how to fix dictionaries in the offline microsoft translator, but I did not find anything

**Comment by KirpichKrasniy** [comment]
I also found an offline translator from the author sugoi translator
it translates online from japanese to english, but the translation quality is poor
