### ISSUE TITLE
DeepLX v2 integration

### ISSUE THREAD

**Issue by krakerz** [HIllya51/LunaTranslator#970]
### Expected behavior 预期的功能

If possible, please add for DeepLX integration v2 API (make it as an option, to choose normal method or v2, just for alternative options, it's working fine with normal method)
normal is /translate
v2 is /v2/translate
as specified in https://deeplx.owo.network/endpoints/official.html

the only differences (as far as i know) in v2 vs normal is, it's auto detect the language, and you only need to add [ ] in text object
the response is different as well, more simple and it's shown in the screenshot below
![image](https://github.com/user-attachments/assets/641687da-a341-4673-8c28-50624e151d84)
the normal ones
![image](https://github.com/user-attachments/assets/09547035-3cae-4da6-9d06-c63b2612f8a1)

**Comment by HIllya51** [comment]
No. 
This thing is garbage and not stable at all. 
If you want to use deepl for free, you can translate it with the debug browser.

**Comment by krakerz** [comment]
> No. This thing is garbage and not stable at all. If you want to use deepl for free, you can translate it with the debug browser.

RIP, i guess i'll stick to deeplx normal mode and sugoi then, debug browser option throw errors and not working (with any provider) for me

{'id': 2, 'error': {'code': -32000, 'message': 'Not supported'}}
Traceback (most recent call last):
  File "E:\Tools\OCR\LunaTranslator\LunaTranslator\translator\basetranslator_dev.py", line 124, in _SendRequest
    return res["result"]
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Tools\OCR\LunaTranslator\LunaTranslator\translator\basetranslator.py", line 97, in level2init
    self._private_init()
  File "E:\Tools\OCR\LunaTranslator\LunaTranslator\translator\basetranslator_dev.py", line 102, in _private_init
    self._createtarget()
  File "E:\Tools\OCR\LunaTranslator\LunaTranslator\translator\basetranslator_dev.py", line 147, in _createtarget
    a = self._SendRequest("Target.createTarget", {"url": url}, ws=ws)
  File "E:\Tools\OCR\LunaTranslator\LunaTranslator\translator\basetranslator_dev.py", line 127, in _SendRequest
    raise Exception()
Exception

**Comment by HIllya51** [comment]
Anyway, my test is working normally.

**Comment by krakerz** [comment]
> Anyway, my test is working normally.

hmmmm
you just need to pointing the chromium directory right? (atleast in option seems only that way)
