### ISSUE TITLE
Sakura GPT 词典的词条在目标语言为繁体时的简繁转换错误问题

### ISSUE THREAD

**Issue by chlbc** [HIllya51/LunaTranslator#975]
### Expected behavior 预期的功能

当目标语言是繁体、Sakura 0.10pre1、使用 GPT 词典时，
可能会因为翻译结果简转繁错误转换的关系，
导致翻译结果中的词汇与 GPT 词典中定义的不同。

因此想询问说当目标语言是繁体、使用 Sakura 0.10pre1 且激活 GPT 词典时，
有沒有可能在 Sakura 翻译完后，添加类似占位符之类的措施，
以让在 GPT 词典中的词汇不会被简繁转换转错。

可能像是下面這樣：
   1. 术语表：`ルイリ　　盧伊里　　男性`
   2. 使用 Sakura 翻译`…ルイリ…`
   3. 翻译后为：`…盧伊里…`
   4. （当前没有）将译文中的 GPT 词典翻译后词条转为“ZXWAZ”、“ZXWBZ”等形式：`…ZXWAZ…`
   5. 翻译结果简繁转换：`…ZXWAZ…`
   6. （当前没有）将“ZXWAZ”、“ZXWBZ”等占位符转回翻译后词条：`…盧伊里…`
   7. 输出翻译结果：`…盧伊里…`

如此才能正确获得 GPT 词典定义的`…盧伊里…`，
但若不以占位符等方式处理（即沒有步骤 4、6），则会输出不符合 GPT 词典的`…盧伊裡…`
（简体“里”-> 繁体“里”、“裡”）

P.S. 我这边目前是在发生该错误时，
就额外在“翻译结果修正”多加一行来处理，
但这种错误在专有名词简转繁中颇常见，
故回报一下。

### Alternative behavior (optional) 近似的功能（可选）

sakura gpt 词典、占用符、简繁转换

**Comment by HIllya51** [comment]
这个问题对于其他翻译引擎也是存在的。如果翻译引擎不原生支持繁体中文，那就是没有办法的事。

**Comment by chlbc** [comment]
了解，
我原本想说 gpt 词典里输入繁体中文词条的话，
这样的方法会不会可行。

不过我这边测试后，
就算目标语言是简体，
但在 gpt 词典里输入繁体词条后，
该译文的该词条依然是简体，
这样的话类似占用符的方法确实不可行没错。

话说我发现一件事：
在 [sakura.py 第 110 行](https://github.com/HIllya51/LunaTranslator/blob/f5d7fd57644631ec3cc53802f11e8592b88d5ac1/LunaTranslator/LunaTranslator/translator/sakura.py#L110C17-L110C79)的`gpt_dict_raw_text = zhconv.convert(gpt_dict_raw_text, "zh-cn")`似乎会在繁体时，
将`gpt_dict_raw_text`全部转成简体，
但是好像只有`翻译`和`注释`需要翻成简体，
`原文`（日文）好像不用？

**Comment by HIllya51** [comment]
那你改下吧。

**Comment by chlbc** [comment]
好，我看一下要怎改

**Comment by chlbc** [comment]
改好了，再麻烦大佬看一下
