### ISSUE TITLE
Translation Optimization not working

### ISSUE THREAD

**Issue by favidelta** [HIllya51/LunaTranslator#977]
### Version 程序版本

5.23.5

### OS version and bits 系统版本和位数

Windows 11 23H2 64bit

### bug's screenshot 错误截图

![Screenshot 2024-08-09 200803](https://github.com/user-attachments/assets/a4c55b10-89f1-45a0-b34d-02a62c7338f0)

### Reproduction steps 复现步骤

Translation Optimization for characters names (直接替换) no longer works in the recent version. It was working fine before v5.23.

### Log files 日志文件

[2024-08-09-20-00-19.txt](https://github.com/user-attachments/files/16561663/2024-08-09-20-00-19.txt)

**Comment by HIllya51** [comment]
update
