### ISSUE TITLE
使用Hook时翻译器闪退

### ISSUE THREAD

**Issue by AAxjcy** [HIllya51/LunaTranslator#978]
### Version 程序版本

5.23.6

### OS version and bits 系统版本和位数

windows 11 23H2 64bit

### bug's screenshot 错误截图

![image](https://github.com/user-attachments/assets/41251a62-136a-4adf-a26a-995a7ae26bb4)

### Reproduction steps 复现步骤

打开（日文）游戏和翻译器，链接到游戏后找到文本并点击显示，当进入对话界面时游戏和翻译器都出现明显卡顿，随后翻译器闪退，游戏一切正常

### Log files 日志文件

[2024-08-09-21-48-59.txt](https://github.com/user-attachments/files/16562031/2024-08-09-21-48-59.txt)

**Comment by HIllya51** [comment]
把游戏给我。

**Comment by HIllya51** [comment]
开内嵌翻译了吗

**Comment by AAxjcy** [comment]
内嵌模式不会开，不过只打开选择文字界面的内嵌开关并不会闪退

**Comment by AAxjcy** [comment]
游戏超过25MB，无法发送

**Comment by HIllya51** [comment]
onedrive/googledrive给我

**Comment by HIllya51** [comment]
或者用这个给我
https://www.wenshushu.cn/

**Comment by HIllya51** [comment]
你让他闪退了再把闪退的log给我啊，这个log没有任何有用的信息。

**Comment by AAxjcy** [comment]
闪退后就只有这个log

**Comment by AAxjcy** [comment]
https://f.ws28.cn/f/estvmsfrect

**Comment by AAxjcy** [comment]
[2024-08-09-22-05-08.txt](https://github.com/user-attachments/files/16562190/2024-08-09-22-05-08.txt)
或者就是这个更短的log

**Comment by HIllya51** [comment]
![屏幕截图 2024-08-09 220633](https://github.com/user-attachments/assets/81bbaf90-9e56-4113-9e40-421d8e9a65cd)

**Comment by HIllya51** [comment]
你怎么搞得闪退的

**Comment by HIllya51** [comment]
我测试没任何问题啊

**Comment by HIllya51** [comment]
哦 我知道了

**Comment by AAxjcy** [comment]
https://www.wenshushu.cn/f/estzfyr3l2l

**Comment by AAxjcy** [comment]
https://github.com/user-attachments/assets/56d45c41-79ba-496a-8ab8-a8b189016205
