### ISSUE TITLE
有道翻譯輸出簡繁輸出問題及工具列圖示問題

### ISSUE THREAD

**Issue by a73420521** [HIllya51/LunaTranslator#98]
請問在最新版中有道翻譯是不是無法輸出成繁體?
![1](https://user-images.githubusercontent.com/87113124/206856057-19377dd6-f393-4a15-80ff-fc8278309516.png)
![2](https://user-images.githubusercontent.com/87113124/206856063-59b8cc72-e408-43f0-9e7d-5a424866e171.png)
還有，之前的版本圖示是縮小在右下角的小圖示，而新版的會固定在工具列上顯示，這是新的改變嗎?
![3](https://user-images.githubusercontent.com/87113124/206856320-450c1e47-cde4-40a8-b3dd-3d4bf358cbbb.png)

**Comment by HIllya51** [comment]
这是一个bug 已修正😂
