### ISSUE TITLE
Doesn't detect Character game

### ISSUE THREAD

**Issue by Yuriuori** [HIllya51/LunaTranslator#980]
### Version 程序版本

v5.25.1

### OS version and bits 系统版本和位数

Windows 11

### bug's screenshot 错误截图

Hello I found a visual novel that doesn't detect the character name for some reason but the text work really fine the visual novel name is: Mitama ~Shinobi~, 御魂～忍～
![Screenshot 2024-08-10 235347](https://github.com/user-attachments/assets/dce40fd0-cb99-45c0-97d9-d3dd158e8068)
![Screenshot 2024-08-10 235356](https://github.com/user-attachments/assets/49b51738-2fba-4226-907f-e88477b4d8ef)

### Reproduction steps 复现步骤

.

### Log files 日志文件

.

**Comment by Yuriuori** [comment]
Will it get fix cuz it's still same error after i updated
![image](https://github.com/user-attachments/assets/6baec4e3-9f3f-4c34-a0e0-567e49521ead)

**Comment by HIllya51** [comment]
use text process to filter the dumplicate

**Comment by Yuriuori** [comment]
May i know which one ? cuz i check them one by one didn't fix it
![Uploading image.png…]()

**Comment by Yuriuori** [comment]
![image](https://github.com/user-attachments/assets/7b5897da-398a-4886-8de7-24792f66182f)

**Comment by Yuriuori** [comment]
I really did everything nothing happen :( [HIllya51](https://github.com/HIllya51)

**Comment by HIllya51** [comment]
莫名其妙
