### ISSUE TITLE
Is there any way to replace the text in manga with the translation using OCR?

### ISSUE THREAD

**Issue by Sarata137** [HIllya51/LunaTranslator#982]
### Question 问题

Do you have any setting that can put translated text over the text in manga bubbles directly? I know I can have it in a separate lunatranslator big window but it gets confusing when there are too many speech bubbles on a manga sheet. Can I just replace the japanese text with the english translation in manga? Thanks

**Comment by Farooq87** [comment]
> ### Question 问题
>I know I can have it in a separate lunatranslator big window but 

@Sarata137 Please explain how to achieve it? What separate big window?

**Comment by Farooq87** [comment]
> ### Question 问题
> Do you have any setting that can put translated text over the text in manga bubbles directly? I know I can have it in a separate lunatranslator big window but it gets confusing when there are too many speech bubbles on a manga sheet. Can I just replace the japanese text with the english translation in manga? Thanks

@Sarata137 
I don't know what separate Luna window with translated image you talked about. I have just found that there is no such function at all in Luna Translator
https://github.com/HIllya51/LunaTranslator/issues/1010

**Comment by Sarata137** [comment]
> > ### Question 问题
> > Do you have any setting that can put translated text over the text in manga bubbles directly? I know I can have it in a separate lunatranslator big window but it gets confusing when there are too many speech bubbles on a manga sheet. Can I just replace the japanese text with the english translation in manga? Thanks
> 
> @Sarata137 I don't know what separate Luna window with translated image you talked about. I have just found out that there is no such function at all in Luna Translator #1010

Ok thank you. By the separate window meant the window with the translations.
