### ISSUE TITLE
大佬求助，ocr识别tgw怎么设置才能让它显示出来

### ISSUE THREAD

**Issue by Z9wind** [HIllya51/LunaTranslator#983]
### Question 问题

以前真的没出现问题的，都用这个OCR功能打通一个游戏了，最近又有一个游戏需要OCR才发现现在TGW无法正常显示了，上次有提过一个问询议题的，大佬你这边告知是tgw翻译太慢了，但我是有把收到翻译再刷新这个功能打开的，能帮忙看一下怎样调整才能让TGW正常显示吗？HOOK的话就不会出现这个问题，HOOK状态下就是TGW比别的翻译会慢几秒出现。
现在OCR状态分两种：1、不开流式时特别短的句子可以显示出来，一长就不显示了得点下刷新才会一下子出来（应该在缓存里了），2、打开流式时会显示一点点然后就中断了
上传了下视频，大佬如果有空的话辛苦看下：
https://drive.google.com/file/d/1n400qfc6QqgmKr7GcPAKOygnj4pPn3Yc/view?usp=drive_link
https://drive.google.com/file/d/1pWOx3lrM4IjLkBhZkfnbcljgk8DPHMwK/view?usp=drive_link

**Comment by HIllya51** [comment]
tgw已经被放弃支持，你把url填到chatgpt兼容接口里试下吧。

**Comment by Z9wind** [comment]
好的我明天试下，谢谢！

**Comment by HIllya51** [comment]
tgw这个东西问题很大，不建议使用tgw。
（而且你大概在用sakura模型？那么你应该使用sakura大模型的专用接口，这个对sakura模型有专门的优化。）

**Comment by HIllya51** [comment]
我猜你是看了那个up的视频来用的tgw？
建议不要用tgw，同样的模型用llamacpp就没问题，tgw一堆问题。
更坑的是有一堆人来问我tgw的bug，我都没怎么用过tgw。。。

**Comment by Z9wind** [comment]
对的;;; 其实我也是看了那个视频才知道luna的哈哈
好的我研究下llamacpp

**Comment by HIllya51** [comment]
https://github.com/SakuraLLM/SakuraLLM/wiki
不用特意研究，你看下sakurallm的wiki就行了，llamacpp最简单也最好
（刚才看到sakurallm的wiki里也写了：“注：如果你并不具备一定的python和debug的能力，请一定不要用text-generation-webui部署模型！”）

**Comment by HIllya51** [comment]
![屏幕截图 2024-08-12 032432](https://github.com/user-attachments/assets/6aef3c66-40e8-4eb0-a2b8-b7d3771513a4)
