### ISSUE TITLE
How to Add another AI translator in ChatGPT-Mirror Settings (Debug Browser)

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#985]
### Question 问题

Please dear friend @HIllya51 consult me how to add there another one AI-translator properly
I have found another cool and free option https://labs.perplexity.ai/
I opened ChatGPT Mirror
![noVPN CHATGPT](https://github.com/user-attachments/assets/25d7ea41-01e5-4ac0-86df-a388dbdc49be)
Then I changed link there on https://labs.perplexity.ai/
![image](https://github.com/user-attachments/assets/3465be11-a7d6-4039-930a-22fac5452636)

Problem is it doesn't return back translation from web-page to Luna and it doesn't push button 'Send' automatically.
It must be something to do with CSS selector lines. What code to add there?
![image](https://github.com/user-attachments/assets/4341331a-eb16-4340-8875-3966061b7fbb)

**Comment by HIllya51** [comment]
This type of website is not supported.

**Comment by Farooq87** [comment]
> This type of website is not supported.

@HIllya51 
Please consider add this unofficial online version of ChatGPT as supported site.
https://chatgptchatapp.com/
Its free for everyone turbo-3.5 and doesn't ask secret key, vpn.
Folks from Russia would be very thankful for this.
