### ISSUE TITLE
Unofficial ChatGPT in 'browser debug' section

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#986]
### Expected behavior 预期的功能

I have latest Luna version 5.26.2.0
Dear @HIllya51 could you please add this very convenient for many users unofficial version of ChatGPT to 'browser debug'
https://chatgptchatapp.com/
It has no registration, no key, no VPN needed
Unlimited 4o and 3.5
Many users of Luna would thank you eternally for this dev-translator. Please!

**Comment by HIllya51** [comment]
I have already said I don’t support it, don’t bother me.

**Comment by HIllya51** [comment]
I have no interest in this kind of junk website full of advertisements. Please don't bother me with this kind of stuff again and again.

**Comment by Farooq87** [comment]
@HIllya51 
Thank you for theb.ai 
I can't express how I am thankful to you, dear friend @HIllya51
You are the best!!!
祝你吉祥康乐
