### ISSUE TITLE
Game Character name still doesn't detect it

### ISSUE THREAD

**Issue by Yuriuori** [HIllya51/LunaTranslator#987]
### Version 程序版本

v5.26.3

### OS version and bits 系统版本和位数

Windows 11

### bug's screenshot 错误截图

https://drive.google.com/file/d/1_YKUvOkkiQ1B4Zk_TqVVkAgQAHwmr12W/view

Hello @HIllya51 

 I found a visual novel that doesn't detect the character name for some reason, even when i try text process still same issue, but the text work really fine the visual novel name is: Mitama Shinobi, 御魂～忍～

### Reproduction steps 复现步骤

你好 @HIllya51

我发现了一款视觉小说，它在某些情况下无法检测到角色名字。即使我尝试处理文本，问题依然存在，但文本本身工作得很好。这款视觉小说的名字是：御魂～忍～。

### Log files 日志文件

.

**Comment by HIllya51** [comment]
提取人名没有意义

**Comment by Yuriuori** [comment]
@HIllya51 I don't understand Japanese so that's why i'm asking because i don't know who is talking i really hope it fix and i can extract people's name
