### ISSUE TITLE
Sakura LLM. API link

### ISSUE THREAD

**Issue by Farooq87** [HIllya51/LunaTranslator#988]
### Question 问题

What link to add there in order Sakura works in Luna.
That link http://127.0.0.1:8080/ which was put there initially gives an error 
![sakuraint](https://github.com/user-attachments/assets/0c58b1ba-1761-4121-9a99-78ddc8f13c0f)
![image](https://github.com/user-attachments/assets/ab5279d1-551b-4f78-b4e9-d05518fda3a7)

**Comment by HIllya51** [comment]
Can you please stop asking me such boring questions? It's really annoying.
If you don't know how to use sakura, don't use it. There's no point in asking.

**Comment by HIllya51** [comment]
﻿I'm not interested in teaching you.
And the tutorial link is clearly provided above, you didn't go to the tutorial but came to ask me such a boring question

**Comment by Farooq87** [comment]
> I'm not interested in teaching you. And the tutorial link is clearly provided above, you didn't go to the tutorial but came to ask me such a boring question

If I annoy you, I apologize. I have no intention to annoy you, my friend. And wish you well. My only goal is deep knowledge in Luna Translator.
