### ISSUE TITLE
您可以添加一个名为EasyOCR的新文本识别器

### ISSUE THREAD

**Issue by gqwg2003** [HIllya51/LunaTranslator#989]
### Expected behavior 预期的功能

只是我的建议如果你不喜欢就不用加了不想我就明白了

### Alternative behavior (optional) 近似的功能（可选）

是的，如果你阅读并回答我，我真的很感谢你。

**Comment by HIllya51** [comment]
他比内置的OCR烂多了，添加它没有任何意义
