### ISSUE TITLE
add an LLM fallback list when a refusal string is detected

### ISSUE THREAD

**Issue by Tor-Saxberg** [HIllya51/LunaTranslator#990]
### Expected behavior 预期的功能

currently you can get translations from multiple selected LLMs. 
you can also replace a translation string (i.e "I'm sorry, but I cannot assist with this") with another string.

### Alternative behavior (optional) 近似的功能（可选）

However, it would be nice to only call the next LLM when that refusal string is detected in the first LLM. 
this way, only one translation shows up in the floating window, and you can save API money with 4o-mini most of the time. 
Ideally this would be in display settings -> show content -> translate. There's even an open space on the top right for it.

if this is already possible, please let me know how.

**Comment by HIllya51** [comment]
You should use a better prompt to avoid this from happening, instead of using this inexplicable thing

**Comment by Tor-Saxberg** [comment]
There is no universal jailbreaking prompt for 4o-mini, and who wants to write a new prompt each time the old one fails, anyways. it makes more sense to switch AI's to deepl or Google that are less restrictive in those cases. 

This repository greatly facilitates the translation process, so this high-value low-hanging fruit should fit nicely into that mission by eliminating a common pain point. 

It's hardly inexplicable; it's a one-sentence suggestion: fallback on a less restrictive AI when the better, more restrictive one fails.
