### ISSUE TITLE
automate click/keystroke after translation

### ISSUE THREAD

**Issue by Tor-Saxberg** [HIllya51/LunaTranslator#991]
### Expected behavior 预期的功能

currently, nothing happens after a translation shows up in the floating window. If you don't want to manually click through a game, you have to use the games auto play feature. 
However, not every game supports string-length based timing, so some messages will disappear too soon/late. 
Even when they do have that option (usually via the text write speed), the hook may only see the text when the full string is displayed in-game, defeating the point. 

### Alternative behavior (optional) 近似的功能（可选）

It may be a simple fix to just pass an [enter] or [left mouse click] to the selected game when a translation is returned. 
There's already an option to simulate the [enter] key in display settings -> tool button, but it's not automatic. 
The main difference is the stirng-length based delay before sending the [enter] key.

This way, Luna Translator can manage the timing itself without even relying on the game options. Furthermore, you would only need to set this up once and it would apply to every game.

**Comment by HIllya51** [comment]
What weird stuff are you talking about?

**Comment by HIllya51** [comment]
I don't understand your train of thought at all, it's very confusing

**Comment by Tor-Saxberg** [comment]
I can simplify the chain of thought:
1) autoplay in games often causes translations to be cut off.
2) the simple fix is to wait for a translation and then simulate an [enter] key press.
3) there should be a delay before [enter] so there is time to read the text.
4) the delay should be related to the length of the text.
5) the translation and the [enter] key press are already built. you just need to automate it and add a delay.

**Comment by HIllya51** [comment]
Very boring feature, no point at all
