### ISSUE TITLE
关于专有名词翻译 占位符

### ISSUE THREAD

**Issue by chlbc** [HIllya51/LunaTranslator#995]
### Expected behavior 预期的功能

希望 Global 设置的专有名词翻译 占位符能修改以下特性：
1. 若当前游戏个别设置的翻译优化中，跟随默认为 OFF 时，
则 Global 设置的占位符设置在添加新词条时，
游戏 ID 能自动设为 0（全局）
2. 希望在复制词条到 Global 设置的占位符时，
如果粘贴时不包含游戏 ID，
则自动将粘贴词条的游戏 ID 设为 0（全局）

### Alternative behavior (optional) 近似的功能（可选）

专有名词翻译 占位符、表格复制粘贴

**Comment by HIllya51** [comment]
不可以。这个东西已经在我的废弃计划之上了。

**Comment by chlbc** [comment]
了解，因为现在基本上都用游戏设置里的占用符，
每次要加全局的都还要再特别把 ID 改成 0，
有点小麻烦。
如果废弃之后不用再每次加全局词条都要特别改 ID 就太好了。
