### ISSUE TITLE
彩云在线报错，其他没问题

### ISSUE THREAD

**Issue by qscasdasd** [HIllya51/LunaTranslator#997]
### Version 程序版本

最新版

### OS version and bits 系统版本和位数

win10 1909

### bug's screenshot 错误截图

![QQ截图20240815172013](https://github.com/user-attachments/assets/79bfa471-d53f-4ab4-81c9-7962ca0136c9)

### Reproduction steps 复现步骤

直接测试翻译复现

### Log files 日志文件

[2024-08-15-17-22-25.txt](https://github.com/user-attachments/files/16623753/2024-08-15-17-22-25.txt)

**Comment by HIllya51** [comment]
彩云似乎服务端挂了，网页上也翻译不了
