### ISSUE TITLE
缩写解密

### ISSUE THREAD

**Issue by gqwg2003** [HIllya51/LunaTranslator#998]
### Expected behavior 预期的功能

 缩写解密        在此函数内部添加添加自己缩写的功能                                                                                                                                                             

 添加缩写和的单独段落。 几个单词的缩写由第一个字母从每个单词中取出并组合成一个单词以添加成绩单   

### Alternative behavior (optional) 近似的功能（可选）

如果您考虑添加此功能，非常感谢。

**Comment by HIllya51** [comment]
你在说什么玩意。。😅

**Comment by gqwg2003** [comment]
Я имею в виду транскрипцию аббревиатур, основанную на типе Советского Союза

**Comment by gqwg2003** [comment]
我的意思是根据苏联的类型缩写的转录

**Comment by gqwg2003** [comment]
关于其他国家

**Comment by HIllya51** [comment]
你是俄国人？你为什么不用英语，你这蹩脚的中文给我看晕了，完全看不懂。。。
