### ISSUE TITLE
You can add a small neural network model to support translation into Russian

### ISSUE THREAD

**Issue by gqwg2003** [HIllya51/LunaTranslator#999]
### Expected behavior 预期的功

You can add a small neural network model to support translation into Russian

### Alternative behavior (optional) 近似的功能（可选）

I'm begging you.   Yes, I am grateful that you will read this, I know you write to everyone, answer, read, so I am very grateful to you, thank you for a good application

**Comment by HIllya51** [comment]
Where can I find such model? You should go find a deep learning expert in your country to do this.

**Comment by gqwg2003** [comment]
I am very grateful to you. I will find a person who will help to make such  And Yes, thank you very much for answering.

**Comment by HIllya51** [comment]
You should find the right person to do this instead of me.
Just like in our country, [SakuraLLM](https://github.com/SakuraLLM/SakuraLLM) creates a model, I can use his model. But I am unable to create a model.

**Comment by HIllya51** [comment]
This kind of thing can only be done at own's country. It is difficult for foreigners to do this, because it requires collecting a large number of domestic language data.

**Comment by gqwg2003** [comment]
I have a neural network that can translate from Russian to English from English to Russian You can install it here In the application 

https://github.com/ManiaCello/en-ru-onmt

**Comment by HIllya51** [comment]
First of all, this thing is too old. Things from 5 years ago are completely out of date. 
Secondly, it must provide an http interface for people to call, otherwise I can't do this.

**Comment by gqwg2003** [comment]
Okay, I'll look for it some more. I'll send you the link later.

**Comment by gqwg2003** [comment]
https://huggingface.co/Helsinki-NLP

**Comment by gqwg2003** [comment]
МодельS

**Comment by gqwg2003** [comment]
I looked there, there are collections of all languages

**Comment by gqwg2003** [comment]
https://github.com/Helsinki-NLP

**Comment by HIllya51** [comment]
**it must provide an http interface for people to call, otherwise I can't do this.**

**Comment by gqwg2003** [comment]
http interface I don't know how to find out if there is an interface for Or not May

**Comment by gqwg2003** [comment]
https://github.com/oobabooga/text-generation-webui  Does it support everything that is needed or not? The text generation interface. I don't know about this and the rest of the text generation. I don't know about the Russian language.

**Comment by gqwg2003** [comment]
She supports the Russian language

**Comment by HIllya51** [comment]
LunaTranslator already supported [tgw](https://github.com/oobabooga/text-generation-webui), you should find a ru model and load it by it, then input the url in ChatGPT Compatibble Interface.

**Comment by gqwg2003** [comment]
Bro, thank you so much  Bro, are you talking about this one? 
![Снимок экрана 2024-08-15 142334](https://github.com/user-attachments/assets/c1defa49-3f4d-44fc-bb42-736fb3044eb8)

**Comment by HIllya51** [comment]
😅can't understand

**Comment by HIllya51** [comment]
![屏幕截图 2024-08-15 192625](https://github.com/user-attachments/assets/f929a96b-86a2-4c64-8aa8-40da021c849d)

**Comment by gqwg2003** [comment]
https://pan.baidu.com/s/1fe7iiHIAtoXW80Twsrv8Nw?pwd=pato#list/path=%2F You're talking about this

**Comment by gqwg2003** [comment]
Can you send me a link to download it from?

**Comment by HIllya51** [comment]
**ChatGPT Compatibble Interface**

**Comment by gqwg2003** [comment]
Yes

**Comment by gqwg2003** [comment]
ChatGPT Compatibble Interface  I once looked for it myself and couldn't find it.

**Comment by HIllya51** [comment]
Using LLM is a difficult thing in itself. I can't help you, and you shouldn't ask me these questions anymore. You should learn it by yourself.

**Comment by gqwg2003** [comment]
I am very grateful for the answers.  https://github.com/SakuraLLM/SakuraLLM  Can you answer the last question, is this the model or not?

**Comment by HIllya51** [comment]
This model only support Chinese. It's of no use to you.

**Comment by gqwg2003** [comment]
I apologize very much to you for the questions. I understand that you have a lot of your own things to do.  Sorry for messing with your head, I'm just curious. I'm sick of needing the internet every time.  Well please offer a model with Russian language support I beg you very much and apologize to you

**Comment by gqwg2003** [comment]
I honestly don't know where to look for this model
![358205459-f929a96b-86a2-4c64-8aa8-40da021c849d](https://github.com/user-attachments/assets/bf8f6b1d-25da-496c-8d43-123b829bc714)

**Comment by HIllya51** [comment]
I have said it many times, you have to find the model yourself, where can I find it?
I'm also sick of answering such boring questions anymore.

**Comment by gqwg2003** [comment]
Thank you very much please don't be angry I'm just asking I don't know who to turn to I repeat once again I thank you very much for the app for the fact that you respond quickly and communicate
